swiftlang/swift-package-manager

Sources/PackageDescription/Version.swift
There is no need to leave duplicated code here.
=> Improve integer literal initializer for Specifier

Tests/dep/Fixtures/26_symlinked_sources_directory/Sources, Tests/dep/Fixtures/27_symlinked_nested_sources_directory/Sources
Change the symlinks in fixture to relative paths, or we have no chance to pass the tests unless changing user name to mxcl. :)
=> Change symlink to relative way

Sources/swift-build/usage.swift
It would be better to keep `TheSwitch` and `TheMode` to follow the same style.
=> Improve readability for Cruncher

Sources/dep/Error.swift
The dependency graph could not be satisifed
=> Minor typo fix

Documentation/DevelopingPackages.md
Add hard wrapping for the last two paragraph like the rest of the file
=> Uniform hard wrapping

Sources/dep/get.swift, Sources/dep/moduleNameForName.swift, Sources/sys/Path.swift, Sources/sys/StringExtensions.swift, Tests/dep/FunctionalBuildTests.swift, Tests/dep/VersionTests.swift
This PR fixes couple typos found in source code.
=> Bugfix - Couple typos

README.md
"less modules" should be "fewer modules"
=> Obnoxious grammar correction

Sources/dep/Package.swift
`convention-layot` -> `convention-layout`
=> Bugfix - Typo in comment

Sources/sys/TOML.swift, Tests/sys/TOMLTests.swift
See #53 for more.
This p-r removed the change on `consumeIf`.
=> Adding Float support for TOML

Sources/PackageDescription/Package.swift, Sources/PackageDescription/Target.swift
Add `TOMLable` protocol and move functions for covering an element to TOML format to it.
=> add TOMLable protocol

Documentation/Internals/SwiftBasedManifestFormat.md
Use swift code syntax. It provides better code highlighting on GitHub
=> swift code format

Documentation/Package.swift.md
This functionality added in PR #57
=> Add documentation how to exclude folders from Package

Tests/PackageDescription/PackageDescriptionTests.swift, Tests/dep/TargetTests.swift, Tests/sys/ShellTests.swift
While investigating approaches to [SR-32](https://bugs.swift.org/browse/SR-32), I came across a few more missing tests
=> Add a few more missing allTests entries

Sources/sys/Resources.swift
This p-r:
1. Refactoring for the internal properties, with a better name and reducing duplicated code.
2. Remove unnecessary `FIXME` according to discussion in #63
=> Improve for resource property

Tests/PackageDescription/PackageDescriptionTests.swift, Tests/XCTestCaseProvider/XCTestCaseProvider.swift, Tests/dep/DependencyGraphTests.swift, Tests/dep/FunctionalBuildTests.swift, Tests/dep/GetTests.swift, Tests/dep/ManifestTests.swift, Tests/dep/PackageTests.swift, Tests/dep/TargetTests.swift, Tests/dep/UidTests.swift, Tests/dep/VersionTests.swift, Tests/sys/FileTests.swift, Tests/sys/MiscTests.swift, Tests/sys/PathTests.swift, Tests/sys/ResourcesTests.swift, Tests/sys/ShellTests.swift, Tests/sys/StringTests.swift, Tests/sys/TOMLTests.swift
=> Change the rest of () -> () to () -> Void to match proper coding style

Sources/POSIX/popen.swift
Remove semicolon from Swift code
=> Remove semicolon

Sources/dep/Git.swift
Remove assigning "" value to root on failure
=> Remove assigning dummy "" value to root on failure

Sources/POSIX/system.swift
The `if var` expression stays in Swift, so let's use it :smiley:
=> Use if var

Sources/Build/describe().swift
Update variable names and comment to be a little more readable.
=> [Build] Document LinuxMain hack

Sources/Transmute/transmute().swift
Replace a double-negative condition (`guard !cond else { ... }`) with an `if` condition. Add documentation on the nature of the hack that needs a "FIXME".
---
I tried removing the condition altogether, but `Utilities/bootstrap test` still passed. Are there automated tests for the swiftpm testing support, or is that something that I can help out with?
=> [testing] Remove guard, document FIXME

Sources/PackageType/Module.swift
=> Refactor isLibrary method

Sources/Utility/ArrayExtensions.swift
=> Use where for filtering items in loop

Sources/Build/describe().swift
re-fixes https://bugs.swift.org/browse/SR-85
=> Add -g for products in debug conf

Documentation/SourceLayouts.md
Depends upon https://github.com/apple/swift-package-manager/pull/152
=> Update SourceLayouts.md - Tests directory

Sources/ManifestParser/TOML.swift, Sources/ManifestParser/fromTOML().swift, Sources/Utility/StringExtensions.swift, Tests/Transmute/ModuleTests.swift
Here are changes to a small set of things I noticed while traversing the code base.
=> Use more succinct code and constructs (nfc)

Sources/Build/describe().swift
Fixes https://bugs.swift.org/browse/SR-856
=> add Xcc for test exe on linux

README.md
=> [docs] Added a note about SWIFT_EXEC in the README

Utilities/bootstrap
https://bugs.swift.org/browse/SR-975
=> Fix SR-975

Sources/Xcodeproj/pbxproj().swift
Removed duplicate Tests folder in Sources introduced [here](https://github.com/apple/swift-package-manager/pull/190/files#diff-6e4ed61fe6a2b02d707327987e61c258R160) in #190.
=> [Xcodeproj] Removed duplicated Tests folder

Fixtures/Products/DynamicLibrary/Foo.swift, Fixtures/Products/DynamicLibrary/Package.swift, Fixtures/Products/StaticLibrary/Foo.swift, Fixtures/Products/StaticLibrary/Package.swift, Sources/Build/Command.compile(SwiftModule).swift, Sources/Build/Command.link().swift, Sources/Build/ToolProtocol.swift, Tests/Functional/TestMiscellaneous.swift
=> Use the new llbuild archive tool

Sources/swift-test/main.swift
Fix https://bugs.swift.org/browse/SR-1159
=> Use configuration on determine test path

Sources/Xcodeproj/Module+PBXProj.swift, Sources/Xcodeproj/generate().swift, Sources/Xcodeproj/pbxproj().swift, Sources/swift-build/main.swift, Tests/Xcodeproj/TestGeneration.swift
Resolves https://bugs.swift.org/browse/SR-1169
=> Xcode generation, Xlinker Xcc and Xswiftc options

Sources/Build/Command.link().swift
Fixes SR-1136
/cc @ddunbar @aciidb0mb3r
=> Ensure products rebuild when modules are modified

Sources/swift-build/--doctor.swift, Sources/swift-build/main.swift, Sources/swift-build/usage.swift
A command to help users troubleshoot and us to diagnose their troubles.
Currently barely anything is there, but we can add more as we go.
=> `swift build --doctor`

Sources/swift-build/main.swift, Sources/swift-build/usage.swift
It is the same as #234, but #234 has conflicts.
So, I tried to rewrite.
I just added `--update` as I was told at #233.
=> [swift-build] Add --update mode

Sources/PackageType/Module.swift, Sources/PackageType/c99name().swift, Sources/Transmute/Package+modules.swift, Sources/Transmute/Package+testModules.swift, Sources/swift-build/--init.swift, Sources/swift-build/Error.swift, Sources/swift-build/main.swift, Tests/Transmute/ModuleDependencyTests.swift, Tests/Xcodeproj/GenerateXcodeprojTests.swift
Fix https://bugs.swift.org/browse/SR-1224
=> validate package name in swift build --init

Sources/swift-build/main.swift
btw why not just `rmtree(dirs.build)`
=> Remove version data on --clean

Sources/Utility/Path.swift
- This avoids a lot of redundant allocation for the common case of path strings
which do not need to be cleaned.
- This is good for a ~10% speedup in the null build time of a SwiftPM on
itself.
=> [Utility] Add a fast path for Path.onesep.

Fixtures/DependencyResolution/External/Complex/FisherYates/src/Fisher-Yates_Shuffle.swift, Sources/Build/PkgConfig.swift, Sources/Get/Range.swift, Sources/ManifestParser/TOML.swift, Sources/OptionsParser/OptionsParser.swift, Sources/PackageDescription/Package.swift, Sources/PackageDescription/Version+StringLiteralConvertible.swift, Sources/PackageDescription/Version.swift, Sources/PackageType/Package.swift, Sources/Utility/CollectionExtensions.swift, Sources/Utility/Git.swift, Sources/Utility/Path.swift, Sources/Utility/StringExtensions.swift, Sources/libc/String+Linux.swift, Tests/Get/DependencyGraphTests.swift, Tests/Get/GetTests.swift, Tests/Transmute/ModuleDependencyTests.swift
This gets swiftpm building, but we can't run tests because XCTest is not ported yet.
=> Adjust for SE-0065 "A New Model for Collections and Indices"

Sources/Xcodeproj/pbxproj().swift
=> Tidy xcodeproj

Documentation/SourceLayouts.md
https://bugs.swift.org/browse/SR-1276
=> added sentence about linking of test suite and target

Sources/Get/RawClone.swift, Sources/POSIX/Error.swift, Sources/POSIX/ctime_r.swift, Sources/POSIX/getcwd.swift, Sources/POSIX/getenv.swift, Sources/POSIX/mkdtemp.swift, Sources/POSIX/realpath.swift, Sources/Utility/Git.swift
This commit fixes up swiftpm for when SE-0054 is merged into swift master. See https://github.com/apple/swift/pull/2322. Do not merge until that PR is merged.
=> Fix up swiftpm for abolition of IUO type in SE-0054.

Sources/swift-build/--show-dependencies.swift, Sources/swift-build/usage.swift
```bash
$ swift-build --show-dependencies json | jq '.'
{
"name": "app",
"url": "/private/tmp/bhargavg/testspm/app",
"version": "0.1.0",
"path": "/private/tmp/bhargavg/testspm/app",
"dependencies": [
{
"name": "Vapor",
"url": "https://github.com/qutheory/vapor",
"version": "0.7.1",
"path": "/private/tmp/bhargavg/testspm/app/Packages/Vapor-0.7.1",
"dependencies": [
{
"name": "S4",
"url": "https://github.com/open-swift/S4.git",
"version": "0.5.0",
"path": "/private/tmp/bhargavg/testspm/app/Packages/S4-0.5.0",
"dependencies": [
{
"name": "C7",
"url": "https://github.com/open-swift/C7.git",
"version": "0.6.0",
"path": "/private/tmp/bhargavg/testspm/app/Packages/C7-0.6.0",
"dependencies": []
}
]
},
{
"name": "String",
"url": "https://github.com/Zewo/String.git",
"version": "0.5.1",
"path": …
```
=> Add JSON dumper for dependencies

Tests/Functional/Utilities.swift, Tests/Xcodeproj/FunctionalTests.swift, Tests/Xcodeproj/GenerateXcodeprojTests.swift, Tests/Xcodeproj/Utilities.swift
This PR adds a very minimal test case which builds a fixture using xcodebuild. Once this is accepted I'll add few of the trick fixtures discovered recently.
Ref: #331 #330 SR-1444
=> [XcodeprojTestSuite] Generate xcodeproj of a fixture and build it using xcodebuild

Sources/PackageLoading/JSONSerialization.swift
This needs a synchronized merge with https://github.com/apple/swift-corelibs-foundation/pull/373 @parkera
=> Update NSJSONSerialization to new naming

Sources/PackageLoading/JSONSerialization.swift
Reverts apple/swift-package-manager#357
=> Revert "Update NSJSONSerialization to new naming"

Sources/Commands/init.swift
- This also adds more explicit variables to distinguish between where the
example package, module, and type names are used.
- Fixes: https://bugs.swift.org/browse/SR-1606
=> [SR-1606] [Commands] Fix warnings in template package.

Sources/Build/Command.compile(ClangModule).swift, Sources/PackageModel/Product.swift, Sources/Utility/misc.swift, Tests/Functional/ClangModuleTests.swift, Tests/Xcodeproj/FunctionalTests.swift
Fixes https://bugs.swift.org/browse/SR-1624
=> [ClangModule] Use correct extension for dynamic shared library on OSX

Sources/Build/Command.compile(ClangModule).swift, Sources/Build/Command.link(ClangModule).swift, Sources/Build/Command.link(SwiftModule).swift, Sources/Build/ToolProtocol.swift, Sources/Build/describe().swift, Sources/Build/misc.swift, Sources/PackageLoading/PackageExtensions.swift, Sources/PackageModel/Product.swift
Fixed the input dependencies of C family targets for swift modules.
=> [ClangModule] Use Product API to generate C language products.

Sources/Get/Git.swift, Sources/SourceControl/GitRepository.swift, Sources/Utility/Git.swift
Let swift build be aware of the http proxy variables.
=> Add https and http proxy support for fetch

Sources/Basic/JSON.swift, Sources/Basic/Lock.swift, Sources/Commands/SwiftTestTool.swift, Sources/Get/Git.swift, Sources/SourceControl/GitRepository.swift, Sources/Utility/File.swift, Sources/Utility/Git.swift, Sources/Utility/makeDirectories.swift, Sources/Utility/misc.swift, Sources/Utility/removeFileTree.swift, Tests/Utility/FileTests.swift
This is a work-in-progress update to build against Foundation's swift-3 branch and https://github.com/apple/swift-corelibs-xctest/pull/125
=> [WIP] Update for Swift 3.

Sources/Basic/TemporaryFile.swift, Tests/Basic/TemporaryFileTests.swift, Tests/Basic/XCTestManifests.swift
This class provides APIs to create and manage temporary disposable
files. It wraps posix's mkstemps method and adds additional
functionality on top of that.
=> [Basic] Add TemporaryFile class.

Sources/Commands/SwiftTestTool.swift
This option will allow skipping invoking llbuild to build the "test"
target when running swift test.
=> [SwiftTestTool] Add option --skip-build.

Sources/Basic/OrderedSet.swift, Tests/Basic/OrderedSetTests.swift, Tests/Basic/XCTestManifests.swift
- Based on code from Michael Rawdon.
=> [Basic] Add a basic native OrderedSet.

Sources/Basic/GraphAlgorithms.swift, Tests/Basic/GraphAlgorithmsTests.swift, Tests/Basic/XCTestManifests.swift
=> [Basic] Add a generic topologicalSort algorithm.

Sources/Basic/TemporaryFile.swift, Tests/Basic/TemporaryFileTests.swift
This class is a wrapper over POSIX's mkdtemp() function useful to create
disposable directories.
=> [Basic] Add TemporaryDirectory class.

Sources/Xcodeproj/TODO.md, Sources/Xcodeproj/xcscheme().swift
Is this what the TODO was for? Seems too easy to be true…
=> Enable code coverage

Sources/Basic/Thread.swift, Tests/Basic/ThreadTests.swift, Tests/Basic/XCTestManifests.swift
This class uses Foundation's Thread class to provide similar API on
Linux and OSX.
=> [Basic] Add Thread class.

Sources/Commands/SwiftBuildTool.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTestTool.swift, Sources/Commands/SwiftTool.swift, Sources/swift-build/main.swift, Sources/swift-test/main.swift
All the 3 swift tools have many in common. It would be nice to extract common logic in 1 place, in a  `SwiftTool`
Would love to hear your feedback.
=> [Commands] add common SwiftTool protocol

Fixtures/ClangModules/SwiftCMixed/Package.swift, Fixtures/ClangModules/SwiftCMixed/Sources/CExec/main.c, Sources/Build/Command.link(ClangModule).swift, Tests/Functional/ClangModuleTests.swift, Tests/Xcodeproj/FunctionalTests.swift
Bug: https://bugs.swift.org/browse/SR-1936
=> [Build] Set rpath to load C shared objects on linux

Sources/Basic/StringConversions.swift, Tests/Basic/StringConversionsPerfTests.swift, Tests/Basic/StringConversionsTests.swift, Tests/Basic/XCTestManifests.swift
=> [Basic] Add a method to create shell escaped strings.

Sources/Basic/SynchronizedQueue.swift, Tests/Basic/SynchronizedQueueTests.swift, Tests/Basic/XCTestManifests.swift
=> Add SynchronizedQueue class.

Sources/Commands/SwiftTestTool.swift
eg: Make test(path:xctestArg) non throwing.
This PR contains some minor refactor to SwiftTestTool, it will be useful for the parallel tests execution for the method to be run in parallel to be non throwing
=> [SwiftTestTool] Minor refactoring in SwiftTestTool

Sources/Utility/Error.swift
Based on a conversation with @aciidb0mb3r, I have removed a period versus adding periods in Error.swift.
Talk about silly commits/PRs =p
=> Removed period

Sources/Commands/Error.swift, Sources/POSIX/exit.swift, Sources/POSIX/getcwd.swift
Depends on https://github.com/apple/swift/pull/3658
=> Update for SE-0102 -- @noreturn attribute replaced with Never type

Sources/PackageLoading/ManifestLoader.swift
This is just a clean up since we don't need to create
a temporary file manually anymore.
=> [PackageLoading] Use TemporaryFile for writing toml

Tests/PackageLoading/ConventionTests.swift
Adopting PackageBuilderTester to change done in aee2407b2c0db8de492bbb90a31fd98ca62b8b4d
=> [Tests] Update APIs to take String instead of Path

Tests/PackageLoading/ConventionTests.swift
This has updates to PackageBuilderTests API
=> Update package builder tester

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoading/ConventionTests.swift
PackageBuilderTester found another bug 💃
=> [PackageBuilder] Fix crash on linux when there is only one test module and is C

Tests/PackageLoading/ConventionTests.swift
This migrates the existing convention tests to use PackageBuilderTester
=> Update convention tests

Sources/Commands/SwiftBuildTool.swift, Sources/Commands/SwiftTestTool.swift
- Just to be more consistent with `swift build`.
=> [Commands] Update swift-test to honor `-v` and `-color`.

Tests/Basic/OutputByteStreamPerfTests.swift, Tests/POSIX/ReaddirTests.swift
=> Minor changes due to SE-0130: Replace String.init(repeating: Character, count: Int) by String.init(repeating: Sttring, count: Int)

Package.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/ConventionTests.swift, Utilities/bootstrap
=> Allow test target dependencies in manifest file

Sources/Basic/PathShims.swift, Sources/Basic/TemporaryFile.swift, Sources/swiftpm-xctest-helper/main.swift, Tests/BasicTests/TemporaryFileTests.swift
this PR should be merged with apple/swift-corelibs-foundation#484
=> update uses of FileManager.default() on Linux to align with Darwin version

Sources/Basic/KeyedPair.swift, Tests/BasicTests/KeyedPairTests.swift, Tests/BasicTests/XCTestManifests.swift
=> [Basic] Add a KeyedPair type.

Sources/Basic/Condition.swift, Sources/Basic/Lock.swift, Sources/Basic/Thread.swift, Sources/Commands/SwiftTestTool.swift, Sources/Get/Git.swift, Sources/SourceControl/GitRepository.swift, Sources/Utility/Git.swift
Removes unnecessary typealiases by cherry-picking 5a462c6 and 74cb48a, which were committed to master
=> Integration of Swift 3 Foundation changes

Sources/Basic/Condition.swift, Sources/Basic/Lock.swift, Sources/Basic/Thread.swift, Sources/Commands/SwiftTestTool.swift, Sources/Get/Git.swift, Sources/SourceControl/GitRepository.swift, Sources/Utility/Git.swift
Integrated into master; this was a mistake on my part
=> Revert "Integration of Swift 3 Foundation changes"

Sources/Xcodeproj/Module+PBXProj.swift, Sources/Xcodeproj/pbxproj().swift
- Fixes https://bugs.swift.org/browse/SR-2488
=> [Xcodeproj] Add appropriate Debug/Release build settings.

Sources/Xcodeproj/pbxproj().swift
This patch adds support for nested groups in generated Xcode project.
Basically this:
**WIP:**
=> [Xcodeproj] Add support for nested groups

Sources/PackageLoading/ModuleMapGenerator.swift, Tests/FunctionalTests/MiscellaneousTests.swift
- https://bugs.swift.org/browse/SR-2613
=> [ModuleMapGen] Rewrite only if contents updated

Sources/PackageDescription/Version.swift
* Explanation: Removing integer overflow
* Scope of Issue: Fixing the existing issue
* Origination: Previous code assumed positive hashCode values
* Risk: Minimal
* Reviewed By: Dmitri Gribenko
* Testing: Running the test suite
* Directions for QA: N/A
rdar://problem/28266819
=> [swift-3.0-branch] Eliminating integer overflow in Version

Sources/SourceControl/CheckoutManager.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/CheckoutManagerTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift
Reverts apple/swift-package-manager#650
reverting for now because CI is unable to link dispatch
https://ci.swift.org//job/oss-swift-incremental-RA-linux-ubuntu-14_04/7404/consoleFull#105482183ee1a197b-acac-4b17-83cf-a53b95139a76
=> Revert "Add serial queue and fetch() to GitRepository"

Sources/SourceControl/CheckoutManager.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/CheckoutManagerTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift
=> Adds fetch()

Sources/Commands/Workspace.swift, Tests/CommandsTests/WorkspaceTests.swift
This method will resolve the dependency graph again and apply
update any dependencies if possible.
=> [Workspace] Add update dependencies method

Sources/Commands/SwiftPackageTool.swift
It is still hidden behind the --enable-new-resolver flag which is
expected to be removed once we make the switch to the new dep resolver.
=> [PackageTool] Add update cli for new resolver

Sources/Commands/SwiftTool.swift, Tests/FunctionalTests/VersionSpecificTests.swift
Sep these commits from #667 because of an issue in building on CI, will debug that particular commit separately
=> Misc changes to remove dependency on Packages/ dir

Package.swift, Sources/Xcodeproj/pbxproj().swift, Tests/XcodeprojTests/PackageGraphTests.swift, Tests/XcodeprojTests/XCTestManifests.swift
This adds some unit testing infrastructure to XcodeprojTest module to
test mock PackageGraphs on the Xcode.project model.
=> [Xcodeproj] Add unit testing infra

Sources/Commands/SwiftTool.swift, Sources/Commands/Workspace.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Sources/SourceControl/RepositoryManager.swift, Tests/CommandsTests/WorkspaceTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
The remove will first check if there are any uncommited changes and will
error out in that case, otherwise will go ahead with removal.
=> [SourceControl] Add remove() to Repository

Sources/TestSupport/SwiftPMProduct.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/ClangModuleTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/ValidLayoutTests.swift
<rdar://problem/28335393> Remove dependency on legacy Packages directory
After this the only dependency on Packages/ dir will be wrt clean
=> Remove dependency from Packages/ dir

Sources/Commands/SwiftTool.swift, Sources/Commands/Workspace.swift
=> [Workspace] Elimiate creating symlinks in Packages/

Tests/CommandsTests/WorkspaceTests.swift
This removes a lot of boilerplate needed for workspace tests.
=> [WorkspaceTests] Create mocking infra for creating manifest graphs

Utilities/bootstrap
=> [Bootstrap] Fix spaces in Xcode issue

Sources/Commands/Workspace.swift, Sources/SourceControl/GitRepository.swift, Tests/CommandsTests/WorkspaceTests.swift
=> [Workspace] Add edit(dependency:at:) method

Sources/Utility/ArgumentParser.swift, Tests/UtilityTests/ArgumentParserTests.swift, Tests/UtilityTests/XCTestManifests.swift
This class aims to be an improvement over the existing options parser.
=> [Basic] Add new ArgumentParser

Sources/Utility/ArgumentParser.swift, Tests/UtilityTests/ArgumentParserTests.swift
=> [ArgParser] Add parser usage text generation logic

Sources/PackageGraph/PackageGraphLoader.swift, Tests/PackageGraphTests/PackageGraphTests.swift
- https://bugs.swift.org/browse/SR-1723
=> [PackageGraphLoader] Detect cycles in package dependencies

Sources/Utility/ArgumentParser.swift, Tests/UtilityTests/ArgumentParserTests.swift
This class aims to be provide APIs to easily fill values in options
struct used with argument parser.
=> [ArgParser] Add ArgumentBinder

Sources/PackageLoading/Module+PkgConfig.swift, Sources/PackageModel/Module.swift
I think this was supposed to be killed long back but it was just hanging
around.
=> [PackageModel] Kill ModuleProtocol

Package.swift, Sources/POSIX/Error.swift, Sources/POSIX/env.swift, Tests/POSIXTests/EnvTests.swift
Separated from #744 as requested by @aciidb0mb3r.
=> POSIX setenv/unsetenv

Sources/Basic/Path.swift
- https://bugs.swift.org/browse/SR-3009
=> [Basic] Change PathImpl to internal for a compiler bug workaround

Utilities/bootstrap
This will allow installing in multiple locations.
Related radar: <rdar://problem/28703014>
=> [Bootstrap] Allow --prefix as array of strings

Fixtures/ClangModules/SwiftCMixed2/Package.swift, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaExec/main.swift, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/Foo.c, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/include/SeaLib/header1.h, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/include/SeaLib/header2.h, Sources/Build/Buildable.swift, Tests/FunctionalTests/ClangModuleTests.swift
- https://bugs.swift.org/browse/SR-3044
=> [Build] Add -I flag to include directory of a ClangModule dependency

Fixtures/ClangModules/SwiftCMixed2/Package.swift, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaExec/main.swift, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/Foo.c, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/include/SeaLib/header1.h, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/include/SeaLib/header2.h, Fixtures/Miscellaneous/ExecDependency/.gitignore, Fixtures/Miscellaneous/ExecDependency/Package.swift, Fixtures/Miscellaneous/ExecDependency/Sources/exec1/main.swift, Fixtures/Miscellaneous/ExecDependency/Sources/exec2/main.swift, Sources/Basic/GraphAlgorithms.swift, Sources/Build/Buildable.swift, Sources/Build/Command.link(SwiftModule).swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/BasicTests/GraphAlgorithmsTests.swift, Tests/FunctionalTests/ClangModuleTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageLoadingTests/ConventionTests.swift
These are misc fixes picked for Swift 3 branch
rdar://problem/28998272&28998299&28998370&28998416
=> [swift-3.0] Misc bug fixes

Sources/Xcodeproj/XcodeProjectModel.swift, Sources/Xcodeproj/generate().swift, Sources/Xcodeproj/pbxproj().swift, Tests/XcodeprojTests/PackageGraphTests.swift, Utilities/bootstrap
These are Xcode project generation related fixes picked for Swift 3 branch
rdar://problem/28998147&28998196&28998234&28998314&28998438&29022975
=> [swift-3.0] Xcodeproj bug fixes

Sources/Commands/SwiftBuildTool.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTool.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/CommandsTests/PackageToolTests.swift
and deprecate swift build --clean
- https://bugs.swift.org/browse/SR-2082
=> [Commands] Add swift package clean

Sources/Basic/FileSystem.swift, Tests/BasicTests/FileSystemTests.swift
This method creates a copy of an object of InMemory file system.
=> [Basic] Add copy() to InMem FS

Sources/Commands/PinsStore.swift, Tests/CommandsTests/PinsStoreTests.swift, Tests/CommandsTests/XCTestManifests.swift
This struct will be used to manage the Package.pins file, to add and
remove pins from the pins file.
=> [Commands] Add PinsStore struct

Sources/Commands/PinsStore.swift, Sources/Commands/Workspace.swift, Sources/SourceControl/InMemoryGitRepository.swift, Tests/CommandsTests/WorkspaceTests.swift
=> [Commands] Add pinning behavior in workspace

Sources/Commands/Error.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift
=> Add pinning cli

Tests/CommandsTests/PackageToolTests.swift
This test failed sometimes when there isn't enough time for llbuild to
realize that the file has changed. Checking the contents of
the working checkout is more deterministic.
- <rdar://problem/29301474> PackageToolTests.testPinning :
XCTAssertEqual failed: ("5") is not equal to ("6")
=> [PackageToolTest] Switch from building to checking contents of checkout

Sources/Xcodeproj/pbxproj().swift, Tests/XcodeprojTests/PackageGraphTests.swift
- https://bugs.swift.org/browse/SR-3133
=> [Xcodeproj] Enable wmo in release mode for generated Xcode projects

Sources/Commands/UserToolchain.swift, Tests/CommandsTests/UserToolchainTests.swift, Tests/CommandsTests/XCTestManifests.swift
- https://bugs.swift.org/browse/SR-3151
=> [Commands] Search for executables in PATH variable as fallback

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/ConventionTests.swift
Related radar: rdar://problem/29228963
=> [PackageBuilder] Disallow modulemap mixed with sources

Sources/Basic/StringConversions.swift, Tests/BasicTests/StringConversionsTests.swift
This has proven to be quite handy in number of places, so adding this to
Basic.
=> [Basic] Add repeating(n:) method to String

Documentation/Resources.md
- https://bugs.swift.org/browse/SR-3243
=> [Documentation] How to file good SwiftPM bug

Sources/Xcodeproj/pbxproj().swift, Tests/XcodeprojTests/PackageGraphTests.swift
- https://bugs.swift.org/browse/SR-3264
=> [Xcodeproj] Fix generated modulemap path in build settings

Sources/Utility/Platform.swift
=> [Utility] Inherit env when using xcrun to find platform path

Sources/Commands/SwiftPackageResolveTool.swift, Sources/Commands/SwiftPackageTool.swift, Sources/PackageGraph/DependencyResolver.swift
This adds option to to dump resolution information in JSON format in the
hidden resolve tool.
=> [ResolveTool] Add an json dumping option

Sources/PackageGraph/DependencyResolver.swift, Sources/TestSupport/MockDependencyResolver.swift, Tests/PackageGraphTests/DependencyResolverTests.swift
- https://bugs.swift.org/browse/SR-3239
=> [Resolver] Fix bug where all the valid versions were being iterated

Fixtures/Miscellaneous/PkgConfig/SystemModuleUserClang/Package.swift, Fixtures/Miscellaneous/PkgConfig/SystemModuleUserClang/Sources/main.c, Sources/Build/Command.compile(ClangModule).swift, Sources/Build/Command.link(ClangModule).swift, Tests/FunctionalTests/MiscellaneousTests.swift
=> [Build] Pass pkgconfig args when compiling ClangModule

Sources/PackageLoading/Module+PkgConfig.swift, Tests/PackageLoadingTests/WhitelistTests.swift
- https://bugs.swift.org/browse/SR-3129
=> [PkgConfig] Remove default search paths which are added by compiler

Sources/Xcodeproj/XcodeProjectModel.swift, Sources/Xcodeproj/pbxproj().swift, Tests/XcodeprojTests/PackageGraphTests.swift
Fix https://bugs.swift.org/browse/SR-3375
=> [Xcodeproj] Add “SKIP_INSTALL = YES” to framework target

Sources/PackageGraph/PackageGraphLoader.swift, Sources/Utility/CollectionExtensions.swift, Tests/UtilityTests/CollectionTests.swift
This is follow on from https://github.com/apple/swift-package-manager/pull/844
=> [Utility] Add split(isMatching:) to Collection Extensions

Sources/Commands/Error.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/Package.swift, Tests/GetTests/GetTests.swift, Tests/PackageLoadingTests/ManifestTests.swift
=> [ManifestLoader] Improve error message when there is no manifest

Sources/Commands/SwiftPackageTool.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift
- <rdar://problem/29772779> Poor diagnostic with `package edit` when
package doesn't resolve
=> [Commands] Always resolve graph before edit

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- <rdar://problem/29730923> Add unregister paths API to Workspace
=> [Workspace] Add unregister package path API

Sources/Commands/UserToolchain.swift
Small typo fixes in docstrings.
=> Fix typos.

Fixtures/Products/DynamicLibrary/Package.swift, Fixtures/Products/StaticLibrary/Package.swift, Package.swift, Sources/PackageDescription/Package.swift, Sources/PackageDescription/Product.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Product.swift, Sources/TestSupport/MockDependencyGraph.swift, Sources/TestSupport/misc.swift, Tests/BuildTests/DescribeTests.swift, Tests/GetTests/GitTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/ConventionTests.swift, Tests/PackageLoadingTests/JSONSerializationTests.swift, Tests/PackageLoadingTests/ManifestTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Utilities/bootstrap
=> [PackageDescription] Add new product API

Sources/PackageGraph/DependencyResolver.swift, Sources/SourceControl/Repository.swift
Add CustomStringConvertible conformance to RepositorySpecifier and
CustomStringConvertible
=> Add description property to some types for debugging

Sources/Utility/ProcessSet.swift, Tests/UtilityTests/ProcessSetTests.swift, Tests/UtilityTests/XCTestManifests.swift, Tests/UtilityTests/processInputs/blocking, Tests/UtilityTests/processInputs/blocking-ignore-sigint
This class is used to manage a set of processes.
=> [Utility] Add ProcessSet class

Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/Foo.c, Fixtures/ClangModules/SwiftCMixed2/Sources/SeaLib/include/module.modulemap, Tests/FunctionalTests/ClangModuleTests.swift
=> [ClangModuleTests] Add a custom modulemap test

Sources/Commands/SwiftPackageTool.swift
When we landed this, the proposal was still in review so this got left out.
=> [SwiftPackageTool] Add pinning help text

Documentation/Usage.md, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift
This will let users use clone repos in parallel by passing
--enable-prefetching flag.
=> [SwiftTool] Add cli option to enable prefetching in resolver

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- <rdar://problem/29944464> Package manager fails to do dependency
resolution if some package is in edit mode
=> [Workspace] Fix dependency resolution in edit mode

Tests/FunctionalTests/ClangModuleTests.swift
We can't assert for dylib anymore because we will not always create
them.
=> [Tests] Remove dylib asserts

Sources/Build/BuildPlan.swift, Sources/Build/Buildable.swift, Sources/Build/llbuild.swift, Sources/Commands/SwiftTestTool.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Product.swift, Tests/PackageLoadingTests/ConventionTests.swift
Since this is no longer in public API change the cases according to
swift 3 API guidelines.
=> [Product] Make product type cases as lower case

Sources/Commands/Describe.swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Package.swift, Tests/PackageLoadingTests/ConventionTests.swift
We don't really need this to be separate.
=> [PackageModel] Remove separate testModule array

Sources/Build/BuildPlan.swift, Sources/Commands/SwiftTestTool.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/Xcodeproj/pbxproj().swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageLoadingTests/ConventionTests.swift, Tests/PackageLoadingTests/ManifestTests.swift
Decide if we want to build them at a higher level
=> [PackageLoading] Always create test modules

Sources/Utility/Process.swift, Sources/Utility/ProcessSet.swift, Tests/UtilityTests/ProcessTests.swift
- https://bugs.swift.org/browse/SR-3625
=> [Utility] Added thread safety to Process.

Fixtures/Miscellaneous/Spaces Fixture/Tests/Moudule Tests/Foo.swift, Sources/Build/BuildPlan.swift, Sources/Build/llbuild.swift, Sources/PackageModel/Module.swift, Sources/PackageModel/Product.swift, Sources/PackageModel/ResolvedModels.swift, Tests/BuildTests/BuildPlanTests.swift
- https://bugs.swift.org/browse/SR-3877
=> Compile LinuxMain.swift as a swift target

Utilities/bootstrap
Create a class to write manifests and run llbuild.
=> [Bootstrap] Make llbuild usage more structured

Package.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/TestSupport/Resources.swift, Utilities/bootstrap
=> PackageDescription 4 🎉

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageLoading/VersionShim.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Module.swift, Sources/TestSupport/MockDependencyGraph.swift, Sources/TestSupport/MockManifestLoader.swift, Sources/TestSupport/misc.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift, Tests/PackageLoadingTests/ConventionTests.swift, Tests/PackageLoadingTests/ManifestTests.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift, Tests/PackageLoadingTests/VersionShimTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
This will allow us to specify the manifest version we want to load.
=> Add manifest version to manifest loader

Sources/PackageDescription4/Package.swift, Sources/PackageDescription4/Target.swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Module.swift, Sources/TestSupport/misc.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageLoadingTests/ConventionTests.swift, Tests/PackageLoadingTests/ManifestTests.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift
Needs a little cleanup and tests but this is it 🎉
=> Finish product proposal 🎉🎉🎉🎉🎉🎉🎉

Tests/FunctionalTests/ToolsVersionTests.swift, Tests/FunctionalTests/XCTestManifests.swift
=> Func test tools version 3.1 branch

Sources/Build/ToolProtocol.swift
This sometimes causes things to rebuild on linux when nothing has changed.
- https://bugs.swift.org/browse/SR-4034
=> [Build] Sort the command inputs before writing

Sources/Utility/Git.swift
https://bugs.swift.org/browse/SR-4040
=> [Utility] Allow setting a custom path for the git executable

Sources/PackageDescription4/Package.swift, Sources/PackageGraph/RawPackageConstraints.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/Utility/Git.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift
This adds support for declaring branches for dependencies in the new manifest.
=> [PD4] Add branch support

Sources/SourceControl/GitRepository.swift
These fit our purpose more and implies bare by default.
=> [SourceControl] use mirror repository instead of bare

Sources/Utility/ArgumentParser.swift, Tests/UtilityTests/ArgumentParserTests.swift
- https://bugs.swift.org/browse/SR-4120
=> [Utility] Display --help option in usage for top level commands

Sources/PackageModel/Manifest.swift
Spotted the typo while reading the code - thought I'd just make a quick fix for it
=> fixing a minor typo in err message

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- https://bugs.swift.org/browse/SR-4061
=> [Workspace] Check revision before editing a package

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [Workspace] Make managed dependencies reloadable

Sources/Commands/SwiftPackageTool.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
-- - <rdar://problem/30976982>
=> [Workspace] Use reloadable result on pinsstore

Sources/Basic/DiagnosticsEngine.swift, Sources/Commands/Error.swift, Sources/Commands/SwiftPackageResolveTool.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTool.swift, Sources/TestSupport/misc.swift, Sources/Utility/Diagnostics.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/ToolsVersionTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [Workspace] Use diagnostic engine for errors

Sources/Commands/SwiftTool.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/TestSupport/misc.swift, Sources/Workspace/Workspace.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift, Tests/XcodeprojTests/PackageGraphTests.swift
=> [PackageGraph] Use DiagnosticEngine for error in package graph

Sources/Commands/UserToolchain.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/TestSupport/Resources.swift, Utilities/bootstrap, Utilities/sandbox/parse-manifest.sb
=> [PackageLoading] Execute manifest parsing within a sandbox

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- resolves [SR-4261](http://bugs.swift.org/browse/SR-4261)
- verified (manually) this resolves the issue of `pin` command failing
- added unit test that invokes use case from the bug to protect against regression
=> [Bugfix] SR-4261

Sources/PackageGraph/DependencyResolver.swift, Tests/PackageGraphTests/DependencyResolverTests.swift
This mode lets the resolver run without fetching the containers which
it doesn't already have. This is useful when we want to run the resolver
with different sets of constraints without going off cloning a lot of
new repositories which might be unnecessary.
This, with delta debugging algo, will eventually let us diagnose the
unresolvable package graphs.
=> [PackageGraph] Add incomplete mode to resolver

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
This caching was taking a major performance hit because we were always resolving
the tags and revision before getting to the cached dependencies. This lead to
shelling out 1-2 times even when cached data is readily available. This patch
increased the resolution time by 5x for `perfect` package.
=> [PackageGraph] Cache dependencies by identifier

Sources/PackageLoading/ManifestLoader.swift
Reverts apple/swift-package-manager#1032
=> Revert "[ManifestLoader] Further restrict the sandbox profile"

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> Re-clone checkouts when folder missing

Sources/PackageLoading/ManifestLoader.swift, Sources/Utility/Platform.swift
Remove (allow mach*) and import system.sb
-- <rdar://problem/31213658> Further restrict SwiftPM's sandbox
=> [ManifestLoader] Restrict the sandbox profile

Sources/Basic/DiagnosticsEngine.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Also slightly improved the implementation to not have to iterate over the whole array.
=> Make DiagnosticsEngine.hasError into a property

Sources/PackageGraph/DependencyResolver.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/DependencyResolverTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
-- <rdar://problem/31022815>
-- https://bugs.swift.org/browse/SR-4072
=> [PackageGraph] Add diagnostics for unresolvable graphs

Sources/Workspace/Workspace.swift
This isn't needed or correct anymore.
-- <rdar://problem/31535055>
=> [Workspace] Remove at least 1 root package precondition

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderV4Tests.swift
This should complete the implementation of target proposal.
-- https://bugs.swift.org/browse/SR-29
-- <rdar://problem/28039974>
=> [PackageBuilder] Add support for Target's path, source and exclude

Sources/Workspace/ManagedDependency.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
-- <rdar://problem/31573297> ManagedDependency should store the name of the package
=> [Workspace] Add name property to ManagedDependency

Sources/PackageGraph/PackageGraphRoot.swift, Sources/PackageGraph/RawPackageConstraints.swift, Sources/PackageLoading/VersionShim.swift, Sources/Workspace/WorkspaceRoot.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [PackageGraph] Use Requirement from PD4 for PackageGraphRoot

Utilities/bootstrap
-- <rdar://problem/31582096> Fix C support in bootstrap script
=> [Bootstrap] Fix C support in bootstrap

Sources/Workspace/Workspace.swift
The different extensions correspond to:
* editing functions
* pinning functions
* utility functions
* dependency management
* repository management
=> Split Workspace into extensions for each responsability

Sources/Workspace/Workspace.swift
We will no longer crash if an edited package has a manifest parse error.
- <rdar://problem/31085712> [SR-4262]: SwiftPM crashes when an edited package manifest is invalid
- https://bugs.swift.org/browse/SR-4262
=> [Workspace] Remove bang from loadManifest(forDependency)

Package.swift, Sources/Build/BuildPlan.swift, Sources/Commands/SwiftTool.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Module.swift, Sources/Utility/Versioning.swift, Sources/Workspace/InitPackage.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/ToolsVersionTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/PackageBuilderV4Tests.swift, Tests/PackageModelTests/ModuleTests.swift, Tests/WorkspaceTests/InitTests.swift
-- <rdar://problem/31711945> Update SwiftPM version to 4 and pass -swift-version flag to compiler
=> Update tools version to 4.0

Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [Workspace] Include path in checkingOut() delegate

Sources/PackageLoading/ManifestLoader.swift
-- <rdar://problem/31776754> Compute SDKROOT in manifest loader if not provided in resources
=> [ManifestLoader] Look for sdk root if not present in resources

Sources/Workspace/Workspace.swift
=> [Workspace] Make some APIs public

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/Manifest.swift, Tests/PackageLoadingTests/ManifestTests.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift
-- <rdar://problem/31840892> Store the manifest version in Manifest model
=> [PackageLoading] Add manifest version property to Manifest

Sources/Utility/SimplePersistence.swift, Sources/Workspace/ManagedDependency.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [Workspace] Don't write blank managed dependencies state file

Sources/Commands/Error.swift
-- <rdar://problem/31888791> Diagnostic for swift-tools-version should show tools-version subcommand
=> [SwiftTool] Display fixit for fixing invalid tools version

Sources/Commands/SwiftPackageResolveTool.swift, Sources/Commands/SwiftTool.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
-- <rdar://problem/31930269> Provide explicit delegate for fetchingDidBegin and fetchingDidFinish from Workspace
=> [Workspace] Add delegate fetchingDidFinish

Sources/PackageGraph/PackageGraphLoader.swift
=> [PackageGraphLoader] Correct the location of diagnostics

Sources/Utility/SimplePersistence.swift, Tests/UtilityTests/SimplePersistenceTests.swift
-- <rdar://problem/31983014> Do not overwrite any extra key present in SimplePersistence state file
=> [Utility] Do not overwrite any extra key in SimplePersistence state file

Sources/Commands/Error.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Workspace/PinsStore.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
This removes repin, unpin and autopinning.
=> [Workspace] Remove several pinning related behaviors

Tests/BasicPerformanceTests/SHA256PerfTests.swift
Just a simple performance test for the new SHA256 class.
=> [Basic] Add performance tests for SHA256.

Tests/WorkspaceTests/WorkspaceTests.swift
Reverts apple/swift-package-manager#1172
=> Revert "[WorkspaceTests] Disable branch and revision test"

Sources/Basic/CollectionAlgorithms.swift, Tests/BasicTests/CollectionAlgorithmsTests.swift
Add `findDuplicates` method and its tests
=> [Basic] Add findDuplicates to CollectionsAlgorithms

Sources/PackageLoading/ManifestLoader.swift, Sources/Workspace/Diagnostics.swift
=> [PackageLoading] Improve error message for empty manifests

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift
-- <rdar://problem/32286386> Turn on parallel cloning by default
=> [Resolver] Turn on parallel cloning by default

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift
Reverts apple/swift-package-manager#1193
=> Revert "[Resolver] Turn on parallel cloning by default"

Sources/Basic/OutputByteStream.swift, Tests/BasicTests/OutputByteStreamTests.swift
-- <rdar://problem/32315728> Make stdoutStream and stderrStream thread safe
=> [Basic] OutputByteStream Make OutputByteStream thread safe

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift
Reverts apple/swift-package-manager#1200
=> Revert "Revert "[Resolver] Turn on parallel cloning by default""

Utilities/bootstrap
=> [bootstrap] Remove hardcoded stdlib rpath in libSwiftPM

Sources/SourceControl/GitRepository.swift, Tests/SourceControlTests/GitRepositoryTests.swift
Reverts apple/swift-package-manager#1201
=> Revert "FIX: hasUnpushedCommits for detatched HEAD"

Package.swift, Utilities/bootstrap
This will allow us to vend libSwiftPM as a package dependency!
=> [Package.swift] Move SwiftPM to new manifest version

Sources/PackageGraph/DependencyResolver.swift, Sources/SourceControl/Repository.swift, Tests/PackageGraphTests/DependencyResolverTests.swift
-- <rdar://problem/32058400> [SR-5000]: Bad Error message when a Package depends on a package which depends on a branch of another package.
-- https://bugs.swift.org/browse/SR-5000
=> [PackageGraph] Add description for DependencyResolverError

Sources/Xcodeproj/pbxproj().swift
-- <rdar://problem/32494304> Generate SWIFT_VERSION build settings
=> [Xcodeproj] Set correct SWIFT_VERSION in generated project

Sources/Basic/FileSystem.swift, Sources/SourceControl/InMemoryGitRepository.swift, Sources/SourceControl/RepositoryManager.swift, Sources/TestSupport/misc.swift, Sources/Workspace/Workspace.swift, Tests/BasicTests/FileSystemTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [Basic] Make remove dir throwing

Sources/Build/BuildPlan.swift, Sources/Commands/SwiftTool.swift, Sources/Utility/BuildFlags.swift
-- https://bugs.swift.org/browse/SR-5270
-- <rdar://problem/32875320> [SR-5270]: Add -Xcxx option
=> [Build] Add -Xcxx option to pass C++ only flags

Sources/Workspace/Workspace.swift
-- https://bugs.swift.org/browse/SR-5307
=> [Workspace] Fix revision logic when computing package state changes

Sources/Commands/SwiftBuildTool.swift, Tests/CommandsTests/BuildToolTests.swift
Resolves [SR-5259](https://bugs.swift.org/browse/SR-5259)
=> Add the `—bin-path` option to `swift build`

Sources/Commands/SwiftTestTool.swift
-- https://bugs.swift.org/browse/SR-5334
=> [SwiftTestTool] Compute test case list only if necessary.

Sources/Commands/SwiftRunTool.swift, Sources/Commands/UserToolchain.swift, Tests/CommandsTests/RunToolTests.swift, Utilities/bootstrap
https://bugs.swift.org/browse/SR-5332
=> Redirect `swift run file.swift` to `swift file.swift`

Fixtures/Miscellaneous/EchoExecutable/Sources/secho/main.swift, Sources/Commands/SwiftRunTool.swift, Tests/CommandsTests/RunToolTests.swift
Resolves [SR-5394](https://bugs.swift.org/browse/SR-5394)
=> Reset working directory before swift run

Sources/Commands/SwiftTool.swift
This creates a new directory under TMPDIR with complete access in the
sandbox.
-- <rdar://problem/33378806> [SR-5491]: LLVM ERROR: IO failure on output stream.
-- https://bugs.swift.org/browse/SR-5061
=> [Commands] Override TMPDIR when shelling out llbuild

Sources/Build/BuildPlan.swift, Sources/Build/Toolchain.swift, Sources/PackageDescription4/CXXLanguageStandard.swift, Sources/PackageDescription4/Package.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Module.swift, Sources/PackageModel/Sources.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/PackageLoadingTests/ModuleMapGenerationTests.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift
https://github.com/apple/swift-evolution/blob/master/proposals/0181-package-manager-cpp-language-version.md
=> Implement SE-0181: C/C++ language standard

Sources/Xcodeproj/pbxproj().swift
-- <rdar://problem/33420045> Generated Xcode project does not include source for dependencies
=> [Xcodeproj] Avoid creating a group if no target needs to be built

Sources/PackageDescription/Version.swift, Sources/PackageDescription4/Version.swift, Sources/Utility/Version.swift
Based on the [latest revision of SE-0104](https://github.com/apple/swift-evolution/blob/91f8ed0620e438712e5d72b20a65a68d6e0a8a1d/proposals/0104-improved-integers.md).
See https://github.com/apple/swift/pull/11203.
=> Reflect changes to the integer types

Sources/PackageDescription/Version.swift, Sources/PackageDescription4/Version.swift, Sources/Utility/Version.swift
Cherry-picked: https://github.com/apple/swift-package-manager/pull/1289 to unblock CI.
=> [Swift 4.0] Reflect changes to the integer types

Documentation/PackageDescriptionV4.md
Edits suggested by @xwu in #1307.
=> Grammar edits to v4 PackageDescription API doc

Sources/Basic/FileSystem.swift, Sources/Basic/Path.swift, Sources/Basic/SHA256.swift, Sources/Basic/misc.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftRunTool.swift, Sources/PackageDescription/Package.swift, Sources/PackageDescription/Version+StringLiteralConvertible.swift, Sources/PackageDescription4/Package.swift, Sources/PackageDescription4/Version+StringLiteralConvertible.swift, Sources/PackageGraph/PackageGraphRoot.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Module.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SourceControl/GitRepository.swift, Sources/Utility/ArgumentParser.swift, Sources/Utility/ArgumentParserShellCompletion.swift, Sources/Utility/Git.swift, Sources/Utility/PkgConfig.swift, Sources/Utility/StringExtensions.swift, Sources/Utility/Version.swift, Sources/Xcodeproj/pbxproj().swift, Tests/BasicTests/CollectionAlgorithmsTests.swift, Tests/BasicTests/ProcessTests.swift, Tests/PackageLoadingTests/ModuleMapGenerationTests.swift, Tests/XcodeprojTests/PackageGraphTests.swift
=> Use String instead of CharacterView

Tests/BuildTests/BuildPlanTests.swift
Apparantely we had no test which has an external test target.
- <rdar://problem/33633549> Land a test that would have caught https://bugs.swift.org/browse/SR-5595
=> [BuildTests] Add a test with an external test target

Sources/Build/Command.swift, Sources/Build/llbuild.swift, Tests/BuildTests/IncrementalBuildTests.swift
- <rdar://problem/33857016> Manifest file is not deterministic
=> [Build] Emit a stable llbuild manifest

Documentation/PackageDescriptionV4.md
=> Minor typo fix for PackageDescriptionV4.md

Documentation/Development.md
Include the platform name in the binary path as we expect to find
things relative to that.
-- https://bugs.swift.org/browse/SR-5801
=> [Documentation] Update Development.md

Sources/PackageGraph/PackageGraphLoader.swift, Tests/PackageGraphTests/PackageGraphTests.swift
The Swift 4 package manager does not have the package identity concept
so it is possible for two packages to have the same name. It may or may
not cause issues in practice but we should diagnose and report such
things.
- https://bugs.swift.org/browse/SR-5728
- <rdar://problem/34008219> [SR-5728]: Manifest duplicate command in 'commands' map
=> [PackageGraph] Diagnose duplicate manifests

Sources/Commands/SwiftTestTool.swift
- https://bugs.swift.org/browse/SR-4754
- <rdar://problem/31940383> [SR-4754]: [XCTest] Non-zero exit without further output
=> [SwiftTestTool] Print message when text exits via signal

Tests/WorkspaceTests/WorkspaceTests2.swift
Don't create a new repository if a package is mentioned again, otherwise
we end up losing the previous tags.
=> [WorkspaceTests] Minor fix in the new testing infra

Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/WorkspaceTests2.swift
Migration to new testing infra
=> [WorkspaceTests] Migrate testCanResolveWithIncompatiblePins

Sources/Build/BuildPlan.swift, Sources/Build/Triple.swift, Sources/Commands/Destination.swift, Sources/Commands/SwiftTool.swift
Conditions in BuildPlan should rely on destination OS.
Not on host
=> Tests cross-compilation support

Tests/XcodeprojTests/FunctionalTests.swift
=> [Tests] Disable few test causing failures due to a compiler change

Tests/XcodeprojTests/FunctionalTests.swift
This will keep the compiler and Swift library consistent during the
tests.
- <rdar://problem/34791474> Use the built Swift standard library in the generated Xcode project tests
=> [XcodeprojTests] Override SWIFT_LIBRARY_PATH in tests

Documentation/Resources.md
This seemed like the right spot for this- please feel free to suggest alternatives!
=> Document verbose flag when performing an update

Documentation/Usage.md
Replace explicit call to executable with the new "swift run" command
=> Add swift run command

Sources/Commands/SwiftTestTool.swift
=> [TestTool] Specify SDK on macOS when running the XCTest bundle

Sources/Workspace/PinsStore.swift, Tests/WorkspaceTests/PinsStoreTests.swift
- <rdar://problem/34186002> [SR-5843]: SwiftPM needs to be resilient to schema changes
=> [PinsStore] Add support for loading PinsStore schema 1 

Sources/Build/BuildPlan.swift
- https://bugs.swift.org/browse/SR-6164
=> [BuildPlan] Move -X* args to the end of the constructed args

Sources/Utility/PkgConfig.swift, Tests/PackageLoadingTests/Inputs/Foo.pc, Tests/PackageLoadingTests/PkgConfigTests.swift, Tests/UtilityTests/PkgConfigParserTests.swift
- https://bugs.swift.org/browse/SR-6172
=> [PkgConfig] Add support for pcfiledir

Utilities/bootstrap
- https://bugs.swift.org/browse/SR-5980
=> [bootstrap] Fix rpath for PD libs on linux

Sources/Xcodeproj/pbxproj().swift
- https://bugs.swift.org/browse/SR-6212
=> [Xcodeproj] Add pkgconfig cflags to other_cflags

Documentation/Development.md, Documentation/Usage.md
Very minor spelling corrections (+1 minor rewording) I made while reading through the documentation.
=> A few minor spelling errors and slight rewording

Sources/Basic/OutputByteStream.swift
Reverts apple/swift-package-manager#1397
=> Revert "Fix recursive constraint warnings"

Sources/Commands/Error.swift, Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Product.swift, Sources/Utility/Diagnostics.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageLoadingTests/PackageBuilderV4Tests.swift
- <rdar://problem/34494792> [SR-5918]: SwiftPM should error out when there are two products with same name
- https://bugs.swift.org/browse/SR-5918
=> [PackageLoading] Detect and warn about duplicate products

Sources/Utility/CollectionExtensions.swift, Sources/Xcodeproj/pbxproj().swift, Tests/UtilityTests/CollectionTests.swift
Fix [SR-6523](https://bugs.swift.org/browse/SR-6523)
=> Use `Collection.partition(by:)` and remove `Collection.split(_:)`

Sources/PackageGraph/PackageGraphLoader.swift, Tests/PackageGraphTests/PackageGraphTests.swift
=> [PackageGraph] Don't emit unused warning for system module deps

Sources/SourceControl/GitRepository.swift, Tests/SourceControlTests/GitRepositoryTests.swift
Fix https://bugs.swift.org/browse/SR-5437 by @ghn and me at SwiftAlps
=> [SR-5437] Check for untracked files

Sources/PackageLoading/PackageDescription4Loader.swift
=> [PackageLoading] Don't try to fix URLs of remote packages

Tests/PackageGraphTests/PackageGraphTests.swift
From [SR-4859](https://bugs.swift.org/browse/SR-4859):
> I suspect our logic for finding duplicate target name across the package graph is broken. We should be able to find the duplicate target names in the following graph:
> 
> Root:
> &nbsp;&nbsp;&nbsp;&nbsp;Tagets: Foo Bar
> &nbsp;&nbsp;&nbsp;&nbsp;Dependencies: Dep1
>
> Dep1:
> &nbsp;&nbsp;&nbsp;&nbsp;Targets: Baz
> &nbsp;&nbsp;&nbsp;&nbsp;Dependencies: Dep2
>
> Dep2:
> &nbsp;&nbsp;&nbsp;&nbsp;Targets: Foo, Bam
> &nbsp;&nbsp;&nbsp;&nbsp;Dependencies: []
>
> If this is in fact broken, we need to fix this in PackageGraphLoader and add appropriate test case.
I don't think there actually is a bug, it outputs as expected. Perhaps there is an alternative test case @aciidb0mb3r ?
=> Check for failure on dupicate external target names [SR-4859]

Sources/Workspace/PinsStore.swift
- <rdar://problem/36094461> SwiftPM needs to write Package.resolved version 1, until tools version is > 4.0
=> [Workspace] Revert resolved file to schema 1

Utilities/bootstrap
<rdar://problem/36301561> Make sure we are building optimized PackageDescription
=> [Bootstrap] Build runtimes in release mode

Documentation/Usage.md
- <rdar://problem/35457967> [SR-5560]: SwiftPM documentation still talks about pinning
=> [Documentation] Add documentation about Package.resolved

Sources/SourceControl/GitRepository.swift, Sources/SourceControl/InMemoryGitRepository.swift, Sources/SourceControl/Repository.swift, Sources/Workspace/Workspace.swift, Tests/SourceControlTests/GitRepositoryTests.swift
- <rdar://problem/33611360> Unexpected error about staging checkout having uncommited changes
This will avoid weird error if the build directory is moved by the user.
=> [Workspace] Ensure bare repository of a checkout is present

Documentation/Usage.md
Update example usage for latest swift package syntax
=> generate completion script

Sources/Basic/Process.swift, Sources/PackageDescription4/Package.swift, Sources/PackageDescription4/PackageRequirement.swift, Sources/PackageModel/Product.swift, Sources/Workspace/CheckoutState.swift, Sources/Workspace/Workspace.swift, Tests/BasicTests/JSONMapperTests.swift
This reverts commit 97268761c6e38ed2e8f6bd51b86513be08afa44f.
=> Revert "Remove Equatable implementation where compiler can generate it"

Sources/Utility/Platform.swift
Switch to using confstr API instead of shelling out which makes every
swiftpm tool ~30ms faster on macOS.
=> Make SwiftPM 30 ms faster on macOS!

Sources/Basic/CacheableSequence.swift, Tests/BasicTests/CacheableSequenceTests.swift, Tests/BasicTests/XCTestManifests.swift
- This adapts an arbitrary sequence to one which can be consumed multiple
times.
- I'm open to suggestions on a better name.
=> [Basic] Add a CacheableSequence.

Sources/Build/BuildPlan.swift, Sources/Build/llbuild.swift, Sources/PackageLoading/ModuleMapGenerator.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/Target+PkgConfig.swift, Sources/PackageModel/Target.swift, Sources/Xcodeproj/pbxproj().swift, Tests/PackageLoadingTests/PkgConfigTests.swift
=>  [PackageModel] Rename CTarget to SystemLibraryTarget.

README.md
Solution for the [SR-6974](https://bugs.swift.org/browse/SR-6974)
=> [SR-6974] Added Link To usage Page And Quick Help Command

Sources/Basic/TerminalController.swift, Sources/Build/Triple.swift, Utilities/bootstrap
This file contains changes required to build and use it on ppc64le platform.
=> ppc64le port.

Sources/Utility/Versioning.swift
<rdar://problem/37031208> Bump SwiftPM version to 4.2
=> [Utility] Update version to 4.2.0

Sources/Workspace/Workspace.swift
This provides major win when there are shared dependencies in the
package graph.
=> [Workspace] Avoid reloading already loaded manifests

CODE_OWNERS.txt
Add Ankit, who's been a primary maintainer on the project for a while.
=> Long overdue update to CODE_OWNERS.txt

Sources/PackageDescription4/LanguageStandardSettings.swift, Sources/PackageDescription4/Package.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Target.swift, Sources/TestSupport/MockDependencyGraph.swift, Sources/TestSupport/misc.swift, Tests/FunctionalTests/ToolsVersionTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Utilities/bootstrap
This is the main implementation of the proposal. It adds a new runtime
and the proposed API changes.
<rdar://problem/38721967> Provide support for Swift 4.2 in SwiftPM
https://bugs.swift.org/browse/SR-7464
=> Implement SE-209 Swift Language Version API Update

Sources/Workspace/Diagnostics.swift
Extra quotation mark in error log
=> [Fix] Logging extra quotation mark

README.md
@aciidb0mb3r as discussed on swiftpm slack in #general:
> **April 10th**  @therealbnut Do you mind opening a JIRA about that? PRs are also welcomed!
=> Add bug reporting guidelines to README.md

Sources/Commands/SwiftTestTool.swift, Tests/FunctionalTests/MiscellaneousTests.swift
This generates xUnit xml file when the option --xunit-output is
specified with the parallel test runner. This is a very minimal
implementation and is currently hidden from help. We should try to get
more information in the output but that requires better communication
with the xctest tool.
=> [SwiftTestTool] Add support for generating xUnit xml file

Utilities/bootstrap
Ticket: https://bugs.swift.org/browse/SR-7559
=> [SR-7559] Confirm rsync exists when bootstrapping

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
<rdar://problem/40627572> Switching between two local dependencies with same name but different path crashed SwiftPM
=> [Workspace] Fix local -> local switch

Sources/PackageDescription4/Package.swift, Sources/PackageDescription4/PackageDependency.swift, Sources/PackageDescription4/PackageRequirement.swift, Sources/PackageDescription4/Target.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
<rdar://problem/41251713> [SR-8041]: Prefix cases with _ for public enums in PackageDescription
=> [PD4_2] Prefix internal enum cases with _

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
This reverts commit f8a0af1d5337da601d78c2c076833dd45104113c.
=> Revert "[Build] Pass object files via a file to Swift compiler"

Sources/Commands/Error.swift, Sources/Commands/SwiftRunTool.swift, Sources/Commands/SwiftTool.swift, Sources/TestSupport/SwiftPMProduct.swift, Tests/CommandsTests/RunToolTests.swift
rdar://problem/34059859
SR-7823
(cherry picked from commit 746a71a10ce5ac830f165a57dc8fc34d55d8f795)
=> [swift-4.2-branch][Commands] Redirect output to stderr when using swift-run

Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift
<rdar://problem/41792011> Emit deprecation notice if there is a v3 manifest in a package graph
Emits a deprecation warning if there are v3 manifests in a
package graph.
=> [Workspace] Add deprecation warning for v3 manifests

Sources/PackageModel/Manifest.swift
=> [PackageModel] Remove an old workaround

Utilities/bootstrap
This makes the generated Xcode project work when we link llbuild
=> [bootstrap] Write proper xcconfig if linking llbuild

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageModel/ToolsVersion.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
<rdar://problem/42139804> Detect and emit diagnostics for unsupported tools version
=> [Workspace] Make sure root pkg is at least toolsversion 4

Sources/Basic/FileSystem.swift, Sources/Basic/PathShims.swift, Sources/POSIX/stat.swift, Tests/BasicTests/FileSystemTests.swift
<rdar://problem/39867442> Modify the extension on stat to use a FileInfo struct
We still need to do a bit of cleanup and get rid of most things in
PathShims.swift
=> [Basic] Add API to return FileInfo

Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
<rdar://problem/42403104> Fix SwiftPM Perf tests
=> [PerfTests] Fix 2 broken perf tests

Sources/Utility/Versioning.swift, Sources/clibc/include/clibc.h, Utilities/bootstrap
<rdar://problem/40205851> [SR-918]: swift build --version should reference
source's git commit sha
=> [bootstrap] Embed git hash in version string

Sources/Basic/Process.swift
<rdar://problem/32291587> [SR-5001]: Print proper errors when git operation fails
=> [Basic] Print stderr in Process's description

Sources/Commands/Describe.swift, Sources/Commands/SwiftPackageTool.swift
<rdar://problem/36273458> describe --type JSON does not output JSON
=> [Commands] Avoid loading entire package graph for describe

Utilities/bootstrap
Also fixes running bootstrap with Python 3 🐍
=> [bootstrap] Fix mixed indentation

Sources/Commands/SwiftTool.swift
=> [Commands] Avoid crash on non-existent cwd

Utilities/Docker/docker-utils
Docker needs access to llbuild to build SwiftPM in the container.
=> Fix building in docker

Sources/Basic/Lock.swift
* Fix 0644 (0o666 is subject to umask and is actually octal, unlike 0644).
* Allow FileLock to work efficiently with multiple locks/unlocks.
* Fix leak of the file descriptor on `lock`+`deinit` outside of `withLock`.
=> FileLock fixes

Sources/Basic/CollectionAlgorithms.swift, Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Package.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/PinsStore.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift
<rdar://problem/42625896> [SR-8379]: SwiftPM? Crash when compiling
LinkerKitIRCBot
=> [PackageLoading] Diagnose duplicate dependency declaration

Sources/Commands/SwiftPackageTool.swift
<rdar://problem/38543455> [SR-7215]: package completion-tool is broken in 4.1
=> [Commands] Add usage text for completion tool

Sources/Basic/CollectionAlgorithms.swift, Sources/PackageGraph/PackageGraphLoader.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageGraphTests/XCTestManifests.swift
<rdar://problem/42036789> [SR-8220]: duplicate command in 'commands' map
=> [PackageGraph] Diagnose duplicate products across package graphs

Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
<rdar://problem/34346476> swiftpm ignores missing source symlinks
=> [PackageLoading] Diagnose broken symlink sources

Sources/Build/BuildDelegate.swift, Sources/Commands/SwiftTool.swift
Depends on the following llbuild PR: https://github.com/apple/swift-llbuild/pull/359
=> Print missing verbose command description on -v

Sources/TestSupport/TestWorkspace.swift, Sources/Workspace/PinsStore.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
<rdar://problem/34302690> Detect changes in dependency URLs when the package identity remains same
=> [Workspace] Detect changes in URLs when identity remains the same

CHANGELOG.md
[SR-8108] Posts all [Package Manager](https://apple.github.io/swift-evolution/#?search=package%20manager) proposals and thanks to @aciidb0mb3r [for his summary](https://forums.swift.org/t/recent-swiftpm-features-and-enhancements/13807).
Still need to go through commits to find [notable improvements](https://swiftpm.slack.com/archives/C0XFJBKUL/p1534389800000100) (particularly in `4.1`) but wanted some initial feedback on the formatting.
=> [changelog] Initial stab at updates for 4.1 and 4.2

Sources/Workspace/InitPackage.swift
First rodeo here.  Low hanging fruit.
=> Spelling, "crerate" -> "create"

Sources/Basic/Process.swift, Sources/Basic/Result.swift, Sources/Commands/SwiftTestTool.swift, Sources/Commands/SwiftTool.swift, Sources/Utility/Process.swift
Allows to stream `Process` stdout/stderr through provided `OutputClosure`-s
=> Process streams stdout/stderr through OutputClosure-s

Sources/Commands/SwiftTool.swift
to get the currentWorkingDirectory
=> [Commands] Fix force unwrap

Utilities/bootstrap
<rdar://problem/44899092> Expose a way to build the runtimes only
=> [Bootstrap] Add an option to build just the runtimes

Sources/Basic/Process.swift
- This is a useful general purpose type for encapsulating a terminated process'
state, so it is reasonable for clients to be able to create instances (useful
for testing, for example).
=> [Basic] Make ProcessResult publicly initable.

Sources/Basic/FileSystem.swift, Sources/Basic/Thread.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTestTool.swift, Sources/SPMLLBuild/llbuild.swift, Sources/swiftpm-xctest-helper/main.swift
=> Don't use "OSX"

Documentation/Development.md, Sources/Workspace/UserToolchain.swift
<rdar://problem/45473237> SWIFTPM_PD_LIBS should accept a list of paths
=> [Workspace] Allow SWIFTPM_PD_LIBS to accept a list of search paths

Sources/PackageGraph/PackageGraphRoot.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
<rdar://problem/45744090> Enable package mirroring for graph root dependencies
=> [Workspace] Enable package mirror for graph root dependencies

Utilities/bootstrap
Update the bootstrap script for the new Foundation build layout.
=> bootstrap: update for foundation layout

Sources/Utility/Git.swift
Add our overrides for git when there is nothing already present.
<rdar://problem/45842921>
=> [Utility] Don't override git's env if already present

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
<rdar://problem/45886718> fresh repo hits: error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
=> [Workspace] Load edited packages from the right path

Utilities/bootstrap
=> Fix libswiftpm-modules-dir option

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
<rdar://problem/46367194> Check for minimum supported tools version when computing interpreter flags
=> [Workspace] Check for min tools version for interpreter flags

Sources/Workspace/InitPackage.swift
<rdar://problem/46157212> New packages should use tools version v5
=> [Workspace] Create new packages with tools version 5.0

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
<rdar://problem/46365542> Diagnose invalid values in header search path build settings
=> [PackageBuilder] Validate header search path build settings

Sources/PackageDescription4/Target.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift
<rdar://problem/23270646> [SR-3948] Need support for specifying build settings
=> [PackageDescription] Remove underscore from build settings APIs

Sources/Basic/Path.swift, Sources/Basic/misc.swift
We all use it as an extension anyway
see https://github.com/apple/sourcekit-lsp/pull/27/files#diff-c56368b1b05968c4effa47f617ce7434R19
=> Add AbsolutePath.asURL

Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
Fixes: https://bugs.swift.org/browse/SR-9402
=> Emit duplicate target dependency warnings

Sources/Commands/SwiftTool.swift, Sources/TestSupport/TestWorkspace.swift, Sources/Workspace/Workspace.swift
<rdar://problem/47008823> Remove some unused delegates from Workspace object
=> [Workspace] Remove some unused delegates

Sources/PackageGraph/DependencyResolver.swift, Tests/PackageGraphTests/DependencyResolverTests.swift
<rdar://problem/45733805> SwiftPM will crash when a package depends on itself
=> [Resolver] Diagnose if a package depends on itself

Sources/TestSupport/TestWorkspace.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
=> [Workspace] Diagnose duplicate root packages

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/XCTestManifests.swift
Second PR. Contains minor fixes and some received feedback. This also includes improvements to the current tests and a trace description to follow along with the steps the resolver takes.
=> [Pubgrub] Minor fixes and test improvements

Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SourceControl/RepositoryManager.swift, Sources/TestSupport/TestWorkspace.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
<rdar://problem/47618570> [SR-9382]: Allow selection of a specific versioned package manifest
=>  Improve support for version specific manifests

Utilities/bootstrap
=> [bootstrap] Accept a list of search paths for finding llbuild.framework

Sources/Workspace/Diagnostics.swift, Sources/Workspace/PinsStore.swift, Sources/Workspace/Workspace.swift
=> [Workspace] Emit a better diagnostic when Package.resolved is corrupted

Sources/Build/BuildPlan.swift, Sources/Build/Toolchain.swift, Tests/BuildTests/BuildPlanTests.swift, Utilities/bootstrap
=> [Build] Embed the Swift stdlib rpaths for executables

Sources/PackageGraph/PackageGraph.swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/Workspace/Workspace.swift
=> [PackageGraph] Expose the list of required packages in a graph

Sources/Basic/OrderedSet.swift, Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift
Includes further fixes for deterministic tests, non-existent version handling in decision making and checking for satisfaction on more complex cases.
=> [Pubgrub] Further improvements

Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift
This refactors decision making into more logical chunks and cleans up
the logic to be more closer to the algorithm.
=> [Pubgrub] Refactor decision making

Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift
Adding a bunch of failing tests and moved the loop into propagate() to
avoid passing changed set as inout
=> [Pubgrub] Some random refactoring, disabled tests and comments

Tests/PackageGraphTests/PubgrubTests.swift
We're unable to detect cycles right now.
=> [Pubgrub] Add some disabled tests for cycle

Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/XCTestManifests.swift
This should've never been necessary and now it really isn't.
=> [Pubgrub] Remove unnecessary isFinished property

Sources/Basic/OrderedDictionary.swift, Sources/PackageGraph/Pubgrub.swift
This should provide more deterministic outcomes when choosing the first value of solution.undecided in decision making.
=> [Pubgrub] Use OrderedDictionary for _positive

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub.swift, Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/PackageModel/Package.swift, Sources/TestSupport/MockDependencyResolver.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/DependencyResolverTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
This didn't really provide any advantage and only made the code
difficult to work with.
=> [DNM][PackageGraph] Remove generics from PackageIdentifier

Tests/PackageGraphTests/PubgrubTests.swift
More consistent renaming and moving the unversioned package dependencies into a convenience constructor. Makes it a little less verbose to work with.
=> [PubgrubTests] Simplify dependency mocking API

Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift
I struggled with these abstractions a bit when getting started on this project. Since there's no need for them anymore now, we might as well remove them.
=> [Pubgrub] Remove unnecessary typealias abstractions

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub.swift
It's a lot easier to understand now. I will add more tests for this in a future PR.
=> [Pubgrub] Refactor intersect(withRequirement:)

Tests/PackageGraphTests/PubgrubTests.swift
Allows creation of mock containers with a lot less boilerplate, much like in original pubgrub's tests.
=> [PubgrubTests] Add DependencyGraphBuilder

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/XCTestManifests.swift
Fixes a crash when a required version of a package is not available.
=> [Pubgrub] Fix intersection for non-existent versions

Sources/PackageGraph/Pubgrub.swift, Sources/Workspace/Workspace.swift
=> [Pubgrub] Support prefetching containers

Tests/PackageGraphTests/PubgrubTests.swift
This is currently hitting an assertion
=> [PubgrubTests] Add a disabled test

Sources/TestSupport/MockDependencyResolver.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
<rdar://problem/48204464> Fix SwiftPM performance tests
=> [PerfTests] Fix a bug in perf tests

Sources/SPMUtility/StringExtensions.swift, Sources/SourceControl/InMemoryGitRepository.swift, Sources/TestSupport/Manifest.swift, Sources/TestSupport/TestWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
=> [Workspace] Compute required identities in a stable order

Sources/PackageGraph/Pubgrub.swift, Tests/PackageGraphTests/PubgrubTests.swift
As requested in #2017, a separate PR for the BoundVersion changes.
=> [Pubgrub] Use BoundVersion instead of Version

Tests/PackageGraphTests/PubgrubTests.swift
Should've been obvious before, makes for nicer resolution tests.
=> [PubgrubTests] Add AssertBindings, -Result

Sources/PackageGraph/Pubgrub.swift
I accidentally introduced this with #2019 🙈
=> [Pubgrub] Fix warning

Sources/Basic/Path.swift
- This method is super expensive because of its trivial implementation. Rather
than complicate the implementation, this just adds a fast path to early exit
in the common case where the string doesn't need normalization.
=> Add a fast path for normalize(absolute:).

Sources/Build/BuildDelegate.swift, Sources/Build/BuildPlan.swift, Sources/Build/SwiftCompilerOutputParser.swift, Sources/Commands/SwiftTool.swift, Sources/SPMUtility/ProgressAnimation.swift, Tests/BuildTests/SwiftCompilerOutputParserTests.swift, Tests/CommandsTests/RunToolTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift
This PR builds (pun intended :p) on the `SwiftCompilerOutputParser` PR #1911 (not yet merged) to update the build animation progress and text for each Swift compiler task.
=> Update the build animation for each Swift compiler task

Sources/Basic/ByteString.swift
- We now have a reasonable stdlib method for implementing this.
=> [ByteString] Update ByteString.cString implementation.

Sources/Basic/FileInfo.swift
...until we can figure out how to properly invalidate the cache
=> [Basic] Keep FileInfo.Kind as computed property

Sources/PackageGraph/DependencyResolver.swift, Sources/Workspace/Workspace.swift
<rdar://problem/48341369> Add cancellation support in DependencyResolver
Unfortunately, I can't think of a good way to unit test this.
=> [PackageGraph] Add cancellation support in DependencyResolver

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/XCTestManifests.swift
<rdar://problem/48141268> [PubGrub] Add support for local and edited packages
=> [Pubgrub] Add support for local and edited packages

Sources/Basic/FileSystem.swift, Tests/BasicTests/FileSystemTests.swift
=> [Basic] Don't fail if the directory already exists

Sources/PackageGraph/DependencyResolver.swift
=> [PackageGraph] Bail out as early as possible when there are errors

Sources/PackageLoading/ToolsVersionLoader.swift, Sources/SPMUtility/Versioning.swift, Tests/FunctionalTests/ToolsVersionTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift
=> [Utility] Bump SwiftPM version to 5.1

Sources/PackageDescription4/Version+StringLiteralConvertible.swift, Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Package.swift, Sources/Workspace/Diagnostics.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> Improve some diagnostics messages

Utilities/bootstrap
=> [bootstrap] Don't use global module cache when bootstrapping

Sources/PackageDescription4/BuildSettings.swift, Sources/PackageDescription4/Package.swift, Sources/PackageDescription4/PackageDependency.swift, Sources/PackageDescription4/PackageRequirement.swift, Sources/PackageDescription4/Product.swift, Sources/PackageDescription4/SupportedPlatforms.swift, Sources/PackageDescription4/Target.swift, Sources/PackageDescription4/Version+StringLiteralConvertible.swift, Sources/PackageDescription4/Version.swift
<rdar://problem/50695506>
(cherry picked from commit 977d08daf08305ee0a448154a733f915f13887df)
=> Update the doc comments for the PackageDescription API

Documentation/PackageDescription.md, Documentation/PackageDescriptionV3.md, Documentation/PackageDescriptionV4.md, Documentation/PackageDescriptionV4_2.md, Documentation/README.md, Documentation/Resources.md, Documentation/Usage.md
This moves all of the API documentation to the PackageDescription.md file.
=> [Documentation] Update to latest API documentation

Sources/Workspace/InitPackage.swift
<rdar://problem/50709094>
(cherry picked from commit eeb85fe86cb8876f0f446b5d578ddc3e5ac101ea)
=> [Workspace] New packages should use tools version 5.1

Sources/PackageDescription4/PackageDependency.swift, Sources/PackageDescription4/Target.swift
(cherry picked from commit aefcd725cdfa1471e7fa95c1dcf1d7c210477bc6)
=> [Documentation] Add missing forward slash in two places

Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
=> [PerfTests] Fix two perf tests

Sources/PackageDescription4/SupportedPlatforms.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Sources.swift, Sources/Xcodeproj/pbxproj().swift, Tests/PackageLoadingTests/PD4LoadingTests.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift
=> [PackageDescription4] Add new OS versions in SupportedPlatforms

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/TestSupport/MockDependencyResolver.swift
... when diagnosing unavailable versions.
<rdar://problem/51183216>
=> [PackageGraph] Ensure container is of the RepositoryContainer type

Sources/Commands/SwiftTestTool.swift, Sources/TestSupport/Resources.swift, Sources/Workspace/Destination.swift
<rdar://problem/51115369>
(cherry picked from commit a8c2b02bb1d7e96888ec26627a1336295336cc23)
=> Support new XCTest overlays

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
<rdar://problem/51667879>
(cherry picked from commit a9e3d4dacf007f7f5c4c26ab4d01eede102c890f)
=> [Build] Disable Swift static linking on macOS

Sources/PackageLoading/ManifestLoader.swift
=> Add SWIFTPM_MODULECACHE_OVERRIDE for Swift CI

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
=> [PackageGraph] Actually implement _isRemoteContainer

Utilities/bootstrap
=> [bootstrap] Add rpath to look inside @exec/../lib/swift/pm/llbuild

Sources/Commands/SwiftTestTool.swift, Sources/TestSupport/Resources.swift, Sources/Workspace/Destination.swift
Reverts apple/swift-package-manager#2161
=> Revert "Support new XCTest overlays"

Documentation/Development.md, Sources/Commands/SwiftTestTool.swift
<rdar://problem/51999854>
(cherry picked from commit 31632abdfb499f5fc98951973447d169b70369e1)
=> [SwiftTestTool] Allow skipping SwiftPM tests using an env variable

Utilities/bootstrap
<rdar://problem/52065093>
(cherry picked from commit e43bae3c5214c239a3baf82dca1602b7b001601e)
=> [bootstrap] Pass sdk when creating libPackageDescription

Sources/PackageDescription4/BuildSettings.swift, Sources/PackageDescription4/LanguageStandardSettings.swift, Sources/PackageDescription4/Package.swift, Sources/PackageDescription4/PackageDependency.swift, Sources/PackageDescription4/PackageRequirement.swift, Sources/PackageDescription4/Product.swift, Sources/PackageDescription4/SupportedPlatforms.swift, Sources/PackageDescription4/Target.swift, Sources/PackageDescription4/Version+StringLiteralConvertible.swift, Sources/PackageDescription4/Version.swift
(cherry picked from commit f6292e68b99a781b952f74fc6548f90d654c9a30)
<rdar://problem/52064767>
=> Update the in-source docs for better readability.

Sources/Basic/FileSystem.swift, Tests/BasicTests/FileSystemTests.swift
=> [Basic] Only chmod regular files when onlyFiles is set

Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
=> [PackageLoading] Diagnose invalid values of build settings

Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift
...from what's on disk
<rdar://problem/49648458>
(cherry picked from commit 843608b8b658192474aa7773657fda7be3bd2cd8)
=> [PackageLoading] Emit warning if case in the manifest is different

Sources/Commands/SwiftTool.swift
<rdar://problem/52359638> Ctrl+C on `swift build` does not interrupt build subprocess
Looks like SwiftPM became responsible for cancelling the build when it switched to
using library-based llbuild.
(cherry picked from commit 20f006ee61aed7bed6b018aa891818350454ddd8)
=> [Commands] Cancel build when we receive a signal

Sources/SPMUtility/PkgConfig.swift
This change makes the emitting the "failed to retrieve search paths with pkg-config; maybe pkg-config is not installed" diagnostic happen lazily and only if an expected pkg-config file was not found.
Without this change, the diagnostic is emitted with every build if pkg-config is not installed on the system.
=> [PkgConfig] Do not emit 'pkg-config not installed' diagnostic unless we failed to find a pc file

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
<rdar://problem/45312296> [SR-10802]: --disable-automatic-resolution doesn't work for local packages
=> [Workspace] Handle local packages when automatic resolution is disabled

Sources/PackageGraph/DependencyResolver.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
=> [PackageGraph] Diagnose invalid usage of local package reference

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
<rdar://problem/50734652> [SR-10616]: SwiftPM should pass deployment target in the link command
=> [Build] Pass deployment target in the link command

Sources/PackageLoading/ManifestLoader.swift
=> [PackageLoading] Always parse manifest when there are errors

Sources/Workspace/PinsStore.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
This reverts commit 32e144d605bbd107c70a65056b7870217d06fd27.
<rdar://problem/53085717>
=> Revert "[Workspace] Improve how we handle changes to Package.resolved"

Documentation/Usage.md
=> Update documentation of version specific manifest

Sources/SPMUtility/StringExtensions.swift, Sources/SourceControl/GitRepository.swift
<rdar://problem/53228398>
(cherry picked from commit 8929db0bc3794337bf0dfbe2b88338134cda7fb9)
=> [SourceControl] Include repository url in the git clone error

Utilities/bootstrap
This are minimal changes required to start Windows bootstapping.
=> [bootstrap] Start recognizing Windows in bootstrap

Sources/Build/BuildPlan.swift, Sources/TestSupport/AssertMatch.swift, Tests/BuildTests/BuildPlanTests.swift
Reverts apple/swift-package-manager#2250
=> Revert "[Build] Pass -application-extension for non-executable/non-system lib…"

Sources/PackageGraph/PackageGraphLoader.swift, Sources/TestSupport/TestWorkspace.swift, Sources/Workspace/CheckoutState.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/WorkspaceTests/XCTestManifests.swift
<rdar://problem/53557659>
SR-11225
This will lift the restriction of using unsafe flags from local and
branch-based dependencies.
=> [PackageGraph] Allow unsafe flags in local and branch-based dependencies

Sources/Build/llbuild.swift
This will make the test discovery command logic to be independent of the
global target list in the build plan, which in turns makes it for
multiroot packages.
<rdar://problem/53762967>
=> [Build] Tweak how we write commands for the test discovery

Sources/Workspace/Workspace.swift
It was wrong to emit this via note diagnostics.
=> [Workspace] Remove ResolverDurationNote

Sources/Build/BuildDelegate.swift, Sources/Build/BuildPlan.swift, Sources/Build/ToolProtocol.swift, Sources/Build/llbuild.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftBuildTool.swift, Sources/Commands/SwiftTool.swift
To prep it for build manifest caching.
=> Refactor a bunch of stuff in Build/Commands module

Sources/Build/BuildPlan.swift, Sources/Build/Sanitizers.swift, Sources/Build/Triple.swift, Sources/PackageModel/BuildSettings.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SPMUtility/BuildFlags.swift, Sources/Workspace/Destination.swift
=> Conform BuildParameters to Encodable

Sources/Basic/DiagnosticsEngine.swift, Sources/Build/BuildDelegate.swift, Sources/SPMUtility/Diagnostics.swift, Tests/BasicTests/DiagnosticsEngineTests.swift
- Make `.note` diagnostics accessible from anywhere
=> Expose .note diagnostics API

Sources/clibc/include/indexstore_functions.h
Update `indexstore_functions.h` from IndexStore-DB.
=> clibc: synchronise `indexstore_functions.h`

Sources/Basic/FileSystem.swift, Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/SPMUtility/Platform.swift, Tests/BasicTests/FileSystemTests.swift, Tests/BasicTests/PathTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/XcodeprojTests/PackageGraphTests.swift
Delete some bleeding whitespace.  This is split from PR2090.
=> whitespace cleanup (NFC)

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub.swift, Sources/PackageGraph/VersionSetSpecifier.swift
This doesn't really contain any functionality change and is just cleanup and prep work for implementing bound computation (54099969).
=> [PubGrub] [NFC] Do prep work for implementing bound computation when returning external incompatibilities

Sources/SourceControl/GitRepository.swift
During package resolution, we end up shelling out repeatedly for some
operations (tools version, manifest parsing, etc). We can memoize the
result of some git operations to improve performance. Also note that
GitRepository objects are released after resolution process is over.
<rdar://problem/54584428>
=> [SourceControl] Memoize results of some git calls
