swiftlang/swift-package-manager

Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
This extends our existing dependency resolver perf tests to also test
using the PubGrub resolver.
<rdar://problem/46075428>
=> [PubGrub] Add performance tests

Sources/PackageGraph/Pubgrub.swift, Sources/PackageGraph/VersionSetSpecifier.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/XCTestManifests.swift
This implements bound computation for tools version which makes its
diagnostics much easier to read and understand. See the updated test
cases for the improvements this brings.
<rdar://problem/54836184>
=> [PubGrub] Implement bound computation for tools version

Sources/Commands/Options.swift
=> [Commands] Enable PubGrub by default

Documentation/PackageDescription.md, Sources/PackageDescription4/BuildSettings.swift
Now this matches with the description of `linkedLibrary`.
=> Clarify what `linkedFramework` is for

Sources/TSCBasic/TemporaryFile.swift
SwiftPM used to allow overriding the temporary directory using the
TMPDIR variable. This facility was removed recently in favor of
NSTemporaryDirectory() but that method doesn't respect TMPDIR on macOS.
<rdar://problem/55147926>
=> [TSCBasic] Allow overriding the temporary directory

Utilities/bootstrap
Reverts apple/swift-package-manager#2340
=> Revert "[bootstrap] Install swiftinterface instead of swiftmodule for PD"

Sources/PackageLoading/ManifestLoader.swift
=> Prefer swiftinterface for PackageDescription

Tests/TSCBasicTests/PathShimTests.swift
=> [TSCBasic] Don't rely on SwiftPM for a PathShimTests

Utilities/bootstrap
Ensure that we check the new Foundation location for the paths to the
libraries.
=> bootstrap: check the new Foundation layout

Sources/Build/BuildDelegate.swift, Sources/Build/BuildPlan.swift, Sources/Build/ToolProtocol.swift, Sources/Build/Triple.swift, Sources/Build/llbuild.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Sources.swift, Sources/PackageModel/Target.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/XCTestManifests.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift
=> [Build] Add code generation for the resources bundle accessor

Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
This adds ability to automatically load sources and resources files in
a target based on rules.
<rdar://problem/56480468>
=> [PackageLoading] Pick up resource files in a target

Tests/XcodeprojTests/FunctionalTests.swift
This will avoid building the PackageDescription target which seems to
flaky sometimes on the CI.
<rdar://problem/56757974>
=> [XcodeprojTests] Use scheme based builds

CMakeLists.txt
Correct the name of the project.  This is SPM.
=> build: rename the package name

Sources/TSCLibc/libc.swift
This enables building for Windows.
=> TSCLibc: add stub for `realpath` on Windows

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest.swift, Sources/Workspace/Diagnostics.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift, Tests/PackageLoadingTests/PD5_2LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
Plus moving validation code into functions to make validation logic more readable.
=> Move duplicate target check to load time

Sources/PackageLoading/PackageBuilder.swift
The 2278a8e1ad80cfbe19dce1e70368cddf3961257a merge commit removed some work done in c1ea9738dcb18b28f6465942980627c4e244c7b7. This PR corrects that merge error.
=> Fix a merge mistake

Utilities/new-bootstrap
=> [new-bootstrap] Use rpath instead of DYLD_FRAMEWORK_PATH

Documentation/Development.md
=> [Docs] Update development documentation

Utilities/bootstrap
Useful for CI to avoid incremental issues.
<rdar://problem/58287933>
=> [bootstrap] Add an option to force cmake configuration step

Fixtures/Resources/Simple/Sources/SeaResource/main.m, Sources/Build/BuildPlan.swift, Sources/PackageModel/Sources.swift
This adds support for generating resources accessor for ObjC targets.
<rdar://problem/56816817>
=> [Build] Generate resources accessor for ObjC targets

Sources/SPMTestSupport/misc.swift, Sources/SourceControl/Repository.swift, TSC/Sources/TSCBasic/CMakeLists.txt, TSC/Sources/TSCBasic/HashAlgorithms.swift, TSC/Sources/TSCTestSupport/Product.swift, TSC/Tests/TSCBasicPerformanceTests/SHA256PerfTests.swift, TSC/Tests/TSCBasicTests/SHA256Tests.swift, TSC/Tests/TSCUtilityTests/ArgumentParserTests.swift, Tests/BuildTests/IncrementalBuildTests.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/CommandsTests/RunToolTests.swift, Tests/CommandsTests/TestToolTests.swift, Tests/FunctionalPerformanceTests/BuildPerfTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/ToolsVersionTests.swift
Required for the new binary target work.
Requires #2497
=> Introduce a new HashAlgorithm protocol and make SHA256 conform to it

Sources/Build/Triple.swift
=> Add -gnu in aarch64 Linux's triple 

TSC/Sources/TSCUtility/Downloader.swift, TSC/Tests/TSCUtilityTests/DownloaderTests.swift
TSC PR: https://github.com/apple/swift-tools-support-core/pull/28
=> Improve Downloader to report progress as a number of bytes instead of percentage

Sources/Build/BuildPlan.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Package.swift, Sources/PackageModel/Target.swift, Sources/Workspace/Diagnostics.swift, Sources/Xcodeproj/SchemesGenerator.swift, Sources/Xcodeproj/Target+PBXProj.swift, Sources/Xcodeproj/pbxproj.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift, Tests/PackageLoadingTests/PD5_2LoadingTests.swift, Tests/PackageLoadingTests/XCTestManifests.swift
=> Introduce the new binary target changes to the Manifest API

Sources/Workspace/InitPackage.swift
<rdar://problem/58530054>
(cherry picked from commit e5e353dc8eeffd55ba6d347e3acd78c2864f8bc0)
=> [Workspace] Bump tools version for init package

Sources/Workspace/Diagnostics.swift
I converted some, but not all (as some have a fairly complex message generation logic), into the new `Diagnostic.Message` system.
=> Convert some of the manifest loading diagnostics to the new system

Sources/PackageGraph/Pubgrub.swift
The prefetching logic had a bug which sometimes leads to deadlock if
prefetched container queries start calling the completion block while
the main resolution logic is trying to fetch a new container that is NOT
in the prefetching list (because it's new dependency). The main reason
for this is that the container provider is using a serial queue for
callbacks (which is questionable) but it's better to not make any
assumptions about the provider and never run potentially blocking code
in the compleition handler.
Unfortunately, this is proving hard to unit test because this
depends on network speed/latency etc.
<rdar://problem/58644686>
=> [PubGrub] Fix a potential deadlock when prefetching

Sources/PackageDescription/CMakeLists.txt, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/ToolsVersion.swift
<rdar://problem/58028627>
(cherry picked from commit 1a4e3f23a3857dbad629f8e68680ca0030a6bbad)
=> Compile manifests instead of interpreting them

Sources/Workspace/Workspace.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/PIFSerialization.swift, Sources/Xcodeproj/XcodeProjectModel.swift, Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Minor reformatting and NFC I did while reading over and studying the `XCBuildSupport` target.
=> Minor tweaks to PIFBuilder and PIF types

TSC/Sources/TSCclibc/include/indexstore_functions.h
=> [TSCclibc] Sync indexstore_functions.h

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD5_2LoadingTests.swift
Once we get this merged, I guess we should do a similar PR against 5.2, correct?
=> [SR-12075] Improve unknown package in dependencies of target diagnostic

Utilities/bootstrap
<rdar://problem/55992972>
(cherry picked from commit 9e37ccbb46c4e2b3a80e8974ea117f371523962f)
=> [bootstrap] Add additional rpath for llbuild

Sources/Build/BuildPlan.swift
(cherry picked from commit da393401075397d16e7be7504d7bbf8d0068272e)
=> Migrate entirely to new color-diagnostics flag

Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Pix performance tests that were broken with the recent conditional dependency commit.
=> Fix perf tests

Package.swift, Utilities/bootstrap
Reverts apple/swift-package-manager#2559
=> Revert "[bootstrap] Allow passing TSC build dir"

Sources/PackageLoading/ManifestLoader.swift, TSC/Sources/TSCUtility/Diagnostics.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
This reverts commit e92f0a3e1d734ffce7e28224c2fedeb129f25d8b.
=> Revert "Fix issues with diagnostics emitted during manifest loading"

Sources/PackageLoading/ManifestLoader.swift, Utilities/bootstrap
=> [5.1] Compile manifests instead of interpreting them

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
=> [PackageGraph] Properly validate tools version for local dependencies

Sources/SPMTestSupport/PIFTester.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Tests/XCBuildSupportTests/PIFTests.swift
This will be used for implementing target conditionals without
requiring PIF regeneration.
<rdar://problem/59535847>
=> [XCBuildSupport] Add PlatformFilter to build file and target dependency

Sources/Commands/BuildSystem.swift, Sources/SPMTestSupport/PIFTester.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
=> [XCBuildSupport] Plumb platform filters in PIF

Sources/Build/BuildParameters.swift, Sources/Commands/BuildSystem.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/XCBuildSupport/PIFBuilder.swift
This allows passing additional flags to the underlying build tool.
<rdar://problem/59634203>
=> [Commands] Add -X* arg for the xcode buildsystem

IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift, Sources/Commands/SwiftTool.swift, Tests/CommandsTests/BuildToolTests.swift
=> [Commands] Fix build subpath when using xcbuild

Sources/PackageGraph/PackageGraphLoader.swift, Tests/PackageGraphTests/PackageGraphTests.swift
The package name validation was wrong for product target dependencies
(`.product(name: "<product>", package: "<package>")`) as we were looking
up the package using its identity instead of the name. This completely
breaks package loading in 5.2 if a package wants to use a product from
a dependency that doesn't match the package name of that dependency.
<rdar://problem/59744465>
=> [PackageGraph] Fix package name validation for product target dependencies

Sources/Commands/SwiftTool.swift, Sources/SPMBuildCore/Triple.swift, Sources/Workspace/Destination.swift
=> Avoid computing toolchain twice when we're using host toolchain

Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PDNextLoadingTests.swift
All paths in target description are expected to be relative path.
<rdar://problem/59397584>
=> [PackageLoading] Validate paths in target description

Sources/Workspace/UserToolchain.swift
On non-macOS platforms, use the PATH environment variable to find programs rather than deferring to `which` (which is unavailable on Windows).
=> Search through PATH instead of calling "which"

Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, TSC/Sources/TSCUtility/JSONMessageStreamingParser.swift, TSC/Sources/TSCUtility/ProgressAnimation.swift
Reverts apple/swift-package-manager#2626
=> Revert "[XCBuildSupport] Display proper build progress"

Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, TSC/Sources/TSCUtility/JSONMessageStreamingParser.swift, TSC/Sources/TSCUtility/ProgressAnimation.swift
=> [XCBuildSupport] Display proper build progress

Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Platform.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
=> [PackageLoading] Plumb platform options to SupportedPlatforms

Sources/PackageModel/Platform.swift, Sources/Workspace/InitPackage.swift, Tests/WorkspaceTests/InitTests.swift
This adds an options parameter to InitPackage that allows customizing
the package template.
<rdar://problem/60397168>
<rdar://problem/60397171>
=> [Workspace] Add more customization options to InitPackage

README.md
This should improve readability of the `README.md` file
=> Add link to the Language Server Protocol website

TSC/Sources/TSCUtility/Platform.swift, TSC/Tests/TSCUtilityTests/PlatformTests.swift, Tests/PackageLoadingTests/PkgConfigTests.swift
Depends on https://github.com/apple/swift-tools-support-core/pull/61
=> Backport fedora support

swift-tools-support-core/Sources/TSCUtility/Versioning.swift
This is already done in TSC repo so nothing to do there.
=> [5.3] Set development = false in versioning

Sources/PackageDescription/PackageDescription.swift, Sources/PackageLoading/ManifestLoader.swift
This avoids revlock between libSwiftPM and PackageDescription, which caused problems some clients (such as SourceKit-LSP) that have a statically linked libSwiftPM but use an older version of PackageDescription.
This restores the functionality prior to SR-12553, while also keeping the separation between stdout and the JSON output emitted by the package manifest.  It still uses a file in the file system for the JSON, but goes back to having it be opened by the caller of the manifest, passing the file descriptor down to the manifest process as before the switch from interpreted to compiled manifests.
Unit test added for SR-12553 still provides test coverage.
=> [SR-12613] [ManifestLoader] Go back to using `-fileno` option for the separate JSON output

Sources/PackageDescription/PackageDescription.swift, Sources/PackageLoading/ManifestLoader.swift
This is the 5.3 nomination for a fix that is already in master.
This avoids revlock between libSwiftPM and PackageDescription, which caused problems some clients (such as SourceKit-LSP) that have a statically linked libSwiftPM but use an older version of PackageDescription.
This restores the functionality prior to SR-12553, while also keeping the separation between stdout and the JSON output emitted by the package manifest. It still uses a file in the file system for the JSON, but goes back to having it be opened by the caller of the manifest, passing the file descriptor down to the manifest process as before the switch from interpreted to compiled manifests.
Unit test added for SR-12553 still provides test coverage.
=> [5.3] [SR-12613] [ManifestLoader] Go back to using `-fileno` option for the separate JSON output

Sources/PackageModel/BuildSettings.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Package.swift, Sources/PackageModel/PackageModel+Codable.swift, Sources/PackageModel/Platform.swift, Sources/PackageModel/Product.swift, Sources/PackageModel/Resource.swift, Sources/PackageModel/Sources.swift, Sources/PackageModel/Target.swift
Conform types in PackageModel target to Codable which allows serializing
and deserializing the package model.
=> [PackageModel] Add Codable support

Sources/Workspace/InitPackage.swift
This PR updates the generated `.gitignore` file to add relative derived data and Xcode 11's `.swiftpm` directory
=> Update generated gitignore

swift-tools-support-core/Sources/TSCBasic/Process.swift, swift-tools-support-core/Tests/TSCBasicTests/ProcessTests.swift
This is a mirror of https://github.com/apple/swift-tools-support-core/pull/69
=> Add Process support for workingDirectory

Fixtures/Resources/Localized/Package.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/2704 to the 5.3 branch.
=> Process any files in .lproj by default

Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XCBuildOutputParser.swift
Cherry-pick #2726 to the 5.3 branch.
=> Improve output when using XCBuild

Sources/Workspace/InitPackage.swift, Tests/WorkspaceTests/InitTests.swift
(cherry picked from commit 15c0035987f9fc927248e08deffa2188e42481a1)
=> [Workspace] Fix indentation in test file generated for libraries

Sources/Workspace/Workspace.swift
Cherry-pick #2743 to the 5.3 branch.
=> Pass XCTest minimum deployment target in Workspace

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift
Cherry-pick #2740 to the 5.3 branch.
=> Fix incorrect assertion in `ManifestParserResult`

Sources/Workspace/InitPackage.swift
Minor tweaks to the wording of newly instantiated packages.
rdar://63120125
=> [Workspace] Update wording in template for Swift Packages

Sources/Build/ManifestBuilder.swift
The Swift driver added some APIs to provide descriptions and
whether a particular job invokes the Swift frontend. Use those
APIs rather than switching on the "kind" of a Swift driver job.
=> [Integrated driver] Adopt new driver APIs for descriptions.

Sources/PackageModel/ResolvedModels.swift
=> Fix typo in comment in ResolvedModels.swift

Sources/Commands/SwiftTestTool.swift
Add usage text for --test-product arguments in test tool.
=> [Commands] Add usage text for --test-product

Sources/Commands/SwiftTestTool.swift, Tests/FunctionalTests/MiscellaneousTests.swift
Implements https://bugs.swift.org/browse/SR-10800
=> Allow test filter to be passed multiple times

Sources/Build/BuildPlan.swift, Sources/Workspace/InitPackage.swift
This hardcoded platform and architectures before, make it more generic to handle macOS on arm64.
=> Update XCFramework logic

Sources/Commands/SwiftTool.swift
5.3 cherry-pick of https://github.com/apple/swift-package-manager/pull/2826
=> Mark `--build-system` as experimental

Sources/PackageLoading/TargetSourcesBuilder.swift
5.3 cherry-pick of https://github.com/apple/swift-package-manager/pull/2825
=> Demote unhandled file diagnostic to a warning

Documentation/Development.md
I think the quotation mark does not belong here.
=> Removed a quotation mark that does not belong in the command

Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageModel/ResolvedModels.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> Improve check for unsafe flags

Sources/Build/ManifestBuilder.swift, Tests/BuildTests/BuildPlanTests.swift
Building a Swift module in Explicit Module Build mode requires passing all of its module dependencies as explicit arguments to the build command. Thus, building a SwiftPM package with multiple inter-dependent targets requires that each target’s build job must have its target dependencies’ modules passed into it as explicit module dependencies.
When planning a build that involves multiple Swift modules (targets), because planning takes place before any of the targets are built, the dependency scanning action will not be able to discover such modules. In such cases, we must provide the driver with information about all such external dependencies, including the path to where their compiled .swiftmodule will be located, once built, and a full inter-module dependency graph for each such …
=> [Explicit Module Builds] Support explicit builds of packages witn inter-dependent Swift targets

Utilities/bootstrap
=> Use `get_build_target` consistently

Sources/SPMBuildCore/BuildParameters.swift, Sources/SPMBuildCore/Triple.swift
Address review feedback comments from @tomerd
=> SPMBuildCore: use `switch` instead of `if` (NFCI)

Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/Resource.swift, Sources/PackageDescription/Target.swift
This PR includes some minor updates to the in-source documentation to address editorial feedback.
=> Minor Updates to the PackageDescription In-Source Documentation

Sources/Workspace/Destination.swift
Position-independent code is not used on Windows, and passing `-fPIC` results in a build error, since the argument is unknown
=> Avoid passing -fPIC compiler argument on Windows

Sources/Build/ManifestBuilder.swift
Targets that depend on products were not previously handled in Explicit Module Builds.
This patch adds support for product dependencies by expanding such dependencies into dependencies on targets that make up a given product, for the sake of propagating target build planning artifacts (binary module path and dependency graph) to depending targets' build planning in the integrated driver.
Resolves rdar://67713214
=> [Explicit Module Builds] Handle product dependencies by expanding them into constituent targets.

Sources/Build/BuildDelegate.swift
=> Build: remove unused variable (NFC)

Utilities/bootstrap
(cherry picked from commit 73b2a4a95fe6aff1631fa9148cdfbbccdb3b7929)
Master PR - https://github.com/apple/swift-package-manager/pull/2902
=> [5.3] [bootstrap] Add support for cross compile hosts flag

Documentation/Usage.md
- path to main.swift was wrong
- tools-version was missing from Package.swift snippet
=> Fix two issues in Usage.md

Documentation/PackageDescription.md
the description of parameter path is not right
=> testTarget method's description of parameter path

Sources/Commands/SwiftPackageTool.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> Improve diagnostics for missing local package dependency (or other file system error)

Sources/Workspace/UserToolchain.swift
Since the C runtime must match in the entire address space, when
building with `/MD` or `/MDd` we know that the C/C++ code must match the
configuration of the runtime.  With static linking, there can be only a
single C runtime in the address space, and so we know that the C/C++
code must match the configuration as well.  We can derive the C/C++
flags for the compiler driver and transliterate them to the clang
spelling rather than the `cl` spelling.
The C/C++ compiler flags being added here map directly to the behaviour
of the associated `cl` flag.
=> Workspace: handle `/MT`, `/MTd`, `/MD`, `/MDd` for C/C++

Sources/Build/ManifestBuilder.swift
This PR changes the interface used to communicate external dependencies to swift-driver's build planning action for an individual target, to match the corresponding change in https://github.com/apple/swift-driver/pull/280. SwiftPM will now pass: 
- A set of external targets along with the location of their resulting `.swiftmodule` files, as before 
- a collection of *all* modules seen so far across all targets already planned in this build.
The second point replaces previous behaviour, where we only passed in the dependency graphs of targets which are dependencies of the target swift-driver is currently planning the build for. This information will allow swift-driver to avoid performing redundant work when scanning modules for dependencies and generating build jobs for them.
=> [Explicit Module Builds] Communicate all previously-seen modules to swift-driver when planning explicit package build.

Sources/Build/ManifestBuilder.swift
Builds on: https://github.com/apple/swift-driver/pull/284
=> [Explicit Module Builds] Rely on swift-driver API to merge dependency graphs across targets

swift-tools-support-core/Sources/TSCBasic/Process.swift, swift-tools-support-core/Tests/TSCBasicTests/ProcessTests.swift
=> Revert changes from apple/swift-tools-support-core#122

Sources/PackageLoading/README.md, Sources/PackageLoading/TargetSourcesBuilder.swift
The sentence in the second paragraph of `README.md` is unfinished. I'm not sure how it was supposed to look originally, so just cleaning it up as is.
=> NFC: Fix typos in PackageLoading

Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/ToolsVersionTests.swift, Tests/FunctionalTests/VersionSpecificTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift
motivation: TSC had some test API changes that break SwiftPM tests
changes: adjust test code to nwe TSC Test aPI
=> adjust tests to changes from TSC

swift-tools-support-core/.swiftformat, swift-tools-support-core/Sources/TSCBasic/ByteString.swift, swift-tools-support-core/Sources/TSCBasic/CMakeLists.txt, swift-tools-support-core/Sources/TSCBasic/FileSystem.swift, swift-tools-support-core/Sources/TSCBasic/HashAlgorithms.swift, swift-tools-support-core/Sources/TSCBasic/Lock.swift, swift-tools-support-core/Sources/TSCBasic/PathShims.swift, swift-tools-support-core/Sources/TSCBasic/TerminalController.swift, swift-tools-support-core/Sources/TSCBasic/Thread.swift, swift-tools-support-core/Sources/TSCLibc/libc.swift, swift-tools-support-core/Sources/TSCTestSupport/misc.swift, swift-tools-support-core/Sources/TSCUtility/Bits.swift, swift-tools-support-core/Sources/TSCUtility/Bitstream.swift, swift-tools-support-core/Sources/TSCUtility/CMakeLists.txt, swift-tools-support-core/Sources/TSCUtility/PersistenceCache.swift, swift-tools-support-core/Sources/TSCUtility/SQLite.swift, swift-tools-support-core/Sources/TSCUtility/SerializedDiagnostics.swift, swift-tools-support-core/Tests/TSCBasicTests/FileSystemTests.swift, swift-tools-support-core/Tests/TSCBasicTests/LockTests.swift, swift-tools-support-core/Tests/TSCBasicTests/ProcessEnvTests.swift, swift-tools-support-core/Tests/TSCBasicTests/ProcessTests.swift, swift-tools-support-core/Tests/TSCBasicTests/miscTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/ArchiverTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/BitstreamTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/DownloaderTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/PersistentCacheTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/PkgConfigParserTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/SQLiteTests.swift, swift-tools-support-core/Utilities/ci.xcworkspace/contents.xcworkspacedata
Syncs the latest tools support core changes into SwiftPM.  This will need to be done periodically until TSC is no longer vendored.
This is currently done by copying the files from a checkout of TSC into SwiftPM, which doesn't preserve the commit history.  This is hopefully not going to be a problem once https://github.com/apple/swift-package-manager/pull/2991 is merged.  Per the comment in that PR, there are currently some remaining CI issues to work through before it can be merged.
=> Sync latest TSC changes from `main`

.swiftformat
motivation: help contributors follow formatting conventions
changes: add swiftformat file that can be used before submitting PR
=> add swiftformat config file

Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift
This adjusts to a ToolSupportCore change.
=> Add cachesDirectory implementation to GitFileSystemView

swift-tools-support-core/Package.swift, swift-tools-support-core/Sources/TSCBasic/CMakeLists.txt, swift-tools-support-core/Sources/TSCBasic/Closable.swift, swift-tools-support-core/Sources/TSCBasic/FileSystem.swift, swift-tools-support-core/Sources/TSCBasic/Path.swift, swift-tools-support-core/Sources/TSCBasic/Process.swift, swift-tools-support-core/Sources/TSCBasic/WritableByteStream.swift, swift-tools-support-core/Sources/TSCLibc/CMakeLists.txt, swift-tools-support-core/Sources/TSCLibc/libc.swift, swift-tools-support-core/Sources/TSCUtility/CMakeLists.txt, swift-tools-support-core/Sources/TSCUtility/IndexStore.swift, swift-tools-support-core/Sources/TSCUtility/PersistenceCache.swift, swift-tools-support-core/Sources/TSCUtility/PkgConfig.swift, swift-tools-support-core/Sources/TSCUtility/Versioning.swift, swift-tools-support-core/Tests/TSCBasicTests/LockTests.swift, swift-tools-support-core/Tests/TSCBasicTests/PathTests.swift, swift-tools-support-core/Tests/TSCBasicTests/ProcessTests.swift, swift-tools-support-core/Tests/TSCBasicTests/processInputs/in-to-out, swift-tools-support-core/Tests/TSCUtilityTests/DownloaderTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/PkgConfigParserTests.swift
This requires https://github.com/apple/swift-package-manager/pull/3024 before tests can succeed.  That PR is still waiting for builds to complete.
=> Sync vendored copy of TSC up to 58a3ddb4a8b810a43cfc25be1f806e0a1ad330bc

Sources/PackageCollections/Model/CVE.swift, Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/Model/Search.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/PackageMetadataProvider.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
motivation: implement fetch package metadata API
changes:
* add PackageMetadataProvider API
* add business logic to fetch metadata from collection sotre + provider and merge it
* add tests
=> fetch package metadata

Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/Model/Search.swift, Sources/PackageCollections/Storage/PackageCollectionsProfileStorage.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
motivation: continue to implement package collections business logic
changes:
* implement in memory search for packages and targets
* performance work on "list" by making decoding in parallel (TBD)
* enable performance tests
=> implement search

swift-tools-support-core/Sources/TSCBasic/FileSystem.swift, swift-tools-support-core/Sources/TSCUtility/Netrc.swift
Synchronizes the vendored TSC to the latest commit (415d6f8814534cc665df6957c119d3fdea8768bc).
=> Sync vendored TSC to latest (415d6f8814534cc665df6957c119d3fdea8768bc)

Sources/Basics/HTTPClient.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Repair the Windows builds after the breakage introduced by #3040 and 3058.
=> build: repair the Windows build after #3040, #3058

Sources/Basics/JSON+Extensions.swift, Sources/Build/BuildDelegate.swift, Sources/Build/SwiftCompilerOutputParser.swift, Sources/Commands/SwiftPackageTool.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/SPMLLBuild/CMakeLists.txt, Sources/SPMLLBuild/llbuild.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Sources/swiftpm-manifest-tool/main.swift, Tests/PackageModelTests/PackageModelTests.swift, Tests/XCBuildSupportTests/PIFTests.swift
motivation: consolidated logic
changes:
* new factory functions for JSONEncoder and JSONDecoder with healthy defaults
* refactor code to use new factories
* update CMake config where required to bring in Basics
=> consolidate json settings

Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/Pubgrub/Incompatibility.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SPMTestSupport/MockPackageContainer.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: clearer error messages help users become more self sufficient
changes:
* simplify language of error messages to be clearer
* update error messages about incompatible tools version to include the tools version in question
* adjust tests
rdar://63732571
=> improve pubgrub error messages

Sources/Basics/CMakeLists.txt, Sources/Basics/ConcurrencyHelpers.swift, Sources/Basics/Dictionary+Extensions.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SPMTestSupport/MockPackageContainer.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace.swift, Tests/BasicsTests/ConcurrencyHelpersTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/InMemoryGitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: improve the performance of resolving dependencies
changes:
* define generic thread-safe caching data strucutures
* update GitRepository to use the new caching data strucutres
* update GitRepository queue to concurrent and use barrier for write operations
* refactor Repository::tag to a throwing function, and change downstream code accordingly
* refactor PackageContainer::reversedVersions to a throwing function, and change downstream code accordingly
* update tests
=> work towards performance improvements

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/Pubgrub/Term.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/Workspace/Workspace.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: better performance, happier users
changes:
* load root manifests in parallel
* add caching to manifest loader
* further tweaks to pubgrub data strucutures to make them thread-safe, and simplify flow
* comments cleanup
=> dependency resolution performance improvements 

Sources/Build/BuildDelegate.swift, Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan.swift, Sources/Build/ManifestBuilder.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/Workspace/Workspace.swift
motivation: less crashes, happier users
changes: replace usage of forced unwraps with throwing guards, use InternalError for assertion during developement
=> reduce usage of forced unwarps

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/Workspace/ResolverPrecomputationProvider.swift
Getting "reference to property 'x' in closure requires explicit 'self.' to make capture semantics explicit"
=> Fix 5.2 build

Tests/XCBuildSupportTests/PIFBuilderTests.swift
We merged that PR without a unit test, this adds one.
rdar://68158441
=> Add missing unit test for https://github.com/apple/swift-package-manager/pull/2891

Sources/Workspace/Workspace.swift
Add missing dispatch group leave in case of download artifacts download fail
Leave dispatch group in all cases - unstuck download queue in case of failure.
=> Add missing dispatch group leave in case of download artifacts download fail

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
The PubgrubError type had become internal at some point since 5.3.  This breaks clients that has special handling of PubgrubError.  This makes them public again.
Some clients of libSwiftPM specialize on PubgrubError to provide more customized errors.
This changes the PubgrubError type to public, and changes one of the enum cases to contain the list of incompatibilities rather than to contain the state.  This allows the state to remain private, while still allowing clients to access the list of incompatibilities (thanks to @tomerd for that suggested improvement).
=> Make the PubgrubError type public again

Sources/Commands/SwiftTool.swift
motivation: no debug print messages
changes: remove leftover debug print statement from #3158
=> remove leftover debug print statement

Sources/Commands/SwiftTool.swift
=> [5.4] remove leftover debug print statement

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.4] identity collisions diagnostics test and fixes

CODEOWNERS
=> Update CODEOWNERS (#3181)

CHANGELOG.md, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageModel/ToolsVersion.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift
It's like #3170, but for the main branch.
=> [PackageLoading] replace Next with 5.4 according to notes left previously

Sources/Commands/SwiftPackageCollectionsTool.swift
Motivation:
When using `swift-package-collection describe` on local and remote packages that aren’t included in any added collections, we return unrelated errors.
For example, with https://github.com/apple/example-package-dealer:
```
$ swift run swift-package-collection describe https://github.com/apple/example-package-dealer
Error: invalidResponse("Missing Content-Length header")
```
The `describe` command can display metadata for:
- Imported or unimported collections
- Packages found in imported collections
Modifications:
- Update `describe`'s help message
- Improve error message for the use-case mentioned
=> [Collections] Improve error message for 'describe' command

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
The [amendment](https://github.com/apple/swift-evolution/pull/1270) has been accepted, hence removing feature flag.
=> [Collections] Remove feature flag for signing

Documentation/Contributing.md
motivation: better docs, happier developers
changes: update continuous integration section with additional information about the package compatibility test suite
=> update contribution guide

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
motivation: make collections sqlite storage more robust
changes:
* use FS lock on sqllit
* on linux, execute command exclusiviely (with the lock)
* move "isShuttingdown" into the state
=> [reliability] improve collections sqlite storage

Sources/Workspace/Workspace.swift
motivation: performance improvment
changes: when loading nested dependencies manifests, load them in parallel instead of one-by-one
=> [performance] load more manifests is parallel

Sources/Basics/JSON+Extensions.swift
It would be nice if we can have sorted keys without pretty printing.
=> Add another JSONEncoder.makeWithDefaults variation

Sources/Basics/CMakeLists.txt, Sources/Basics/Sandbox.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/BasicsTests/SandboxTests.swift
motivation: in preparation to suppoting linux sandboxing, make sandbox infra DRYer
changes:
* new Sandbox utility in Basics
* refactor manifest loader + plugins to use the new utility
* add tests
=> consolidate sandbox infrastructure

Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
Compilation errors: missing return in a function expected to return 'Bool'
=> [Collections] Fix build for unsupported platforms

Documentation/PackageCollections.md
- Add table of contents
- Document all CLI command options
=> [Collections] Documentation: add more details on the CLI

Sources/Workspace/Workspace.swift
motivation: improved performance
changes: refactor how parallelism is done when fetching the "pinned" containers, resulting in less thread hops
=> improve fetching of repositories from Package.resolved

Tests/FunctionalTests/PluginTests.swift
Finding and fixing the issue is tracked by rdar://76421504
=> Skip a test on Apple Silicon until we find out what's wrong; it's blocking CI

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
Sometimes package-collection CLI subcommand ends with "Error: [Failed to close database]".
A new `SQLitePackageCollectionsStorage` is created then destroyed for each subcommand execution. The initialization includes populating in-memory trie using data in SQLite (`populateTargetTrie`) and may take a while to complete depending on the number and size of configured collectons. There is logic in `SQLitePackageCollectionsStorage.close` to signal `populateTargetTrie` to stop, but because it keeps holding on to `stateLock`, it prevents `populateTargetTrie` from determining if it should stop and causes the "database is locked" error.
Modifications:
Break down the `withStateLock` block in `close` to smaller blocks such that `retryClose` is called outside of it. This allows …
=> [Collections] Shorten hold to lock on db close

Sources/Commands/SwiftPackageCollectionsTool.swift
This is https://github.com/apple/swift-package-manager/pull/3412 for 5.5.
=> [5.5][Collections] Better handling of spaces in collection file path

Sources/Commands/SwiftTool.swift
motivation: we dont need dead code around
changes: remove SwiftTool::sandboxProfile which is not in use
=> remove dead code

Documentation/ReleaseNotes/5.4.md
This PR removes an extra word in the 5.4 release notes.
=> [Release notes] Improve wording

Sources/Commands/APIDigester.swift, Sources/Commands/SwiftTool.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift, Sources/Xcodeproj/generate.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/InMemoryGitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.5] deprecate willClone/didClone in favor of willCreateWorkingCopy/didCreateWorkingCopy

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
=> [5.5] make test discovery generation output predictable

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
Add/delete/refresh package collections lead to frequent deletes in SQLite. This causes the database file size to grow very quickly when we have a huge collection.
Modification:
- Run `VACUUM` after SQLite delete. This repacks the database file and helps reduce its size.
- Don't update FTS tables unless the collection's packages have changed. This helps reduce the number of deletes.
Related to rdar://77077510
=> [Collections] SQLite optimizations

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
This is https://github.com/apple/swift-package-manager/pull/3437 for 5.5
=> [5.5][Collections] SQLite optimizations

Sources/Basics/FileSystem+Extensions.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
=> [5.5] improve location of config directory

Sources/Basics/SQLiteBackedCache.swift
https://github.com/apple/swift-package-manager/pull/3456 for 5.5
=> [5.5] Fix SQL syntax error

Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
https://github.com/apple/swift-package-manager/pull/3461 for 5.5
=> [5.5][Collections] Fix auth token lookup (#3461)

Sources/PackageCollections/PackageCollections+Configuration.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
https://github.com/apple/swift-package-manager/pull/3443 for 5.5
=> [5.5][Collections] Auth tokens need to be mutable (#3443)

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
This is a cherry-pick of #3463.
=> [5.5] Fix resource bundle lookup (cherry-pick of #3463)

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
https://github.com/apple/swift-package-manager/pull/3471 for 5.5
=> [5.5][Collections] Improve error handling (#3471)

Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
https://github.com/apple/swift-package-manager/pull/3477 for 5.5
rdar://77620938
=> [5.5][Collections] Add information about metadata provider to getPackageMetadata result

Tests/PackageCollectionsTests/PackageCollectionsTests.swift
https://github.com/apple/swift-package-manager/pull/3479 for 5.5
=> [5.5] Fix PackageCollectionsTests.testUpdateAuthTokens (#3479)

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
https://github.com/apple/swift-package-manager/pull/3491 for 5.5
Related to rdar://77873780
=> [5.5][Collection] Optimize collection fetch in search methods

Documentation/PackageCollections.md
remove reference specific certificate for now
=> collection doc cleanup

Sources/PackageDescription/SupportedPlatforms.swift, Tests/PackageLoadingTests/PD5_5LoadingTests.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3537
=> [5.5] Add constants for new OS versions

Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Requires https://github.com/apple/swift-package-manager/pull/3565
Only https://github.com/apple/swift-package-manager/commit/fb8d648036e27277e5c7b0da22d367e7ec1dd8c1 is for this PR.
rdar://79528550
=> [Collections] Add listPackages API

Sources/Commands/SwiftTool.swift
This is more forward compatible with adding additional cases that also want to add extra manifest flags here.
=> Change `extraManifestFlags` to be additive

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
https://github.com/apple/swift-package-manager/pull/3611 for 5.5
=> [5.5][Collections] Stale search index data

Sources/PackageCollections/PackageCollections.swift
https://github.com/apple/swift-package-manager/pull/3617 for 5.5
=> [5.5][Collections] Removed local package collection comes back alive

Sources/Workspace/WorkspaceState.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3614
=> [5.5] Do not print workspace-state diagnostic to stdout

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
`populateTargetTrie`, potentially because it's done in a background queue, causes a lot of random crashes in tests (not just in SwiftPM but other projects as well). The exception happens inside SQLite C library and it's not yet clear what the real cause is. However, since most tests do not use the package collections feature at all, `populateTargetTrie` is basically a no-op and therefore doesn't need to be queued.
Modification:
Queue `populateTargetTrie` only if there is package collection data.
This code change doesn't actually fix anything but may perhaps reduce the chance of crashing.
rdar://80840989
=> [Collections] Don't queue populateTargetTrie if there is no data

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Cherry-picking https://github.com/apple/swift-package-manager/pull/3629 and https://github.com/apple/swift-package-manager/pull/3634 to 5.5
=> [5.5][Collections] populateTargetTrie changes

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3638
=> [5.5] Improve diagnostic when automatic resolution is disabled

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/Workspace/Workspace.swift
motivation: cleanup deprecated methods
changes: remove apis deprecated 6m+ ago
=> remove a few deprecated apis

CMakeLists.txt, CONTRIBUTING.md, Package.swift, Sources/Basics/CMakeLists.txt, Sources/Basics/Exports.swift, Sources/Build/BuildPlan.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/Pubgrub/Incompatibility.swift, Sources/PackageGraph/Pubgrub/PartialSolution.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/PubgrubTests.swift, Utilities/bootstrap
brings back https://github.com/apple/swift-package-manager/pull/3595
=> adopt swift-collections

CHANGELOG.md
The change is user-facing, so it should be documented.
Added an entry describing changes introduced in #3486.
Reformatted a few previous entries to be consistent with even earlier entries.
=> [Doc] Add an entry for #3486 in the change log

Sources/Commands/SwiftPackageTool.swift
This has a significant performance boost when running on large projects
=> Run swift-format in parallel mode

Sources/Build/BuildPlan.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
=> [5.5] Pass toolchain settings when using XCBuild

Sources/Basics/HTTPClient.swift, Sources/Basics/SQLiteBackedCache.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift, Sources/PackageCollectionsSigning/PackageCollectionSigning.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/Workspace/Workspace.swift, Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift, Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift, Tests/PackageCollectionsSigningTests/Utilities.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
motivation: adapt new diagnostics apis
changes: refactor the PackageCollections module to use new diagnostics api
=> convert the PackageCollections module to the new diagnostics apis

Tests/WorkspaceTests/WorkspaceTests.swift
This was never a good thing to do, but now that we have v2 of Package.resolved, it is an actively harmful thing to do if the IDE or toolchain being used to build SwiftPM and run the tests is older (e.g. using the 5.5 toolchain but working on main).
What happens is that after the test is run, using the older toolchain on the checkout (such as running `swift build`) results in a "unsupported schema version 2" error for the Package.resolved.
There's not need at all to run this test against SwiftPM itself — a sample package created for the purpose in the usual temporary directory is all that's needed.
rdar://83222890
=> Fix a unit test that is writing to the checkout of SwiftPM itself

Sources/Commands/SwiftTestTool.swift
motivation: code cleanup
changes: remove almost identitical code in the two variants of the test method, and replace with a shared implementation that takes an output redirection and either prints or collects the output
=> reduce duplicate code in test tool

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Allow libSwiftPM clients that can generate manifest source generation to provide a tools version header comment, a list of imports, and custom handling for product types (falling back on default behavior if they don't provide a custom source code fragment for the product).
This provides libSwiftPM clients that programmatically generate package manifests with more flexibility in how they do so.
- allow clients to provide the comment that follows the semicolon in the `swift-tools-version` header (note that this isn’t parsed; it’s intended for informational purposes)
- allow a list of additional imports, such as Foundation
- allow customization of how the product is rendered into a source fragment
- makes SourceCodeFragment available to clients and adds documentation code for it
- add a unit …
=> Allow libSwiftPM clients additional flexibility in the manifest source generation

Sources/Build/BuildPlan.swift
Simplify resource_bundle_accessor.swift
Change "?:" into more swifty "??" operator
Simplify the generated resource_bundle_accessor.swift file
=> [Optimus] Simplify resource_bundle_accessor.swift

Package.swift
Ran `PackageCollectionsSigningTests` locally in `swift:5.5-focal`.
=> Upgrade to swift-crypto 2.0.2

Sources/Build/BuildOperation.swift, Sources/SourceControl/RepositoryManager.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: recent changes to TSC exposed several thread safety issues
changes:
* make build description and graph caches thread safe
* simplify repository manager in-memory cache and make it thread-safe
* adjust tests
=> address thread safety issues

Sources/Basics/VirtualFileSystem.swift, Tests/BasicsTests/VFSTests.swift
This is an implementation of the `FileSystem` protocol that can be written to and read from a JSON file which can be useful for testing.
=> Add a `VirtualFileSystem`

Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/PackageToolTests.swift
When a command plugin has a dependency on an executable, it needs to be built or brought-up-to-date and included in the tool map.
- extended the SwiftPackageTool logic to build these tools first
- other small fixes in the SwiftPackageTool logic for running plugins
- include them in the tools map sent to the command plugin
- extend a unit test to include this local and remote built tools
=> Build local and remote tools depended on by command plugins before running the plugins

Sources/SPMBuildCore/PluginInvocation.swift, Tests/FunctionalTests/PluginTests.swift
Fix a bug with the information provided in the context to plugins when there are multiple packages involved.
- fix the serialization logic to always end up with the right package id
- extend a unit test to check for this
=> Fix a bug in the plugin context where the top-level package was not always the root package

Tests/WorkspaceTests/WorkspaceTests.swift
motivation: ensure resolure works across mixed graphs (source control + regsitry)
changes: add unit test
rdar://82896561
=> add a test for (simple) mixed graph

Sources/Workspace/DefaultPluginScriptRunner.swift
Provide better and more detailed error messages when things go wrong compiling and running plugins
This will help debug exceptional conditions, including in CI.  Regular syntax errors in plugins etc were already being reported.
- add more specific cases to the errors reported by the DefaultPluginScriptRunner
- wrap all of the compiler command line construction in a do-catch block and convert the `try?` to  a `try` rather than paper over a failure to get minimum deployment target on Darwin
- emit the textual output of the compiler as a `info` to the observability scope
- emit more specific error messages, such as the signal number that ended the plugin invocation
=> Provide better and more detailed error messages when things go wrong compiling and running plugins

Sources/PackageRegistry/RegistryClient.swift, Sources/SPMTestSupport/MockPackage.swift, Sources/SPMTestSupport/MockRegistry.swift, Sources/SPMTestSupport/MockWorkspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: better test coverage for registry negative scenarios
changes:
* add tests for server, archiver errrors making sure errors propagate correctly
* improve error messages description in registry client
=> add more registry tests

Sources/PackageRegistry/RegistryClient.swift, Sources/SPMTestSupport/MockPackage.swift, Sources/SPMTestSupport/MockRegistry.swift, Sources/SPMTestSupport/MockWorkspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.6] add more registry tests (#3914)

Package.swift, Sources/Basics/FileSystem+Extensions.swift, Sources/Commands/CMakeLists.txt, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/PackageFingerprint/FilePackageFingerprintStorage.swift, Sources/PackageFingerprint/Model.swift, Sources/PackageFingerprint/PackageFingerprintStorage.swift, Sources/PackageRegistry/CMakeLists.txt, Sources/PackageRegistry/RegistryClient.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SPMTestSupport/MockPackage.swift, Sources/SPMTestSupport/MockPackageFingerprintStorage.swift, Sources/SPMTestSupport/MockRegistry.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/CMakeLists.txt, Sources/Workspace/SourceControlPackageContainer.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/WorkspaceConfiguration.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/3890 for 5.6
=> [5.6] Implement TOFU for package downloads

Sources/PackageGraph/GraphLoadingNode.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/SPMTestSupport/MockPackageContainer.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/SPMTestSupport/misc.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/FileSystemPackageContainer.swift, Sources/Workspace/ManagedDependency.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/WorkspaceState.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.6] Optionally use a per-package filesystem for `PackageBuilder`

Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/Workspace/RegistryPackageContainer.swift, Sources/Workspace/Workspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/SourceControlPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.6] optimize manifest requests for registry based dependencies (#3929)

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
=> [5.6] fix a warning on linux (#3947)

Package.swift
motivation: use the correct minimum version of swift-system
changes: update min version of swift-system to 1.1.1
=> update min version of swift-system

Sources/PackagePlugin/Plugin.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/FunctionalTests/PluginTests.swift
When a plugin throws an uncaught error, it should be reported as a diagnostic rather than causing the standard Swift output.
This is a better user experience than the very technical output that is shown otherwise.
As part of making this work well, we also simplify the way the result code is received from the plugin.  It was a bit awkward to have two result codes (the one from the last message as well as the exit code from the process) so now we just use the exit code.  This is also most robust to any plugin that decides to do "exit(1)" on its own from inside the code.  If/when we have long-running multi-action plugins we can revisit this.
We also make sure that at least one error message is emitted from any plugin that exits with an error code but that does not emit an error diagnostic. …
=> Errors thrown at top level of plugin should be reported as diagnostics

Sources/PackagePlugin/Plugin.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/FunctionalTests/PluginTests.swift
This is the 5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/3957
=> [5.6] Errors thrown at top level of plugin should be reported as diagnostics

Sources/Workspace/Workspace.swift
motivation: additional debug information for resolution errors with overrides
changes: include package location on resolution information log
=> add more information about resolution

Sources/Basics/VirtualFileSystem.swift, Sources/Commands/SwiftTool.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
motivation: TSC FileSystem API changed to add tempDirectory accessor
changes: add tempDirectory accessor in SwiftPM FileSystem implementations
rdar://86644116
=> adjust FileSystem implementations to TSC API changes

Sources/Workspace/Workspace.swift
=> [5.6] add more information about resolution (#3960)

Sources/Basics/VirtualFileSystem.swift, Sources/Commands/SwiftTool.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
=> [5.6] adjust FileSystem implementations to TSC API changes (#3962)

Sources/Workspace/ManagedArtifact.swift, Sources/Workspace/ManagedDependency.swift, Sources/Workspace/WorkspaceState.swift, Tests/WorkspaceTests/WorkspaceStateTests.swift
=> [5.6] gracefully fail workspace state loading when duplicate entries found (#3974)

Tests/XcodeprojTests/FunctionalTests.swift
Tests/XcodeprojTests/FunctionalTests.swift
libary -> library
=> Fixed typo libary -> library

CHANGELOG.md
motivation: document user visible changes in change log
changes: Update CHANGELOG to include configuration files location changes
=> Update CHANGELOG to describe configuration files location changes

CHANGELOG.md
motivation: document user visible changes in change log
changes: Update CHANGELOG to describe Package.resolved 2.0 format
=> Update CHANGELOG to describe new Package.resolved format

Fixtures/Miscellaneous/TestDiscovery/Async/Tests/AsyncTests/SwiftTests.swift, Fixtures/Miscellaneous/TestDiscovery/Deprecation/Package.swift, Fixtures/Miscellaneous/TestDiscovery/Deprecation/Sources/Simple/Simple.swift, Fixtures/Miscellaneous/TestDiscovery/Deprecation/Tests/SimpleTests/SwiftTests.swift, Fixtures/Miscellaneous/TestDiscovery/Simple/Tests/SimpleTests/SwiftTests.swift, Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Sources/Build/BuildPlan.swift, Sources/Build/LLBuildManifestBuilder.swift, Sources/LLBuildManifest/Tools.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/TestDiscoveryTests.swift
=> [5.6] avoid deprecation warnings from test discovery (#3992)

Sources/Workspace/Diagnostics.swift
Needed for https://github.com/apple/swift-tools-support-core/pull/276
=> Add new errors to `FileSystemError.description`

Sources/Workspace/Workspace.swift
5.6 cherry pick of #4017 
---
Explanation:
Limit the concurrent HTTP requests for downloading binary dependencies to `n` concurrent requests. User reported having a fairly large Package.swift with 50 binary dependencies. In total the size of these 50 zip files is 400 MB. On a slower internet connection (16 MBit) the `swift package resolve` command errors out with some HTTP timeouts. It seems the main problem is that all 50 HTTP requests are executed at the same time.
Scope of Issue: 
This impacts the reliability of SwiftPM when resolving graphs with many binary dependencies.
Reason for Nominating to 5.6 : 
Important reliability fix for real-world use case.
Risk: 
Low risk; No functional changes, this limits the amount of concurrent requests using a semaphore.
Reviewed By: @tomerd …
=> [5.6] Limit concurrent HTTP requests when downloading binary dependencies

Sources/PackageLoading/ManifestLoader.swift
motivation: improve dependency resolution performance
changes: use semaphore instead of operation queue when loading manifests which has lower overhead and allows us to manage the concurrency more accurately as the operation queue syle did not wait for the loading to complete
=> manifest loading performance

Sources/Build/BuildOperation.swift, Sources/SPMBuildCore/PluginInvocation.swift, Tests/CommandsTests/PackageToolTests.swift
Emit output and diagnostics from build tool plugin invocations as diagnostics.
Printed output and emitted diagnostics were not being shown in the `swift build` CLI, and this made it difficult to see what build tool plugins were doing (note that this is distinct from command plugins, which are invoked differently and where output is already emitted).
- make BuildOperation emit output text and diagnostics from the build tool plugin results
- add more fields to the build tool plugin result structure
Errors and warnings from a build tool plugin are emitted by default, and general `print()` output is emitted as `.info` in this PR.  A future PR should introduce a new `.output` log level that is emitted by default, without having to specify `-v`, but this will require more …
=> Emit output and diagnostics from build tool plugin invocations as diagnostics

Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/PackageToolTests.swift
Command plugins can call back to SwiftPM to build one or more targets.  But the parameters passed by the plugin weren't being passed through to the BuildOperation, which instead used the ones that had been set on the SwiftTool.  The set of returned built artifacts also wasn't fixed properly.
This fixes bugs in the documented behavior or package command plugins, a new feature in SwiftPM 5.6.
- add parameters to SwiftTool.createBuildOperation() to allow build parameters and log level to be customized
- pass through the parameters that had been been received by SwiftPackageTool
- filter the returned artifacts based on not just what could be built but what was requested to be built
- properly collect the log based on the verbosity level and pass it on back to the plugin
- add a unit test to …
=> Fix bugs in builds that are run from a command plugin

Sources/Build/BuildOperation.swift, Sources/SPMBuildCore/PluginInvocation.swift, Tests/CommandsTests/PackageToolTests.swift
This is the 5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/4037.
=> [5.6] Emit output and diagnostics from build tool plugin invocations as diagnostics

Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/PackageToolTests.swift
This is the 5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/4039.
=> [5.6] Fix bugs in builds done on request from command plugins

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/PackageCollections+Configuration.swift, Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift, Tests/PackageCollectionsSigningTests/CertificateTests.swift, Tests/PackageCollectionsSigningTests/KeyTests+EC.swift, Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift, Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift, Tests/PackageCollectionsSigningTests/SignatureTests.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/4036 and https://github.com/apple/swift-package-manager/pull/4004 to 5.6
=> [5.6][Collections] Honor --config-path and --cache-path options

Sources/PackagePlugin/PackageModel.swift, Tests/CommandsTests/PackageToolTests.swift
This is the SwiftPM 5.6 nomination of https://github.com/apple/swift-package-manager/pull/4044.
=> [5.6] Fix the `Target.recursiveTargetDependencies` plugin API function

Sources/Build/BuildPlan.swift
This adjusts the output file map writing code to ensure that we emit the
proper native path string and correct escaping of `\` which otherwise
yields invalid JSON which cannot be deserialized subsequently.  This
will be critical to enabling the use of swift-driver with SPM.
=> Build: correct emitted output file map

Tests/PackageCollectionsTests/PackageIndexTests.swift
https://github.com/apple/swift-package-manager/pull/4058#issuecomment-1023881874
=> Disable cache usage in package index tests

Sources/Basics/VirtualFileSystem.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
motivation: new APIs added to FileSystem: isReadable/isWriteable
changes: implement isReadable/isWriteable in all SwiftPM's FileSystem implementations
=> adjust FileSystem implementation to new APIs

Tests/SourceControlTests/RepositoryManagerTests.swift
=> [Test] Disable a flaky test (RepositoryManagerTests.testConcurrency) while investigating

Sources/Basics/AuthorizationProvider.swift
=> [5.6] update netrc auth provider to read file "live"

Tests/CommandsTests/PackageToolTests.swift
Disable a flaky part of the unit test `PackageToolTests.testPluginCom pilationBeforeBuilding`.  Filed https://bugs.swift.org/browse/SR-15831 to investigate and fix it.
We don't want to skip the entire test since there are other good things being tested here that are not flaky, such as some of the other output as well as the exit code of the subprocess.
This also fixes a separate mistake in the test, which is not relevant to this flakiness but may cause confusion because the terminology in a fixture is wrong.
=> Disable a flaky part of the unit test `PackageToolTests.testPluginCom pilationBeforeBuilding`

Sources/PackageLoading/ManifestJSONParser.swift
motivation: TSC URL is deprecated
changes: migrate the url scheme extraction code to the one call site that needs it
=> fix warning from using deprecated TSC URL API

Tests/FunctionalTests/ModuleAliasingTests.swift
=> Update module aliasing functional tests 

Sources/Commands/SwiftTool.swift
motivation: diagnostics with "location prefix" print that prefix before the diagnostics severity prefix (eg warning, errror) which is less clear
changes:
* always print severity prefix first
* reduce overhead when printing diagnostics by avoiding redundant stream flushes
=> improve the readabilty of diagnostics that have a "location prefix"

IntegrationTests/Package.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, IntegrationTests/Tests/IntegrationTests/Helpers.swift, IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift, IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift, Sources/Workspace/InitPackage.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/WorkspaceTests/InitTests.swift
Reverts apple/swift-package-manager#4133
requires changes to the swift integration test suite
=> improve example created by package init --type executable

Sources/PackageLoading/ManifestJSONParser.swift
motivation: make code easier to reason about
changes:
* rename "fixDependencyLocation" to "sanitizeDependencyLocation" to reflect what it does
* restructure the code in sanitizeDependencyLocation to be easier to reason about
=> cleanup dependency location sanitization in manifest parser

Fixtures/Miscellaneous/ModuleAliasing/DirectDeps/AppPkg/Package.swift, Fixtures/Miscellaneous/ModuleAliasing/DirectDeps/GamePkg/Package.swift
=> Fix module aliasing integration test fixture

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
=> Handle moduleAliases with source code fragment

Tests/FunctionalTests/PluginTests.swift
motivation: cleaner code
changes
* use string form of writeFileContents
* do not wrap fixtures with try/catch
=> use newer testing conventions in plugin tests 

Sources/Commands/SwiftPackageTool.swift, Sources/Xcodeproj/generate.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift
motivation: namespaced code is good code
changes: move global funcitons in the XcodeProject module to a namespace
=> move global functions to a namespace

README.md
Fix README.
Code span in README was incorrect.
I Fixed code span in README.
README has been reformatted.
=> Fix code span in README

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageModel/Target.swift, Tests/BuildTests/BuildPlanTests.swift
Support module aliasing for multiple root packages 
Add module alias tracker API
Resolves rdar://88518683
=> Module aliasing: allow multiple root packages

Sources/Basics/HTPClient+URLSession.swift
Motivation:
`HTTPClient` automatically sets `Authorization` HTTP header if `AuthorizationProvider` can locate user credentials. It is not doing that for redirected requests, however.
Modifications:
Update `URLSessionHTTPClient` to make use of `AuthorizationProvider` in redirection handler.
=> HTTPClient should set Authorization header for redirected requests

Sources/PackageDescription/PackageDependency.swift, Sources/PackageDescription/Target.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
=> Enable moduleAliases in 5.7

Sources/PackageGraph/PackageGraph+Loading.swift
Use explicit labels, use .contains for better readability, etc.
=> Update code readability

Sources/Workspace/UserToolchain.swift
This is pretty much a macOS specific change. Today, `UserToolchain` on macOS pretty much entirely uses `xcrun` to find tools which isn't necessarily appropriate for all clients. This adds the optional ability for clients to pass in explicit search paths at which point we'll never shell out to `xcrun` and only exclusively use those explicit search paths.
=> Optional explicit search paths for `UserToolchain`

Fixtures/Miscellaneous/SwiftRun/Package.swift, Fixtures/Miscellaneous/SwiftRun/main.swift, Sources/Commands/SwiftTool.swift, Tests/FunctionalTests/MiscellaneousTests.swift
This is a cherry-pick PR of #4224, #4235, and #4250 for Swift 5.6.
(CC: @tomerd)
rdar://90574791
=> [5.6] Fix SIGINT handling during `swift run` (Cherry-pick of #4224, #4235, #4250)

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Sources/PackageModel/UserToolchain.swift
Repair the Windows build after #4255 and #4256 changed things without
testing on Windows.
=> repair the build after #4255, #4256

Tests/FunctionalTests/ModuleAliasingTests.swift
Reverts apple/swift-package-manager#4128
=> Revert "troubleshoot module aliasing"

Sources/PackageModel/UserToolchain.swift
Add in a migration path for adjusting the layout of the toolchain.  This
is required in order to support more than one architecture SDK to be
installed simultaneously.  The problem is primarily on the XCTest side,
where the binary is not slotted to an architecture.  Having multiple
variants of XCTest is difficult with the toolchain layout.  The XCTest
installation is located at
`%DEVELOPER_DIR%\Platforms\<Platform>.platform\Library\XCTest-<version>`.
The runtime component is located under, and the DLL is always named
`XCTest.dll`.  The following options were considered:
1. renaming `XCTest.dll` to:
- `XCTest32.dll` (x86)
- `XCTest64.dll` (x64)
- `XCTest32a.dll` (ARMv7)
- `XCTest64a.dll` (ARM64)
2. renaming `bin` to:
- `bin32` (x86)
- `bin64` (x64)
- `bin32a` (ARMv7)
- `bin64a` (ARM64)
3. …
=> PackageModel: adjust toolchain layout for Windows

Tests/FunctionalTests/ModuleAliasingTests.swift
=> Re-enable module aliasing functional test

Sources/Basics/SwiftVersion.swift
=> Update the Swift version to 5.6.1

Sources/PackageModel/UserToolchain.swift
This corrects a long standing issue in locating XCTest on Windows.  We
erroneously assumed that we could use `DEVELOPER_DIR` to construct a
path to XCTest.  However, this is not correct for two reasons:
1. We may be targeting something other than Windows
2. We may have passed `-sdk` explicitly, which would move the
location of the SDK to something that no longer is relative
to `DEVELOPER_DIR`.
Instead, we now construct the path relative to `SDKROOT` OR the explicit
SDK specified.  This reduces the dependency on the environment, and
makes `SDKROOT` behave as intended as well as completely drops the need
for `DEVELOPER_DIR` within SPM.
This will also restore the ability for us to have relocatable SDK
installations on Windows which eases some local testing for parallel SDK
installations. …
=> PackageModel: correct and improve XCTest location on Windows

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
=> [5.7] update CommandTaskTracker to match llbuild's reporting of CustomTasks

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageModel/Sources.swift, Tests/BuildTests/BuildPlanTests.swift
Module aliasing: validate source files / only allow Swift files for modules aliased
Resolves rdar://90661600
=> [5.7] Module aliasing: validate source files / only allow Swift files for modules aliased

Sources/Commands/Options.swift, Sources/Workspace/Workspace+Configuration.swift, Sources/Workspace/Workspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
=> Change default FingerprintCheckingMode to 'strict'

Sources/Commands/Options.swift, Sources/Workspace/Workspace+Configuration.swift, Sources/Workspace/Workspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
=> [5.7] Change default FingerprintCheckingMode to 'strict'

Package.swift
Motivation:
With https://github.com/apple/swift-crypto/pull/94, swift-crypto's
`Crypto` depends on `CCryptoBoringSSL` conditionally, on non-Apple
platforms only.
Since `PackageCollectionsSigningLibc` imports `CCryptoBoringSSL`
through `Crypto`, it fails to compile on Apple platforms.
Modifications:
Define `PackageCollectionsSigningLibc` target and associated
dependencies conditionally on platforms where it's available.
I tried using `.target(name:when:)` in combination with dynamic target
array, but got source not found error for
`PackageCollectionsSigningLibc`.
I also tried just changing target dependency on
`PackageCollectionsSigningLibc` to be conditional, but apparently
`PackageCollectionsSigningLibc` still gets compiled despite not being
used, thus causing build to fail.
=> Make 'PackageCollectionsSigningLibc' target conditional

Sources/PackageLoading/ToolsVersionParser.swift
We lost this in the 5.4 refactoring of tools-version parsing.
=> Restore unsupported tools-version error

Package.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/4311 to 5.7
=> [5.7] Make 'PackageCollectionsSigningLibc' target conditional

Package.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/4311 to 5.6
=> [5.6] Make 'PackageCollectionsSigningLibc' target conditional

Fixtures/Miscellaneous/PluginGeneratedResources/Package.swift, Fixtures/Miscellaneous/PluginGeneratedResources/Plugins/Generator/plugin.swift, Fixtures/Miscellaneous/PluginGeneratedResources/Sources/PluginGeneratedResources/PluginGeneratedResources.swift, Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan.swift, Sources/Build/LLBuildManifestBuilder.swift, Sources/Commands/SwiftTool.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/PackageModel/Target.swift, Sources/SPMBuildCore/PrebuildCommandResult.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/PackageGraphTests/TargetTests.swift
=> [5.7] Handle generated resources from plugins

Tests/FunctionalTests/MiscellaneousTests.swift
5.7 cherry-pick of https://github.com/apple/swift-package-manager/pull/4321
=> [5.7] rdar://92275318 (Swift CI Unblock:OSS - Swift Incremental RA - macOS - Apple Silicon - testPluginGeneratedResources Failure)

Sources/Workspace/Workspace+BinaryArtifacts.swift
motivation: in some case duplicate artifacts or parallel processes may race the extraction of binary artifacts
changes:
add a file system lock around archive extraction of local archives, similar to what we do for remote archives
rdar://92622234
=> make local binary archives extraction more resilient

Sources/Workspace/Workspace+BinaryArtifacts.swift
=> [5.7] make local binary archives extraction more resilient

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageModel/Target.swift, Tests/BuildTests/BuildPlanTests.swift
Update module alias tracker 
Move module aliases setting per target into alias tracker 
Improve perf
Handle edge cases
Add more tests
Resolves rdar://90337780
=> [Module Aliasing] Update alias tracker / handle edge cases

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageModel/Target.swift, Tests/BuildTests/BuildPlanTests.swift
Update module alias tracker
Handle edge cases
Improve perf
Add more tests
Resolves rdar://90337780
=> [5.7] Update module alias tracker / handle edge cases

Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
Use the explicit path constructors to build the paths rather than
spelling out the paths explicitly with a non-placeholder path component
separator.  This enables these tests to pass on Windows.
=> Tests: clean up modulemap generation tests for paths

Tests/BuildTests/BuildPlanTests.swift
This adjusts most of the tests to use the path composition rather than
explicitly writing out the paths.  We now use the constructed context
for generating the expectations which should make it easier to change
expectations in the future should it be desired.
~This allows a significant portion of this test suite to now pass on
Windows (down to 11 failures from about 80).~
The BuildPlanTests suite fully passes on Windows now.
=> Tests: adjust BuildTests to compose paths

Sources/Commands/SwiftTestTool.swift
=> [5.7] fix concurrent access issue when running tests in parallel

Tests/XCBuildSupportTests/PIFTests.swift
This adjusts paths to accommodate non-UNIX platforms.
=> Tests: make the PIF tests pass on Windows

Sources/PackageGraph/PackageGraph+Loading.swift, Tests/BuildTests/BuildPlanTests.swift
Besides different alias values, we also need to detect if there's no alias for the same key. 
Resolves rdar://92990727
=> Update conflicting alias detection

Sources/PackageGraph/PackageGraph+Loading.swift, Tests/BuildTests/BuildPlanTests.swift
Besides different alias values, we also need to detect if there's no alias for the same key.
Resolves rdar://92990727
=> [5.7] Update conflicting alias detection

Sources/SourceControl/GitRepository.swift
Rather than redirecting the file list from a file, pass the files on the
command line.  This avoids an unnecessary file write as well as a
subshell.  Furthermore, it makes the command more portable and enables
this to now succeed on Windows.
=> SourceControl: remove unnecessary shell usage

Sources/Workspace/Workspace+State.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.7] reload workspace state before reloading package graph

Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/PackageToolTests.swift
Added additional description for swift-package init -help command explaining what each type means
I added description using swift-argument-parser @Option which was discussed in #4701. Also added several small unit tests on this behaviour
=> #4701 - Resolves SR-10803

Sources/PackageLoading/PkgConfig.swift, Tests/PackageLoadingTests/PkgConfigParserTests.swift
Windows does not have a distributed pkg-config installation and we need
to stub that out for tests.
=> PackageLoading: introduce new entry points for testing

Tests/PackageLoadingTests/PackageBuilderTests.swift
Update the test expectations to use `AbsolutePath` for the construction
of the path literals in order to support non-`/` path separator
characters.  This allows these test expectations to match on Windows.
=> Tests: adopt `AbsolutePath` APIs for path construction

Tests/BasicsTests/VFSTests.swift
Windows requires that we have the destination exist before we create the
file to disambiguate between the file and directory symbolic link case.
Swap the ordering of the fixture creation to accommodate this.
The `isExecutable` check on Windows is more restrictive, identifying
only binary executables rather than scripts.  As a result, we must
disable one of the checks.
=> Tests: adjust VFS tests for Windows

Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
This adjusts the Package Loading test suite to use `AbsolutePath` to
represent and perform path operations.  This allows flexibility for
differing path separator characters (e.g. `\` on Windows).
=> Tests: adopt `AbsolutePath` in more of the PackageLoadingTests

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.7] Avoid loading duplicated packages if a root overrides a local dependency

Documentation/ModuleAliasing.md
User guides
Resolves rdar://88839880
=> Add Module Aliasing documentation

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SPMTestSupport/Observability.swift, Tests/PackageGraphTests/PubgrubTests.swift
=> [5.7] fix an edge case where dependency resolution can go into endless loop 

Sources/PackageGraph/DependencyMirrors.swift, Tests/WorkspaceTests/PinsStoreTests.swift
=> [5.7] fix mirrors reverse mapping to be more deterministic

Documentation/Plugins.md
Update the plugins documentation, especially in light of the XcodeProjectPlugin module in Xcode 14 Beta.
- clarify and improve the language for PackagePlugin and plugins in general
- add brief description of how to use IDE-specific extension libraries, such as XcodeProjectPlugin
=> Updates to the Plugins.md documentation

Documentation/ModuleAliasing.md
Updated example / requirements
=> Updates to module aliasing doc

Documentation/ModuleAliasing.md
Updates to overriding method
More detailed example
=> Doc updates to module alias overriding

Utilities/bootstrap
Reverts apple/swift-package-manager#5611
=> Revert "Do not test inferior Swift libraries on Darwin"

Tests/FunctionalTests/MiscellaneousTests.swift
changes: disable unstable test
=> [Test] Disabled testSwiftRunSIGINT.

Utilities/bootstrap
Otherwise this crashes if you don't pass it any args
=> Mark bootstrap command as required

Sources/PackageGraph/ModuleAliasTracker.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift
=> Fix a typo / add more tests

Sources/Basics/Cancellator.swift
=> [5.7] Do not try to interrupt/terminate a process if it isn't running

Sources/PackageDescription/SupportedPlatforms.swift, Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
=> Handle invalid custom platform version

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
=> [5.7] improve heuristics for @main support

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
Reverts apple/swift-package-manager#5678
=> Revert "improve heuristics for @main support"

Sources/Commands/SwiftTestTool.swift
motivation: --show-codecov-path is only relevant after running test with test coverage
changes:
* only allow the use of --show-codecov-path when running swift test with --enable-code-coverage
* remove the dedicate "swift test show-codecov-path" subcommand
* print code coverage path at the end of test coverage invocation, when flag is set
rdar://88464565
=> improve "swift test --show-codecov-path"

Sources/Build/BuildPlan.swift
=> `Bundle.module` should be a constant.

Sources/Build/BuildPlan.swift
=> [5.7] `Bundle.module` should be a constant

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace+Configuration.swift, Sources/Workspace/Workspace.swift
=> [5.7] Improve warning for deprecated collections config

Sources/PackageFingerprint/FilePackageFingerprintStorage.swift, Sources/PackageFingerprint/PackageFingerprintStorage.swift, Sources/SPMTestSupport/MockPackageFingerprintStorage.swift, Sources/Workspace/SourceControlPackageContainer.swift, Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/5776 to 5.7
=> [5.7] Add hash of source control URL to fingerprint filename to help disambiguate

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Path-based package dependencies were being written out as absolute during manifest source generation, even though relative is almost always (if not always) the right thing to write out in order to avoid creating packages that only work on the local machine.
- add a `packageDirectory` parameter to `generateManifestFileContents()` to specify where the package containing the manifest is located
- use this directory to make path-based dependencies relative
- remove the old compatibility wrapper `generatedManifestFileContents` which no longer makes sense (clients can easily switch to the regular function)
- adjust and extend unit test that covers manifest source generation for package dependencies
- in particular, that test is now more realistic to the kinds of packages that are actually …
=> Swift package manifest generation should not write out absolute paths for path-based package dependencies

Sources/Basics/Observability.swift, Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Sources/Build/SPMSwiftDriverExecutor.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/Model/PackageTypes.swift, Sources/PackageCollections/Model/TargetListResult.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageGraph/DependencyMirrors.swift, Sources/PackageGraph/DependencyResolver.swift, Sources/PackageLoading/IdentityResolver.swift, Sources/PackageLoading/ToolsVersionParser.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/PackageModel.swift, Sources/PackageModel/PackageReference.swift, Sources/Workspace/Workspace+Configuration.swift, Sources/Workspace/Workspace.swift, Tests/BasicsTests/ObservabilitySystemTests.swift
Reverts apple/swift-package-manager#5756
=> Revert "Remove most deprecated APIs"

Sources/PackageLoading/ManifestJSONParser.swift, Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
=> Do not crash on invalid file URLs

Sources/Build/LLBuildManifestBuilder.swift
Replacing it with 'externalTargetModuleDetailsMap'.
=> Switch away from using a deprecated Driver 'init' with 'externalTargetModulePathMap' argument.

Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
The absolute path was not absolute, but when constructing an `AbsolutePath` we would use the current drive as the path is current drive relative.  In debug builds, this would trigger an assertion failure in swift-tools-support-core.  Adjusting the path representation to be OS dependent fixes the assert.
Additionally, adjust the path representation that is used to compare the string literals. Because the path representation is converted to a native representation, we must expectation values accordingly.
=> Tests: repair `testPackageDependencyVariations` on Windows

Tests/BuildTests/BuildPlanTests.swift
Looks like I missed a few here.
=> Fix path-related deprecation warnings

Documentation/Plugins.md, Documentation/README.md, README.md
This should improve the discoverability of these resources.
=> Link new-ish md files and WWDC sessions

Sources/Basics/SwiftVersion.swift, Sources/Build/BuildPlan.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageModel/PackageModel.swift, Sources/PackageModel/ToolsVersion.swift, Sources/PackagePlugin/PackageModel.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
=> Update current version to 5.8

Sources/XCBuildSupport/CODEOWNERS, Sources/XCBuildSupport/XCBuildMessage.swift
=> XCBuildMessage: add Sendable annotations to relevant types

Sources/Build/BuildPlan.swift, Sources/Commands/PackageTools/PluginCommand.swift, Sources/PackagePlugin/Context.swift, Sources/PackagePlugin/Errors.swift, Sources/PackagePlugin/Plugin.swift, Sources/PackagePlugin/PluginMessages.swift, Sources/SPMBuildCore/BinaryTarget+Extensions.swift, Sources/SPMBuildCore/PluginInvocation.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
=> Pass supported triples info to invoke/run plugin for better diagnostics

Sources/SPMBuildCore/PluginInvocation.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
=> Error and exit early if prebuild command references built tool

Tests/SourceControlTests/GitRepositoryTests.swift
motivation: Recent versions of git made a security fix to disallow the file transport by default. The GitRepository submodule test cases fail with these recent versions, because they use local submodules which rely on the file transport.
changes: The GitRepositoryTests submodule tests set the environment variable GIT_ALLOW_PROTOCOL=file to tell git to allow use of the file protocol only for these tests where it's required.
credit for this change to @dtweston
(cherry picked from commit 36c222ead99fe5976d2dac6a70907a8f9ea3bc10)
=> [5.7] update submodules tests to set GIT_ALLOW_PROTOCOL = file (#5914)

Sources/PackageGraph/PinsStore.swift
motivation: reduce target dependencies
changes: remove redundant import of SourceControl in PackageGraph
=> remove an unnecessary import

Sources/PackageGraph/PinsStore.swift
=> [5.8] remove an unnecessary import

Sources/Basics/NSLock+Extensions.swift, Sources/Basics/SQLite.swift, Sources/PackageGraph/ModuleAliasTracker.swift, Sources/PackageModel/BuildFlags.swift, Sources/SPMSQLite3/sqlite.h, Tests/BasicsTests/TemporaryFileTests.swift, Tests/BuildTests/MockBuildTestHelper.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift
motivation: make sure code is consistent with soundness rules
changes: run Utilities/soundness script and address all reported issues
=> address soundess issues reported by soundness script

Sources/Basics/AuthorizationProvider.swift, Sources/Basics/Netrc.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftTool.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/RegistryConfiguration.swift, Sources/PackageRegistryTool/SwiftPackageRegistryTool.swift, Sources/Workspace/Workspace+Configuration.swift, Sources/Workspace/Workspace.swift, Tests/BasicsTests/AuthorizationProviderTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/CommandsTests/SwiftToolTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/PackageRegistryTests/RegistryConfigurationTests.swift, Tests/WorkspaceTests/AuthorizationProviderTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/5838 to 5.8
=> [5.8] Add token authentication support to SwiftPM

Sources/Commands/ToolWorkspaceDelegate.swift, Sources/CoreCommands/MinimalBuildTool.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift
This is the 5.8 nomination of https://github.com/apple/swift-package-manager/pull/6020.
=> [5.8] Pass along the duration in the remaining WorkspaceDelegate calls as well (#6020)

Package.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/5920 to 5.8
rdar://82934196
=> [5.8] Swift to swift-crypto v2.x

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageRegistry/RegistryDownloadsManager.swift, Sources/SPMTestSupport/MockManifestLoader.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift, Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift, Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.8] update purge cache to warn when failing to delete files

Sources/Basics/SwiftVersion.swift, Sources/PackageModel/ToolsVersion.swift
https://github.com/apple/swift/pull/63014
=> Update the version to 5.9

Sources/Basics/SwiftVersion.swift
https://github.com/apple/swift/pull/63038
=> Bump the Swift version to 5.7.3

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageModel/PackageModel.swift, Sources/PackageModel/Target.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Enable use of product ID to distinguish duplicate product names
Resolves rdar://102138022
=> [5.8] Enable use of product ID to distinguish duplicate product names

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
If a command gets marked as cancelled from the llbuild side, we currently do not care at all and treat the build as successful which can be confusing for the user. This at least makes sure clients are notified via the delegate and the build complete message is altered.
rdar://104425290
=> Minimal handling of cancellation

Sources/PackageLoading/PackageBuilder.swift, Tests/BuildTests/BuildPlanTests.swift
Align with the compiler flag. Fixes rdar://104718540
=> Rename `-enable-future-feature` to `-enable-upcoming-feature` (#6084)

Sources/PackageRegistryTool/SwiftPackageRegistryTool.swift
`getpass` is an obselete function as per POSIX and is unavailable on windows.  Replicate the behaviour with `SetConsoleMode` and `ReadConsole`.  We assume that we can use the standard definition of `PASS_MAX` (255) for the value.  The usage requires that we replicate the behaviour of a leaked global buffer.
=> PackageRegistryTool: repair the Windows build

Sources/SourceControl/Repository.swift
motivation: less warning, stable CI
changes: add few sendable annotations to address warning / errors
=> fix few sendable warning

Sources/Basics/FileSystem/AsyncFileSystem.swift, Utilities/soundness.sh
motivation: make soundness check more robust
changes:
* test formatting in changed files
* address current soundness violations
=> improve soundness script

Sources/PackageRegistry/RegistryClient.swift, Sources/Workspace/Workspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
=> [5.8] improve registry identity lookup cache

Sources/CoreCommands/Options.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistryTool/SwiftPackageRegistryTool+Auth.swift, Sources/PackageRegistryTool/SwiftPackageRegistryTool+Publish.swift, Sources/PackageRegistryTool/SwiftPackageRegistryTool.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
motivation: support publishing to registry
changes:
* split SwiftPackageRegistryTool to multiple files as its growing large
* add "swift package-registry publish" command
* implement client side for registry requirments API
* add test
=> initial support for registry publishing

Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift, Sources/Workspace/Workspace.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
motivation: make progress on publishing from SwiftPM to a registry
changes:
* implement the publishing API in RegistryClient
* integrate the API into the publishing flow
* add tests
=> publishing API implementation 

Sources/PackageRegistry/RegistryClient.swift
motivation: improve registry support
changes:
* improve registry headers parsing
* improve error handling
=> improve support for registry based dependencies

Tests/BuildTests/BuildPlanTests.swift
=> Unblock CI - testPackageNameFlag 

Fixtures/Collections/JSON/good.json, Fixtures/Collections/JSON/good_signed.json, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageCollectionsModel/Formats/v1.md, Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift, Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/Utility.swift
=> Add package identity support to package collection

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
motivation: address warning from deprecation of LazyCache
changes: in BuildExecutionContex use ThreadSafeBox instead of LazyCache
=> use ThreadSafeBox instead of LazyCache

Sources/PackageRegistry/RegistryClient.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
motivation: check registry availability before assuming it is ready to use
changes:
* add API in registry client to support  new availability endpoint
* add tests
* remove dead code
=> add support for registry availability endpoint

Sources/Basics/Observability.swift, Sources/PackageModel/PackageIdentity.swift, Sources/PackageRegistry/Registry.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/RegistryConfiguration.swift, Sources/PackageRegistry/RegistryDownloadsManager.swift, Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift, Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift, Sources/PackageRegistryTool/PackageRegistryTool.swift, Sources/SPMTestSupport/MockRegistry.swift, Sources/Workspace/Workspace.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/PackageRegistryTests/RegistryConfigurationTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: improved registry support
changes:
* make use of availability information when persent
* improve handling of 404 responses
* add and improve tests
=> further improvements to registry API handling

Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift, Fixtures/Miscellaneous/PackageNameFlag/barPkg/Package.swift, Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildOperation.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/CoreCommands/SwiftTool.swift, Sources/DriverSupport/DriverSupportUtils.swift, Sources/PackageModel/PackageModel.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/APIDiffTests.swift
* Check supported flags in the built-in driver since they might differ from the frontend flags
* Cache supported flags in DriverSupport for better performance
* Add a tools version check to allow passing -package-name
Resoles rdar://105305875
=> Check driver supported flags and manifest toolsversion when passing -package-name

Sources/PackageSigning/SignatureProvider.swift, Sources/PackageSigning/SigningIdentity.swift
`#if` of imports need to match the implementation.
=> Fix `PackageSigning`

Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/RegistryConfiguration.swift, Sources/PackageRegistry/SignatureValidation.swift, Sources/SPMTestSupport/MockRegistry.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/PackageRegistryTests/RegistryConfigurationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Also change default onUnsigned and onUntrustedCert to log warning instead of prompt since the latter is not yet supported.
=> Wire up SignatureValidation in RegistryClient

Sources/PackageDescription/BuildSettings.swift, Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/PackageDescriptionSerializationConversion.swift, Sources/PackageDescription/Product.swift, Sources/PackageDescription/Resource.swift, Sources/PackageDescription/Target.swift
- add missing availability annotations
- remove use of get/set pattern that doesn't seem to useful anymore
- fix visibility issues
- update use of enums
=> Clean up manifest APIs

Sources/Build/LLBuildManifestBuilder.swift
As more changes will be made to this file, let's keep the formatting changes separate. This only contains results of applying SwiftFormat to the file.
=> [NFC] Build: format `LLBuildManifestBuilder.swift`

Sources/PackageSigning/SignatureProvider.swift, Sources/PackageSigning/SigningIdentity.swift, Sources/PackageSigning/X509Extensions.swift, Tests/PackageSigningTests/SigningEntityTests.swift, Tests/PackageSigningTests/SigningIdentityTests.swift, Tests/PackageSigningTests/SigningTests.swift
It should be os(macOS) not canImport(macOS) :facepalm
=> implementationOnly import Security and fix some platform checks

Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/RegistryConfiguration.swift, Sources/PackageRegistry/SignatureValidation.swift, Tests/PackageRegistryTests/SignatureValidationTests.swift
motivation: allow for promp UX when desired
changes: define delegate methods to allow clients to drive prompt behavior
=> initial plumbing for prompting on unsigned on untrusted pacakges

Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/SigningEntityTOFU.swift, Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift, Sources/PackageSigning/SigningEntity/PackageSigningEntityStorage.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: nicer CLI UX
changes:
* update output and diangostics format
* adjust any tests that check specific output
=> improve diagnostics and outputs for registry dependencies

Sources/Workspace/InitPackage.swift
New packages shouldn't have spelling mistakes in source code comments.
Change the text in a string emitted as new source code.
=> Fix a spelling mistake in the source files generated for a new package

Sources/Basics/AuthorizationProvider.swift, Sources/Commands/ToolWorkspaceDelegate.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/SignatureValidation.swift
motivation: easier debugging
changes:
* add info logging for actions that may be interesting to users
* add debug logging to assist troubleshooting
=> add logging to registry flows

Sources/SPMLLBuild/CMakeLists.txt
Remove a duplicated link in the closure.
=> SPMLLBuild: remove duplicated link

Sources/PackageRegistry/RegistryConfiguration.swift
We didn't actually security when merging.
=> Fix global security config

Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift, Sources/PackageRegistryTool/PackageRegistryTool+Sign.swift, Tests/CommandsTests/PackageRegistryToolTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
Implement changes as proposed in amendent to SE-0391: https://github.com/apple/swift-evolution/pull/1977
=> Sign package release metadata at publication time

Sources/Basics/Concurrency/ThreadSafeBox.swift
- Offer a mutate function
- Offer an append function for boxed strings
=> Improvements to `ThreadSafeBox`

Sources/PackageDescription/BuildSettings.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Tests/BuildTests/BuildPlanTests.swift
This reverts commit 4006737e9dad74ecf6dd9de6845b1a91ba28c320.
=> Revert "Add build setting for enabling the builtin module (#6311)"

Sources/Workspace/Workspace+Configuration.swift
motivation: better user experience
changes: catch the JSON error and wrap it with a more detailed diagnostics
=> improve diagnostics when registry configuration is broken

Sources/Basics/Errors.swift, Sources/Basics/HTTPClient/URLSessionHTTPClient.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
motivation: improved user experience
change: override the default description of nserror (in registry client only) and produce a more user friendly diagnostics
=> better diagnostics for networking errors

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/SPMTestSupport/ManifestExtensions.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.9] better diagnostics when potentially duplicate packages are found

Sources/Basics/Errors.swift, Sources/Basics/HTTPClient/URLSessionHTTPClient.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
=> [5.9] better diagnostics for networking errors

Sources/Workspace/Workspace+Configuration.swift
=> [5.9] improve diagnostics when registry configuration is broken

Sources/Commands/PackageTools/Config.swift, Sources/PackageGraph/DependencyMirrors.swift, Sources/PackageGraph/PinsStore.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/WorkspaceTests/MirrorsConfigurationTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.9] cleanup mirror config command

Documentation/Registry.md
Cherry pick https://github.com/apple/swift-package-manager/pull/6275 to 5.9
=> [5.9] Update registry service spec per SE-0391

Sources/PackageMetadata/PackageMetadata.swift
This exposes all of the version-specific metadata, not just the readme URL. For convenience, this is still flattened and only the metadata for the latest version is available, but I have also added a `latestVersion` property if we are taking metadata from a specific version to indicate where it is from.
(cherry picked from commit 8c6d925b6c9a1a39d963dd9e98e57e59556b5fd3)
=> rdar://107033737 (Expose `PackageVersionMetadata` from `PackageSearchClient`)

Documentation/PackageRegistryUsage.md
=> [5.9] Documentation on registry usage

Sources/Workspace/Workspace.swift
=> [5.9] sort identities from url lookup to make lookup result consistent 

Sources/Basics/Cancellator.swift, Sources/swiftpm-xctest-helper/main.swift, Tests/PackageCollectionsSigningTests/Utilities.swift
(cherry picked from commit 6c99ed504d46961541aa1d845a35901d126c2fc9)
=> [5.9] A few fixes for building SwiftPM for MacCatalyst

Sources/Workspace/Workspace+BinaryArtifacts.swift
=> [5.9] quiet down redundant warnings for binary targets with multiple info.plist

Sources/PackageModel/ArtifactsArchiveMetadata.swift
=> Remove empty line in ArtifactsArchiveMetadata.swift

Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift, Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift, Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Package.swift, Sources/PackageDescription/Target.swift, Sources/PackageModel/PackageModel.swift, Tests/BuildTests/BuildPlanTests.swift
The package visibility proposal has officially been accepted: https://forums.swift.org/t/accepted-se-0386-package-access-modifier/64904
Resolves rdar://109152010
=> [5.9] Enable package visibility feature in tools-version 5.9

Sources/PackageRegistry/RegistryClient.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/6576 to 5.9
=> [5.9] Improve error message for 'package-registry publish'

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
=> Add token-file option to 'package-registry login'

Documentation/Registry.md
=> Fix missing link in `Documentation/Registry.md`

Sources/Basics/AuthorizationProvider.swift, Tests/BasicsTests/AuthorizationProviderTests.swift
Cherry pick https://github.com/apple/swift-package-manager/pull/6737 and https://github.com/apple/swift-package-manager/pull/6738 to 5.9
=> [5.9] Keychain credentials - better support for protocol and port

Sources/Basics/AuthorizationProvider.swift
Cherry pick https://github.com/apple/swift-package-manager/pull/6748 to 5.9
=> [5.9] Keychain search to return all matches

Documentation/PackageSecurity.md
=> Add documentation for package fingerprints

Sources/PackageLoading/ManifestLoader+Validation.swift, Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_7_LoadingTests.swift
motivation: help users reason about erros when encountering an unknown dependency
changes:
* include the dependency location in the error string
* refactor tests to cover more use cases
rdar://113411527
=> improve error message when running into an unknown target dependency

Sources/Basics/CMakeLists.txt, Sources/Basics/OSSignpost.swift, Sources/Commands/PackageTools/Update.swift, Sources/Commands/ToolWorkspaceDelegate.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift
motivation: help with performance analsysis
changes:
* define a few more workspace delegates
* in debug mode, emit additional performance information
* add signpost helpers
=> add instrumentation probes for easier performance analysis

Sources/Commands/PackageTools/PluginCommand.swift
According to the [original proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0332-swiftpm-command-plugins.md#discovering-command-plugins), only plugin products from direct dependencies should be included here. The proposal doesn't mention root packages directly, but I think it makes sense to include any plugin targets from them, regardless of whether they're exposed via a product or not.
In addition, this method was just returning all plugin targets, we should limit it to those that define a command plugin, as the name suggests.
=> Fix `availableCommandPlugins()`

Package.swift
=> [5.10] Update related dependencies branch to release/5.10

.swiftpm/xcode/xcshareddata/xcschemes/SwiftPM-Package.xcscheme
Since this file hasn't been added to `.gitignore`, we have to update it after the list of targets is updated.
=> [NFC] Update SwiftPM-Package.xcscheme

Package.swift, Sources/PackageCollectionsSigning/CertificatePolicy.swift, Sources/PackageCollectionsSigning/X509Extensions.swift, Sources/PackageSigning/VerifierPolicies.swift, Sources/PackageSigning/X509Extensions.swift, Tests/PackageSigningTests/SigningTests.swift
This reverts the revert PR https://github.com/apple/swift-package-manager/pull/6988
**This requires update-checkout changes**
=> [5.10] Bring back "Update swift-certificates to 1.0.1, swift-crypto to 3.0.0 (#6949)"

Documentation/Usage.md
=> Warn against absolute paths in `Documentation/Usage.md`

xcode/SwiftPM-Package.xctestplan
This target was missing so far.
=> Add `LLBuildManifestTests` to test plan

CODEOWNERS
Also sort the list alphabetically.
=> [GH] Add bnbarham to codeowners

Sources/PackageModel/InstalledSwiftPMConfiguration.swift, Utilities/config.json
=> Bump `swift-syntax` in template to `600.0.0-latest`

CODEOWNERS, Sources/XCBuildSupport/CODEOWNERS
Standalone files in subdirectories don't work.
=> Update XCBuildSupport CODEOWNERS

Tests/SPMBuildCoreTests/PluginInvocationTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
SPI was added here in #7465, but missed adding it to this module.
=> Use new SPI for SourceKitLSPAPITests

Sources/Basics/Environment/Environment.swift, Sources/DriverSupport/DriverSupportUtils.swift, Sources/DriverSupport/SPMSwiftDriverExecutor.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
=> Expose `Environment` with `@_spi`

README.md
=> Update copyright years in `README.md`

Sources/Workspace/InitPackage.swift
Resolves https://github.com/swiftlang/swift-package-manager/issues/7772
=> Add `/.index-data` to `.gitignore` in `InitPackage.swift`

Sources/swift-bootstrap/main.swift
Remove temp_await from swift-bootstrap
`temp_await` is unsafe and it would be better to use true async methods
Replace `temp_await` with `unsafe_await` in swift-bootstrap (temporarily)
=> Remove `temp_await` from swift-bootstrap

Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
Helps to simplify compatibility testing.
=> Remove some PIF overrides to match Xcode behavior

Sources/Basics/Sandbox.swift, Tests/BasicsTests/SandboxTests.swift
Previously, nondeterministic item replacement directory paths could be included in the sandbox content. This can lead to spurious incremental rebuilds of plugin outputs.
Because `itemReplacementDirectories` returns a unique temporary directory on each call, I don't believe including it in the sandbox profile had the intended effect, so removing it should not break existing plugins.
=> Ensure package plugin sandbox contents is deterministic

Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
Companion of https://github.com/swiftlang/sourcekit-lsp/pull/1685
=> Report whether a source file is part of a test target in the SourceKit-LSP API

Sources/XCBuildSupport/PIF.swift, Tests/XCBuildSupportTests/PIFTests.swift
=> Use `OrderedDictionary` for `PIF.BuildSettings` internal properties

Sources/PackageGraph/Resolution/ResolvedPackage.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/Workspace/Workspace.swift
Change a few access modifiers to public.
As a user of the package, I am trying to access these properties.
=> Make access modifiers public for users of the package.

Sources/Build/BuildDescription/ClangModuleBuildDescription.swift
Guard resource access header with __OBJC__ to avoid including Foundation.h in languages that do not support it. i.e. non-objc/c++
Add check the file extension for assembly files to not include Foundation.h there as well.
Fixes: #7949
=> Guard resource access header with  __OBJC__ to avoid including Foundation.h

Tests/WorkspaceTests/WorkspaceTests.swift
Addresses https://github.com/swiftlang/swift-package-manager/pull/8138#discussion_r1855175099
=> Add additional tests for `interpreterFlags`

Package.swift
Improve the formatting in there.
=> Format XCBuildSupport target

Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/swift-bootstrap/main.swift, Utilities/bootstrap
Reverts https://github.com/swiftlang/swift-package-manager/pull/8334
This seems to cause an issue in the incremental buildbots
=> Revert "Include Swift Build support in second stage bootstrap builds"

Tests/BasicsTests/Environment/EnvironmentTests.swift
Handle the case insensitivity correctly
=> Fix test_initDictionaryFromSelf on Windows

Sources/PackageGraph/ModulesGraph+Loading.swift
Remove a trailing comma to have swiftpm compilng using 6.0.3
=> Remove trailing comma

Sources/Basics/SwiftVersion.swift
https://forums.swift.org/t/development-open-for-swift-6-1-1-for-linux-and-windows/79152
=> Bump the Swift version to 6.1.1

Sources/_InternalTestSupport/Observability.swift, Tests/BasicsTests/Environment/EnvironmentKeyTests.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/BasicsTests/Graph/AdjacencyMatrixTests.swift, Tests/BasicsTests/Graph/DirectedGraphTests.swift, Tests/BasicsTests/Graph/UndirectedGraphTests.swift, Tests/BasicsTests/ObservabilitySystemTests.swift, Tests/BasicsTests/ProgressAnimationTests.swift, Tests/BasicsTests/StringExtensionsTests.swift
Convert `BasicsTests/Environemnt/*.swift`, `BasicsTests/Graph/*.swift` and a couple other in BasicsTests to Swift Testing
=> Tests: Convert Environment/Graph and other suites to ST

CODEOWNERS
Added @AnthonyLatsis, @bnbarham and myself as code owners for migration and swift fix-it.
=> Add new maintainers to migrate command and SwiftFixIt module

Tests/SwiftFixItTests/BasicTests.swift, Tests/SwiftFixItTests/CategoryTests.swift, Tests/SwiftFixItTests/FilteringTests.swift, Tests/SwiftFixItTests/Utilities.swift
Follow-up to https://github.com/swiftlang/swift-package-manager/pull/8671#discussion_r2089650900.
=> [test] SwiftFixIt: Switch to Swift Testing

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
This emits an error if a build task fails, to improve clarity, and explicitly lists out some of the other messages we aren't handling right now.
=> Improve output formatting with Swift Build backend

Sources/Basics/Concurrency/AsyncProcess.swift, Sources/_InternalTestSupport/SkippedTestSupport.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/BasicsTests/Archiver/TarArchiverTests.swift, Tests/BasicsTests/Archiver/UniversalArchiverTests.swift, Tests/BasicsTests/Archiver/ZipArchiverTests.swift, Tests/BasicsTests/AsyncProcessTests.swift, Tests/CommandsTests/PackageRegistryCommandTests.swift
=> Remove workarounds for missing chdir support on Amazon Linux 2

Sources/PackageDescription/SupportedPlatforms.swift
(cherry picked from commit 573d8c14dc5c5e5d7af04e8cd5df69c0e1a85cd3)
=> [6.2] Add amended OS versions to SupportedPlatforms

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
Closes https://github.com/swiftlang/swift-package-manager/issues/8999
=> Properly format build duration when using --build-system swiftbuild

Sources/Basics/HTTPClient/URLSessionHTTPClient.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
- **Explanation**:
* Fix download of private artifact bundles on GitHub; which now involves a redirect to another domain to which authentication header should not be sent. Fixes https://github.com/swiftlang/swift-package-manager/issues/8946
* DataTaskManager has a redirect handler, but DownloadTaskManager does not. Pass  authorizationProvider to DownloadTaskManager in order to set correct authorization headers for cases when there is a redirect to a new domain.
- **Scope**: Package resolution when using private artifact bundles
- **Issues**: https://github.com/swiftlang/swift-package-manager/issues/8946
- **Original PRs**: https://github.com/swiftlang/swift-package-manager/pull/8947
- **Risk**: Low.
- **Testing**: Regression test added.
- **Reviewers**: @plemarquand
=> [6.2] fix: DownloadTaskManager handle redirect authentication

CODEOWNERS
Add self to recommended reviewers list
=> Add self to recommended reviewers list
