swiftlang/swift-package-manager

Fixtures/Miscellaneous/DoubleFree/Package.swift, Fixtures/Miscellaneous/DoubleFree/README.md, Fixtures/Miscellaneous/DoubleFree/Sources/exec/main.swift, Fixtures/Miscellaneous/DoubleFree/Sources/lib/lib.swift, Fixtures/Miscellaneous/DoubleFree/Tests/LinuxMain.swift, Fixtures/Miscellaneous/DoubleFree/Tests/libTests/XCTestManifests.swift, Fixtures/Miscellaneous/DoubleFree/Tests/libTests/libTests.swift, Sources/SPMBuildCore/Sanitizers.swift, Tests/CommandsTests/RunToolTests.swift, Tests/CommandsTests/TestToolTests.swift
The Swift PR apple/swift#28538 adds support for the Scudo hardened
allocator to swiftc. This patch adds support for it to Swift Package
Manager, allowing the Package Manager to correctly plumb Scudo through
the entire build pipeline.
See the aforementioned PR for more discussion on the value of supporting
Scudo.
Note that the tests will fail until apple/swift#28538 lands.
=> Add support for the Scudo sanitizer.

Sources/SPMTestSupport/TestWorkspace.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Currently, we rely on a build failure if an expected XCFramework isn't
present in a downloaded ZIP. We should instead check if the expected
XCFramework is present while extracting the ZIP so that we can surface
this error already during package loading.
rdar://problem/60619547
=> Fail early if expected XCFramework is not present

Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XCBuildOutputParser.swift
- Print build diagnostics and output as they both are used for potential
error message
- If the build failed, was canceled or aborted, log a message.
rdar://problem/60925204
=> Improve output when using XCBuild

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
(copied from [SR-12170](https://bugs.swift.org/browse/SR-12170))
> Right now, if SwiftPM doesn't find a system target's module.modulemap at the expected location, it emits the following diagnostic:
>
> `Source files for target SystemLib should be located under 'Sources/SystemLib', or a custom sources path can be set with the 'path' property in Package.swift`
>
> even if there is a module map file in that folder but with the wrong name. Perhaps SwiftPM should generate a more precise diagnostic:
>
> `missing system target module map at 'Sources/SystemLib/module.modulemap'`
>
> Or perhaps SwiftPM could also scan for any modulemap file inside the target folder.
- Addition of a new `ModuleError.InvalidLayoutType` case called `modulemapMissing`.
- Implementation of the new error to be thrown in …
=> Improve diagnostic for system target with missing modulemap

Sources/PackageLoading/MinimumDeploymentTarget.swift, Tests/PackageLoadingTests/MinimumDeploymentTargetTests.swift
This could assert with empty stdout from `xcrun` or if the output of `xcrun` was not an absolute path. We should be robust against these cases and return the fallback.
rdar://problem/62898201
=> Make `computeXCTestMinimumDeploymentTarget()` more robust

Sources/Workspace/UserToolchain.swift
When building for WebAssembly/WASI `swiftc` needs the `-sdk` option passed to it with the sdk path.
=> Pass sdk option to Swift compiler for WASI triples

Sources/PackageDescription/BuildSettings.swift, Sources/PackageDescription/PackageDependency.swift, Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/Product.swift, Sources/PackageDescription/Resource.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageDescription/Target.swift, Sources/PackageDescription/Version+StringLiteralConvertible.swift, Sources/PackageDescription/Version.swift
This PR includes the changes from #2715 but targets `master`. It's what #2732 should have been.
Sorry @neonichu 😇 and thanks for your patience with me.
=> Update in-source documentation

Sources/Workspace/UserToolchain.swift
Currently, when cross-compiling on macOS SwiftPM attempts to find `xctest` and use that for running tests. This doesn't make sense for non-Darwin target triples.
=> Avoid searching for xctest with non-Darwin triples

Sources/Workspace/UserToolchain.swift
This PR contains a few minor changes to `UserToolchain`:
- When searching for `llvm-cov` & `llvm-profdata` we should take the `.exe` suffix into account.
- Compiler search on non-macOS used `Foundation.FileManager` instead of `LocalFileSystem`.
- There were multiple ways to retrieve an executable by a tool name and validate it which caused some duplication.
=> Fix search for coverage tools on Windows & cleanup UserToolchain

Sources/Build/BuildPlan.swift
LinuxMain is also used to run tests on WebAssembly/WASI (and potentially on Android, Windows etc)
=> Use LinuxMain on all platforms except Darwin

Utilities/bootstrap
Add flags to allow `build-script` to pass down the directories for `Dispatch` and `Foundation`, which will be needed for building Yams integration
=> [Bootstrap] Add optional flags for Dispatch and Foundation build directories

CMakeLists.txt, Package.swift, Sources/Build/BuildPlan.swift, Sources/Build/CMakeLists.txt, Sources/Build/ManifestBuilder.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/LLBuildManifest/BuildManifest.swift, Sources/SPMBuildCore/BuildParameters.swift, Utilities/bootstrap
Add bootstrap and build support for building the new Swift driver
and importing it (as a library) into SwiftPM. Then introduce the new
SwiftPM flag `--use-integrated-swift-driver` to enable use of the
integrated Swift driver rather than shelling out to a separate
Swift driver binary. The jobs created by the integrated Swift driver
will be merged into SwiftPM's build graph.
=> [Build] Add support for building with the integrated Swift driver

Sources/Workspace/Workspace.swift
This will allow clients of libSwiftPM to provide custom values for
XCTest minimum deployment target instead of the defaults.
rdar://problem/62858732
=> Pass XCTest minimum deployment target in Workspace

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift
This assertion in `ManifestParseResult` would always be triggered if parsing the manifest returns non-zero and produced output. One case where that happens is if running the manifest crashes, e.g. due to a force unwrap.
rdar://problem/63040735
=> Fix incorrect assertion in `ManifestParserResult`

Sources/Build/BuildPlan.swift, Sources/Build/ManifestBuilder.swift, Sources/SPMBuildCore/BuildParameters.swift, swift-tools-support-core/Sources/TSCBasic/FileSystem.swift
When writing an output file map and using the integrated Swift
driver, use the provided file system rather than the local file
system.
=> [Build plan] Use the provided file system consistently 

Sources/Build/BuildDelegate.swift, Sources/Build/BuildOperation.swift, Sources/Build/ManifestBuilder.swift, Sources/LLBuildManifest/BuildManifest.swift, Sources/LLBuildManifest/Tools.swift
Create Swift compiler output parser instances for Swift frontend jobs,
too. This provides better feedback for (e.g.) batch mode, where there
are multiple source files processed in a single frontend invocation,
and also helps line up the "Compiling" output from SwiftPM between
the integrated and non-integrated Swift drivers.
=> [Swift driver] Process the parseable output from Swift frontend jobs.

Sources/Build/ManifestBuilder.swift, Tests/BuildTests/BuildPlanTests.swift
A few minor fixes for issues uncovered when enabling the integrated Swift driver as the default:
* Unique the set of job inputs; only the tests seem to care, but it's the right thing to do anyway
* Loosen a few string-based output checks to account for benign differences between the integrated and traditional Swift driver
=> [Integrated Swift driver] Minor fixes to get a clean test run

Sources/Workspace/InitPackage.swift
Minor tweaks to the wording of newly instantiated packages.
This is the 5.3 merge of the already approved master commit with the same content.
rdar://63120125
(cherry picked from commit 4221fdcea2b20e26c78085f0a795c9bc17461e53)
=> [5.3] [Workspace] Update wording in template for Swift Packages

Sources/Build/ManifestBuilder.swift
The new enum case was added to handle `-embed-bitcode` in https://github.com/apple/swift-driver/pull/101 , this PR handles it in a couple switches to fix a compile error.
=> Handle new Job.Kind.backend enum case from swift-driver

Utilities/bootstrap
Currently, when the `bootstrap` script is given an invalid `swiftc` path, its error message is unhelpful:
```
--- bootstrap: error: [Errno 2] No such file or directory
```
The `boostrap` script should clarify which exact file it was looking for and at what path. With this change a check for `swiftc` path is added, which is consistent with an existing path check in `get_llbuild_source_path`. Now the error message specifies the exact path it was looking for:
```
--- bootstrap: error: unable to find swiftc at
/home/builder/source/host-toolchain-sdk/swift-wasm-DEVELOPMENT-SNAPSHOT-2020-05-18-a/usr/bin/swiftc
```
=> Check if swiftc exists at path in bootstrap

Sources/Workspace/InitPackage.swift
This only affects `swift init`, not existing packages.
The existing unit test `testInitManifest` checks that the manifest of the instantiated package has the updated version number.
rdar://63365232
=> Update `swift-tools-version` in newly created packages to 5.3.

Sources/Workspace/InitPackage.swift
This only affects `swift init`, not existing packages.
The existing unit test `testInitManifest()` checks that the manifest of the instantiated package has the updated version number.
This is the 5.3-specific PR of a change that has already been approved and merged to master.
(cherry-picked from commit d4d56d8799c3255c7ef95ea493ed5b5b45b0afbe)
=> [5.3] Update `swift-tools-version` in newly created packages to 5.3.

Sources/Build/ManifestBuilder.swift
Rather than letting the integrated Swift driver guess at where the
Swift frontend is located, pass through the location of the Swift
compiler. This also allows `SWIFT_EXEC` overrides to work with the
integrated driver.
=> [Integrated Swift driver] Pass along the Swift location.

Utilities/bootstrap
As part of bootstrapping, also run tests with the integrated Swift
driver.
=> [Bootstrap] Bootstrap & test with the integrated Swift driver.

Tests/FunctionalTests/MiscellaneousTests.swift
This test fails spuriously but rather frequently on linux recently.
SR-12902
=> Disable testPackageManagerDefineAndXArgs

Utilities/Docker/docker-utils, Utilities/bootstrap
- paths to swift-driver and yams were missing
- the dispatch and foundation dir arguments became mandatory on
non-macOS, this makes them optional again
=> Fix docker-utils

Sources/Commands/SymbolGraphExtract.swift
This is also broken on the 5.3 branch, not sure if it's too late to cherry-pick
=> Pass -output-dir to swift-symbolgraph-extract instead of -o, which was removed

Sources/Build/ManifestBuilder.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/SPMBuildCore/BuildParameters.swift
With the integrated Swift driver. The feature is hidden behind: 
`--use-integrated-swift-driver --experimental-explicit-module-build`.
While it is not yet in a shape where SwiftPM can bootstrap in this mode, this should allow us to start experimenting with it.
=> [Build] Add support for building targets in Explicit Module Build mode

Sources/Build/BuildDelegate.swift, Sources/SPMBuildCore/BuildParameters.swift, Tests/BuildTests/BuildPlanTests.swift
Currently, with the `--enable-test-discovery` flag SwiftPM looks for `libIndexStore` using the target triple if one was present, instead of the host triple. This breaks when cross-compiling, since you actually need `libIndexStore` from the host, not the target. This is resolved by adding a new `hostTriple` property, as opposed to the existing target `triple` property. New `hostTriple` is used in `createIndexStoreAPI` to infer the extension of `libIndexStore` when searching for it.
=> Use host triple in createIndexStoreAPI

Documentation/Usage.md
Currently, the available documentation provides no examples of how to build SwiftPM packages for non-macOS Apple platforms with `xcodebuild`.
=> Add xcodebuild examples to Documentation/Usage.md

swift-tools-support-core/Utilities/import
Currently the directory is named swift-tools-support-core, not TSC.
=> Fix swift-tools-support-core path in Utilities/import

Sources/PackageDescription/CMakeLists.txt, Utilities/bootstrap
I think this should work, given the relative rpaths that are added, but limited to non-Darwin for the shared libraries as the relative rpath is only added there.
=> ELF platforms: remove host toolchain rpath from executables and shared libraries

Sources/Build/BuildDelegate.swift
Currently the `outputs` array in `TestDiscoveryCommand.execute` function is traversed twice. Once in a `for` loop that writes tests for each module, and second time in the `first(where:)` call just after the loop. The loop also checks for the main file anyway to skip it, so there's an opportunity for an easy optimization here, which could be felt in packages with big test suites.
=> Avoid traversing array in TestDiscoveryCommand twice

Package.swift
Add an extra rpath for swiftpm-xctest-helper on macOS:
`@executable_path/../../../lib/swift/macosx`.
This fixes SR-12600:
```console
$ swift test --filter a
error: signalled(6): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-06-10-a.xctoolchain/usr/libexec/swift/pm/swiftpm-xctest-helper /Users/danielzheng/TestPkg/.build/x86_64-apple-macosx/debug/TestPkgPackageTests.xctest /var/folders/m_/6f7q8zfs3n9fr0c_4gy8840m00hc_q/T/TemporaryFile.3eFu0u output:
dyld: Library not loaded: @rpath/XCTest.framework/Versions/A/XCTest
Referenced from: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-06-10-a.xctoolchain/usr/libexec/swift/pm/swiftpm-xctest-helper
Reason: image not found
```
---
Fix found by @abertelrud in https://github.com/apple/swift-package-manager/pull/2694#issue …
=> Add swiftpm-xctest-helper rpath on macOS.

Documentation/Development.md
Both swift-driver and yams are now needed for bootstrap, so we should document how to set this up.
=> Document new dependencies

Sources/PackageDescription/LanguageStandardSettings.swift
* This adds support for two newer C++ standards.
=> Add support for newer C++ language standards.

Sources/PackageGraph/PinsStore.swift, Sources/SPMTestSupport/TestWorkspace.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/misc.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
We can safely make the assumption that any dependency in the resolved file was required.
=> Do not store products in resolved file

Sources/SPMTestSupport/TestWorkspace.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/WorkspaceState.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
#2792 removed product filters from pins. This takes the clean‐up further and removes product filters from managed dependencies, workspace state, and the pin testing utilities and fixtures.
To decouple the filters from `ManagedDependency` (to avoid encoding them), `DependencyManifests` and `loadDependencyManifests(root:diagnostics:)` required some refactoring to track the filters directly.
The rest of the changes are just the removal of dead properties and parameters.
=> Remove Product Filters from All Persistent Files

Sources/PackageGraph/PinsStore.swift, Sources/Workspace/Workspace.swift
This was a leftover from the old resolver, but it was no longer actually being used for anything.
=> Remove `PinsStore.createConstraints()`

swift-tools-support-core/Sources/TSCUtility/Version.swift
```swift
@available(*, unavailable)
extension Range where Bound == Version {
/// Marked as unavailable because we have custom rules for contains.
public func contains(_ element: Version) -> Bool {
// Unfortunately, we can't use unavailable here.
fatalError("contains(_:) is unavailable, use contains(version:)")
}
}
```
It can be marked as unavailable.
```swift
let range = Version(1, 0, 0)..<Version(2, 0, 0)
range.contains(Version(1, 0, 0)) // error message: 'contains' is unavailable
```
=> mark unavailable to range contains of Version

Sources/Workspace/Destination.swift
The Termux app sets the `PREFIX` environment variable with its root of `/data/data/com.termux/files/usr`, so read that and set the SDK path for Android.
Until now, [I was simply hard-coding](https://github.com/termux/termux-packages/blob/master/packages/swift/swiftpm-Sources-Workspace-Destination.swift#L10) that [path at compile time](https://github.com/termux/termux-packages/blob/master/packages/swift/build.sh#L73). This is the last patch needed to build SPM natively on Android.
=> Android: add host destination to the workspace

Utilities/bootstrap
The Swift Driver uses this environment variable to detect swiftc.
=> Use SWIFT_DRIVER_SWIFT_EXEC to pass swiftc_path to driver in bootstrap

Sources/Workspace/Destination.swift, Sources/Workspace/UserToolchain.swift
Passing / as sysroot breaks usage of toolchains installed in custom locations.
=> Don't pass / as default sysroot on Linux

swift-tools-support-core/Sources/TSCBasic/Path.swift, swift-tools-support-core/Tests/TSCBasicTests/PathTests.swift
These functions are present in the TSC repository (merged in https://github.com/apple/swift-tools-support-core/pull/85), but are not present in the SwiftPM repo yet, which breaks `build-script` builds.
=> Add `appending` functions to RelativePath

Sources/Build/ManifestBuilder.swift
For a given target, in the Explicit Module Build world, `swift-driver` produces jobs to build the main module and jobs to build all module dependencies.
Cross-target dependencies should be added as explicit inputs to a target's main module build job, but not intermediate build dependency jobs.
Always adding cross-target dependencies as inputs can lead to cycles in the build manifest when multiple targets share common intermediate module dependencies.
=> [Explicit Module Builds] Avoid adding cross-target input dependencies to intermediate build artifact jobs.

Sources/Build/ManifestBuilder.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/LLBuildManifest/CMakeLists.txt, Sources/LLBuildManifest/DOTManifestSerializer.swift, Sources/SPMBuildCore/BuildParameters.swift
Similarly to how swift-driver can serialize Jobs for a given compilation target, add a capability to write out the entire build manifest as a dot graph. 
This was extremely useful for debugging various build issues.
=> Add an option to output a dot graph of the build manifest.

Tests/BuildTests/BuildPlanTests.swift, swift-tools-support-core/Sources/TSCUtility/PkgConfig.swift, swift-tools-support-core/Tests/TSCUtilityTests/PkgConfigParserTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/pkgconfigInputs/gobject-2.0.pc, swift-tools-support-core/Tests/TSCUtilityTests/pkgconfigInputs/libffi.pc
This adds support for absolute paths in the `Requires` and `Requires.private` fields of a `.pc` file, which currently cause the `PkgConfig` initializer to fail.
On macOS, the Homebrew-provided package `gobject-2.0` (GLib's GObject library) has an absolute path dependency:
```
$ cat $(brew --prefix)/opt/glib/lib/pkgconfig/gobject-2.0.pc
prefix=/usr/local/Cellar/glib/2.64.3
libdir=${prefix}/lib
includedir=${prefix}/include
Name: GObject
Description: GLib Type, Object, Parameter and Signal Library
Version: 2.64.3
Requires: glib-2.0
Requires.private: /usr/local/opt/libffi/lib/pkgconfig/libffi.pc >=  3.0.0
Libs: -L${libdir} -lgobject-2.0
Libs.private: -lintl
Cflags:-I${includedir}
```
This prevents any system library dependencies that depend on `glib` from having their search paths correctly …
=> Fix Absolute Path Dependencies in `.pc` Files

Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Some of the Xcode project generation tests were using in-memory file systems and others not.  But the Xcode project generation code does not currently support non-local file systems (which should itself perhaps be addressed), and so this could cause tests to start traversing large parts of the actual file system, including over NFS mounts.
Ideally the Xcode project generation should support the in-memory file system, but since this functionality was primarily useful before Xcode supported loading packages natively, it's not clear whether it's worth the effort to fix that.
rdar://65200866
=> Some of the GenerateXcodeprojTests are hanging on pull request testing

Sources/PackageDescription/Target.swift
Exposing just one `Target.testTarget` method with the recently introduced `resources` argument (which has a default value) is enough.
This makes `Target.testTarget` consistent with `Target.target` which already has this attribute and doesn't expose the `resource`-less version of the method.
=> Add `obsoleted` attribute to testTarget method without resources argument

Sources/Workspace/Destination.swift
Instead, use #2797, which made the SDK path optional, and simply pass nil by default as on linux.
The only reason I added it in #2790 was that setting the SDK path was mandatory at the time, but it was never necessary for builds, as the Swift and clang compilers in Termux are already pre-configured with the Termux sysroot. Now that it's optional, clear it and the user can always set it on the command-line if wanted, just like on linux.
=> Revert "Android: add host destination to the workspace"

Sources/Build/ManifestBuilder.swift
This is mostly NFC, the executor we pass explicitly is the same as the default argument except it uses `plan.diagnostics` instead of a new DiagnosticsEngine (hopefully that's correct). This will allow me to drop the default argument value in SwiftDriver and eliminate a layering violation.
Eventually, SPM will probably implement its own executor. For now, this one is just used for jobs that run during planning (dependency scanning, -print-target-info, etc.)
=> Explicitly pass a DriverExecutor to the integrated swift driver

Sources/PackageDescription/SupportedPlatforms.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift
This removes the temporary alias that was added during transition from 10.16 to 11 numbering for macOS 11
rdar://65056342
=> Mark the temporary v10_16 alias for macOS v11 as unavailable and having been renamed to v11

Documentation/Usage.md, Sources/PackageLoading/ModuleMapGenerator.swift, Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
After more discussion about this, we will be removing the warning and just updating the documentation to match the behavior that’s been in place since 2016.  This is because the current implemented behavior was, according to the extensive PR discussion, the intended behavior, and there is concern about how many existing packages would require changes to get rid of the warning.
We will put up an evolution proposal with refined module map semantics, and at that time, probably tie it to the tools version, since this has now been the semantic for four years and a lot of packages have been written in the meantime.
rdar://65692136
=> Remove warning and update the documentation to reflect the long-stand ing behavior of treating all C module headers as umbrella headers by default

Sources/Workspace/InitPackage.swift
Foundation on Catalyst does not have `Process`, so by default the template was broken.
=> Fix building the executable template for Catalyst

Sources/PackageLoading/TargetSourcesBuilder.swift
Currently only `.h` header extension is supported.
=> Support C++ headers in TargetSourcesBuilder.swift

Sources/Commands/SwiftTool.swift
Typically, we only hide options from help to do that. The `--build-system` option itself is already not shown, but `-Xxcbuild` was. This hides `-Xxcbuild` as well. The same is true for `-arch` which requires using XCBuild today.
rdar://problem/65633615
=> Mark `--build-system` as experimental

Sources/PackageLoading/TargetSourcesBuilder.swift
This was an error before, but we decided to make it a warning instead in order to ease transition to tools-version 5.3.
rdar://problem/65345954
=> Demote unhandled file diagnostic to a warning

Documentation/Usage.md
The currently documented behavior for how the headers in the  directory are handled doesn't match what actually happens.  Since the current behavior dates back to the original implementation and many packages rely on it, we keep the existing semantics but correct the documentation.  We may want to adjust the current semantics in a future evolution proposal.
rdar://problem/65751265
=> [5.3] Update the documentation to reflect the long-standing behavior of treating all C module headers as umbrella headers by default

Sources/Build/BuildPlan.swift, Sources/PackageLoading/ModuleMapGenerator.swift, Sources/Xcodeproj/pbxproj.swift, Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
SwiftPM's ModuleMapGenerator currently emits any warnings to `stdout` and throws specialized errors in case of problems.  It should use DiagnosticsEngine like the rest of SwiftPM.
The output to `stdout` is particularly problematic since it can interfere with things like `swift package describe --type json`.
The tests have also been reworked to use DiagnosticsEngineTester instead of the home-grown warning string test code.
rdar://65891271
=> [SR-13266] ModuleMapGenerator should use DiagnosticsEngine instead of emitting to `stdout`

Sources/PackageDescription/SupportedPlatforms.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift
This is the 5.3 nomination for https://github.com/apple/swift-package-manager/pull/2816
This marks the temporary alias that was added during transition from 10.16 to 11 numbering for macOS 11 as unavailable.
rdar://65834459
=> [5.3] Mark the temporary v10_16 alias for macOS v11 as unavailable and having been renamed to v11

Documentation/Resources.md
This changes the internal link to match the linked heading
=> [Docs] Fix broken link in Resources.md

Tests/BuildTests/BuildPlanTests.swift
In #2812, I updated the logic to support other architectures than just x86_64, but I did not update the tests. This extends the existing `testBinaryTargets` with the missing coverage.
=> Extend binary target tests to multiple arches

Sources/Build/BuildPlan.swift, Sources/Workspace/InitPackage.swift, Tests/BuildTests/BuildPlanTests.swift
5.3 cherry-pick of https://github.com/apple/swift-package-manager/pull/2812
=> Update XCFramework logic

Utilities/build_ubuntu_cross_compilation_toolchain
Requires a tmpdir as the first argument.
=> Fix `usage` of script

Tests/XcodeprojTests/GenerateXcodeprojTests.swift
This is a 5.3 nomination of a test-only fix that is already in the main branch.
Some of the Xcode project generation tests were using in-memory file systems and others not.  But the Xcode project generation code does not currently support non-local file systems (which should itself perhaps be addressed), and so this could cause tests to start traversing large parts of the actual file system, including over NFS mounts.
Ideally the Xcode project generation should support the in-memory file system, but since this functionality was primarily useful before Xcode supported loading packages natively, it's not clear whether it's worth the effort to fix that.
Original PR: https://github.com/apple/swift-package-manager/pull/2809
rdar://66386071
(cherry picked from commit …
=> [5.3] Some of the GenerateXcodeprojTests are hanging on pull request testing

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, swift-tools-support-core/Sources/TSCUtility/CMakeLists.txt
This switches the manifest cache approach used inside manifest loader to
directly use sqlite database instead of going through llbuild. The main
reason for this switch is to simplify caching behavior and take
advantage of SQLite's WAL mode for concurrent access. A separate PR will
make the manifest cache global for the user.
=> [PackageLoading] Use a simpler manifest cache

Sources/Build/BuildDelegate.swift
The swift-frontend currently does not support parseable output, therefore, the parsers here are not needed.
The presence of these parsers also leads to these jobs to be skipped from being reported on in the LLBuild status line printing.
Resolves rdar://66594405
=> [Integrated Swift Driver] Do not create CompilerOutputParsers for swift-frontend jobs

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD5_2LoadingTests.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift
Manifest loading has been sandboxed on macOS for a while, but the change in #2518 broke it for 5.3.
https://bugs.swift.org/browse/SR-13346
rdar://problem/66586184
=> Reinstate manifest sandboxing

Sources/PackageGraph/PackageGraphLoader.swift, Sources/PackageModel/ResolvedModels.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
We prohibit unsafe flags in package dependencies, but the check was only looking at targets which are direct dependencies of a product, not transitive ones.
rdar://problem/66499615
=> Improve check for unsafe flags

Sources/XCBuildSupport/XCBuildOutputParser.swift
When I use:
`swift build --build-system xcode -v`
I get:
error: failed parsing XCBuild output: unexpected JSON message: : dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize Kind from invalid String value Package Product", underlyingError: nil))
=> Add missing kind values to TargetStartedInfo

Sources/Build/SwiftCompilerOutputParser.swift, Tests/BuildTests/SwiftCompilerOutputParserTests.swift
Swift frontend jobs are not required to have outputs. When they don’t, there is no “output” field in the driver’s JSON. SwiftPM previously assumed an “output” field must be present; this commit disabuses it of that notion.
(Necessary for apple/swift#33114; previously, the Swift driver never happened to do this for the compiles SwiftPM requested.)
=> Allow SwiftCompilerMessages with no outputs

Utilities/bootstrap
There were still a few places in the bootstrap script that were using a hardcoded target triple.
rdar://problem/63036398
=> Use `get_build_target` consistently

Utilities/bootstrap
This adjusts to building SwiftPM fat specifically when the build is happening on an Intel host and cross-compile host is set to "macosx-arm64".
I am intentionally not making a master PR first, because cherry-picking wouldn't merge cleanly and also building for multiple arches seems to be broken in master.
=> Build fat when `CROSS_COMPILE_HOSTS` is set

Sources/SPMBuildCore/BuildParameters.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
This changes the default to be dylibs when using XCBuild since we only create frameworks in Xcode for App Store submission. It also fixes an issue where even when dylib creation was enabled, we weren't producing dylibs.
rdar://problem/66849186
=> Create dylibs by default when using XCBuild

Sources/PackageLoading/ManifestLoader.swift
Currently SwiftPM compiles the package manifest with an `-rpath` linker argument which is not supported on Windows.
On Windows it should instead execute the compiled manifest with an additional `PATH` component representing the `PackageDescription.dll` location.
This implementation relies on https://github.com/apple/swift-tools-support-core/pull/92 to pass the `PATH` environment variable to the manifest executable, but these PRs can be merged in any order.
After this change the compiled manifests can be executed manually by running `id-manifest.exe -fileno 1` 
– it prints the package manifest JSON to stdout.
(Execution by SwiftPM itself still fails because of a different issue: the file descriptor of the JSON output is not shared properly with the child process)
=> Compile the package manifest properly on Windows

Sources/SPMBuildCore/BuildParameters.swift
Windows has a different naming scheme for libraries:
lib<name>.lib: static libraries
<name>.dll: shared libraries
<name>.lib: import libraries for the shared library
Adjust the generated name for Windows targets.
=> SPMBuildCore: correct naming scheme for libraries on Windows

Sources/PackageDescription/PackageDescription.swift, Sources/PackageLoading/ManifestLoader.swift
Passing fileno through to the child from the parent is not viable on
Windows.  "File Descriptors" are not a first class entity on Windows.
The concept of file descriptors is specifically a userspace concept that
is emulated via the C runtime.  The system speaks only in HANDLEs.
Because the file descriptor is emulated, the value of the file
descriptor is not shared across the parent and child.  Instead of
passing the file descriptor, reach into the C library and fetch out the
underlying system HANDLE.  Because the `HANDLE` was constructed via
`_open`, it will be marked with `bInherit` as `TRUE` (this can be
verified via `GetHandleInformation` which will pass back
`HANDLE_FLAG_INHERIT`.
We now serialize the handle and pass that explicitly to the child.  The
child then does this dance in …
=> PackageDescription: renegotiate the PackageDescription contract

Sources/swiftpm-xctest-helper/main.swift
Windows does not use `Glibc` but rather uses `ucrt` for the C runtime.
Add the proper import for the `exit` function.  This is needed for
building swift-package-manager on Windows with swift-package-manager.`
function.  This is needed for building swift-package-manager on Windows
with swift-package-manager.
=> swiftpm-xctest-helper: add Windows C library handling

Sources/SPMBuildCore/BuildParameters.swift
This ensures that SPM identifies the host correctly enabling platform
specific linker and compile settings to be applied properly.
Previously, we would treat Windows as Linux resulting in incorrect
application of linker options.  This was detected when building
swift-package-manager with swift-package-manager on Windows and we would
attempt to link against `libm`.
=> SPMBuildCore: detect Windows hosts properly

Sources/Xcodeproj/XcodeProjectModel.swift, Sources/Xcodeproj/pbxproj.swift, Tests/XcodeprojTests/PackageGraphTests.swift
This should resolve [SR-4265](https://bugs.swift.org/browse/SR-4265) for now, even though it might not be the final solution (as discussed in SR-4265).
I thought a first working solution is better than no solution... 🙂
=> [Xcodeproj]: Set CURRENT_PROJECT_VERSION to 1 in generated Xcode project

Sources/PackageGraph/PackageGraphRoot.swift
This property formatting was not alinged with the rest of the file.
=> Fix property formatting in `PackageGraphRoot.swift`

Sources/PackageModel/Platform.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Ensure that Windows is listed as a known platform.  Failure to
acknowledge that will result in failures to map the platform from the
string representation.
=> PackageModel: add `windows` to the list of known platforms

Documentation/Development.md, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, Sources/Commands/SwiftTestTool.swift, Tests/FunctionalTests/MiscellaneousTests.swift
Multiple `--skip` invocations can be used to skip multiple tests. Keep the environment variable around till its users switch over.
@aciidb0mb3r added the functionality to skip tests in #2181 last summer, but it was only available from an environment variable. I was unaware of that and really wanted the option to skip tests, especially when segfaulting tests cause the whole test run to stop, so I looked into implementing it and found his code. Simply adding this flag surfaces his implementation to the user and works, but ~is~was incomplete.
I ~'d go~went further and ~make~made it so that `--filter` and `---skip` could be used at the same time ~(the naive implementation in this WIP pull causes the skip flag to override the filter flag)~, so one could `--filter BuildTests --skip …
=> [Commands] Allow skipping tests with a flag

Sources/Commands/SwiftTestTool.swift
Windows does not have the concept of signals, therefore processes may
not terminate with signalling exits.  Such an exit is encoded in the
exit status code on Windows.
=> Commands: remove `signalled` cases for Windows

Sources/Workspace/UserToolchain.swift
When the user specifies the Swift executable via `SWIFT_EXEC` in the
environment, assume that the value is supposed to be used.  This changes
the order in which the Swift compiler is evaluated as being present.
This can avoid an unnecessary lookup for the executable in the case that
it is specified by the user.
=> Workspace: assume that the user is always correct

Sources/Workspace/UserToolchain.swift
This environment variable is needed during bootstrapping.  Using `:` as
a delimiter does not allow passing a valid windows path as `:` is the
drive separator.  Use the traditional path separator `;` on Windows and
use `:` on the other platforms.  This allows setting the correct path to
the package description modules.
=> Workspace: handle `SWIFTPM_PD_LIBS` properly on Windows

Utilities/bootstrap
When using the integrated swift-driver, SPM may need to look up swift-autolink-extract. Symlinking it into the build dir alongside `swift` and `swiftc` prevents some test failures caused by apple/swift-driver#208 (which fixes generation of autolink-extract jobs on linux)
=> Symlink swift-autolink-extract into the SPM build dir

Sources/PackageLoading/PackageBuilder.swift, Sources/SPMTestSupport/MockDownloader.swift, Sources/Workspace/Workspace.swift, Utilities/build-using-self, swift-tools-support-core/CMakeLists.txt, swift-tools-support-core/CODE_OF_CONDUCT.md, swift-tools-support-core/Sources/TSCBasic/CMakeLists.txt, swift-tools-support-core/Sources/TSCBasic/CStringArray.swift, swift-tools-support-core/Sources/TSCBasic/FileSystem.swift, swift-tools-support-core/Sources/TSCBasic/Path.swift, swift-tools-support-core/Sources/TSCBasic/Process.swift, swift-tools-support-core/Sources/TSCBasic/ProcessEnv.swift, swift-tools-support-core/Sources/TSCBasic/StringConversions.swift, swift-tools-support-core/Sources/TSCBasic/TemporaryFile.swift, swift-tools-support-core/Sources/TSCBasic/TerminalController.swift, swift-tools-support-core/Sources/TSCBasic/misc.swift, swift-tools-support-core/Sources/TSCLibc/libc.swift, swift-tools-support-core/Sources/TSCTestSupport/PseudoTerminal.swift, swift-tools-support-core/Sources/TSCUtility/CMakeLists.txt, swift-tools-support-core/Sources/TSCUtility/Downloader.swift, swift-tools-support-core/Sources/TSCUtility/Git.swift, swift-tools-support-core/Sources/TSCUtility/Netrc.swift, swift-tools-support-core/Sources/TSCclibc/process.c, swift-tools-support-core/Tests/TSCBasicTests/ProcessTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/DownloaderTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/NetrcTests.swift
This fixes two issues:
- First one is the same as #2875
- Second one is a crash related to build conditionals which looks like a
longer standing bug that was triggered by https://github.com/apple/swift-llbuild/pull/681
Unforunately, llbuild CI doesn't test the package, so it slipped through
and now causes SwiftPM to crash when building itself
=> Unblock SwiftPM's build

Sources/PackageLoading/PackageBuilder.swift
This just replaces `flatpMap` which is deprecated in favour of
`compactMap` to avoid a deprecation warning.  NFCI.
=> PackageLoading: use `compactMap` instead of `flatMap` (NFC)

Sources/Build/CMakeLists.txt
This module is marked as `@_implementationOnly`.  The users of `Build`
should not have to link against `SwiftDriver`.
=> Build: treat `SwiftDriver` as a private link dependency

Sources/PackageLoading/ModuleMapGenerator.swift
The `pathString` is overloaded and used as both a printing string and a
path string.  When used to generate the module map, we need to escape
the path separator as it is an escape sequence indicator otherwise.
This allows us to generate modulemaps which can be consumed by clang
on Windows.
=> PackageLoading: escape `\` when generating the modulemap

Sources/Workspace/UserToolchain.swift
The path environment variable spelt `Path` on Windows and `PATH` on
Unicies (since most of Windows is case insensitive).  This is already
properly handled in swit-tools-support-core.   Use the helper accessor
rather than duplicate that knowledge here.
=> Workspace: use `ProcessEnv.path` rather `ProcessEnv.vars["PATH"]`

Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift
In this case:
```swift
let linkerSettings: [LinkerSetting]
if ProcessInfo.processInfo.environment["SOMETHING"] == nil {
linkerSettings = []
} else {
linkerSettings = [
.unsafeFlags(["something"]),
]
}
// pass linkerSettings to a .target below
```
It's useful to be able to pass empty lists here.
=> Allow empty build settings arrays

IntegrationTests/Tests/IntegrationTests/BasicTests.swift, Sources/Build/BuildPlan.swift, Tests/CommandsTests/TestToolTests.swift
Currently, running `swift test` fails when a test target accesses `Bundle.module` during a test (https://forums.swift.org/t/swift-5-3-spm-resources-in-tests-uses-wrong-bundle-path/37051).
This patch uses the bundlePath that already exists instead of crafting the path from `Bundle.main`. I've tested this in both library, executable, and test targets on macOS and it seems to do the trick.
=> [SR-12912] Fix crash in test targets when accessing Bundle.module

Sources/PackageLoading/ManifestLoader.swift, Sources/Workspace/Workspace.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Workspace's reset method removes the cache directory while the sqlite
database is in use, which is a considered a bug in client of sqlite
databases. This exposes a proper way to reset a cache that might be used
by a particular manifest loader implementation.
<rdar://problem/67712262>
=> [PackageLoading] Add a method to properly reset manifest cache

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/PackageLoading/ManifestLoader.swift
This introduces a new `-Xmanifest` flag that will allow the user to pass
additional flags to the manifest build invocation.  This is particularly
important for the case of Windows, where the split SDK/toolchain model
requires the additional flags such as `-sdk` or `-resource-dir` to be
passed to the manifest build system.
=> PackageLoading: introduce `-Xmanifest`

Sources/Workspace/Destination.swift
Windows does not really use libstdc++ (although it would be useful under
MinGW).  This allows building on the Windows target.
=> Workspace: remove `-lstdc++` on Windows

Sources/Commands/SwiftTestTool.swift
The ArgumentParser adoption changed the default test specification to be `.skip([])` instead of `.none` — this change switches it back. I'll follow up with test coverage in a later PR.
=> Use .none as the default test specification

Utilities/bootstrap
I accidentally added it as a build argument.
=> `--skip-integrated-driver-tests` should be a test argument

Tests/FunctionalTests/MiscellaneousTests.swift
After apple/llvm-project#1718, we should see no remaining issues from
this test.
=> Re-enable Test

Documentation/Development.md
Also add copyable command lines for the other two dependencies as well, since we're having to add one for the `0.3.0` tag for argument parser (looks odd to have the command line for two out of the four repositories).
=> Update the Development documentation for the bootstrapping with the swift-argument-parser dependency

Sources/XCBuildSupport/PIFBuilder.swift
In PIF generation, we were unconditionally generating a module map, but this needs to be conditional on whether `clangTarget.moduleMapPath` exists.
=> Make module map generation conditional

Sources/Xcodeproj/XcodeProjectModelSerialization.swift, Tests/XcodeprojTests/XcodeProjectModelSerializationTests.swift
SR-1754: Spaces should be escaped in HEADER_SEARCH_PATHS
=> [Xcodeproj] Quote space-separated build settings when necessary.

Sources/SourceControl/GitRepository.swift, Sources/SourceControl/InMemoryGitRepository.swift, Sources/SourceControl/Repository.swift, Tests/SourceControlTests/GitRepositoryTests.swift
SwiftPM fetches a remote repository by mirroring it to the local file system, then clones that local repository to a working directory, after which it checks out a specific ref.
When the local clone happens, Git also does a checkout.  This is unnecessary, since the checkout will immediately be replaced by the intended ref, and it also makes the checkout sensitive to whether the default branch name is set up correctly for the repository.
Since the working copy is guaranteed to be checked out after the clone, there is no need to do a checkout as part of the cloning.
rdar://68165300
=> [SR-13484] Use `--no-checkout` when cloning packages, since it's immediately followed by a `checkout` anyway

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/MinimumDeploymentTarget.swift, Tests/CommandsTests/PackageToolTests.swift
For the tools that are in fixed locations, SwiftPM should run them using absolute paths.
Failing to do so will cause the build to fail when running `swift build` under certain environments such as tests where PATH is set incorrectly.  It's also a bad idea to run `sandbox-exec` out of a random location.
Furthermore, it is not valid to invoke `xcrun` from any other location but `/usr/bin`, so we should not spend time looking up a constant.
rdar://68374424
=> SwiftPM should be more resilient against random binaries named `xcrun` and `sandbox-exec` in the PATH

Utilities/bootstrap
This makes bootstrapping immune to whatever defaults are set in swift-llbuild's own CMake files, and makes bootstrapping succeed again.
rdar://68383324
=> On Darwin, pass CMAKE_OSX_ARCHITECTURES with just the host during the CMake portion of the bootstrap.

Utilities/bootstrap
These flags were only passed for regular builds, but not for testing or other actions.
rdar://problem/68542579
=> Cross-compile flags should be in `get_swiftpm_flags`

Utilities/bootstrap
Only the last commit is new, the rest is from #2736
=> [bootstrap] Add swift-argument-parser as a bootstrapped swift-driver dependency

Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
This just makes XCBuild support match what we do in SwiftPM's own build
system here: https://github.com/apple/swift-package-manager/blob/master/Sources/XCBuildSupport/PIFBuilder.swift#L308
We should probably revisit this behaviour, because this seems like a
very confusing side effect on macOS where test discovery isn't even a
thing, but right now we just want to match what the builtin build system
does.
(cherry picked from commit 57f9d0d305fd3dc9fa53e00ae82db62249e14569)
=> Enable testability if test discovery is enabled

Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Utilities/bootstrap
5.3 cherry-pick of https://github.com/apple/swift-package-manager/pull/2916 and #2918
=> [5.3] Fix cross-compile bootstrap

Sources/Build/BuildPlan.swift, Sources/PackageLoading/ModuleMapGenerator.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Target.swift, Sources/Workspace/Diagnostics.swift, Sources/Xcodeproj/pbxproj.swift, Tests/PackageLoadingTests/ModuleMapGenerationTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
This also modifies module map generation to use the unified logic for determining the module map type, and cleans up diagnostics reporting.
With detection of module map type (based on a target's header layout) separate from generation of a module map, the existing ModuleMapGenerator API of having a struct that gets initialized only to perform the one operation (either determining module map type of generating a module map) is a bit clunky.  We may want to refine that to make these standalone functions, but I think that can be done as a separate PR.
Vending the target's module map layout information provides more semantic information to the client than just vending the raw contents of the generated module map.  This semantic information can then (for example) be shown in the user interface …
=> [SR-13235] libSwiftPM should vend a ClangTarget's module map generation information to clients

Package.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftPackageTool.swift
There's a conflict between '--enable-code-coverage' in the top-level options and the same flag in the Xcode-project generation command. This uses the top-level flag (which is required for the build parameters, even though it's only ever used by `swift test`) for both purposes.
=> Use global code coverage flag in `swift package generate-xcodeproj`

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
https://bugs.swift.org/browse/SR-648 has been resolved, so we can enable
this flag on Linux
=> Enable --static-swift-stdlib on Linux

Sources/Build/ManifestBuilder.swift
This case was just added to swift-driver in https://github.com/apple/swift-driver/pull/144, causing an SPM build failure because the switch was no longer exhaustive. File lists can be treated the same as temporary files when resolving to a node.
=> Handle new SwiftDriver.VirtualPath case in ManifestBuilder

Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
This also sets the code up to make it easier to do other similar heuristics as needed, and as a bonus, adds one that is related to the `master` -> `main` renaming (suggesting `main` if `master` is requested and doesn't exist, but `main` does).  There isn't yet any support for fix-its in SwiftPM, but this would be a case for such a facility once it is supported.
Note that tags go through different processing, since they are the inputs to the semantic versioning and missing tags are reported differently.  There is no way in SwiftPM to define an explicit dependency on a non-semver tag, which is why this code only needs to handle branches and commits.
The error message does not list all the branches, since there can be many, but that could be another future improvement (or at least to list …
=> Improve the diagnostics that are emitted when a package dependency specifies a non-existent branch or commit

Sources/Workspace/CMakeLists.txt
`Sources/Workspace/UserToolchain.swift` references `PackageLoading` but
the build did not list the dependency.  Add the missing dependency.
=> build: list the `PackageLoading` dependency

Sources/PackageGraph/PinsStore.swift, Tests/PackageGraphTests/PackageGraphTests.swift
This used to be a fatal error, instead we're now printing a more friendly error to the user.
rdar://problem/68928705
=> Handle duplicated keys in `PinsStore`

Examples/package-info/Sources/package-info/main.swift, Sources/PackageLoading/CMakeLists.txt, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/UserManifestResources.swift, Sources/SPMTestSupport/Resources.swift, Sources/Workspace/CMakeLists.txt, Sources/Workspace/UserToolchain.swift, Sources/Workspace/WindowsToolchainInfo.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Use the special environment variable named `SDKROOT` which provides the
root of the SDK as a means for deriving the flags for building code on
Windows.  We assume that the layout is in the following canonical
layout (subject to incompatible evolution):
```
Developer                                         (%DEVELOPER_DIR%)
`- Platforms
`- Windows.platform
+- Developer
|   +- Library
|   |    `- XCTest-[Version]
|   `- SDKs
|       `- Windows.sdk                  (%SDKROOT%)
|           +- SDKSettings.plist
`- Info.plist
```
This adds 3 sets of flags to the `Xmanifest` options by default:
- `-sdk` which should theoretically be sufficient for everything
- `-I`, `-L`, `-resource-dir` which serve as workarounds for bugs in the
SDK and swift driver
- `-libc MD` by inspecting the contents of …
=> PackageLoading,Workspace: derive flags for Windows

swift-tools-support-core/Sources/TSCBasic/GraphAlgorithms.swift
`topologicalSort` and `findCycle` function from the `Basic` module has `FIXME`s saying the needed to be converted to use stack instead of recursion.
Both algorithms have pretty much the same implementation. System stack and recursion is emulated using `OrderedDictionary` collection which key-value pair represents a single stack frame. The key is a node that is being traversed and the value is an array slice of its successors.
=> Changing recursive implementation of graph algorithms to iterative

Sources/SPMTestSupport/TestWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
(for status and logs in clients such as IDEs)
=> Add Workspace callbacks for when each package is loaded

IntegrationTests/Tests/IntegrationTests/BasicTests.swift, Sources/Build/BuildPlan.swift
Same as #2817, resolves SR-12912 in the `release/5.3` branch.
Setting the path for Bundle.module fails in the case where the bundle is accessed during tests.
This uses the already derived bundlePath instead.
=> [SR-12912] Fix crash in test targets with Bundle.module in 5.3

Sources/Commands/SwiftTestTool.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/UserManifestResources.swift, Sources/Workspace/UserToolchain.swift
Windows does not support the concept of `rpath`.  Adjust the path when
invoking the test binary to include XCTest in the Path, enabling the
test execution.
=> Commands: make `swift test` work on Windows

Sources/PackageLoading/ManifestLoader.swift
This allows clients of libSwiftPM to continue building without being modified.
=> Add an empty implementation of the new function `swiftCompilerFlags` in the ManifestResourceProvider

swift-tools-support-core/Sources/TSCUtility/Diagnostics.swift, swift-tools-support-core/Tests/TSCUtilityTests/DiagnosticsUtilityTests.swift
This is a cherry-pick from the swift-tools-support-core change, to sync up the vendored copy of TSC in SwiftPM with the separate one.
=> Add a way for emittable diagnostics (e.g. Swift.Errors) to provide custom DiagnosticLocations

Sources/Build/BuildDelegate.swift
This is required for test discovery to work properly.  We would
previously incorrectly compute the location for IndexStore, and fail to
discover tests as a result.
=> Build: correct lookup for `libIndexStore.dll` on Windows

Sources/PackageGraph/PackageGraphLoader.swift, Tests/PackageGraphTests/PackageGraphTests.swift
Move the instantiation of PackageBuilder into the `diagnostics.with(location:)` closure that sets the package location.
Without this, errors thrown for a package would be associated with a location, but regularly emitted diagnostics would not.  The reason is that when the PackageBuilder is instantiated outside of the `diagnostics.with(location:)`, it keeps the unlocationed diagnostics engine as a property, and then uses that for all the diagnostics even though the `construct()` call happens inside of a with-location closure.
This change allows all the diagnostics emitted by the PackageBuilder to be properly associated with the package.
This also fixes a unit test that does not seem to have been testing the correct location to begin with.
=> Make sure that a package location is associated with the diagnostics emitted from PackageBuilder for a particular package

Sources/PackageLoading/PackageBuilder.swift
This fixes a crash related to build conditionals which looks like a
longer standing bug that was triggered by https://github.com/apple/swift-llbuild/pull/681
Unforunately, llbuild CI doesn't test the package, so it slipped through
and now causes SwiftPM to crash when building itself
rdar://problem/67432513
=> [5.3] Fix crash related to build conditionals

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
https://bugs.swift.org/browse/SR-648 has been resolved, so we can enable
this flag on Linux
Cherry pick of https://github.com/apple/swift-package-manager/pull/2921
=> Enable -static-stdlib on Linux (#2921)

Sources/PackageDescription/CMakeLists.txt, Utilities/bootstrap
before installing.
It has been suggested to me by some Swift devs that this would be good to get in before the 5.3 release, a cherry-pick from #2703.
This should be completely safe for the 5.3 branch, as it's just removing the build toolchain's stdlib rpath, which should be unused by SPM.
=> [5.3] On ELF platforms, remove the host toolchain rpath from executables and shared libraries

Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
This will help with error reporting, especially in clients of libSwiftPM.
=> Make sure that GetDependenciesError diagnostics have a associated diagnostic location that identifies the repository

Sources/Build/ManifestBuilder.swift
This name matches the actual language-level module name versus the target name.
These names are not always the same so when we get it wrong, module dependencies get lost.
=> [Explicit Module Builds] Use c99name instead of name when forming a list of external module dependencies

Sources/Build/ManifestBuilder.swift
System modules will consist of a `.modulemap` somewhere in the filesystem, with the path to that module being either manually-specified on the `build` command or computed based on the system module type (apt, brew).
Similarly, binary targets will bring in an `.xcframework`, the contents of which will be exposed via search paths.
In both cases, the dependency scanning action in the driver will be automatically be able to detect such targets' modules.
=> [Explicit Module Builds] Skip over binary and systemLibrary targets when generating explicit target build jobs

Sources/Build/BuildPlan.swift, Sources/Build/ManifestBuilder.swift
- When computing command line arguments for the integrated driver invocation, append all source files, both belonging to the package and derived.
- When writing out an output file map, add derived source files and their build artifacts to it as well.
Before this change, the [Implicit | Explicit] integrated driver flow ignores derived files when building a target and therefore is not able to handle targets with specified resource bundles, for example.
=> [Integrated Swift driver] Handle derived source files in the integrated driver.

Sources/Build/CMakeLists.txt, Sources/Build/ManifestBuilder.swift, Sources/Build/SPMSwiftDriverExecutor.swift
SPM does not need or use the full functionality of SwiftDriverExecutor, which we're planning to move to a separate library so that the SwiftDriver planning library no longer depends on LLBuild. Introduce a minimal SPMSwiftDriverExecutor for the processes the integrated driver needs to launch during planning.
=> Replace SwiftDriverExecutor with SPMSwiftDriverExecutor

Tests/FunctionalTests/MiscellaneousTests.swift
We are seeing CI failures of the form:
```/private/var/folders/_8/79jmzf2142z2xydc_01btlx00000gn/T/Miscellaneous_ParallelTestsPkg.s9qJNJ/Miscellaneous_ParallelTestsPkg/Tests/ParallelTestsPkgTests/ParallelTestsFailureTests.swift:1:8:
error: compiled module was created by an older version of the compiler;
rebuild 'XCTest' and try again:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftmodule
```
Let's skip these tests while we are investigating.
=> Skip tests related to ParallelTestsPkgTests

Sources/PackageDescription/CMakeLists.txt, Utilities/bootstrap
Without it, we don't see API documentation.
This fix covers both CMake and the bootstrap script.
=> The PackageDescription.swiftdoc file is missing on Darwin

Sources/Commands/SwiftTool.swift, Sources/SPMTestSupport/Resources.swift, Sources/Workspace/UserToolchain.swift
Currently, when building for WASI, our users need to provide a `destination.json` file that contains a WASI sysroot path. It would be great if the sysroot path could be inferred automatically from PATH, when the appropriate WASI triple is requested as the destination platform. With this PR it's enough to pass `--triple wasm32-unknown-wasi` to `swift build` to build for WASI.
Unused private `processEnvironment` property of `UserToolchain` is removed.
(cc @kateinoigakukun)
=> Wasm/WASI: propagate PATH to UserToolchain to fix sysroot search

Tests/BuildTests/BuildPlanTests.swift
This makes it easier to tell whether or not the environment is properly configured to test explicit module builds.
=> Skip testExplicitSwiftPackageBuild instead of silently passing if toolchain is too old

swift-tools-support-core/Sources/TSCBasic/Path.swift, swift-tools-support-core/Tests/TSCBasicTests/PathTests.swift
`basenameWithoutExt` method is very useful and already present in `AbsolutePath` type. It would be nice to have it also available in `RelativePath`.
Removed ` // FIXME: We also need tests for dirname, basename, suffix, etc.`, looks it has been already addressed.
=> Add basenameWithoutExt method to RelativePath

CMakeLists.txt, Sources/Build/CMakeLists.txt
Yams is not directly used by swift-package-manager.  Remove the
unnecessary check and linkage.
=> build: remove Yams references from SPM

Sources/PackageLoading/Target+PkgConfig.swift, Tests/PackageLoadingTests/Inputs/Bar.pc, Tests/PackageLoadingTests/PkgConfigTests.swift, Tests/PackageLoadingTests/WhitelistTests.swift, swift-tools-support-core/Sources/TSCBasic/StringConversions.swift, swift-tools-support-core/Sources/TSCTestSupport/PseudoTerminal.swift, swift-tools-support-core/Sources/TSCUtility/PkgConfig.swift, swift-tools-support-core/Tests/TSCBasicTests/TerminalControllerTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/ProgressAnimationTests.swift
=> Remove non-inclusive language

Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/SourceControlTests/GitRepositoryTests.swift
This makes sure that Git failures clients can distinguish from other Process errors (so failure handling can be customized), and that they all have a location.  At present the location for an error during a cloning operation is the remote URL, while the operation for an operation on a local clone is the path of the local clone.  We might want to extend this in the future so that local clones also keep track of the URL, but this will require the GitRepository to keep a copy of the associated RepositorySpecifier of its origin remote.  This would in turn require a change to the Repository protocol so that all methods take a RepositorySpecificier, and it would require changes to all the clients.  So that should be a separate PR.
=> Add a customized GitRepositoryError and funnel all Git operations through a method that throws one of those if an operation fails.

Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/SourceControlTests/GitRepositoryTests.swift
Reverts apple/swift-package-manager#2958 because we are reverting a change that this depends on in TSC: https://github.com/apple/swift-tools-support-core/pull/143
=> Revert "Add a customized GitRepositoryError and funnel all Git operations through a method that throws one of those if an operation fails."

Sources/Build/BuildPlan.swift
We need to ensure that we escape `\` for paths in strings.  This enables
using bundles for tests on Windows.
=> Build: quote the path string for bundle resources

Sources/Commands/SwiftTestTool.swift
We need to construct the test environment on Windows to list the tests.
This adds that to the list test path on both Linux and Windows.  The
impact of this change on Linux is that additional environment variables
may be defined when executing the tests.
Resolve SR-13694!
=> Commands: make `--list-tests` work on Windows

Sources/Commands/CMakeLists.txt, Sources/PackageDescription/CMakeLists.txt, Sources/PackageLoading/CMakeLists.txt, Sources/Workspace/CMakeLists.txt
This is meant to support the Windows toolchain build which uses a staged
build where Foundation is prebuilt and will be used from the prebuilt
image rather than from a build root.
=> build: permit building without Foundation build roots

Sources/PackageDescription/Target.swift
The doc comment doesn't specify that the value of `publicHeadersPath` should be relative to the value specified in `path`.
=> NFC: clarify Target.publicHeadersPath comment

Sources/Workspace/UserToolchain.swift
This cleans up the unnecessary flags now that they are not absolutely
required.  This will break compatibility with older releases, however,
because there is no current stable release on Windows with
swift-package-manager support, this is acceptable.
=> Workspace: remove unnecessary flags on Windows

Sources/Build/ManifestBuilder.swift
This will allow adding new enum cases without breaking the SPM build, like in https://github.com/apple/swift-driver/pull/250. It's not a perfect solution, but it solves the immediate issues with exposing an enum (`VirtualPath`) as public API.
=> Avoid switching over SwiftDriver.VirtualPath

Package.swift, Sources/Build/CMakeLists.txt, Sources/PackageLoading/CMakeLists.txt, Sources/Workspace/CMakeLists.txt, Sources/Workspace/Destination.swift, Sources/Workspace/UserToolchain.swift
The declared dependencies haven't followed some of the code changes, and this corrects some of those.  This prunes some of the dependencies of the Workspace and the PackageLoading targets down to no longer have indirect dependencies on llbuild.
=> Correct and clean up some of the target dependencies in the closure of libSwiftPM

Documentation/libSwiftPM.md, Package.swift, Utilities/bootstrap
This is a subset of the libSwiftPM library, which remains unchanged so as to avoid breaking any clients.  In order to avoid too much duplication in the bootstrap script, I factored it so that multiple dylibs with different names and different combinations of modules can be built.  There are separate flags to build the different libraries, so that building just the data model doesn't require building the code that it doesn't depend on.
=> Define libSwiftPMDataModel for clients that want the libSwiftPM data model but not the build system

Documentation/PackageDescription.md
Update the PackageDescription markdown file based on comments in the PackageDescription module.  This is something that unfortunately has to be done by hand at the moment.  I'll look over this PR again and it's possible it will need some iteration, since there were a lot of changes (it hadn't been updated since 5.1, I think).
=> Update the PackageDescription markdown file

Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift, Tests/WorkspaceTests/InitTests.swift
- we were actually not really skipping a few tests, because I didn't do
that correctly in #2948
- we need to skip a few additional tests which are using the same
functionality (running an inferior `swift test`)
Supersedes #2982
=> Fix skipping of tests and skip some additional ones

Sources/PackageGraph/RepositoryPackageContainerProvider.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/SourceControlTests/GitRepositoryTests.swift
This makes sure that Git failures clients can distinguish from other Process errors (so failure handling can be customized), and that they all have a location.  At present the location for an error during a cloning operation is the remote URL, while the operation for an operation on a local clone is the path of the local clone.
We might want to extend this in the future so that local clones also keep track of the URL, but this will require the GitRepository to keep a copy of the associated RepositorySpecifier of its origin remote.  This would in turn require a change to the Repository protocol so that all methods take a RepositorySpecificier, and it would require changes to all the clients.  So that should be a separate PR, if we do it.
This is a re-opening of a PR …
=> Add a customized GitRepositoryError and funnel all Git operations thr ough a method that throws one of those if the operation fails

Sources/Commands/Options.swift, Sources/SPMBuildCore/Sanitizers.swift, Tests/BuildTests/BuildPlanTests.swift
This makes a few small improvements to using sanitizers:
1. Include the valid values in `--help`.
Before:
```
--sanitize <sanitize>  Turn on runtime checks for erroneous behavior
```
After:
```
--sanitize <sanitize>  Turn on runtime checks for erroneous behavior,
possible values: address, thread, undefined, scudo
```
2. Improve error for invalid values.
Before:
```
error: unknown value 'invalid' for argument --sanitize; use --help to print usage
```
After:
```
error: The value 'invalid' is invalid for '--sanitize <sanitize>': valid sanitizers: address, thread, undefined, scudo
```
3. Allow underlying values as arguments.
Before:
```
error: unknown value 'tsan' for argument --sanitize; use --help to print usage
```
After:
Works!
Fixes:
- https://bugs.swift.org/browse/SR-12545
- …
=> Improve sanitizer usage

Sources/Build/BuildDelegate.swift
rdar://69970428
After running `swift build` the final output could display a ‘success message’ (if the build is successful) and some basic infos about where the generated binaries are located.
Currently, after a successful build, it ends with exit code 0 and the output is:
`[476/476] Linking swift-package`
Result after changes:
**Success**:
=> Add Build Success Message in Console

Package.swift
It seems to me that `libSwiftPMDataModel` instead of `libSwiftPM` was meant in this context.
=> Fix comment typo in `Package.swift`

Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/CMakeLists.txt
`InMemoryGitRepository` is currently located in the `SourceControl` module, but is used exclusively for testing. This PR moves it to the `SPMTestSupport` module, to clarify the scope and nature of its use.
=> Move InMemoryGitRepository to SPMTestSupport

Sources/PackageGraph/DependencyResolutionNode.swift, Sources/PackageModel/Manifest.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageModelTests/ManifestTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
We are seeing some issues with the full implementation of target-based dependency resolution done in #2749 and need to temporarily disable it to unblock affected projects. The changes are still available behind a compile-time define `ENABLE_TARGET_BASED_DEPENDENCY_RESOLUTION` and the tests have been modified accordingly to work in both cases (some tests are skipped by default for now and only enabled when enabling target-based dependency resolution).
I haven't yet distilled the issues into test cases, but once I have I'll start a branch of re-enabling this again.
rdar://problem/65284674
=> Temporarily disable target-based dependency resolution

Sources/SPMTestSupport/XCTAssertHelpers.swift
This ends up polluting the output of `swift test` quite a bit and doesn't seem very useful. I am assuming it was just accidentally left there.
=> Remove print statement

swift-tools-support-core/Sources/TSCUtility/Triple.swift
Mirrors https://github.com/apple/swift-tools-support-core/pull/153.
=> Wasm executables should have .wasm extension

Sources/Workspace/UserToolchain.swift, Sources/Workspace/WindowsToolchainInfo.swift
Add the support for the platform to specify extra flags to the Swift
compiler.  This is intended to be used for Windows to pass `-use-ld=lld`
by default when building SPM.  The reason to prefer this the
configuration is that using the native tools is preferable normally,
however, when building with SPM, the AST wrapping and debug info
generation tends to confuse link.exe sometimes.  Additionally, extra
flags are required for using link which are not required when using lld
(namely, `/incremental:no` to avoid incremental linking which will add
padding to the metadata which the runtime does not expect).
=> Workspace: allow passing extra swiftc flags via Info.plist

Sources/PackageGraph/PackageModel+Extensions.swift, Tests/WorkspaceTests/WorkspaceTests.swift
At this point (until we…change the semantics), an explicitly provided name in a package dependency is _not_ used as the identity.  It is validated against what the package manifest claims, but does not currently constitute the identity.
re: https://github.com/apple/swift-package-manager/pull/2997
rdar://problem/70764221
=> Fix a recent regression in package identity

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
Current implementation propagates `-static-stdlib` flag only for Linux, but wasm also needs to use that flag to link stdlib and Foundation statically because wasm only supports static linking at now. So I changed to allow it for wasm32.
=> [WASM] Propagate -static-stdlib for wasm32

Sources/SPMBuildCore/BuildParameters.swift, Tests/BuildTests/BuildPlanTests.swift
Test products produced for Wasm are not really test bundles. Running `swift build --build-tests --triple wasm32-unknown-wasi` produces a single WebAssembly binary that has to be run manually in a suitable WebAssembly host. Thus, `.xctest` is not really a fitting extension for these binaries. In my opinion, it would be best for produced test binaries to have the `.wasm` extension.
CC @kateinoigakukun
=> Wasm: test products should have .wasm extension

Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XCBuildOutputParser.swift
If we fail to parse a message, throw an Error instead of crashing. Also,
mark a few fields which actually can be nil, as optional.
rdar://70919533
=> Improve robustness of XCBuild output parser

CMakeLists.txt, Utilities/bootstrap
Rather than building with CMake and then using that freshly built swift-build to build it with itself, add this flag to check for a prebuilt swift-build next to swiftc and use that instead if it's there. The PackageDescription libraries are still built using CMake, as this repo's Package.swift only builds the latest 4_2 version.
This is part of [my patches to cross-compile the corelibs and SPM for Android using the official prebuilt Swift toolchain for Ubuntu](https://github.com/termux/termux-packages/tree/master/packages/swift), as it doesn't make sense to rebuild a native SPM before cross-compiling it, since the official toolchain already has a native swift-build.
I tested this pull with the Oct. 22 source snapshot and official prebuilt snapshot toolchain after applying this small patch …
=> [bootstrap] Add a --skip-cmake-bootstrap flag to use a prebuilt swift-build

Sources/PackageLoading/ManifestLoader.swift, Sources/XCBuildSupport/PIFBuilder.swift
This was only cherry-picked into 5.3 recently: https://github.com/apple/swift-corelibs-foundation/pull/2889, so to get SwiftPM to build with the 5.3 released toolchain on non-Darwin platforms, we have to conditionalize it.
=> Conditionalize use of `.withoutEscapingSlashes`

Sources/XCBuildSupport/XCBuildOutputParser.swift
The original patch missed that XCBuild still emits empty strings for the
interestingPath field. Handle this.
=> <rdar://70975582> SwiftPM crashes when parsing XCBuild's output (v2)

Sources/PackageDescription/SupportedPlatforms.swift
As reported by @broadwaylamb in SR-13813:
>In my project, I want to only build a SwiftPM target when the platform I'm building for is *not* `.wasi`. For that, I wrote the following code in my `Package.swift`:
```swift
// This list should be updated whenever SwiftPM adds support for a new platform.
let supportedPlatforms: [Platform] = [
.macOS,
.iOS,
.watchOS,
.tvOS,
.linux,
.android,
.windows,
.wasi,
]
extension Array where Element: Equatable {
func except(_ exceptions: [Element]) -> [Element] {
return filter { platform in
!exceptions.contains(platform)
}
}
}
```
>I expected that I could write:
```swift
.target(name: "WASIIncompatibleTarget",
condition: .when(platforms: supportedPlatforms.except([.wasi])))
```
>However, that didn't work because `Platform` is not `Equatable. I see no …
=> Make Platform/SupportedPlatform types Equatable

Documentation/libSwiftPM.md
The Makefile doesn't appear to have existed for some time and the
example appears to run fine without it.
=> Remove instructions to use make in libSwiftPM example.

Package.swift, Sources/Basics/CMakeLists.txt, Sources/Basics/FileSystem+Extensions.swift
motivation: with the introduction of TSC there is no more room for common SwiftPM utilities such as FS extensions
changes:
* add Core module that dependends on TSC and make everything depend on it
* add FS extensions for getting ~/.swiftm and SwiftPM's cache directory
* adjust code to latest TSC FS changes
=> add Core module to place common utilities such as FileSystem extensions

Sources/Xcodeproj/SchemesGenerator.swift, Sources/Xcodeproj/pbxproj.swift
Motivation:
Repeated runs of generate-xcodeproj generate different results
as Set is used to store targets which is ordered by hash.
Hash is randomly seeded between runs making the set be differently
ordered on each run.
Having the output reordered on rerun makes comparison very difficult
and is particularly annoying if the generated project is to be stored
in revision control or similar.
Change:
Sort the targets before output, removing the major
source of differences between runs.
=> Sort targets for outputting to xcodeproj.

Sources/Build/BuildOperation.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, swift-tools-support-core/Sources/TSCBasic/FileSystem.swift, swift-tools-support-core/Sources/TSCBasic/PathShims.swift, swift-tools-support-core/Tests/TSCBasicTests/FileSystemTests.swift, swift-tools-support-core/Tests/TSCBasicTests/POSIXTests.swift, swift-tools-support-core/Tests/TSCBasicTests/PathShimTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/DownloaderTests.swift
motivation: latest changes to FS APIs are breaking SwiftPM
changes:
* resync vendored copy of TSC
* adjust FS implementation in SwiftPM to new API
* address warnings from deprecated APIs
=> adjust to latest TSC FS APIs

swift-tools-support-core/Sources/TSCBasic/Await.swift, swift-tools-support-core/Tests/TSCBasicTests/AwaitTests.swift
To aid with (further) source compatibility testing, rename `await` to
`tsc_await` to get it out of the way of the use of the `await` keyword
in Swift's Concurrency design. Leave the `await` here as deprecated
entry points so we don't break any code in the process.
=> Rename "await" to "tsc_await"

Package.swift, Sources/SPMTestSupport/Resources.swift, Sources/SPMTestSupport/misc.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Tests/XCBuildSupportTests/PIFTests.swift, Tests/XcodeprojTests/FunctionalTests.swift
Remove a dependency of the SPMTestSupport target on the Command target, which in turn depends on Build, etc.  This lets the subset of unit tests that doesn't actually require the command line tools to still be used to test libSwiftPMDataModel.
The only real code change needed is to move two tests that are actually testing handling of command line arguments of the `swift-build` tool from BuildPlanTests to BuildToolTests.  This is where it belonged anyway, architecturally, since it's testing command line arguments.
=> Make SPMTestSupport not require the command line tools (so it can be used for libSwiftPMDataModel)

Sources/SPMTestSupport/misc.swift
Each passed successfully but one unintentionally restored an import that the other had removed.
These were https://github.com/apple/swift-package-manager/pull/3029 and https://github.com/apple/swift-package-manager/pull/3019
=> Fix a build failure resulting from a race condition between two PRs.

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SPMPackageEditor/PackageEditor.swift, Sources/Workspace/Workspace.swift, Tests/PackageCollectionsTests/PackageCollectionsProfileStorageTest.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
This is the follow-on to https://github.com/apple/swift-package-manager/pull/3036, adopting the new swift-tools-support-core and using `tsc_await` in lieu of `await`.
=> Use tsc_await rather than await

Sources/PackageCollections/API.swift, Sources/PackageCollections/CMakeLists.txt, Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/Model/License.swift, Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/Model/Search.swift, Sources/PackageCollections/Model/TargetListResult.swift, Sources/PackageCollections/PackageCollectionProvider.swift, Sources/PackageCollections/PackageCollections+Configuration.swift, Sources/PackageCollections/PackageCollections+Storage.swift, Sources/PackageCollections/PackageCollections+Vallidation.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Storage/PackageCollectionsProfileStorage.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Sources/PackageCollections/Utility.swift, Tests/PackageCollectionsTests/PackageCollectionsProfileStorageTest.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
motivation: continue the implmentation of package-collections
changes:
* implemented PackageCollectionsProtocol which is the main business logic of the feature
* added basic configuration model for the feature
* added basic validation rules for collection source
* simplfied model names to be shorter
* added relevants tests
=> implement package-collections business logic

Tests/PackageCollectionsTests/PackageCollectionsTests.swift
motivation: adjust code to new function name, get rid of warnings
changes: use `tsc_await` instead of `await`
=> await -> tsc_await catch up

Sources/PackageModel/CMakeLists.txt, Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Ability to write out package manifests as source code, providing more flexibility for things like mechanical package manifest generation.
Note that this is _not_ suitable for editing the package manifest, since that would need to preserve whitespace and comments.  Rather, this is for things like automatically generating packages from test sets, or for generating the initial configuration of packages (e.g. a more flexible `package init`).
rdar://70271810
=> Ability to write out package manifests as source code (for mechanical package generation)

Sources/Build/SPMSwiftDriverExecutor.swift
In order to implement interleaved waves for incremental builds in swift-driver, the `DriverExecutor` protocol was changed. Update `SPMSSwiftDriverExecutor` to conform. 
Requires: https://github.com/apple/swift-driver/pull/351
=> [Incremental] Update DriverExecutor protocol to be consistent with swift-driver

Package.swift
To make the new module available to clients of the various versions of libSwiftPM, we need to add it to the corresponding products.
=> Export "PackageCollections" module to clients

Sources/PackageCollections/Model/Profile.swift
It is expected that clients have to construct `Profile` objects themselves, so there should be a public initializer.
=> Add public initializer to `Profile`

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
--static-swift-stdlib support on Linux is introduced by https://github.com/apple/swift-package-manager/pull/2921 but it doesn't work when linking CoreFoundation.
When CoreFoundation is used on a project and a user uses --static-swift-stdlib, SwiftPM compiled object files without
-static-stdlib and linked them with that option. This mismatch of compiler option broke swift autolink mechanism.
The object files built without -static-stdlib references `/lib/swift/CoreFoundation/module.map`, which is intended to be used for dynamic linking, and the modulemap doesn't have `link "CoreFoundation"` statement. So the autolink sections in built object files doesn't have `-lCoreFoundation` and it causes linking failure.
This issue was reported on …
=> Pass -static-stdlib for all compiler jobs

Sources/PackageCollections/Storage/PackageCollectionsProfileStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
motivation: broken build on older swift versions for linux
changes: replace unsupported functions with supported ones
=> linux adjustments

Utilities/build_ubuntu_cross_compilation_toolchain
The core libs files branch is now called main and not master, the script build_ubuntu_cross_compilation_toolchain fails silently because it can't find the file https://raw.githubusercontent.com/apple/swift-corelibs-libdispatch/master/src/BlocksRuntime/Block.h. 
The script no longer works, and I'd like it to work again 😊
Update of the url to https://raw.githubusercontent.com/apple/swift-corelibs-libdispatch/main/src/BlocksRuntime/Block.h
The script completes successfully again.
=> build_ubuntu_cross_compilation_toolchain URL Fix

Package.swift, Sources/Basics/CMakeLists.txt, Sources/Basics/DispatchTimeInterval+Extensions.swift, Sources/Basics/FileSystem+Extensions.swift, Sources/Basics/HTPClient+URLSession.swift, Sources/Basics/HTTPClient.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
motivation: incoming features use HTTP to access remote resources: package collection and package registry. we should abstract given complexy around error handling and non-apple platform support
changes:
* create HTTPClient utility in Basics modules
* implement URLSession based backend
* implment exponential backoff
* implement (naive) circuit breaker
* add tests
TODO:
⚠️   discuss our approach to non-apple platforms (given FoundationNetworking dependency on OpenSSL)
=> HTTP Client abstraction 

Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Sources/Workspace/Diagnostics.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, swift-tools-support-core/Sources/TSCBasic/FileSystem.swift, swift-tools-support-core/Sources/TSCBasic/Lock.swift, swift-tools-support-core/Sources/TSCBasic/WritableByteStream.swift, swift-tools-support-core/Sources/TSCUtility/Archiver.swift, swift-tools-support-core/Tests/TSCBasicTests/FileSystemTests.swift, swift-tools-support-core/Tests/TSCUtilityTests/ArchiverTests.swift
Mirrors https://github.com/apple/swift-tools-support-core/pull/167 change to the TSC package.
I've recently stumbled upon this error when running `swift build`:
```
error: noEntry
```
This is the exact and only output of this `swift build` invocation. Unfortunately, I think it's impossible to diagnose without an attached debugger. It's also hard to pinpoint where exactly the error comes from in the source code, since `FileSystemError.noEntry` is thrown from multiple places.
In my opinion, for an error value to be helpful it should have associated information attached to it. In this case, it would make sense for almost all cases of `FileSystemError` to have an associated `AbsolutePath` value.
`FileSystemError` now also has to be explicitly declared `Equatable` to make the tests compile, …
=> Improve FileSystemError by adding associated path

CHANGELOG.md, Sources/Commands/SwiftPackageTool.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/Workspace/ToolsVersionWriter.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift, Tests/WorkspaceTests/ToolsVersionWriterTests.swift
ORIGINAL DESCRIPTION
---------------
[SR-13566](https://bugs.swift.org/browse/SR-13566)
This pull request changes the regex pattern on line [181 of swift-package-manager/Sources/PackageLoading/ToolsVersionLoader.swift](https://github.com/apple/swift-package-manager/blob/9e0a63fe8e148cf8b645a8d870b43f8e59ff6701/Sources/PackageLoading/ToolsVersionLoader.swift#L181) to allow any combination of _horizontal_ whitespace characters between "//" and "swift-tools-version" in the swift tools version specification in `Package.swift`
The old regex pattern is `^// swift-tools-version:(.*?)(?:;.*|$)`
The new regex pattern is `^//\h*?swift-tools-version:(.*?)(?:;.*|$)`
---
NEW DESCRIPTION (2020-11-04)
---------------
This PR proposes the following changes to the parsing of the `Package` manifest and its …
=> [PackageLoading] Improve flexibility in formatting Package manifests and correctness in parsing Swift tools version specifications

Sources/Commands/SwiftPackageTool.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift
motivation: Starting Xcode 11, packages are directly supported by Xcode and the generate-xcodeproj command is no longer needed
changes:
* add deprecation warning that generate-xcodeproj will be deprecated soon
* add test
rdar://problem/65633238
=> add deprecation warning to 'generate-xcodeproj'

Utilities/bootstrap
This will ensure that multiple build jobs running in parallel on the
same machine using different Swift compilers (like it could be the case in CI) do not interfere with
each other.
Addresses rdar://71487295
=> [bootstrap] Use separate module cache for builds

Sources/CMakeLists.txt, Sources/PackageCollections/CMakeLists.txt
motivation: modules are not available for bootstrap
changes: add missing CMake indexes
=> add missing CMake setup for Basics and PackageCollections

Fixtures/Collections/JSON/good.json, Sources/PackageCollections/CMakeLists.txt, Sources/PackageCollections/JSONModel/JSONCollection+v1.swift, Sources/PackageCollections/JSONModel/JSONCollection.swift, Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/Model/TargetListResult.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageModel/Platform.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
According to https://forums.swift.org/t/package-collection-format/42071
- Rename `summary` and `title` to `description` and `name`, respectively
- Add `keywords` to `PackageCollection.Package`
- Add `minimumPlatformVersions` to `PackageCollection.Package.Version`
- Add `createdBy` to `PackageCollection`
API models and tests are updated as well.
=> Update JSON package collection models

Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections+Validation.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
motivation: nicer code
changes:
* create an internal alias for the model defintion so code is less verbose
* better handling of default http client initialization
=> package collections small refactoring

Sources/Build/CMakeLists.txt, Sources/Commands/CMakeLists.txt, Sources/LLBuildManifest/CMakeLists.txt, Sources/PackageCollections/CMakeLists.txt, Sources/PackageGraph/CMakeLists.txt, Sources/PackageLoading/CMakeLists.txt, Sources/PackageModel/CMakeLists.txt, Sources/SPMBuildCore/CMakeLists.txt, Sources/SPMLLBuild/CMakeLists.txt, Sources/SourceControl/CMakeLists.txt, Sources/Workspace/CMakeLists.txt, Sources/Xcodeproj/CMakeLists.txt
A build error sometimes occurs when building SwiftPM with CMake, because the dependencies on `Basics` target are missing for some other targets. The error might happen or not, depending on the order in which CMake builds the targets.
This change adds the missing dependencies.
The CMake build succeeds after this change.
=> Fix build on Windows: add dependencies in CMake script

Sources/Basics/HTTPClient.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
motivation: provide users with useful information when error condistions occur
changes:
* add DiagnosticEngine to relevant entities in PackageCollection and HTTPClient
* add few diagnostics messages in error cases where users may need to be informed or take action
=> add diagnostics to package collections

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PD5_2LoadingTests.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift
motivation: better diagnostics help uses be self sufficient
changes:
* update error message when target dependencies not found to include list of valid dependencies
* update error message when product refers to unknown target to include list of valid targets
* adjust tests
=> improve error message when targets dependencies are not found

Sources/Xcodeproj/XcodeProjectModel.swift, Sources/Xcodeproj/pbxproj.swift, Tests/XcodeprojTests/PackageGraphTests.swift
Without SUPPORTS_MACCATALYST=YES, the Mac Catalyst build destination
will not be available, and therefore
`xcodebuild -destination 'platform=macOS,variant=Mac Catalyst'`
will fail to build the package.
=> Allow generated Xcode projects to build for Mac Catalyst

Sources/Workspace/Diagnostics.swift
=> NFC: Fix comment typo in Workspace/Diagnostics.swift

Sources/PackageCollections/PackageCollections+Configuration.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
motivate: gfithub emposes API rate limiting, using an auth token helps mitigate low non-auth limits
changes:
* expose auth token configuration that can be set by clients of libSwiftPM
* add functionality to GitHubPackageMetadataProvider to handle auth token
* add functionality to GitHubPackageMetadataProvider to handle api limit errors
* add tests
TODO:
* allow users to configure auth tokens via config files (follow up PR)
=> package metadata: add support for auth tokens 

Sources/Commands/Describe.swift, Tests/CommandsTests/PackageToolTests.swift
As the SwiftPM package model has been extended, the `describe` subcommand hasn't kept up to include new properties.  Also, the implementation was duplicated for JSON and plain-text, raising the possibility that they would get out of sync.
This change reworks the `describe` subcommand to use a unified data model and adds more of the properties defined by the package.
There is some overlap with the `dump-package` subcommand, which actually only dumps the contents of the manifest and not the results of also taking into account the package file system layout.  A future PR should decide what to do about that subcommand.  If it remains, it should probably be renamed to `dump-manifest`.
This adds properties to the `swift package describe` command to make it more useful, and supports both JSON …
=> Rework the `describe` command to emit more information and have a unified implementation for JSON and text

Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
motivation: fixes race condition
changes:
* remove redundant queue
* change return/callback logic to update the result set and deal with errors in a non-racy way
=> fix concurrency issue with GithubMetadata provider

Sources/Commands/Describe.swift
Switch to using `JSONEncoder.makeWithDefaults()` for JSON output formatting of `describe` command, now that it exists.  No change in semantics, so no change to tests.
This cleans up the code by adopting newly added convenience initializers.
Use `JSONEncoder.makeWithDefaults()` in the implementation of the `describe` subcommand rather than the conditional code for the various SDK versions.
No change in semantics, but cleaner code.
=> Switch to using `JSONEncoder.makeWithDefaults()` for JSON output of `describe` command

Sources/PackageDescription/LanguageStandardSettings.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift
Generate the enum cases by preprocessing the [LangStandards.def](https://github.com/apple/llvm-project/blob/apple/main/clang/include/clang/Basic/LangStandards.def) file.
Follow-up to: apple/swift-package-manager#2716
* Add enum cases for C17/C18, C2x, and C++20.
* Deprecate enum cases for C++1z.
* Remove enum cases for C++2a (which aren't in [release/5.3][] yet).
* Update the raw string value for C94 (bug fix).
* New documentation comments.
* New cases for the latest C/C++ language standards.
[release/5.3]: <https://github.com/apple/swift-package-manager/blob/release/5.3/Sources/PackageDescription/LanguageStandardSettings.swift>
=> Update the CLanguageStandard and CXXLanguageStandard enums

Sources/PackageCollections/JSONModel/JSONCollection+v1.swift, Sources/PackageCollections/PackageCollections+Configuration.swift, Sources/PackageCollections/PackageCollections+Validation.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsTests/JSONPackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/ValidationMessageTests.swift
Motivation:
JSON collection needs to be validated before it gets saved to local
storage. We also plan to add a tool for validating JSON collections in
case someone decides to generate them without using the provided
generator.
Modifications:
Implement a validator for `JSONPackageCollectionModel.V1` models to
check for number packages, versions, etc.
=> Add JSONPackageCollectionModel validator

Sources/Commands/SwiftTool.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageModel/SwiftLanguageVersion.swift, Sources/PackageModel/ToolsVersion.swift
Use `#"extended delimiters"#` for regex strings.
This removes a lot of backslashes and make the strings more readable.
Replaced the normal delimiters with extended delimiters for regex strings.
No functional change.
=> [NFC] Use extended delimiters for regex strings

Sources/Basics/HTTPClient.swift, Sources/Basics/JSON+Extensions.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
Motivation:
I was building another project that depends on this repo in docker:
- Swift 5.2 build failing with `requires explicit 'self.'` at a couple of places.
- Swift 5.3 build failing with `'JSONEncoder.OutputFormatting' has no member 'withoutEscapingSlashes'`
Modifications:
Add `self.` where appropriate.
Remove `.withoutEscapingSlashes` for non-Apple platforms.
Result:
Linux builds complete successful with Swift 5.2 and 5.3.
=> Fix Linux builds

Sources/PackageGraph/Pubgrub/PartialSolution.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubgrubTests.swift
motivation: make PubgrubDependencyResolver safer for concurrent work
changes:
* turn PubgrubDependencyResolver into a struct and get rid of it's state
* move all state into a new State abstraction that is thread-safe and can be passed around between funcations
* turn PartialSolution into a struct, highlighting which functions are mutating
* cleanup / move code around in PubgrubDependencyResolver so its easier to reason about
* adjust tests
no functional changes here, just code reorganization
⚠️ based on #3091 and #3092, so let merge those  first
=> more work towards performance improvements

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SourceControl/GitRepository.swift
motivation: improve performance of dependency resolution
changtes:
* cache manifest between calls
* cach tools-versions between calls
* slightly improve caching in GitRepository
⚠️ based on #3091, #3092, #3093, and #3095, so let merge those first
=> performance improvements

Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Motivation:
Git URLs don't always include `.git` suffix, but the logic for constructing GitHub API URL incorrectly requires it.
Modification:
Convert git URL to lowercase and remove `.git` suffix before pattern matching.
Result:
Git URLs with or without `.git` suffix are accepted.
=> Don't require .git suffix in repo URL

Sources/Basics/HTPClient+URLSession.swift, Sources/Basics/HTTPClient.swift
A couple of improvements to `HTTPClient` in support of the Swift package registry implementation (#3023). 
I want to use `URLProtocol` to test the HTTP client that interacts against a mock package registry server. However, it's not currently possible to access the underlying `URLSession` of an `HTTPClient` to configure the URL protocol. 
This PR introduces a `HTTPClientProtocol` protocol that provides the minimal amount of dependency injection necessary to make this work.
In addition, this PR conforms `HTTPClientHeaders` to be `ExpressibleByDictionaryLiteral` and reorganizes some declarations in `HTTPClient.swift`. These changes (8385b794c44b1cedde4d778c504ab4a65ef35087 and c5717b04167b6e27585c5ffe21ec009b5af032ab) are entirely severable, and you're welcome to ignore them. 
As a result of …
=> HTTPClient Enhancements

Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/InMemoryGitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
Rename the `tags()` functions of Repository and of WorkingCheckout to `getTags()`.  Until recently this was a property called `tags`, but now that it’s a function it makes more sense to call it `getTags()`.
This makes it more consistent with all the other functions, which have a verb at the start (including the `getCurrentRevision()` function), but more importantly this makes it easier for clients to adopt to the change (having a property change to a method without changing name makes it difficult for a type that adopts the protocol to conform to both).
Renamed the function in protocols and clients.
No change in functionality but more consistent naming and easier transition for clients.
=> Rename the `tags()` functions of Repository and of WorkingCheckout to `getTags()`

Fixtures/Miscellaneous/AtMainSupport/Package.swift, Fixtures/Miscellaneous/AtMainSupport/Sources/ClangExec/NotMain.c, Fixtures/Miscellaneous/AtMainSupport/Sources/SwiftExec/NotMain.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest/TargetDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageModel/Target.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/PackageGraphTests/TargetTests.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift, Tests/PackageLoadingTests/PDNextVersionLoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Implementation of support for `executableTarget` in the manifest.  This allows use of `@main` by having targets be explicitly declared as executable rather than by looking for particular file names.
One preliminary change compared with the evolution proposal is that, in order to make the upgrading from tools version 5.3 smoother, regular targets containing `main.swift` etc are still supported but cause a warning that the target declaration should be changed to `executableTarget` if the tools version is newer than 5.3.  This is a bit more clear than silently treating the target as a library once the tools version is upgraded.
See https://forums.swift.org/t/se-0294-declaring-executable-targets-in-package-manifests/42404
Implements the evolution proposal (including the warning mentioned …
=> Support for `executableTarget` in the manifest, to allow use of `@main` in package targets

Sources/PackageGraph/BoundVersion.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/PubgrubTests.swift
It looks like the pubgrub resolver did not actually keep the revision of branch-based dependencies around during resolution. I found this when testing individual `swift package update` when branch-based dependencies were involved, but there might be more cases where this lead to us updating the resolved file unconditionally. In particular, it seems as if the recorded revision was used to determine dependencies which could have potentially caused inconsistencies when not actually using that revision in practice.
- add an optional `branch` parameter to `BoundVersion` to represent a particular revision of a branch-based dependency
- use this to keep the revision from `pinsMap` in `PubgrubDependencyResolver` if needed
- adjusted expected result of `testBranchedBasedPin`, this was testing …
=> Keep revision from resolved file during resolution

Sources/Build/BuildPlan.swift, Sources/PackageLoading/Target+PkgConfig.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/Xcodeproj/pbxproj.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/PackageLoadingTests/PkgConfigTests.swift
_Parse pkgConfig (of .systemLibrary targets) in Swift Package Manager on all OS in the same way (in the way it is done on Ubuntu)_
_On Arch Linux derrivatives, pkgConfig is parsed differently; and it can cause segfaults of SPM on some cases. The main example is [SwiftGtk](https://github.com/rhx/SwiftGtk) which cannot be built on Arch Linux. It recognizes in SwiftGLib's [package.swift](https://github.com/rhx/SwiftGLib/blob/master/Package.swift) "glib-2.0 gio-unix-2.0" as two files on Ubuntu ("glib-2.0.pc" and "gio-unix-2.0.pc") where on Arch it recognizes it as "glib-2.0 gio-unix-2.0.pc", that does not exists and will lead to a Segmentation fault when calling realpath (there is no pc files with this name)._
_(Target+PkgConfig.swift) pkgConfigArgs now returns an array (since now, string is …
=> [PackageLoading] Fix inconsistent .systemLibrary's pkgBuild parsing

Sources/PackageGraph/LocalPackageContainer.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SPMTestSupport/MockPackageContainer.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
motivation: easier to reason about code
changes:
* rename PacakgeContainer::reversedVersions to PackageContainer::versionsDescending
* add PacakgeContainer::versionsAscending to avoid the versionsDescending().reveresed() code
* rename PacakgeContainer::versions(filter) to PackageContainer::toolsVersionsAppropriateVersionsDescending to better reflect the true meaning
* remove filter from PackageContainer::toolsVersionsAppropriateVersionsDescending since its not used in practice
* adjust tests and mocks
=> clarfiy reveresedVersions/versions in pubgrub

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/Pubgrub/Term.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/Workspace/Workspace.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
This reverts commit bfde016c44acc43c27eb3b7a0545a0662a181502.
We are seeing issues like "error: database is locked" when using SwiftPM with this commit, let's do a speculative revert.
See also https://ci.swift.org/job/oss-swift-pr-test/15882/consoleText
=> Revert "dependency resolution performance improvements (#3106)"

Fixtures/Miscellaneous/ExeTest/Package.swift, Fixtures/Miscellaneous/ExeTest/Sources/Exe/main.swift, Fixtures/Miscellaneous/ExeTest/Tests/ExeTests/ExeTests.swift, Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/WorkspaceTests/InitTests.swift
Improves the error messages that result from trying to import and link against executable targets.  This is an interim step while working on support for testing executable targets.
When a unit test (or another target) imports the module for an executable target, the error emitted is quite bad.  This is because the module for the executable target is actually emitted into a directory where the compiler finds it, but then the linking fails because the corresponding object files aren't passed to the linker (which is because of symbol name collisions — see below).  So the result is a linker error complaining about missing symbols, rather than at least a module import error and ideally a specific message about why the module isn't available.
Ideally, tests should be able to import executable …
=> Better error messages when trying to import executable targets

Sources/Build/BuildDelegate.swift, Sources/Build/BuildOperation.swift, Tests/FunctionalTests/MiscellaneousTests.swift
Improve the error message that's shown when a target tries to import an executable module.  This machinery can also be used for other kinds of errors in the future.  Currently only supports Swift targets that link against executables (either C or Swift).
This adds a check for the common case of a target trying to import an executable target, and provides an additional note to the error message.
Add a way for the BuildOperation to react to build command failures by looking at the build plan and providing more tailored output.
Better diagnostics when a target (typically a test) tries to link against an executable module.
=> Improve the error message that's shown when a target tries to import an executable module

IntegrationTests/Fixtures/XCBuild/ExecutableProducts/Bar/Sources/cbar/main.c, IntegrationTests/Fixtures/XCBuild/ExecutableProducts/Foo/Sources/cfoo/main.c, IntegrationTests/Package.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, IntegrationTests/Tests/IntegrationTests/Helpers.swift, IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift, IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift, Utilities/build-using-self
Try enabling the existing integration tests on the self-hosted bots.
Investigate expanding our test coverage. Follow up to #2592, where the groundwork was laid but we evidently didn't have the Xcode support we needed on Swift CI.
- Run the tests in `IntegrationTests` on our existing self-hosted CI bots.
- ~Remove `--enable-test-discovery`, since it's enabled by default now.~ Can't remove this quite yet, it appears.
- ~Temporarily enable three disabled tests, to see what happens on CI. Some/all of these will likely be disabled again before this is ready to merge.~ Failing tests have been disabled and need to be investigated separately.
=> Enable integration tests on self hosted CI

Sources/PackageDescription/Version.swift
Corrects a typo in the doc comments for the major version number in `PackageDescription.Version`
=> Fix doc comment typo in PackageDescription.Version

IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
Temporarily skipping failing integration test until it can be investigated.  This was newly added (#3088) but is failing.
This is blocking PR builds.
=> Temporarily skipping failing integration test until it can be investigated

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SourceControl/RepositoryManager.swift
motivation: prevent potential deadlocks
changes:
* dont wait on prefetch sync, notify instead.
* use memoize on prefteches to avoid races / redundant prefetches
* replace switch with tryMap to improve code readability
* rename ContainerProvider::provider to ContainerProvider::underlying to improve code readability
* add some code comments
=> improve concurrency safety of pubgrub prefetch

IntegrationTests/Tests/IntegrationTests/Helpers.swift, IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
Improve integration test failure messages, as the current text sometimes doesn't include enough information to diagnose the issue.
The integration tests were enabled in #3088 but [one started failing](https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/1257/console) soon thereafter with this uninformative message:
> 22:57:59 Test Case '-[IntegrationTests.XCBuildTests testTestProducts]' started.
> 22:57:59 
/Users/buildnode/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift:146: error: -[IntegrationTests.XCBuildTests testTestProducts] : XCTAssertEqual failed: ("terminated(code: 1)") is not equal to ("terminated(code: 0)")
> 22:57:59 …
=> Improve integration test failure messages

Sources/SourceControl/RepositoryManager.swift
Ignore lock files when purging cache.
I found a small bug where `swift package purge-cache` would try to delete the lock files inside the cache. When deleting the lock files a lock for the lock file would be acquired creating a new lock file with the same name but ".lock" appended.
Don't delete files/directories with a suffix of ".lock"
Lock files will stay intact and no new lock files will be created.
=> Ignore lock files when purging cache

Tests/SourceControlTests/RepositoryManagerTests.swift
Temporarily disable a test that is crashing only in CI, but leave an environment variable to reenable it for testing.  The crash is being investigated.
=> Temporarily disable a test that is crashing only in CI

Sources/Basics/ConcurrencyHelpers.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift
motivation: manifest loading concurrency tests sometime crash when they blow the threads limits in dispatch
changes:
* centralize max operation into a helper
* use the max concurrent operations limit for both manifest loading and repository lookup
=> reduce the max concurrent operation performed when loading manifests

Documentation/PackageDescription.md, Sources/PackageDescription/Target.swift, Sources/PackageLoading/PackageBuilder.swift
Enable explicitly declared executable targets by default, now that SE-0294 has been accepted, and adjust the PackageDescription documentation.
=> Enable explicitly declared executable targets by default, now that SE-0294 has been accepted

Sources/Commands/SwiftPackageTool.swift
motivation: `swift package udpate` succeeds today even if the graph is broken (e.g. cyclic dependency), which only surfaces when running `swift build` or other operations that load the graph
chnages: load the graph and emit any errors after update is run
=> load the graph after `swift package update` to show any errors

Sources/Commands/SwiftTool.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift
motivation: current symblink is ~/.switpm/cache -> idiomatic-cache-location/repositories, this creates an issue for other types of caches
changes:
* refactor how cache directory is computed and defaults are created on disk, and move it to SwiftTool so it can be used across RepositoryManager and other parts of the code that need caches
* change the symlink of ~/.swift/cache to point to the top level cache not the repositories subdirectory
* adjust test
note: if you used the shared cache feature before you should delete ~/.swiftpm/cache since its pointing to the wrong place
=> improved shared repositories cache location

Tests/SourceControlTests/RepositoryManagerTests.swift
Modify skip condition for SourceControlTests.RepositoryManagerTests.testCache() to only skip on macOS < 11
This allows the test to run in environments that aren't affected by the underlying bug.
Changed the condition under which XCTSkip() is called.
rdar://72092379
=> Modify skip condition for SourceControlTests.RepositoryManagerTests.testCache() to only skip on macOS < 11

Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan.swift, Sources/Build/ManifestBuilder.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/Xcodeproj/pbxproj.swift
motivation: less crashes, happier users
changes: replace a few more cases of using fatalError with throwing an InternalError which asserts in development mode
=> replace more usage of fatalError with throwing an error

Fixtures/Miscellaneous/TargetMismatch/Package.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/FunctionalTests/MiscellaneousTests.swift
motivation: generation of implicit products ignores explicit products and can lead to incorrect and confusing warnings
changes:
* reorder product generation such that first explicit products are added, then implicit ones
* do not generate implicit executable product when a product with such name already exists
* warn when a non-executable product exists for an executable target
* add test
fixes rdar://71268198
=> improve correctness of implicit executable target generation

Sources/Basics/ConcurrencyHelpers.swift, Sources/Basics/Errors.swift, Sources/Basics/HTTPClient.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTestTool.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageGraph/LocalPackageContainer.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/SPMTestSupport/MockManifestLoader.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: better performance for dependency resolution
changes:
* make the loadManifest function asynchronous
* move the operation queue into ManifestLoader instead of Workspace
* load root manifest asynchronous
* adjust test
* replace some queue.wait with queue.notify
* tested with TSAN
=> manifest loading performance improvements

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageCollections/JSONModel/JSONCollection+v1.swift, Sources/PackageCollections/PackageCollections+Validation.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/BasicsTests/ConcurrencyHelpersTests.swift
motivation: a failing test hinted to a thread safety issue, which was then diagnosed to an incorrect lock on an array. this prompted creating a thread safe utility for array to avoid such cases
changes:
* create a thread-safe utlitiy for array
* replace array + lock with the new utility
* add test
=> fix thread safety issue in package collections

Sources/Workspace/Workspace.swift
> using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead
=> Fix compiler warning

Sources/PackageLoading/ManifestLoader.swift
motivation: caching manifests that fail to parse makes development of swift-pm harder, and is not meaningful from a perfoamnce pov
changes: only cache manifests if they have no parse errors
=> only cache successfully parsed manifets

Sources/Commands/Describe.swift, Tests/CommandsTests/PackageToolTests.swift
Don't include test products in the `product_memberships` key of the `describe` command.  Also fix a problem where not all products were included.
This key is new in 5.4 (so there's no backward compatibility to maintain), and it's confusing that test products are included since they're not really considered products from a user point of view.
Exclude test products from the `product_memberships` array.
Fix a bug that caused some products to be excluded from the array.
=> Don't include test products in the `product_memberships` key of the `describe` command

Sources/Build/SwiftCompilerOutputParser.swift, Sources/SourceControl/RepositoryManager.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XCBuildOutputParser.swift, Sources/Xcodeproj/XcodeProjectModelSerialization.swift
> using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead
=> Fix compiler warnings

Sources/Workspace/Workspace.swift
Call atrifacts download delegate final method only if we ever try to download an artifact.
`WorkspaceDelegate.didDownloadBinaryArtifacts` is called despite there's nothing to download, nor we even tried to download anything. Given the name "did download" it should be called only if there was a download (attempt).
Check with flag whether any download happened.
=> Call artifacts download delegate final method

Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift
Make the `Workspace.delegate` property weak optional. It doesn't have to be captured with strong reference (It's unlike for delegate pattern to retain)
Initialize the `Workspace.delegate` separately at any point. Ref: https://bugs.swift.org/browse/SR-4402
`Workspace.delegate` is weak property now. That means if any code relies on the retain, need update.
=> Workspace delegate weak property

Sources/Workspace/Workspace.swift
Add optional delegate parameter to `Workspace.create()`
`Workspace.create` is a convenient way to instantiate a `Workspace` instance. However can't use it if want to use `WorkspaceDelegate` - that is unfortunate. `Workspace.delegate` is a `let` property, hence it can't be set after initialization.
Add optional delegate perameter to Workspace.create()
Ref https://bugs.swift.org/browse/SR-4402
=> Add optional delegate perameter to Workspace.create()

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/SPMTestSupport/MockManifestLoader.swift, Sources/Workspace/Workspace.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
motivation: manifest cache improves performance by caching a parsable version of the menifest, making the cache global improve performance across different build which use similar dependencies
changes:
* change the default manifest cache location from local .build to shared SwifPM cache directory
* change purgeCache to include manifest cache, instead of workspace reset
=> performance: shared manifests cache

Sources/Commands/SwiftTool.swift
motivation: better reseliency
changes: catch file system errors when trying to create default cache locations and warn + disable cache instead of failing
follow up / replacement for https://github.com/apple/swift-package-manager/pull/3142
=> make code more resilient when cache directories cannot be created 

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageLoading/ManifestLoader.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
motivation: more stable tests
changes:
* add a test variant with warmed up caches
* modify test to load 250 different manifests instead of the same one to create concurrent load on the parser
* add file-system lock around sqlite db state (ie when creating/closing it)
* change default concurrency to number of available CPUs
* make manifest cache failures non-fatal, emit warnings and continue
=> improve manifest loader concurrency and tests

Sources/Workspace/Workspace.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/XcodeprojTests/PackageGraphTests.swift
Some are replaced with 2 spaces, some 4. Now all lines in `Sources/` and `Tests/` are indented by multiples of 4 spaces.
=> [Gardening] replace horizontal tabs with correct number of spaces for indentation

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift
motivation: clearer flags, happier users
changes:
* deprecate global "skip-cache" flag
* introduce "--disable-repositories-cache" flag for disabling repositories cache
* update flag help
* adjust call-site
=> rename flags for repositories cache

Package.swift
Fixes non-CI builds of SPM 5.3
=> [5.3] The llbuild dependency should reference the 5.3 release branch

Package.swift
Same as #3145.
`swift-driver` doesn't follow same tagging conventions so not included.
=> Unify dependencies branch name for non-CI builds

Sources/Build/BuildOperation.swift, Sources/Commands/APIDigester.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftRunTool.swift, Sources/Commands/SwiftTool.swift, Tests/BuildTests/IncrementalBuildTests.swift
motivation: improve performance
changes:
* set the flag to true by default
* refactor the code to better reflect true meaning of flag
* warn on any error and fallback to non-cached version
* add test for disabling the cache
rdar://63981763
=> enable build manifest caching by default

Sources/PackageGraph/DependencyResolutionNode.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Manifest/PackageDependencyDescription.swift
Early in the 5.4 development process, we merged #2749 to bring a full implementation of target-based dependency resolution, but we disabled that later because of regressions with some real-world packages. The plan was to bring this back for the final 5.4, but after some discussion in #3121, we have identified a few issues without a clear fix that doesn't carry significant risk this late in the release cycle.
However, the current state is also not acceptable for the 5.4 release, since this regresses dependency resolution back to the state before #2424 which could break real world packages.
This PR brings back the 5.3 behavior of taking only into account targets that are required by any products and omitting any dependencies that aren't required by any products. We can then revisit …
=> Reinstate 5.3 behavior of target-based dependency resolution

Sources/Basics/ByteString+Extensions.swift, Sources/Basics/CMakeLists.txt, Sources/PackageLoading/ManifestLoader.swift, Sources/SourceControl/Repository.swift, Sources/Workspace/Workspace.swift, Sources/XCBuildSupport/PIF.swift, Tests/BasicsTests/ByteStringExtensionsTests.swift
Improves performance and convenience of SHA256 checksum generation.
While working on #3023, dependency resolution with package registries was significantly slower than I expected. After a bit of profiling, I determined that a call to `SHA256().hash` for the downloaded Zip archive of each package release was responsible for the slowdown. Switching to the CryptoKit implementation of SHA256 created improved end-to-end performance from 70s to 15s. (See https://github.com/apple/swift-package-manager/pull/3023#issuecomment-743482235)
This PR starts by creating a `sha256Checksum` property in an extension on `ByteString` that provides a lowercase hexadecimal representation of the SHA256 hash, using CryptoKit when available (0bd6a548cd8ab944ca2a76dbaf7b6f6c5a723022).
Next, it refactors existing …
=> Refactor generation of SHA256 checksums

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: there are several use cases where identity collisions cause resolution errors with misleading diagnostics. We added several test cases to capture these cases, as a basis for improving identity collisions (some of them are legitimate use cases) or at the minimum by finding ways to emit more helpful / accurate diagnostics.
changes:
* add several test cases to capture use cases of identity collisions
* diagnose potential identity collisions and emit more actioable error messages
* add FIXME highlighting where some of the issues are coming from
=> identity collisions diagnostics test and fixes

Sources/PackageModel/Product.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: existing logic deduped manifests avaialbe for graph resolution based on the mainfest name. this is causing issues when a repository is renamed and both the old and new URL are in the graph (as in the case of SR-11338), since the graph can never get resolved with one of the required manifests missing
changes:
* change the logic to dedup based on the identity instead of name. this means we are deduping by URLs instead of manifest names which is more consistent with the way the rest of the code base works and more helpful in most case/
* move the lgoic to identify incorrect overrides to the resolve function instead of being based on the fact a manifest is missing (which is a side effect)
* added some code comments to explain what the code does
* a bit of formatting/gardening in …
=> change manifest loading deduping logic to be based on identity instead of manifest name

Package.swift
motivation: swift-pm and swift-drivers are version locked
changes: adjust the dependency declaration of swift-driver to use the "relatedDependenciesBranch" variable
=> adjust swift-driver branch to use the version-lock variable

CHANGELOG.md, Sources/PackageLoading/ToolsVersionLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
The changes to how tools version comments are parsed introduced a subtle regression, causing packages that have a `Package@swift-3.swift` manifest to fail with an error about the missing tools version, even if the regular manifest is newer.  As described in https://swift.org/blog/swift-package-manager-manifest-api-redesign, packages without a tools version comment should be assumed to have version 3.1.
This fixes a regression introduced in 5.4, as described above.
Check for a version-specific tools version less than v4 and consider it to be v3.1.0 (i.e. the documented behavior).
rdar://72939860
=> SwiftPM still support v3 manifests in dependencies but then it complains that they have no tools version comment

CHANGELOG.md, Sources/PackageLoading/ToolsVersionLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
This is the SwiftPM 5.4 nomination of a bug fix in the handling of version-specific manifests that have a manifest version earlier than 4.  Such old versions are no longer supported for any root package, but are still supported as version specific manifest overrides for dependencies.
The original PR is https://github.com/apple/swift-package-manager/pull/3172, which has reviews and more details.
=> [5.4] SwiftPM complains about missing tools version comments in SwiftPM v3 version-specific manifest overrides

Sources/PackageModel/Product.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
same as #3165, needs #3179 to be merged first
=> [5.4] change manifest loading deduping logic to be based on identity instead of manifest name

Sources/PackageModel/Manifest.swift, Tests/WorkspaceTests/WorkspaceTests.swift
This is a follow-up to #3162. While that brought back the code for `dependenciesRequired(for:)`, the guard based on `productFilter` actually made it so that it was practically never executed. Instead, the guard should be based on whether the package in question is a root package.
Additionally, this made the order of the returned dependencies unstable, due to use of `Set`. Since `dependenciesRequired(for: keepUnused:)` is now only used if `ENABLE_TARGET_BASED_DEPENDENCY_RESOLUTION` is set, I removed some dead code from there as well.
=> Actually skip not needed dependencies during dependency resolution

Sources/Commands/SwiftPackageTool.swift, Sources/SourceControl/GitRepository.swift, Tests/CommandsTests/PackageToolTests.swift
```
OVERVIEW: Create a source archive for the package
USAGE: swift package archive <options>
OPTIONS:
-o, --output <output>   The absolute or relative path for the generated source archive 
```
The Package Registry Service proposal ([SE-0292](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md)) describes a new [`swift package archive` subcommand](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md#archive-subcommand). This tool provides an authoritative method for generating source archives for package releases, which is important for generating and validating integrity checksums.
The `swift package` command will have a new `archive` subcommand.
> **Note**: This feature is orthogonal to the package …
=> Add swift package archive-source subcommand

Fixtures/Collections/GitHub/license.json, Fixtures/Collections/JSON/good.json, Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/JSONModel/JSONCollection+v1.swift, Sources/PackageCollections/Model/License.swift, Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Updating package collection models based on [feedback](https://forums.swift.org/t/package-collection-format/42071).
- Add new computed properties `latestReleaseVersion` and `latestPrereleaseVersion` to `Package.Version`; convert existing `latestVersion` to be a computed property. (https://github.com/apple/swift-package-manager/commit/b7de686f26b85953514fcf6ca11d2e1086c70369)
- Add optional `license` to `Package` so that it can hold _current_ license info. Currently only `Package.Version` has `license` and that's only suitable for snapshot data. (https://github.com/apple/swift-package-manager/commit/c7c2b453988453eb8d3778879b6a600f84bd49bc)
- It might not always be possible to determine license name. Instead of forcing people to use values such as `"unknown"`, `""` for `license.name`, it …
=> Updates to package collection models

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift, Tests/PackageCollectionsTests/ValidationMessageTests.swift
Motivation:
Some package collections fail to get imported because download response doesn't contain the `Content-Length` header.
Modifications:
The response headers for failed requests contain `Transfer-Encoding` header. If the request includes `Accept-Encoding` header then there will be `Content-Type` header in the response and no `Transfer-Encoding`.
Result:
Can import collections hosted as gists.
=> Collections hosted as GitHub gist sometimes fail with missing 'Content-Length' header

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest/TargetDescription.swift, Sources/SPMTestSupport/MockPackage.swift, Sources/SPMTestSupport/MockTarget.swift, Sources/SPMTestSupport/MockWorkspace.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift, Tests/PackageModelTests/ManifestTests.swift
This converts various `preconditions` in `TargetDescription` into errors, since these can actually be hit by users writing manifests in disallowed ways.
I think ideally we would find to change the manifest API so that getting into these kind of illegal states wouldn't even be possible, but at least this turns them into runtime errors instead of crashes.
rdar://70682458
=> Convert preconditions for `TargetDescription` into errors

Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/PackageCollections+Validation.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Motivation:
Try passing a local FS path (file:///foo/bar) to the command `swift-package-collection describe`. It fails with `Error: invalidResponse`. This is because we try to fetch local file with HTTP client.
Modications:
If a collection URL points to local FS path, read the file contents instead of downloading it via HTTP GET.
Also improve error messages.
Result:
Local package collections can be imported.
=> Cannot import local package collections

Sources/PackageDescription/LanguageStandardSettings.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/ToolsVersion.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Before releasing SwiftPM 5.4, the PackageDescription API should be updated so that specifying 5.4 allows use of the new APIs in 5.4.
Replace references to 999.0 (the placeholder for "next release") with 5.4.
This is in addition to the changes being made in https://github.com/apple/swift-package-manager/pull/3173 for tools-version-loader specific version numbers.
rdar://73203278
=> Change 999.0 to 5.4 in PackageDescription and related tests

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest/TargetDescription.swift, Sources/SPMTestSupport/MockPackage.swift, Sources/SPMTestSupport/MockTarget.swift, Sources/SPMTestSupport/MockWorkspace.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD5_3LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift, Tests/PackageModelTests/ManifestTests.swift
=> [5.4] Convert preconditions for `TargetDescription` into errors

Sources/PackageModel/Manifest.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> [5.4] Actually skip not needed dependencies during dependency resolution

Sources/Commands/SwiftPackageCollectionsTool.swift
The `describe` command for a package version was printing modules, but not products.
=> Add products to package collections CLI

Tests/CommandsTests/PackageToolTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
This caused warnings, and then the tests failed because there were diagnostics.
This was caused by the ToolsSupportCore change to increment the current SwiftPM version to be 5.4.  What is odd is that the PR tests succeed, and they were supposed to have done a full test, including SwiftPM.
=> Fix package tool unit tests that assumed that .currentVersion meant .v5_3

Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
To address unit test failures caused by incorrect assumptions about `.currentToolsVersion` being the same as `.v5_3`, several uses of `.currentToolsVersion` were converted to `.v5_3` in https://github.com/apple/swift-package-manager/pull/3196.  This included some that, based on later conversation in https://github.com/apple/swift-package-manager/pull/3197 should not have been converted.  This restores them so that package-collection-related tests continue using `.currentToolsVersion`.
This aligns `main` with what's being nominated for `release/5.4` and undoes some overzealous conversion of `.currentToolsVersion` to `.v5_3`.  No other change than unit tests.
=> Convert some uses of `.v5_3` in unit tests back to `.currentToolsVersion` based on feedback

Fixtures/Miscellaneous/AtMainSupport/Package.swift, Sources/PackageDescription/LanguageStandardSettings.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/ToolsVersion.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
This is the 5.4 cherry-pick of https://github.com/apple/swift-package-manager/pull/3193, which is a mechanical change of the placeholder "999.0" for features in future releases to be "5.4" in the release branch.
This is in addition to the similar PR https://github.com/apple/swift-package-manager/pull/3170 for tools-version-loader specific changes.
This depends on https://github.com/apple/swift-tools-support-core/pull/183 in order for SwiftPM to accept packages that have tools version 5.4.
rdar://73203278
=> [5.4] Change 999.0 to 5.4 in package description and related tests

Tests/CommandsTests/PackageToolTests.swift
A few of the unit tests in SwiftPM use `.currentToolsVersion` instead of `.v5_3` and unintentionally relied on SwiftPM 5.3 semantics.  This causes warnings now that SwiftPM is 5.4 (though they don't seem to affect all integration builds — it's not yet clear why not).  The correct thing to do semantically is for them to use `.v5_3` as the tools version if they rely on 5.3 semantics.
This is the 5.4 cherry-pick of https://github.com/apple/swift-package-manager/pull/3196.
rdar://73253889
=> [5.4] Fix incorrect use of current tools version in unit tests that assume 5.3 semantics

Package.swift
The Package.swift on the `release/5.4` branch should use that branch for the dependencies also.  We might need to first open related PRs for adjustment of the `release/5.4` branches of those dependencies, as it seems that some haven’t yet been updated.
rdar://73202559
=> [5.4] Adjust dependencies on 5.4 branch to `release/5.4`

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
motivation: sqlite manifest cache is now shared by default, controlling its max size is important
changes:
* introduce SQLiteManifestCache::Configuraiton allowing to set max database size, and set it to 100MB
* when database is full, truncate it. this is not refined, but since this is a cache it should be fine.
* add tests including a couple of other tests for SQLiteManifestCache that were missing
=> limit size of sqlite manifest cache

Fixtures/Miscellaneous/AtMainSupport/Package.swift
... and not 999.0.  This has already been done on the `release/5.4` branch.
=> Fix the tools version in the @main fixture manifest to be 5.4

Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
This was just causing noise.  Now any failure messages include both the original and rewritten contents of the manifest.
=> Remove an unconditional print statements in a test

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
=> [5.4] limit size of sqlite manifest cache (#3178)

Sources/PackageDescription/Target.swift
Edit documentation to fit to the way swift parses pkgConfig files.
In #3080 I did make changes on how SPM parses pkgConfig to make it consistent. This PR is made to reflect these changes in the documentation
I added "for each pkg-config file separated by space"
The documentation will be closer to the reality
PS: Do not hesitate to edit this PR to make the text better.
=> [PkgConfig] Update PkgConfig documentation

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageCollections/CMakeLists.txt, Sources/PackageCollections/Model/TargetListResult.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageCollections/Storage/Trie.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift, Tests/PackageCollectionsTests/TrieTests.swift
This is an alternative to https://github.com/apple/swift-package-manager/pull/3090 but is a complete solution.
Motivation:
Currently to support search for package collections API we read and deserialize collection blobs from SQLite then perform string matchings on individual properties in memory (e.g., `package.summary.contains("foobar")`). This can be optimized.
Modifications:
Use SQLite FTS--define FTS virtual tables for packages and targets, and update implementation for `findPackage`, `searchPackages`, and `searchTargets` methods of `SQLitePackageCollectionsStorage`.
Without optimization, `PackageCollectionsTests.testPackageSearchPerformance` and `testTargetsSearchPerformance` take about ~400ms to run on my local machine.
With FTS, `testPackageSearchPerformance` takes ~40ms and …
=> Package collections: improve search performance

Documentation/ContinousIntegration.md, Documentation/README.md
Add documentation for Packages in CI
Developers might be interested on adding building Swift Packages in Continuous Integration workflows
- Added Documentation/ContinousIntegration.md
- Added link to ContinousIntegration.md in Documentation/README.md
- New file Documentation/ContinousIntegration.md
- New link to  Documentation/ContinousIntegration.md in Documentation/README.md
=> <rdar://65206398> Add documentation for Packages in CI

CONTRIBUTING.md
motivation: make contribution guide link to the specific SwiftPM guidelines instead of the generic Swift one
=> update link to SwiftPM contribution guide

Sources/PackageLoading/ToolsVersionLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Fix a tools version loading failure that occurred when the regular manifest doesn't contain a tools-version.
Usually the main manifest is the latest, but there are examples of packages where it's the opposite:  the main version is the old one, and newer ones have version suffixes.  In rare cases the main manifest is so old that it doesn't have a tools version, and the new logic for tools version loading incorrectly reported an error in those cases.
rdar://73267827
=> Fix a tools version loading failure that occurred when the regular manifest doesn't contain a tools-version

Sources/PackageLoading/ToolsVersionLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Usually the main manifest is the latest, but there are examples of packages where it's the opposite:  the main version is the old one, and newer ones have version suffixes.  In rare cases the main manifest is so old that it doesn't have a tools version, and the new logic for tools version loading incorrectly reported an error in those cases.
rdar://73267827
(cherry picked from commit a27bbb53f8f32af9e1d8d15b569f63e3dbabffa4)
This was committed to the `main` branch as https://github.com/apple/swift-package-manager/pull/3208.
=> [5.4] Fix a tools version loading failure that occurred when the regular manifest doesn't contain a tools-version.

CHANGELOG.md, Sources/PackageLoading/ToolsVersionLoader.swift, Sources/PackageModel/ToolsVersion.swift, Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift
#2937 used "Next" and `ToolsVersion.vNext` because at that point it was unconfirmed what the next version of Swift was. Now that the 5.4 branch is cut, I corrected all the references to Swift Next to Swift 5.4, according to rules I wrote in the comments in the previous PR.
**EDIT**: By "all the references to Swift Next", I mean all those introduced in #2937. There are other "Next" and `.vNext` not changed by this PR.
=> [5.4][PackageLoading] replace "Next" with "5.4" according to notes left previously

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
When invoking the Swift compiler, SwiftPM was passing search paths to C headers as "-I" arguments.  But it wasn't prefixing them with "-Xcc" so they were being interpreted by the Swift driver and not Clang.  This meant that they weren't recorded as serialized import paths in the AST.  It isn't fully clear why they are needed when building the module in response to the debugger or REPL but not when building using the compiler, but it is clear that these are C header search paths and not Swift module search paths, so they should indeed be passed using "-Xcc" prefixes.
rdar://58709835
=> SR-12050: lldb error: could not build C module 'CNIOBoringSSLShims' (Linux 5.1.3) when debugging

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SourceControl/GitRepository.swift
motivation: in 5.4 we introduced a timeout on computing packages bounds to help mitigate scenarios where the resolution would hang. using a fixed timeout prooves to be incorrect since the time it takes to compute the bounds is a direct function of the number of version the repository has. as such, repositories with very large number of tags (2000+) would hit the timeout
changes: make the timeout a function of the # of versions
rdar://73470011
=> resolve timeout for repositories with large number of tags

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SourceControl/GitRepository.swift
motivation: in 5.4 we introduced a timeout on computing packages bounds to help mitigate scenarios where the resolution would hang. using a fixed timeout prooves to be incorrect since the time it takes to compute the bounds is a direct function of the number of version the repository has. as such, repositories with very large nuymber of tags (2000+) would hit the timeout
changes: make the timeout a function of the # of versions
rdar://73470011
=> [5.4] resolve timeout for repositories with large number of tags (#3218)

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
This is the 5.4 release nomination of https://github.com/apple/swift-package-manager/pull/3215.
When invoking the Swift compiler, SwiftPM was passing search paths to C headers as "-I" arguments. But it wasn't prefixing them with "-Xcc" so they were being interpreted by the Swift driver and not Clang. This meant that they weren't recorded as serialized import paths in the AST. It isn't fully clear why they are needed when building the module in response to the debugger or REPL but not when building using the compiler, but it is clear that these are C header search paths and not Swift module search paths, so they should indeed be passed using "-Xcc" prefixes.
This PR depends on https://github.com/apple/sourcekit-lsp/pull/363 in SourceKit-LSP, since unit tests in that package make assertions …
=> [5.4] SR-12050: lldb error: could not build C module 'CNIOBoringSSLShims' (Linux 5.1.3) when debugging

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Fix an internal that would occur when switching a dependency between two repositories that had the same last path component and identical package manifest contents (happens frequently with forks).  This was due to the in-memory manifest cache, and thus only seen in libSwiftPM clients and not in the CLI.
rdar://73462555
Need to figure out a good way to unit test this without actually accessing network.
=> Fix an internal error resulting from reusing a stale in-memory cached manifest when switching dependencies between forks

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Fix an internal error that would occur when switching a dependency between two repositories that had the same last path component and identical package manifest contents (happens frequently with forks).  The specific problem was that the old URL was part of the cached in-memory manifest, but was not serialized to the database and therefore not part of the manifest key.  There are other properties of Manifest that are also in addition to those stored in the database cache.  Since measurements don't indicate a noticeable performance impact and we don't know all the properties that could cause this, the cache is removed, at least for now.  If restored, it should store only the properties that actually come from the manifest (not the URL).
This was due to the in-memory manifest cache, and …
=> [5.4] Remove the in-memory manifest cache to fix an internal error caused by stale cache data

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/PackageCollectionsSourcesStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsSourcesStorageTest.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
Package collections may optionally be signed in the future ([forum post](https://forums.swift.org/t/package-collection-signing/43855)). Unsigned collections will require some changes to the UX (e.g., user needs to confirm their trust on unsigned collections), therefore the Package Collection APIs will need to be updated accordingly.
Modifications:
- Each package collection "source" in the config has a new `isTrusted` flag to record user's trust preference.
- `addCollection` has a new `trustConfirmationProvider` closure that gets invoked when the newly added collection is unsigend. API client needs to provide user's trust preference when the closure is invoked.
- New `updateCollection` API to update a collection's trust preference. This is for one-off config changes.
- New …
=> [Collections] API changes to support signed collections

Sources/PackageCollectionsModel/CMakeLists.txt
PackageCollectionsModel has grown a dependency on Foundation, explicitly
list it in the build.
=> PackageCollectionsModel: correct dependency (NFC)

Sources/SourceControl/RepositoryManager.swift
It is possible that copying from the cache fails mid-way which can lead to SwiftPM hitting a precondition in the fallback.
We should clear any potential leftover data before doing the fallback.
Hitting the precondition can be avoided.
rdar://73505115
=> Fix potential crash in repository cache fallback

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
Using the `package-collection` CLI, the `remove` command results in "database is locked" error even though the collection is removed successfully. This is because a `SQLitePackageCollectionsStorage` is created at the beginning of each command run, and in the initializer the time-consuming `populateTargetTrie` is called. When the command finishes running, it triggers `SQLitePackageCollectionsStorage` to be closed, which in turn closes the SQLite connection, but this is done while `populateTargetTrie` is still running and thus causes the "database is locked" error.
Modifications:
- Initializing `PackageCollections` can be expensive and should only be done once in a command
- Add and set `isShuttingDown` flag when `SQLitePackageCollectionsStorage.close` is called so …
=> [Collections] CLI 'remove' results in "database is locked" error

Sources/SourceControl/RepositoryManager.swift
5.4 cherry-pick of https://github.com/apple/swift-package-manager/pull/3221, plus the change from https://github.com/apple/swift-tools-support-core/pull/186 inlined here to decrease the surface area of that change.
=> [5.4] Fix potential crash in repository cache fallback

Documentation/PackageDescription.md
Making the documentation easier to read.
I fixed the formatting of two functions in the text.
It now looks good :)
=> Fix formatting in PackageDescription.md

Sources/PackageDescription/PackageDescription.swift
Symbols from `Glibc`/`Darwin`/`ucrt` are not used in the public interface of `PackageDescription`, so there is no need to expose them in the generated module interface.
This change hides the import statements from the generated `PackageDescription` module interface.
It relies on https://github.com/apple/swift/pull/35575 (already merged).
After this change SourceKit returns a `PackageDescription` interface without `import Darwin.C`/`import Glibc`/`import ucrt`.
=> PackageDescription: mark imports as implementation-only

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageCollections/PackageCollections.swift
motivation: CI crashes in PackageCollectsTest::testBrokenRefresh suggest a race condition in the code
changes:
* change ThreadSafeArrayStore::apend to return the current count in a thread safe manner
* update the callsite to use the count returned from append instead of after the append -- which could be racy
rdar://73884751
=> fix potential race in PackageCollections.refreshCollections

Fixtures/Collections/JSON/good_signed.json, Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift, Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
- Introduce new `SignedCollection` as
[proposed](https://forums.swift.org/t/package-collection-signing/43855).
- Update logic in `JSONPackageCollectionProvider` to check for signature
- Adjust tests
=> [Collections] Add and wire up models for signed package collections

CMakeLists.txt, Documentation/Contributing.md, Package.swift, Sources/PackageCollections/CMakeLists.txt, Sources/PackageCollections/Signing/PackageCollectionSignature.swift, Utilities/bootstrap
Motivation:
Upcoming package collections feature will require swift-crypto dependency.
Modifications:
- Add swift-crypto dependency
- Bump minimum macOS version to 10.15, for it's required by swift-crypto
=> Add swift-crypto dependency

Sources/Build/ManifestBuilder.swift, Tests/BuildTests/BuildPlanTests.swift
Instead of accumulating individual dependency graphs from target-specific Driver invocations, use a reference-type `InterModuleDependencyOracle` introduced in: https://github.com/apple/swift-driver/pull/356.
=> [Explicit Moduel Builds] Adapt to swift-driver's InterModuleDependencyOracle API for cross-target dependency tracking

Sources/Basics/JSON+Extensions.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift
motivation: cleanup
changes:
* remove check for < macOS 15 which is now the min target
* remove code deprecated in or before 5.4
=> remove deprecated code

Sources/Commands/Describe.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageGraph/PackageModel+Extensions.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Manifest/PackageDependencyDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/SPMTestSupport/MockDependency.swift, Sources/Workspace/Workspace.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD4LoadingTests.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Tests/PackageLoadingTests/PD5LoadingTests.swift, Tests/PackageLoadingTests/PD5_2LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageModelTests/ManifestTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift, Tests/XcodeprojTests/PackageGraphTests.swift
motivation: improve code infrastrucuture towards fixing correctness issues with identity
changes:
* rename PackageDependencyDescription::url to PackageDependencyDescription::location to reflect its true meaning
* rename PackageDependencyDescription::name to PackageDependencyDescription::nameForTargetDependencyResolutionOnly to make sure its not used for wrong reasons
* move "file://" prefix handing from PackageDependencyDescription::init to PackageDependencyDescription::init(json) which where all the other location validation is done
* addjsut call-sites
* adjust and add tests
=> refactor PackageDependencyDescription towards identity changes

Utilities/bootstrap
Make `swift-package-collection` available in downloadable toolchains.
=> Install `swift-package-collection` in the toolchain

Sources/XCBuildSupport/PIFBuilder.swift
We were passing this unconditionally which would break in the case where we weren't generated a module map because an explicit one exists.
rdar://74115399
=> Fix `-fmodule-map-file` pointing to non-existent path

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
This got broken in #3209 which was using `llbuildSwift` unconditionally. This is easy to miss, but in some environments we set `SWIFTPM_LLBUILD_FWK` and link against a pre-built framework which will only have the module `llbuild`.
We should improve the testing here and build in both modes to avoid this kind of breakage in the future.
=> Fix `BuildOperationBuildSystemDelegateHandler`

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
motivation: include the name of the target in the warning so its more actionable
changes: add the target name in the "use executableTarget in 5.4" warning
=> improve error message for deduced executableTarget

Sources/Basics/ConcurrencyHelpers.swift, Sources/Basics/HTPClient+URLSession.swift, Sources/Basics/HTTPClient.swift, Sources/Basics/SwiftVersion.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
motivation: prepare to consolidate downloader from TSC and http client from Basics
changes:
* add progress support to "execute"
* add authorization support to HTTPClientRequest::Options and HTTPClient::Configuration
* refactor call-sites to use new ways
* add and adopt tests
=> refactor http client

Sources/Build/SPMSwiftDriverExecutor.swift, Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift, Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
Currently we only include common name, but we have all the other information available and there is no reason not to show them.
Modification:
Add user ID, organizational unit, and organization to `Certificate.Name`.
=> [Collections] Add more info to certificate subject and issuer in signature

Sources/Workspace/Workspace.swift
Looks like `Diagnostics.fatalError` is used to throw errors when appropriate diagnostics have already been emitted and the only goal is to quickly return to the caller.  This is documented in TSCUtility.
Future cleanup should avoid this special behavior.
This prevents an ugly extra line of output
It prevents `Diagnostics.fatalError` from being added to the diagnostics engine, in a way that's similar to how it is done in some other places.
rdar://74263826
=> [5.4] Prevent manifest load errors from causing SwiftPM to display "fatalError" in CLI

Sources/Workspace/Workspace.swift
This is the `main` thread cherry-pick of https://github.com/apple/swift-package-manager/pull/3261
Looks like `Diagnostics.fatalError` is used to throw errors when appropriate diagnostics have already been emitted and the only goal is to quickly return to the caller.  This is documented in TSCUtility.
Future cleanup should avoid this special behavior.
This prevents an ugly extra line of output
It prevents `Diagnostics.fatalError` from being added to the diagnostics engine, in a way that's similar to how it is done in some other places.
rdar://74263826
=> Prevent manifest load errors from causing SwiftPM to display "fatalError" in CLI

Sources/PackageLoading/TargetSourcesBuilder.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Introduce a warning that is not currently present, informing the user of paths that they have added to their manifest file that do not exist.
This also includes a warning when trying to use a resource that is located outside the root of the package.
rdar://60745311
rdar://60708059
=> Emit warning when a path is marked for exclude:, resources: but does not actually exist.

Sources/Commands/SwiftPackageTool.swift
motivation: fix a bug where in some cases a duplicate error message is printed
changes: only try to load the graph if the previous operation succeeded
=> [5.4] Duplicate error message on package resolve

Fixtures/Collections/JSON/good.json, Fixtures/Collections/JSON/good_signed.json, Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollectionsModel/Formats/v1.md, Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift, Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
It seems useful for package version to have a description and creation timestamp.
Modifications:
- Add `summary` and `createdAt` to the models
- Update collection format doc
=> [Collections] Add summary and creation timestamp to package version

Sources/Build/SPMSwiftDriverExecutor.swift
It would be beneficial for us to stay compatible with the 5.3 branch of swift-driver for the time being, so I'm reverting the change to fix a warning here.
=> Restore compatibility with 5.3 branch of swift-driver

Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Inform the user what package contains the duplicate target dependency. Figured it would be better to add a new method for the printout over editing the current message to just include the package name, that way it can be called whenever it's needed. 
rdar://47085587
=> The "duplicate target dependency" warning should say what package it's coming from

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Motivation:
It seems like sending request header `Accept-Encoding: *` would cause some servers to do gzip compression (`Content-Encoding: gzip`) and chunked transfer (`Transfer-Encoding: chunked`), and would lead to missing `Content-Length` header in the response.
Modification:
Explicitly disallow gzip encoding.
=> [Collections] Missing Content-Length header

Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift
motivation: fatalError crashes the process, do not uses unless absolutley required
changes:
* replace fatalError with throw InternalError where possible
* remove redundant overrides that are not in use
=> reduce use of fatalError

Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Package.swift, Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MyLocalTool/main.swift, Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenExt/extension.swift, Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenRuntimeLib/library.swift, Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenTool/main.swift, Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenToolLib/library.swift, Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Tests/MySourceGenExtTests/MySourceGenExtTests.swift, Sources/Build/BuildPlan.swift, Sources/Commands/Describe.swift, Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest/TargetDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageModel/Target.swift, Sources/Workspace/InitPackage.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/Xcodeproj/SchemesGenerator.swift, Sources/Xcodeproj/Target+PBXProj.swift, Sources/Xcodeproj/pbxproj.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageLoadingTests/PD4_0LoadingTests.swift, Tests/PackageLoadingTests/PD5_0LoadingTests.swift, Tests/PackageLoadingTests/PD5_4LoadingTests.swift, Tests/PackageLoadingTests/PDNextVersionLoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
A start at a draft implementation of https://github.com/abertelrud/swift-evolution/blob/swiftpm-extensible-build-tools/proposals/NNNN-swiftpm-extensible-build-tools.md
This is guarded by a feature flag until the proposal is accepted and any requested changes have been implemented.  Until then, extensions can be enabled by setting SWIFTPM_ENABLE_EXTENSION_TARGETS=1 in the environment.  If the proposal is rejected, the changes can easily be neutralized by just reverting PackageDescription.
Package extension targets don't yet do anything in this PR — that is in the works, and will be in future PRs soon.  But with this PR they can be declared in manifests, and they are present in the project model.  They show up in generated manifest sources and in package descriptions.  This commit includes …
=> Preparatory work for extensions to generate build commands (under feature flag pending proposal review)

Sources/PackageLoading/PackageDescription4Loader.swift
Throwing an error on aesthetic issues like this makes it difficult to conditionally generate these arguments.
(This is a followup to #2880.)
=> Don't trap on empty resource lists

Fixtures/Miscellaneous/LocalPackageAsURL/Bar/Package.swift, Fixtures/Miscellaneous/LocalPackageAsURL/Bar/main.swift, Fixtures/Miscellaneous/LocalPackageAsURL/Foo/Foo.swift, Fixtures/Miscellaneous/LocalPackageAsURL/Foo/Package.swift, Package.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/SPMTestSupport/misc.swift, Sources/SourceControl/GitRepository.swift, Tests/FunctionalTests/MiscellaneousTests.swift
Improve error message
rdar://69272273
=> Improved the error message when using a local package dependency as 'url:' instead of 'path:'

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/SPMTestSupport/misc.swift
Allow the feature flag to enable package extensions to be controlled by input parameters to the package graph in addition to the SWIFTPM_ENABLE_EXTENSION_TARGETS environment variable.
This makes it easier to write unit tests for package extensions, which will continue to be behind a feature flag until the proposal is accepted and any needed changes have been made.
Thread through a new boolean so that the feature is enabled if either the caller asks for it or if SWIFTPM_ENABLE_EXTENSION_TARGETS is set in the environment.
This builds on https://github.com/apple/swift-package-manager/pull/3277 and it is best to review that PR first and then just the diff b4c8df39b4d66b14649ab6f103d0387f1ce33941 of this PR.
=> Allow unit tests to enable feature flag controlling extension feature

Sources/PackageLoading/CMakeLists.txt
motivation: PR #3236 added a dependency between PackageLoading and SourceControl but did not update CMake
changes: add a dependency between PackageLoading and SourceControl in CMake
=> add a dependency between PackageLoading and SourceControl in CMake

Package.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/SPMBuildCore/CMakeLists.txt, Sources/SPMBuildCore/ExtensionEvaluator.swift, Sources/SPMTestSupport/PackageGraphTester.swift, Sources/SPMTestSupport/misc.swift, Tests/SPMBuildCoreTests/ExtensionEvaluationTests.swift
Add a first version of an ExtensionEvaluator that allows all use of extensions in targets to be evaluated and that returns the commands to run and other information.  Some TODOs and FIXMEs in the code for things left to be filled in, such as product dependencies and separate extension usage arrays.  This will be added in follow-on PRs.
This abstracts out the logic around invoking extensions and passing them inputs and receiving outputs, while leaving the details of how that is done (e.g. compiling and then running in a sandbox, or some other way) to concrete implementations.  This also allows the facility to be at a lower level than the logic providing the extension runner.
There is no caching yet and but that will be added in future PRs (although most is likely to live in the concrete …
=> Add an ExtensionEvaluator for evaluating extensions in a package graph

Package.swift, Sources/PackageCollectionsSigning/CMakeLists.txt, Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift, Sources/PackageCollectionsSigning/PackageCollectionSigning.swift, Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift, Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift, Tests/PackageCollectionsSigningTests/Utilities.swift
This is part 3 of a series of PRs to support package collection signing on **Apple** platforms. Originally #3245.
Depends on #3264
Modifications:
- Add certificate policies to validate collection-signing certificates.
- Wire up `PackageCollectionSigning` with certificate policies.
=> [Collections] Signing (apple, 3): certificate validations

Sources/PackageLoading/ManifestLoader.swift
Filter out remarks from the swift driver when parsing manifests.
This remark is temporary, but is causing spurious test failures for tests that make sure there are no diagnostics.
Avoid emitting a diagnostic when the only output from manifest compilation is the remark.
Remarks from manifest compilation will no longer show up as diagnostics from SwiftPM.  Note that remarks from building are unaffected.
=> When compiling manifests, filter out remarks emitted by new Swift compiler driver

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsSourcesStorageTest.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
On non-Apple platforms since there are no trusted root certificates by default, signature checks will most certainly fail. To help people get started more quickly, and to offer people a way to opt-out, we will add a `--skip-signature-check` flag to the `add` collection command. User's selection is persisted to collection sources config such that `refresh` would honor it as well.
Modifications:
- Add `skipSignatureCheck` to `CollectionSource`
- Add `--skip-signature-check` to CLI
- Add `isVerified` to `Collection.SignatureData`. It is `false` when `skipSignatureCheck == true`.
- Update logic in `JSONPackageCollectionProvider` to honor `skipSignatureCheck`
- Update CLI to handle `cannotVerifySignature` error
=> [Collections] Add skip signature check option to 'add'

Package.swift
We will add signing to [the set of collections tools](https://github.com/apple/swift-package-collection-generator), and for that we'd need `PackageCollectionsSigning`.
=> [Collections] Export PackageCollectionsSigning as library

Sources/Build/ManifestBuilder.swift, Sources/SPMBuildCore/ExtensionEvaluator.swift, Tests/SPMBuildCoreTests/ExtensionEvaluationTests.swift
Allow the executable in commands passed back from extensions to be a string either a relative or absolute path.  If a string, it will be resolved against the build directory.
Note that the whole feature of build tool extensions is guarded by a feature flag until the proposal has been reviewed and any feedback has been implemented.
The interface by which extensions specify the executable to invoke is still being worked out for this experimental feature, and allowing them to pass back a string will make it easier to iterate on the possible approaches.  When binary targets support executables, this may change again.
Changed the executable from AbsolutePath to String
Form an AbsolutePath on use (using build products directory as base path)
=> [Extensions] Allow commands passed back from extensions to reference a relative or absolute path

Sources/Workspace/Workspace.swift
This lets clients of libSwiftPM enable the experimental support for package extensions.
=> [Extensions] Pass through the `allowExtensionTargets` flag from the Workspace to PackageGraph

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fix an assertion failure that occurred when a local XCFramework was at a subdirectory (the path in the manifest can be a relative path and not just a path component).
=> Fix an assertion failure with XCFramework inside a subdirectory

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections+CertificatePolicy.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionSourceCertificatePolicyTests.swift
Motivation:
If a collection source has an entry in the certificate pinning configuration that it must be signed. Currently we are not checking for this.
Modifications:
Update `JSONPackageCollectionProvider` to check that if a collection is unsigned, then it shouldn't have an entry in the certificate pinning configuration. Otherwise, throw `missingSignature` error which cannot be bypassed.
=> [Collections] Check for collections that are required to be signed

Sources/Basics/ConcurrencyHelpers.swift, Sources/SPMTestSupport/MockHTTPClient.swift, Sources/SPMTestSupport/MockHashAlgorithm.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: to support the package extensions feature, we need to support binary dependencies with tools that can be distributed across different platforms. in previous PR we intriduces the archive file, this PR adds the archive index files which helps control the size of the archive files by splitting them across key platforms
changes:
* introduce new binary dependency file type named "Archive Index" with the extension "ari"
* the structure of the file is a flat list of archive files, their checksums and the target-triples they support
* add code to Workspace pre-downloading the binaryTarget "zip" files to first fetch "ari" files, parse them and add any relevant "zip" files to the *host* tripple to the list of candidate downloads
----
the new archive file name, …
=> introduce archive index files

Sources/Commands/SwiftPackageTool.swift
motivation: fix a bug where in some cases a duplicate error message is printed
changes: only try to load the graph if the previous operation succeeded
=> Duplicate error message on package resolve

Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Motivation:
When package collection model/format changes, deserializing data stored in SQLite might fail. Most of the time `SQLitePackageCollectionsStorage`
just silently ignores deserialization errors, and no one would know that something had gone wrong. This could lead to collection APIs not
returning any data, which would be confusing for users.
What we should do with this kind of deserialization error is to trigger collection refresh so that data in SQLite gets updated. `listCollections`
can do this quite easily by calling refresh whenever the results count does not equal sources count.
Modifications:
In `listCollections` check that sources count equals results count, otherwise trigger refresh on the "missing" collections.
=> [Collections] Trigger collection refresh if deserialization of SQLite data fails

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
This fixes warnings of the form
> clang: warning: -framework XCTest: 'linker' input unused [-Wunused-command-line-argument]
when using `linkedFramework` for C-family and Swift targets.
rdar://74548652
=> Do not pass `-framework` to compiler tasks

Sources/Workspace/InitPackage.swift
Newly generated executable packages currently use `.target(...)` API for declaring the executable target, which seems to be deprecated since 5.4.
* bumped `swift-tools-version` for new packages to 5.4
* replaced `.target` call with `.executableTarget` for new executable packages
After this change `swift package init --type executable` generates a package which declares the executable target via the new `.executableTarget(...)` API.
=> Use `executableTarget` in generated new executable packages

Package.swift
[swift-crypto v1.1.4](https://github.com/apple/swift-crypto/releases/tag/1.1.4) has all the changes we need and we can pin to that version instead of `main`.
=> Update swift-crypto dependency to use version instead of main

Sources/PackageGraph/PackageGraph+Loading.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: package identity is critical to SwiftPM ability to dedup package reliably
changes:
* use package identity instead of manifest name to flatten the dependencies list
* add more test for duplicate identity permutations across identity derived from URL and manifest name
=> improve identity handling

Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollectionsSigning/Certificate/Certificate.swift, Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift, Sources/PackageCollectionsSigning/Key/Key+EC.swift, Sources/PackageCollectionsSigning/Key/Key+RSA.swift, Sources/PackageCollectionsSigning/Signing/Signing+RSAKey.swift, Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift, Tests/PackageCollectionsSigningTests/CertificateTests.swift, Tests/PackageCollectionsSigningTests/KeyTests+EC.swift, Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift, Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift, Tests/PackageCollectionsSigningTests/SignatureTests.swift, Tests/PackageCollectionsSigningTests/SigningTests+ECKey.swift, Tests/PackageCollectionsSigningTests/SigningTests+RSAKey.swift, Tests/PackageCollectionsSigningTests/Utilities.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Some `Security` framework APIs are available on macOS only
=> [Collections] Tighten import conditions

CHANGELOG.md, Documentation/PackageDescription.md, Fixtures/DependencyResolution/External/Branch/Bar/Package.swift, Fixtures/DependencyResolution/External/Branch/Bar/Sources/Bar/Bar.swift, Fixtures/DependencyResolution/External/Branch/Foo/Package.swift, Fixtures/DependencyResolution/External/Branch/Foo/Sources/Foo/Foo.swift, Sources/PackageDescription/PackageDependency.swift, Sources/SPMTestSupport/misc.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/PackageLoadingTests/PD4_0LoadingTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift
Improve quality of life when using a branch for a package dependency requirement.
It feels more natural to use `.package(url:, branch:)` as opposed to `.package(url:,.branch())`
rdar://55857600
=> Allow for .package(url: , branch:) syntax

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageModel/Manifest.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: SwiftPM 5.2 introduced target based dependencies which added complexity at code level and to users, this PR tries to both simplify the "rules" and the code
changes:
* allow target dependency in the form of ".product(name:, package:)" where package parameter is the last segment of the dependency URL, which is the most intuitive choice (IMO)
* change validation code to encourage the above form instead of encouraging adding a "name" attribute to the dependency deceleration. we want to get away from dependency::name in the long run.
* add several tests that capture the numerous permutations we are coding for
rdar://65048461
=> improve and simplify validation of target based dependencies

Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Sources/PackageModel/Manifest/TargetDescription.swift, Sources/PackageModel/Target.swift
Move the usage of plugins from the `dependencies` parameter of targets in the package manifest to instead be in a separate `plugins` parameter.
Despite their similarity to dependencies we want users to consider them differently.  This also leaves room to grow in the future, when plugin usage might support parameters, etc.  We encode them separately in the manifest JSON, but merge them into regular dependencies to avoid duplicated implementation on the SwiftPM side.  This can be changed later without affecting clients.  For now it would just mean duplicate code.
Modifications:
- change PackageDescription API in accordance with proposal (involving the usual unfortunate duplicate of declarations with deprecation of older ones)
- add PluginUsage type, and plumb it through
- in PackageBuilder, …
=> Move usage of plugins from `dependencies` to `plugins` parameter to align with SE-0303

Sources/PackageCollections/Model/Collection.swift, Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Motivation:
`refreshCollection` relies on `CollectionSource` argument to provide the correct source config, but it should:
1. Check that the source exists in the config
2. Read latest source config from storage
Modifications:
Update `refreshCollection` to check that the given source exists in config file before actually doing a refresh. Also make sure that `Collection`'s `source` is current before returning it.
=> [Collections] refreshCollection should have correct source config

Sources/Commands/SwiftPackageCollectionsTool.swift
Motivation:
`package-collection`'s `describe` subcommand should display signature info if collection is signed.
Modifications:
Update output for signed collection to print additional:
```
Signed By: Jane Doe (verified)
```
=> [Collections] describe subcommand should include signature info

CHANGELOG.md, Documentation/PackageDescription.md, Sources/PackageDescription/PackageDependency.swift, Tests/PackageLoadingTests/PD4_0LoadingTests.swift, Tests/PackageLoadingTests/PDNextVersionLoadingTests.swift
Just adding the convenience init .package(url: String, revision: String)
=> Allow for .package(url: String, revision: String) syntax

Sources/PackageLoading/TargetSourcesBuilder.swift
The current version is repetitive in two ways:
1. Prints the path out twice
2. The same warning can be emitted multiple times
With these changes not only is the warning message more concise, but it only prints unique warnings out 
If an exclude, source, and or resource is missing/found outside the root of the package a warning will be emitted
=> Clean up warnings, and only emit unique warnings with respect to missing targets, sources, and or resources

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
`testHappyRefresh` crashed in https://ci.swift.org/job/oss-swift-package-centos-8/975
```
Test Suite 'PackageCollectionsTests' started at 2021-03-02 22:01:52.483
Test Case 'PackageCollectionsTests.testHappyRefresh' started at 2021-03-02 22:01:52.483
Exited with signal code 11
```
This is similar to https://github.com/apple/swift-package-manager/pull/3232
Modifications:
Both `testHappyRefresh` and `testBrokenRefresh` call `listCollections` after `refreshCollections`, and part of the `listCollections` code where we read collection blobs from the database might be racy since we are not using `ThreadSafeArrayStore`.
=> [Collections] Potential fix for race in list collections

Sources/Basics/ConcurrencyHelpers.swift, Sources/SPMTestSupport/MockArchiver.swift, Sources/SPMTestSupport/MockHashAlgorithm.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: fix flaky tests
changes:
* make MockArchiver thread safe + refactor for better readability
* make few WorkspaceTests that monitor downloads thread-safe
* refactor MockHashAlgorithm for for better readability (same change as MockArchiver)
rdar://75060297
=> make download test utilities thread-safe

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift, Sources/SPMBuildCore/PluginInvocation.swift
Follow-up to #3311 where "extension" was renamed to "plugin" — this commit makes that same change in `PackageCollectionModel.V1.ProductType` and other related sites.
Update `PackageCollectionModel.V1.ProductType` to be consistent with `PackageModel.V1.ProductType`.
- Renamed `PackageCollectionModel.V1.ProductType` case `.extension` to `.plugin`.
- Fixed deprecation message in `PluginInvocation.swift` to point to correct replacement.
/cc @abertelrud @yim-lee
=> Rename straggling "extension" cases to "plugin"

Tests/CommandsTests/PackageToolTests.swift
motivation the test "testArchiveSource" has been writing a file to the project's root when invoked from the command line
changes: change the test to use a temporary directory instead of current working directory
=> stop testArchiveSource from writing files to package root

CHANGELOG.md, Fixtures/Miscellaneous/ExeTest/Package.swift, Fixtures/Miscellaneous/TestableExe/Package.swift, Fixtures/Miscellaneous/TestableExe/Sources/TestableExe1/main.swift, Fixtures/Miscellaneous/TestableExe/Sources/TestableExe2/main.swift, Fixtures/Miscellaneous/TestableExe/Sources/TestableExe3/include/TestableExe3.h, Fixtures/Miscellaneous/TestableExe/Sources/TestableExe3/main.c, Fixtures/Miscellaneous/TestableExe/Tests/TestableExeTests/TestableExeTests.swift, Sources/Build/BuildPlan.swift, Sources/PackageGraph/PackageGraph.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift
Allow unit test targets to import and link executable targets.  This allows them to test everything except the main function in those targets without having to run the executable as a subprocess.  With these changes they can still run the subprocess if they want to.
Many package authors don’t want to split their code into executable targets vs library targets, but still want to test data structures and algorithms in their executables.
This uses a new Swift compiler flag introduced in https://github.com/apple/swift/pull/35595 to compile the main symbol to a different name than `_main`, so that it doesn't cause symbol collisions when linked into a test executable.  When linking the actual executable, the entry point symbol is then renamed back to to `_main`.  This is done using linker flags …
=> Allow unit test targets to import and link executable targets

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/SPMBuildCore/PluginInvocation.swift, Sources/SPMTestSupport/misc.swift, Sources/Workspace/Workspace.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
- removed the no-longer-needed deprecated shims
- changed remaining uses of "extension" to "plugin" in comments and unit tests
=> Clean up remaining uses of "extension" terminology (it's now "plugin")

Tests/BuildTests/BuildPlanTests.swift
Fix the unit tests so they work on Apple Silicon Macintoshes.
Get unit tests passing.
Replace hardcoded strings with ones that depend on the host toolchain.
rdar://75113176
=> Fix invalid assumptions leading to unit test failures on Apple Silicon

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageCollections/Storage/Trie.swift
Motivation:
`testHappyRefresh` still crashes. See:
https://ci.swift.org/job/oss-swift-package-linux-ubuntu-16_04/5991/console
`refreshCollections` leads to target trie getting updated. `Trie` is not thread-safe.
Modifications:
Make `Trie` thread-safe. `TrieNode` should be thread-safe already.
=> [Collections] Fix racy refresh

Sources/LLBuildManifest/BuildManifest.swift, Sources/LLBuildManifest/ManifestWriter.swift, Sources/LLBuildManifest/Tools.swift, Tests/BuildTests/LLBuildManifestTests.swift
Extend LLBuildManifestWriter to let shell commands specify environment and initial working directory.
Plugin build tool commands can specify an environment and initial working directory, and we need LLBuildManifestWriter support for this.
- add parameters to addShellCmd()
- add support for writing out dictionaries to the llbuild manifest
- add unit test for shell command writing
=> Extend LLBuildManifestWriter to let shell commands specify environment and initial working directory

Sources/PackageLoading/TargetSourcesBuilder.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
This changes `diagnoseInvalidResource` to work off the declared resources instead of the ones we found rules for. Also amended some of the tests with a check for a count of diagnostics since they could pass with zero diagnostics being emitted.
=> Fix `diagnoseInvalidResource`

Tests/CommandsTests/BuildToolTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/CommandsTests/RunToolTests.swift, Tests/CommandsTests/TestToolTests.swift
Add the stdout that was received to the test failure, so we can know what the problem is.  This is good in general, since it's hard to diagnose these failures without seeing the output.
The motivation here is to find and fix a unit test failure that only seems to happen in CI.
=> Add better unit test failure diagnostics for when basic SwiftPM commands fail

Tests/CommandsTests/RunToolTests.swift
=> Unit test should handle both SwiftArgParser 0.3.x and 0.4.x output

Sources/Basics/ConcurrencyHelpers.swift, Sources/Commands/Error.swift, Sources/Commands/Options.swift, Sources/SPMBuildCore/Sanitizers.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: no warnings, happy delelopers
changes:
* remove left over code referring to TSC argument parser and Downloader which are both deprecated and not in use
=> resolve warnings resulting from deprecations in TSC

Sources/Commands/SwiftTool.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/SPMTestSupport/misc.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
When introducing the `--build-system xcode` option, we apparently did not consider that the file types that are specific to that mode should not be enabled when using the built-in build system. We also did not actually support the `additionalFileRules` parameter of `TargetSourcesBuilder`, it was never passed to the actual computation.
This PR changes the behavior for tools version > 5.4 only to be backwards compatible. In newer tools versions, we will only include the XCBuild specific file types in the CLI when XCBuild is being used. When using libSwiftPM, the file types will not be included at all, unless using an older tools version.
rdar://64961989
=> Do not include XCBuild file types by default

Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Sources/MyLocalTool/main.swift, Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Sources/MySourceGenBuildToolPlugin/plugin.swift, Sources/SPMBuildCore/PluginInvocation.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/FunctionalTests/PluginTests.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Like package manifests, package extensions are compiled as executables and are run in order to produce output.  These invocations need to be sandboxed in the same way as package manifests are.
As with package manifests, this is currently only supported on macOS, and uses `sandbox-exec`.  Support for other platforms is tracked by rdar://40235432.  When it is implemented for manifests for other platforms, the implementation should be done in a way that supports package plugins as well.
The sandboxes for manifests and package plugins are similar, and the implementations for the two kinds of script runner should be unified. 
rdar://74662476
=> Run package plugin scripts in a sandbox that permits writing only to the designated output directory

Tests/XcodeprojTests/FunctionalTests.swift
This makes the Xcode project generation tests more robust by passing the `macOS` platform.  These tests are currently specific to macOS anyway, so this is appropriate.
Pass `-destination` `platform=macOS` to `xcodebuild` to be specific about the destination.  This is more robust.
=> Fix Xcode project generation build tests to pass the platform to `xcodebuild`

Sources/Build/BuildPlan.swift, Sources/Build/CMakeLists.txt, Sources/SPMBuildCore/ArtifactsArchiveMetadata.swift, Sources/SPMBuildCore/BinaryTarget+Extensions.swift, Sources/SPMBuildCore/CMakeLists.txt, Sources/SPMBuildCore/XCFrameworkMetadata.swift, Tests/SPMBuildCoreTests/ArtifactsArchiveMetadataTests.swift, Tests/SPMBuildCoreTests/XCFrameworkMetadataTests.swift
Move down the parsing of binary artifacts such as XCFrameworks and ArtifactArchives to SPMBuildCore.
We can also discuss whether it should in fact be moved down to the project model.
This makes conceptual sense anyway, but in particular so that plugins can have access to it.
- move down code from Build target to SPMBuildCore target
- adjust CMakeList etc.
This is a fairly literal sinking down of the APIs.  An API cleanup to unify the different kinds of binary artifact can wait for a future PR.
=> Move down the parsing of binary artifacts to SPMBuildCore

Sources/PackageGraph/PackageGraphRoot.swift, Sources/PackageGraph/PackageModel+Extensions.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
An `assert` would cause Xcode to crash if there is bad configuration in the manifest i.e. using the url to a pull request as if it was a branch. 
Now instead we guard and throw a StringError for a more graceful exit.
rdar://60879046
=> Prevent Xcode from crashing because of a bad branch config in manifest file

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
motivation: fix data race
changes: guard access to progressAnimation with the queue
=> fix data race in build-complete handler

Documentation/PackageCollections.md
Document for SwiftPM users how to use the `package-collection` CLI and the signing-related errors that they might see, and for collection publishers how to generate and sign collections, as well as the certificate-pinning config.
=> [Collections] Documentation

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
motivation: when build-complete handler is run async it may never get actually done since the process may exit
changes: run the complete handler sync
=> run build complete handler sync

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Previously, sources directories must be all swift or all clang based source files--even if `additionalFileRules` had a file rule description that matches against a file in sources. This commit makes SwiftPM respect the `additionalFileRules` parameter.
The `additionalFileRules` parameter was never practically usable for sources directories, since having a rule that matched against a certain file extension would cause SwiftPM to emit an error that the sources were considered mixed. This PR is a targeted fix for allowing `additionalFileRules` to match against files in the sources directory.
Fixes the implementation for a property called `containsMixedLanguage`, which now checks to if there are both Clang and Swift based sources (instead of what the previous implementation did, which only …
=> Support `additionalFileRules` inside sources.

Utilities/bootstrap
With the version-bump of Yams in https://github.com/apple/swift/pull/36366, Yams `4.0.2` now actually expresses the dependency on Dispatch in its CMake config.
With the current behavior of passing `-Ddispatch_DIR` to its CMake build, we have the following problem on Linux:
- `swift`'s `build-script` installs Dispatch into a just-built toolchain which we use to build SwiftPM, which will contain, among other things, the Dispatch `.swiftmodule`.
- The compiler workspace checkout of `swift-corelibs-libdispatch` also contains a copy of the Dispatch `.swiftmodule`.
Both of these will be found, leading to build failures like:
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-nightly-install/usr/lib/swift/dispatch/module.modulemap:1:8: error: redefinition of module 'Dispatch' …
```
=> [Bootstrap] Do not pass `-Ddispatch_DIR` to the Yams CMake build

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
Ordering of search results is not consistent across runs of the same query.
Modifications:
FTS doesn't sort results by relevance, and since post-processing of search results uses dictionary, ordering wouldn't be preserved anyway.
To have consistent ordering then, we sort package results by identity and targets by name.
=> [Collections] Consistent ordering of search results

Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/PackageModel/Diagnostics.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: better performance, happier users
changes:
* the bottle neck in dependency resolution is the iteration of available versions and reducing the list to thos with matching tools-versions,
each version iteration shells out to git several times now, which is fairly expensive given the shelling out aspect.
* change RepositoryPackageContainer::toolsVersion to find & load the manifest based on tag
* change RepositoryPackageContainer::loadManifest to load the manifest based on tag
* this reduces the amount of git shelling (in this use case by 60%), reducing total resolutoin duration  for large packages by 25%
=> [performance] reduce dependency resolution git calls

Sources/Basics/ConcurrencyHelpers.swift, Sources/Basics/HTTPClient.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageGraph/LocalPackageContainer.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Sources/SPMTestSupport/MockManifestLoader.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift
motivation: improve performance, reduce complexity
changes:
* define single shared concurrent queue and update code that runs async operation to use it.
* replace cases where dispatch queue is used "as a lock" with a lock
=> [performance] reduce amount of dispatch queues

Fixtures/Miscellaneous/Edit/App/Package.swift, Fixtures/Miscellaneous/Edit/App/src/main.swift, Fixtures/Miscellaneous/Edit/Bar/Bar.swift, Fixtures/Miscellaneous/Edit/Bar/Package.swift, Fixtures/Miscellaneous/Edit/Foo/Foo.swift, Fixtures/Miscellaneous/Edit/Foo/Package.swift, Sources/Workspace/Workspace.swift, Tests/FunctionalTests/MiscellaneousTests.swift
motivation: changes to identity has broken edit mode
changes:
* compute edited path from the managed depedency instead of relying on location which is now the remote location
* add end to end test for edit mode (local urls)
rdar://75645049
=> fix regression in edit mode

Sources/Basics/ConcurrencyHelpers.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Motivation:
The `getMetadata` API makes GitHub API requests to fetch additional package metadata. We can cache the results as optimization, which also decreases the chance of caller hitting API limit.
Modifications:
Add cache to GitHubPackageMetadataProvider. Default TTL is 1 hour.
=> [Collections] Cache GitHub API responses

Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
Motivation:
Apple Development certs are valid code signing certs that can be used for signing collections, so we should support critical extensions that are unique to them as well.
Modifications:
Expand the list of supported critical extensions to prevent BoringSSL verification failure.
=> [Collections] Support Apple Development cert marker extensions

Sources/PackageCollectionsSigningLibc/asn1/a_d2i_fp.c, Sources/PackageCollectionsSigningLibc/ocsp_cl.c, Sources/PackageCollectionsSigningLibc/ocsp_vfy.c
Motivation:
Build SwiftPM with `-Xcc -Wshorten-64-to-32` and see a bunch of these warnings.
Modifications:
Fix warnings wherever we can. Many of them come from the dependencies though.
=> Reduce "implicit conversion loses integer precision" warnings

Documentation/ReleaseNotes/5.4.md
Adds a 5.4 release notes file alongside 5.3 containing the main changes in 5.4.  Moving forward this should be created much earlier in the release cycle, so a separate commit will create a 5.5 release notes file and start iterating on the 5.5 changes.
=> Add release notes file for SwiftPM 5.4

CHANGELOG.md, Fixtures/DependencyResolution/External/Branch/Bar/Package.swift, Fixtures/DependencyResolution/External/Branch/Foo/Package.swift, Fixtures/Miscellaneous/ExeTest/Package.swift, Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Package.swift, Fixtures/Miscellaneous/TestableExe/Package.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, IntegrationTests/Tests/IntegrationTests/Helpers.swift, Sources/Basics/SwiftVersion.swift, Sources/Build/BuildPlan.swift, Sources/PackageDescription/PackageDependency.swift, Sources/PackageDescription/Product.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageDescription/Target.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SPMTestSupport/Resources.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/PackageLoadingTests/PD4_0LoadingTests.swift, Tests/PackageLoadingTests/PD5_4LoadingTests.swift, Tests/PackageLoadingTests/PD5_5LoadingTests.swift, Tests/PackageLoadingTests/PDNextVersionLoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
This updates the current SwiftPM to 5.5 (see https://forums.swift.org/t/swift-5-5-release-process/45644).
When a new Swift release is announced, SwiftPM is updated to reflect that version.
- change default version to 5.5.0
- add `v5_5` tools version
- modify `999.0` availability and `vNext` to `5.5` and `v5_5` respectively
- adjust unit test to reflect that executable modules are now linkable by unit tests
Note that SwiftPM is still marked as a development version so that 999.0 is still accepted in mainline.  This will be changed after branching 5.5.
=> Update current SwiftPM version to 5.5

Documentation/PackageDescription.md
A one-line description for a one-line documentation change: just reducing “.com.com” to “.com”.
Doubled-up “.com” is unnecessary in example code or anywhere, really.
Reduced the example package URL from “http://example.com.com/ExamplePackage/ExamplePackage” to “http://example.com/ExamplePackage/ExamplePackage”.
Example code is now easier to grok. Hooray!
=> Remove duplicated “.com” in product example code documentation

Sources/Build/SPMSwiftDriverExecutor.swift
We have switched to a newer version of swift-driver at this point and can fix this warning.
=> Fix warning

Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PD5_0LoadingTests.swift
Throw an error instead.
rdar://75936643
=> Fix crash on invalid Swift language version

Sources/PackageModel/Platform.swift, Tests/BuildTests/BuildPlanTests.swift
=> 10.11 minimum deployment target

Sources/PackageModel/Platform.swift, Tests/BuildTests/BuildPlanTests.swift
This reverts commit 5fe380c387b06b4079aa10ccae6be41dc3838707.
With https://github.com/apple/swift-driver/pull/581 being merged, we can undo this temporary workaround.
rdar://76167831
=> Revert "Raise the minimum deployment target to 10.11 (#3384)"

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Motivation:
Currently `getPackageMetadata` searches across all imported collections for a given package and if found, returns metadata from the most recently processed
collection. This isn't always the desired behavior though, for we might be interested in metadata from specific collection(s) only.
Modifications:
Add optional `collections` parameter to the API. It keeps the current behavior if `nil`, otherwise it only searches inside the specific collections.
=> [Collections] getPackageMetadata from specific collections

Tests/BuildTests/BuildPlanTests.swift
Loosen the pattern-match to detect that the expected dependencies files are present.
As of https://github.com/apple/swift-driver/pull/582 swift-driver will correctly generate unique temporary files, and this test relied on that not being the case.
=> [Test] Fixup `testExplicitSwiftPackageBuild` test to account for swift-driver's temporary files having unique filenames.

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
1s might be too aggressive for larger collections. Increasing it to 5s.
=> [Collections] Increase timeout for fetching package collections

Sources/Build/BuildPlan.swift, Sources/Commands/SwiftTool.swift, Tests/FunctionalTests/MiscellaneousTests.swift
motivation: nicer user experience in cases LinuxMain is kept for older tools
changes:
* only emit --enable-test-discovery deprecation warning when targeting darwin based platforms or when LinuxMain does not exist
* adjust tests
rdar://76356108
=> refine when --enable-test-discovery deprecation warning is emmited

Sources/PackageCollections/PackageCollections+Validation.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Motivation:
Refresh fails when a collection's URL changes or becomes invalid. The API error returned is `Basics.HTTPClientError.badResponseStatusCode(404)` which 1) doesn't tell user which collection is failing; 2) might be confusing if user is not familiar with HTTP status codes.
Modifications:
Improve error messages. For example, the error above becomes `collectionNotFound` and includes collection URL.
=> [Collections] Improve error messages

Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
Package release on GitHub has title/name. It would be nice to display it.
Modifications:
- Add `title` to the `Version` model.
- Update `GitHubPackageMetadataProvider` to set `version.title` to `release.name`. We were fetching `release.name` already just didn't have a place for it.
- Update package metadata merge logic.
=> [Collections] Add optional title to package version

Tests/PackageCollectionsSigningTests/Utilities.swift
Motivation:
Tests in `PackageCollectionsSigningTests` that involve `Test_ec.cer` are failing. See https://github.com/apple/swift-package-manager/pull/3393.
I think this is a timezone-related issue. `Test_ec.cer` is valid from November 15, 2020 10:45:20am PST for a year. In the tests we manipulate the timestamp at which the cert validation is done so we don't have to regenerate new test certs and so we can test for different scenarios. That timestamp is set to November 16, 2020 midnight, and depending on where the tests are run, it might potentially mean a time before `Test_ec.cer` is valid and that's why we see "certificate is not yet valid" error. Note that this doesn't happen with tests that use `Test_rsa.cer` since the certificate is valid from November 8, 2020.
Modification:
Change …
=> [Collections] Adjust cert verify date in tests

Sources/PackageCollections/PackageCollections.swift
Steps to reproduce:
1. Add a local collection
2. Delete or rename the local collection file
3. Try deleting the local collection
Result: Error about local file not found
Expected: Non-existent local collection deleted
The `remove` collection subcommand calls `getCollection` API to fetch collection's name for displaying success message later. `getCollection` tries to fetch collection from storage, and if it's not found there, it fetches from the source directly. The error is caused by the source validation logic, which mistakenly is the first thing `getCollection` does but should really only be done when we need to fetch from the source.
=> [Collections] Should be able to delete a non-existent local collection

Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageCollectionsSigning/Certificate/Certificate.swift, Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift, Sources/PackageCollectionsSigning/Key/BoringSSLKey.swift, Sources/PackageCollectionsSigning/Key/Key+RSA.swift, Sources/PackageCollectionsSigning/Signing/BoringSSLSigning.swift, Sources/PackageCollectionsSigning/Signing/Signing+RSAKey.swift, Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift, Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift, Tests/PackageCollectionsSigningTests/Utilities.swift
Fix building package collections for Android
Building latest trunk or the last March 25 trunk source snapshot for Android fails because Android is not added to these supported OS lists.
Add Android to the list of supported OS's.
I'm now able to both cross-compile and natively compile SPM for Android. When running the tests, I get the following failures:
```
Test Suite 'Selected tests' started at 2021-04-08 16:09:18.868
Test Suite 'CertificatePolicyTests' started at 2021-04-08 16:09:18.890
Test Case 'CertificatePolicyTests.test_EC_validate_happyCase' started at 2021-04-08 16:09:18.891
/data/data/com.termux/files/home/src/swiftpm/Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift:56: error: CertificatePolicyTests.test_EC_validate_happyCase : XCTAssertNoThrow failed: threw …
```
=> Android: enable BoringSSL and other Package Collections support

Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/Target.swift
This makes it so compiling a manifest won't require the presence of the Foundation .swiftmodule
=> Use implementation-only imports

Sources/PackagePlugin/ImplementationDetails.swift, Sources/PackagePlugin/PublicAPI/Path.swift
This is the same as https://github.com/apple/swift-package-manager/pull/3404 but for PackagePlugin.
As with PackageDescription, PackagePlugin should not have an interface dependency on Foundation.  There is no specific current problem but reducing the dependencies here is cleaner.
Convert one import of Foundation to implementation-only (we need it for decoding the JSON coming from SwiftPM and for encoding the JSON sent to SwiftPM).
Remove another import of Foundation altogether; it was only left over from code that has since been removed.
=> Use implementation only import of Foundation in PackagePlugin

Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Motivation:
Some of the tests generate random HTTP status code to simulate bad collection URLs, but recent code changes distinguish status `404` from others and return a `notFound` error instead of `unavailable`. This causes tests to fail randomly.
Modification:
Change range of random generated status code to start from 500 such that `404` is excluded.
=> [Collections] Fix flakey tests

Sources/SourceControl/GitRepository.swift
Explicitly set `core.symlinks` to `true` to enable symlink support.
On Windows, symbolic link support in `git` is defaulted to `false`. Since SwiftPM itself also heavily depends on symlinking, there’s no reason that we should not enable it.
Explicitly set `core.symlinks=true` on `git clone`.
Repositories cloned by SwiftPM will have `core.symlinks` set to `true`, which means symbolic links can be resolved correctly.
If a system doesn’t support symlink, then SwiftPM itself will also break; if it does, then we should enable it regardless of global configs. We need to ensure that Swift package repos are checked out correctly.
=> Enable symlink support explicitly

Fixtures/Miscellaneous/DistantFutureDeploymentTarget/Package.swift, Fixtures/Miscellaneous/DistantFutureDeploymentTarget/Sources/main.swift, Fixtures/Miscellaneous/OverrideSwiftcArgs/Package.swift, Tests/FunctionalTests/MiscellaneousTests.swift
This fixes the test to be architecture-neutral.
Make the test work in CI on Apple Silicon.
This unit test was already specific to macOS, and this fix doesn't change that; what it does is to make the architecture the same as the host.  The old hardcoding of x64_64 seems to work on the desktop even on Apple Silicon, but does not appear to work in CI.
- generalize on the host architecture
- also fixes the use of 10.20 as a hypothetical future macOS release to instead be 41
- also renames the test to reflect the apparent intent of the test, which is narrower than the previous name suggested
rdar://76770888
=> MiscellaneousTests.testOverridingSwiftcArguments() fails on Apple Silicon

Sources/Commands/APIDigester.swift, Sources/Commands/SwiftTool.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/SourceControl/GitRepository.swift, Sources/SourceControl/Repository.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift, Sources/Xcodeproj/generate.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/InMemoryGitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: cloning has very specific meaning in git repository which is not quite what the delegate method represents, causing confusion
changes:
* deprecate willClone/didClone
* introduce willCreateWorkingCopy/didCreateWorkingCopy
* update call-sites and internal delegates
* adjust tests
=> deprecate willClone/didClone in favor of willCreateWorkingCopy/didCreateWorkingCopy

Sources/Basics/SwiftVersion.swift
Mark SwiftPM binaries produced from the 5.5 branch as release instead of development binaries.  Among other things this disables the use of 999.0 as a valid package tools version.
This is done for every release branch once it has been created.  As this change is only made on the release branch, `main` continues to be marked as a development branch.
- change a boolean flag in SwiftPM
=> [5.5] Disable the `development` flag on the 5.5 branch, marking 5.5 binaries as release builds

Fixtures/Miscellaneous/DistantFutureDeploymentTarget/Package.swift, Fixtures/Miscellaneous/DistantFutureDeploymentTarget/Sources/main.swift, Fixtures/Miscellaneous/OverrideSwiftcArgs/Package.swift, Tests/FunctionalTests/MiscellaneousTests.swift
This is the 5.5 nomination of a fix of a unit test.  Please see https://github.com/apple/swift-package-manager/pull/3414 for details.
=> [5.5] MiscellaneousTests.testOverridingSwiftcArguments() fails on Apple Silicon

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
The logic to generate manifest source from existing parsed manifest data structures misquoted some package version requirement ranges.
This fixes those cases, producing a semantically equivalent package manifests.  Since the model does not capture how a particular range was specified, it is not possible to recreate the original shorthands.
A future improvement can either extend the model to record the original spelling of the range requirements, or can apply heuristics to shorten the rules in the future (e.g. automatically derive `upToNextMajor()` etc.
This also eliminates an extra whitespace before the minimum tools version declaration when the specified tools version allows it, so older parsers can parse the generated manifests.
rdar://76559428
=> Fix a problem in the logic to generate manifest source from existing parsed manifest structs

Tests/CommandsTests/RunToolTests.swift
Cherry-picking this change in release/5.4 to unblock Apple Silicon bot.
=> Handle both SwiftArgParser 0.3.x and 0.4.x output.

Sources/Commands/SwiftPackageCollectionsTool.swift
Motivation:
Try adding a local package collection file with space(s) in the filename and it would result in error "Error: Invalid argument 'collectionUrl'".
Modifications:
In case `URL(string:)` fails, try `URL(fileURLWithPath:)` if the path starts with `file://`. This initializer escapes whitespaces appropriately.
rdar://76732268
=> [Collections] Better handling of spaces in collection file path

CHANGELOG.md, Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
Pass `-parse-as-library` when compiling an executable module that has a single source file that isn't named `main.swift`.  This avoids a compiler error when using `@main` in single-file executable modules.
It should be possible to use `@main` in executables, even if they are implemented as a single source file.
The Swift compiler has certain special behaviors regarding main source files:
- if a module has just a single source file of any name, then that file is treated as the main source file
- if a module has a source file named `main.swift`, then that file is treated as the main source file
If a source file is considered the main source file, it can have top level code.  But a source file that has top level code can't also have `@main`.
This means that a single source file executable …
=> Pass compiler flags to alllow use of `@main` in single-source-file executable modules

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3415 which fixes a problem serializing package manifests with ranged package dependencies.
=> [5.5] Fix a problem in the logic to generate manifest source from existing parsed manifest structs

CHANGELOG.md, Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3410 which makes it possible to have single-file source modules with a `@main` by taking the same approach as Xcode does when building such modules (also increasing compatibility of packages between SwiftPM and Xcode).
The original PR is https://github.com/apple/swift-package-manager/pull/3410 and has a lot more details.
=> [5.5] Pass compiler flags to alllow use of @main in single-source-file executable modules

Tests/FunctionalTests/MiscellaneousTests.swift
This test sometimes fails due to what seem to be module rebuilding issues.  The diagnostics are only shown if the test fails; they don't pollute the regular output.
=> Add compiler diagnostics to a test that sometimes fails in CI

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub/PartialSolution.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubgrubTests.swift
motivation:
* significant part of package resolution can be spent in the dependency resolver which does not emit events we can use to tell the user what is happening
* a follow up PR would use these new events to emit information when package dependencies are resolved, e.g when running swift package update
chnages:
* define DependencyResolverDelegate
* replace logging in PubgrubDependencyResolver with calling the relevant delegate methods
* add TracingDependencyResolverDelegate which back-fills the existing logging behavior in PubgrubDependencyResolver
* adjust call-sites
=> add delegate to track events from the dependency resolver

Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub/PartialSolution.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/Workspace/Workspace.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubgrubTests.swift
=> [5.5] add delegate to track events from the dependency resolver

Utilities/Docker/docker-compose.yaml
motivation: fixed shared repositories cache between mac and linux using docker
changes: since ~/.swiftpm/cache is a symlink, define the volume mount there instead of the parent directory
=> fix docker SwiftPM cache setup

Fixtures/Miscellaneous/TestDiscovery/Extensions/Package.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Sources/Simple/Simple.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests1.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests2.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests3.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests4.swift, Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Tests/FunctionalTests/TestDiscoveryTests.swift
motivation: less bugs, happier users
changes: modify test discovery code to key of class name rather than blindly iterate over tetst
rdar://58435666
=> fix a bug in test discovery where tests defined in extensions break the discovery

Fixtures/Miscellaneous/TestDiscovery/Extensions/Package.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Sources/Simple/Simple.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests1.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests2.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests3.swift, Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests4.swift, Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Tests/FunctionalTests/TestDiscoveryTests.swift
=> [5.5] fix a bug in test discovery where tests define in extensions break the discovery

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
motivation: predictable output will prevent exessive compiles
changes: sort keys before iterating on them
=> make test discovery generation output predictable

Sources/Commands/SwiftPackageCollectionsTool.swift
Update error message to cover the case when collection is not available (e.g., due to network problems)
rdar://77031755
This replaces https://github.com/apple/swift-package-manager/pull/3426
=> [Collections] Improve error message when package collection download times out

Tests/BuildTests/BuildPlanTests.swift, Utilities/bootstrap
With the version-bump of Yams in https://github.com/apple/swift/pull/36366, Yams `4.0.2` now actually expresses the dependency on Dispatch in its CMake config.
With the current behavior of passing `-Ddispatch_DIR` to its CMake build, we have the following problem on Linux:
- `swift`'s `build-script` installs Dispatch into a just-built toolchain which we use to build SwiftPM, which will contain, among other things, the Dispatch `.swiftmodule`.
- The compiler workspace checkout of `swift-corelibs-libdispatch` also contains a copy of the Dispatch `.swiftmodule`.
Both of these will be found, leading to build failures like:
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-nightly-install/usr/lib/swift/dispatch/module.modulemap:1:8: error: redefinition of module 'Dispatch' …
```
=> [5.4] [Bootstrap] Do not pass `-Ddispatch_DIR` to the Yams CMake build (#3363)

Documentation/PackageCollections.md, Sources/Commands/SwiftPackageCollectionsTool.swift
What we are displaying here are stars, not watchers, so the output should reflect that.
=> Fix CLI output for stars

Sources/Commands/SwiftPackageCollectionsTool.swift
Update error message to cover the case when collection is not available (e.g., due to network problems)
rdar://77031755
This is https://github.com/apple/swift-package-manager/pull/3438 for 5.5.
=> [5.5][Collections] Improve error message when package collection download times out

Sources/Basics/DispatchTimeInterval+Extensions.swift, Sources/Commands/SwiftTool.swift, Sources/PackageGraph/DependencyResolver.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/Workspace.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: when resolving packages, the output is lacking key information about computing the appropriate package version. this can mislead users about what SwiftPM is doing and where the time is spent.
changes:
1. expose willComputeVersion/didComputeVersion on WorkspaceDelegate
2. use willComputeVersion/didComputeVersion in SwiftTool::ToolWorkspaceDelegate to print information about the version computation stage
3. add duration information to WorkspaceDelegate::fetchingDidFinish and WorkspaceDelegate::repositoryDidUpdate
4. print duration infortmation SwiftTool::ToolWorkspaceDelegate about fetching and updating, in addition to computing
5. remove empty delegates since they are potentialy hiding dperecations
6. adjust test
=> improve output when resolving packages

Sources/Build/BuildPlan.swift, Sources/Commands/APIDigester.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SymbolGraphExtract.swift, Tests/CommandsTests/PackageToolTests.swift
This fixes swift package experimental-api-diff, which doesn't need or accept library search path arguments. I also added a small test to avoid regressions in the short term. The motivation here is to begin working towards semantic versioning suggestions for packages when tagging a release.
=> Fix experimental-api-diff command and add a test

Sources/Workspace/InitPackage.swift, Tests/WorkspaceTests/InitTests.swift
Motivation: Fix formatting of the XCTest source file in newly `init`'ed library packages, and include the
`throws` keyword on the example XCTest method as a convenience to users and to promote use of throwing
XCTest methods.
Changes:
- Fix a bug in the formatting of XCTest source files in `InitPackage`, where the closing `"""` string
terminator was outdented one level too far, which resulted in the file contents being indented unnecessarily.
- Include the `throws` keyword on `func testExample()` in the new Library type package template.
- Modify an existing test to validate these improvements.
rdar://77209458
rdar://77209464
=> Fix new package XCTest file formatting and include throws keyword

Sources/Basics/FileSystem+Extensions.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
motivation: use more idiomatic location for SwiftPM config
changes:
* on darwin platforms, use ~/Library/org.swift.swiftpm to store SwiftPM configs, which is more idiomatic
* if idiomatic config directory is different from ~/.swift/config, create a symlink ~/.swift/config -> idiomatic
* add temporary transition code for beta users of 5.5 that may already have ~/.swift/config in place
* refactor and centralize the computation of config directory
* refactor and centralize the computation of cache directory (no functional changes)
=> improve location of config directory

Sources/Workspace/InitPackage.swift, Tests/WorkspaceTests/InitTests.swift
Motivation: Fix formatting of the XCTest source file in newly `init`'ed packages, and include the
`throws` keyword on the example XCTest method as a convenience to users and to promote use of throwing
test methods in XCTests.
Changes:
- Fix a bug in the formatting of XCTest source files in `InitPackage`, where the closing `"""` string
terminator was outdented one level too far, which resulted in the file contents being indented unnecessarily.
- Include the `throws` keyword on `func testExample()` in the new Library type package template.
- Modify an existing test to validate these improvements.
rdar://77209458
rdar://77209464
=> [5.5] Fix new package XCTest file formatting and include throws keyword

Sources/Commands/SwiftPackageTool.swift, Sources/PackageGraph/DependencyMirrors.swift, Sources/PackageGraph/PinsStore.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceConfigurationTests.swift
motivation: mirror urls leak today to package.resolved
changes:
* add storage for "original urls" in the pins store
* pass the mirors to the pins file handler
* transform the url when encoding and decoding the pins store such that the package.resolved file contains the non-mirrored URL but SwiftPM internals work witht mirrored ones
* adjust call-sites
rdar://52529014
rdar://52529011
=> fix package.resolved interplay with mirrors

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/MinimumDeploymentTarget.swift, Sources/PackageLoading/PlatformRegistry.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageModel/Platform.swift, Sources/SPMTestSupport/PIFTester.swift, Sources/Workspace/InitPackage.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/PackageLoadingTests/MinimumDeploymentTargetTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
This adds Mac Catalyst as a support platform, so that a minimum deployment target can be specified and conditional build settings can be configured.
(just like the earlier DriverKit patch)
rdar://60376383
=> Add Mac Catalyst as a supported platform

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/MinimumDeploymentTarget.swift, Sources/PackageLoading/PlatformRegistry.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageModel/Platform.swift, Sources/SPMTestSupport/PIFTester.swift, Sources/Workspace/InitPackage.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/PackageLoadingTests/MinimumDeploymentTargetTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
This adds Mac Catalyst as a support platform, so that a minimum deployment target can be specified and conditional build settings can be configured.
(just like the [earlier DriverKit patch](https://github.com/apple/swift-package-manager/pull/3293))
rdar://60376383
=> [5.5] Add Mac Catalyst as a supported platform

Sources/Basics/CMakeLists.txt, Sources/Basics/SQLiteBackedCache.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Sources/PackageLoading/ManifestLoader.swift, Tests/BasicsTests/SQLiteBackedCacheTests.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift, Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
Motivation:
Currently we use transient in-memory cache for storing GitHub package metadata.
Modifications:
- Add generic `SQLiteBackedCache` in Basics
- Change `ManifestLoader` to use `SQLiteBackedCache`
- Change `GitHubPackageMetadataProvider` to use `SQLiteBackedCache`
- Adjust tests
=> [Collections] Use persistent cache for GitHub package metadata

Sources/Commands/SwiftPackageTool.swift, Sources/PackageGraph/DependencyMirrors.swift, Sources/PackageGraph/PinsStore.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceConfigurationTests.swift
=> [5.5] fix package.resolved interplay with mirrors

Sources/Basics/CMakeLists.txt, Sources/Basics/SQLiteBackedCache.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Sources/PackageLoading/ManifestLoader.swift, Tests/BasicsTests/SQLiteBackedCacheTests.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift, Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/3441 for 5.5.
=> [5.5][Collections] Use persistent cache for GitHub package metadata (#3441)

Sources/Workspace/InitPackage.swift
This makes it easier to use it from clients which makes for a better default experience.
rdar://77110377
=> Make the struct in the default template public

Sources/Basics/SQLiteBackedCache.swift
`DELETE` statement doesn't need `LIMIT` and it's breaking CentOS7 builds.
rdar://77275629
=> Fix SQL syntax error

Sources/PackageCollections/PackageCollections+Configuration.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
=> [Collections] Auth tokens need to be mutable

Sources/Workspace/InitPackage.swift
This makes it easier to use it from clients which makes for a better default experience.
rdar://77110377
(cherry picked from commit fae7303169891815682c4088b5dae83d2f7bcdd7)
=> [5.5] Make the struct in the default template public

Sources/PackageLoading/PackageBuilder.swift
We also need Mac Catalyst to fall back to iOS in PackageBuilder
rdar://60376383
PR for release/5.5: #3460
=> BuildSettingCondition should offer a Mac Catalyst condition (amend)

Sources/PackageLoading/PackageBuilder.swift
We also need Mac Catalyst to fall back to iOS in PackageBuilder
rdar://60376383
PR for main: #3459
=> [5.5] BuildSettingCondition should offer a Mac Catalyst condition (amend)

Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Motivation:
In `AuthTokenType` `host` is the GitHub host (e.g., `github.com`), but when we look up auth token we use the GitHub API host (e.g., `api.github.com`). As a result the auth tokens are not used.
Modification:
Look up auth tokens with GitHub host by removing `api.` prefix.
rdar://77293200
=> [Collections] Fix auth token lookup

Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
Fix the preferred lookup location for resource bundles.
The preferred lookup location for resource bundles is next to the binary that is executed. This was previously achieved by searching next to `Bundle.main.bundlePath`. [This change](https://github.com/apple/swift-package-manager/pull/2972/files#diff-13eb4b18e8a4f2de8467dae905be6bdc133208159aded4aa6dbb6a03be21c6bdL584) moved the execution of `Bundle.main` outside of the generated bundle accessor code - and thus uses `Bundle.main` of the compilation process.
Move the `Bundle.main` call back to the generated code.
The preferred resource bundle lookup will again be the location of the compiled binary.
Fixes https://bugs.swift.org/browse/SR-14555.
=> Fix resource bundle lookup

Package.swift, Sources/Commands/Options.swift, Sources/Commands/SwiftBuildTool.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftRunTool.swift, Sources/Commands/SwiftTestTool.swift, Tests/CommandsTests/PackageToolTests.swift
Depends on this [PR](https://github.com/apple/swift-argument-parser/pull/300)
Fixes `swift package init --help` to only show help for `init`
This is a major UI improvement as it allows the user to focus on the help that is solely relevant to `init`, and not get overwhelmed with other options.
rdar://76116106
=> Fix swift package init --help printout

Package.swift
This switches the branch dependencies for `swift-tools-support-core`, `swift-llbuild`, and `swift-driver` (as we do for every release branch).  This will be come more important as `main` starts to diverge from `release/5.5`.
This depends on https://github.com/apple/swift-driver/pull/626
=> Change branch dependencies on TSC, LLBuild, and SwiftDriver from `main` to `release/5.5`

Fixtures/DependencyResolution/External/XCFramework/Foo.xcframework/Info.plist, Fixtures/DependencyResolution/External/XCFramework/Foo/Foo.swift, Fixtures/DependencyResolution/External/XCFramework/Package.swift, Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift, Tests/CommandsTests/PackageToolTests.swift
motivation:
* netrc functionality is useful on all platforms
* underlying functionality is avaialbe via https://github.com/apple/swift-tools-support-core/pull/210
changes:
* remove platforms restructions where appropriate
* add test fixute that actually exercises the netrc parsing logic
* adjust tests to run on all platforms
=> enable netrc on non-darwin platforms

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Make sure errors returned by `JSONPackageCollectionProvider` have good string representation.
rdar://77530631
=> [Collections] Improve error handling

Package.swift, Sources/PackageDescription/CMakeLists.txt, Sources/PackageDescription/LanguageStandardSettings.swift, Sources/PackageDescription/PackageDependency.swift, Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/PackageRequirement.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackagePlugin/CMakeLists.txt, Sources/Workspace/DefaultPluginScriptRunner.swift, Sources/Xcodeproj/pbxproj.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Utilities/bootstrap
Replace the compile-time conditionals in PackageDescription with availability annotations, and build a single runtime library that can be used for all package tools versions.
This is preparatory work for https://github.com/apple/swift-package-manager/pull/3431 and will also make it easier for clients of libSwiftPM, since only one version of PackageDescription needs to be built.
The runtime support library for PackageDescription is currently built twice:  once for SwiftPM 4.0 and another time for 4.2 and later.  This is done using compile-time conditionals, producing two separate binaries in the file system.  Code in the manifest loader chooses between them based on the declared tools version of the package.
Having two versions of the library has several problems:
- it makes the build …
=> Unify the two versions of PackageDescription into a single one using availability annotations instead of compile conditionals

Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/Target.swift
Reverts apple/swift-package-manager#3404
Reverting because it this does have impact on existing manifests,  see: apple/swift-standard-library-preview#4
=> Revert "Use implementation-only imports"

Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Motivation:
Test crashed in CI: https://github.com/apple/swift-package-manager/pull/3478#issuecomment-834153469
Modification:
Use `ThreadSafeKeyValueStore` to as backing store of `authTokens`.
=> Fix PackageCollectionsTests.testUpdateAuthTokens

Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
`getPackageMetadata` requires the package being looked up to exist in at least one imported package collection. It tries to fetch additional metadata from third-party providers such as GitHub and combine it with local collection data. If GitHub APIs yield no result or fail, the error is silently ignored and the code proceeds with returning collection data only. Some of these GitHub API errors can be prevented--e.g., the rate-limit for authenticated requests is much higher than unauthenticated ones (5000 vs 60), so if we expose these GitHub errors, the caller can take preventive actions.
Modifications:
Add `provider: PackageMetadataProviderContext?` to `PackageMetadata` (which is a tuple type), which includes information such as `AuthTokenType` and whether the corresponding …
=> [Collections] Add information about metadata provider to getPackageMetadata result

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
motivation: silent crashes, confused uers
changes:
* change the order in swiftCompilerOutputParser such that print the stdout happens before any parsing attenpts are made
* constraint the parsing attempts to output < 10k, since otherwise they struggle to complete
=> fix silent crash when output from compiler is too large

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
=> [5.5] fix silent crash when output from compiler is too large

.mailmap
I've previously used a silly pseudonym in my git commits. I'm now mapping it to my real name.
=> [Gardening] Update information for 冀卓疌

Sources/SourceControl/GitRepository.swift
Enable symlink support explicitly
This is a cherry-pick of commit 5f80bd7 from `main`.
enable git symlink support for Windows
pass core.symlinks=true to git clone operations
repositories cloned by SwiftPM will have `core.symlinks` set to `true`
=> [5.4] Enable symlink support explicitly

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
All the search methods in `SQLitePackageCollectionsStorage` start by fetching a subset or all of the collections from database. This is because prior to using FTS, search was done directly on the `Collection` instances. In case of FTS, we can optimize things by:
1. Fetching collections from the database iff there are matches. i.e., return `NotFoundError` or empty result early
2. Fetching only collections where matches are found
Modifications:
Rearrange logic in search methods to do the optimizations described above.
Related to rdar://77873780
=> [Collection] Optimize collection fetch in search methods

Sources/Commands/Options.swift, Sources/Commands/SwiftTool.swift
cherry picked from commit 09ec01b525236ce30ec2fb969e09ce0ab3e06b91
#3469
=> [5.5] Update index store to enum 

Tests/CommandsTests/BuildToolTests.swift
https://github.com/apple/swift-package-manager/pull/3496 for 5.5
=> [5.5] Update BuildToolTests.testBuildCompleteMessage

Sources/Build/BuildDelegate.swift, Sources/Build/BuildOperation.swift, Tests/CommandsTests/BuildToolTests.swift
brings #3313, #3352, #3353 to 5.4
rdar://77669218
=> [5.4] fix "build complete" message

Sources/Build/BuildDelegate.swift
=> [5.4] fix silent crash when output from compiler is too large

Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
Package metadata returned by GitHub API may contain duplicate entries for the same tag. e.g., https://github.com/vapor/postgres-nio releases 1.5.0 and 1.5.1. This causes `getPackageMetadata` API to crash.
Modification:
Dedupe versions/tags when we construct dictionary from GitHub package versions array.
=> [Collections] Dedupe package versions in GitHub metadata

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
motivation: with trie genration now running on lower priority, a race was exposed where the operation may start after the storage already was closed
changes: guard on state before trying to execute a statement on the connection since it may be terminated
=> fix race condition when trie generation thread may be invoked after storage has been closed

Sources/Commands/SwiftRunTool.swift, Sources/Workspace/UserToolchain.swift
If -debugger is passed, launch a SwiftPM-built executable in LLDB
Simplify the debugging process a but so that developers don't need to find the exact path to the built product when starting an LLDB session.
- Add a new mode to swift-run which launches LLDB with the appropriate executable path and arguments
Passing -debugger to swift-run will let users debug an executable
=> Add a -debugger option to swift-run to start an executable in a debugger session

Sources/PackageCollections/PackageCollections.swift
https://github.com/apple/swift-package-manager/pull/3504 for 5.5
=> [5.5][Collections] Dedupe package versions in GitHub metadata (#3504)

Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: some users reported an edge case where the state is reset but the directory lingers, so that the secondary attempt to download and extract the ginary depedency fails
changes:
* extract the downloaded archive to a temporary location
* ensure the destination does not exist prior to moving it from the temporary extraction location to the desired location 
* adjust confusing (test only) function name 
rdar://75975702
rdar://77011310
=> fix an edge case where binary artifacts have already been downloaded and linger or disk, causing secondary attempt to fail

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
=> [5.5] run trie generation thread with QOS set to background

Documentation/RegistryDraft.md
This PR includes the following changes to the [draft registry specification](https://github.com/apple/swift-package-manager/blob/main/Documentation/RegistryDraft.md) in response to feedback for [SE-0292](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md). 
- Make `url` field optional in release objects, as discussed in https://github.com/apple/swift-evolution/pull/1319#issuecomment-834394168
=> Incorporate SE-0292 feedback into RegistryDraft

Sources/Commands/SwiftPackageCollectionsTool.swift
Motivation:
The collection API implementation fetches additional package metadata via GitHub APIs but we aren't showing all of it in the CLI.
Modifications:
Add license and languages. Reorder line items. e.g., the updated output of `describe https://github.com/apple/swift-nio`:
```
Description: Event-driven network application framework for high performance protocol servers & clients, non-blocking.
Available Versions: 2.29.0, 2.28.0, 2.27.0, 1.14.2, 1.14.1, 1.14.0
Readme: https://raw.githubusercontent.com/apple/swift-nio/main/README.md
License: Apache-2.0 (https://raw.githubusercontent.com/apple/swift-nio/main/LICENSE.txt)
Authors: weissi, normanmaurer, Lukasa, compnerd, glbrntt, PeterAdams-A, tomerd, tigerpixel, kevinclark, fabianfett, BasThomas, Davidde94, gwynne, helje5, ktoso, …
```
=> [Collections] Include more package metadata in CLI output

Documentation/PackageCollections.md, Sources/Commands/SwiftPackageCollectionsTool.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/3439 and https://github.com/apple/swift-package-manager/pull/3509 for 5.5
rdar://77533967
=> [5.5][Collections] Update CLI output for 'describe'

Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Motivation:
With https://github.com/apple/swift-package-manager/pull/3505, the code does `preconditionFailure` when trying to execute DB statement after connection is disconnected. In `populateTargetTrie` we check connection state before calling `executeStatement`, but it's still possible for storage to close _after_ the check but _before_ `executeStatement`. This might have caused rdar://78513692.
Modifications:
- Throw error instead of `preconditionFailure`
- Unrelated: `GitHubPackageMetadataProvider.configuration` doesn't need to be var
=> [Collections] Throw error instead of preconditionFailure after storage closed

Sources/Workspace/InitPackage.swift
This PR adds `.netrc` to the `.gitignore` file in the new project template.
As discussed in https://github.com/apple/swift-evolution/pull/1319, a user may inadvertently expose credentials by checking in their project's `.netrc` file. Adding this entry to the `.gitignore` file in the new project template significantly minimizes the possibility of the user leaking credentials in the future.
```diff
+ .netrc
```
After this change, all future projects created by running `swift package init` will default to ignoring `.netrc` files.
Existing packages will be unaffected.
=> Add .netrc to default .gitignore

Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
https://github.com/apple/swift-package-manager/pull/3512 for 5.5
=> [5.5][Collections] Throw error instead of preconditionFailure after storage closed

Sources/PackageCollections/PackageCollections+Validation.swift, Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift
Motivation:
Currently packages in a collection can have `versions` array be empty. Can't remember if this was intentional but a package that has no versions is not very useful.
Modification:
Update validation to fail when `package.versions` is empty.
=> [Collections] Don't allow package.versions to be empty

Sources/PackageCollections/PackageCollections+Validation.swift, Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift
https://github.com/apple/swift-package-manager/pull/3515 for 5.5
=> [5.5][Collections] Don't allow package.versions to be empty

Sources/Commands/SwiftTool.swift
When mixing a newer compiler which does the implicit concurrency import with an older SDK that doesn't have a Concurrency module, manifest compilation is emitting warnings right now. This adds an extra flag to disable the implicit import if the flag is supported by the compiler in use.
rdar://78032108
=> Avoid warnings when using SDKs without a Concurrency module

Sources/Build/BuildPlan.swift
The new driver does not support Windows, yet, so the check for `supportedFrontendFlags` needs to be conditional to non-Windows.
=> Avoid calling `supportedFrontendFlags` on Windows

Package.swift
The `SwiftPMDataModel` target can't be linked statically at the moment, because it uses `type: .dynamic` explicitly in the `Package.swift` manifest file. Dynamic linking makes distribution of CLI tools relying on SwiftPM much harder, since you have to redistribute this dynamic libraries too, with little to no benefit.
New `SwiftPMDataModel-auto` target is added, which uses the same approach as the `SwiftPM-auto` target of not specifying the linking type explicitly.
Tools that utilize the SwiftPM package can use the `SwiftPMDataModel-auto` target for static linking instead of `SwiftPMDataModel`.
=> Allow static linking of the SwiftPMDataModel target

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
Motivation:
`PackageCollectionsStorageTests/testPopulateTargetTrie` gets stuck sometimes because `targetTrieReady` is already set and `callback` is only invoked in the body of `memoize`.
https://ci.swift.org/job/oss-swift-package-ubuntu-20_04-aarch64/79/console
Modifications:
Rearrange logic in `populateTargetTrie` such that `callback` is invoked outside of `memoize` body.
Also, add `populateTargetTrieLock` to prevent more than one thread from calling `memoize` at the same time.
=> [Collections] testPopulateTargetTrie sometimes gets stuck

Utilities/bootstrap
The bootstrap script needs to build the PackageDescription and PackagePlugin runtime support libraries universal when cross-compiling.  This PR builds on https://github.com/apple/swift-package-manager/pull/3464, so it will be easier to review that PR first.
Even when invoking the bootstrap script with flags to build universal for macOS x86_64 and arm64, the PackageDescription and PackagePlugin libraries ended up single-architecture.  This is because the bootstrap script copied them from the CMake-built artifacts instead of the swiftpm-built artifacts.
PR https://github.com/apple/swift-package-manager/pull/3464 resolves the complication of PackageDescription having both a 4.0 and a 4.2 variant.
- in the bootstrap script, build SwiftPM so that Swift interface files are emitted
- consolidate …
=> Bootstrap script needs to build PackageDescription and PackagePlugin universal

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
https://github.com/apple/swift-package-manager/pull/3522 for 5.5
=> [5.5][Collections] testPopulateTargetTrie sometimes gets stuck

Package.swift, Sources/PackageDescription/CMakeLists.txt, Sources/PackagePlugin/CMakeLists.txt
Because PackageDescription unintentionally exports Foundation (for which a fix was attempted but then reverted after it broke some packages — see SR-14718), we can only enable library evolution on Darwin platforms.
- conditionalize passing of `-enable-library-evolution` on the macOS platform
rdar://78827075
=> [SR-14718] Only pass `-enable-library-evolution` for PackageDescription and PackagePlugin on macOS

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
rdar://78872613
`SQLitePackageCollectionsStorage.useSearchIndices` is set in `createSchemaIfNecessary`, which is invoked only along with a database operation. Since search methods (e.g., `searchPackages`) check `useSearchIndices` first thing, it's possible that `createSchemaIfNecessary` hasn't been called yet and as a result `useSearchIndices` defaults to `false`, causing a different code path to get executed.
Modification:
Make sure `createSchemaIfNecessary` is called before reading `useSearchIndices`.
=> [Collections] Fix useSearchIndices race

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
https://github.com/apple/swift-package-manager/pull/3529 for 5.5
=> [5.5][Collections] Fix useSearchIndices race

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
Motivation:
rdar://78939220
`SQLitePackageCollectionsStorage.populateTargetTrie` is always called in the initializer and to be completed by a background thread. Looks like the crash could be caused by `populateTargetTrie` being run while `SQLitePackageCollectionsStorage` gets destroyed as part of `PackageCollections` deallocation.
Modifications:
Add option in `SQLitePackageCollectionsStorage.Configuration` to skip calling `populateTargetTrie` in tests to avoid the race between db destruction and `populateTargetTrie`. Not all tests need storage or make use of `populateTargetTrie`, and it's caused many crashes in CI already. We have added traps for db connection state but that doesn't seem to be enough.
Another approach is probably to use `withExtendedLifetime` in `testUpdateAuthTokens`, …
=> [Collections] PackageCollectionsTests.testUpdateAuthTokens sometimes causes signal 11

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/Utility.swift
https://github.com/apple/swift-package-manager/pull/3534 for 5.5
=> [5.5][Collections] PackageCollectionsTests.testUpdateAuthTokens sometimes causes signal 11

Fixtures/Miscellaneous/LibraryEvolution/Package.swift, Sources/Build/BuildPlan.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
Enable swift module interfaces for targets that are compiled with `enable-library-evolution`.  This supports the intent of building a module that way.
There isn't currently a way for package authors to enable library evolution or module interfaces from the package manifest.  They can pass `-enable-library-evolution` in their unsafe flags, but because `-emit-module-interface` requires a path parameter, it isn't something that can be set in the manifest.
This change enables swift module interfaces when a library does specify `-enable-library-evolution` in its unsafe flags, supporting the semantic intent of providing that flag.
This is useful in the general case, but is most immediately needed to generate .swiftinterface files for https://github.com/apple/swift-package-manager/pull/3431.
- …
=> Enable swift module interfaces if the package author enables library evolution via unsafe flags

Package.swift, Sources/Build/BuildPlan.swift, Sources/SPMTestSupport/Resources.swift
cherry-pick from b2e73caa7d6ee70308bb72c74c87185529140cff
=> [5.5] Check what compiler flags are available (#3398)

Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/Target.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3476
=> [5.5] Revert "Use implementation-only imports (#3404)"

Utilities/bootstrap
This reverts the bootstrap changes and goes back to copying the CMake-built libraries instead of the SwiftPM-built ones.  This means that they will be thin on macOS, built only for the architecture of the host on which they were built.  This is temporary until the Xcode that is used on the builders is new enough to have the XCBuild support needed for emitting Swift module interfaces.
This caused toolchain build failures.
Revert the part of bootstrap that copies the PackageDescription and PackagePlugin so they again come from CMake.  It does not do a wholesale revert of unrelated changes, since other diffs have stacked on them.
PackageDescription and PackagePlugin will again be built thin on macOS, since they will come from the CMake bootstrap build, as before.  But they will have the …
=> Revert the bootstrap changes to copy the SwiftPM-built universal PackageDescription and PackagePlugin libraries

Sources/Build/BuildOperation.swift
If linking `oldBuildPath` fails, SwiftPM will emit a warning instead of an error.
Symlinking `oldBuildPath` is not a vital step of `swift build`, but emitting an error will depress the `run` and `test` commands. This largely troubled Windows users, since symlinking requires elevated privileges on Windows.
Codes of linking `oldBuildPath` is now wrapped with `do-catch` to capture the error and change it into a warning.
If linking `oldBuildPath` fails, SwiftPM will emit a warning instead of an error.
=> Change symlink error to warning

Sources/Commands/SwiftPackageCollectionsTool.swift
An exceedingly minor grammar fix: conditionally pluralize the `package-collection refresh` response based on the number of collections that were refreshed.
Use correct grammar in user-facing messages.
Changed the output of `package-collection refresh` to say "Refreshed _n_ configured package collection[s]." instead of always pluralizing "collections".
If only one collection is refreshed, the output of this command will now say "collection" instead of "collections".
=> Fix pluralization of 'package-collection refresh' text

Sources/PackageCollections/PackageCollections+Storage.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageCollectionsModel/Formats/v1.md
Motivation:
rdar://79069839
To distinguish between package vs. collection URL, we first search for it as if it were a package URL. The package search, however, is done using `PackageIdentity` and not the actual URL itself. The problem with identity is that it only uses the last URL path component, so `bar/foo` and `baz/foo` would end up with the same identity `foo`.
Modifications:
Update `findPackage` to allow multiple results since a package identity (the way it is) can be associated with multiple repository URLs. Caller of `findPackage` should then filter out packages by repository URL if needed.
=> [Collections] 'describe' package matching is too loose

Package.swift, Sources/PackageDescription/CMakeLists.txt, Sources/PackageDescription/LanguageStandardSettings.swift, Sources/PackageDescription/PackageDependency.swift, Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/PackageRequirement.swift, Sources/PackageDescription/Target.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackagePlugin/CMakeLists.txt, Sources/Workspace/DefaultPluginScriptRunner.swift, Sources/Xcodeproj/pbxproj.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift, Utilities/bootstrap
This is a SwiftPM 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3464.  Some of the fixes we still want to do in 5.5 (such as building the toolchains with universal binaries for PackageDescription and PackagePlugin on Darwin) require this change (since SwiftPM cannot currently build the same target in two different ways, i.e. cannot product a 4.0 and 4.2 PackageDescription).
=> [5.5] Unify the two versions of PackageDescription into a single one using availability annotations instead of compile conditionals

Documentation/Contributing.md
The instructions have moved from the main `README` to a separate "get started" guide.
=> [Doc] Update link to dependency installation instructions

Sources/PackageCollections/PackageCollections+Storage.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageCollectionsModel/Formats/v1.md
https://github.com/apple/swift-package-manager/pull/3543 for 5.5
=> [5.5][Collections] 'describe' package matching is too loose

Sources/PackageDescription/Target.swift
This was left over after unifying the two flavors of PackageDescription.
Because the condition was `#if !PACKAGE_DESCRIPTION_4`, there is actually no semantic difference, but is should be cleaned up.
=> Remove a remaining stray reference to PACKAGE_DESCRIPTION_4

Sources/PackageDescription/Target.swift
This change makes a couple of underscored properties of `Target` private & adds a missing `@availability` attribute.
`Target._url` & `Target._checksum` shouldn't be visible in the module interface of `PackageDescription`, since they are implementation details of `Target`. The user-facing properties do not have an underscore and are named `Target.url` & `Target.checksum`.
The `public` access modifier was probably a typo.
Also `Target.url` was introduced in SwiftPM 5.3, but was missing the corresponding `@availability` attribute.
Replaced `public` with `private` & added an `@availability` attribute.
Underscored properties are no longer exposed in the public module interface of `PackageDescription`.
=> PackageDescription: make underscored properties private

Sources/PackageDescription/Target.swift
Since the condition was `#if !PACKAGE_DESCRIPTION_4`, there is actually no semantic difference. (#3549)
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3549.
(cherry picked from commit 27d72819e13e70cd14b7918489f53008741cb3ce)
=> [5.5] Remove a remaining stray reference to PACKAGE_DESCRIPTION_4

Package.swift, Sources/SPMTestSupport/Resources.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/WorkspaceTests/InitTests.swift
In https://github.com/apple/swift-package-manager/pull/3398, we introduced a way to check whether a compiler supports specific flags. This functionality relies on the Swift Driver and therefore the `Build` module which isn't available on all platforms and therefore shouldn't be used by `SPMTestSupport`. 
For example, llbuild does not currently work on iOS and the Swift Driver doesn't support Windows at this time.
Moreover, we should also not proliferate use of the `Build` module to parts of the code base that should be separate from an actual build process, in order to keep the separation between the full SwiftPM library and the data model variant.
This change removes the dependency and replaces the check in tests with a check for the 5.5 Swift compiler instead.
Tests can be compiled and …
=> `SPMTestSupport` should not depend on `Build`

Package.swift, Sources/SPMTestSupport/Resources.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/WorkspaceTests/InitTests.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3551
=> [5.5] `SPMTestSupport` should not depend on `Build`

Sources/PackageCollections/PackageCollections+CertificatePolicy.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift, Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionSourceCertificatePolicyTests.swift, Tests/PackageCollectionsTests/Utility.swift
https://github.com/apple/swift-package-manager/pull/3530 for 5.5
=> [5.5][Collections] Support multiple cert pinning configs per domain

Tests/PackageLoadingTests/PD4_2LoadingTests.swift
This test is failing on the aarch64 CI for unknown reasons, we will skip it for now until we can fix it. Since that is targetting Linux, we only skip the test there for now.
=> Skip `testCacheInvalidationOnEnv` for now

Sources/PackageLoading/ManifestLoader.swift
This is a follow-on to https://github.com/apple/swift-package-manager/pull/3464 that makes the current SwiftPM able to work with libraries from an older toolchain.
This makes the use of the Manifest API directory (the directory in which PackageDescription.dylib and its interface is located) more robust, so that it works with mismatching toolchains.  This is a little tricky to unit-test from inside the codebase, since it involves having an old toolchain compared with the expected one.  Existing unit tests make sure there are no regressions.
No change in behavior when the SwiftPM and the toolchain libraries match.
=> Make the lookup of the PackageDescription dylib fall back on the versioned location if needed

Sources/Commands/Describe.swift, Tests/CommandsTests/PackageToolTests.swift
While `swift package describe` had an entry for `target_dependencies` in the output of each target, it omitted `product_dependencies`.
Currently (while we still have the distinction between products and targets in the SwiftPM package model) we should include both kinds of dependencies in the package description output format.
- add product dependencies to the per-target outputs (because of how this is done, the same code automatically works for both JSON and plain text output)
=> [SR-14782] `swift package describe` is omitting product dependencies from per-target output

Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Motivation:
`listCollections` has optional `identifiers` that if specified, only those collections are supposed to be fetched. However, the current implementation always fetches all configured collections because the logic for determining "missing" collections is flawed.
Modification:
Fix logic such that `listCollections` returns all or a subset of collections depending on `identifiers` param.
=> [Collections] listCollections always returns all configured collections

Package.swift
Simplify the deployment targets on Darwin platforms, setting the minimum deployment target to macOS 10.15 and iOS 13 or later on Darwin platforms.  The environment variables were needed during a transitional phase, and SwiftPM already required macOS 10.15 or later on macOS.  Note that non-Darwin platforms are unaffected.
This simplifies the logic while keeping the same macOS 10.15 dependency, and aligns SwiftPM with the ToolsSupportCore requirements in https://github.com/apple/swift-tools-support-core/pull/225.
See comment in https://github.com/apple/swift-package-manager/pull/3552#issuecomment-861841741
Set macOS 10.15 and iOS 13 as minimum deployment targets.
No change for macOS, v13 required for iOS.
=> Simplify minimum deployment target on Darwin platforms (still requiring macOS 10.15+, adding iOS 13+)

Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
https://github.com/apple/swift-package-manager/pull/3565 for 5.5
=> [5.5][Collections] listCollections always returns all configured collections

Sources/PackageLoading/ManifestLoader.swift
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3560.
This makes the use of the Manifest API directory (the directory in which PackageDescription.dylib and its interface is located) more robust, so that it works with mismatching toolchains.  This is a little tricky to unit-test from inside the codebase, since it involves having an old toolchain compared with the expected one.  Existing unit tests make sure there are no regressions.
(cherry picked from commit 7e0f5e627c4d68dc05593e1b2ca8698bc6b20d51)
=> [5.5] Make the lookup of the PackageDescription dylib fall back on the versioned location if needed

Tests/PackageGraphTests/PubgrubTests.swift
This PR fixes 2 places where `DependencyGraphBuilder.serve` mishandles `dependencies` with duplicate keys (`product`s). 
1. [One of the callers] of the function passes in a dictionary literal with duplicate keys. Although the logic in this function suggests that duplicate keys are allowed, `TSCBasic.OrderedDictionary` preserves only [the final] of all duplicate keys' values in a dictionary literal. In addition, with #3533, Swift Collections' `OrderedDictionary` [traps] on duplicate keys. `KeyValuePairs` seems like the right replacement that allows duplicate keys.
2. Because of the duplicate keys, when `dependencies` are iterated, the same `product` can appear more than once, each time with possibly different `filteredDependencies`. In each iteration, the `filteredDependencies` associated …
=> [PubgrubTests] Handle duplicate product keys in `DependencyGraphBuilder.serve`

Sources/Build/BuildOperation.swift
If linking `oldBuildPath` fails, SwiftPM will emit a warning instead of an error. (Cherrypicked from #3490)
Symlinking `oldBuildPath` is not a vital step of `swift build`, but emitting an error will depress the `run` and `test` commands. This largely troubled Windows users, since symlinking requires elevated privileges on Windows.
Codes of linking `oldBuildPath` is now wrapped with `do-catch` to capture the error and change it into a warning.
If linking `oldBuildPath` fails, SwiftPM will emit a warning instead of an error.
=> [5.5] Change symlink error to warning

Sources/Build/BuildPlan.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3521
=> [5.5] Avoid calling `supportedFrontendFlags` on Windows

Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift
https://github.com/apple/swift-package-manager/pull/3566 for 5.5
=> [5.5][Collections] Add listPackages API

Utilities/bootstrap
This seems like a leftover from the integrated TSC days. TSC has its own CI these days, so this shouldn't be necessary anymore.
Opening as a draft first, because we may need to adjust `build-script` to actually test TSC independently of SwiftPM's `bootstrap`.
=> Do not test TSC in `bootstrap`

Sources/Commands/SwiftTool.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3517
=> [5.5] Avoid warnings when using SDKs without a Concurrency module

Fixtures/Miscellaneous/TestableExe/Package.swift
We should be using .executableTarget, not .target, for executables.
=> Fix warnings generated when testing.

Utilities/bootstrap
This enables cross-compiling SPM for other hosts, such as Android.
In addition to `--cross-compile-hosts`, add a new bootstrap flag, `--cross-compile-config`, that will pass in a JSON file with the destination cross-compilation flags.
SPM can be cross-compiled for another OS, with Android as the first example.
=> Android: add cross-compilation configuration file flag

Sources/Basics/DispatchTimeInterval+Extensions.swift, Sources/Commands/SwiftTool.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageLoading/PlatformRegistry.swift, Sources/PackageModel/Platform.swift, Sources/SPMBuildCore/BinaryTarget+Extensions.swift, Sources/SPMBuildCore/BuildParameters.swift, Tests/PackageCollectionsTests/Utility.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Utilities/bootstrap
Pepper in the right conditionals throughout.
The unversioned triple issue is still necessary for the bootstrap script
(and only the bootstrap script) which we will deal with separately.
Permit SPM to build on this platform.
* `Sources/Basics/DispatchTimeInterval+Extensions.swift`: add the platform to the `#if` to make the extension available
* `Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift`: add the platform to the switch -- likely not required to build but we might as well extend this now we are enabling the platform.
* `Sources/PackageDescription/SupportedPlatforms.swift`: add the static var for the platform. Please let me know here if the 5.4 availability annotation needs revision here.
* `Sources/PackageLoading/PlatformRegistry.swift`: add to the known …
=> Basic OpenBSD support.

Tests/BasicsTests/SandboxTests.swift
Using `XCTSkipIf(true)` avoids build warnings on Linux.
=> Fix warnings in `SandboxTests`

IntegrationTests/Tests/LinuxMain.swift, Tests/LinuxMain.swift, Utilities/Docker/docker-compose.yaml, Utilities/bootstrap, Utilities/build-using-self
We have made the flag default a while ago, so we can assume that it'll be passed as default.
=> Do not require `--enable-test-discovery` anymore on Linux

Utilities/bootstrap
Restores the bootstrap script changes that were partially reverted in https://github.com/apple/swift-package-manager/pull/3540, and updates the bootstrap script to filter out the .swiftmodule files on Darwin, leaving just .swiftinterface.
In order to build universal toolchains, the bootstrap script was changed to install the PackageDescription and PackagePlugin libraries built by SwiftPM rather than those built by CMake.  When building for more than one architecture, SwiftPM uses XCBuild, but apparently only Xcode versions such as those used on the bot don't properly support the build setting to emit Swift module interface files.
Revert the changes to copy the installed PackageDescription and PackagePlugin from the CMake-built ones, so that they again come from the SwiftPM-built ones. …
=> Restore the bootstrap script changes to install the SwiftPM-built PackageDescription and PackagePlugin libraries

Sources/Commands/APIDigester.swift, Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/APIDiffTests.swift
Add a --breakage-allowlist-path flag to allow ignoring specified breaking changes when running experimental-api-diff
Sometimes, it's beneficial to be able to ignore certain API breaking changes when perfect API compatibility isn't necessary.
- Adds a new --breakage-allowlist-path flag which is forwarded directly to the api digester's diagnose-sdk action. If the flag isn't specified, the tool will also check to see if api-breakage-allowlist.txt exists at the package root and use that.
Users can choose to ignore certain API-breaking changes when running comparisons
=> [APIDiff] Support forwarding breakage allowlists to the api digester

Sources/Workspace/InitPackage.swift
This PR adds `.swiftpm/config` to the `.gitignore` file in the new project template.
As discussed in SE-0292, a user may inadvertently reveal the existence of a private registry or expose hardcoded credentials by checking in their project's `.swiftpm/config` file or directory. Adding this entry to the `.gitignore` file in the new project template significantly minimize the possibility of the user leaking credentials in the future.
```diff
+ .swiftpm/config
```
After this change, all future projects created by running swift package init will default to ignoring `.swiftpm/config` files (which covers both the file `.swiftpm/config` if it's a file, and the contents of the directory if `.swiftpm/config/` is a directory).
Existing packages will be unaffected.
=> Add .swiftpm/config/registries.json to default .gitignore

Utilities/bootstrap
This is a cherry-pick of 38df7c3.
```
In addition to '--cross-compile-hosts', add a new bootstrap flag, '--cross-compile-config', that will
pass in a JSON file with the destination cross-compilation flags.
```
=> [5.5] Android: add cross-compilation configuration file flag

Sources/Commands/APIDigester.swift, Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/APIDiffTests.swift
Add flags that can be used to manage API baselines
In some environments, it can be useful to check API baseline files into source control, those of tagged versions for example.
- `--baseline-dir` can be used to choose a directory to emit API baselines in
- `--regenerate-baseline` wil cause the tool to ignore preexisting baseline files
It's now possible to choose a directory to emit baseline file to and then check them in
=> [APIDiff] Add baseline management flags

Tests/CommandsTests/APIDiffTests.swift
Enable the api diff tests on Linux once https://github.com/apple/swift/pull/37703 is merged
Make sure experimental-api-diff is works and is tested on Linux
This PR just enables tests, the cross-platform fix is in https://github.com/apple/swift/pull/37703
API diff tests will run on all platforms
=> [APIDiff] Enable tests on non-Darwin

Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Empty arrays of unsafe flags are currently only disallowed using an assertion, which is compiled out for release builds.  The result is that some packages fail assertions when run in debug mode even though they work fine in a tools release.  There is no reason to disallow this, and it's useful when programmatically building up lists of unsafe flags.
=> Allow empty arrays of unsafe flags (already allowed in practice; this removes a debug assertion and adds a test)

Tests/CommandsTests/APIDiffTests.swift
Temporarily disable failing APIDiff tests to unblock builds
Some APIDiff tests are failing on latest main.
Temporarily disable to unblock builds until proper fixes. 
Unblock builds.
=> Temporarily disable failing APIDiff tests to unblock builds

Fixtures/Miscellaneous/LibraryEvolution/Package.swift, Package.swift, Sources/Build/BuildPlan.swift, Sources/PackageDescription/CMakeLists.txt, Sources/PackagePlugin/CMakeLists.txt, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Utilities/bootstrap
This is the 5.5 cherry-pick of a sequence of changes to build PackageDescription and PackagePlugin universal on macOS platform.  SwiftPM switches to the XCBuild build system when building universal, and this PR includes the necessary follow-up changes to make that work.
This includes 5.5 cherry-picks of the changes in:
https://github.com/apple/swift-package-manager/pull/3431
https://github.com/apple/swift-package-manager/pull/3526
https://github.com/apple/swift-package-manager/pull/3528
each as a separate commit containing the original commit hash from which it was cherry-picked.
This PR builds on top of the PR https://github.com/apple/swift-package-manager/pull/3492, which is kept as a separate PR since it is for a different issue.
The three are put up as one PR since they all are steps …
=> [5.5] Build PackageDescription and PackagePlugin universal on macOS platform

CONTRIBUTING.md
`bootstrap` needs TSC, but it's missing from the instructions in `CONTRIBUTING`. This PR adds it.
In addition, all `git clone` steps in the instructions are sorted alphabetically descending and with "straightforward" ones coming before those that need some more care. Versions for swift-argument-parser and swift-crypto are updated to the latest in this PR, so #3595 won't need to.
This PR conflicts with #3595.
=> [Gardening] Add missing "clone TSC" step to bootstrap instructions and reformat existing steps

Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/BuildToolTests.swift
When using the `xcode` build system, SwiftPM isn't passing down the result of overriding SWIFT_EXEC.  The same is true for `-toolchain` and `-sdk` but this will be fixed in a different PR.
Besides being incorrect and thus a generally something that should be fixed, this also affects SwiftPM CI, where the newly built compiler isn't being used when cross-compilation is active (since SwiftPM currently implements multi-architecture builds by switching build system to use xcbuild).
- pass down SWIFT_EXEC to `xcbuild` so it matches what the native build system would have used
- add a unit test for this
rdar://80194565
=> [SR-14896] `swift build --build-system xcode` doesn't respect `SWIFT_EXEC`

Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/BuildToolTests.swift
This is the Swift 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3596, which fixes a problem that causes SWIFT_EXEC to not be used when the `xcode` build system is used.
The motivation for nominating this fix to 5.5 is that any SwiftPM 5.5 CI that is building packages for both x86_64 and arm64 on macOS is unintentionally using the stock compiler rather than the newly built one.
=> [5.5] [SR-14896] `swift build --build-system xcode` doesn't respect `SWIFT_EXEC`

Utilities/bootstrap
This PR consolidates some `build_...` functions in `bootstrap` into `build_dependency`, as @abertelrud [suggested](https://github.com/apple/swift-package-manager/pull/3533#discussion_r651188173) in #3533's review. This removes some repetition. 
some functions such as `build_llbuild` and `build_swiftpm_with_cmake` are are not consolidated, because they're more different.
=> [Bootstrap] Consolidate some `build_...` functions into `build_dependency`

Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/BuildToolTests.swift
When using the `xcode` build system, SwiftPM isn't passing down the same architecture that the native build system would have used.  This has probably been masked in practice by the `xcode` build system only being used by default when multiple architectures are involved, in which case an overriding set of architectures is passed down.
This is a follow-on to https://github.com/apple/swift-package-manager/pull/3596
rdar://80334540
=> `swift build --build-system xcode` is hardcoding "x86_64" rather than using the build destination arch

Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Sorting by package identity is not very intuitive and gets confusing for users.
rdar://80351736
=> [Collections] Sort packages by name instead of identity

Fixtures/CFamilyTargets/CLibraryNoIncludeDir/Cfactorial/Package.swift, Fixtures/CFamilyTargets/CLibraryNoIncludeDir/Cfactorial/Sources/factorial/factorial.c, Fixtures/CFamilyTargets/CLibraryNoIncludeDir/Cfactorial/Sources/factorial/factorial.h, Fixtures/CFamilyTargets/CLibraryNoIncludeDir/Package.swift, Fixtures/CFamilyTargets/CLibraryNoIncludeDir/Sources/Client/main.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Resolves rdar://52162539 ([SR-10975]: Improve the error message when a C target is missing the include directory). 
Added a check to verify the include dir exists for a library clang target if toolchain is 5.5+.
With the change, it now properly throws an error indicating missing include directory.
=> Check for the include directory for a library Clang target

Sources/XCBuildSupport/XcodeBuildSystem.swift
SwiftPM parses all stderr output from XCBuild that shouldn't lead to a build failure, but emits it as an error diagnostic, which does lead to it. Diagnostics are already available via the parseable JSON output on stdout, not textually via stderr.
Resolves rdar://75751711 (SwiftPM is parsing _ALL_ stderr output from XCBuild into an error diagnostic that fails the build).
This change parses XCBuild stderr and emits error only if stdout is empty. 
If XCBuild stdout is not empty, stderr is now ignored, else it will throw a build error.
=> Parse XCbuild stderr only if stdout is empty

Package.swift, Tests/CommandsTests/APIDiffTests.swift
Reenable the APIDiff tests
Reenable the APIDiff tests
- Check supported frontend flags to determine if a toolchain is compatible.
APIDiff tests should pass or be skipped instead of failing with toolchains from 2021-05-14 - 2021-06-28
=> Fix APIDiff test suite

Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Currently, SwiftPM crashes when someone specifies the URL of a package dependency as a relative file URL. We should instead be able to just make it absolute based on the location of the package itself.
=> Do not crash on relative file URLs in a dependency

Sources/PackageCollections/Model/Package.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
https://github.com/apple/swift-package-manager/pull/3599 for 5.5
=> [5.5][Collections] Sort packages by name instead of identity

Sources/PackageGraph/PinsStore.swift, Tests/PackageGraphTests/PackageGraphTests.swift
motivation: fixing dar://52529014 and rdar://52529011 caused a regression in resolved files serialization in which package name lost its original form, causing slight difference between resolved files in 5.4 and 5.5
changes: update serialization code to correctly preserve the package original name when constructing the package ref from the mirrors
=> fix a bug where resoved files looses package name case

Sources/PackageGraph/PinsStore.swift, Tests/PackageGraphTests/PackageGraphTests.swift
=> fix a bug where resolved file loses package name case

Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
The collection key used to identify records for removal is different from the one used for insertion, causing no records to actually get removed.
rdar://80552471
=> [Collections] Stale search index data

Sources/Workspace/WorkspaceState.swift
We should not be printing diagnostics to stdout.
This should really use the diagnostics engine as the FIXME says, but that will require a more involved refactoring, since just passing one in `Workspace.init` feels off if so many of the methods also take one as an argument.
rdar://80085064
=> Do not print workspace-state diagnostic to stdout

Sources/PackageLoading/TargetSourcesBuilder.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Ignore `.docc` files rather than emitting warnings, since it's useful to have them in packages without warnings.
Unlike other Xcode-specific file types, such as Storyboards and Asset Catalogs, the .docc bundles are not needed for correctness during the build, and should therefore not trigger warnings.
- introduced a list of ignored file types in `TargetSourceBuilder`
- add that list to the end so it is only used if `additionalFileTypes` doesn't contain those types
Building a package does not emit warnings for .docc bundles.
rdar://78133445
=> Ignore .docc files rather than emitting warnings, since it's useful to have them in packages without warnings

Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Package.swift, Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Sources/Dep/dep.swift, Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Package.swift, Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Sources/pkg/pkg.swift, Sources/PackageModel/Manifest.swift, Tests/FunctionalTests/DependencyResolutionTests.swift
motivation: starting tools-version 5.2, SwiftPM validates the target depedenies by name but the validation is case sensitive
changes:
* udpate the validation to be non-case sensitive (the actual lookup is not case sensitive)
* add a test
=> make target dependency lookup case-insensitive

Sources/PackageCollections/PackageCollections.swift
Steps to reproduce:
1. Add a local collection
2. Delete the collection **file** on local disk
3. Refresh collections
4. The unavailable local collection is back!
This is caused by us not deleting unavailable/invalid collections from storage when refresh fails.
rdar://80388968
=> [Collections] Removed local package collection comes back alive

Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Package.swift, Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Sources/Dep/dep.swift, Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Package.swift, Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Sources/pkg/pkg.swift, Sources/PackageModel/Manifest.swift, Tests/FunctionalTests/DependencyResolutionTests.swift
=> [5.5] make target dependency lookup non-case-sensitive

Sources/Commands/SwiftTool.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/SPMTestSupport/misc.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Ignore .docc files rather than emitting warnings, since it's useful to have them in packages without warnings.
Unlike other Xcode-specific file types, such as Storyboards and Asset Catalogs, the .docc bundles are not needed for correctness during the build, and should therefore not trigger warnings.
This change does this in a cleaner way that uses either Xcode build system or SwiftPM build system rules rather than always adding a list of extensions to ignore.
- change the ignored-types list to a swiftpm-build-system type list as peer of the one for xcode build system types
- have the caller choose which list, if any, to use
This is a refinement of the fix in #3609.
rdar://78133445
=> Refine the change to ignore .docc files rather than emit warnings to avoid having multiple definitions for the same file extension

Sources/Commands/SwiftTool.swift, Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/SPMTestSupport/misc.swift, Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3609.  Same motivation and changes as in that PR.
=> [5.5] Ignore .docc files rather than emitting warnings, since it's useful to have them in packages without warnings

Sources/Commands/Error.swift, Tests/CommandsTests/PackageToolTests.swift
Improve Package.swift not found diagnostic error
The current error message when running swift-build in a folder that has no Package.swift file is not descriptive enough.
[SR-14829](https://bugs.swift.org/browse/SR-14829)
Changed the error message and the relevant unit test.
When running `swift-build ` in a folder that doesn't contain a Package.swift the below error is emitted:
error: `Could not find Package.swift in this folder or any of it's parent folders.`
@neonichu
=> Improve Package.swift not found diagnostic error SR-14829

CMakeLists.txt, CONTRIBUTING.md, Package.swift, Sources/Basics/CMakeLists.txt, Sources/Basics/Exports.swift, Sources/Build/BuildPlan.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/Pubgrub/Incompatibility.swift, Sources/PackageGraph/Pubgrub/PartialSolution.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/PubgrubTests.swift, Utilities/bootstrap
motivation: replace TSC versions of ordered collections with the new ones from swift-collections
changes:
* pull in swift-collections as a dependency
* update bootstrap script
* adapt call-sites to swift-collections
=> adopt swift-collections

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Tests/PackageGraphTests/PackageGraphTests.swift
A product declared in a package should not be used as a dependency. This PR improves diagnostics in such case. 
Resolves rdar://71912826 ([SR-13913]: Library product name must match target name??) 
This PR checks if a target dependency includes a product declared in the same package, checks the targets of that product, and throws an error if invalid with an improved diagnostics.  
It throws an error with improved diagnostics preventing using a product declared in the same package as a dependency.
=> Improve diagnostics error when a product declared in a package is also used as a dependency

Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift, Tests/WorkspaceTests/InitTests.swift
We disabled these a while ago due to issues we had with using XCTest from the sueprior with an inferior SwiftPM. The underlying compiler issue should be fixed at this point and we can re-enable the tests.
=> rdar://69448176 (Fix and re-enable test related to "ParallelTestsPkg")

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
It turns out that relative file URLs actually do not exist, see [here](https://github.com/apple/swift-package-manager/pull/3604#issuecomment-881715869) for more discussion. Instead we will now error and guide users to using a local package reference.
=> Error on relative file URLs

Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Motivation:
Some of the package collection tests don't require search and finish quickly, so when background thread tries to `populateTargetTrie` it results in signal 4.
For [example](https://github.com/apple/swift-package-manager/pull/3623#issuecomment-883749028):
```
10:23:08 Test Suite 'PackageCollectionsTests' started at 2021-07-20 10:21:53.935
10:23:08 Test Case '-[PackageCollectionsTests.PackageCollectionsTests testCollectionPendingTrustConfirmIsKeptOnAdd]' started.
10:23:08 Test Case '-[PackageCollectionsTests.PackageCollectionsTests testCollectionPendingTrustConfirmIsKeptOnAdd]' passed (0.105 seconds).
10:23:08 Exited with signal code 4
```
Modifications:
Set `initializeTargetTrie` to `false` for these tests such that `populateTargetTrie` is not called.
=> [Collections] Disable target trie in some of the tests

Sources/Commands/SwiftTestTool.swift
Right now if no tests are matching after filter/skip/etc, we pass no argument to `XCTest` which actually crashes the `xctest` CLI. This makes it so we instead pass an explicit empty argument to it.
=> Do pass explicit empty argument to `-XCTest`

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageDescription4Loader.swift, Tests/PackageLoadingTests/PD4_2LoadingTests.swift
=> [5.5] Do not crash on relative file URLs in a dependency

Package.swift, Sources/Commands/APIDigester.swift, Sources/Commands/SwiftPackageTool.swift, Tests/CommandsTests/APIDiffTests.swift
Now that this feature is tested on CI and the basic functionality is in place, I think it makes sense to drop the 'experimental' from its name. There are still a number of potential improvements, but no major issues that I know of
Rename experimental-api-diff -> dianose-api-breaking-changes to reflect its status as a more officially supported feature.
- Rename experimental-api-diff -> dianose-api-breaking-changes
- Add a stub command to notify users of the new name if they try to use the old one
- Update tests
No functional changes other than the new name
This PR builds on #3622 just so I could avoid some merge conflicts in the tests
=> Rename experimental-api-diff -> dianose-api-breaking-changes

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- Show the exact path where we looked for a resolved file
- Special case if there wasn't a file to begin with
rdar://81172549
=> Improve diagnostic when automatic resolution is disabled

Sources/Basics/SwiftVersion.swift, Sources/PackageModel/ToolsVersion.swift
Add tools version 5.6 and set it as the current version for `main` branch
It's not clear yet whether this will be the next version, but we need a new version in order to remove the gates for the plugin support.  We can always adjust it later when the next version of Swift gets an official version number.
- add `v5_6` enum
- set 5.6.0 as the current SwiftPM version (but keep it marked as being in development)
A separate PR will adjust the plugin availability.
=> Add tools version 5.6 and set it as the current version for `main` branch

Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Package.swift, Sources/PackageDescription/Product.swift, Sources/PackageDescription/Target.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/SPMTestSupport/misc.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/PackageLoadingTests/PD_5_4_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Enable package plugins with a 5.6 deployment target without a special environment variable.
This removes the `SWIFTPM_ENABLE_PLUGINS` environment variable and sets the availability annotations to 5.6.
The goal is to make plugins available without special flags in the next version of SwiftPM.
- remove `SWIFTPM_ENABLE_PLUGINS` and associated flags
- set availability annotations for package plugins as 5.6
Package plugins can be used without special flags or environment variables.
=> Enable package plugins with a 5.6 deployment target without a special environment variable

Sources/PackageDescription/PackageDescription.swift
The C imports are important, particularly on Windows, where `HANDLE` is
not available without the platform SDK (`WinSDK` is roughly synonymous
to `Darwin`).
=> PackageDescription: repair the build after #3635

Package.swift, Sources/Commands/Describe.swift, Sources/PackageDescription/PackageDependency.swift, Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageGraph/PackageGraph.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/Manifest.swift, Sources/PackageModel/Manifest/PackageDependencyDescription.swift, Sources/SPMTestSupport/MockDependency.swift, Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift, Sources/SPMTestSupport/Resources.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift, Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift, Tests/XcodeprojTests/PackageGraphTests.swift
motivation: follow-on work to the change in 5.5 that _allows_ users to not specify a name on the dependency, this soft-deprecates the ability to do so
changes:
* emit a deprecation warning when using the name attribute on a dependency
* refactor the dependency::name attribute to dependency::deprecatedName to reflect the fact it was deprecated and prevent using it in downstream logic
* cleanup the internal API
* cleanup and add tests
=> deprecate name attribute on package dependencies

Documentation/Usage.md, Sources/Build/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
C Flags passed in through a destination JSON are now passed in _before_ a package's internal flags, which can cause problems, as was fixed for the command-line flags with #1365. Also, C flags passed in through a destination JSON are _not_ passed in to the Swift compiler, while command-line `-Xcc` flags are.
Moved all the Workspace toolchain flags to right before the command-line flags, so they can still be overriden by the command-line, and documented the discrepancy between `-Xcc` command-line flags and the destination JSON. 
Fixes issues with the flag ordering and documents how C flags are passed in differently, between the command-line and the Workspace toolchain. 
I hit this because I was passing in a sysroot with prebuilt library dependencies like SQLite when cross-compiling SPM …
=> Change the order of Workspace toolchain C/Swift flags to match the command-line, and document the different ways to pass these flags to SPM

Sources/PackageDescription/PackageRequirement.swift
motivation: new data structures should not be exposed pre-maturily
changes: add availability flag on RegistryRequirement and SourceControlRequirement
=> add a couple of availability flags on new data structures

Sources/PackageGraph/PackageModel+Extensions.swift
Improves the documentation of the function `nodes` from `PackageContainerConstraint`.
Further improves the documentation of Swift Package Manager. Makes it easier for developers to read inline docs of this particular function in particular and its module in general. 
Added mark-up comments to the function `nodes` from `PackageContainerConstraint`.
SPM's Documentation is improved.
---
Thank you! This is my first time opening a PR for SPM, so I would really appreciate any feedbacks or guidances!
=> Add document comment to PackageContainerConstraint function

CHANGELOG.md, Sources/Basics/Version+Extensions.swift, Sources/PackageGraph/RepositoryPackageContainer.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
While implementing SPM manifests in existing Git repos, I found many were using two component tags where the patch version was 0. The intention behind this change is to better support that Git tagging pattern without retraining existing teams, or causing SPM integration to be disruptive to existing tagging practices.
Lenient parsing was added to swift-tools-support-core at apple/swift-tools-support-core#212. The tag based initializer for Version was altered to use this new lenient initializer.
It’s possible for two tags with the same meaning but different literal strings to be present in the same repository. This case did exist previously. Tags like v2.0.0 and 2.0.0 could conflict, and a decision about which tag to use would be required.
- Previous behavior was that a tag without a …
=> Enable lenient parsing of Git version tags

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
motivation: is some development cases, the cached version of the manifest may persist even though is not-parsable and break dependency resolution
changes: refactor caching logic to first try and parse the cached JSON and fall back to trying to re-evaluate the manifest into JSON if it's not parsable.
=> improve cached manifest error handling

Sources/Commands/SwiftPackageCollectionsTool.swift, Sources/Commands/SwiftPackageTool.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/SPMTestSupport/MockDependencyGraph.swift, Sources/SPMTestSupport/MockPackageContainer.swift, Sources/SPMTestSupport/MockWorkspace.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
motivation: less warnings
changes: use Version(_:) instead of the recently deprecated Version(string:)
=> resolve warning from recent Version constructor changes

Examples/package-info/Package.swift, Examples/package-info/Sources/package-info/main.swift, Sources/Commands/APIDigester.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/ToolchainConfiguration.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: configuration work has pointed out that some of the static APIs  use inefficient defaults
changes:
* deprecate Workspace.create,  Workspace.loadRootGraph, PackageBuilder.loadRootPackage, ManifestLoader.loadRootManifest and replace them with instance methods on workspace
* add a simple constructor to workspace, that uses the host toolchain by default
* adjust call-sites, test and examples
=> deprecate static APIs with inefficient defaults

Utilities/Docker/docker-compose.2004.55.yaml
motivation: keep with the times
changes:
* update 5.4 docker file to use the release version instead of the development one
* add a 5.5 dockerfile
=> add docker file for swift 5.5

Sources/PackageModel/PackageIdentity.swift, Tests/PackageModelTests/PackageIdentityNameTests.swift, Tests/PackageModelTests/PackageIdentityScopeTests.swift
Adds package identity scope and name types as defined by SE-0292 (according to updated naming rules proposed by #3624).
Implement [SE-0292](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md).
- Adds a new `PackgeIdentity.Scope` type and related tests
- Adds a new `PackageIdentity.Name` type and related tests
The types added by this PR are tested, but not otherwise used by other APIs, so this change has no immediate effect.
=> Add nested `PackgeIdentity.Scope` and `PackageIdentity.Name` types

Sources/PackageLoading/ManifestLoader.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/PackageLoadingTests/PD5_0LoadingTests.swift
Extend the ManifestLoaderProtocol to allow a custom manifest loader to provide custom environment variables when compiling the manifest.
Clients of libSwiftPM can already provide a set of custom flags to pass to the Swift compiler when compiling and linking the manifest. This extends this support to allow custom environment entries as well. There's no immediate use for this in SwiftPM itself, but it could be used in the future, and some clients need this.
- add a new property to ManifestLoadersProtocol that contains a string-to-string mapping
- use it when compiling manifests and plugin scripts
- add a unit tests that uses this functionality for a toy purpose (for testing)
Clients of libSwiftPM can specify environment entries.  Note that this does not affect the environment that is passed …
=> [5.5] Allow a custom manifest loader to provide custom environment variables when compiling the manifest

Sources/Commands/APIDigester.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftTool.swift, Sources/PackageGraph/DependencyMirrors.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/WorkspaceConfiguration.swift, Tests/WorkspaceTests/WorkspaceConfigurationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: nicer API to work with
changes:
* deprecate previous initializer
* introduce new initializer with minimal signatures, and clearly defined argument names and API docs
* make DependencyMirrors thread safe
=> refactor workspace initializers

Sources/PackageGraph/CheckoutState.swift, Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/WorkspaceTests/PinsStoreTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: when working on configuration, CheckoutState data model stood out as one that can be improved to be safer
changes:
* transition CheckoutState from struct with optionals to enum representing the finite states
=> refactor CheckoutState

CHANGELOG.md
motivation: document manifest API / behavior changes
changes: add reference to product package name lookup done in #3280
=> Document user facing api changes introduced in 3280 and 3641

Tests/BuildTests/BuildPlanTests.swift
The swift-driver functionality this test relies on requires access to a fully-formed toolchain with the Swift compiler *and* the associated `lib` directory contents.
This test is using a mock toolchain which isn't sufficient. This is required to land a [driver change](https://github.com/apple/swift-driver/pull/781) and I will investigate fixing (pointing the test at a real host toolchain) and re-enabling this test in the coming days.
=> Temporarily disable `testExplicitSwiftPackageBuild` due to use of mock toolchain

CHANGELOG.md
`pacakge` -> `package`, `explciit` -> `explicit`
=> Fix typos in `CHANGELOG.md`

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/ToolchainConfiguration.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
Extend `ToolchainConfiguration` to allow a customization of the environment used when compiling package manifests.
Clients of libSwiftPM can already provide a set of custom flags to pass to the Swift compiler when compiling and linking the manifest.  This extends this support to allow custom environment entries as well.  There's no immediate use for this in SwiftPM, but it could be used in the future, and there are clients that want to do so
- add a new property to `ToolchainConfiguration` that contains a string-to-string mapping
- default it to `ProcessEnv.vars` to maintain status quo — this happens to not be needed on Darwin but is needed on Linux
- use it when compiling manifests and plugin scripts
- add a unit tests that uses this functionality for a toy purpose (for testing)
A …
=> Allow a custom manifest loader to provide custom environment variables

Tests/BuildTests/BuildPlanTests.swift
Cherry-pick of https://github.com/apple/swift-package-manager/pull/3673
------------------------------------------
The swift-driver functionality this test relies on requires access to a fully-formed toolchain with the Swift compiler *and* the associated `lib` directory contents.
This test is using a mock toolchain which isn't sufficient. This is required to land a driver change and I will investigate fixing and re-enabling this test in the coming days.
=> [5.5] Temporarily disable `testExplicitSwiftPackageBuild`

CONTRIBUTING.md, Sources/Commands/SwiftRunTool.swift, Sources/Commands/SwiftTestTool.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/ToolchainConfiguration.swift, Sources/SPMPackageEditor/PackageEditor.swift, Sources/SPMTestSupport/Toolchain.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Sources/Workspace/Destination.swift, Sources/Workspace/UserToolchain.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/FunctionalPerformanceTests/BuildPerfTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XcodeprojTests/FunctionalTests.swift, Utilities/bootstrap
motivation: improve logic in how Manifest and Plugin APIs locations are derived
changes:
* rename fields on ToolchainConfiguration to better articulate their meaning
* change logic in UserToolchain to derive the SwiftPM libraries path more clearly and reliably
* adjust call-sites and test
=> refactor toolchain SwiftPM libraries path

Sources/PackageCollectionsSigning/Certificate/Certificate.swift
This function takes a named argument which is the `EVP_PKEY` and checks
the underlying public key type (expected to be one of RSA or EC).
However, instead of checking the key type of the given public key, it
was always returning the key type of the underlying certificate.  This
happened to give the correct result as the current usage always used the
same object to get the key.  This corrects that and uses the proper
accessors for the value.
=> PackageCollectionsSigning: correct `BoringSSLCertificate.keyType(of:)`

Sources/Commands/Describe.swift, Sources/PackageDescription/PackageDependency.swift
motivation: when using path based dependencies it could be useful to set a name (for target based package lookup), as the path may change depending on context
changes:
* remove recently added deprecation flag from .package(name:, path:) API
* update package describe command to include dependecy identity which is useful to know how the dependency can be address in target based package lookup
=> un-deprecate name argument on file-system (aka local) dependencies

Sources/Basics/AuthorizationProvider.swift, Sources/Basics/CMakeLists.txt, Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/WorkspaceConfiguration.swift, Tests/BasicsTests/AuthorizationProviderTests.swift
motivation: support custom authentican providers, not just netrc
changes:
* reafactor and seperate out the auth data model from the loading/saving mutation utility
* add tests
=> enhance configuraiton for authentication providers 

Tests/FunctionalTests/MiscellaneousTests.swift
Temporary logging code to a unit test, only on failure on macOS on arm64, to collect more information about a CI failure that seems to be specific to Apple Silicon and is hard to reproduce.  On macOS and arm64 only, if the test fails it is not considered a test failure but instead additional information is emitted by running the test build again with `-v`.  This will be removed as soon as the underlying cause is found.
=> Add temporary failure handling to testTestsCanLinkAgainstExecutable that logs environmental information

IntegrationTests/Fixtures/XCBuild/Libraries/Bar/Package.swift, IntegrationTests/Fixtures/XCBuild/Libraries/Foo/Package.swift
This fixes `Found multiple targets named 'FooLib'` which is happening in this test when using the XCBuild from Xcode 13. We should figure out separately what to do about that case, but for now it seems most practical to change the test in order to not block other work in SwiftPM.
See https://github.com/apple/swift-package-manager/pull/3684 for more context.
=> Fix integration test for Xcode 13

Sources/Commands/SwiftRunTool.swift
In the case that you used `swift run`, and your executable failed to
build, previously you would see this output, at the bottom of a
potentially long list of warnings:
```
error: fatalError
```
In some cases, especially with lots of build output, this makes it look
like your command ran, but your program failed, not the build.
This silences that message, since the point of that error is that some
other diagnostics should have been printed anyways.
=> Improve swift-run failure mode

Sources/Commands/SwiftPackageTool.swift
This makes 2 changes to `_format`:
1. Only invoke `swift-format` once, this is helpful for larger projects
2. Include the `Package.swift` file for formatting
=> Improve _format command

Utilities/bootstrap
During bootstrap, we should only be using local dependencies and therefore never be in the position to write a resolved file.
Note: this will require https://github.com/apple/swift-package-manager/pull/3691 to actually work.
=> Enforce resolved versions in bootstrap

Sources/XCBuildSupport/XcodeBuildSystem.swift
We pass this as an additional `-L` when building with SwiftPM's own build system, so we should also pass this when using XCBuild.
rdar://82313817
=> Pass `toolchainLibDir` if using XCBuild

Tests/CommandsTests/APIDiffTests.swift
Output of the API diff digester can be different per platform, which should be addressed at the functionality level, as long as the invocation is successful. This separates out the integration point testing of the diff digester and SwiftPM from the functionality tests of the digester itself.
=> Add an environment check to opt in for API diff functionality tests

Sources/XCBuildSupport/XcodeBuildSystem.swift
This already works, because it seems like the second `--buildParametersFile` option wins when invoking `xcbuild`, but it seems better to make this more explicit and more clean to not generate a file if the expectation is that it won't be used.
=> Do not generate a build parameters file if a custom one has been passed

Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/ManagedArtifact.swift, Sources/Workspace/Workspace.swift, Sources/Workspace/WorkspaceState.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: ManagedArtifacts are based on location instead of on identity, refactor them to be based on identity as part of the transition to identity based logic
changes:
* transition ManagedArtifacts underlying hashmap to be based on identity
* update call sites to use package identity instead of location when reading/writing managed artifacts
* adjust tests where needed
=> refactor managed artifacts

Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: stable CI
changes: XCTSkip the test until we get to the bottom of it
=> temporary skip flaky test

Tests/BasicsTests/SandboxTests.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/IncrementalBuildTests.swift, Tests/CommandsTests/APIDiffTests.swift, Tests/CommandsTests/BuildToolTests.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/TestDiscoveryTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Broadly refactor tests to use helper functions that print better failures and use consistent verification logic.
Tests that use `XCTAssert()` without providing custom failure messages are difficult to debug — when they fail, we don't get much context, e.g., “XCTAssertTrue failed”.
We have `XCTAssertMatch()` (and friends) that include robust string matching options and always print nice failure messages that include the expected and actual results, so we should use those functions where we can.
* Use `XCTAssertMatch()` instead of `XCTAssertTrue(string.contains())`, etc.
* Use `XCTAssertNoMatch()` instead of `XCTAssertFalse(string.contains())`, etc.
- When these tests fail they'll have much better failure messages.
=> Tests Refactor: Adopt XCTAssertMatch and eliminate most bare `XCTAssert(string.contains())`

Documentation/Registry.md
Updates the Swift package registry specification with the proposed publishing endpoint. 
This PR serves as the implementation for the corresponding [Swift Evolution proposal](https://github.com/apple/swift-evolution/pull/1424). 
- Adds a new `PUT /{scope}/{name}/{version}` endpoint
This PR updates documentation, and has no functional effect on Swift Package Manager itself.
=> Update registry specification to include publishing endpoint

Sources/Commands/SwiftTool.swift, Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
When running SwiftPM while requiring a resolved file, print some more verbose info on why SwiftPM decided the existing file was out-of-date or why a resolved file was required.
We have been seeing some unexplained issues in CI related to resolved files where this would help us to debug them. It can also generally be helpful for folks. 
If resolution is required and we are in verbose mode, append a reason to the diagnostic about the resolved file being out-of-date.
This is a pretty basic translation from `WorkspaceResolveReason` into prose which may need some improvements in the future, but it's a start at least.
=> Print reason for requiring resolution in verbose mode

Sources/Build/BuildPlan.swift, Sources/Build/ManifestBuilder.swift, Sources/Commands/CMakeLists.txt, Sources/Commands/Snippets/Card.swift, Sources/Commands/Snippets/CardEvent.swift, Sources/Commands/Snippets/CardStack.swift, Sources/Commands/Snippets/Cards/SnippetCard.swift, Sources/Commands/Snippets/Cards/SnippetGroupCard.swift, Sources/Commands/Snippets/Cards/TopCard.swift, Sources/Commands/Snippets/Colorful.swift, Sources/Commands/SwiftPackageTool.swift, Sources/Commands/SwiftRunTool.swift, Sources/PackageGraph/ResolvedProduct.swift, Sources/PackageLoading/Diagnostics.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/CMakeLists.txt, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageModel/Product.swift, Sources/PackageModel/Snippets/Model/Snippet.swift, Sources/PackageModel/Snippets/Model/SnippetGroup.swift, Sources/PackageModel/Snippets/Parsing/PlainTextSnippetExtractor.swift, Sources/PackageModel/Target.swift, Sources/SPMBuildCore/BuildParameters.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/Xcodeproj/SchemesGenerator.swift, Sources/Xcodeproj/Target+PBXProj.swift, Sources/Xcodeproj/pbxproj.swift, Tests/PackageModelTests/SnippetTests.swift
Snippets are small, focused pieces of example code for packages. They are meant
for current and potential package clients to read and try when exploring a
package.
Snippets build with the rest of a package so they don't get stale and
can run as an executable target with hidden "demo code" to illustrate and prove
that the snippets work (this does not mean that snippets are tests!).
Summary of changes:
- Add a `.snippet` product and target type
- Add the `Snippet` and `SnippetGroup` model to PackageModel
- When building a package in `PackageBuilder`, look for snippets in the
`Snippets` subdirectory.
- Add the "card stack" terminal UIs for browsing a package's snippets
- "Top" card: The top level menu that displays products and snippet groups
- "Snippet Group" card: The menu that shows the …
=> Introduce the `snippet` target type

Sources/Commands/Options.swift
This adds a new alias for this flag and also updates the help text. Previous names of the flag will continue to work as well.
rdar://81961772
=> New name for "disable automatic resolution"

Documentation/PackageCollections.md
Add information about the new Swift Package Collection certificate type, available on
developer.apple.com, that can be used for signing package collections.
=> [Documentation] Update package collection docs

Sources/Commands/SwiftTool.swift, Sources/Workspace/Destination.swift
Do not inherit host destination's extra flags for target destination
Host environment specific flags, such as XCTest module directory, were implicitly inherited by target destination. It caused unexpected reference to host module file when cross-compiling for WASI, so drop them explicitly
Create a new fresh Destination for WASI target and move some logic into Destination to be more generic for different targets.
CC: @MaxDesiatov
=> Do not inherit host destination's extra flags for target destination when cross-compiling

Sources/SourceControl/RepositoryManager.swift
motivation: fix unstable test
changes: compute the cache state before queueing the delegate call, since otherwise it may compute the state after the cache has been created
=> fix potential race in the computation of cache state

Sources/PackageGraph/PackageGraph+Loading.swift, Sources/PackageModel/Manifest.swift, Tests/WorkspaceTests/WorkspaceTests.swift
motivation: recent change to SwiftPM introduced stricter validation of dependencies uniquness to address undefined behavior. however, we want to allow users some times to adjust before making a breaking change
changes: update the validation to emit a warning instead of error under the specific condition the previous behavior incorrectly ignored!
=> relax stricter validation to warning to allow transition

Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift, Sources/SPMTestSupport/InMemoryGitRepository.swift, Sources/SPMTestSupport/MockDependency.swift, Sources/SPMTestSupport/MockPackage.swift, Sources/SPMTestSupport/MockWorkspace.swift, Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift, Tests/CommandsTests/PackageToolTests.swift, Tests/PackageGraphTests/PackageGraphTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Tests/XcodeprojTests/GenerateXcodeprojTests.swift
motivation: expand the test suite as we are changing the dependency uniqueness validation functionality 
changes:
* add facilities to use urls in mocks, not just path
* add tests that demonstrate the current behavior when dependency identity conflict (different URLs, same identity) is encountered
=> add more tests for additional dependency uniqueness validation 

Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift
In some situations, XCBuild's only output will be raw text to stdout, we need to handle this case properly because otherwise it will seem like a silent error in SwiftPM. In addition, in the case the only content is on stderr, we need to emit that before throwing.
rdar://82742081
=> Improve XCBuild output handling
