swiftlang/swift-package-manager

- Sources/Commands/SwiftTool.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace.swift
motivation: code should be easier to reason about
changes:
* rename resolveToResolvedVersion to resolveBasedOnResolvedVersionsFile
* cleanup redundant private function abstractions where possible to reduce complexity
> rename resolveToResolvedVersion to resolveBasedOnResolvedVersionsFile

- Sources/Workspace/Workspace.swift
motivation: manifest loading uses its own diagniostics engine to be able and communicate errors through the delegate, but the code did not actually use the right dignostics engine
changes: more clearly name the variable and make sure the right diagnotics engine is used while loading the manifest
> improve manifest loading diagnostics handling

- Sources/PackageGraph/PinsStore.swift
- Tests/WorkspaceTests/PinsStoreTests.swift
motivation: resolved file now encodes the package name which is redundant. it also does not include the identity of the package so that needs to be computed frmo the url and could be incorrect in case of "creative" mirroring. it will also pose issues as we transition to registry based dependencies
changes:
* create V2 of the resolved file format
* in new format, encode identity and not name
* adjust tests
> update the resolved file format

- Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
- Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
Motivation:
A new product type `snippet` was added. Package collection model needs
to be updated accordingly.
Modifications:
Add `snippet` to corresponding `ProductType` in package collection
model.
> [Collections] Add support for new 'snippet' product type

- Sources/Build/BuildPlan.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
This is a follow-up to #3695, adding various other settings of the toolchain that we weren't yet correctly forwarding when XCBuild is being used.
rdar://82313817
> Pass toolchain settings when using XCBuild

- Sources/SPMTestSupport/ManifestExtensions.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
- Tests/PackageModelTests/ManifestTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
- Tests/XcodeprojTests/GenerateXcodeprojTests.swift
- Tests/XcodeprojTests/PackageGraphTests.swift
motivation: address correctness issues with tests that create in-memory manifests
changes:
* test helper function to create in-memopry manifest should take a path instead of a string representing a path
* in-memory test manifest pacageLocation is equal to the path in most test cases, remove redundancy where possible to avoid correctlness issues
* adjust tests
> cleanup test manifest creation

- Sources/Commands/Options.swift
> [5.5] New disable automatic resolution alias

- Sources/Build/BuildPlan.swift
Snippets are also a kind of executable, so need the same _main aliasing
logic that executables have.
> Rename _main symbol when linking snippets

- Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
This uses the `CCryptoBoringSSL_X509_STORE_CTX_get_current_cert`
accessor to access the `current_cert` member.  This is purely a cleanup
change that will become important when swift-crypto is bumped as
BoringSSL has made more of the interfaces opaque.
> PackageCollectionsSigning: avoid peeking into `X509_STORE_CTX`

- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
Recent Swift drivers may schedule an emit-module job to build module-wide
files instead of merging partial swiftmodules.
Some tests are failing with a recent Swift driver that schedules emit-module jobs as the tests expect a merge-module job explicitly. Unblock Swift-side CI testing like: https://ci.swift.org/job/swift-PR-macos-smoke-test/31017/
Updated tests to accept both merge-module and emit-module.
Tests should pass with a recent driver, and older ones.
> Update tests expecting a merge-module job to also accept emit-module

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/PackageIdentity.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: new package location validation is a pure string comparison which is not subtle enough to address how git URLs can be expressed
changes:
* use the canonical location facilities to compare package locations
* add more tests
> improve package location validation

- Sources/PackageModel/Manifest.swift
- Tests/PackageModelTests/ManifestTests.swift
Include Plugins in `Manifest.targetsRequired`
Fixes SR-14343. As Plugins are modeled as a dependency they also must be included the list of required targets for a product.
Changed the implementation of `Manifest.targetsRequired` to include plugins 
SR-14343 is fixed
> [Plugins] Include Plugins in `Manifest.targetsRequired`

- Sources/Build/ManifestBuilder.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageModel/Target.swift
motivation: no warnings
changes:
* mark generateManifest as discardableResult
* udpated call-sites of TSC Path contains to isDescendantOfOrEqual(to:)
> fix warnings from API changes

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
The code in `Workspace.parseArtifacts()` assumes prior validation of paths even though it is running before any such validation.
rdar://83059393
> Fix crash with absolute path to binary artifact

- Sources/Workspace/Workspace.swift
motivation: use identity everywhere we can as locaiton will be deprecated as we trasnition toward regsitry based dependencies
changes: change workspace::packageStateChanges to be identity based
> use identity in workspace state tracking

- Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift
- Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Package.swift
- Sources/PackageDescription/Product.swift
- Sources/PackageDescription/Target.swift
- Tests/PackageLoadingTests/PD_5_4_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift
- Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Changes the availability annotations of manifest API related to plugins back to 5.5 again.
They were originally marked as 5.5, I changed this to 5.6 when removing the feature flag.  This means that existing packages with experimental use of plugins no longer load, however, which is a problem since IDEs such as Xcode 13 actually support loading such manifests but there is no IDE that supports 5.6 yet.
SwiftPM 5.5 already has the feature flag to prevent casual use.  Supporting 5.5 again allows early adopters to write their code to work with either or both of 5.5 and/or 5.6.
- changed the availability annotations back to 5.5
Packages no longer have to upgrade their tools version to 5.6 to contain mentions of plugins.
> Mark package plugins as being available in 5.5 again, not 5.6

- Sources/Commands/SwiftPackageCollectionsTool.swift
- Sources/PackageCollections/API.swift
- Sources/PackageCollections/Model/Package.swift
- Sources/PackageCollections/Model/TargetListResult.swift
- Sources/PackageCollections/PackageCollections.swift
- Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
- Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
- Sources/PackageCollections/Providers/PackageMetadataProvider.swift
- Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
- Sources/PackageCollections/Utility.swift
- Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
- Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
- Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
- Tests/PackageCollectionsTests/PackageCollectionsTests.swift
- Tests/PackageCollectionsTests/Utility.swift
motivation: adoption of SE-0292 package registry
chnages:
* migrate APIs that take PackageRefernec to take PackageIdentity
* adjust and update tests
rdar://83073308
> update collections APIs to use package identity

- Sources/PackageDescription/SupportedPlatforms.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Sources/PackageModel/Platform.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
- Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Allow Package.swift specification of minimum SDK version for unknown platforms by using new "custom" platform with platform name string, and version string.
Currently, platforms in SwiftPM have to always be hard-coded and we should get to a more flexible model here. As a first step, this PR adds the ability to declare custom platform deployment versions in the package manifest, which won’t be handled by SwiftPM’s own build system, but will be part of the package model, so that they can be utilized when using libSwiftPM together with another build system.
Added a new API, custom() to each of Platform and SupportedPlatform.  Added fall back while reading manifest to create a custom platform where the platform is not recognized.  Tests were added for Package Loading and Building.
From now …
> adding support for custom platforms

- Sources/PackageGraph/LocalPackageContainer.swift
- Sources/PackageGraph/PackageModel+Extensions.swift
- Sources/PackageGraph/RepositoryPackageContainer.swift
- Sources/PackageModel/Diagnostics.swift
- Sources/PackageModel/ToolsVersion.swift
- Sources/Workspace/ResolverPrecomputationProvider.swift
- Sources/Workspace/Workspace.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: adoption of SE-0292 package registry
changes:
* remove assumption and runtime check about RepositorySpecifier always available for PackageRefrence
* adjust call-sites and test
> use identity instead of location where possible

- Sources/PackageModel/PackageIdentity.swift
This PR replaces the synthesized conformance to `Equatable` and `Hashable` and updates adoption of `Comparable` to use case-insensitive comparisons. 
With [SE-0292](https://github.com/apple/swift-evolution/pull/1410), package identifiers must be case-insensitive. For example, a dependency declared as `mona.LinkedList` is equivalent to `MONA.LINKEDLIST`.
This change also makes sense for packages identified by a remote URL<sup>*</sup> or local path<sup>**</sup>.
<small>* Technically, URLs are case-sensitive. However, many if not most websites treat them as case-insensitive. This includes all of the popular code hosting services I'm aware of. I would be very surprised if any packages in the wild rely on remote packages differing only in case _not_ being equivalent.</small> 
<small>** …
> Update PackageIdentity to be case-insensitive

- Sources/SourceControl/GitRepository.swift
Updates `swift package archive-source` command according to the [SE-0292 amendment](https://github.com/apple/swift-evolution/pull/1410).
With https://github.com/apple/swift-package-manager/pull/3624, the behavior of the `archive-source` command now adds a `--prefix` argument to the `git-archive` invocation, so that entries are prefixed by output name.
```diff
try callGit("archive",
"--format", "zip",
+             "--prefix", path.basenameWithoutExt,
"--output", path.pathString,
"HEAD",
failureMessage: "Couldn’t create an archive")
```
Generated source archives are prefixed by output name. 
For example:
```console
$ swift package archive-source --output="LinkedList-1.2.0.zip"
$ zipinfo LinkedList-1.2.0.zip
Archive:  path/to/LinkedList-1.2.0.zip
[...]
[...] LinkedList-1.2.0/
[...] …
```
> Update `swift package archive-source` command to provide directory prefix

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3737
> [5.5] Fix crash with absolute path to binary artifact

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
An earlier change in `main` broke the default location associated with diagnostics from package manifest evaluation.
- this fixes a regression
- pass through the default location when creating the DiagnosticEngine for manifest loading
- add a unit test for the location
- this restores the 5.5 behavior
> Fix the default location for diagnostics resulting from package manifest loading

- Sources/PackageLoading/ModuleMapGenerator.swift
- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
motivation: adapt new diagnostics apis
changes: refactor the PackageLoading module to use new diagnostics api
> convert the PackageLoading module to the new diagnostics apis

- Tests/BuildTests/BuildPlanTests.swift
motivation: fix CI
changes: change assumption in test about single diagnostic emitted, as there may be more on systems that do not have pkg-config installed
> fix PkgConfigHint test on systems that do not have pkg-config installed

- Sources/PackagePlugin/PublicAPI/Context.swift
- Sources/SPMBuildCore/PluginInvocation.swift
https://github.com/apple/swift-package-manager/pull/3712 accidentally made SwiftPM no longer compile using 5.4, which lacks automatic Codable synthesis for enums.
Make `PluginAction` in the PackagePlugin API conform to `String` as well as `Decodable`.
SwiftPM can build on 5.4.
> Add conformance of an enum to String so that SwiftPM still builds on 5.4

- Sources/Build/BuildOperation.swift
motivation: clearer error message to help diagnose when LLBuild fails
changes: instead of throwing a generic error, throw a more detailed one
> make error message more specific when failing to create build system with LLBuild

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Stop passing `-fmodules` to C++ compilation.
Historically, `swift build` has indiscriminately passed `-fmodules` when invoking Clang on Darwin, regardless of the language being compiled for.  Also historically, Clang on Darwin has ignored the `-fmodules` option for C++ files.
In some builds of Clang on Darwin, C++ module functionality is getting activated and this can in some case cause build failures.  SwiftPM should stop passing `-fmodules` for C++ on Darwin for now, as it is already disabled altogether for Windows and Android due to SDK compatibility issues.
- on Darwin, condition the passing of `-fmodules` on not building for C++ or Objective-C++
- clean up the logic to avoid repeating this condition in two places, and add an explanatory comment
- adjust unit tests
- `-fmodules` and …
> `swift build` shouldn't pass `-fmodules` when compiling C++ files

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/PackageIdentity.swift
- Sources/PackageModel/PackageReference.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SPMTestSupport/misc.swift
- Sources/Workspace/ManagedDependency.swift
- Sources/Workspace/ResolverPrecomputationProvider.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceState.swift
- Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: ManagedDependencies are based on location instead of on identity, refactor them to be based on identity as part of the transition to identity based logic
changes:
* transition ManagedDependencies underlying hashmap to be based on identity
* update the ManagedDependencies edit state to include the "basedOn" property which is only relevant to that state
* update calls ites to use package identity instead of location when reading/writing managed depedencies
* refactor related call-sites to handle edited state more safely and correctly
* add code comments to explain some of the more subtle business logic
* adjust tests where needed
> refactor managed dependencies

- Sources/Build/CMakeLists.txt
- Sources/Build/LLBuildManifestBuilder.swift
motivation: clearer intent
changes: rename ManifestBuilder -> LLBuildManifestBuilder
> rename LLBuild manifest builder to LLBuildManifestBuilder

- Sources/SPMTestSupport/InMemoryGitRepository.swift
motivation: use modern version of foundation utilities
changes: replace use of NSUUID with UUID
> replace use of NSUUID with UUID

- Package.swift
- Sources/PackageCollectionsSigning/Certificate/Certificate.swift
- Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
Motivation:
swift-crypto v2.x has breaking BoringSSL API changes. We don't want to upgrade to v2 just yet (at least until it's out of beta), but we need to be able to test v2 readily.
Modifications:
- API changes for swift-crypto v2: https://github.com/apple/swift-package-manager/commit/c1be158d24b9014cac6700cc4ade0cccbcf17096 from https://github.com/apple/swift-package-manager/pull/3731 
- `CRYPTO_v2` flag to allow coexistence of v1 and v2 code and make it easier to test v2: https://github.com/apple/swift-package-manager/commit/e8d39eae5ca3e3eae76dc8ec46e7b740a559c55a
I verified locally that package collection tests pass with swift-crypto 1.1.6 and ~~2.0.0-beta.2~~ 2.0.0 (with `CRYPTO_v2`) on macOS and Linux.
> swift-crypto 2.x upgrade

- Sources/PackageModel/Product.swift
- Tests/PackageModelTests/PackageModelTests.swift
This fixes a case of not being able decode a `ProductFilter` that had been encoded.
`ProductFilter` in the SwiftPM project model is declared as `Codable` and it should be possible to decode what was encoded.
The `ProductFilter.everything` is encoded as the `.none` case of a `[String]?`, which gets encoded by the `SingleValueEncodingContainer` as JSON `null`.  But then `SingleValueDecodingContainer` doesn't decode that `null` as the `.none` case of `[String]?`, instead throwing an error.
This change uses `decodeNil` to check for `null`, but it seems to me that there might be a bug in `SingleValue{Encoding,Decoding}Container` here, since it doesn't seem symmetrical.  I would expect consistent handling of `[String]?` for encoding and decoding.
So there is follow-up there on a possible …
> `ProductFilter` type is not `Decodable` for the `everything` case

- Sources/PackageModel/Product.swift
- Tests/PackageModelTests/PackageModelTests.swift
This is the 5.5 cherry-pick of #3775.  See that PR for the details.
> [5.5] `ProductFilter` type is not `Decodable` for the `everything` case (#3775)

- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: bug where delegate was only notified on success but not on error
changes:
* udpate logic to notify on both error and success cases
* added unit test
> fix workspace to notify delegate on any result of manifest loading

- Sources/PackageLoading/ToolsVersionLoader.swift
- Sources/PackageModel/Diagnostics.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
- Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift
#3073 left out a few instances of `"// swift-tools-version:\(version < .v5_4 ? "" : " ")\(versionSpecifier)"`. This PR replaces them with `version.specification(roundedTo:)`
less repetition in code; more consistent formatting
Changed a few `"// swift-tools-version:\(version < .v5_4 ? "" : " ")\(versionSpecifier)"` to `version.specification(roundedTo:)`.
There are still a lot of explicitly spelt-out tools version formatting in some test files. I think tests should be explicit and shouldn't rely on the logic in the source files, so I left them unchanged.
Also fixed an unrelated mis-indentation.
NFC, other than that in `ToolsVersionLoader.swift`, tools version error messages now omits the patch version in the suggested version if it's 0.
> Replace hard-coded version specification (sub)string with `Version.specification(roundedTo:)` in more places

- Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
- Sources/PackageDescription/Version+StringLiteralConvertible.swift
Switch to parenthesized variants of the APIs.
Silence some annoying warnings about potentially misleading trailing closures in conditions.
Use the parenthesized form of the APIs.
NTC
> Silence some warnings about potentially misleading trailing closures

- Sources/Build/LLBuildManifestBuilder.swift
This avoids adding duplicate entries to the LLBuild manifest in explicit module builds by de-duplicating explicit dependency pre-build jobs based on their unique output filename.
> [Explicit Module Builds] De-duplicate dependency build jobs before adding them to LLBuild manifest

- Sources/LLBuildManifest/BuildManifest.swift
Otherwise this results in silently replacing some commands in the graph.  We can discuss whether a future improvement would be to make these internal errors reported at runtime.
Without these assertions, adding two or more commands with the same name result in only the last of them remaining, which can lead to hard-to-diagnose build failures.  I have to not come across any cases of this happening intentionally, but there is currently a Linux-specific test failure that I need to look closer at.  It could be a bug that this is catching or could be that this needs to be made more lenient.  Even if the replacement behavior is intentional, it seems like the kind of thing that should be done explicitly in the code.  This was motivated by an unintentional replacement of a build command.
- add …
> Add development-time assertions to catch errors where two llbuild commands are created with the same name

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This is the 5.5 cherry-pick of https://github.com/apple/swift-package-manager/pull/3739.  That fix landed some time ago, but I didn’t realize that the regression was also in 5.5.
An earlier change in main broke the default location associated with diagnostics from package manifest evaluation.
This fixes a regression causing diagnostics involving manifests to not be properly associated with the packages whence they came.
- pass through the default location when creating the DiagnosticEngine for manifest loading
- add a unit test for the location
rdar://83818577
> [5.5] Fix the default location for diagnostics resulting from package manifest loading

- Sources/Workspace/WorkspaceState.swift
The `ManagedDependencies` and `ManagedArtifacts` collections use dictionaries as their underlying storage, so enumerating their elements is nondeterministic.
In CI, we hash the contents of the workspace state, and use that as part of a cache key to avoid re-building unnecessarily, e.g. when pre-merge and post-merge sources are identical.  Thus, nondeterminism in serializing the workspace state contributed to extremely high cache invalidation rates.
Sort artifacts and dependencies by package identity, which seems to be unique and Comparable.
I ran `swift-package resolve` on SPM itself, and verified by inspection that the resulting dependencies in `.build/workspace-state.json` were sorted as expected.
> Serialize workspace state deterministically

- Sources/Commands/SwiftTestTool.swift
- Tests/CommandsTests/TestToolTests.swift
motivation: adopt new Observability APIs
changes: replace DiagnosticsEngine with Observability APIs in SwiftTestTool
> migrate SwiftTestTool to Observability APIs

- Sources/Basics/CMakeLists.txt
- Sources/Basics/EnvironmentVariables.swift
- Sources/Build/SPMSwiftDriverExecutor.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/LLBuildManifest/BuildManifest.swift
- Sources/LLBuildManifest/Tools.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageModel/ToolchainConfiguration.swift
- Sources/SPMTestSupport/XCTAssertHelpers.swift
- Sources/SPMTestSupport/misc.swift
- Sources/SourceControl/GitRepository.swift
- Sources/Workspace/Destination.swift
- Sources/Workspace/UserToolchain.swift
- Tests/BasicsTests/EnvironmentVariablesTests.swift
- Tests/CommandsTests/APIDiffTests.swift
- Tests/CommandsTests/PackageRegistryToolTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/XcodeprojTests/FunctionalTests.swift
motivation: users should be able to set DYLD_LIBRARY_PATH
changes:
* define new utility named EnvironmentVariables
* add prependPath and appendPath helpers to EnvironmentVariables
* update call sites that take [String:String] as environment variables to use the new EnvironmentVariables
* fix the code in SwiftTestTool that stripped DYLD_LIBRARY_PATH to use EnvironmentVariables::appendPath which gives user's setting preference
* add tests for EnvironmentVariables
rdar://83607631
> fix an issue where user defined DYLD_LIBRARY_PATH gets ignored

- Sources/Basics/AuthorizationProvider.swift
- Sources/Basics/CMakeLists.txt
- Sources/Commands/SwiftTool.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/BasicsTests/AuthorizationProviderTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Motivation:
Support keychain auth on macOS.
Modifications:
- Add `addOrUpdate` API to `AuthorizationProvider` protocol
- Implement `KeychainAuthorizationProvider`
- Move `NetrcAuthorizationProvider` to `Basics` and update conformance
- Add tests
rdar://83682028
> Add keychain auth provider

- Sources/Workspace/ManagedDependency.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Sources/Workspace/WorkspaceState.swift
As suggested in https://github.com/apple/swift-package-manager/pull/3698#discussion_r709598802, this PR provides additional refactoring of `ManagedDependencies` by rebasing changes in #3640 against #3698.
Improve convenience and correctness of `Workspace` APIs.
- Converted `ManagedDependency` from class to structure and made `ManagedDependency.State` an indirect enumeration. It makes sense for this to be a value type and has the added benefit of automatic `Equatable` synthesis.
- Removed `ManagedDependency.packageIdentity` property. This was a helper for `self.packageRef.identity` and only used in a couple places.
- Consolidated dependency path determination into dedicated APIs. There are a few places where we determine the location of a repository checkout or edited package by appending …
> Additional refactoring of ManagedDependencies

- Sources/PackageModel/ManifestSourceGeneration.swift
- Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Allow clients of the code that can generate manifest source generation to provide a tools version header comment, a list of imports, and custom handling for product types (falling back on default behavior if they don't provide a custom source code fragment for the product).  Also makes SourceCodeFragment available to clients and adds documentation code for it.
(cherry picked from commit 263ad3a7a3680a2453bf4805a5920eae07adfee6)
This is the 5.5 nomination of https://github.com/apple/swift-package-manager/pull/3782 for a client that needs it.
> [5.5] Allow libSwiftPM clients additional flexibility in the manifest source generation (#3782

- Tests/WorkspaceTests/WorkspaceStateTests.swift
Check that serialized workspace state indeed has stable ordering for dependencies.
Follow-up from https://github.com/apple/swift-package-manager/pull/3785.
Adds a new test case for `WorkspaceState` that loads a mis-sorted state file, then re-saves it.
Because the underlying issue is non-deterministic, this test has a false-negative rate of roughly 50%, i.e. it will pass half the time, even when it should fail.  Repeating the test can improve those odds, but I wan't able to do so reliably from within the test itself vs. multiple `swift test` invocations.
> Add a test for WorkspaceState serialization stability

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Commands/SwiftTool.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/CommandsTests/SwiftToolTests.swift
motivation: SE-0292 defines that local .netrc files should be honored with priority over user home directory .netrc files
changes:
* add lookup for local .netrc file before defaulting to user home directory
* deprecate Workspace.Configuration.Netrc since it now redundant
* add tests
> add support for local netrc file

- Sources/Build/BuildOperation.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/APIDigester.swift
- Sources/Commands/SwiftBuildTool.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftRunTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/Commands/WatchmanHelper.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/Target+PkgConfig.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/XCBuildSupport/XCBuildDelegate.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Sources/Xcodeproj/generate.swift
- Sources/Xcodeproj/pbxproj.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/CommandsTests/APIDiffTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/PackageLoadingTests/PkgConfigTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
- Tests/XcodeprojTests/GenerateXcodeprojTests.swift
- Tests/XcodeprojTests/PackageGraphTests.swift
motivation: adapt new diagnostics apis
changes:
* refactor the build  modules and relevant call sites to use new diagnostics api
* clean up assumptions about local file system as a default argument
* adjust call-sites and test
> convert the build modules to the new diagnostics apis

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Add `Accept: application/octet-stream` header to binary download request to allow use of Github API.
I want to be able to download Github release assets as binary dependencies. However the [Github API states](https://docs.github.com/en/rest/reference/repos#get-a-release-asset) that in order to download an asset a `Accept: application/octet-stream` header should be present, otherwise the API JSON response is returned.
When downloading a binary artifact an `Accept: application/octet-stream` header is added to the request.
On each download download request of an artifact the `Accept: application/octet-stream` header is added.
> Add accept header to download request

- Sources/PackageCollections/PackageCollections.swift
- Sources/PackageModel/PackageReference.swift
- Sources/PackageRegistry/RegistryManager.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SourceControl/GitRepository.swift
- Sources/SourceControl/Repository.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/ManagedDependency.swift
- Sources/Workspace/SourceControlPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceState.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: use identity instead of location where possible
changes:
* abstract PackageRef comparison which need to acccount for location intoa function
* replace several places in Workspace that use location but can use identity
* rename "location" to "locatioString" to discourage the uses of the untypes / string form
* deprecate RepositorySpecifier::url in favour of RepositorySpecifier::location
> cleanup use of package location where we can avoid it

- Sources/Workspace/WorkspaceState.swift
- Tests/WorkspaceTests/WorkspaceStateTests.swift
motivation: some tools rely on using older SwiftPM to generate the state, so SwiftPM must be able to read older formats
changes:
* add deserialization for v4 and number the new format as v5
* add tests for v4 and v5 deserialization
rdar://84172027
> add backwards compatibility for workspace-state.json v4

- Sources/PackageLoading/TargetSourcesBuilder.swift
- Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
motivation: treat directories with extensions more correctly and intuitivly: only treat well known directory extensions specially
changes:
* define list of known directory extensions (eg .xcassets)
* only treat well known directory extensions specially
rdar://82933763
> improve treatment of directories with extensions

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/ResolvedPackage.swift
- Sources/PackageGraph/ResolvedProduct.swift
- Sources/PackageGraph/ResolvedTarget.swift
- Sources/PackageModel/Manifest.swift
- Sources/PackageModel/Package.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/Target.swift
- Sources/XCBuildSupport/PIF.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
motivation: ObjectIdentifierProtocol is being deprecated
changes:
* replace use of ObjectIdentifierProtocol with Hashable where still needed
* update call sites
> remove the use of ObjectIdentifierProtocol

- Sources/Commands/SwiftTestTool.swift
motivation: fix a regression in test output when running in parallel
changes:
* only emit diagnostics when writeToOutputStream is set to true, otherwise accumalate error info
* ignore ProcessSetError.cancelled as we have a specific handler for when the process is signaled
> fix regression in test output

- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/CommandsTests/BuildToolTests.swift
motivation: when no work needs to be done the output is `[0/0] Build complete!` which is confusing
changes: treat the build complete step as a discrete step incrementing the step + total counts
> improve build complete message

- Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
This extends `PackageCollectionSigner` with a signature that accepts the private key PEM as `Data` in addition to the existing `URL`.
The existing `URL` based signature is conformed to via this new signature such that clients only need to implement the `Data` one.
For example, the sole change required in https://github.com/apple/swift-package-collection-generator to adopt this is
```diff
@@ -62,7 +62,7 @@ final class PackageCollectionSignTests: XCTestCase {
private struct MockPackageCollectionSigner: PackageCollectionSigner {
func sign(collection: Model.Collection,
certChainPaths: [URL],
-              certPrivateKeyPath: URL,
+              privateKeyPEM: Data,
certPolicyKey: CertificatePolicyKey,
callback: @escaping (Result<Model.SignedCollection, Error>) -> Void) {
let signature = …
```
> Allow signing from key provided as `Data` in addition to `URL`

- Sources/Build/BuildOperation.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Sources/Build/BuildPlan.swift
- Sources/LLBuildManifest/Tools.swift
- Tests/CommandsTests/BuildToolTests.swift
motivation: inform users of configuration they building for
changes: add "building for <configuration>" message at the begining of the build
rdar://84533229
> add "building for <configuration>" message

- Sources/PackageDescription/PackageDependency.swift
motivation: existing message is generic and does not provide an actionable fix
changes: add information to the message to make it more actionable
> improve the availablity message for deprecate manifest APIs

- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageGraph/DependencyResolver.swift
- Sources/SPMTestSupport/Observability.swift
- Sources/Workspace/Workspace.swift
- Tests/BasicsTests/ObservabilitySystemTests.swift
- Tests/PackageGraphTests/PubgrubTests.swift
- Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: provide transperancy / debug information when needed
changes:
* add a new dependency resolver delegate that emits debug diagnostics for resover callbacks, wire it into the observability system
* this information will only show when running in verbose mode
* deprecate TracingDependencyResolverDelegate which was a bespoke solution serving the same need
> emit information diagnostics for dependency resolution

- Sources/SourceControl/Repository.swift
Many clients of libSwiftPM will want to deal with Foundation URLs here, so it makes sense to offer a computed property to convert a `RepositorySpecifier` location into that.
> Replace deprecated `url` with a more useful one

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
When building an executable or test target for macOS prior to 12.0,
add an additional rpath to point into the toolchain's copy of the
back-deployed concurrency shared libraries. This allows `swift build`
to build executables that can run on the same macOS that predates
macOS 12.0.
Fixes rdar://problem/85209998 / SR-15445.
> Include rpath for back-deployed concurrency on macOS prior to 12.0.

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
When building an executable or test target for macOS prior to 12.0,
add an additional rpath to point into the toolchain's copy of the
back-deployed concurrency shared libraries. This allows `swift build`
to build executables that can run on the same macOS that predates
macOS 12.0.
Fixes rdar://problem/85209998 / SR-15445.
> [5.5] Include rpath for back-deployed concurrency on macOS prior to 12.0.

- Fixtures/Miscellaneous/TestDiscovery/Async/Package.swift
- Fixtures/Miscellaneous/TestDiscovery/Async/Sources/Async/Async.swift
- Fixtures/Miscellaneous/TestDiscovery/Async/Tests/AsyncTests/SwiftTests.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
This adopts [a recent enhancement to swift-corelibs-xctest for supporting `async` test methods](https://github.com/apple/swift-corelibs-xctest/pull/331) by ensuring the automatic test discovery machinery used on non-Apple platforms generates the correct test manifest code for the harness to run async tests.
I have adjusted the code-gen logic used during test discovery to notice async test methods, using the richer IndexStore data provided by https://github.com/apple/swift-tools-support-core/pull/258, and wrap such methods in the `asyncTest` helper from swift-corelibs-xctest so that they can execute correctly.
With this change, it is now possible to transparently run async XCTests on Linux via `swift test`.
> Add support for correctly discovering async test methods on non-Apple platforms

- Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Motivation:
I noticed that when I run `package-collection remove` in CLI there is a warning in the output:
```
Failed to 'VACUUM' the database: SQL logic error
```
Modifications:
- Not sure what the real cause is, but the problem doesn't occur if there is a sleep between `DELETE` and `VACUUM`, so perhaps `VACUUM` fails because other operations are not done yet. Instead of calling `VACUUM` synchronously, do that in an async queue, which is probably more appropriate since `VACUUM` can be time consuming.
- Fix a bug in the same file where we didn't do `ROLLBACK` when a transaction fails.
> [Collections] Call VACUUM in async queue

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Split out compilation of package plugins so it can be done separately from invoking them (typically for collecting diagnostics up-front) and add a `PluginCompilationResult` type that can be returned to clients.
This allows libSwiftPM clients (and at some point the SwiftPM CLI) to compile plugins separately from running them.
- mark the compilation function public and clean it up a bit while changing it
- add a struct for returning the results of compiling the plugin (including path to .dia file)
- add a unit test for this functionality
> WIP:  Provide libSwiftPM API to allow plugins to be compiled before they are invoked

- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
Spun out of #3838. This makes sure the order of resolution diagnostics is deterministic.
Unlike the first iteration in #3838, this does it properly and preserves the user’s order (which turned out to be much easier than I expected). It also adds a test that would catch any regression, regardless of the resolution mode.
> Improve Resolver Determinism

- Sources/Workspace/WorkspaceState.swift
motivation: state parsing is a "legitimate" error that we handle gracefuly and should not assert on
changes: use StringError instead of InternalError when encountering invalid kind/type attribute
> state file parsing errors should not assert

- Sources/PackageRegistry/RegistryManager.swift
- Tests/PackageRegistryTests/RegistryManagerTests.swift
Continue https://github.com/apple/swift-package-manager/pull/3640 and
polish up the registry client.
> Package registry client

- Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
`VACUUM` causes more problems than benefits, so removing it.
rdar://85368153
> [Collections] Remove VACUUM

- Tests/CommandsTests/APIDiffTests.swift
- Tests/CommandsTests/BuildToolTests.swift
- Tests/CommandsTests/CommandsTestCase.swift
- Tests/CommandsTests/MultiRootSupportTests.swift
- Tests/CommandsTests/PackageRegistryToolTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/CommandsTests/RunToolTests.swift
- Tests/CommandsTests/SwiftToolTests.swift
- Tests/CommandsTests/TestToolTests.swift
This is a test-only change that makes the commands tests robust against any working directory changes done by the tool being tested in the same process (as for example `--package-path` does).
Tests are flaky on the local desktop depending on what order they run in.  Not sure why this doesn't happen more in the CI.  The symptom here is that the test fails when run as part of the test suite but succeeds when run individually.
In the particular case that kept hitting me, `SwiftTools` was run on a test fixture in a temporary directory, changed current working directory to that directory, and then after the temporary directory was removed again, new calls to `SwiftTools` failed with "cannot get current working directory".  Which makes sense, since it had been removed.
- use a common …
> Make the commands tests robust against any working directory changes

- Sources/PackageLoading/TargetSourcesBuilder.swift
- Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
motivation: SwiftPM emits warning on invalid excludes and missing resources definitions for dependencies which is not actionable and noisy
changes:
* in TargetSourcesBuilder check the package type before emiting resources related warnings
* add tests
> dont emit resources or excludes warnings for dependencies

- Package.swift
- Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
- Sources/PackageCollectionsSigningLibc/asn1/a_d2i_fp.c
- Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
- Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
Motivation:
Test and upgrade to the latest swift-crypto [2.0.1](https://github.com/apple/swift-crypto/releases/tag/2.0.1) release, which
includes a BoringSSL update: https://github.com/apple/swift-crypto/pull/95
Modifications:
Tests that use real certs, which execute the OCSP code path, crash on Linux (`swift:5.5` and `swift:5.5-focal` docker images). (rdar://85280061)
The crash happens on L351 of `CertificatePolicy.swift` (`BoringSSLOCSPClient.checkStatus`) because `response`, an `OCSP_RESPONSE` pointer, is `NULL`. It is `NULL` because the logic in BoringSSL's `crypto/asn1/asn1_lib.c` has changed (https://github.com/google/boringssl/commit/ee510f58895c6a88b59f1b66a94939d08ebdfe5b), so the return value needs to be handled differently in `PackageCollectionsSigningLibc/asn1/a_d2i_fp.c`.
I …
> Bump minimum swift-crypto v2 version to 2.0.1

- Sources/SPMTestSupport/PIFTester.swift
- Tests/PackageModelTests/ManifestTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
Spun out of #3838.
Either these tests were only mistakenly disabled behind `ENABLE_TARGET_BASED_DEPENDENCY_RESOLUTION` in the first place, or else the reason for their disabling has since evaporated.
The PIF tests had gone stale and missed some some identifier and setting updates, so those have been repaired.
(I did also update one identifier that is still behind a disabling condition. Otherwise it would have been the only stale PIF identifier left, and it seemed like it belonged together with all the PIF identifiers.)
> Activate Disabled Tests

- Sources/PackagePlugin/PackageModel.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
This brings it in line with SE-0325.
- rename `name` to `displayName` as SE-0325 says
- pass the identity in the serialized data and use it as the `Package.id` instead of a constructed string
- add a unit test that checks the value of display name
> Rename the package `name` property to `displayName` in the plugin API

- Sources/PackageDescription/Version.swift
Motivation: Concrete types are better than `Any`.
Result: This removes an unreachable `default` case, and should result in a bit less runtime cost.
> [NFC] Replace type-erased pattern matching with typed if-else blocks

- Sources/PackageDescription/Version.swift
Semantic Versioning 2.0.0 allows only ASCII alpha-numeric characters and "-" in identifiers.
This change makes version initialization more restrictive, so it _might_ be source breaking.
> Correctly validate characters in semantic version identifiers

- Fixtures/Miscellaneous/TestDiscovery/Async/Package.swift
- Fixtures/Miscellaneous/TestDiscovery/Async/Sources/Async/Async.swift
- Fixtures/Miscellaneous/TestDiscovery/Async/Tests/AsyncTests/SwiftTests.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
Nominating the changes from https://github.com/apple/swift-package-manager/pull/3844 to be pulled back for a 5.5.x dot release.
> [5.5] Add support for correctly discovering async test methods on non-Apple platforms

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/Workspace/ManagedDependency.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: resolution retry + removing of package resolved in failure is difficult to justify
changes: remove the retry code from package resolution and "give up" after one attempt without mutating the package resolved file
> remove resolution retry on resolution failure

- Package.swift
- Sources/Basics/HTTPClient.swift
- Sources/Commands/SwiftPackageRegistryTool.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageLoading/ToolsVersionLoader.swift
- Sources/PackageModel/PackageIdentity.swift
- Sources/PackageRegistry/CMakeLists.txt
- Sources/PackageRegistry/RegistryClient.swift
- Sources/SPMTestSupport/MockDependency.swift
- Sources/SPMTestSupport/MockPackage.swift
- Sources/SPMTestSupport/MockRegistry.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift
- Sources/Workspace/CMakeLists.txt
- Sources/Workspace/RegistryPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageRegistryTests/RegistryManagerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: support registries
changes:
* create RegistryPackageContainer to handle dependencies from registry, integrated with the previously introduces registry client
* update workspace to create RegistryPackageContainer when dealing with registry dependencies
* update registry client (RegitryManager) to perform download request (buffered) when downloading the package archive
* update registry client manifest listing and handling so it supportes multi-manifest setups. simplified the client to return the manifest content instead of attempting to load it which is done in RegistryPackageContainer which has additional context
* update registry client to use Codable
* add testing infrastructure to MockWorkspace to mock registry dependencies
* add basic tests for registry scenarios
> integrate registry dependencies into dependency resolution

- Sources/PackageModel/Manifest.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/PackageModelTests/ManifestTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Spun out of #3838. This contains only the pieces related to identities.
The first commit adds a test against an existing bug in the logic that connects the dependency declarations of a target to their respective packages. Named packages (tools versions 5.2 to 5.5) are not looked up correctly, and the resolver ends up looking for them everywhere, as though the manifest were 5.1 or older. I do not think it can lead to anything breaking, but it does lead to excessive work in the resolver, and in rare cases, to more dependencies being fetched than necessary (If two dependencies have products with the same name, and only one of them is actually used, both will be fetched anyway). The test is only meaningful with target‐based resolution engaged, as legacy resolution overrides the logic with a …
> Fix Identity Resolution

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/SPMTestSupport/MockPackageContainer.swift
- Tests/PackageGraphTests/PubgrubTests.swift
Spun out of #3838. This contains only the pieces related to `PubGrubPackageContainer` and the bug in its caching. The relevant code branches are traversed and tested under both resolution modes. (But I think the context that flushes out the problems never occurs naturally under legacy resolution.)
> Fix PubGrub Container

- Package.swift
Increment SwiftPM tools version to 5.5 and minimum deployment target to 10.15.4 on macOS
Allow use of Swift 5.5 features such as automatic `Codable` synthesis.  Minimum deployment target of 10.15.4 allows use of FileHandle improvements such as `read(upToCount:)`.
> Increment SwiftPM tools version to 5.5 and minimum deployment target to 10.15.4 on macOS

- Sources/SourceControl/GitRepository.swift
Motivation:
Source archives created using the `archive-source` command doesn't
include top-level directory.
Modification:
The trailing slash `/` in the `--prefix` argument to `git archive`,
which is the underlying command for `archive-source`, is required to
create top level directory. Without it the prefix is simply added to all the files and
dirs in the archive.
> Fix archive-source command

- Tests/WorkspaceTests/WorkspaceTests.swift
Spun out of #3838.
This one‐liner fixes `testDuplicateTransitiveIdentityWithoutNames`. The test exists to check the diagnostics of clashing package identities, however one of its paths is also misspelled.
Under legacy resolution, the resolver happens to traverse the graph in an order that first reaches the expected diagnostic before it actually queries the bad path. But under target‐based resolution the resolver is not so lucky, and traverses the graph in an order that attempts to read from the bad path before it detects the identity clash. Attempting to read from the bad path results in the `InMemoryGitRepositoryProvider` failing to look it up (as expected) and crashing on a force‐unwrap. (In the real world outside of the mocking infrastructure, a `GitRepository` in the same situation …
> Fix `testDuplicateTransitiveIdentityWithoutNames`

- Tests/CommandsTests/PackageToolTests.swift
Make tests pass with different version of git installed.
On my system, I have a more recent version of git installed (git version 2.33.1) than comes with Xcode (git version 2.30.1 (Apple Git-130)). This causes the unit test  CommandsTests.PackageToolTests/testArchiveSource to fail.
Remove the test of the version-specific string.
Test will pass on more platforms. This addresses https://bugs.swift.org/browse/SR-15500
> Fix CommandsTests.PackageToolTests/testArchiveSource by removing git version specific error message

- Tests/PackageDescriptionTests/VersionTests.swift
`XCTAssertGreaterThan` only asserts that the "true" path of `>` works, which implies that the "true" path of `<` works, but it doesn't test the "false" path. `XCTAssertFalse` covers the "false" path of `<`.
Motivation: better test coverage
Modifications: added a `XCTAssertFalse(<)` for each `XCTAssertGreaterThan`.
Result: better test coverage
> Test the "false" path of `<`

- Sources/PackageLoading/ManifestLoader.swift
This change set changes the ManifestLoader class to use the new asynchronous `Process.popen()` API, introduced in https://github.com/apple/swift-tools-support-core/pull/261.
Each time `Process.popen()` is used in the current SPM codebase, it blocks a thread by synchronously waiting for a sub-process to finish. This wastes resources (stack memory, thread overhead) and hurts performance.
This change set primarily refactors the parsing and loading methods to use completion blocks in order to support asynchronous execution. Synchronous throwing methods returning type `T`, are replaced with methods that take completion blocks that accept `Result<T, Swift.Error>` parameters, an enum that can hold either type.
Fewer total threads will be blocked, which should reduce the overall number of worker …
> Load manifests asynchronously

- Package.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
Fix iOS minimum deployment annotation and fix compilation error on iOS from plugin changes.
Fixes a build break on iOS.
- set the iOS deployment target to 13.4 to match the macOS 10.15.4 set earlier — this provides access to Swift-friendly Foundation.FileHandle APIs
- conditionalize use of Process APIs that aren't available on iOS, watchOS, tvOS
Be able to build on iOS again.
> Fix iOS minimum deployment annotation and fix compilation error on iOS from plugin changes

- Sources/PackagePlugin/Plugin.swift
Windows UCRT doesn't have `setlinebuf` but does have `setvbuf` (which `setlinbuf` is just a cover for).
Fixes a Windows build failure.
- change `setlinebuf` to `setvbuf`
It works on Windows too.
> Fix a build failure in plugins on Windows

- Sources/PackageLoading/ManifestLoader.swift
This reverts #3872.
This apparently made `testConcurrencyNoWarmUp` very flaky in CI, e.g. https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/1799/ and https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/1801/, so we need to revert for now in order to not block Swift CI.
> Revert "Load manifests asynchronously (#3872)"

- Sources/Basics/SQLiteBackedCache.swift
motivation: on some platforms sqlite is not safe to access concuurently, so never assume it is safe
changes: always run the process code inside the sqlite access lock
rdar://85856852
> address race condition in platforms where sqlite is not safe to access concurrently

- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackagePlugin/Context.swift
- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Add ability to pass down a list of additional search paths to a plugin, and use them when looking up the plugin.  Configure call sites to pass down the toolchain bin directory.
This implements part of the design of plugins: they have access to binary executables and built executables that they declare dependencies on, plus what is in the toolchain.
- Add ability to pass down a list of additional search paths to a plugin, and use them when looking up the plugin.
- Configure call sites to pass down the toolchain bin directory.
- Extend a unit test to check that it works.
> Allow plugins to look up tools from the toolchain (such as `docc`)

- Documentation/Registry.md
Motivation:
`RegistryClient` relies on the HTTP `Link` header returned by the `/{scope}/{name}/{version}/Package.swift` endpoint to know the existence of alternative manifests.
Modification:
Update registry server API spec to make `Link` required in the response for `/{scope}/{name}/{version}/Package.swift`. For requests that include the `swift-version` query param, the server is not required to set `Link`.
> [Registry] Update server API spec for the fetch manifest endpoint

- Sources/Basics/ConcurrencyHelpers.swift
- Tests/PackageLoadingTests/PDLoadingTests.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
Fix a thread sanitizer warning
When running thread sanitizer with unit tests, there was a thread writing and another thread reading warning.
Switch to using ThreadSafeBox<T> to do the reading and writing protected by a lock.
Thread sanitizer no longer warns.
> Thread sanitize package loading tests

- Sources/Commands/SwiftTool.swift
Motivation:
The migration from `.swiftpm/config` to `.swiftpm/configuration/mirrors.json` moves `.swiftpm/config` and leads user to think that the file gets deleted. (rdar://85917746)
Modifications:
- Copy `.swiftpm/config` to `.swiftpm/configuration/mirrors.json` instead of moving it.
- Emit warning that `.swiftpm/config` has been deprecated.
- Don't perform the migration if `.swiftpm/configuration/mirrors.json` already exists to prevent error. (rdar://85917836)
> Mirrors config migration should not modify user's file

- Sources/PackageLoading/ContextModel.swift
Fixes a compiler warning.
Nobody likes warnings.
Just use `import Foundation`
Warnings are gone.
> Don't use scoped imports when building with library evolution enabled

- Sources/Basics/Observability.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
- Tests/PackageGraphTests/PubgrubTests.swift
motivation: less warnings, happier developers
changes:
* update use of deprecated package and manifest name attributes
* remove setting of legacyLocation diagnostic metadata which is no longer in use
> clear warnings

- Package.swift
- Sources/PackageLoading/CMakeLists.txt
- Sources/PackageLoading/PkgConfig.swift
- Sources/PackageLoading/Target+PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
- Tests/PackageLoadingTests/PkgConfigTests.swift
- Tests/PackageLoadingTests/pkgconfigInputs/deps_variable.pc
- Tests/PackageLoadingTests/pkgconfigInputs/empty_cflags.pc
- Tests/PackageLoadingTests/pkgconfigInputs/escaped_spaces.pc
- Tests/PackageLoadingTests/pkgconfigInputs/failure_case.pc
- Tests/PackageLoadingTests/pkgconfigInputs/freetype2.pc
- Tests/PackageLoadingTests/pkgconfigInputs/gobject-2.0.pc
- Tests/PackageLoadingTests/pkgconfigInputs/gtk+-3.0.pc
- Tests/PackageLoadingTests/pkgconfigInputs/harfbuzz.pc
- Tests/PackageLoadingTests/pkgconfigInputs/libffi.pc
- Tests/PackageLoadingTests/pkgconfigInputs/quotes_failure.pc
motivation: PkgConfig was moved from SwiftPM into TSC, but really is closer to SwiftPM (not generic enough) and would be easier to maintain within SwiftPM itself
changes:
* copy the PkgConfig code into SwiftPM
* replace use of DiagnosticsEngine with ObservabilityScope
* minor cleanup (more needed, epecially use of statics)
* also copy and adjust tests
> move PkgConfig frmo TSC into SwiftPM

- Fixtures/Miscellaneous/TestDiscovery/Async/Tests/AsyncTests/SwiftTests.swift
This fixes a compilation problem when running tests under SPM.
If running unit tests with SPM like so:
swift test --sanitize=thread --filter FunctionalTests.TestDiscoveryTests/testAsyncMethods
The test fails with these errors:
```
/private/var/folders/s3/556s8dsd7y9272mxm7rydmsr00056_/T/Miscellaneous_TestDiscovery_Async.Guycrz/Miscellaneous_TestDiscovery_Async/Tests/AsyncTests/SwiftTests.swift:6:22: error: concurrency is only available in macOS 12.0.0 or newer
func testAsync() async {
^
```
This change fixes the problem.
Add `@available` attribute to the `AsyncTests` class in the test fixture.
Test now passes when run under SPM.
> Add @available attribute to testAsyncMethods fixture

- Sources/PackageRegistry/RegistryClient.swift
Per the [API spec](https://github.com/apple/swift-package-manager/blob/main/Documentation/Registry.md#41-list-package-releases), a release's `url` field in the "list package releases" (`GET /{scope}/{name}`) API response is optional.
> [Registry] Package release 'url' is optional

- Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
- Sources/Basics/Sandbox.swift
- Sources/Build/BuildOperation.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/APIDigester.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftRunTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/BasicsTests/SandboxTests.swift
Sandboxing was already applied to the running of plugins, but for `buildTool` plugins, they were not to the commands they provide for the build system to run.
Since the plugin can configure commands in any way it wants to, they need to be just as sandboxed as the plugin.
This change applies the sandbox to the regular build commands and to the prebuild commands returned by `buildTool` plugins.
It also fixes a related bug that caused the sandboxing of plugins in general to ignore the `disable-sandbox` option, which is documented to disable sandboxing for all subprocesses.
Since many Foundation functions requires that the non-persistent temporary directory be writable, this also adds a new strictness level that allows this, and uses that when invoking the build commands.  Without this, many …
> Apply sandbox to commands generated by build tools (on platforms that support sandboxing)

- Sources/Workspace/ResolverPrecomputationProvider.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: take advantage of precomputation resolution
changes:
* extend condition of ResolverPrecomputationProvider::LocalPackageContainer to handler registry based depndencies along side source control ones
* include error details when precomputation resolution fails in the general / unknown case
> adjust precomputation resolution to registry based dependencies

- Sources/Build/BuildOperation.swift
motivation: BuildOperation::buildPackageStructure may fail due to legitimate deepndecy resolution issues
changes:
* do not throw a control flow error when BuildOperation::buildPackageStructure failes, instead return a boolean
* use boolean from BuildOperation::buildPackageStructure to define the control flow in getBuildDescription
rdar://85461964
> fix error handling in BuildOperation::buildPackageStructure

- Sources/Basics/Sandbox.swift
It seems that `TSCBasic.determineTempDirectory()` lets environment variables override the temporary directory, which might be alright for the process itself but not necessarily for spawned subprocesses.  If the subprocess uses NSTemporaryDirectory(), then that still won't be covered by the sandbox.
This change makes sure that it is covered by the sandbox, and uses a set to avoid duplicates (which wouldn't actually hurt but is inelegant).
This fixes a CI problem such as seen in https://ci.swift.org/job/oss-swift-package-macos/6399.
- add NSTemporaryDirectory() to the set of writable directories in the sandbox, and don't just rely on TSC's notion of the temporary directory
- use a set to avoid duplicates
It's interesting to note that the PR build passed.  Perhaps the set of environment …
> Make sure that NSTemporaryDirectory() is included in the sandbox when `writableTemporaryDirectory` is set

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This is an optimization that skips the compilation step of a package plugin if a compiled version already exists, if none of the input files have changed, and if none of the compiler flags have changed.
Better performance by avoiding unnecessary work.
- compute hash of the input conditions and store it next to the compiled executable
- if the compiled executable exists and the hash is the same since the next time, skip compiling
- add a field to the compilation result structure to reflect whether the compilation was cached
- extend a unit test to verify that diagnostics (e.g. warnings) are still emitted
No functional change, but less time spent compiling plugins.
rdar://74663095
> Only recompile plugin scripts to executables when needed

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
Initial version of the `--list` option for command plugins.  This shows each command, along with the target and package that provides them.  A later change can easily refine this to also list the intent (separately from the command).
This is useful and is a part of the proposal SE-0332.
- add a `--list` option to `swift package plugin`
- extend a unit test
Invoking `swift package plugin --list` now shows all available command plugins, initially in the form:
`‘mycmd’ (plugin ‘MyPlugin’ in package ‘MyPackage’)`
We could refine this to also group by intent, and should also show the description where there is a custom intent.  Suggestions are welcome.
> Initial version of the `--list` option for command plugins

- Package.swift
- Sources/tsan_utils/include/module.modulemap
- Sources/tsan_utils/include/tsan_utils.h
- Sources/tsan_utils/tsan_utils.c
- Tests/BasicsTests/SQLiteBackedCacheTests.swift
- Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
This change set disables a few tests that cause hangs when the thread sanitizer is used.
A few tests hang when run under the thread sanitizer. These changes provide a workaround.
Added a small C module, tsan_utils with one function, is_tsan_enabled(). This simply tests the compile-time environment for the flags that indicate thread sanitizer support has been compiled in. This is called from these tests:
```
PackageCollectionsTests.PackageCollectionsStorageTests/testFileDeleted
PackageCollectionsTests.PackageCollectionsStorageTests/testFileCorrupt
BasicsTests.SQLiteBackedCacheTests/testFileDeleted
BasicsTests.SQLiteBackedCacheTests/testFileCorrupt
```
to disable them at runtime if the thread sanitizer is enabled.
No more test hangs under thread sanitizer.
> Add thread sanitizer utilities (tsan_utils)

- Sources/Basics/Sandbox.swift
This is the 5.6 cherry-pick of #3918 and its refinement #3920.
This change makes the sandbox cover the regular "/tmp" and NSTemporaryDirectory() paths.  If environment entries are used to set other temporary directories in the subprocess, then the calling code should pass those to the `writableDirectories` parameter.
rdar://86150592
(cherry picked from commit 5546a97a5d48ab170b625bede6cd030ba2f1c962 and  3ba330585206c717c6e2067d0a9f24e298ffe88c)
> [5.6] Make sure that NSTemporaryDirectory() is included when `writableTemporaryDirectory` is set.

- Sources/Commands/SwiftPackageTool.swift
- Sources/PackagePlugin/Path.swift
- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
Add the ability to pass an output path to command plugins.  This output path is given to the plugin and is added to the sandbox as a place to which it can write.
This is a proposed amendment to the SE-0332 proposal currently being reviewed.
Like all plugins, command plugins are run in a sandbox that only provides write access to temporary directories.  But it's quite common for a plugin to generate output, so there needs to be a way for a user to provide the path to the command and for SwiftPM to add that as a writable path to the sandbox.  This path can be either a directory or a file — it's up to the plugin to decide what it creates at that path.
- extend the plugin protocol to have a `outputPath` parameter
- add compatibility glue to allow existing plugins to continue working
- add the …
> Add the ability to pass an output path to command plugins

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
5.6 cherry-pick of #3915 
This is an optimization that skips the compilation step of a package plugin if a compiled version already exists, if none of the input files have changed, and if none of the compiler flags have changed.
rdar://74663095
(cherry picked from commit 1148eed8eab9da8d7c6ff17b34270e00897ea836)
> [5.6] Only recompile plugin scripts to executables when needed (#3915)

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
This is the 5.6 cherry-pick of #3916 
It shows the command, along with the target and package that provides them.  A later change can easily refine this to also list the intent (separately from the command).
(cherry picked from commit 8ebbc236ac4305642ed77ae12d41f9339a3c5f78)
> [5.6] Implement the `--list` option for command plugins. (#3916)

- Sources/Basics/Sandbox.swift
Specifically, we add regular and the Foundation temporary directories, but not anything passed in through the environment.
This reduces the amount of magic and unpredictability regarding what's in the profile.  Client code that wants to add additional directories can do so using the array of writable paths that's already supported.
- change the sandbox profile creation to just add `"/tmp"` and `NSTemporaryDirectory()`
> Simplify the adding of temporary directories to the sandbox profile when strictness is 'writableTemporaryDirectory'

- CHANGELOG.md
- Sources/PackageDescription/PackageDependency.swift
- Sources/PackageDescription/PackageRequirement.swift
motivation: preserve source compatibility
changes:
* re-introduce Package.Dependency.Requirement::upToNextMajor and ::upToNextMinor
* mark  Package.Dependency.Requirement::upToNextMajor and ::upToNextMinor as @_disfavoredOverload to disambiguate from the extension on Range
* add relevant API docs
* fix a few typos in docs
rdar://86041332
> re-introduce Package.Dependency.Requirement::upToNextMajor and ::upToNextMinor

- Package.swift
- Sources/Basics/FileSystem+Extensions.swift
- Sources/Commands/CMakeLists.txt
- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
- Sources/PackageFingerprint/Model.swift
- Sources/PackageFingerprint/PackageFingerprintStorage.swift
- Sources/PackageRegistry/CMakeLists.txt
- Sources/PackageRegistry/RegistryClient.swift
- Sources/SPMTestSupport/InMemoryGitRepository.swift
- Sources/SPMTestSupport/MockPackage.swift
- Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
- Sources/SPMTestSupport/MockRegistry.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/CMakeLists.txt
- Sources/Workspace/SourceControlPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This is a continuation of https://github.com/apple/swift-package-manager/pull/3879.
Wire up fingerprint storage such that it is used for integrity checks of package downloads. Fingerprint must match previously recorded value (if any) or else it would result in an error.
> Implement TOFU for package downloads

- CHANGELOG.md
- Sources/PackageDescription/PackageDependency.swift
- Sources/PackageDescription/PackageRequirement.swift
> [5.6] re-introduce Package.Dependency.Requirement::upToNextMajor and ::upToNextMinor

- Sources/Commands/SwiftTool.swift
- Sources/PackageFingerprint/Model.swift
- Sources/PackageFingerprint/PackageFingerprintStorage.swift
- Sources/PackageRegistry/RegistryClient.swift
- Sources/Workspace/SourceControlPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
Motivation:
Source compat test failure: https://ci.swift.org/job/swift-PR-source-compat-suite/5701/artifact/swift-source-compat-suite/
```
error: Failed to get source control fingerprint for swift-log remoteSourceControl https://github.com/apple/swift-log.git version 1.4.2 from storage: Error Domain=NSCocoaErrorDomain Code=513 "You don't have permission to save the file "fingerprints" in the folder "security"." UserInfo={NSFilePath=/Users/buildnode/.swiftpm/security/fingerprints, NSUnderlyingError=0x7feaae439370 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error: Error Domain=NSCocoaErrorDomain Code=513 "You don't have permission to save the file "fingerprints" in the folder "security"." UserInfo={NSFilePath=/Users/buildnode/.swiftpm/security/fingerprints, …
```
> Disable fingerprint checking when storage is not available

- Sources/PackageLoading/ToolsVersionLoader.swift
- Sources/PackageRegistry/RegistryClient.swift
- Sources/Workspace/RegistryPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: improve performance by reducing redundant http calls
changes:
* save main manifest on first request
* cache known manifest across calls in RegistryPackageContainer
* add RegistryPackageContainer tests
* fix a bug in workspace where custom tools version is not propogated to the toolsLoader
rdar://86218181
> optimize manifest requests for registry based depedendcies

- Sources/PackageGraph/GraphLoadingNode.swift
- Sources/PackageGraph/PackageContainer.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/SPMTestSupport/MockPackageContainer.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SPMTestSupport/misc.swift
- Sources/Workspace/Diagnostics.swift
- Sources/Workspace/FileSystemPackageContainer.swift
- Sources/Workspace/ManagedDependency.swift
- Sources/Workspace/ResolverPrecomputationProvider.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceState.swift
- Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Currently, we have the ability to provide a custom file system to the whole workspace and we partially use git-backed file system during package resolution. This change aims to allow using a custom file system when running `PackageBuilder` as well which e.g. allows to load a graph without having full checkouts of every package.
To utilize this feature, clients of `Workspace` can pass a custom `PackageContainerProvider` and use the new `CustomPackageContainer` protocol.
> Optionally use a per-package filesystem for `PackageBuilder`

- Sources/Commands/SwiftTool.swift
It continues to cause failures in the source compatibility test.
> Disable TOFU feature temporarily

- CMakeLists.txt
- CONTRIBUTING.md
- Package.swift
- Sources/Basics/CMakeLists.txt
- Sources/Basics/FileSystem+Extensions.swift
- Utilities/bootstrap
motivation: SwiftSystem provides infra that can replace some bespoke implementations in TSC and SwiftPM, improving the cross-platform support
changes: add SwiftPM and CMake setup for including SwiftSystem as a dependency
> begin to integrate SwiftSystem

- Sources/PackageGraph/PinsStore.swift
motivation: We moved to JSONEncoder in 5.6 which formats JSON in a non-traditional way (add space around the field name colon), and different from previous version of SwiftPM. We can make the change tools-version dependent.
changes: user older JSON encoder when tools-version < 5.6, preserving previous format
rdar://86341850
> preserve old formatting of Package.resolved in tools-version < 5.6

- Sources/Commands/SwiftTool.swift
Motivation:
Source compat test continues to fail even with https://github.com/apple/swift-package-manager/pull/3928:
```
"You don’t have permission to save the file “fingerprints” in the folder “security”
```
https://ci.swift.org/job/swift-PR-source-compat-suite/5709/artifact/
The tests we did with https://github.com/apple/swift-package-manager/pull/3938 shows that we can create directories but not write files.
Modifications:
Test creating `security` directory and writing file in it, and disable TOFU feature if the test fails.
> Create 'security' directory test should try writing files too

- Package.swift
Tested BoringSSL changes with `swift:5.5-focal` docker image.
> Update to swift-crypto 2.0.3

- Sources/PackageRegistry/RegistryClient.swift
- Sources/Workspace/SourceControlPackageContainer.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
Per review feedback, reverting part of the changes introduced in https://github.com/apple/swift-package-manager/pull/3928.
> Throw fingerprint write errors

- Sources/PackageGraph/PinsStore.swift
> [5.6] preserve old formatting of Package.resolved in tools-version < 5.6 (#3931)

- Sources/Commands/SwiftTool.swift
- Sources/PackageFingerprint/Model.swift
- Sources/PackageFingerprint/PackageFingerprintStorage.swift
- Sources/PackageRegistry/RegistryClient.swift
- Sources/Workspace/SourceControlPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/3928, https://github.com/apple/swift-package-manager/pull/3936, https://github.com/apple/swift-package-manager/pull/3932, https://github.com/apple/swift-package-manager/pull/3941 to 5.6
> [5.6] Cherry-pick TOFU changes from main branch

- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageDescription/PackageDescriptionSerialization.swift
- Sources/PackageDescription/Target.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Sources/PackagePlugin/PackageManagerProxy.swift
- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
This adjusts the implementation to match https://github.com/apple/swift-evolution/pull/1496
Specifically:
- removes the `outputPath` parameter to the plugin again
- renamed `outcome` property to `result` in the tests
- change the `PluginCommandIntent` and `PluginPermission` enums into opaque structs, with static constructor functions for the enum cases
> Adjust command plugin implementation to match SE-0332 amendments

- Sources/Commands/SwiftPackageTool.swift
A previous commit removed the parameter to the plugin invocation and made the option not do anything, but this removes it from `swift package plugin` as well.
This is to align with SE-0332.
- remove the command line option (it was still present but didn't do anything)
> Actually remove the `--output` option from `swift package plugin`

- Sources/PackageRegistry/RegistryClient.swift
Per [API spec](https://github.com/apple/swift-package-manager/blob/main/Documentation/Registry.md#42-fetch-information-about-a-package-release), `metadata` is optional:
> A server MAY include metadata in its package release response.
> [Registry] Package release 'metadata' is optional

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
- Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Utilities/Docker/docker-compose.2004.55.yaml
- Utilities/Docker/docker-compose.yaml
motivation: use idiomatic location for security directory on macOS
changes:
* allow users to customize security directory location with new --security-path CLI option
* on macOS use <user>/Library/org.swiftpm/security for security files and symlink from ~/.swiftpm/security
* move configuration directory from <user>/Library/org.swiftpm to <user>/Library/org.swiftpm/configuration
* add migration code from old configuraiton location to new one
* update docker setup for new locations
> use idiomatic location for security directory and update location of configuration directory

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageGraphTests/PubgrubTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
motivation: less warngings, happier developers
changes:
* use package identity instead of deprecated manifest name
> fix a warning on linux

- Tests/CommandsTests/BuildToolTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/CommandsTests/RunToolTests.swift
- Tests/CommandsTests/TestToolTests.swift
motivation: broken tests when warnings are present in stderr
changes: use XCTAssertMatch and check for error instead of straight comparison
> make tests that check stderr more robust

- Sources/Basics/FileSystem+Extensions.swift
motivation: some tests run SwiftPM processes in parallel causing contention on ~/.swiftpm which can cause to test failures
changes: local ~/.swiftpm before reading / writing subdirectories
rdar://86586729
> protect ~/.swiftpm from concurrent access

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
- Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/CommandsTests/BuildToolTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/CommandsTests/RunToolTests.swift
- Tests/CommandsTests/TestToolTests.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Utilities/Docker/docker-compose.2004.55.yaml
- Utilities/Docker/docker-compose.yaml
cherry-pick #3942, #3951, #3952 into 5.6
> [5.6] use idiomatic location for security directory and update location of configuration directory (#3942)

- Fixtures/Miscellaneous/InvalidRefs/InvalidBranch/Package.swift
- Fixtures/Miscellaneous/InvalidRefs/InvalidRevision/Package.swift
- Package.swift
- Sources/PackageGraph/PackageGraphRoot.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/SPMTestSupport/InMemoryGitRepository.swift
- Sources/SourceControl/GitRepository.swift
- Sources/SourceControl/Repository.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
motivation: all access to git operations should be done via the repositoriesProvider handed to the workspace, but some was hard wired to using Git
changes:
* move git related validation from manfeist JSON parser and graph loader to workspace and use the workspace repositoryProvider to perform them
* add methods on RepositoryProvider to hande validation of directory and ref formats.
* remove PackageLoading depedency on SourceControl which was a problem for a while and only needed for these validations
rdar://84393257
> move manifest validation that requires source control to Workspace

- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
motivation: with manfiest loading async, the concurrent loading tests introduce significant contention on cpu since the underlying queue in unbounded
changes: use semaphore to limit the concurrency to max active cpus
> reduce concurrent manifest loading test contention

- CONTRIBUTING.md
Unit tests fail if ran with the incorrect Xcode scheme. [This can trip up newcomers](https://forums.swift.org/t/spm-support-basic-auth-for-non-git-binary-dependency-hosts/37878/65). This PR improves the docs accordingly.
> Specify which Xcode scheme to use to run unit tests

- Fixtures/Miscellaneous/InvalidRefs/InvalidBranch/Package.swift
- Fixtures/Miscellaneous/InvalidRefs/InvalidRevision/Package.swift
- Package.swift
- Sources/PackageGraph/PackageGraphRoot.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/SPMTestSupport/InMemoryGitRepository.swift
- Sources/SourceControl/GitRepository.swift
- Sources/SourceControl/Repository.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
> [5.6] move manifest validation that requires source control to Workspace (#3955)

- Sources/Basics/ByteString+Extensions.swift
- Sources/Workspace/Workspace.swift
motivation: simplify logic around which SHA256 implementation to use
changes: always call SHA256 which abstracts over platform differences
> adjust to TSC SHA256 API changes

- Sources/PackageLoading/ManifestLoader.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
This is a cherry pick of PR #3894 on to the release/5.6 branch.
> [5.6] Load manifests asynchronously [cherry pick]

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
There's no strong ordering between the free form output of a plugin and the diagnostics it emits, but for things like thrown exceptions etc, it makes a bit more sense to show the diagnostic last.
Perhaps the test shouldn't really depend on the order here — we will see if this addresses the issue in the CI (it seems specific to Linux and I was never able to reproduce it in Docker).
Fix a flaky test in CI, but also to make the order of output from the end of the plugin execution make a little more sense when it exits by throwing an error.
- after process termination, read the last text output before any diagnostics
- I also made the unit test text a little less whimsical, and got rid of the emoji annotating the plugin output, and added printing out of the received diagnostics …
> Fix an ordering issue of a print statement and a diagnostic arriving right at the exit of a plugin

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/3964
> [5.6] Fix an ordering issue of a print statement and a diagnostic arriving right at the exit of a plugin

- Package.swift
Tools depending on `release/5.6` branch of SwiftPM together with `release/5.6` branch of TSC fail to build due to conflicting dependencies.
`relatedDependenciesBranch` now is set to `release/5.6` instead of `main` when SwiftPM `release/5.6` branch is checked out. This makes dependencies consistent and resolvable when other Swift tools are included in the dependency tree. 
Tools depending on `release/5.6` branch of SwiftPM can be built without failures.
> [5.6] Set `relatedDependenciesBranch` to `release/5.6`

- CHANGELOG.md
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageDescription/Target.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
Mark command plugins as 5.6 instead of 999.0 now that SE-0332 has been accepted, and remove the feature flag that controls it.
Allows packages with a 5.6 tools version to define command plugins.
- Change 999.0 to 5.6 in the right places
- Remove the feature flag that controls it
This change will also be nominated for the `release/5.6` branch.
> Mark command plugins as 5.6 instead of 999.0 now that SE-0332 has been accepted

- Sources/Workspace/ManagedArtifact.swift
- Sources/Workspace/ManagedDependency.swift
- Sources/Workspace/WorkspaceState.swift
- Tests/WorkspaceTests/WorkspaceStateTests.swift
motivation: some older versions of SwiftPM wrote duplicate entries into workspace-state.json which can cause a crash due to use of Dictionary::uniquingKeysWith
changes:
* do not use Dictionary::uniquingKeysWith for non-santized input such as workspace state
* add tests
rdar://86857825
> gracefully fail workspace state loading when duplicate entries found

- CHANGELOG.md
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageDescription/Target.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
5.6 branch cherry-pick of https://github.com/apple/swift-package-manager/pull/3969.
> [5.6] Mark command plugins as 5.6 instead of 999.0 now that SE-0332 has been accepted (#3969

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
Allow package plugins to be invoked using just `swift package`, and not require `swift package plugin`.  The `plugin` subcommand remains, especially for things like `--list` and future plugin-specific subcommands.
This is part of the SE-0332 proposal.  Requiring the `plugins` spelling was always temporary.
- set `plugin` as the default subcommand for `swift package`
- fix the error messages to be clearer, and to use the swift-argument-parser `ValidationError` where appropriate (this also emits the help text)
- extend unit test to check that both with `plugin` and without `plugin` spelling work
Invoking `swift package foo` will fall back on `swift package plugin foo` if `foo` is not a built-in command.
rdar://87077988
> Allow package plugins to be invoked using just `swift package`, and not require `swift package plugin`.

- Sources/Commands/SwiftPackageTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
This adds an option that was spelled out in the proposal.  Also adds an additional useful option to specify arbitrary directories to allow the plugin to write to, which is helpful for plugins that have their own output arguments.
- adds `--allow-writing-to-package-directory` as described in SE-0332
- also adds `--allow-writing-to-directory`, which takes a relative or absolute path as an argument
- also adds `--block-writing-to-temporary-directory` to provide control over whether the temporary directories can be written to
It also adds in the error to message that is shown if writing to the package directory isn't allowed, which includes the stated reason the plugin provided for why it needs this access.
rdar://86786404
> Support `--allow-writing-to-package-directory` as described in SE-0332 and `--allow-writing-to-directory` to allow arbitrary directories

- Sources/Commands/SwiftPackageTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/3972
> [5.6] Support `--allow-writing-to-package-directory` as described in SE-0332 and `--allow-writing-to-directory` to allow arbitrary directories (#3972)

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
> [5.6] Allow package plugins to be invoked using just `swift package`, and not require `swift package plugin` (#3977)

- Sources/Commands/SwiftPackageTool.swift
It is noisy and makes the plugin commands look very different from the built in commands, which is opposite of the long-term goal.
- change the output string to not include the prefix
rdar://86855690
> Don't prefix each line of command plugin output with the name of the plugin

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
This makes it possible for tools to use regular commands expected to be in `/usr/bin` etc and which should appropriate to embed as an artifact archive in a package.
- add the standard set of search paths to the list we already pass down to the plugin (and which includes the toolchain etc)
> Include the default command search paths for plugin tool lookup

- Sources/Commands/SwiftPackageTool.swift
This is the 5.6 cherry pick of https://github.com/apple/swift-package-manager/pull/3983.
> [5.6] Don't prefix each line of command plugin output with the name of the plugin (#3983)

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
Nominating https://github.com/apple/swift-package-manager/pull/3984 for SwiftPM 5.6.
> [5.6] Include the default command search paths for plugin tool lookup. (#3984)

- Fixtures/Miscellaneous/TestDiscovery/Async/Tests/AsyncTests/SwiftTests.swift
- Fixtures/Miscellaneous/TestDiscovery/Deprecation/Package.swift
- Fixtures/Miscellaneous/TestDiscovery/Deprecation/Sources/Simple/Simple.swift
- Fixtures/Miscellaneous/TestDiscovery/Deprecation/Tests/SimpleTests/SwiftTests.swift
- Fixtures/Miscellaneous/TestDiscovery/Simple/Tests/SimpleTests/SwiftTests.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/LLBuildManifest/Tools.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
motivation: do not prduce warning when tests are marked as deprecated, since they are designed to test deprecated functionality
changes:
* mark generated test-discovery wrappers as psuedo-deprecated so they dont produce deprecation warnings
* use @main for the test discovery entry point instead of main.swift which helps avoid deprecation warnings at the entry point
* cleanup test discovery generate  names to be easier to reason about
* add and adjust tests for throwing variants
* add test for deprecation use case
> avoid deprecation warnings from test discovery

- Sources/Build/BuildPlan.swift
motivation: small follow up cleanup to #3992 which consolidates the use of a share definition for the test discovery main file name
changes: use the shared definition for the main file name used for test discovery everywhere
> cleanup use test-discovery main file name

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageGraphTests/PubgrubTests.swift
motivation: dependency resolution could be incorrect in some edge cases when a pre-release requirement is specified, and not report the issue to the user
changes:
* depedency resolustion should not assume 0.0.0 is the correct minimal requirment, instead it should use the specified version
* fix dependency term computation which used incorrect version requirment for the the parent node
* add validation at the end of package udpate API to make sure no missing packages exist after resolution, and fail the operation if such exists. this mirrors the behavior of package resolve API
> fix dependency resolution edge cases issues

- CHANGELOG.md
motivation: document user visible changes in change log
changes: Update CHANGELOG to include deprecation of dependency requirement enum calling convention
> Update CHANGELOG to describe manifest API changes

- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SymbolGraphExtract.swift
- Tests/CommandsTests/PackageToolTests.swift
This includes reworking the SymbolGraphExtract type that so it's more suitable for being called in the context of plugins.
The symbol graph extraction support for plugins called into the existing SymbolGraphExtract type, but this type was more suited to use from the command line action, and this caused some bugs for its use from plugins.
This PR refactors SymbolGraphExtract to hoist the assumptions about things like destination path out into the caller, and adjusts the call sites.
- factor out assumptions and console output from SymbolGraphExtract to the caller
- when used for plugins, avoid generate symbol graph information for targets other than the one asked for
- use a unique symbol graph output directory for each package/target combination
- add a unit test with better checking for …
> Make the symbol graph extraction requested by plugins more robust

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageGraphTests/PubgrubTests.swift
> [5.6] fix dependency resolution edge cases issues (#3985)

- Sources/Basics/Sandbox.swift
- Sources/Build/BuildOperation.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/BasicsTests/SandboxTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Enforce read-only-ness of package directory even when it's inside `/tmp` and other writable directories to the number of reduce special cases.
The package directory should always be read-only unless specifically requested to be writable, even if it happens to be in `/tmp` or other implicitly writable locations.
The sandbox supports a list of `writableDirectories`, which are treated as path component prefixes after package resolution.  The are applied to the sandbox rules after the default-deny and everything-is-read-only rules, carving out cones of writability in specific areas of the file system.
But if the package directory is under one of these directories that is allowed by default, then it is implicitly writable even in the absence `--allow-writing-to-package-directory`.  It also …
> Enforce read-only-ness of package directory even when it's inside writable directories

- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SymbolGraphExtract.swift
- Tests/CommandsTests/PackageToolTests.swift
This is the 5.6 nomination of https://github.com/apple/swift-package-manager/pull/3993.
> [5.6] Make the symbol graph extraction requested by plugins more robust (#3993)

- Sources/Basics/Sandbox.swift
- Sources/Build/BuildOperation.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/BasicsTests/SandboxTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
5.6 cherrypick of https://github.com/apple/swift-package-manager/pull/3996
> [5.6] Enforce read-only-ness of package directory even when it's inside writable directories (#3996)

- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageModel/Target.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Make sure that `.docc` bundles (and in the future, any other files that have built-in rules that mark them as ignored) are still passed through to plugins.  Note that this is separate from files marked as excluded by the manifest, with are filtered out at an earlier stage and never seen by plugins or the internal logic.
Plugins such as documentation generations need to be able to see `.docc` files without having to look in the file system.  It was a bug that ignored files were not being passed through, as all other files were.
There was a special rule added in 5.5 to mark .docc bundles as ignored, so that there wouldn't be warnings about packages that contained them (since Xcode could deal with them but SwiftPM couldn't).  But that also caused `.docc` files to become filtered out of the …
> Don't filter out `.docc` bundles from the list of target source files provided to plugins

- Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
- Tests/PackageCollectionsSigningTests/CertificateTests.swift
- Tests/PackageCollectionsSigningTests/KeyTests+EC.swift
- Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift
- Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
- Tests/PackageCollectionsSigningTests/SignatureTests.swift
- Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
- Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
- Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Motivation:
Started seeing Git related errors in package collection tests.
Modifications:
Pass `createGitRepo: false` to `fixture` since the tests don't involve Git repos.
> Set 'createGitRepo: false' in test fixtures

- Package.swift
Adds an auto linked variant of SwiftPMDataModel library.
We want to statically link to `SwiftPMDataModel` library in a [CLI app](https://github.com/swiftwasm/carton) to resolve [duplicate symbols issues](https://github.com/swiftwasm/carton/issues/274).
Directly adds another build product. This is already solved [more generically](https://github.com/yonihemi/swift-package-manager/blob/d644f4d0577c2c7f4074ea322134a492e229a796/Package.swift#L54) on `main` but we're still relying on the 5.5 branch.
> [5.5] Add automatic library product for SwiftPMDataModel

- Sources/Basics/DispatchTimeInterval+Extensions.swift
- Sources/Commands/CMakeLists.txt
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/TestingSupport.swift
- Sources/Workspace/UserToolchain.swift
- Tests/CommandsTests/PackageToolTests.swift
This wraps up the last piece for SE-0332, including support for filtering and for capturing code coverage while the tests are running.
This is specified in SE-0332 (it's the last part of SE-0332 that wasn't yet merged).
- add support to running tests in a similar manner as `SwiftTestTool`, reusing much of the implementation of `swift test`
- factor out some of the `SwiftTestTool` methods so they they can be invoked on request from plugins too
This uses most of the same implementation that existed in a very specify way in SwiftTestTool.swift, factoring it out into a new shared `TestingSupport.swift` file and making it more generic.  Future refactoring should move it down to a new module that provides the shared test support for use from everywhere.
> Allow running tests from a command plugin

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
motivation: improve dependency resolution performance
changes:
* add informational diagnostics on manifest cache hit/miss
* disable expensive optimization in pubgrub resolver that has no functional value given changes from  #3985
* adjust resolver workspace delegate to be less noisy given the difference in resolution callbacks
follow on from https://github.com/apple/swift-package-manager/pull/4006
> dependency resolution performance

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
5.6 cherry pick of #4007
Explanation:
Fixed dependency resolution issues causing failure on edge cases such with pre-release versions. as a result of that fix, the bounds computation done as part of the resolution is no longer requires which removes a significant performance bottleneck. this PR removes the bounds computation yielding 3x performance improvement on medium to large projects. 
The bounds computation was originally added in [aee02eb](https://github.com/apple/swift-package-manager/commit/aee02eb246442bcc28119101b89feee1d54110b4) in an attempt to improve diagnostics when graph fail to be resolve. https://github.com/apple/swift-package-manager/pull/3985 changes how the underlying data for these diagnostics is captured which yield even better diagnostics. as such this PR is purely …
> [5.6] dependency resolution performance (#4007)

- Sources/Commands/SwiftPackageTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This allows relative paths passed as parameters to work.  For build tool plugins we pass in the package directory so that relative paths in configuration files work there as well.  This also matches the behavior of many build systems.  The proposal didn't specify the initial working directory and usually all paths are absolute, but having predictable initial working directories follows the principle of least surprise.
- pass through the working directory as a parameter to the plugin invocation
- for build tool invocations, make it the package directory
- for command invocations, keep the original working directory
rdar://86831942
> Package command plugins should have the same initial working directory as the invocation

- Sources/Workspace/Workspace.swift
Limit the concurrent HTTP requests for downloading binary dependencies to 8 concurrent requests.
We have a fairly large Package.swift with 50 binary dependencies. In total the size of these 50 zip files is 400 MB. On a slower internet connection (16 MBit) the `swift package resolve` command errors out with some HTTP timeouts. It seems the main problem is that all 50 HTTP requests are executed at the same time.
Using some `DispatchSemaphore` to limit the concurrently downloaded binary dependencies to 8 concurrent requests. 
In our project with the 50 binary dependencies it successfully completes the `swift package resolve` command. It's still open for discussion if the `max 8 concurrent downloads` is the right number. Also not sure if we should introduce another queue for this, reusing …
> Limit concurrent HTTP requests when downloading binary dependencies

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: when binary artifact download fails it may leave behind a partial or otherwise corrupt file
changes:
* remove pre-existing archive file before attempting to download the same file again
* add test
> gracefully handle pre-existing binary artifact from failed downloads

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
5.6 cherry-pick of #4021
---
Explanation:
When binary artifact download fails it may leave behind a partial or otherwise corrupt file, which fail subsequent attempts to resolve the dependency graph unless manually cleaned up (remove .build)
Scope of Issue:
This impacts the reliability of SwiftPM when resolving graphs with binary dependencies.
Reason for Nominating to 5.6 :
Important reliability fix for real-world use case.
Risk:
Low risk; No functional changes, this removes a file if exists before attempting to write it.
Reviewed By: @abertelrud 
Automated Testing: Unit tests
Dependencies: None
Impact on CI: None
How to Verify: Resolve package dependencies on a binary dependency, cause it to fail mid way, try to resolve again.
> [5.6] gracefully handle pre-existing binary artifact from failed downloads (#4021)

- Sources/Basics/DispatchTimeInterval+Extensions.swift
- Sources/Commands/CMakeLists.txt
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/TestingSupport.swift
- Sources/Workspace/UserToolchain.swift
- Tests/CommandsTests/PackageToolTests.swift
This is a cherry-pick of https://github.com/apple/swift-package-manager/pull/4002.
**Explanation:**  This cherrypicks the change to allow package command plugins to run tests in SwiftPM and get the results back in structured form.  This change is on the main branch but should be included in the 5.6 release as command plugins are available in SwiftPM 5.6 for the first time.
**Scope of Issue:**  This applies to command plugins that want to use the `PackageManager.test(_:parameters:)` function.
**Reason for Nominating to 5.6:**  This allows command plugins to use the new `PackageManager.test(_:parameters:)` function in SE-0332.
**Risk:**  Low — the material changes affects only a new code path that was introduced for command plugins, so only plugins that use …
> [5.6] Allow running tests from a command plugin (#4002)

- Sources/Basics/Sandbox.swift
- Tests/BasicsTests/SandboxTests.swift
This is the 5.6 nomination of #4009.
**Explanation:**  The sandbox rules introduced in #3996 made the entire package directory read-only, but that isn't appropriate when `.build` is inside the package directory.  Swapping the order so that the sandbox applies the allow-write rules after the deny-write rules allows `.build` (or whatever the output directory is) to be written to while keeping the rest of the package directory readonly to the plugin.
**Scope of Issue:**  This affects SwiftPM users who run command plugins that write to the plugin working directory and who are not customizing the intermediate-files directory using the `--build-path` option.
**Reason for Nominating to 5.6:**  This is a common use case in new functionality (command plugins).
**Risk:**  Low — although the sandbox …
> [5.6] Sandbox blocks output to default plugin output directory when it's under `<pkgdir>/.build`

- Sources/Commands/SwiftPackageTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
5.6 nomination cherry-pick of https://github.com/apple/swift-package-manager/pull/4014
**Explanation:**  The initial working directory of invoked plugin processes isn't defined, but is currently set to the cache directory.  For command plugins this is not a particularly useful default, especially since any relative paths passed as command line arguments should be relative to whatever working directory the command is invoked from (which is not necessarily the package directory).  Before command plugins initially become in SwiftPM 5.6, we should fix this to use the original working directory of the `swift package <verb>` invocation, and as follow-up we should clarify this in SE-0332.
**Scope of Issue:**  This applies to command plugins that accept relative paths as arguments.  SE-0332 …
> [5.6] Package command plugins should have the same initial working directory as the invocation

- Sources/Basics/SwiftVersion.swift
Mark the SwiftPM 5.6 branch as a release branch.
As happens with every release, the development bit in SwiftPM needs to be turned off in the release branch so that it disallows use of 999.0 package manifest tools versions.  This also causes `swift package --version` to show the version without a `-dev` suffix.
- change `development` from `true` to `false` in SwiftVersion.swift
rdar://87535197
> [5.6] Mark the SwiftPM 5.6 branch as a release branch

- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/FunctionalTests/PluginTests.swift
An existing warning about dependencies on packages from which no products are used shouldn't apply if the package has any command plugin products.  The warning assumes that the only use of products is to link against them or use them as build tool plugins, but that's not correct for command plugins, where the dependency is only used to make the plugin available for the user to invoke.
With command plugins it's perfectly reasonable to depend on a package without explicitly having a reference to any of its products, so suppress the warning in that case.
- added a check to skip the warning if the depended-on-package vends at least one command plugin product
- add a unit test to check the absence of this diagnostic, and the continued presence of diagnostics about unused built tool plugins …
> Don't emit a "this package dependency is unused" warning for packages that vend command plugins

- Sources/SPMTestSupport/MockWorkspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: recent change to SwiftPM introduce a limit on # of concurrent binary artofacts downloads, but was missing a test
changes: add a test for the new functionality
> add a test for new binary artifact download concurrent download limit

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageGraphTests/PubgrubTests.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
motivation: nicer code, better performance
changes: audit use of `.map{ $0 }` which are redundant and remove such
> cleanup redundant maps

- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/FunctionalTests/PluginTests.swift
5.6 nomination cherry-picked from https://github.com/apple/swift-package-manager/pull/4028
**Explanation:**  If a package depends on another package that vends a command plugin, and if it does not use any other product from that package, then SwiftPM emits a warning saying that the dependency is unused.  This warning predates the introduction of command plugins, and is no longer correct when a package dependency vends command plugins, because the reason for the dependency might be to make those plugins available when using the package.  Since those command plugins could be invoked by the user at any time, this change elides the warning when the package dependency contains command plugin products (but not when it contains only unused build tool plugins, since the warning does apply in that …
> [5.6] Don't emit "package dependency is unused" warning for packages containing command plugin products

- Sources/Basics/Dictionary+Extensions.swift
- Sources/PackageGraph/DependencyResolutionNode.swift
- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Tests/PackageGraphTests/PubgrubTests.swift
motivation:  when resolving graphs with non-versioned depedendencies (such as branch dependencies), the dependencies get "flattened" onto the root node which looses the original association with the dependency's parent yielding incorrect diagnostics
changes:
* more accuretly track the underlying dependency when computing root dependencies from non-versioned depedendencie
* peek into the "real" cause when producing depedency based diagnostics for the root node
* TBD: use top level package as root instead of synthesized root when appropriate 
* add a bunch of tests
rdar://87486528
rdar://64226666
> improve dependency resolution diagnostics when resolving non-versioned dependencies

- Sources/SourceControl/GitRepository.swift
This disables the builtin FS monitor on the checkouts of the
dependencies.  This ensures that the global configuration of
the setting does not influence the repository local behavior
as that can cause problems on Windows. Due to the filesystem
behaviour on Windows, we cannot remove a directory with open
descriptors - which the monitor implies. This should resolve
the problem where a series of `swift package` commands would
result in failures.
> SourceControl: avoid the builtin FS monitor

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: it is common for archives to include top level directory, e.g. GitHub release archives
changes:
* when downloading binary artifacts archives, perform first level component stripping if deemed necessary
* add informational diagnostics to help debug binary artifacts downloads
* add tests
> support binary artifact archives that require first level component stripping

- Sources/SourceControl/GitRepository.swift
This disables the builtin FS monitor on the checkouts of the
dependencies.  This ensures that the global configuration of
the setting does not influence the repository local behavior
as that can cause problems on Windows. Due to the filesystem
behaviour on Windows, we cannot remove a directory with open
descriptors - which the monitor implies. This should resolve
the problem where a series of `swift package` commands would
result in failures.
> [5.6] SourceControl: avoid the builtin FS monitor (#4032)

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
> [5.6] support binary artifact archives that require first level component stripping (#4020)

- Sources/Commands/SwiftPackageCollectionsTool.swift
- Sources/PackageCollections/PackageCollections+Configuration.swift
- Sources/PackageCollections/PackageCollections.swift
Package collections configuration and storage paths should be customizable via `--config-path` and `--cache-path` options.
rdar://74887473
> [Collections] Honor --config-path and --cache-path options

- .gitignore
- CONTRIBUTING.md
- Sources/PackageDescription/BuildSettings.swift
- Sources/PackageDescription/PackageDescription.docc/Info.plist
- Sources/PackageDescription/PackageDescription.docc/PackageDescription.md
- Sources/PackageDescription/PackageDescription.swift
- Sources/PackageDescription/Resource.swift
- Sources/PackageDescription/Target.swift
Add rough initial cut of PackageDescription.docc and adopt DocC formatting in some of its constituent code.
We'd like to be able to generate documentation for certain parts of SwiftPM using Apple's [DocC](https://github.com/apple/swift-docc) tool, which should allow for easier maintenance and a much better end result.
- Add `Sources/PackageDescription/PackageDescription.docc`, which contains DocC configuration and some documentation meta-content.
- Adopt the DocC double-tick code voice style in some inline PackageDescription docs — this explicitly tells DocC to link that class/method/etc. name to its DocC page/anchor.
[Here's a downloadable `.doccarchive` bundle](https://github.com/apple/swift-package-manager/files/7892868/PackageDescription-89b7b32.doccarchive.zip) for easier review of …
> Add initial support for DocC in PackageDescription module

- Sources/Basics/Observability.swift
- Sources/PackageLoading/ManifestLoader.swift
- Tests/BasicsTests/ObservabilitySystemTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: clearer error descriptions to users
changes:
* add explicit handler for LocalizedError when extracintg its description  string into Diagnostics
* conform ManifestParseError to CustomStringConvertible
* add and adjust test
> improve observability error description interpolation, especially for manifest parsing error

- Sources/Basics/Dictionary+Extensions.swift
- Sources/Commands/TestingSupport.swift
- Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
- Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
- Sources/PackageGraph/PackageGraph.swift
- Sources/Workspace/Workspace.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/swiftpm-manifest-tool/main.swift
- Tests/BasicsTests/DictionaryTest.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: Dictionary::uniqueKeysWithValues is asserting and will crash the process on bad data. need a throwing variant
changes:
* create Dictionary::throwingUniqueKeysWithValues which is the same as uniqueKeysWithValues but throwing insteada of asserting on duplicate key
* update call sites that take user data (which is not sanitized) to use the throwing variant
* update relevant call sites to new throwing signatures
* add test
> do not use Dictionary::uniqueKeysWithValues when input is not sanitized

- Documentation/Usage.md
Fixes a broken link. 
The link got broken by https://github.com/apple/swift-package-manager/commit/4ee5feda08e7f9d760a4bc1397500fc23ec5bb29, and currently, the linked file no longer exists. Thus, I set to a suitable link.
> [Docs] Fix broken link in Usage.md

- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMTestSupport/Toolchain.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
Make the `@main` entry point for plugins be `async`.
This allows the `@main` entry point for plugins to call APIs marked `async`.
- mark the protocols in the plugin API as `async`
- use `await` when calling those APIs
- add a required `-rpath` when compiling plugins on macOS older than 12.0 (not needed on other platforms)
rdar://83206272
*Note:*  This builds on https://github.com/apple/swift-package-manager/pull/3898 and will be easier to review once that one is merged.
> Make the `@main` entry points for plugins be `async` so they can call other `async` APIs

- Package.swift
- Sources/PackagePlugin/ArgumentExtractor.swift
- Sources/PackagePlugin/CMakeLists.txt
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackagePluginAPITests/ArgumentExtractorTests.swift
This helps with simple cases until it is possible to use SwiftArgumentParser or other package dependencies from package plugins
The initial version of plugins can't yet link against other modules, which excludes use of SwiftArgumentParser and similar libraries.  Plugins with more advanced needs will probably include an implementation of one of the other, simpler argument parser libraries available, but after discussion we've agreed that something minimal that operates on just string lists may make sense.  The future is clearly to use the proper argument parser, but this is a useful helper until we have that.
- add an ArgumentExtractor type to the PackagePlugin module
- added a new dedicated unit test for this PackagePlugin API
- extended an end-to-end plugin unit test
Simple extraction of …
> Add a simple argument extractor to PackagePlugin

- Sources/Commands/SwiftPackageTool.swift
- Sources/PackagePlugin/Errors.swift
- Sources/PackagePlugin/PackageModel.swift
- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
As part of this we simplify the command plugin method to not have a `targets` parameter but to instead get all the inputs in `arguments`.
Any `--target` or `--product` flags from the `swift package` invocation are now prepended as `--target` and `--product` parameters in the plugin arguments, respectively, and the ArgumentExtractor helper type makes it easier to get at this information from the plugin.  Also add methods to make it easier to look up products and targets in the plugin context's package.
The `targets` parameter was fairly specific and didn't account for products and other entities that the plugin might instead operate on.  Providing API inside the plugin to help look this up based on arguments provides more flexibility for the plugin.
- pass on any `--target` and `--product` …
> Simplify the command plugin method to get all the inputs in `arguments` instead of a specific `targets` parameter

- Sources/Basics/SwiftVersion.swift
- Sources/PackageModel/ToolsVersion.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
- Tests/PackageLoadingTests/PD_Next_LoadingTests.swift
Also clean up what seems like a couple of mistakes from previous updates (detailed under _Modifications_, below).
This is necessary bookkeeping that is done whenever a new minor (or major) Swift version is announced.  In this case https://forums.swift.org/t/swift-5-7/54862.
- add a `v5_7` enum case to `SwiftVersion`
- mark the current version as 5.7.0
- create a new `PD_5_7_LoadingTests.swift` with no tests in it for now
- create a new `PD_Next_LoadingTests.swift`
- it still has `testRegistryDependencies` since this still needs the 999.0 (`vNext`) availability
- also clean up what seems like a couple of mistakes from previous updates:
- remove a defunct `PDNextVersionLoadingTests.swift` (the new name is `PD_Next_LoadingTests.swift`)
- move a the `testCommandPluginTarget` test to the 5.6 …
> Update the SwiftPM version to 5.7 on main

- Sources/PackagePlugin/Diagnostics.swift
- Sources/PackagePlugin/Path.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackagePluginAPITests/PathTests.swift
Remove ExpressibleByStringLiteral conformance but allow initializer to be invoked, reducing surprises.  Add Hashable conformance.  Adjust diagnostics, and add unit test.
These are further ergonomic changes for plugins based on usage experience.
- mark `PackagePlugin.Path.init()` public
- remove ExpressibleByStringLiteral conformance
- add Hashable conformance
> Make PackagePlugin `Path.init()` public, clean up conformances

- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageRegistry/CMakeLists.txt
- Sources/PackageRegistry/RegistryClient.swift
- Sources/PackageRegistry/RegistryDownloadsManager.swift
- Sources/SPMTestSupport/MockRegistry.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/ToolsVersionSpecificationRewriter.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
- Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: better performance when using registry
cached:
* introduce RegistryDownloadsManager which manages the downloads across the local and cache
* integrate RegistryDownloadsManager into Workspace, which now uses it to download from registry instead of the registry client directly
* update workspace delegate to handle callback from registry downloads, and propogate them to workspace delegates
* improve / generalize the workspace fetching delegate methods such that they are appropriate to both repositories and registry downloads
* deprecate --enable-repository-cache/--disable-repository-cache in favor of --enable-dependency-cache/--disable-dependency-cache
* fix several download and unzip edge cases which came to bear now that a cache is in place
> cache registry downloads

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
There were a few undesirable issues caused by a combination of a `swift-argument-parser` issue and making the `plugin` subcommand be the default subcommand so that the `plugin` subcommand could be omitted:
- when you invoke `swift package` without any arguments it starts resolving the package graph
- when you make a typo like `swift package resove` it emits an error that it did not find any plugin (`error: No command plugins found for ‘resove’`)
- the `--list` option of the `plugin` subcommand incorrectly applied even when `plugin` was omitted
- `swift package plugin --help` yields no help
- `swift package plugin` yields `error: No plugin command name specified`
This change introduces a new separate default subcommand that has behavior suitable for omitting the `plugin` subcommand:
- if …
> Fix issues caused by having the `plugin` subcommand be the default subcommand

- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMTestSupport/Toolchain.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
This also adds a `-rpath` flag when compiling the plugin to run on macOS earlier than 12.0, so that the back deployment libraries in the compiler's toolchain can be found.
Cherry-pick of #3842 to 5.6.
rdar://83206272
> [5.6] Make the `@main` entry points for plugins be `async` so it can call other `async` APIs

- Sources/Commands/SwiftPackageTool.swift
- Sources/PackagePlugin/Errors.swift
- Sources/PackagePlugin/PackageModel.swift
- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/PackagePlugin/Protocols.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
This is a 5.6 cherry-pick of #4055. Details in that PR. Motivation: This improves package plugins, a new feature in SwiftPM 5.6
This PR builds on #4064 because waiting for each full build before opening the next PR would take a long time. All the diffs have already been reviewed in the original PR on main.
> [5.6] Simplify the command plugin method to get all the inputs in `arguments` instead of a specific targets parameter  (#4055)

- Sources/PackagePlugin/Diagnostics.swift
- Sources/PackagePlugin/Path.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackagePluginAPITests/PathTests.swift
This is a 5.6 cherry-pick of #4058. Details in that PR. Motivation: This improves package plugins, a new feature in SwiftPM 5.6
> [5.6] Make PackagePlugin Path.init() public, clean up conformances (#4058)

- Sources/Build/BuildPlan.swift
The swift-driver works on Windows is in the process of becoming the
default driver on Windows.  This enable the last piece of the
swift-driver support in SPM.
> Build: enable the swift-driver on Windows

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
This is a 5.6 cherry-pick of #4060. Details in that PR. Motivation: This improves package plugins, a new feature in SwiftPM 5.6.
> [5.6] Fix issues caused by having the plugin subcommand be the default subcommand (#4060)

- Sources/Basics/CMakeLists.txt
- Sources/Basics/String+Extensions.swift
- Sources/PackageRegistry/RegistryDownloadsManager.swift
- Sources/SPMTestSupport/InMemoryGitRepository.swift
- Sources/SourceControl/GitRepository.swift
- Sources/SourceControl/Repository.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
- Tests/SourceControlTests/GitRepositoryProviderTests.swift
- Tests/SourceControlTests/GitRepositoryTests.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
motivation: apply learning from implementing registry downloads maanger to repository manager
changes:
* remove the use of state file, rely on well-known storage path instead
* add method to RepositoryProvider to check if a path contains a valid repository
* replace use of RepositorySpecifier::fileSystemIdentifier (String)  with RepositorySpecifier::storagePath() -> RelativePath
* refactor repository manger delegate to use clearer terminology, and align it with registry downloads manager delegate
* update repository manager tests to use more modern testing techniques and improve its concurrency handling
* adjust mocking facilities and tests
> refactor repository manager

- Package.swift
- Sources/Commands/SwiftTool.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SourceControl/CMakeLists.txt
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
motivaton: SwiftPM clients now need to reverse engineer the package identity from the url
changes:
* add PackageIdentity to WorkspaceDelegate::willFetchPackage
* add PackageIdentity to WorkspaceDelegate::fetchingPackage
* add PackageIdentity to WorkspaceDelegate::didFetchPackage
* rename WorkspaceDelegate::repositoryWillUpdate to WorkspaceDelegate::willUpdateRepository and add PackageIdentity
* rename WorkspaceDelegate::repositoryDidUpdate to WorkspaceDelegate::didUpdateRepository and add PackageIdentity
* add PackageIdentity to WorkspaceDelegate::willCreateWorkingCopy
* add PackageIdentity to WorkspaceDelegate::didCreateWorkingCopy
* add PackageIdentity to WorkspaceDelegate::willCheckOut
* add PackageIdentity to WorkspaceDelegate::didCheckOut
* add PackageIdentity to …
> refactor workspace delegates

- Sources/Commands/SwiftTool.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
Remove the `TSCLibc` dependency as we do not depend on any of the
interfaces from the module.  This matters particularly on Windows
where static linking Swift content is not available, so this will
reduce the amount of dirty memory due to the dynamic library link
that cannot be removed.
> Remove unnecessary `TSCLibc` dependency

- Sources/Commands/SwiftTool.swift
- Sources/Workspace/Workspace.swift
https://ci.swift.org/job/swift-PR-source-compat-suite-debug/4058/
```
$ sandbox-exec -f /Users/buildnode/jenkins/workspace-private/swift-source-compat-suite-sandbox/sandbox_package.sb /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-debug/build/compat_macos/install/toolchain/usr/bin/swift package --disable-sandbox -C /Users/buildnode/jenkins/workspace/swift-PR-source-compat-suite-debug/swift-source-compat-suite/project_cache/GRDB.swift clean
warning: '--chdir/-C' option is deprecated; use '--package-path' instead
warning: Failed to load .netrc file at /Users/buildnode/.netrc. Error: unreadableFile(<AbsolutePath:"/Users/buildnode/.netrc">)
error: other(1)
```
Not sure if the `other(1)` error is `.netrc` related. Trying to see if
this code change will fix it.
> Test parent directory of .netrc file is writable before using it

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
~Implements https://bugs.swift.org/browse/SR-9402, which calls for SwiftPM to emit a warning when a target has duplicate dependencies.~
SPM was already partially checking for this, so this updates/expands that check. I'm not in love with `duplicateDetectionHash`, but it does what it needs to.
> [SR-9402] Emit a warning on duplicate target dependencies

- Sources/SourceControl/RepositoryManager.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: more reliable and performant lookup
changes:
* replace operation queue with a semaphore
* reorganize code so that pending lookups are always tested for
> improve concurrency handling in RepositoryManager

- Sources/Commands/SwiftTool.swift
- Sources/Workspace/Workspace.swift
motivaiton: cleaner code
changes: user new FS APIs to test for readability/writability instead of attempting to create a temp file
> improve testing for readability/writability of shared directories

- Sources/Basics/AuthorizationProvider.swift
- Sources/Basics/CMakeLists.txt
- Sources/Basics/Netrc.swift
- Tests/BasicsTests/NetrcTests.swift
motivation: the Netrc parser is only used by SwiftPM and can be moved into, which brings us closer to reducing TSC codebase
changes:
* migrate netrc parser from TSC into SwiftPM
* clean up the API a bit, e.g. use throwing instead of returning Result in non-async methods
* spelit netrc utility to parser and model vs. one monolithic utility
* migrate and clean up the tests
* update call sites
> move netrc parser into SwiftPM (from TSC)

- Tests/CommandsTests/PackageToolTests.swift
Temporarily skipping PackageToolTests.testPluginCompilationBeforeBuilding while fixing rdar://88453397.  Proper fix expected later today.
> Temporarily skip `PackageToolTests.testPluginCompilationBeforeBuilding` while fixing flaky test

- Sources/Basics/AuthorizationProvider.swift
motivation: providers may live for a long time (together with workspace) so cannot cache the content of the file
changes:
* read the netrc file content every time data is requested
> update netrc auth provider to read file "live"

- Sources/Build/BuildPlan.swift
- Tests/CommandsTests/PackageToolTests.swift
The code that processes targets in a BuildPlan was traversing a Set without any particular order, result in different order of processing each time (due to collection enumeration randomization).
The new code that collects lists of plugin descriptions became dependent on this order, causing plugins to be compiled in different order, which would sometimes cause a unit test to fail.
Rather than just imposing the order later, it seems prudent to make sure that the initial code that traverses the targets in the graph runs in a well-defined order, if nothing else to make debuggability easier.  There is no advantage to randomizing this order, and so this PR sorts them by name.  Ideally SwiftPM would preserve the order in which targets were declared, on the theory that the user had some purpose …
> Make the order in which targets (including plugin targets) are processed consistent

- Sources/PackagePlugin/Utilities.swift
- Tests/CommandsTests/PackageToolTests.swift
This continues expanding the set of utility methods based on feedback from early use of plugins.  This makes it easier to write simpler and briefer plugin code.
The extensions are:
```
extension Package {
/// The products in this package that conform to a specific type.
public func products<T: Product>(ofType: T.Type) -> [T]
/// The targets in this package that conform to a specific type.
public func targets<T: Target>(ofType: T.Type) -> [T]
}
extension SourceModuleTarget {
/// A possibly empty list of source files in the target that have the given
/// filename suffix.
public func sourceFiles(withSuffix suffix: String) -> FileList
}
```
The last of these was documented in SE-0325, and the other two added based on feedback.
> Add `products(ofType:)`, `targets(ofType:)`, and `sourceFiles(withSuffix:)` utilities to PackagePlugin API

- Tests/SourceControlTests/RepositoryManagerTests.swift
changes: leave sync group only after recording results
rdar://88453312
> fix flaky test

- Sources/PackagePlugin/Utilities.swift
- Tests/CommandsTests/PackageToolTests.swift
SwiftPM 5.6 nomination of https://github.com/apple/swift-package-manager/pull/4094
> [5.6] Add `products(ofType:)`, `targets(ofType:)`, and `sourceFiles(withSuffix:)` utilities to PackagePlugin API

- Tests/CommandsTests/PackageToolTests.swift
This reverts commit eb198dd878ae0c29b62ce34bf48a121b3853891c now that the underlying issue has been fixed in ffd0759fffdbff6ad95dd7dbde039a33fd37b612.
> Reenable the `PackageToolTests.testPluginCompilationBeforeBuilding`

- Package.swift
```
'SwiftPM' /Users/ylee/apple/swift-package-manager: warning: found 2 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/ylee/apple/swift-package-manager/Tests/BasicsTests/Inputs/archive.zip
/Users/ylee/apple/swift-package-manager/Tests/BasicsTests/Inputs/invalid_archive.zip
```
> Fix warning about unhandled files

- Sources/Basics/AuthorizationProvider.swift
- Sources/Commands/SwiftTool.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/CommandsTests/SwiftToolTests.swift
- Tests/WorkspaceTests/AuthorizationProviderTests.swift
motivation: more easily share authorization provider setup with libSwiftPM users
changes:
* move authorization providers setup from SwiftTool to a Worksapce configuraiton utility
> refactor authorization provider setup

- Sources/Commands/SwiftTool.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
*Motivation:*
Cancelling the plugin host (such as `swift package`) should also cancel any running plugins.
*Changes:*
Add a registry that keeps track of running plugin processes, and an API to cancel them.  We can't use `ProcessSet()` since it's tied to ToolsSupportCore's implementation of a subprocess and doesn't use Foundation.  In this case we don't need such a general solution in any case.
Added a unit test that goes to some length to try to determine that process is really gone after cancelling.
rdar://87280309
> Cancelling `swift package` with Control-C doesn't stop any running plugins

- Sources/PackagePlugin/PackageModel.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
Although the different basic kinds of targets were expressed through types, the module kind (executable, test, or regular) for a source module target was not expressed in the API.  This adds that property, letting plugins filter in or out, for example, test modules.
rdar://86786080
> Add module kind enum to the package plugin API

- Fixtures/ValidLayouts/SingleModule/ExecutableMixed/.gitignore
- Fixtures/ValidLayouts/SingleModule/ExecutableMixed/Package.swift
- Fixtures/ValidLayouts/SingleModule/ExecutableMixed/README.md
- Fixtures/ValidLayouts/SingleModule/ExecutableMixed/Sources/ExecutableC/c.c
- Fixtures/ValidLayouts/SingleModule/ExecutableMixed/Sources/ExecutableCxx/cxx.cpp
- Fixtures/ValidLayouts/SingleModule/ExecutableMixed/Sources/ExecutableSwift/main.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Tests/CommandsTests/BuildToolTests.swift
This forwards the -Xlinker, -Xcc, -Xcxx and -Xswiftc flags to the
xcbuild invocation.
This use case appeared when creating universal binaries by specifying
the arm64 and x86_64 and needing to specify the rpath flag. Since the
change is small, decided to add all of the BuildFlags as well.
Changes in how the XcodeBuildSystem is configured using the BuildFlags already available in `buildParameters`.
This command will work as expected when building universal binaries:
```swift
swift build --arch arm64 --arch x86_64 -Xlinker -rpath -Xlinker -/some/rpath
```
> Add support for -X* flags when building with Xcode

- Package.swift
Increment SwiftArgumentParser dependency to 1.0.3 to pull in a bug fix that would cause subcommand arguments to be folded into the parent command
We'd like to get the fix in https://github.com/apple/swift-argument-parser/pull/397 in order to fix issues with `swift` `run` and `swift` `plugin` arguments.  For example, `swift package plugin foo --verbose` would cause the `--verbose` to be applied to the parent command and not the plugin.
rdar://88097258
> Increment SwiftArgumentParser dependency to 1.0.3

- Package.swift
Increment SwiftArgumentParser dependency to 1.0.3 to pull in a bug fix that would cause subcommand arguments to be folded into the parent command
Motivation:
We'd like to get the fix in apple/swift-argument-parser#397 in order to fix issues with swift run and swift plugin arguments. For example, swift package plugin foo --verbose would cause the --verbose to be applied to the parent command and not the plugin.
rdar://88097258
> [5.6] Increment SwiftArgumentParser dependency to 1.0.3

- Tests/CommandsTests/PackageToolTests.swift
This is a 5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/4103 after being asked to cherry-pick this change since it's also affecting 5.6 CI.  It was already merged in main.
As in main, we don't want to skip the entire test since there are other good things being tested here that are not flaky, such as some of the other output as well as the exit code of the subprocess.
**Explanation:**  Temporarily disable a what is reported to be a flaky condition in a unit test that is causing occasional CI failures.  This is test-only change.  Investigation of the underlying cause is tracked by https://bugs.swift.org/browse/SR-15831.
**Scope of Issue:**  This is limited to one condition in a unit test, which checks the compiler output being printed by SwiftPM.  This hasn't been …
> [5.6] Disable a flaky part of the unit test `PackageToolTests.testPluginCompilationBeforeBuilding`

- Sources/PackagePlugin/PackageModel.swift
- Sources/PackagePlugin/PluginInput.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/CommandsTests/PackageToolTests.swift
SwfitPM 5.6 nomination of #4098.
Although the different basic kinds of targets were expressed through types, the module kind (executable, test, or regular) for a source module target was not expressed in the API.  This adds that property.
**Explanation:**  This adds a property to the `SourceModuleTarget` type in `PackagePlugin` to let plugins identify the kind of target:  executable, test, or generic.  This is useful for some plugins such as docc, which may want to skip test targets when generating documentation.
**Scope of Issue:**  This affects some package plugins that need a way to filter out different purposes of targets.
**Reason for Nominating to 5.6:**  This is a refinement requested by the .docc plugin (and useful to other plugins) in new functionality in 5.6 (command plugins). …
> [5.6] Add module kind enum to the package plugin API

- Sources/Commands/SwiftTool.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
This is a SwiftPM 5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/4104.
**Explanation:**  This makes sure that any running package plugins are killed as part of the shutdown procedure that runs when `swift` `package` receives a Control-C.
**Scope of Issue:**  This affects long-running package command plugins which a user may want to cancel by using Control-C on `swift` `package`.  Using Control-C causes SwiftPM to do some cleanup and exit, and does not reliably cause the subprocess to exit (killing `swift` `package` directly, outside of Control-C, does seem to always cause the subprocess to exit).
**Reason for Nominating to 5.6:**  This is an issue in new functionality (command plugins) that affects the user experience with long-running plugin processes. In …
> [5.6] Cancelling `swift package` with Control-C doesn't stop any running plugins

- Sources/PackageCollections/Model/Search.swift
- Sources/PackageCollections/PackageIndexAndCollections.swift
- Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
Modify `findPackages` logic to allow search in:
- package index only
- package collections only
- both index and collections
> [Collections] Add search options

- Sources/SPMTestSupport/GitRepositoryExtensions.swift
- Sources/Workspace/Workspace.swift
- Tests/CommandsTests/PackageToolTests.swift
Honor `skipDependenciesUpdates` when enforcing resolved versions.
Previously there could be cases where an existing checkout won't be updated from the remote even if `--skip-update` hasn't been passed.
Pass in the correct value from `WorkspaceConfiguration` when calling `getContainer` and ensure we wait for all `getContainer` calls to complete before proceeding.
We won't update with stale checkouts that could break builds because the resolved file is requiring newer revisions than what we have in the existing local checkouts.
> Ensure checkouts get updated when enforcing resolved versions

- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTestTool.swift
- Tests/FunctionalTests/DependencyResolutionTests.swift
motvation: some CLI command emit consumable informaiton such as json. in those case we dont want to include any other information on stdout, so that it can be consumed by pipes
changes:
* for the following commands:
* swift package dump-package
* swift package dump-pif
* swift package describe
* swift package experimental-api-diff
* swift package show-dependencies
* swift test --list
* redirect stdout to stderr prior to calling other actions
* adjust result printing to always use stdout
rdar://78612028
> improve handling of redundant output on stdout for commands that emit consumable information

- Fixtures/Miscellaneous/TestableExe/Tests/TestableExeTests/TestableExeTests.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/TestingSupport.swift
- Sources/LLBuildManifest/BuildManifest.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Tests/CommandsTests/TestToolTests.swift
motivation: give users an option to build the tests without testability (testable imports). this can increase build / test cycles when tests do not require the testable imports feature, so build artifacts are more is cachable
changes:
* add a `--disable-testable-imports` flag to `swift test` with which tests are build without the testability feature
* always use `-enable-testing` when building test modules as it is required for test discovery 
* add tests
rdar://82448144
> add flag to disable building with testablity when running tests

- Tests/FunctionalTests/ModuleAliasingTests.swift
changes: disable new module aliasing tests
> disable module aliasing test while investigating

- Tests/CommandsTests/BuildToolTests.swift
This seems to be failing in CI on Apple Silicon because we can't build universal with the inferior toolchain there. On the one hand, that seems fair enough and most of our XCBuild tests are not part of the main test suite but they are in integration tests. On the other hand, there's `testXcodeBuildSystemOverrides` which should be hitting the same issue and it is present since last year. So I am disabling the test here to get more signal on whether this is a problem with the new test somehow or a new issue outside of SwiftPM / this particular test.
> Temporary disable `testXcodeBuildSystemWithAdditionalBuildFlags`

- IntegrationTests/Package.swift
- IntegrationTests/Tests/IntegrationTests/BasicTests.swift
- IntegrationTests/Tests/IntegrationTests/Helpers.swift
- IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
- IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
- Sources/Workspace/InitPackage.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/WorkspaceTests/InitTests.swift
motivation: example is out of date with best practices
changes:
* use @main istead of main.swift
* test executable directly instead of shelling out to a process
rdar://82119401
> improve example created by package init --type executable

- IntegrationTests/Package.swift
- IntegrationTests/Tests/IntegrationTests/BasicTests.swift
- IntegrationTests/Tests/IntegrationTests/Helpers.swift
- IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
- IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
- Sources/Workspace/InitPackage.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/WorkspaceTests/InitTests.swift
Reverts apple/swift-package-manager#4122
```
********************
Failed Tests (2):
swift-package-tests :: swift-package-init-exec.md
swift-package-tests :: swift-run.md
```
> Revert "improve example created by package init --type executable"

- Tests/FunctionalTests/MiscellaneousTests.swift
```
[80/83] Compiling FunctionalTests CFamilyTargetTests.swift
/Users/ec2-user/jenkins/workspace/oss-swift-incremental-RA-macos-apple-silicon/swiftpm/Tests/FunctionalTests/MiscellaneousTests.swift:584:61: error: cannot find 'prefix' in scope
let (stdout, stderr) = try executeSwiftTest(prefix, extraArgs: ["-v"])
^~~~~~
error: fatalError
```
> Fix missing prefix rename to fixturePath in MiscellaneousTests.swift

- Sources/Workspace/Workspace.swift
Also reduces some of the assignment repetitions, which makes the code even clearer (IMO).
> Refactor nested `if`s into a switch statement

- Sources/Commands/SwiftTool.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: some complext integrations may require customization of the host toolchain
changes:
* add customization point at workspace initializer to pass in a custom host toolchain
rdar://74700642
> add customization point for host toolchain

- Sources/PackageDescription/BuildSettings.swift
Instead of a single `when` method that takes two optional values, use multiple methods so that it is impossible for both to be `nil`.
> Make it impossible to create an invalid `BuildSettingCondition`

- Sources/PackageLoading/ManifestLoader.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: clearer, more actionable error message
changes:
* catch invalid relative path for binary artifacts and emit a clear diagnostics
* overall improve validation of binary targets path and urls
* add tests
rdar://84365161
> improve error message when using invalid path for local binary artifacts

- Sources/Basics/HTPClient+URLSession.swift
- Sources/Basics/HTTPClient.swift
- Sources/Basics/String+Extensions.swift
- Sources/PackageRegistry/RegistryClient.swift
- Sources/Workspace/RegistryPackageContainer.swift
- Tests/BasicsTests/StringExtensionsTests.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
motication: preparation work for mixed graphs
changes:
* rename RegistryClient::listVersions API to getPackageMetadata and revise it to parse the link header that contains the alternative URLs for the package
* enhance RegistryClient::getIdentifers API to use codable for parsing the server result
* add small utility to drop prefx from string to Basics
* cleanup redundant HTTPClientProtocol which was used for RegistryClient testing but since deprecated
> improve registry client handling of alternative locations

- CHANGELOG.md
- Sources/Build/BuildPlan.swift
- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Tests/BuildTests/BuildPlanTests.swift
In the past it was unsafe to pass -dead_strip because there was some
required swift metadata that was stripped. It seems that at this point all
of those cases are either fixed or marked as @llvm.used, so passing
these flags should safely reduce binary size in some cases. If there are
other cases where this isn't safe we should likely annotate them as
@llvm.used.
Related: https://bugs.swift.org/browse/SR-521 https://github.com/apple/swift-package-manager/pull/215
> Add -dead_strip / --gc-sections for release builds

- Sources/SPMTestSupport/MockWorkspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: binary artifacts tests had redundant complexity that made them difficult to maintain
changes: remove extra layer of indirection when not required to the test by making the binary targets on the root package instead of on dependencies
> cleanup workspace binary artifacts tests

- Sources/Commands/SwiftTestTool.swift
- Sources/PackageModel/ToolchainConfiguration.swift
- Sources/Workspace/UserToolchain.swift
motivation: users should be able to use SwiftPM on macOS without Xcode installed (with the exception of testing for now)
changes:
* in UserToolchain make xctest lookup optional on macOS and only validate its exists when trying to perform tests
* consolidate two different representations of xctest path (one was for Windows and the other for macOS)
rdar://88651484
> make XCTest optional on macOS for operations that do not require testing

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/PackageGraph.swift
- Tests/BuildTests/BuildPlanTests.swift
When multiple module aliases are specified upstream, an override should be allowed downstream to resolve conflicts. 
Resolves rdar://88295338.
> Allow an override when multiple module aliases are specified

- Utilities/bootstrap
swift-package-manager does not use Yams, remove the unnecessary flag
being passed to the build.
> build: remove `-DYams_DIR=` from s-p-m build

- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageGraph/PackageModel+Extensions.swift
- Sources/PackageModel/Manifest.swift
- Sources/PackageModel/Manifest/PackageDependencyDescription.swift
- Sources/PackageRegistry/RegistryClient.swift
- Sources/SPMTestSupport/MockPackage.swift
- Sources/SPMTestSupport/MockRegistry.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/FileSystemPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Sources/Workspace/WorkspaceConfiguration.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: support mixed dependencies graphs where some dependencies come from source control while other from registry, and encourage the transition to the registry
changes:
* introduce new CLI flag to determine the source control to registry transformation mode (disabled, identity only, swizzle)
* wrap manifest loading with a transformer that translates source control dependencies to registry ones when the dependency is found in the registry, based on the mode
* add a bunch of tests
> resolve source control dependencies via the registry when available

- Sources/Build/BuildPlan.swift
- Sources/Commands/APIDigester.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/Commands/SymbolGraphExtract.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Tests/CommandsTests/BuildToolTests.swift
motivation: deprecate global and process verbosity
changes:
* stop using TSC global verbosity flags
* set a logging handler on Process to funnel debug information to observability handler
> adjust to TSC verbosity API changes

- Sources/Build/BuildOperation.swift
- Sources/Commands/APIDigester.swift
- Sources/Commands/Snippets/CardStack.swift
- Sources/Commands/SwiftBuildTool.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftRunTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/SwiftTool.swift
- Tests/CommandsTests/SwiftToolTests.swift
- Tests/CommandsTests/TestToolTests.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
motivation: better handling of what neds to go to stdout vs stderr
changes:
* update all CLI commands to use stdout for the final result. this means "swift build" and "swift test" output goes to stdout
* update all other background activities to output to stderr, this includes output from build operations and pacakge resolution that take place as part of another action
* set SwiftTool default output stream to sdterr instead of stdout
* update "swift test" to emit its output to stdout
* refactor all instance creation sites of BuildOperation to use a standard factory method which uses the appropriate output stream (normally stderr), whith a customization point for "swift build" to direct the output to stdout
> improve output stream handling in CLI

- Tests/FunctionalTests/PluginTests.swift
This fixes a reported thread sanitizer issue in the `PluginTests.testCommandPluginCancellation()` test.
**Description:** The delegate is called in sequence because the caller passes in a serial queue, but there is a race condition between the timeout of waiting for the subprocess to finish and accessing the delegate’s parsed-out process identifier.  Accessing it on the delegate queue will preserve the thread access integrity.
This is an alternate (and in my view better) fix of https://github.com/apple/swift-package-manager/pull/4159 because making the data structures thread-safe would mask further tsan issues.
**Motivation:** Fixes a reported tsan violation in unit tests.
**Changes:**
- access the parsed process identifier from the serial delegate callback queue
> Fix a tsan issue in `PluginTests.testCommandPluginCancellation()`

- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Sources/MyLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Tests/MyLibraryTests/test.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Libraries/LocalToolHelperLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Plugins/MyPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Tools/ImpliedLocalTool/main.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Tools/LocalTool/main.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Libraries/RemoteToolHelperLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Tools/RemoteTool/main.swift
- Sources/Commands/SwiftPackageTool.swift
- Tests/FunctionalTests/PluginTests.swift
This is a SwiftPM 5.6 cherry-pick of https://github.com/apple/swift-package-manager/pull/4160.
**Explanation:** When a package command plugin has a dependency on an executable built from source (as opposed to a binary target) and that executable is in the same package as the plugin, the dependency ends up being on the executable target and not the product. This means that the module gets built but the final link step is never performed, so trying to use the executable from within the plugin fails.
**Scope of Issue:** This affects helper tools that are built from source and defined in the same package as the plugin that uses them.
**Reason for Nominating to 5.6:** This is a serious bug in new functionality (command plugins) that affects the user experience. It is also very safe, since the …
> [5.6] Fix a bug that caused a plugin dependency on a local executable to not work properly

- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Sources/MyLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Tests/MyLibraryTests/test.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Libraries/LocalToolHelperLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Plugins/MyPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Tools/ImpliedLocalTool/main.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Tools/LocalTool/main.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Libraries/RemoteToolHelperLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Tools/RemoteTool/main.swift
- Sources/Commands/SwiftPackageTool.swift
- Tests/FunctionalTests/PluginTests.swift
Motivation:  This bug affects how packages that vend plugins that rely on built tools can be structured (remote tool dependencies work but local dependencies do not, without this fix).
Changes:
- pass `.product` instead of `.target` to make sure that the executable is linked and not just compiled
- add a unit test that checks remote and local tools, with both implicitly and explicitly defined products for the local case
rdar://89267060
> Fix a bug that caused a plugin dependency on a local executable to not work properly

- Sources/SPMTestSupport/XCTAssertHelpers.swift
- Tests/CommandsTests/APIDiffTests.swift
- Tests/CommandsTests/BuildToolTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/CommandsTests/RunToolTests.swift
- Tests/CommandsTests/TestToolTests.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/FunctionalTests/ToolsVersionTests.swift
motivation: easier to maintain tests
changes:
* define new XCTAssertThrowsCommandExecutionError testing helper for test that invoke SwiftPM commands and check the output
* use the new helper in all potential call sites to reduce call site complexity and chance of missing errors
> tests cleanup

- Sources/SPMTestSupport/InMemoryGitRepository.swift
- Tests/SourceControlTests/InMemoryGitRepositoryTests.swift
motivation: easier to debug test failures
changes: replace force unwraps in InMemoryGitRepository with explcity exception that provide more detailed error message
> cleanup force unwraps in a test utillity

- Tests/BasicsTests/URLSessionHTTPClientTests.swift
motivation: address warnings
changes: update URLSessionHTTPClientTest to use the new netrc utility instead of the deprecated ones from TSC
> address warning from TSC netrc deprecaton

- Sources/Commands/SwiftPackageTool.swift
- Sources/PackagePlugin/CMakeLists.txt
- Sources/PackagePlugin/PackageManagerProxy.swift
- Sources/PackagePlugin/Plugin.swift
- Sources/PackagePlugin/PluginContextDeserializer.swift
- Sources/PackagePlugin/PluginMessages.swift
- Sources/SPMBuildCore/CMakeLists.txt
- Sources/SPMBuildCore/PluginContextSerializer.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/SPMBuildCore/PluginMessages.swift
- Sources/SPMBuildCore/PluginScriptRunner.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Motivation:
Refactor the plugin machinery for better maintainability, consolidation of wire protocol struct definitions, and groundwork for extending the plugin functionality (such as adding new capabilities or new plugin messages such as dynamic querying of capabilities).
Changes:
- factor out the Codable declarations of enums and struct for the plugin wire protocol into a PluginMessage file that can be shared between the plugin and plugin host; this gets us compile-time checking so that the host and plugin are always in sync
- separate out the functionality of DefaultPluginScriptRunner to only handle the mechanics to talking to the plugin and not be concerned with what the messages are (this is factored back down into PluginInvocation)
- hoist the different kinds of plugin action …
> Refactor and clean up plugin communication and wire messages

- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/PackageGraph/Pubgrub/Incompatibility.swift
- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/PackageGraph/ResolvedProduct.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/PkgConfig.swift
- Sources/PackageModel/Manifest/ProductDescription.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/Target.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
- Tests/PackageModelTests/ManifestTests.swift
- Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
motivation: better robustness
changes:replace use of preconditions and asserts with throwing guards
> reduce use of preconditions and asserts

- CHANGELOG.md
- Sources/PackageDescription/BuildSettings.swift
- Sources/PackageDescription/PackageDescriptionSerialization.swift
- Sources/PackageDescription/Target.swift
- Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
motivation: reduce use of preconditions, make editing manifest safer
changes:
* deprecate TargetDependencyCondition "when" initializor that uses a precondition
* move TargetDependencyCondition code to a more appropriate place
* add tests
* update change log
> Update to manifest API to make it impossible to create an invalid target dependency condition.

- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/BuildSettings.swift
- Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/Xcodeproj/pbxproj.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
- Tests/XcodeprojTests/PackageGraphTests.swift
motivation: as part of auditing the code for preconditions and assets it came to light that the target build setting model can be improved to handle preconditions via the type system
changes:
* move the build settings values into the build setting kind enum as associated values (istead of floating attribute)
* adjust call sites and test
> refactor target build settings model

- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageModel/Manifest/TargetDescription.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Sources/PackageModel/Resource.swift
- Tests/BasicsTests/URLSessionHTTPClientTests.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
- Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
motivation: while looking to eliminate preconditions from the code, noticed the resource localization model could be improved to better use the type system
changes:
* move localization from a floating optional attribute to the process rule enum case
> refactor resource localization model

- Sources/PackageCollections/PackageCollections+Validation.swift
- Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
> Improve package collection validation error message

- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
motivation: improved concurrency control and cleaner code
changes:
* use a separate queue to schedule the lookup tasks to ensure concurrency control is done correctly
* create a sync version of lookup to help make maintaining the code easier, at least while the git client is sync
* reduce double queue overhead when Workspace::geContainer calls into RepositoryManager::lookup
> improve repository manager lookup concurrency control

- Sources/PackageLoading/ManifestLoader.swift
- Sources/SPMTestSupport/MockManifestLoader.swift
- Sources/Workspace/FileSystemPackageContainer.swift
- Sources/Workspace/RegistryPackageContainer.swift
- Sources/Workspace/SourceControlPackageContainer.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
- Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: more correct and robust concurrency control for manifest loading
changes:
* use a seperate queue to schedule the evaluation tasks to ensure concurrency control is done correctly
* move concurrency control to the methods that forks the child processes so that its more targeted
* clarify what is the delegate queue and what is the callback queue
* move a handful of data structure defintions around to make code easier to read
* make concurrency tests more challanging
> improve manfiest loader concurrency control

- Sources/Basics/ConcurrencyHelpers.swift
- Sources/Basics/Errors.swift
- Sources/Basics/HTPClient+URLSession.swift
- Sources/Basics/HTTPClient.swift
- Sources/Workspace/Workspace.swift
- Tests/BasicsTests/HTTPClientTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: controlling how many concurrent requests are taking place is important for controlling bandwidth requirements, especially as we are transitioning to registry based dependencies
changes:
* add max concurrency controls to http client using a dedicated queue
* remove workspace binary dependencies concurrency control since its not longer necessary (applied at http client level)
* fix a bug in URLSeesion based HTTP client where download can be removed between delegate calls
> http client to support configurable max concurrent requests

- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
motivation: the warning is redundant
changes:
* remove the validation when english is the default langauge
* adjust test
* refactor TargetSourcesBuilderTests so we can test for no diagnostics
rdar://86297221
> deprecate validation that a resource localization exists when English is the default language

- Sources/Commands/CMakeLists.txt
- Sources/PackageDescription/CMakeLists.txt
- Sources/PackageLoading/CMakeLists.txt
- Sources/PackagePlugin/CMakeLists.txt
- Sources/Workspace/CMakeLists.txt
The dependencies on Foundation are effectively required on all
non-Darwin platforms.  Unconditionalize them and force the link against
the libraries irrespective of whether they are wired up to the build or
rely on the default linker search path.
> build: clean up some unnecessary conditions

- Sources/Workspace/Workspace.swift
In case of using a custom package container provider, a custom file-system object can be provided for package dependencies. Providing one for local, file-system based dependencies doesn't make sense and should be skipped.
> Fix handling of file-system based dependencies

- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTool.swift
motivation: consolidate use of build operation construction which is important for cancellation support
changes:
* use the general purpose function to create a build operation
* small refactoring of how build plan is extracted after the build is complete
> refactor how plugins call the build system when using the CLI

- CHANGELOG.md
motivation: keep change log accurate 
changes: add reference to SE-0303 in 5.6
> add reference to SE-0303 in 5.6 changelog

- Utilities/Docker/Dockerfile
- Utilities/Docker/docker-compose.2004.56.yaml
- Utilities/Docker/docker-compose.yaml
motivation: keep docker setup up to date
changes:
* add docker setup for 5.6 (nightly)
* udpate swiftpm system dependencies to include runtime dependencies (needed for tests)
* update volume mounts to include the dependencies on swift-system and swift-collections (needed by bootstrap)
> update docker setup

- Sources/Commands/Options.swift
- Sources/Commands/SwiftBuildTool.swift
- Sources/Commands/SwiftPackageCollectionsTool.swift
- Sources/Commands/SwiftPackageRegistryTool.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftRunTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/Commands/TestingSupport.swift
- Tests/CommandsTests/BuildToolTests.swift
- Tests/CommandsTests/SwiftToolTests.swift
motivation: fix an issue when not all options are presented as expected, and make the code clearer to reason about
changes:
* rename SwiftToolOptions to GlobalOptions
* refactor SwiftToolOptions (GlobalOptions) to multiple groups per domains: locations, caching, logging, build, linker, etc
* set GlobalOptions "hiddenFromHelp" flag to false for swift-build, swift-test and swift-package
* move enableCodeCoverage from GlobalOptions to TestToolOptions, since they apply there
* refactor code that construct test build to pass in more fine grained options rather than take the entire global options model
* adjust call sites and test
rdar://82658867
> refactor CLI options

- Sources/XCBuildSupport/PIF.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/Xcodeproj/XcodeProjectModel.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
When `—arch` has more than 1 arg, `swift build` triggers Xcode build system, e.g. `swift build —arch x86_64 —arch arm64`. Module aliasing needs to be supported with PIF gen in such scenario.
Resolves rdar://87363580
> Support module aliasing for PIF gen with xcode build system in SwiftPM

- Sources/PackageGraph/PackageGraph+Loading.swift
Move stack push out of a nested loop
Resolves rdar://89776259
> Early return when module aliases are not defined

- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
llbuild does not make guarantees that the output from subcommands are
emitted in complete buffers.  This shows up particularly well on
Windows.  clang will emit diagnostics which get read in different
chunks.  By emitting these eagerly we would print partial messages which
would leave the terminal in the improper state due to the message not
being complete.  With multiple parallel threads writing the messages
partially, we would get splits in the message that would yield
unreadable messages.
Switch to a buffering approach, buffering the entire content until the
command exits.  At that time we can emit the complete message in a
"single" write (which is locked).  This ensures that the output is no
longer partially emitted and corrects the rendering with the animated
emission on Windows. …
> Build: adjust the BuildSystemDelegate hander

- Sources/Commands/Options.swift
motivation: When invoking any unknown or help-triggering `swift package` command in terminal, the suggested invocation always includes the `--enable-dependency-cache` flag.
changes: useDependenciesCache flag to be non-optional, since this triggres a bug in argument parser which adds the option to the usage synopsis
note: underlying issue fixed in https://github.com/apple/swift-argument-parser/pull/416
rdar://89488586
> work around argument parser usage synopsis issue

- Sources/Workspace/RegistryPackageContainer.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
motivation: fix an existing issue with registry dependencies that can lead to resolution failure
changes:
* improve the placeholder manifest lookup of registry based dependencies that have alternative manifests
* add test
> fix a bug in resolving registry dependencies with alternative manifest versions

- Sources/Build/BuildPlan.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/ResolvedPackage.swift
- Sources/PackageGraph/ResolvedProduct.swift
- Sources/PackageGraph/ResolvedTarget.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/PkgConfig.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageModel/Platform.swift
- Sources/PackageModel/Target.swift
- Sources/SPMTestSupport/PackageGraphTester.swift
- Sources/SPMTestSupport/misc.swift
- Sources/Workspace/Workspace.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/Xcodeproj/pbxproj.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/PackageGraphTests/TargetTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
- Tests/XcodeprojTests/GenerateXcodeprojTests.swift
- Tests/XcodeprojTests/PackageGraphTests.swift
motivation: clients of libSwiftPM need access to both the raw (as entered in manifest) and derived (computed) platform support information
changes:
* move defaultLocalization and platforms information from target to ResolvedTarget, as this is derviced from the package level
* add defaultLocalization and platforms information to ResolvedPackage
* add defaultLocalization and platforms information to ResolvedProduct,derived from the product targets
* move the computation of derived platforms to package graph loading phase
* udpate call sites
* add and update test
rdar://86748009
> expose both raw and derived platform support information

- Sources/Commands/APIDigester.swift
- Sources/Commands/Options.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace+Configuration.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: nicer CLI experience
changes:
* rename --build-path to --scratch-space-path which better aligns with the meaning, and improve help messae
* use the "direcotry" completion option for locations since they mostly point to directories
* hide deprecate options like -C
* rename flag variables to better align with meaning
> improve location CLI options

- Documentation/PackageCollections.md
- Sources/Commands/SwiftPackageCollectionsTool.swift
Motivation:
A signed package collection with invalid or expired signature cannot be
previewed. `describe` prints error and there is no way to bypass the
error.
Modifications:
- Add `--skip-signature-check` flag to `describe`.
- Update error handling and messages
- Update docs
rdar://89993605
> 'describe' should allow previewing package collection with invalid signature

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
This was originally added to enable workflows like `swift run` on systems without Swift libraries in the OS. SwiftPM does not run on any systems old enough anymore at this point, so these rpaths can be removed at this point.
> Remove rpaths to the toolchain libraries

- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
Some projects like SwiftSyntax conditionally add some unsafe flags based
on environment variables. In the case they don't need them they add an
empty unsafe flags target. Previously this caused a failure, with this
change there is only a failure in the case the unsafe declaration
provides flags.
SwiftSyntax has also updated its Package.swift to not add the
empty `.unsafeFlags([])`, but this seems reasonable to be less strict
about as well.
Fixes https://bugs.swift.org/browse/SR-15989
> Allow empty unsafeFlags from dependencies

- Sources/Basics/Cancellator.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/BasicsTests/CancellatorTests.swift
- Tests/FunctionalTests/PluginTests.swift
motivation: consistent cancellation system to include plugins
changes:
* DefaultPluginScriptRunner is now Cancellable, with an internal copy of canncelator to maange its internal state
* dedup call sites that create DefaultPluginScriptRunner so that we can register it more easily with the SwiftTool::Cancellator instance
* Cancellator now supports Foundation::Process
> integrate plugins with new cancellation sub-system

- Sources/Basics/String+Extensions.swift
- Sources/PackageLoading/PackageBuilder.swift
- Tests/BuildTests/BuildPlanTests.swift
Throw an error if the module aliases parameter key/value pairs contain empty or invalid identifiers 
rdar://89836778
> Validate module alias input values

- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Specifically between the `BuildOperationBuildSystemDelegateHandler.commandProcessFinished()` and `BuildOperationBuildSystemDelegateHandler.commandProcessHadOutput()` methods.
The issue is that in one case there is access to `nonSwiftMessageBuffers` from outside the `org.swift.swiftpm.build-delegate` serial queue.
Fix ThreadSanitizer violation.
Move access to `nonSwiftMessageBuffers` inside the `queue.async`.
These tests were failing with thread sanitizer enabled, and now they're passing:
BuildToolTests.testXcodeBuildSystemDefaultSettings
BuildToolTests.testXcodeBuildSystemOverrides
TestToolTests.testEnableDisableTestability
MiscellaneousTestCase.testExternalDependencyEdges1
MiscellaneousTestCase.testExternalDependencyEdges2
MiscellaneousTestCase.testPkgConfigCFamilyTargets …
> Fixes data access race in command output handling detected by ThreadSanitizer

- Fixtures/Miscellaneous/TestDiscovery/Subclass/Package.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Sources/Subclass/Subclass.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsBase.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsDerived.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
Motivation:
In https://github.com/apple/swift-package-manager/pull/3992 the class name was stripped from the static array of tests (i.e. `__allTests_CLASSNAME` became `__allTests`). The class name ensured the variable was uniquely named. Without it, in a test class which is derived from another, it is not unique and results in compile-time errors. 
This is a regression introduced into Swift 5.6. See also: https://bugs.swift.org/browse/SR-15955
Modifications:
- Reintroduce the class name
- Add tests
Result:
Derived test classes do not result in compilation errors on Linux.
> Re-add class name to '__allTests' for test discovery

- Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
Motivation:
OCSP check can be done via HTTP POST or GET. The current code only does
POST and gives up if that fails.
Modification:
Try GET if POST fails.
rdar://90280783
> Support OCSP check via HTTP GET on non-Darwin platforms

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Previously if you had a binary target, that you replaced the checksum
and URL for at the same time, SwiftPM would reject it because the
checksum had changed. In my experience this is the common case when you
are copy pasting the inclusion instructions from documentation for an
update and then you run `swift build`.
In the case of package resolution the addedOrUpdatedPackages list is
always empty.
> Allow binary targets to change checksums and URLs at the same time

- Sources/Basics/HTTPClient.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageDescription/PackageDescription.swift
- Sources/PackageDescription/PackageDescriptionSerialization.swift
motivation: more reliable conditional imports
changes: use canImport(module) instead of os(OS) to drive conditional imports
> improve platform conditional imports

- Sources/Workspace/Workspace+BinaryArtifacts.swift
In the case of 404s from binary target URLs, the URLSession delegate to
write the file still gets called, since it's just a HTTP failure, and we
ended up copying an invalid file into the destination. This resulted in
subsequent builds failing since the file still existed. Now in this case
we remove the invalid archive regardless of failure reason.
Relevant log:
```
error: failed downloading 'https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/download/5.6/lib_InternalSwiftSyntaxParser.xcframework.zip' which is required by binary target 'lib_InternalSwiftSyntaxParser': badResponseStatusCode(404)
% swift build
error: failed downloading 'https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/download/5.6/lib_InternalSwiftSyntaxParser.xcframework.zip' which is …
```
> Remove binary target downloads on failure

- Fixtures/Miscellaneous/Plugins/PluginsAndSnippets/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginsAndSnippets/Plugins/PluginScriptTarget/Script.swift
- Sources/PackagePlugin/PackageModel.swift
- Sources/PackagePlugin/PluginContextDeserializer.swift
- Sources/PackagePlugin/PluginMessages.swift
- Sources/SPMBuildCore/PluginContextSerializer.swift
- Tests/FunctionalTests/PluginTests.swift
Snippets seem to be a kind of executable, and weren't handled properly by package plugins.  This adds a module type for snippets so that they are included in the list of targets passed to a plugin.
Snippets are a new experimental feature and should work with plugins.
- handle the case of a .snippet module
- add an enum type to represent snippet modules
Plugin is invoked without error and plugin can see the snippet.
rdar://89773759&89787888
> Package plugins throw an exception if snippets are present

- Documentation/Registry.md
- Error payload returned by the server *must* be in the format described
in "3.3. Error handling" to ensure consistent handling in SwiftPM.
- Add "4.6.2.1. Reserved metadata keys" to list reserved metadata keys
such that the server can make some safe assumptions and make use of
the metadata.
> Update registry service spec

- Sources/Commands/SwiftTool.swift
This is a hot fix for Windows build broken by #4224. #4231 also needs this change.
#4224 broke Windows build as @compnerd pointed out at https://github.com/apple/swift-package-manager/pull/4224#issuecomment-1072474100. The global function `exec` added in #4224 is actually unnecessary for Windows because [`signal(SIGINT, SIG_IGN)`](https://github.com/apple/swift-package-manager/blob/0e804edf19e05ddd02d05c1534d4ceea01117e5f/Sources/Commands/SwiftTool.swift#L418) is not compiled for Windows target.
```swift
#if os(Windows)
// set shutdown handler to terminate sub-processes, etc
SwiftTool.cancellator = cancellator
_ = SetConsoleCtrlHandler({ _ in
// Terminate all processes on receiving an interrupt signal.
try? SwiftTool.cancellator?.cancel(deadline: .now() + .seconds(30))
// Reset the …
```
> Fix a build failure on Windows (#4224)

- Sources/Workspace/DefaultPluginScriptRunner.swift
This could happen because the Process termination handler only called `availableData` and not `readToEnd()`, so based on timing, there might be data that had been emitted by the plugin subprocess before it exited but that hadn't yet been received.
This caused sporadic failures of the `testLocalAndRemoteToolDependencies` unit test.  And could of course sometimes cause output to be lost in actual usage too.
The fix is to switch to using `readToEnd()`.  This was not a problem for messages from the plugin, because they were already being read (and not collected using `availableData`).
rdar://89490777
> The last amount of `stderr` output from a plugin subprocess could occasionally get lost

- Sources/PackagePlugin/PackageModel.swift
An incorrect annotation from a recent change causes a warning.
Change `deprecated:` to `introduced:` for a new enum value.
Fix a warning (and correctly mark the symbol as not available in 5.7 and earlier).
> Fix a warning by correcting a `deprecated:` that should have been `introduced:`

- Sources/Basics/Cancellator.swift
Fix compilation failure on iOS, tvOS, watchOS.
Exclude `Foundation.Process` functionality on platforms that don't have that type.
Fix build failure.
> Annotate Cancellator APIs that involve Foundation.Process to exclude platforms that don't have it

- IntegrationTests/Tests/IntegrationTests/BasicTests.swift
- IntegrationTests/Tests/IntegrationTests/Helpers.swift
- IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
- Tests/CommandsTests/PackageRegistryToolTests.swift
- Tests/FunctionalTests/ResourcesTests.swift
- Tests/XcodeprojTests/FunctionalTests.swift
This cleans up the last of the instances of
`AbsolutePath.appending(RelativePath(_:))` in favour of
`AbsolutePath(_:relativeTo:)`.  The three remaining instances are of
`AbsolutePath.appending(RelativePath(validating:))`.
> Tests: replace use of `AbsolutePath.appending(RelativePath(_:))`

- Sources/PackageDescription/PackageDependency.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
- Tests/PackageLoadingTests/PD_Next_LoadingTests.swift
motivation: make experimental use of registry easier
changes:
* make registry based dependencies syntax available in 5.7
* move the relevant tests to the 5.7 suite
> make registry dependencies available in 5.7

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Workspace/Workspace+Configuration.swift
motivation: make legacy file warning less noisy if the file is empty
changes: check to see if the configuration file in the legacy location is empty before migrating it and emitting the warning
> ignore empty configuration files in legacy check

- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: add test coverage for a recently fixed issue
changes: add a test case for when binary dependency downlod fails and leaves behind a stray artifact which should be deleted
> add a test case to make sure binary artifact is deleted when download fails

- Fixtures/Miscellaneous/SwiftRun/Package.swift
- Fixtures/Miscellaneous/SwiftRun/main.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
motivation: test coverage for newly discovered regression
changes: add fixture based test case for this use case
> add test fixture for handling SIGINT on "swift run"

- Fixtures/Miscellaneous/TestDiscovery/Subclass/Package.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Sources/Subclass/Subclass.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsBase.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsDerived.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
Motivation:
In https://github.com/apple/swift-package-manager/pull/3992 the class
name was stripped from the static array of tests (i.e.
`__allTests_CLASSNAME` became `__allTests`). The class name ensured the
variable was uniquely named. Without it, in a test class which is
derived from another, it is not unique and results in compile-time
errors.
Modifications:
- Reintroduce the class name
- Add tests
Result:
Derived test classes do not result in compilation errors on Linux.
(cherry picked from commit 27cd3dff9d162ac456ac5fc8cbd674259d7de943)
rdar://90575219
> [5.6] Re-add class name to '__allTests' for test discovery

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
In the case of 404s from binary target URLs, the URLSession delegate to
write the file still gets called, since it's just a HTTP failure, and we
ended up copying an invalid file into the destination. This resulted in
subsequent builds failing since the file still existed. Now in this case
we remove the invalid archive regardless of failure reason.
Relevant log:
```
error: failed downloading 'https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/download/5.6/lib_InternalSwiftSyntaxParser.xcframework.zip' which is required by binary target 'lib_InternalSwiftSyntaxParser': badResponseStatusCode(404)
% swift build
error: failed downloading 'https://github.com/keith/StaticInternalSwiftSyntaxParser/releases/download/5.6/lib_InternalSwiftSyntaxParser.xcframework.zip' which is …
```
> [5.6] Remove binary target downloads on failure

- Sources/Workspace/Workspace.swift
This had been removed in one of the previous refactorings, but clients of libSwiftPM still need it.  This is because the actual minimum deployment version of the installed XCTest framework (part of the toolchain) establishes a hard floor on the minimum deployment version that can be used for tests, no matter what the package says.
- put back `customXCTestMinimumDeploymentTargets` with default value and pass it through
Clients of libSwiftPM can pass in a minimum deployment version for each platform, which will be used for the unit tests built for the package.
> Restore the ability to pass in `customXCTestMinimumDeploymentTargets` when loading a package graph

- Sources/PackageLoading/CMakeLists.txt
- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageModel/CMakeLists.txt
- Sources/PackageModel/MinimumDeploymentTarget.swift
- Sources/PackageModel/PlatformRegistry.swift
- Sources/PackageModel/ToolchainConfiguration.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Sources/Workspace/UserToolchain.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/PackageModelTests/MinimumDeploymentTargetTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
- Remove old fallback for PD libs in `ManifestLoader`
- Move computation for PD/PluginAPI library paths to `SwiftPMLibrariesLocation`
- Extend `SwiftPMLibrariesLocation` with the ability to pass in a minimum deployment target for PD/PluginAPI libraries. If a minimum deployment target is passed in by the client, `ManifestLoader`/`DefaultPluginScriptRunner` will not try to determine it on their own using `vtool`
- Remove copy of `computeMinimumDeploymentTarget` from `DefaultPluginScriptRunner`
> Improve handling of PD/PluginAPI libraries

- Sources/Commands/TestingSupport.swift
- Sources/PackageModel/UserToolchain.swift
The original change was the most expedient change to get the CI
coverage restored.  After further investigation, it seems that we are
able to reconstruct the XCTest path through a public variable that has
appeared after the original Windows support was added.  This now allows
us to restore the configuration to its previous state of `private`.
> Repair #4258

- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageModel/UserToolchain.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
This fixes two issues with the recent toolchain refactor:
- The custom search paths weren't being used for finding `swiftc`
- We lost the differentiation between the general and the manifest-specific Swift compiler. This restores it.
> Fix issues with recent `UserToolchain` refactor

- Sources/PackageModel/UserToolchain.swift
If the user specifies `-sdk` always prefer that over the `SDKROOT`
environment variable.  We would previously honor that but then fail to
pass along the argument.  We never noticed this as `SDKROOT` has always
been set up until this point.  With newer SDKs, this will become less a
guarantee.
> PackageModel: pass along `-sdk` property on Windows

- Sources/LLBuildManifest/Tools.swift
> Format args to module-aliases as a list of key/value strings before passing to llbuild 

- Sources/PackageDescription/Target.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
Target.Dependency.productItem/targetItem/byNameItem should not be used in a package manifest (they are only visible/public since they are part of function sigs that became public). Changing them to internal requires a lot more changes so throw an error with a suggestion to use the right API for now. Creating a static func for targetItem and byNameItem throws an invalid redeclaration error so this PR currently only handles .productItem use case.
Resolves rdar://91013735
> Throw an error if Target.Dependency.productItem is used instead of .product. 

- Sources/SPMBuildCore/BinaryTarget+Extensions.swift
In https://github.com/apple/swift-tools-support-core/pull/300, I made `Triple` more lenient w.r.t. different spellings of macOS. Since we are using string matching for finding matching binary artifacts, that would break with differently spelled triples. This PR in conjunction with https://github.com/apple/swift-tools-support-core/pull/307 ensures that we are finding artifacts based on the parsed representation of triples, not their string representations.
> Use `Triple` equality for finding matching binaries

- Fixtures/CFamilyTargets/CLibraryParentSearchPath/.gitignore
- Fixtures/CFamilyTargets/CLibraryParentSearchPath/Package.swift
- Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/CHeaderInclude/answers.c
- Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/CHeaderInclude/include/answers.h
- Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/Constants/Constants.h
- Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/HeaderInclude/FinalForm.swift
- Sources/Build/BuildPlan.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/MinimumDeploymentTarget.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/SPMBuildCore/BinaryTarget+Extensions.swift
- Sources/SPMBuildCore/Toolchain.swift
- Sources/SPMTestSupport/MockRegistry.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SPMTestSupport/misc.swift
- Sources/Workspace/InitPackage.swift
- Sources/Workspace/UserToolchain.swift
- Sources/Workspace/Workspace.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Sources/Xcodeproj/SchemesGenerator.swift
- Sources/Xcodeproj/generate.swift
- Tests/FunctionalTests/CFamilyTargetTests.swift
This replaces the use of `AbsolutePath.appending(RelativePath(_:))` in
the code base in favour of `AbsolutPath(_:relativeTo:)`.  This form
allows us to compute the absolute path prior to the normalization of the
path which ensures that we can validate the path properly.  This is
particular important to enable the use of relative paths on Windows
which cannot normalize at the parent path without a reference as there
may be substitutions which need to be applied.
> [5.6] Remove use of `AbsolutePath.appending(RelativePath(_:))`

- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyLibrary/Package.swift
- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyLibrary/Sources/MyLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyPlugin/Plugins/PackageScribblerPlugin/plugin.swift
- Sources/Commands/SwiftTool.swift
- Tests/FunctionalTests/PluginTests.swift
At some point `--disable-sandbox` seems to have stopped working for the commands run on behalf of plugins.  This caused one of the source compatibility suite packages (the protobuf one) to fail.
Not exactly sure when this broke, but the setting ended up not getting passed through in one of the refactorings a couple of weeks ago.  There wasn't a unit test covering this so it wasn't noticed until the source compat suite broke.  This commit adds a specific unit test for it.
- pass through `options.security.disableSandbox` to the corresponding `buildParameters` bit
rdar://90955872
After merging this we should revert https://github.com/apple/swift-source-compat-suite/pull/652 which XFAILed the SwiftProtobuf package test.
> `--disable-sandbox` didn't properly disable it for build tool plugin commands (just the plugins themselves)

- Sources/PackageDescription/PackageDependency.swift
Restore the doc of package(name:exact:) to sync with its actual semantics
It seems the doc comment was unintentionally taken from
`package(name:from:)`. This happend in 8dd0202d01f0d644a9d0a12fb039892d8828c240
Sync the documentation with `Requirement.exact`, which has the same semantics.
https://github.com/apple/swift-package-manager/blob/8dd0202d01f0d644a9d0a12fb039892d8828c240/Sources/PackageDescription/PackageRequirement.swift#L71-L76
> Restore the doc of `package(name:exact:)`

- Documentation/README.md
Replace the Package Manager Community Proposal broken link with a new working one.
replace the broken link with a new working one.
Avoiding error 404 page.
change the path from Internals/PackageManagerCommunityProposal.md  to ->  Design/PackageManagerCommunityProposal.md 
The link will work properly.
> Fix broken link

- Documentation/Plugins.md
There needs to be a guide to getting started with both using and authoring plugins.
Add `Plugins.md` file to `Documentation` directory.
This is a reasonably complete first version.  There will be lots of edits and additions, but seems like a good starting point.
> Getting Started with Plugins document

- Sources/PackagePlugin/ArgumentExtractor.swift
- Tests/PackagePluginAPITests/ArgumentExtractorTests.swift
Fix ArgumentExtractor implementation bug
`swift-docc-plugin` uses the PackagePlugin API and support `generate-documentation` action.
If we run
```
swift package --allow-writing-to-directory ./docs \
generate-documentation --target SymbolKit --output-path ./docs
```
It will be fine.
However if we run
```
swift package --allow-writing-to-directory ./docs \
generate-documentation --target=SymbolKit --output-path ./docs
```
It will loop infinitely.
And the core reason seems to be the ArgumentExtractor implementation in PackagePlugin Package.
- Fix the ArgumentExtractor implementation bug
- Add testExtractOption for ArgumentExtractor
When using `--<name>=<value>` form to specify the argument, the Plugin will no long loop infinitely.
I think this should be cherry-picked into release/5.7
But …
> Fix ArgumentExtractor implementation bug

- Sources/Commands/SwiftTestTool.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
Time tests for display in xunit report
It is useful to see simple reports on how long tests take to complete so a proper time duration has been added to the xunit report.
Replaced hardcoded time of `0.0` in xunit reports with proper time duration for each test run.
Xunit reports now report an accurate time duration for each testcase and an aggregate duration for each testsuite.
> Time tests for display in xunit report

- Sources/PackagePlugin/ArgumentExtractor.swift
- Tests/PackagePluginAPITests/ArgumentExtractorTests.swift
Fix ArgumentExtractor implementation bug
`swift-docc-plugin` uses the PackagePlugin API and support `generate-documentation` action.
If we run
```
swift package --allow-writing-to-directory ./docs \
generate-documentation --target SymbolKit --output-path ./docs
```
It will be fine.
However if we run
```
swift package --allow-writing-to-directory ./docs \
generate-documentation --target=SymbolKit --output-path ./docs
```
It will loop infinitely.
And the core reason seems to be the ArgumentExtractor implementation in PackagePlugin Package.
- Fix the ArgumentExtractor implementation bug
- Add testExtractOption for ArgumentExtractor
When using `--<name>=<value>` form to specify the argument, the Plugin will no long loop infinitely.
> [5.7] Fix ArgumentExtractor implementation bug (#4287)

- Tests/FunctionalTests/MiscellaneousTests.swift
motivation: test coverage
changes: improve state machine to handle the case the output is fully buffered and enable the test
rdar://91024625
> restore disabled testSwiftRunSIGINT test

- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
motivation: adjust SwiftPM to llbuild reporting of task progress, which now includes custom tasks
changes: increment finished tasks count based on the commandStatusChanged event instead of the commandFinished event
rdar://84883732
> update CommandTaskTracker to match llbuild's reporting of CustomTasks

- Sources/PackageLoading/ManifestLoader.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
motivation: flaky test
changes: reduce the amount of concurrent manifest loaded since its causing CI flakiness (runs for 1m+) and not material for what the test is checking - any number significantly larger than number of cores is sufficient
rdar://91272154
> reduce load created by manifest loading test

- Sources/Basics/JSON+Extensions.swift
- Sources/Build/BuildOperation.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/SPMBuildCore/PluginScriptRunner.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Provide more information to clients of libSwiftPM even when a compiled plugin doesn't have to be recompiled because nothing has changed since the last time it was.  Also make the API a bit cleaner.
Clients now get the command line and compiler output even in the case of failure, and also when the plugin doesn't have to be recompiled because nothing changed (previously this information was lost).  This is done by serializing a proper struct to JSON rather than just storing the hexadecimal representation of the configuration hash.
Callers also have control over the name of the temporary directory to represent the plugin, rather than always having it be the last path component of the sources directory.
The changes to the construction of the command line to compile plugins isn't nearly as …
> Clean up the code and some of the API of compiling plugins, and improve persistence of cached compiler outputs

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/PackageGraph.swift
- Sources/PackageModel/Sources.swift
- Tests/BuildTests/BuildPlanTests.swift
Validate source files for modules being aliased to only allow Swift sources
Resolves rdar://90661600
> Module aliasing: validate source files / only allow Swift files for modules aliased

- Sources/Workspace/DefaultPluginScriptRunner.swift
This fixes a build break on Windows from #4290.
> Fix breakage on Windows, which doesn't have `ProcessResult.ExitStatus.signalled`.

- Sources/PackageModel/UserToolchain.swift
`XCTest` accidentally did not use the directory form of the swiftmodule,
which did not matter with a single architecture being available.
Migrate to the directory form to match the SDK setup.  With the SDK
migrating to the architecture independent directory for the modules,
follow suit and provide a compatibility path that will allow use of
either.
Co-dependents:
apple/swift#42419
apple/swift-installer-scripts#119
apple/swift-driver#1063
> PackageModel: support the unified swift modules for XCTest

- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyLibrary/Package.swift
- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyLibrary/Sources/MyLibrary/library.swift
- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyPlugin/Plugins/PackageScribblerPlugin/plugin.swift
- Sources/Commands/SwiftTool.swift
- Tests/FunctionalTests/PluginTests.swift
This is the 5.7 nomination of #4283.  See that PR for details.
> [5.7] The `shouldDisableSandbox` setting wasn't being passed along to build tool plugin commands (#4283)

- Sources/Basics/JSON+Extensions.swift
- Sources/Build/BuildOperation.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/SPMBuildCore/PluginScriptRunner.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This is the 5.7 nomination of https://github.com/apple/swift-package-manager/pull/4290 and the follow-on Windows fix https://github.com/apple/swift-package-manager/pull/4299.  Those PRs contain the details.
Provide more information to clients of libSwiftPM even when a compiled plugin doesn't have to be recompiled because nothing has changed since the last time it was. Also make the API a bit cleaner.
> [5.7] Clean up the code and some of the API of compiling plugins, and improve persistence of cached compiler outputs (#4290 & #4299)

- Fixtures/Miscellaneous/PluginGeneratedResources/Package.swift
- Fixtures/Miscellaneous/PluginGeneratedResources/Plugins/Generator/plugin.swift
- Fixtures/Miscellaneous/PluginGeneratedResources/Sources/PluginGeneratedResources/PluginGeneratedResources.swift
- Sources/Build/BuildOperation.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/SwiftTool.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageModel/Target.swift
- Sources/SPMBuildCore/PrebuildCommandResult.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/PackageGraphTests/TargetTests.swift
> Handle generated resources from plugins

- Tests/FunctionalTests/MiscellaneousTests.swift
We are seeing this issue on the particular bot:
```
'dyld: Library not loaded: @rpath/libswift_Concurrency.dylib
Referenced from: /Users/ec2-user/jenkins/workspace/oss-swift-incremental-RA-macos-apple-silicon/build/buildbot_incremental/swiftpm-macosx-arm64/arm64-apple-macosx/bootstrap/pm/PluginAPI/libPackagePlugin.dylib
Reason: image not found
```
This speculatively bumps the minimum required toolchain for the test.
> rdar://92275318 (Swift CI Unblock:OSS - Swift Incremental RA - macOS - Apple Silicon - testPluginGeneratedResources Failure)

- Sources/PackageDescription/PackageDescription.docc/PackageDescription.md
I updated the links in the `PackageDescription` DocC docs to point to the correct location.
The links were incorrect in that they used `_` (underscore) to separate words, while the actual URLs used `-` (dash).
I modified the `Sources/PackageDescription/PackageDescription.docc/PackageDescription.md` file.
Only the above mentioned file was modified, and it now contains the correct links.
> Updated the links that point to using Swift packages with Xcode.

- Sources/PackageDescription/PackageDescription.docc/PackageDescription.md
Co-authored-by: Zsolt Kiraly <z.k@apple.com>
I updated the links in the PackageDescription DocC docs to point to the correct location.
The links were incorrect in that they used `_` (underscore) to separate words, while the actual URLs used `-` (dash).
I cherry-picked commit 7b2a4cdede2349d7aa8a735c6505124afb2370fb from PR #4324.
One file was changed: `Sources/PackageDescription/PackageDescription.docc/PackageDescription.md` with the updated URLs in the `PackageDescription` documentation catalog.
> [5.7] Updated the links that point to using Swift packages with Xcode. (#4324)

- Fixtures/Miscellaneous/ModuleAliasing/DirectDeps/AppPkg/Package.swift
- Sources/Basics/SwiftVersion.swift
- Tests/FunctionalTests/PluginTests.swift
As we do with every release, we need to turn off the development bit in SwiftPM so that it disallows use of 999.0 package manifest tools versions and also (somewhat less importantly) shows the version without a `-dev` suffix in response to `swift package --version`.
Specific changes:
- change `development` from true to false in SwiftVersion.swift
rdar://92289630
> [5.7] Mark the SwiftPM 5.7 branch as a release branch

- Tests/BasicsTests/CancellatorTests.swift
`sleep` is non-portable; prefer `Thread.sleep(forTimeInterval:)`.
> Tests: use `Thread.sleep(forTimeInterval:)` rather than `sleep`

- Tests/BasicsTests/CancellatorTests.swift
This avoids compiling code which is not run as it makes assumptions
about the environment.
> Tests: don't try to compile un-executed code

- Sources/Basics/VirtualFileSystem.swift
Rather than use a "root" for Windows, use the drive-relative path as a
"root" to terminate iteration/recursion.  Windows does not present the
file system as a unified singular rooted tree and instead has a forest
and thus the level-1 path is conceptually close to the root desired.
> Basics: alter the definition of root for Windows

- Tests/BasicsTests/EnvironmentVariablesTests.swift
The test expectations were pre-constructed with `:` ignoring the path
separator.  Alter the expectation to construct the value at run time to
match the actual results.
> Tests: correct some test cases for path separator

- Tests/BuildTests/LLBuildManifestTests.swift
This adjusts the expectations to allow Windows to be supported as well
with the use of the paths more thoroughly.  This identified an issue in
the path handling in the manifest generation (tracked as #5475).
> Tests: adjust LLBuildManifestTests expectations for Windows

- Sources/Basics/CMakeLists.txt
- Sources/Basics/WritableByteStream+Extensions.swift
- Sources/Build/BuildOperation.swift
- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
Command plugins can include a request for permission to modify the package directory.  In this case, `swift package` should:
a) if connected to a TTY, ask a "do you want to do this" question and wait for input
b) if not connected to a TTY, emit a message that you need to pass `--allow-writing-to-package-directory`
The current message doesn't provide information about how to grant the permission the plugin wants.  Also, if the user is invoking it interactively, it makes more sense to ask permission than have them invoke it again.
- if connected to a tty, ask the user
- if not, include the flag name in the error
- move down a extension to WritableOutputStream to detect whether it's connected to a TTY; this is now in Basics
- adjust unit test
When on a TTY this now looks like:
```
Plugin …
```
> `swift package` should ask for plugin permissions interactively when on a TTY

- Sources/Basics/CMakeLists.txt
- Sources/Basics/WritableByteStream+Extensions.swift
- Sources/Build/BuildOperation.swift
- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
This is the 5.7 cherry-pick nomination of https://github.com/apple/swift-package-manager/pull/5471
Command plugins can include a request for permission to modify the package directory. In this case, `swift package` should:
a) if connected to a TTY, ask a "do you want to do this" question and wait for input
b) if not connected to a TTY, emit a message that you need to pass `--allow-writing-to-package-directory`
rdar://89442616
(cherry picked from commit e65712cf6548677fb60ce17b8917031c0c11f239)
> [5.7] `swift package` should ask for plugin permissions interactively when on a TTY

- Sources/PackageDescription/PackageDescription.swift
- Sources/PackageDescription/PackageDescriptionSerialization.swift
- Sources/PackageLoading/Target+PkgConfig.swift
- Sources/PackageModel/Manifest/SystemPackageProviderDescription.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Tests/PackageLoadingTests/PkgConfigTests.swift
Introduce the `nuget` package provider, which is the only option on
Windows, but is portable to other systems as well. This is required
for enabling the test suite on Windows.
Refs: #4369
> Add `nuget` package provider

- Sources/Commands/SwiftTool.swift
This is to avoid warnings of the form `warning build: unable to perform implicit import of "_StringProcessing" module: no such module found`.
- pass ["-Xfrontend", "-disable-implicit-string-processing-module-import"] when compiling manifests if the compiler supports it
Avoid warnings when the `_StringProcessing` module isn't available.
> Pass `-Xfrontend -disable-implicit-string-processing-module-imports` to manifest and plugin compilation

- Sources/Commands/SwiftTestTool.swift
motivation: fix data race
changes: add lock when mutating test output as it may happen concurrently
rdar://92260631
> fix concurrent access issue when running tests in parallel

- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/XcodeprojTests/GenerateXcodeprojTests.swift
There is no guarantee that there is a singular unified file system view.
Use the current directory for the root of the filesystem.  This is
required for platforms like macOS (classic) and Windows where a forest
of roots exist.
> Tests: adjust test for real file systems

- Tests/CommandsTests/PackageToolTests.swift
It looks like the reason this wasn't caught in CI is because these tests have to be skipped since the test machines are running an older set of tools that don't support concurrency, which plugins require.  It's concerning if too many tests are skipped in CI, so we should see about having a way to not have so many tests getting skipped in CI.
> Fix a wording error in a unit test for package plugin commands

- Sources/Commands/SwiftTool.swift
This is to avoid warnings of the form `warning build: unable to perform implicit import of "_StringProcessing" module: no such module found`.
(cherry picked from commit 553b5ee263871d3082534f412d9519d1cd68fb73)
This is the 5.7 nomination of https://github.com/apple/swift-package-manager/pull/5487
> [5.7] Pass `-Xfrontend -disable-implicit-string-processing-module-imports` to manifest and plugin compilation (#5487)

- Tests/CommandsTests/PackageToolTests.swift
This is a 5.7 cherry-pick of https://github.com/apple/swift-package-manager/pull/5491.
(cherry picked from commit e2549fb443833040e21125b13d4a8402f8b1a30d)
> [5.7] Fix a wording error in a unit test for package plugin commands

- Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Compose paths using the path APIs to enable non-UNIX platforms to be
able to execute the test suite.
> Tests: make the Workspace tests pass on Windows

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/Target.swift
- Tests/BuildTests/BuildPlanTests.swift
Split module aliases propagation into two phases
Add a separate merge phase to handle reset or union of un/overriden aliases
Resolves rdar://92990727
> Handle reset/override of conflicting aliases from different products 

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/Target.swift
- Tests/BuildTests/BuildPlanTests.swift
Split module aliases propagation into two phases
Add a separate merge phase to handle reset or union of un/overriden aliases
Resolves rdar://92990727
> [5.7] Handle reset/override of conflicting aliases from different products 

- Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
This adjusts the package loading tests to allow them to pass on Windows
for the most part.  The one tests that currently does not work on
Windows is the `testConcurrencyNoWarmUp` which requires further work in
Foundation to fix a race condition which is tracked separately as
apple/swift-corelibs-foundation#4589.
> Tests: adjust the PackageLoading tests for Windows

- Tests/BasicsTests/SandboxTests.swift
`echo` is a `cmd` shell builtin and not available as a standalone binary
as from coretuils on Linux.  It should be noted that `echo` is available
as a shell builtin on Linux and is not required to be provided as a core
binary.  `tar` is only available on more recent Windows releases with 10
or newer.
> Tests: use `tar` rather than `echo` for sandbox test on Windows

- Sources/Workspace/Workspace+State.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: long running host processes (ie IDEs) need this in case other SwiftPM processes (ie CLI) made changes to the state
changes:
* call reload state before reloading the graph
* add test
> [alternative 2] reload workspace state before reloading package graph

- IntegrationTests/Tests/IntegrationTests/Helpers.swift
- Sources/SPMTestSupport/misc.swift
Rather than using `touch` which is not a universal command, use the
FileManager APIs to create the file.
> Tests: use `FileManager.default.createFile(atPath:contents:)`

- Tests/BuildTests/BuildPlanTests.swift
This is not related to the test and simply adds noise to the output.
> Tests: remove errant `print`

- Tests/BasicsTests/SQLiteBackedCacheTests.swift
- Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
Windows does not permit deleting files with open handles.  This test
appears to rely on those semantics (expecting that the deletion
operation will succeed and the file will be marked for delete on close).
Because Windows does not provide such semantics for `rm`, simply skip
the test on Windows.
> Tests: disable SQLite test on Windows

- Sources/Commands/SwiftPackageTool.swift
- Tests/CommandsTests/PackageToolTests.swift
The main branch ignores the `--pretty-print` command line parameter when dumping a symbol graph, this PR pipes it through to `SymbolGraphExtract`.
Both `swift package dump-symbol-graph` and `swift package dump-symbol-graph --pretty-print` produce compact non-prettified JSON. The infrastructure to support pretty JSON, including the command line option are already on "main" but the option is ignored and always set to `false`. This behavior is erroneous as the options help advertises the availability of the `--pretty-print` option.
There is a single line change passing the value of the command line parameter over to `SymbolGraphExtract`.
The `--pretty-print` option will produce prettified symbol graph JSON output.
These are the steps that the unit test follows, you can try them in the …
> fixes ignoring the "--pretty-print" comand line argument

- Sources/PackageLoading/PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
Use the `AbsolutePath` APIs to build paths to support non-`/` preferred
path separators.  This enables a subset of the PackageLoading tests to
now pass on Windows.
> PackageLoading: adopt `AbsolutePath` APIs for path representation

- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Product.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
Plugin targets can only be in plugin products, but right now there is no validation for this.  The plugin targets just get ignored, which is confusing.
- add validation for library products
- clarified the product name in the description of libraries (e.g. "dynamic library" instead of just "dynamic" for the type of product)
- make both executable and library products check that there are no plugin targets
- add a new unit test for libraries, and modify one for executables
We could extend this to other kinds of products in the future, but libraries and executables are the ones that accept targets today.
> Add validation checking for having plugin targets in library or executable products

- Sources/SourceControl/GitRepository.swift
Use `AbsolutePath` more aggressively for building paths and file system
names.  This enables the file processing to work properly on Windows as
well.
> SourceControl: adjust file path handling

- Sources/PackageRegistry/RegistryClient.swift
This uses `parentDirectory` to get the dirname of the path which will
also fix the path construction for Windows.  The construction of the
relative path is normalized and `..` cannot be normalized without an
anchor.
> PackageRegistry: use `parentDirectory` to get the parent directory

- Sources/PackageLoading/PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
Windows and subsequently `pkg-config` (and `pkgconf`) use `;` as the
path delimiter rather than `:`.  Adjust the codepaths to account for
the difference in the sigil.  Additionally, because `\` is the preferred
path separator on windows, the pkg-config specification behaves slightly
differently for the treatment of `\`.  Unless we are escaping spaces or
the `\` literal, emit the `\` as a character rather than treat it as an
escape modifier.  This gives us the desired behaviour, even though it is
a slight bit more clever than the reference implementations.
> PackageLoading: further portability changes for pkg-config

- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Product.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
(cherry picked from commit a802f691aa578084acbeede4a008362a5284c044)
This is a 5.7 nomination of https://github.com/apple/swift-package-manager/pull/5524
> [5.7] Add validation checking for having plugin targets in library or executable products (#5524)

- Tests/SourceControlTests/RepositoryManagerTests.swift
Use `url` rather than converting the path description to a string and
processing it on a specified path separator.  This will ensure that we
properly handle the path on Windows.
> Tests: normalize the repository path

- Tests/WorkspaceTests/WorkspaceTests.swift
The Windows platform uses `\` as a path separator, which must be quoted
by Swift strings, and the regex.  Thus the pattern suffers from
toothpickitis, but allows the test to pass on Windows.
> Tests: adjust path regex to account for alternate path separator

- Sources/Basics/DispatchTimeInterval+Extensions.swift
We would previously perform a `subtractingReportingOverflow` on the
nanosecond representation of the final time and a given point in time.
Furthermore, the directionality of time was unconsidered, that is, the
subtrahend may be greater than the minuend, which would give us negative
time.  The interface of `DispatchTimeInterval.uptimeNanoseconds` is a
value in `UInt64`.  Consequently, we would perform a difference
operation on `UInt64` values - unsigned values.  When the subtrahend was
greater than the minuend, we would get a value that is a 2s complement
representation of a negative value, which would then be converted to an
`Int` without a `bitPattern:` initializer, resulting in the negative
value being treated as a positive value.  Thus we were converting
negative time into a large …
> Basics: correct time handling

- Tests/BasicsTests/DispatchTimeTests.swift
SPM adds an extension for `DispatchTime` (the fact that it is public is
a separate issue) for adding `distance(to:)`.  This was previously found
to have an oversight in the implementation (#5539).  Add some test
coverage to prevent future regressions.
> Tests: add some test coverage for `DispatchTime`

- Sources/Basics/VirtualFileSystem.swift
This adjusts the VFS to make sure that it honors the path handling for
the target.  This is required for properly handling Windows paths.
> Basics: use `AbsolutePath` to handle paths

- Sources/SourceControl/Repository.swift
Prefer using the `url` member to get a URL representation of the
location, and then use the `pathComponents` property rather than
splitting on `/` which may be an invalid path separator.
> SourceControl: normalise repository basename computation

- Tests/BasicsTests/VFSTests.swift
Use the explicitly specified boolean state "macro"s rather than
converting the results to a true value.  This simplifies the checks
and makes it less likely to accidentally miss the `!`.
> Tests: clean up some `XCTAssert` usage

- Sources/Build/BuildPlan.swift
- Tests/WorkspaceTests/InitTests.swift
The `-rdynamic` link path works on Windows though requires that there
are exposed symbols.  In such a case, an import library will be emitted
along with the executable to permit the linking.  This marker changes
the location of the swiftmodule emission which enables the last test to
now pass.
> Build: mark Windows for supporting link against executable

- Tests/BasicsTests/ConcurrencyHelpersTests.swift
The Windows time-slice is in units of 10ms.  This along with the high
contention can cause the concurrency tests to be flakey.  Increase the
timeout some to enable more machines to pass.
> Tests: adjust slack for concurrency tests

- Tests/SourceControlTests/GitRepositoryTests.swift
This adds support for Windows to the compressed repository download
test.  Unfortunately, the repository contained within the tarball
contains files which contain invalid characters for some file systems.
For the time being, disable the test, though it would be preferable to
limit the repository contents to that which can be represented on all
file systems (perhaps consider the FAT32 restrictions which likely can
cover the file systems that we are likely to run on).
> Tests: adjust repository test and disable on Windows

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This was quite subtle. 
Normally, we resolve before calling `loadDependencyManifests` and roots will override any type of dependency in such a way that they don't become part of managed dependencies which means if we try to load via `loadManagedManifest`, we will get no result, essentially filtering them from dependency manifests. Now when requiring a resolved file, we are producing managed dependencies from the resolved file, plus we were adding entries for any local dependencies unconditionally which would mean we would get results from `loadManagedManifest`, resulting in an additional entry in dependency manifests, compared to the "normal" mode. 
This PR changes the behavior such that we don't add a local dependency to managed dependencies if there's a root with the same identity which …
> Avoid loading duplicated packages if a root overrides a local dependency

- Sources/Basics/TemporaryFile.swift
- Tests/BasicsTests/TemporaryFileTests.swift
Create helper functions for creating temporary files in order to slowly migrate to async/await based approach to concurrency
There are examples such as in ManifestLoading where async/await approach would be helpful to migrate from completionHandlers to async/await
As mentioned in https://github.com/apple/swift-tools-support-core/pull/321#issuecomment-1132432209 it was advised to put this code inside SwiftPM/Basics module in order to not increase amount of code in TSCBasics.
After that i would also create helper functions for creating temporary files, and maybe start to further investigate what kind of limitations exist to adopt async/await to manifest parsing. As far i can see `Process` also have to be migrated
> Create helper functions for temporary directories which supports new concurrency features

- Sources/PackageGraph/DependencyMirrors.swift
- Tests/WorkspaceTests/PinsStoreTests.swift
motivation: stable resolved files in complex mirroring configurations where multiple mapping exist for a singl repository, leading to non-deterministic reverse mapping
chnages:
* track all reverse index mapping instead of just the latest
* when performing reverse mapping, sort based on which mapping was "visited", then alphabetically
* add tests
rdar://93579273
rdar://94029942
> fix mirrors reverse mapping to be more deterministic

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/SPMTestSupport/Observability.swift
- Tests/PackageGraphTests/PubgrubTests.swift
motivation: reliable dependency resolution
changes:
* before adding a synthesized requirement, check if the negative requirement already exists
* add hard protection from infinite loop 
rdar://93335995
> fix an edge case where dependecy resolution can go into endless loop

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
This causes clients to have to filter diagnostics in order to avoid emitting empty lines.
- add a conditional before emitting a diagnostic
- update a unit test to check for it
rdar://94414151
> Avoid emitting a `.info` diagnostic with an empty message when there is no compiler output at all

- Sources/PackageDescription/SupportedPlatforms.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
Add the next version of each Apple platform to match the WWDC 2022 Xcode beta release.
This allows packages to specify the new platform versions as minimum deployment targets.
- add definitions of the next version of each platform
- add a test
> Update minimum deployment targets for the Apple platforms

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/FunctionalTests/PluginTests.swift
This is a 5.7 cherry-pick of #5566.
rdar://94414151
(cherry picked from commit e22ea16cf2c3e0820f33c1f8ed54ce468acad101)
> Avoid emitting a `.info` diagnostic with an empty message when there is no compiler output at all (#5566)

- Sources/Basics/Observability.swift
- Sources/PackageLoading/CMakeLists.txt
- Sources/PackageLoading/ManifestLoader+Validation.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/Workspace/Workspace.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/PackageLoadingTests/PDLoadingTests.swift
- Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_4_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: make code easier to reason about and maintain
changes:
* create new ManfeistValidator utility
* move manifest validation code out of ManifestLoader and Workspace and into the new validation utility
* seperate out manifst validation diagnostics from manifest loading diagnostics such that a fake diagnostics scope is no longer required
* adjust call sites and test
> consolidate and improve manifest validation

- Sources/PackageGraph/ModuleAliasTracker.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/Target.swift
- Tests/BuildTests/ModuleAliasingBuildTests.swift
This change is for automatic library products only. No product names are altered.
Add an ID property to Product and ProductReference: combine package ID and product name to make it fully qualified.
Pass packageID to Product/Reference initializers.
Use product IDs to look up duplicates if the product is an automatic library type. 
Use product IDs to compute aliasing related logic in ModuleAliasTracker.
Resolves rdar://89836609.
> Allow duplicate automatic library product names when module aliasing is used.

- Sources/Build/BuildOperation.swift
- Sources/Commands/SwiftTool.swift
- Tests/CommandsTests/SwiftToolTests.swift
motivation: continue cleanup work, fixing issues when diagnositics output ay interleave with delegates writing directly to the output or reportig progress
changes:
* change ToolWorkspaceDelegate to use provided  output and progress handlers instead of wirting to OutputStream directly
* add print and progress handlers to SwiftToolObservabilityHandler, including a serial queue to maange the sequence of outputing to the output stream
* adjust tests to wait on diagnostics when necessary given the queue setup
> refactor stream output and progress bars (part 1)

- Fixtures/Miscellaneous/FlatPackage/MyExec.swift
- Fixtures/Miscellaneous/FlatPackage/MyTest.swift
- Fixtures/Miscellaneous/FlatPackage/Package.swift
- Fixtures/Miscellaneous/FlatPackage/README.md
- Sources/LLBuildManifest/ManifestWriter.swift
- Tests/BuildTests/LLBuildManifestTests.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
This requires the llbuild commit a1adaff2a405c3a74925e60356431050cb9a3a9d, but it does not cause problems if the llbuild being used doesn't yet support this property.  Instead it will be ignored.
Also added a dedicated test with a flat package.
We should consider whether any customized scratch directory should also be included in the list.  This is a little tricky since the exclusion patterns are applied to all subdirectory name, not just those at the top level.  Oddly, in testing I did not repro the problem if I was using a custom scratch directory, so this may not be a issue in practice.
Note that this fixes the problem with doing spurious rebuilds (of which the spurious JSON output is just a symptom) for the case of a flat package structure, where the root directory of the package is …
> Use llbuild's new `content-exclusion-patterns` node attribute to prevent it from descending into `.build` and `.git` directories

- Sources/PackageDescription/SupportedPlatforms.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/Platform.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/BuildTests/MockBuildTestHelper.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
Update minimum supported deployment targets and mark older version constants as deprecated in tools-version 5.7.
If a package specifies a custom deployment target older than the minimum, the derived one in the model will be automatically raised, similar to how it was alreaady being done for test targets.
rdar://93920177
Xcode 14.0 is raising the minimum supported deployment target versions for most platforms.
> Adjust SwiftPM 5.7 to minimum supported deployment target changes

- Sources/PackageGraph/ModuleAliasTracker.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/BuildTests/ModuleAliasingBuildTests.swift
* Use alias value defined upstream as a key downstream for overriding and chain them
* Add pre-chained aliases to targets when needed and show diags
Resolves rdar://93445417, rdar://93218209
> [5.7] Module aliases override updates

- Sources/PackageDescription/SupportedPlatforms.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/Platform.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/BuildTests/MockBuildTestHelper.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/XCBuildSupportTests/PIFBuilderTests.swift
5.7 cherry-pick of https://github.com/apple/swift-package-manager/pull/5598
rdar://93920177
> [5.7] Adjust SwiftPM 5.7 to minimum supported deployment target changes

- Fixtures/Miscellaneous/DependenciesWarnings/app/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings/app/app.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep1/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep1/code.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep2/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep2/code.swift
- Sources/Build/BuildPlan.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
motivation: warnings from remote dependencies are not actionable and make the use of -warnings-as-errors difficult
changes:
* wire up the ResolvedPackage to SwiftTargetBuildDescription
* pass -suppress-warnings for remote dependencies
* add unit test
> suppress warnings from remote dependencies

- Fixtures/Miscellaneous/DependenciesWarnings/app/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings/app/app.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep1/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep1/code.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep2/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings/dep2/code.swift
- Sources/Build/BuildPlan.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
> [5.7] suppress warnings from remote dependencies 

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
> Add diagnostics to use module aliasing when duplicate targets found

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
> [5.7] Add diagnostics to use module aliasing when duplicate targets found

- Fixtures/Miscellaneous/DependenciesWarnings2/app/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings2/app/app.swift
- Fixtures/Miscellaneous/DependenciesWarnings2/dep1/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings2/dep1/code.swift
- Fixtures/Miscellaneous/DependenciesWarnings2/dep2/Package.swift
- Fixtures/Miscellaneous/DependenciesWarnings2/dep2/code.swift
- Sources/Build/BuildPlan.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
motivation: warnings-as-errors and suppress-warnings are mutually exclusive
changes:
* do not pass warnings-as-errors for remote dependencies which use suppress-warnings
* add test
> allow use of warnings-as-errors while dependencies have supressed warnings

- Sources/PackageDescription/Target.swift
This is a one-word fix for a typo. =)
> Fix a typo in the in-source docs of Target

- Sources/Commands/SwiftTool.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
This matches what we already do for package manifests.
rdar://95117842
> Pass `-v` to plugin compilation if in verbose mode

- Sources/Basics/Archiver+Zip.swift
- Sources/Basics/Cancellator.swift
- Sources/Build/BuildOperation.swift
- Sources/Build/SPMSwiftDriverExecutor.swift
- Sources/Commands/SwiftBuildTool.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/Utilities/APIDigester.swift
- Sources/Commands/Utilities/SymbolGraphExtract.swift
- Sources/Commands/Utilities/TestingSupport.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageLoading/PkgConfig.swift
- Sources/PackageLoading/Target+PkgConfig.swift
- Sources/PackageModel/Destination.swift
- Sources/PackageModel/UserToolchain.swift
- Sources/SourceControl/GitRepository.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Tests/BasicsTests/SandboxTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/XcodeprojTests/FunctionalTests.swift
- Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Basically it marks all usage of Process as TSCBasic.Process
It is to address a problem of disambiguation that occurs when creating `Process` inside SwiftBasics library. The motivation overall is driven by comment https://github.com/apple/swift-package-manager/pull/5532#issuecomment-1133212593
Specify explicitly that current `Process` is from `TSCBasic` library. It is done in source code and tests
The result is to make sure that adoption by targets of future `Process` inside SwiftBasics to be incremental
> Prepare SPM Targets for Process migration by specifying that callee should use TSCBasic.Process

- Fixtures/Miscellaneous/PackageWithMalformedLibraryProduct/Package.swift
- Fixtures/Miscellaneous/PackageWithMalformedLibraryProduct/Sources/PackageWithMalformedLibraryProduct/main.swift
- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/PackageBuilder.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
Currently a library product that includes an executable target in its `targets` array only results in a warning.  This was the best that could be done before `executableTarget` was introduced, since further checking was needed to see if a `target` was a library or executable target.  Since we have explicit types now, we should promote this to an error since people are running into it and it's not clear what the problem is.
This check is limited to tools version 5.7 or later.  This change includes a new test fixture and unit test.
rdar://95782540
> Validation of package products should check that a library product doesn't try to include executable targets

- Fixtures/Miscellaneous/PackageWithMalformedLibraryProduct/Package.swift
- Fixtures/Miscellaneous/PackageWithMalformedLibraryProduct/Sources/PackageWithMalformedLibraryProduct/main.swift
- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/PackageBuilder.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
This is the 5.7 nomination of https://github.com/apple/swift-package-manager/pull/5625.
rdar://95782540
(cherry picked from commit 5bd3355d7f76b0a899c83bbf8dee138af70298ab)
> [5.7] Validation of package products should check that a library product doesn't try to include executable targets (#5625)

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Cherry-pick of https://github.com/apple/swift-package-manager/pull/5621
----------------------------------------------------------
Behaviour modified in rdar://78280429.
Resolves rdar://95793872
> [5.7] Modify driver invocation on `swift run --repl` to match new REPL behavior.

- Sources/PackageDescription/Target.swift
This is the 5.7 nomination of #5624.
> [5.7] Fix typo in in-source docs for Target (#5624)

- Fixtures/Miscellaneous/TestDiscovery/Subclass/Package.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/Module1Tests/Tests1.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/Module1Tests/Tests2.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/Module2Tests/Test1.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsBase.swift
- Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsDerived.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
- Utilities/Docker/docker-compose.2004.56.yaml
- Utilities/Docker/docker-compose.2004.57.yaml
motivation: test discovery on linux depends on index store test listing
changes:
* use new API from TSC that fixes the issue
* adjust test
* add docker setup for 5.7
rdar://59655518
> improve  test discovery to include inherited tests

- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Package.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Plugins/MySourceGenBuildToolPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MyLocalTool/foo.dat
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MyLocalTool/main.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MySourceGenBuildTool/main.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MySourceGenBuildToolLib/library.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Plugins can specify dependencies on executables.  Currently, those executables get built before running build tool commands returned by the plugin if those dependencies were either:
- the path of the executable of a build tool command returned by the plugin, or
- explicitly included by the plugin in the list of input dependencies to a build command returned by the plugin
This could potentially be more efficient than building all dependencies, since a plugin could depend on two separate executables and then return commands that only used one or the other of them.  This would result in SwiftPM only building the executables that were actually mentioned by build commands.
However:  This led to confusion and multiple bug reports of failures resulting from not building the executables before …
> SwiftPM does not build all dependency executables before invoking plugin build command

- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Package.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Plugins/MySourceGenBuildToolPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MyLocalTool/foo.dat
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MyLocalTool/main.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MySourceGenBuildTool/main.swift
- Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MySourceGenBuildToolLib/library.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This is a 5.7 nomination of https://github.com/apple/swift-package-manager/pull/5636.
> [5.7] SwiftPM does not build all dependency executables before invoking plugin build command (#5636)

- Sources/SPMTestSupport/XCTAssertHelpers.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
This introduces a new `XCTSkipIfCI` and uses it in two tests which are flaky on CI.
rdar://96517321
rdar://96290746
> Skip tests which are flaky on CI

- Package.swift
This allows packages depending on SwiftPM to correctly resolve dependencies.
> [5.7] set `relatedDependenciesBranch` to `release/5.7`

- Sources/PackageGraph/ModuleAliasTracker.swift
- Sources/PackageModel/Target.swift
- Tests/BuildTests/ModuleAliasingBuildTests.swift
-Keep track of aliases that should be referenced directly
-Keep track of pre-chain aliases separately from the final module aliases
-Use above lists when applying final aliases
-Update logic to determine when to apply aliases
-Added additional tests
Resolves rdar://95724629
> [5.7] Updates to chained aliases / Use direct-ref aliases and pre-chain aliases

- Sources/Build/BuildPlan.swift
Stop using --gc-sections for Wasm target to protect metadata sections
Now wasm-ld strips data segments referenced through __start/__stop symbols
during GC, and it removes Swift metadata sections like swift5_protocols.
This option has been added in https://github.com/apple/swift-package-manager/pull/4135
We should add support for SHF_GNU_RETAIN-like flag for __attribute__((retain))
to LLVM and wasm-ld.
For now, just disable section GC for Wasm target.
Context
- https://github.com/llvm/llvm-project/issues/55839
- https://reviews.llvm.org/D126950#3558050
Swift metadata sections are retained in the final executable in release configuration for Wasm target.
CC: @MaxDesiatov @keith
> Stop using `--gc-sections` for Wasm target to protect metadata sections

- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/Library/Package.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/Library/Sources/Library/Library.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/PluginOnly/Package.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/PluginOnly/Plugins/MyPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Package.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Sources/TransitivePluginOnlyDependency/TransitivePluginOnlyDependency.swift
- Sources/PackageModel/Manifest.swift
- Tests/FunctionalTests/PluginTests.swift
In tools-version 5.2 or higher, we only include dependencies which are required in the package graph. Historically, any dependencies required by a target that's included in a product was considered required, we also need to include any dependencies that vend plugins required by those targets.
fixes #4334
rdar://93982305
> Mark plugin-only dependencies in required targets as required

- Sources/Build/BuildPlan.swift
Cherry-pick https://github.com/apple/swift-package-manager/pull/5638 because it's a regression happening since in 5.7
CC: @MaxDesiatov
> [5.7] 🍒 Stop using `--gc-sections` for Wasm target to protect metadata sections

- Utilities/bootstrap
`required` was only added as a parameter to `add_subparsers` in Python
3.7. Explicitly set `required` on `subparsers` after instead, which is
supported on all versions.
> Use < 3.7 compatible API for marking subparsers as required

- Fixtures/Miscellaneous/Plugins/MissingPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/MissingPlugin/Sources/MissingPlugin/MissingPlugin.swift
- Fixtures/Miscellaneous/Plugins/PluginCanBeReferencedByProductName/Package.swift
- Fixtures/Miscellaneous/Plugins/PluginCanBeReferencedByProductName/Plugins/MyPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/PluginCanBeReferencedByProductName/Sources/Exec/main.swift
- Fixtures/Miscellaneous/Plugins/PluginCanBeReferencedByProductName/Sources/PluginCanBeReferencedByProductName/PluginCanBeReferencedByProductName.swift
- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Manifest.swift
- Tests/FunctionalTests/PluginTests.swift
- if a plugin is referenced by its product name in the same package, automatically use the target instead
- if a plugin referenced in the same package doesn't exist, emit an error
fixes #5650
rdar://96664671
> Improve handling of missing plugins

- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/Library/Package.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/Library/Sources/Library/Library.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/PluginOnly/Package.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Dependencies/PluginOnly/Plugins/MyPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Package.swift
- Fixtures/Miscellaneous/Plugins/TransitivePluginOnlyDependency/Sources/TransitivePluginOnlyDependency/TransitivePluginOnlyDependency.swift
- Sources/PackageModel/Manifest.swift
- Tests/FunctionalTests/PluginTests.swift
> [5.7] Mark plugin-only dependencies in required targets as required

- Sources/Workspace/DefaultPluginScriptRunner.swift
Package plugins depend on the plugin library, which is not located in
the `Path` environment variable by default.  Adjust the path to ensure
that the plugin is able to locate the library.
Fixes: #5656
> Workspace: adjust `Path` when executing plugins

- Sources/PackagePlugin/Plugin.swift
Windows is much less lenient about handling and requires that a buffer
is provided if performing line buffering.  On Windows completely
disable all buffering instead which leaves us vulnerable to partial line
emissions if more than one thread is active.
Fixes: 5668
> PackagePlugin: change the `setvbuf` usage

- Sources/PackageDescription/Product.swift
- Sources/PackageDescription/Target.swift
Fix typo in in-source for Target.Dependency
Refine doc
From
```A denpendency on a target.```
To
```A dependency on a target.```
Better doc.
> Fix typo in in-source for Target.Dependency

- Sources/Basics/Cancellator.swift
Calling these on a process that isn't currently running results in
```
'NSInvalidArgumentException', reason: '*** -[NSConcreteTask terminate]: task not launched'
```
so we should check first.
rdar://96964401
> Do not try to interrupt/terminate a process if it isn't running

- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This seems like the better default until we might add a dedicated debugging feature for plugins.
This is the same as #5659 for 5.7, but since we are seeing a test issue there that seems to be limited to `main` potentially and that is outside of our control, I'm going to try to land this in 5.7 first given the timeline.
> [5.7] Build plugin executables with debug symbols

- Sources/swift-package/main.swift
- Utilities/bootstrap
motivation: support of package registry
changes:
* make sure swift-package-registry is installed (symlinked) via the bootstrap script
* add entry point in swift-package executable
> expose swift-package-registry as top level tool

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
motivation: heuristics was based on file name, which is not accurate enough and did not include files like LinuxMain.swift
changes:
* change heuristics to look into the ocntent of the source file and check for the @main annotation and decide on that
* update tests
> improve heuristics for @main support

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Reverts apple/swift-package-manager#5680
Verifying if this resolves the issue for swift-driver
```
/home/build-user/swift-driver/Sources/swift-help/main.swift:156:1: error: expressions are not allowed at the top level
SwiftHelp.main()
^
error: fatalError
```
> Revert "[5.7] improve heuristics for @main support"

- Sources/Basics/TemporaryFile.swift
- Sources/Workspace/Workspace.swift
In some environments we have to disable the implicit import of concurrency for reasons, so we need to explicitly import the module where needed.
Note: ideally, we would catch this by adding `-disable-implicit-concurrency-module-import` to the bootstrap invocation of `swift-build`, but I wasn't able to get that working locally without the inferior `swift-build` crashing on me. I'll open a separate draft PR for that change that we can land once that has been figured out.
rdar://97387827
> Import _Concurrency where needed

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
motivation: heuristics was based on file name, which is not accurate enough and did not include files like LinuxMain.swift
changes:
* change heuristics to look into the ocntent of the source file and check for the @main annotation and decide on that
* update tests
radar/9729773
> improve heuristics for @main support 

- Tests/FunctionalTests/MiscellaneousTests.swift
Seems like this is not necessarily failing when passing `-fmodules`, e.g. on Ubuntu 18.04. I don't think testing that this crashes in older tools-versions is important enough for the test to come up with more complex logic here, the important part is that it'll pass in newer tools-versions.
> Simplify `testCompileCXX17CrashWithFModules`

- Sources/Build/BuildPlan.swift
- Sources/PackageLoading/PackageBuilder.swift
- Tests/BuildTests/BuildPlanTests.swift
The heuristics for deciding whether to include the `-parse-as-library` flag
were recently improved in #5687 (rdar://97297732).
This change allows
`.snippet` target types to benefit from those improved heuristics.
Added `.snippet` to the cases allowed for `SwiftTargetBuildDescription.needsToBeParsedAsLibrary`.
Testing: Changed the walk when searching for snippets to explicitly use the
`PackageBuilder.fileSystem`; the default argument uses the local filesystem,
which won't work for in-memory filesystems used in tests.
Testing: Added additional snippet files, one with `@main` and one without, to
`BuildPlanTests.testParseAsLibraryFlagForExe`.
According to the same rules, snippets with `@main` should get
`-parse-as-library`, while those assumed to have top-level code should not. …
> Add .snippet target to @main heuristics for including -parse-as-library

- Utilities/bootstrap
We're currently loading the incorrect version of the concurrency compatibility libraries in OSS toolchains.
rdar://92270166
> Set rpath to compatibility libraries

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Similar to the comment here about wasm-ld, lld recently switched a
default that broke this for all elf targets. This is a low risk fix
since we weren't passing this flag before either. People who really need
this behavior can still pass something like `-Xlinker --gc-sections
-Xlinker -z -Xlinker nostart-stop-gc`
Fixes https://github.com/apple/swift-package-manager/issues/5698
> Remove --gc-sections for all targets for now

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Similar to the comment here about wasm-ld, lld recently switched a
default that broke this for all elf targets. This is a low risk fix
since we weren't passing this flag before either. People who really need
this behavior can still pass something like `-Xlinker --gc-sections
-Xlinker -z -Xlinker nostart-stop-gc`
Fixes https://github.com/apple/swift-package-manager/issues/5698
> [5.7] Remove --gc-sections for all targets for now

- Documentation/PackageDescription.md
Without the "https://" if you click the link, it tries to open: https://github.com/apple/swift-package-manager/blob/main/Documentation/www.semver.org.
- now the link works properly
- it also solves: https://github.com/apple/swift-org-website/issues/60
> Fix broken link in package description.

- Sources/swift-package/main.swift
- Utilities/bootstrap
> [5.7] expose swift-package-registry as top level tool

- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/LLBuildManifest/BuildManifest.swift
- Sources/PackageModel/Toolchain.swift
- Sources/PackageModel/ToolchainConfiguration.swift
- Sources/PackageModel/UserToolchain.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/BuildTests/MockBuildTestHelper.swift
Introduce a SPM controlled build rule for building static libraries.
This is the intended way to use llbuild to drive the generation of
static libraries.  We would previously rely on the static default
rule intended for testing to generate the static libraries.  Not only
did this tool not properly support Windows, it would actually cause
problems on macOS due to the use of `ar` for the creation of the library
over the preferred tool - `libtool`.  We now locally determine the
correct rule and generate the command.
This is incomplete support for Windows and in fact regresses
functionality.  We no longer honour `AR` as an environment variable on
Windows and thus cannot switch the implementation of the librarian.  We
now drive the archiving through `lld-link` unconditionally while we
should …
> Build: initial pass to support static archives on Windows

- Utilities/bootstrap
For release builds, we want the rpath to Swift compatibility libs to be relative to our executable.
> Adjust rpaths for release builds

- Utilities/bootstrap
We need to disable these implicit imports in some environments for reasons, this will avoid introducing breakage in those environments by verifying compatibility in CI.
> Disable implicit imports of Concurrency and StringProcessing

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
It should work with lld now that the lld flag `-z nostart-stop-gc` was added with apple/swift#60544 and apple/swift-driver#1153.
> Revert 'Remove --gc-sections for all targets for now (#5707)'

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Cherrypick of #5735
__Explanation:__ [lld 13 changed how `--gc-sections` works last year](https://reviews.llvm.org/D96914), which was then [flipped on by default](https://reviews.llvm.org/rG6d2d3bd0a61f5fc7fd9f61f48bc30e9ca77cc619), and causes all Swift code on ELF platforms not to link with lld 13 and 14 anymore if stripping is enabled.
__Scope:__ Only affects ELF platforms
__SR Issue:__ #5698 and apple/swift#60406
__Risk:__ low, since it only affects ELF platforms with lld, with nobody else complaining since this was merged six months ago in #4135
__Testing:__ I [just built the last August 2 source snapshot of the 5.7 toolchain for Android AArch64](https://github.com/buttaface/termux-packages/actions/runs/2886129294), where lld 14 is the default linker, with this flag enabled back then …
> [5.7] Revert 'Remove --gc-sections for all targets for now (#5708)'

- Utilities/Docker/Dockerfile
- Utilities/bootstrap
- Utilities/helpers.py
- Utilities/soundness.sh
- Utilities/test-toolchain
release/5.7 swift project moved to python3, moving swiftpm build tools to
python3 to match.
(cherry picked from commit c0d5daa8fb43d87a6043a79c3cd132987eb40623)
To support Ubuntu 22.04 for Swift 5.7, we need to cherry-pick changes to support Python3.
> [5.7] Migrate to python3

- Sources/Commands/SwiftPackageCollectionsTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/Workspace/Workspace+Configuration.swift
- Sources/Workspace/Workspace.swift
- Do not emit the warning for `swift build`, `swift test` etc, since these commands by definition to not work with package collections
- Do emit the warning for `swift package-collections` by request an active workspace
> Improve warning for deprecated collections config

- Sources/PackageLoading/PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
- Tests/PackageLoadingTests/pkgconfigInputs/dummy_dependency.pc
Dummy dependency can be seen in some awkwardly generated `.pc` files and it can crash SwiftPM silently at least on Windows.
To enhance robustness and avoid silent crashes on Windows.
Ignore parsed dependency with an empty name from a `.pc` file.
SwiftPM will not crash when parsing dependency list like `dep1, , dep2`.
> [PkgConfig] Avoid creating dummy dependency

- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
createCommand now returns an Optional, since command creation may fail.
rdar://99298420
> Transition away from deprecated protocol requirement in llbuild's Tool

- Sources/PackageLoading/PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
- Tests/PackageLoadingTests/pkgconfigInputs/dummy_dependency.pc
Cherry-pick of #5741
Dummy dependency can be seen in some awkwardly generated `.pc` files and it can crash SwiftPM silently at least on Windows.
To enhance robustness and avoid silent crashes on Windows.
Ignore parsed dependency with an empty name from a `.pc` file.
SwiftPM will not crash when parsing dependency list like `dep1, , dep2`.
> [5.7][PkgConfig] Avoid creating dummy dependency

- Utilities/bootstrap
Allow bootstrap to work when building a toolchain on Apple Silicon
We are ironing out the current issues we are having when building a toolchain on Apple Silicon, and currently we are hitting the following exception when bootstrap starts (rdar://99040114)
```
Traceback (most recent call last):
File "/Volumes/Storage/swift_public/swift-arm64/swiftpm/Utilities/bootstrap", line 825, in <module>
main()
File "/Volumes/Storage/swift_public/swift-arm64/swiftpm/Utilities/bootstrap", line 65, in main
args.func(args)
File "/Volumes/Storage/swift_public/swift-arm64/swiftpm/Utilities/bootstrap", line 329, in build
parse_build_args(args)
File "/Volumes/Storage/swift_public/swift-arm64/swiftpm/Utilities/bootstrap", line 225, in parse_build_args
args.bootstrap_dir = os.path.join(args.target_dir, …
```
> Allow bootstrap to work when building a toolchain on Apple Silicon

- Utilities/bootstrap
...so that the build with swiftpm can start.
This will allow to build a Swift toolchain on Apple Silicon
Addresses rdar://99484030
We are ironing out the current issues we are having when building a toolchain on Apple Silicon, and after #5754 we are now hitting
```
--- bootstrap: note: Building SwiftPM (with a freshly built swift-build)
--- bootstrap: error: cannot cross-compile for macosx-x86_64 
```
Amend a check so not to assume any particular architecture when assessing if we are cross compiling on Darwin.
We should be able to build swiftpm as part of a Swift toolchain on Apple Silicon
> bootstrap: generalize check for cross-compilation on Darwin

- Sources/Build/SPMSwiftDriverExecutor.swift
In response to https://github.com/apple/swift-driver/pull/1171, adopt TimePoint over Foundation.Date in the interface of DriverExecutor.
> Update SPMSwiftDriverExecutor to Adopt TimePoint

- Sources/PackageLoading/ManifestLoader.swift
Remove `rdar://73710910` workaround in `ManifestLoader`.
`rdar://73710910` is already fixed by apple/swift#35885. We can remove the workaround now.
Remove `rdar://73710910` workaround.
This should be NFC now.
> [PackageLoading] Remove `rdar://73710910` workaround

- Sources/Build/BuildOperation.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Sources/SPMBuildCore/PluginScriptRunner.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Fixes the output for "Compile plugin" commands to use the progress tracker, just as for build commands.
This fixes potential output corruption in the console output.  No change in behaviour.
- add delegate callbacks to the DefaultPluginScriptRunner so that clients can found out when compilation:
1. will start
2. did finish, or
3. was skipped because the cache is already up-to-date
- change the printing of the output to use the same progress tracker as for build commands
- only show the direct compiler output in verbose mode, as for build commands
An even better approach for a future PR would probably be to have the plugin compilation commands be registered as llbuild tasks, which would allow them to go through the regular dependency machinery.  This would still have to happen as a …
> Fix the output when compiling plugins before a build starts

- Sources/Commands/SwiftTestTool.swift
- Tests/CommandsTests/TestToolTests.swift
motivation: listing tests should not require rebuilding
changes:
* update argument parser usage to avoid hiding flag by "super" command
* add argument to list command to skip builds (dropped by mistake)
* add tests
> fix regression where swift test list --skip-build is ignored

- Examples/package-info/Sources/package-info/example.swift
- Sources/Basics/TemporaryFile.swift
- Tests/BasicsTests/TemporaryFileTests.swift
A few warnings remain and from what I can see they aren't really addressable? We're using a bunch of types in async code that inherently can't be sendable.
rdar://100038401
> Add `@preconcurrency` to imports where suggested

- Sources/Workspace/Diagnostics.swift
- Sources/Workspace/Workspace+BinaryArtifacts.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: improve the diagnostics when binary artifacts do not follow the naming / directory strucuture convention
changes:
* validate that the path is actually a directory (as expected by downstream code)
* improve diagnostics language
* add tests
> improve validation for binary artifacts

- Sources/PackageModel/Target.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Diagnostics.swift
- Sources/Workspace/ManagedArtifact.swift
- Sources/Workspace/Workspace+BinaryArtifacts.swift
- Sources/Workspace/Workspace+State.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: imporve the experience of using binary dependencies
changes:
* track binary artifacts type in workspace state, requires new version (v6) of state file
* derive binary artifact type from content of artifact, not name of directory
* update callsites and tests
radar/93973163
> refactor handling of binary artifacts such that they do not depend on naming conventions

- Sources/Basics/FileSystem+Extensions.swift
- Sources/Workspace/Workspace.swift
If we just copied the config to the new location or if the configs at old and new location are identical, do not warn about the presence of both configs. The warning's purpose is making people aware of the fact that different versions of SwiftPM are using different configs, but if they are identical, there's no need for them to really know about it.
rdar://99721607
> Improve collections configuration warning

- Sources/Build/BuildOperation.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/Options.swift
- Sources/Commands/SwiftTool.swift
- Sources/Commands/Utilities/GenerateLinuxMain.swift
- Sources/LLBuildManifest/BuildManifest.swift
- Sources/LLBuildManifest/Tools.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/ResolvedProduct.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/Target.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Sources/Workspace/Workspace.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/CommandsTests/TestToolTests.swift
- Tests/FunctionalTests/TestDiscoveryTests.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
There are situations where a user may wish to customize the entry point file used to run tests on non-Apple platforms via `swift test`. For example, to run custom code before invoking the `XCTMain(...)` function. But including a custom `XCTMain.swift` file (or its former name, `LinuxMain.swift`) causes `swift test` to solely rely on that file to run tests, and more importantly, it causes SwiftPM to skip automatic test discovery, so you end up needing to list all the tests to run in that file. Passing `--enable-test-discovery` explicitly does the opposite: it performs test discovery, synthesizes its own test entry point file, and ignores any custom entry point file present in the package.
This PR adds a way to both provide a custom test entry point file and still perform test discovery, …
> Add experimental flag which allows providing a custom test entry point file while still performing test discovery

- CHANGELOG.md
(As per title. See referenced PR for context.)
> Update changelog for #5728 [NFC]

- Sources/Basics/Observability.swift
- Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
- Sources/Build/SPMSwiftDriverExecutor.swift
- Sources/PackageCollections/API.swift
- Sources/PackageCollections/Model/PackageTypes.swift
- Sources/PackageCollections/Model/TargetListResult.swift
- Sources/PackageCollections/PackageCollections.swift
- Sources/PackageGraph/DependencyMirrors.swift
- Sources/PackageGraph/DependencyResolver.swift
- Sources/PackageLoading/IdentityResolver.swift
- Sources/PackageLoading/ToolsVersionParser.swift
- Sources/PackageModel/Manifest.swift
- Sources/PackageModel/PackageModel.swift
- Sources/PackageModel/PackageReference.swift
- Sources/Workspace/Workspace+Configuration.swift
- Sources/Workspace/Workspace.swift
- Tests/BasicsTests/ObservabilitySystemTests.swift
Currently, we still need the diagnostics compatibility layer because swift-driver uses the TSC diagnostics engine.
> Remove most deprecated APIs

- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Tests/BuildTests/BuildPlanTests.swift
This fixes a few callsites that weren't taking conditionals into account, most notably the check for minimum deployment target.
rdar://70543422
> Fix handling of build environment when planning

- CMakeLists.txt
- Package.swift
- Sources/Basics/CMakeLists.txt
- Sources/Basics/SQLite.swift
- Sources/Basics/SQLiteBackedCache.swift
- Sources/CMakeLists.txt
- Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
- Sources/SPMSQLite3/CMakeLists.txt
- Sources/SPMSQLite3/module.modulemap
- Sources/SPMSQLite3/sqlite.h
- Tests/BasicsTests/SQLiteBackedCacheTests.swift
- Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
This moves the SQLite API wrapper to SPM from tools-support-core.  There is currently a single user of this API, which is SPM.  By migrating the API to SPM we can deprecate the TSC interfaces to prevent new adoption. It also reduces the dependencies on `TSCUtility` for SPM which works towards the longer term goal of shedding the tools-support-core dependency.
> Basics: migrate `TSCUtility.SQLite` to `Basics`

- Sources/PackageLoading/PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigParserTests.swift
- Tests/PackageLoadingTests/pkgconfigInputs/case_insensitive.pc
Parse pkg-config keys case-insensitive
I had a typo `CFlags` instead of `Cflags` in a pkg-config file. The command line tool `pkg-config` had no problem parsing and doing the right thing. This would have helped.
Just lowercased the string in the switch statement.
I am guessing that makes parsing a little closer to what users might expect.
> read pkg-config files case insensitive

- Sources/Build/BuildPlan.swift
- Sources/PackageModel/Destination.swift
We should not use `extraCPPFlags` as a vehicle for specifying linker flags, instead just decide on which C++ library to link based on the target triple in `BuildPlan`.
Separately, it seems worthwhile to look into refactoring `Destination` to actually allow specifying linker flags since that seems to have been an accidental feature of `extraCPPFlags` (as long as one didn't pass compiler flags there as well).
rdar://100575898
> Fix use of `extraCPPFlags`

- Documentation/Registry.md
Properties with `type: array` MUST have an `items` property indicating the type of items in the array.
This is supposed to be a string array, right?
> Fix OpenAPI spec compliance issue

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
This seems like an oversight in `PackageBuilder` validation so I don't think it needs to be guarded by tools-version.
rdar://94661861
> Error on empty product names

- Documentation/PackageDescription.md
Fixed the typo `n` for `in` in the description of "A branch-based requirement".
> Fix typo in PackageDescription.md

- Sources/PackagePlugin/CMakeLists.txt
Synchronise the Package.swift and CMakeLists.txt to build this as a shared library.  Previously we were reliant on `-DBUILD_SHARED_LIBS=YES` being passed to properly construct this artifact.
> build: enforce shared library for PackagePlugin

- Sources/Workspace/DefaultPluginScriptRunner.swift
There were cases in which this code in DefaultPluginScriptRunner could crash.  This change introduces local variables that keep both the handle and handler alive long enough to not crash rather than doing it all in one expression.  Note that this isn't a race condition — the handler does the correct locking.  But the object lifetime was a bit ambiguous with the existing line of code, and the new one removes the ambiguity.
No new unit tests — 21 of the existing unit tests cover this, and that's how the ambiguity was found.
rdar://101229820
> Make the code that deals with the remaining data in the NSFileHandle readabilityHandler be more robust

- Tests/BuildTests/BuildPlanTests.swift
Windows uses a different C++ runtime, which we rely on the linker driver to adjust the linker invocation (due to ABI incompatibilities between debug and release builds).  This allows the BuildPlan tests to now pass on Windows.
> Tests: remove `-lstdc++` on Windows test expectations

- Sources/Commands/SwiftPackageTool.swift
- Sources/SPMBuildCore/PluginInvocation.swift
So far, we were ignoring conditionals here which could lead to looking for an executable that wasn't produced or trying to build one that was excluded.
> Respect conditionals when finding/building executables used by plugins

- Sources/PackageGraph/ModuleAliasTracker.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageLoading/Diagnostics.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/PackageModel.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/Target.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/BuildTests/ModuleAliasingBuildTests.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Resolves rdar://94744134
Use product IDs to distinguish products to allow duplicate product names.
Add a tool version check.
> Use product IDs to allow duplicate product names in package graph

- Utilities/build_ubuntu_cross_compilation_toolchain
`Utilities/build_ubuntu_cross_compilation_toolchain` is currently outdated.
Updated the script to use Swift 5.7, Ubuntu 22.04 (Jammy), and LLVM/clang 13.0.1.
Cross-compilation SDK script is working for latest versions of Swift and Ubuntu.
> Update cross-compilation SDK script for Swift 5.7

- Fixtures/Miscellaneous/RootPackageWithConditionals/Package.swift
- Fixtures/Miscellaneous/RootPackageWithConditionals/Sources/client/client.swift
- Fixtures/Miscellaneous/RootPackageWithConditionals/Sources/linuxOnly/linuxOnly.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/PackageGraph/PackageGraph.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
SwiftPM's build system always build every target that's part of a root package, regardless of its reachability in the graph, supposedly to ensure all the code in the root package will get exercised. This is of course fundamentally incompatible with the idea of conditional dependencies and therefore causes user confusion.
The most reasonable way to resolve this seems to be to exclude any target that's conditionally depended upon with a condition unfullfiled by the current build environment from building automatically because of its presence in the root package. This does not change what gets built based on dependencies, so degenerate cases where a target is depended upon both conditionally and unconditionally will not be affected. Because of this, it seems reasonable to not tie the new …
> Fix conditional dependencies in root packages

- Sources/SPMTestSupport/Toolchain.swift
- Sources/Workspace/DefaultPluginScriptRunner.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This seems like the better default until we might add a dedicated debugging feature for plugins.
> Build plugin executables with debug symbols

- Sources/PackageModel/Destination.swift
- Sources/PackageModel/Toolchain.swift
- Sources/PackageModel/UserToolchain.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Tests/BuildTests/MockBuildTestHelper.swift
Usually, CPP is used as an abbreviation for the C preprocessor, while CXX more commonly refers to the C++ compiler. We also use `cxxSettings` in `Package.swift` manifest: https://developer.apple.com/documentation/packagedescription/target/cxxsettings.
For this wider consistency, `extraCXXFlags` is introduced as a replacement for `extraCPPFlags`. The latter is then deprecated and is made a computed property that just returns the value of `extraCXXFlags`.
Users who are coming from C++ background can be more familiar with the codebase. In the next schema version of `destination.json` (introduced in a future PR) we can use the new naming as well.
> Introduce `extraCXXFlags`, deprecate `extraCPPFlags`

- Tests/WorkspaceTests/WorkspaceTests.swift
The path representation is always platform dependent and cannot be written as a literal.  Use `AbsolutePath` to ensure that we get the correct spelling for the path separator.
> Tests: correct expectations for WorkspaceTests

- Sources/Build/BuildPlan.swift
- Sources/Commands/Options.swift
- Sources/PackageModel/BuildFlags.swift
- Sources/PackageModel/CMakeLists.txt
- Sources/PackageModel/Destination.swift
- Sources/PackageModel/Toolchain.swift
- Sources/PackageModel/UserToolchain.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Sources/XCBuildSupport/XcodeBuildSystem.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/BuildTests/MockBuildTestHelper.swift
We're relying on `BuildFlags` from TSC for passing flags in some places, but there are also cases where flags are passed as separate properties, such as `extraCFlags`, `extraCXXFlags` etc.  `BuildFlags` is quite useful, as it allows grouping of these properties instead of passing them around separately. In most if not all cases they need to be passed all at once anyway. This apparently already let to issues, where `Destination` didn't have its own linker flags property, also see https://github.com/apple/swift-package-manager/pull/5793. We also had issues with inconsistent naming of these properties. Unifying everything under `BuildFlags` could prevent such issues from happening.
Adding `BuildFlags` to `PackageModel`, mostly a copy of the declaration in TSC, but with a cleaned up …
> PackageModel: add `struct BuildFlags`, reduce reliance on TSC

- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Add diags for non-existing binary used by prebuild plugin.
Add a test to verify a package with a plugin target no longer requires a non-plugin target.
Resolves rdar://90442392, rdar://86787091
> Add diags for non-existing binary used by prebuild plugin

- Tests/CommandsTests/PackageToolTests.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
> Unblock tests by skipping if concurrency is not supported

- Sources/PackageGraph/PackageGraph.swift
- Tests/FunctionalTests/PluginTests.swift
A target's use of a plugin is represented as a kind of dependency, but this should not influence the test association.  Otherwise every test that depends on a library that uses a plugin seems to be associated with every other target that uses the plugin.
This function is returning wrong results, causing tests of targets that use plugins to be incorrectly associated with other targets that use those same plugins.
- filter out plugin target dependencies
rdar://101564030
> `PackageGraph.computeTestTargetsForExecutableTargets() is incorrectly affected by plugin usage

- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Dependency/Binaries/MyVendedSourceGenBuildTool.artifactbundle/info.json
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Dependency/Binaries/MyVendedSourceGenBuildTool.artifactbundle/mytool-linux/mytool
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Dependency/Binaries/MyVendedSourceGenBuildTool.artifactbundle/mytool-macos/mytool
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Dependency/Package.swift
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Package.swift
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Sources/MyLocalTool/foo.dat
- Fixtures/Miscellaneous/Plugins/BinaryToolProductPlugin/Sources/MyLocalTool/main.swift
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/Commands/SwiftPackageTool.swift
- Sources/PackageGraph/ResolvedProduct.swift
- Sources/PackageLoading/ManifestLoader+Validation.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/Target.swift
- Sources/SPMBuildCore/PluginContextSerializer.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/FunctionalTests/PluginTests.swift
- Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
This adds support for vending an executable product that consists solely of a binary target that is backed by an artifact bundle. This allows vending binary executables as their own separate package, independently of the plugins that are using them.
rdar://101096803
> Support vending products that are backed by binaryTargets

- Sources/Commands/SwiftPackageTool.swift
- Sources/Commands/SwiftRunTool.swift
- Sources/Commands/SwiftTestTool.swift
- Sources/Commands/SwiftTool.swift
- Sources/Commands/Utilities/TestingSupport.swift
- Tests/CommandsTests/PackageToolTests.swift
Simple rename for clarity since we `getHostToolchain()`.
> Rename `getToolchain()` to `getDestinationToolchain()`

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/PackageGraph.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
A plugin target currently cannot depend on a library target or product; this PR adds a check to validate it and throws an error
Resolves rdar://95117424
> Add diagnostics for unsupported plugin dependency

- Sources/Commands/SwiftPackageTool.swift
Use `nil` instead of empty string for `DefaultCommand` as otherwise `swift package completion-tool generate-zsh-script` will generate an invalid script 
https://github.com/apple/swift-package-manager/issues/5789
Use `nil` instead of empty string for `DefaultCommand`
Fixes #5789
Tested locally
```
swift build
.build/arm64-apple-macosx/debug/swift-package completion-tool generate-zsh-script > ~/.oh-my-zsh/completions/_swift
```
and ZSH completion script works.
Script
```
#compdef swift
local context state state_descr line
_swift_commandname=$words[1]
typeset -A opt_args
_swift() {
integer ret=1
local -a args
args+=(
'(-h --help)'{-h,--help}'[Show help information.]'
'(-): :->command'
'(-)*:: :->arg'
)
_arguments -w -s -S $args[@] && ret=0
case $state in
(command)
local subcommands …
```
> fix completion script generation

- Sources/PackageModel/BuildEnvironment.swift
- Sources/PackageModel/Manifest/PackageConditionDescription.swift
- Tests/BuildTests/MockBuildTestHelper.swift
This allows filtering dependencies solely based on whether they support a given platform which may be desirable if the build configuration is not yet known.
> Make `configuration` optional in `BuildEnvironment`

- Tests/CommandsTests/BuildToolTests.swift
The test testBuildCompleteMessage appears to be sensitive to changes in the cache when built against the C++ driver. Let's make it a bit more tolerant by adding a build just to stabilize the cache before checking for the build messages.
> Update testBuildCompleteMessage to be more tolerant to cache changes

- Package.swift
It depends on `Basics`, so we should declare that dependency.
> Add missing dependency to `DriverSupport`

- Sources/Build/BuildOperation.swift
- Sources/Commands/SwiftTool.swift
This was broken in #5846 which accidentally used the default value instead of passing along the global option.
rdar://101681661
> Fix `disableSandboxForPluginCommands`

- Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
- Tests/PackageCollectionsSigningTests/CertificateTests.swift
- Tests/PackageCollectionsSigningTests/KeyTests+EC.swift
- Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift
- Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
- Tests/PackageCollectionsSigningTests/SignatureTests.swift
- Tests/PackageCollectionsSigningTests/SigningTests+ECKey.swift
- Tests/PackageCollectionsSigningTests/SigningTests+RSAKey.swift
- Tests/PackageCollectionsSigningTests/Utilities.swift
- Tests/PackageCollectionsTests/PackageCollectionsTests.swift
- Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
Currently, we get this linker warning:
```
ld: warning: method '-skipIfUnsupportedPlatformAndReturnError:' in category from /Users/neonacho/Projects/public/swift-package-manager/.build/arm64-apple-macosx/debug/PackageCollectionsTests.build/PackageCollectionsTests.swift.o conflicts with same method from another category
```
since we have two test modules defining the same category methods on `XCTestCase`. To avoid this, we can add a prefix to both implementations.
> Fix duplicated category method issue

- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
If a package does not specify a custom deployment target for MacCatalyst, we are supposed to fallback to the iOS one, if declared. This currently does not work for test targets, because we prefer the minimum XCTest deployment target, even if it may be lower than the customized iOS one.
> Fix MacCatalyst minimum deployment fallback

- Sources/Build/BuildPlan.swift
- Sources/SPMBuildCore/BinaryTarget+Extensions.swift
- Tests/BuildTests/BuildPlanTests.swift
When packaging a Swift dylib as an XCFramework, its modules will be at the top-level, so that directory needs to become part of search paths.
fixes #5723
> Improve search paths for XCFrameworks

- Utilities/bootstrap
It looks like so far we have only been passing `SWIFT_EXEC` to `swift-build` but not `swift-test`.
> Pass `SWIFT_EXEC` to swift-test via bootstrap

- Utilities/build_ubuntu_cross_compilation_toolchain
[ShellCheck](https://www.shellcheck.net) (a linter for shell scripts) discovered [a warning](https://www.shellcheck.net/wiki/SC2155) in our cross-compilation SDK script.
We'd like our shell scripts to be maintainable, readable, and debuggable, and not having linter warnings in them helps us achieve that.
In the original code, the return value of `brew` is ignored, and export will instead always return true. This may prevent conditionals, `set -e` and traps from working correctly.
`PATH` environment variable is declared and assigned separately to avoid masking return value of `brew`.
When `brew` is not installed on user's machine when the script is executed, they'll see a clear error messaging related to this, instead of resurfacing this as a different confusing error later in the script.
> Fix ShellCheck warning in CC SDK script for Ubuntu

- Tests/CommandsTests/BuildToolTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
They're blocking CI and we don't have an immediate fix or commit to revert.
> Skip two failing tests

- Sources/Basics/CMakeLists.txt
- Sources/Basics/VFSOverlay.swift
- Sources/PackageLoading/ManifestLoader.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
If there happens to be a file at the location passed into the `ManifestLoader`, we were using that to compile the manifest, instead of the actual contents. This is dangerous, because the public API of `ManifestLoader` accepts a custom filesystem parameter that is not taken into account at all here, so the file being used might not be the right one, it just has the same path on the local filesystem.
We could have done some more work to preserve the optimization in the case where the used filesystem is the local one and the correct file is being used, but that doesn't seem worth it since the vast majority of loads are being done for remote dependencies (this we may load multiple times as we are resolving) which are never using the local filesystem.
> Remove slightly dangerous optimization

- Package.swift
rdar://101868275 "error: cannot find 'XCTAssertEqual' in scope" can affect almost any functional test, so we flat out disable them all until we know what is going on
> Disable `FunctionalTests` temporarily

- Sources/Commands/SwiftTool.swift
- Sources/PackageModel/Destination.swift
- Sources/PackageModel/UserToolchain.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/PackageModelTests/PackageModelTests.swift
`Destination` type has some properties with pretty short names based entirely on abbreviations or knowledge of context. It also can't store the triple of the host that supports this destination. Making names of properties consistent makes it more maintainable and readable.
Introduced `sdkRootDir` replacing `sdk`, `toolchainBinDir` replacing `binDir`, and `destinationTriple` replacing `target` old names are marked as deprecated. Also added the new `hostTriple` property.
Makes property names in the codebase more consistent, also incorporates some preparatory work I'm doing for #5812.
> PackageModel: clean up naming of `Destination` properties

- Sources/Basics/TemporaryFile.swift
This fixes `Capture of 'body' with non-sendable type '(AbsolutePath, @escaping (AbsolutePath) -> Void) async throws -> Result' in a @Sendable closure` warning.
Added `@Sendable` attribute to the `body` argument of `withTemporaryDirectory`.
Less concurrency-related warnings when `Sendable`-related checks are enabled.
> Basics: add missing `@Sendable` to `withTemporaryDirectory`

- Sources/Basics/Observability.swift
This type is `private`, so plain renaming should be safe.
Applied renaming to `DiagnosticsHandlerWrapper` within `Basics/Observability.swift`. Also fixed a typo in a comment in the same file.
No more typo here, the type easier to find with textual/symbol search.
> Basics: fix `DiagnosticsHanderWrapper` typo

- Sources/SourceControl/RepositoryManager.swift
If there's an error populating the cache, check whether we're offline and have an existing valid repository state. If yes, use cached state and emit a warning.
On macOS, we're using network reachability to determine the connection status, on other platforms we rely on crude parsing of the git error message for now.
> Use repository cache without update if offline

- Sources/PackageLoading/ManifestLoader.swift
Previously, we were relying on `defer` to close the database, but that would mean we're closing it when exiting the scope which is typically *after* we are calling completion handlers. It seems as if we should instead call them before.
Related to rdar://101956252
> Close manifest cache DB before calling completion handlers

- Fixtures/Miscellaneous/APIDiff/BrokenPkg/Package.swift
- Fixtures/Miscellaneous/APIDiff/BrokenPkg/Sources/BrokenPkg/bestHeaders/header.h
- Fixtures/Miscellaneous/APIDiff/BrokenPkg/Sources/BrokenPkg/code.m
- Fixtures/Miscellaneous/APIDiff/BrokenPkg/Sources/Swift2/file.swift
- Sources/Commands/Utilities/APIDigester.swift
- Tests/CommandsTests/APIDiffTests.swift
It looks like `swift-api-digester` is always returning 0, so failures to parse modules can turn into false negative breakage reports. Do a minimal sniff test of the produced JSON to see if it contains symbols and if it does not, we'll emit the full output of `swift-api-digester` which will hopefully contain any errors encountered.
> Improve `diagnose-api-breaking-changes` error reporting

- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageLoading/ToolsVersionParser.swift
- Tests/PackageLoadingTests/ToolsVersionParserTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This change makes it clearer to the user what problem SwiftPM thinks their manifest has, avoiding some confusions in [cases like this](https://forums.swift.org/t/missing-swift-tools-version-specification-build-fail/61051).
In the future, for errors not specific to the tools version specification, we should move their diagnostics to before calling `ToolsVersionParser.parse`. This probably requires some restructuring of manifest parsing in general.
Some additional changes:
- Removed an incorrect FIXME, and added a TODO for testing `ManifestParseError.runtimeManifestErrors`.
- Decapitalised the description for the other `ManifestParseError` cases, in keeping with [Swift’s diagnostics style](https://github.com/apple/swift/blob/3a939255c8fc1f2825560cca3a5fa6b167c414c3/docs/Diagnostics.md).
> [PackageLoading] Diagnose empty manifest separately from missing tools version specification

- Tests/CommandsTests/APIDiffTests.swift
Looks like these tests are disabled by default, so some failures snuck in.
> Fix tests for `swift-api-digester` integration

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Tests/PackageGraphTests/PubgrubTests.swift
Before committing to the pinned version, the resolver should make sure that it's still available. This change fixes #5873.
If the resolver decides to honor a pin that is no longer available, the error message produced is `Dependencies could not be resolved because no versions of 'package' match the requirement 1.0.0..<2.0.0 and root depends on 'package' 1.0.0..<2.0.0`. However, that error message is confusing, because the requirement specified in the error message was replaced by the stricter version requirement that was pinned for the project. 
Since pinned versions are discarded if they no longer meet the requirements, it seemed reasonable to do the same if the pinned version is no longer available.
The resolver first checks to see if the pinned version of the package is still available …
> Verify that the pinned version is still available

- CHANGELOG.md
- Sources/PackageDescription/PackageDependency.swift
- Sources/PackageDescription/PackageDescription.swift
- Sources/PackageDescription/PackageDescriptionSerialization.swift
- Sources/PackageDescription/Target.swift
- Sources/PackageLoading/CMakeLists.txt
- Sources/PackageLoading/ContextModel.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/ManifestLoader+Validation.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageLoading/ModuleMapGenerator.swift
- Sources/PackageLoading/PkgConfig.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageLoading/ToolsVersionParser.swift
- Sources/PackageModel/CMakeLists.txt
- Sources/PackageModel/IdentityResolver.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
- Tests/PackageLoadingTests/PD_Next_LoadingTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This changes all imports of `Foundation` in the `PackageDescription` module to be implementation-only, making it so that it needs to be explicitly imported if being used. To avoid breaking existing packages, we inject an explicit import into manifests with tools-version 5.7 or earlier. In the next tools-version, `Foundation` will no longer be implicitly available.
rdar://92879696
> Remove implicit availability of `Foundation` from future manifest versions

- Sources/Basics/CMakeLists.txt
- Sources/Basics/ImportScanning.swift
- Sources/CoreCommands/SwiftTool.swift
- Sources/PackageLoading/ManifestLoader.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace+Configuration.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageLoadingTests/PDLoadingTests.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
This allows passing a minimal list of allowed modules and the minimum tools-version for applying the restricton to `ManifestLoader` and `WorkspaceConfiguration` (which passes it to the manifest loader). This allows clients of libSwiftPM to choose to be more restrictive about the modules package manifests are allowed to import.
rdar://92879696
> Extend `ManifestLoader` with the ability to restrict imports

- Examples/package-info/Sources/package-info/example.swift
- Tests/BasicsTests/TemporaryFileTests.swift
Since we merged https://github.com/apple/swift-tools-support-core/pull/367
> Fix preconcurrency-related warnings

- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
Landed two PRs at the same time which lead to the unexpected interaction of `Foundation` now showing up in the list of imported modules for tools-version 5.7 and earlier.
> Fix `testImportRestrictions`

- Sources/Basics/FileSystem+Extensions.swift
- Sources/CoreCommands/Options.swift
- Sources/CoreCommands/SwiftTool.swift
- Sources/PackageModel/Destination.swift
- Sources/PackageModel/Manifest.swift
- Sources/PackageModel/UserToolchain.swift
- Tests/PackageModelTests/DestinationTests.swift
- Tests/PackageModelTests/PackageModelTests.swift
"Cross-compilation SDK" is a bit of a mouthful to say, and we've previously denoted this as a "destination". After some consideration, I think calling "cross-compilation SDKs" as "destinations" simplifies a lot of things. Additionally, "target triple" and "target platform" are terms of art after all. Renaming them to "destination triple" and "destination platform" arguably was a mistake. Since we had no tagged releases in the meantime, let's clean up the naming before it's too late.
`--experimental-cross-compilation-sdks-path` is renamed to `--experimental-destinations-path`, `sharedCCSDKDirectory` to `sharedDestinationsDirectory`. `destinationTriple` is renamed to `targetTriple`.
More clear, widely consistent naming.
> PackageModel: rename "CC SDKs" to "destinations"

- Sources/CoreCommands/Options.swift
motivation: support registry based depedendencies
changes: enabe the "swizzle" mode by default, which would replace a dependency that comes from source control with one that comes frmo the regsitry when the identity mapping is known
> enable scm to regsitry substitution

- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
The additional bogus error muddles the water on what the underlying error was, so we should simply not emit it.
rdar://84000597
> Do not emit errors about the resolved file being out-of-date if cloning already fails

- CONTRIBUTING.md
Change references to JIRA to GitHub issues.
SwiftPM has moved away from JIRA 
Changed references to JIRA to GitHub and updated the description of the bug reporting fields.
More accurate docs.
> Update CONTRIBUTING.md to reflect that Jira is not used

- Tests/SourceControlTests/GitRepositoryTests.swift
motivation: Recent versions of git made a security fix to disallow the file transport by default. The GitRepository submodule test cases fail with these recent versions, because they use local submodules which rely on the file transport.
changes: The GitRepositoryTests submodule tests set the environment variable GIT_ALLOW_PROTOCOL=file to tell git to allow use of the file protocol only for these tests where it's required.
credit for this change to @dtweston
> update submodules tests to set GIT_ALLOW_PROTOCOL = file

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
Snippets illustrate how to use a package's products by design, so they shouldn't link to library targets that aren't exported as products.
If snippets link to all library targets, one negative result would be inadvertently linking to test support libraries, which could cause failures due to automatic linking of `@rpath/libXCTestSwiftSupport.dylib`, a library not available to snippets at runtime.
rdar://102746374
> Only automatically link snippets to product libraries

- Sources/PackageModel/Target.swift
- Tests/BuildTests/BuildPlanTests.swift
When computing the underlying executable target for a resolved product, consider snippet targets as well. Otherwise, this results in a fatal error when building a package that contains snippets.
rdar://102784273
> Consider snippets in ResolvedProduct.executableTarget

- Sources/PackageGraph/PackageGraph+Loading.swift
- Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Dramatically improve speed of cycle detection for large or well-connected manifest graphs.
Loading a project with a large or well-connected package graph in Xcode can be very slow. 
Xcode uses `Workspace.loadPackageGraph(rootPath:...)`, which calls into
calls into [`findCycle()`](https://github.com/apple/swift-package-manager/blob/25c671ef3ef2bd7a245403f9848cb3be3321c790/Sources/PackageGraph/PackageGraph%2BLoading.swift#L866). `findCycle` has a bug leading to slower than linear cycle detection.
There is a note to convert to use an algorithm tracking traversal with a stack, which would allow for linear time cycle detection. But given the output of `findCycle` is the path to first the cycle, and the cycle itself, not all the elements in a strongly connected subgraph, it's enough to memoize …
> [5.7] Avoid redundant checks in cycle detection

- Sources/Commands/SwiftRunTool.swift
- Sources/CoreCommands/SwiftTool.swift
- Tests/CommandsTests/RunToolTests.swift
motivation: swift run should handle signals correctly, recent refactoring broke it
changes: move the exec wrapper back to SwiftRunTool and rename it so its harder to regress
> fix a regression in swift run signal handling

- Sources/SPMTestSupport/PIFTester.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Sources/XCBuildSupport/XCBuildDelegate.swift
We were not embedding the resource bundle correctly when using XCBuild. This also fixes the delegate so that target and task diagnostics get emitted to the console.
rdar://102785735
> Fix use of resources when using XCBuild

- Package.swift
This was recently added, but generates a warning if unhandled, so we should mark it as excluded.
> Ignore `CODEOWNERS` in `XCBuildSupport`

- Documentation/Registry.md
This change clarifies two aspects of the registry specification per guidance from the Swift registry team. 
After reviewing the SPM Registry spec, I had two questions regarding how to interpret functional behavior of the registry. I reached out to @yim-lee who helped answer these questions. To close the loop, I am proposing these changes to the registry spec so that others in the future can interpret the spec with clarity.
1. Replace mentions of "latest version" with "highest precedence version" to clarify that it should be based on Semantic Versioning 2.0 precedence.
* Previously, the language could have been interpreted to mean that relative version ordering should be based on the time that the release was published.
* For example, package owners could publish a bugfix release versioned …
> Registry spec disambiguation

- Sources/PackageDescription/BuildSettings.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Tests/BuildTests/BuildPlanTests.swift
Implement the SwiftPM part of [SE-0362 "Piecemeal adoption of upcoming language improvements"](https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md).
> [SE-0362] Add `enableUpcomingFeature` and `enableExperimentalFeature` Swift settings

- Utilities/bootstrap
`Utilities/bootstrap` has `--clang-path`, which currently is parsed, but not propagated anywhere. Ignoring this option caused issues on certain Linux distributions, where the process of bringing up clang is convoluted and `bootstrap` ended up using GCC, which caused build failures.
`args.clang_path` value is now passed to CMake as `-DCMAKE_C_COMPILER`.
Build failures on Linux in certain configurations are fixed.
> Utilities/bootstrap: fix ignored `--clang-path` option

- Package.swift
motivation: more accuratly reflect internal target dependenies
changes: PackageGraph does not depend on SourceControl or Registry, only Workspace does
> improve internal target dependencies

- Sources/PackageLoading/PackageBuilder.swift
- Tests/PackageLoadingTests/PackageBuilderTests.swift
Following error message has word "sources" duplicated:
```
error: 'swift-png': target 'PNGUnitTests' has sources overlapping sources: /Users/*****/swift-png/tests/unit/XCTestManifests.swift, /Users/*****/swift-png/tests/unit/PNGTests.swift
```
Fixed above error message into following:
```
error: 'swift-png': target 'PNGUnitTests' has overlapping sources: /Users/*****/swift-png/tests/unit/XCTestManifests.swift, /Users/*****/swift-png/tests/unit/PNGTests.swift
```
👆🏻
> Fix error message

- Fixtures/Resources/Simple/Package.swift
- Fixtures/Resources/Simple/Sources/MixedClangResource/Foo.m
- Fixtures/Resources/Simple/Sources/MixedClangResource/bar.c
- Fixtures/Resources/Simple/Sources/MixedClangResource/bar.h
- Fixtures/Resources/Simple/Sources/MixedClangResource/include/Foo.h
- Sources/Build/BuildPlan.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/CommandsTests/TestToolTests.swift
- Tests/FunctionalTests/ResourcesTests.swift
Fix issue where adding a resource to a package containing Objective-C and C sources causes a build failure. **Note:** This only occurs when using `swift build` via the package manager CLI.
Please see https://github.com/apple/swift-package-manager/issues/5923 for the context regarding the issue. The package manager will add the `resource_bundle_accessor.h` as an input when compiling C sources. This causes a build failure because of the Foundation import in `resource_bundle_accessor.h`.
This PR fixes this issue.
- Modify build instructions for Clang targets to _not_ include the `-include /path/to/resource_bundle_accessor.h` compile argument when compiling a C source.
- Add unit test `testClangBundleAccessor` in `BuildPlanTests.swift`. I wrote this with intention of testing the fix but it …
> [Issue #5923] Fix resource-related build failure for package containing Objective-C and C sources

- Sources/Build/BuildOperation.swift
- Tests/CommandsTests/PackageToolTests.swift
> Stop build if there were build-tool plugin failures

- Sources/Commands/Utilities/TestingSupport.swift
- Sources/PackageModel/Destination.swift
- Sources/SPMTestSupport/Toolchain.swift
- Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift
We should not ignore errors or an empty SDK platform path since that means XCTest imports and test execution might silently fail on macOS with no indication to what the problem is.
> Improve `Destination.sdkPlatformFrameworkPaths()`

- Sources/PackageModel/Destination.swift
`extraCPPFlags` previously had a default value, but after renaming to `extraCXXFlags` in https://github.com/apple/swift-package-manager/commit/75877ea8304339a5e54da6638f2e476f3f47b406 this default value was lost. Let's restore it for compatibility with libSwiftPM clients.
`extraCPPFlags` argument of deprecated `Destination.init` now has a default argument, like it had before 75877ea8304339a5e54da6638f2e476f3f47b406.
Code relying on libSwiftPM now can rely on the default argument, as it did before.
> PackageModel: fix `Destination.init` default arguments

- Utilities/bootstrap
Not sure what has caused this, possibly underlying CMake changes, but I am seeing linker errors related to missing linkage of the C++ standard library recently. This changes `bootstrap` to explicitly inject into linker flags when building llbuild to avoid the problem.
> Fix `bootstrap` for certain macOS environments

- Sources/Build/BuildPlan.swift
- Tests/BuildTests/BuildPlanTests.swift
Always pass the `-static` parameter, instead of relying on the default of `libtool`.
This matches the implementation of the static linker in swift-driver, which always adds the explicit `-static`.
https://github.com/apple/swift-driver/blob/caa81e560362a4e14034cd4502114d03e45ea261/Sources/SwiftDriver/Jobs/DarwinToolchain%2BLinkerSupport.swift#L95-L102
Additionally, this improves the compatibility with LLVM's libtool, which does not (intentionally) default to static libraries (it defaults to do nothing).
Adds a new parameter `-static` for every invocation of `libtool` to create static libraries in Darwin.
The internal invocation of libtool always uses the `-static`. No changes should be experienced, since this is the default for cctools' `libtool`.
/cc @compnerd as the author of #5720 which …
> Build: create static libraries explicitly with libtool.

- Sources/PackageModel/PackageReference.swift
- Sources/Workspace/FileSystemPackageContainer.swift
- Sources/Workspace/RegistryPackageContainer.swift
- Sources/Workspace/SourceControlPackageContainer.swift
- Sources/Workspace/Workspace.swift
`PackageContainer` is a protocol that is implemented by various types involved in SwiftPM package resolution.  They can emit messages but those messages don't get associated with the diagnostics.
There are currently three implementors of this protocol:  `FileSystemPackageContainer`, `SourceControlPackageContainer`, and `RegistryPackageContainer`.  All three just assign a given `ObservabilityScope`, and setting a package location metadata on that scope is a good way to make sure that all the diagnostics emitted to that scope get associated with the package.
This fix makes sure that diagnostics emitted through these scopes get properly associated with the package.  This is particularly useful for manifest-related diagnostics, which inherit the scope used by the various kinds of …
> Add package metadata to observability scopes used by PackageContainers

- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/ManifestLoader.swift
- Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_4_LoadingTests.swift
- Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
- Tests/PackageLoadingTests/PD_Next_LoadingTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This could make it easier to debug these type of errors.
> Include the compiler commandline in `ManifestParseError.invalidManifestFormat`

- Sources/Commands/PackageTools/PluginCommand.swift
- Sources/SPMBuildCore/PluginInvocation.swift
- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Until now, we had two almost identical code paths for processing accessible tools and e.g. the command plugin code didn't get the fixes from #5945. This PR consolidates the two and also fixes a bug regarding executable path handling of vended tools.
> Consolidate plugin accessible tools

- Sources/Commands/PackageTools/DumpCommands.swift
- Sources/Commands/Utilities/PluginDelegate.swift
- Sources/Commands/Utilities/SymbolGraphExtract.swift
- Sources/PackagePlugin/PackageManagerProxy.swift
- Sources/PackagePlugin/PluginMessages.swift
- Sources/SPMBuildCore/PluginInvocation.swift
Adds support for emitting extension block symbols to the `dump-symbol-graph` command and other `SymbolGraphOptions`.
Extension block symbols with the respective command line flags `-emit-extension-block-symbols` and `-omit-extension-block-symbols` were introduced in apple/swift#59047 and apple/swift#61637 as part of an ongoing effort to solve apple/swift-docc#210. These flags should be exposed in higher-level commands such as `swift package dump-symbol-graph` as well as the package plugin API, so that users and package manager plugins such as [apple/swift-docc-plugin](https://github.com/apple/swift-docc-plugin) can access them more easily.
This PR adds the flag-pair `--emit-extension-block-symbols`/`--omit-extension-block-symbols` to the `DumpSymbolGraph` command and exposes the …
> Add emit extension block symbols option to `dump-symbol-graph` and `SymbolGraphOptions`

- Sources/Commands/PackageTools/DumpCommands.swift
- Sources/Commands/Utilities/PluginDelegate.swift
- Sources/Commands/Utilities/SymbolGraphExtract.swift
- Sources/PackagePlugin/PackageManagerProxy.swift
- Sources/PackagePlugin/PluginMessages.swift
- Sources/SPMBuildCore/PluginInvocation.swift
Reverts apple/swift-package-manager#5892
Breaks the windows build due to missing dependencies.
> Revert "Add emit extension block symbols option to `dump-symbol-graph` and `SymbolGraphOptions`"

- README.md
While bugs.swift.org no longer hosts Jira and redirect's to `swift` repository issue tracker, that's still wrong. We should direct people to SwiftPM's issue tracker.
> Update old link to Swift Jira in `README.md`

- Sources/Workspace/InitPackage.swift
Sample code for `swift package init --type executable` contains redundant `public` access modifiers on a `@main` type that isn't supposed to be available anywhere outside of its own module. 
Thus, `public` seems to be unneeded in sample code generated in `InitPackage.swift`
Remove `public` access modifiers from sample code generated by `swift package init --type executable`.
Sample code that's more lightweight.
> InitPackage.swift: remove redundant `public`

- Sources/Commands/PackageTools/PluginCommand.swift
Previously, we were creating a build system object in the inner loop, but it should be sufficient to just create one for all plugins.
> Reduce the amount of build system objects being created

- Sources/PackageLoading/ManifestLoader.swift
- Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
It looks like we're seeing an issue with the use of the VFS overlay on Windows which leads to manifests being loaded from the current working directory instead of the path mapped by the VFS. While we are investigating a solution, disable the use of the overlay on Windows since its intent is having more correct paths in diagnostics which is mostly cosmetic.
> Disable VFS overlay on Windows

- CHANGELOG.md
Two recently added links weren't correctly displayed in Markdown, as they required adding absolute links at the end of the document.
> Fix broken links in `CHANGELOG.md`

- Sources/Commands/PackageTools/DumpCommands.swift
- Sources/Commands/Utilities/PluginDelegate.swift
- Sources/Commands/Utilities/SymbolGraphExtract.swift
- Sources/PackagePlugin/PackageManagerProxy.swift
- Sources/PackagePlugin/PluginMessages.swift
- Sources/SPMBuildCore/PluginInvocation.swift
Fixes apple/swift-package-manager#5892. ~~Reverts apple/swift-package-manager#5975. The Windows build failure had nothing to do with the original PR #5892.~~
~~The [previous windows build](https://ci-external.swift.org/job/swiftpm-PR-windows/697/) for #5950, which does not include the changes from #5892 fails in exactly the same way.~~
> Fix "Add emit extension block symbols option to `dump-symbol-graph` and `SymbolGraphOptions`"

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Fix more cases in which there is a relevant package or package reference, but where the `ObservabilityScope` didn't have the metadata.
Clients of libSwiftPM that present diagnostics use the package metadata that can optionally be attached to an emitted `Diagnostic` to associate it with the package in the user interface.
This change addresses a few more cases in which no package metadata was associated.  Where possible, the metadata is associated with the `ObservabilityScope` at the highest place in the call stack so that any diagnostic emitted below it gets the package metadata.
- create child scopes with associated package metadata
- add the metadata directly to a couple of `emit()` calls where it wasn't clearly correct to create a new child scope
- extend a unit test
The diagnostic's …
> Add package metadata to a few more ObservabilityScopes in workspace-wide and package graph loading operations

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
SwiftPM 5.8 nomination of https://github.com/apple/swift-package-manager/pull/5984.
rdar://103561534
(cherry picked from commit 723a5925412f756333a77fee74aedae13569814e)
> [5.8] Add package metadata to a few more ObservabilityScopes in workspace-wide package operations

- Sources/Commands/PackageTools/DumpCommands.swift
- Sources/Commands/Utilities/PluginDelegate.swift
- Sources/Commands/Utilities/SymbolGraphExtract.swift
- Sources/PackagePlugin/PackageManagerProxy.swift
- Sources/PackagePlugin/PluginMessages.swift
- Sources/SPMBuildCore/PluginInvocation.swift
This PR reintroduces support for emitting extension block symbols for the `dump-symbol-graph` command originally introduced by #5892 and reverted by #5975.
The original PR #5892 was reverted because it caused a CMake build failure on Windows that hadn't been reported in the GitHub CI overview for the PR. This was fixed with 1de306b15aa4c386102d9295e68e313609419a7a. #5978, which contains the exact same changes as this PR, already landed on main. However, due to an unrelated build failure in the toolchain (see comments on #5978), merging #5978 was delayed until after the Swift 5.8 branch off. 
The following sections are taken from #5892 and should provide a good overview over the scope of this change and its impact on the Swift 5.8 release.
Extension block symbols with the respective …
> Fix "Add emit extension block symbols option to dump-symbol-graph and SymbolGraphOptions"

- Sources/CoreCommands/Options.swift
- Sources/CoreCommands/SwiftTool.swift
- Tests/CommandsTests/SwiftToolTests.swift
This PR adds a quiet flag (`-q`, `--quiet`) to `swift` commands which suppresses all but error output.
Closes #4395. Executable targets often depend on the output of other executable targets. When an executable target is run with `swift`, there is currently no way to suppress the build output, which makes it more difficult to pass the output of one executable as the input of another. The new quiet flag suppresses all output except errors.
- Added a `@Flag` to `LoggingOptions`
- Interpret that flag as a `Diagnostic.Severity` in `LoggingOptions.logLevel`.
- Added tests for both the short and long flag.
When a user passes the quiet flag, only errors will be logged.
> Add quiet flag (-q, --quiet) to LoggingOptions.

- Sources/PackageRegistry/RegistryDownloadsManager.swift
In some situations, `swift package purge-cache` raises the following error:
```
$ swift run swift-package purge-cache
Building for debugging...
[3/3] Linking swift-package
Build complete! (1.04s)
$HOME/Library/Caches/org.swift.swiftpm/registry/downloads
error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “downloads” doesn’t exist." UserInfo={NSFilePath=$HOME/Library/Caches/org.swift.swiftpm/registry/downloads, NSUserStringVariant=(
Folder
), NSUnderlyingError=0x6000019da940 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
```
It's better to check the existence of repository cache dirs.
This error raises in `withLock`. So I added an existence check of cache directories before calling this.
https://github.com/apple/swift-tools-support-core/blob/4cac812e26a1c9ec …
> Check existance of package resolver caches

- Sources/Build/SwiftCompilerOutputParser.swift
- Tests/BuildTests/SwiftCompilerOutputParserTests.swift
- Tests/CommandsTests/BuildToolTests.swift
SwiftPM uses the Swift Driver's `-parseable-output` flag to get a sequence of length-prefixed JSON-encoded messages that it can read.  Unfortunately the Swift Driver doesn't JSON-encode its own diagnostics, leading to things like https://github.com/apple/swift-package-manager/issues/5968.
I filed https://github.com/apple/swift-driver/issues/1241 on the Swift Driver to get it to encode its JSON messages, but meanwhile, it turns out that we can fairly easily fix the fallback logic that SwiftPM uses when it emits raw output.  It was simply missing a newline.  It's safe to always add one, since the logic that parses JSON splits by newlines, so we won't find any terminating newlines.
- add a newline after emitting the unparseable line of Swift Driver output
Raw output from …
> SwiftPM outputs raw diagnostics from SwiftDriver without trailing newlines [5968]

- Sources/PackageGraph/PackageGraphRoot.swift
> PackageGraphRoot.swift: fix typo in comment

- Sources/Build/SwiftCompilerOutputParser.swift
- Tests/BuildTests/SwiftCompilerOutputParserTests.swift
- Tests/CommandsTests/BuildToolTests.swift
This is the 5.8 nomination of https://github.com/apple/swift-package-manager/pull/5987.
rdar://103608636
(cherry picked from commit 14d05ccaa13b768449cd405fff81d630a520e04a)
> [5.8] SwiftPM outputs raw diagnostics from SwiftDriver without trailing newlines

- Sources/PackageDescription/PackageDescription.swift
SwiftPM manifests are compiled and then run, and they communicate the results representing the package structure back to SwiftPM via a JSON-encoded dictionary.  This JSON is currently pretty-printed, which includes inserting a bunch of whitespace.
In my measurements we can save about 35%-40% of the byte size by just skipping this formatting.  Anybody who wants to look at it for debugging purposes can just run it through `json_pp` or a similar formatter.
We still keep `.sortedKeys` for stability, and `.withoutEscapingSlashes` to avoid adding unnecessary escapes for path separators.
- remove the option to pretty-print the JSON emitted by the PackageDescription
No functional change, but cached manifests should be between 35% and 40% smaller.
> There's no need to pretty-print the JSON that a compiled manifest sends back to SwiftPM

- Sources/PackageDescription/PackageDescription.swift
This is a 5.8 nomination of https://github.com/apple/swift-package-manager/pull/5995.  The change is already in main.
> [5.8] There's no need to pretty-print the JSON that a compiled manifest sent back to SwiftPM (#5995)

- Sources/Basics/Sandbox.swift
This function is used solely in SPM and is the last portion of `TSCUtility.Platform` in use.  Move the implementation into the single use site to allow us to deprecate the interface in swift-tools-support-core.
> Basics: extract `darwinCacheDirectories` from `TSCUtility`

- Package.swift
This makes sure that dependencies of SwiftPM built with SwiftPM and coming from the Swift project use `release/5.8` branch.
> 5.8: set `relatedDependenciesBranch` to 5.8 in `Package.swift`

- Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
> PubgrubDependencyResolver: fix typo in child scope description

- Sources/swift-package-manager/main.swift
Currently, it fails with an error:
```
swift_package_manager/main.swift:39: Fatal error: swift-package-manager launched with unexpected name: swift-experimental-destination
```
> main.swift: fix `swift-experimental-destination` invocation

- Sources/Commands/ToolWorkspaceDelegate.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Adds a new package identity parameter to the callbacks for loading manifests.
Without this, implementors of these delegate calls that want the package identity have to re-derive it from the URL, which is lossy.  Instead the callbacks should pass through the package identity it already knows about.
- add a package identity parameter to each of the will/did callbacks for the manifest
- the client code has the original package identity
> Pass through the package identity as a parameter to `willLoadManifest`/`didLoadManifest` callbacks

- Sources/Basics/AuthorizationProvider.swift
- Sources/Basics/Netrc.swift
- Sources/CoreCommands/Options.swift
- Sources/CoreCommands/SwiftTool.swift
- Sources/PackageRegistry/RegistryClient.swift
- Sources/PackageRegistry/RegistryConfiguration.swift
- Sources/PackageRegistryTool/SwiftPackageRegistryTool.swift
- Sources/Workspace/Workspace+Configuration.swift
- Sources/Workspace/Workspace.swift
- Tests/BasicsTests/AuthorizationProviderTests.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/CommandsTests/SwiftToolTests.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
- Tests/PackageRegistryTests/RegistryConfigurationTests.swift
- Tests/WorkspaceTests/AuthorizationProviderTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
Evolution proposal: https://github.com/apple/swift-evolution/pull/1820
> Add token authentication support to SwiftPM

- Sources/Commands/ToolWorkspaceDelegate.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
The wall clock duration is already passed in didFetch, didUpdate, etc.  For completeness, Workspace should pass along the duration in the didLoadManifest/didCreateWorkingCopy/didCheckOut calls as well, so that libSwiftPM clients that want to use this information has access to it.
- capture the start and end times, and pass them in the delegate callback
- clients of these delegate calls have access to the duration for all of the will/did delegate call pairs
This builds on top of https://github.com/apple/swift-package-manager/pull/6019 (because the changes touch the same lines), so only the newer of the two commits is specific to this PR.
> Pass along the duration in the remaining WorkspaceDelegate calls as well

- Sources/Commands/ToolWorkspaceDelegate.swift
- Sources/CoreCommands/MinimalBuildTool.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
This is the 5.8 nomination of https://github.com/apple/swift-package-manager/pull/6019
> [5.8] Pass through the package identity as a parameter to `willLoadManifest`/`didLoadManifest` callbacks (#6019

- Sources/Basics/Errors.swift
Since https://bugs.swift.org redirects to https://github.com/apple/swift/issues/, we'd like to point users to the SwiftPM repository issues instead.
> Basics: don't point users to bugs.swift.org with `InternalError`

- Package.swift
rdar://82934196
Update to swift-crypto ~~2.2.1~~ ~~2.2.2~~ 2.2.3
> Switch to swift-crypto v2.x

- Sources/PackagePlugin/PackageManagerProxy.swift
`unimlemented` -> `unimplemented`
Since it's a case in a `public enum` of `PackagePlugin` module, which plugins are supposed to import, this is technically a source-breaking change. OTOH, do we expect that anyone had a `switch` for every case of this `enum`? This error case isn't thrown from anywhere.
> PackagePlugin: fix typo in `PackageManagerProxyError` case

- Sources/Build/BuildPlan.swift
Currently, the error message `BuildPlan.Error.noBuildableTarget` doesn't specify any actions that a user could take to resolve the issue.
Expanded the string literal returned from `description` of this error type to include a suggestion for users to take to resolve it.
Users who stumble upon the error are less confused by the error message.
> BuildPlan: provide user-actionable error description for `.noBuildableTarget`

- Sources/PackageLoading/ManifestLoader.swift
- Sources/PackageRegistry/RegistryDownloadsManager.swift
- Sources/SPMTestSupport/MockManifestLoader.swift
- Sources/SourceControl/RepositoryManager.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
- Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
- Tests/SourceControlTests/RepositoryManagerTests.swift
- Tests/WorkspaceTests/RegistryPackageContainerTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: better error reporting, more forgiving cache purging
changes: pass observability scope and emit warning / error when running into purge issues instead of throwing
rdar://103959749
> update purge cache to warn when failing to delete files

- .swiftformat
Since `Package.swift` specifies the lowest supported version as 5.5, let's update `.swiftformat` config accordingly.
> Update `.swiftformat` for Swift 5.5

- Sources/PackagePlugin/PackageManagerProxy.swift
`unimlemented` -> `unimplemented`
Since it's a case in a `public enum` of `PackagePlugin` module, which plugins are supposed to import, this is technically a source-breaking change. OTOH, do we expect that anyone had a `switch` for every case of this `enum`? This error case isn't thrown from anywhere.
> [5.8] PackagePlugin: fix typo in `PackageManagerProxyError` case

- Sources/swift-package-manager/main.swift
Currently, it fails with an error:
```
swift_package_manager/main.swift:39: Fatal error: swift-package-manager launched with unexpected name: swift-experimental-destination
```
> [5.8] main.swift: fix `swift-experimental-destination` invocation

- Utilities/bootstrap
We were still building llbuild with CMake even when the skip-option was passed.
> Fix `--skip-cmake-bootstrap`

- Sources/XCBuildSupport/XcodeBuildSystem.swift
We need to sanitize `DYLD_LIBRARY_PATH` in the environment before launching XCBuild because otherwise just built dependencies of SwiftPM can interfere with the linked dependencies of XCBuild which will typically not end well. This can e.g. happen during bootstrap builds.
> Sanitize environment for XCBuild

- Tests/FunctionalTests/PluginTests.swift
[`Tests/FunctionalTests/PluginTests.swift`](../../blob/main/Tests/FunctionalTests/PluginTests.swift) now compiles.
The [`FunctionalTests` target is currently disabled](https://github.com/apple/swift-package-manager/blob/main/Package.swift#L554-L564), but I've been developing functional tests for #5919. In the time that it has been disabled, I guess there have been some API changes that broke the tests. This PR just fixes the test file so it compiles.
Up until now, I have just been commenting out the file, but we might as well fix it so everything works when the `FunctionalTests` is re-enabled.
Fixed build errors in [`Tests/FunctionalTests/PluginTests.swift`](../../blob/main/Tests/FunctionalTests/PluginTests.swift).
If you uncomment the `FunctionalTests` target locally, the target now …
> [NFC] Resolve `Tests/FunctionalTests/PluginTests.swift` test file's build errors.

- CHANGELOG.md
- Documentation/ReleaseNotes/5.8.md
- Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
This was a change that landed in #5728 but it has the unintended consequence of generating unfixable warnings for packages which do import Foundation. We can probably solve that with import scanning to decide between the two import types, but given where we are in the 5.8 schedule, this seems to be something better done for a future manifest version.
See also #5991
> Disable implementationOnly Foundation import for resource accessor

- Tests/PackageGraphTests/PackageGraphTests.swift
This PR corrects a typo that was included in the following PR.
https://github.com/apple/swift-package-manager/pull/6006
> Fix typos in test cases

- Sources/Workspace/Workspace.swift
A convenience constructor of `Workspace` received some arguments. However, they are ignored. 
It may be a simple mistake.
I passed some arguments to the default constructor from arguments.
> Pass WorkspaceConfiguration from convenience constructor

- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageModel/PackageModel.swift
- Sources/PackageModel/Target.swift
- Tests/BuildTests/BuildPlanTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
>  Enable use of product ID to distinguish duplicate product names

- Sources/Build/BuildPlan.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageModel/BuildSettings.swift
- Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
- Sources/PackageModel/Target.swift
- Sources/XCBuildSupport/PIFBuilder.swift
- Tests/PackageGraphTests/PackageGraphTests.swift
- Tests/PackageGraphTests/TargetTests.swift
Currently, we are diagnosing unsafe flags in a bit of a backwards way, trying to infer them from build settings that were derived from them. This adds an explicit `usesUnsafeFlags` model property that is driven by whether the `unsafeFlags` API was used in a given target.
fixes #5965 
cc @DougGregor
> Refactor how we are diagnosing unsafe flags

- .gitignore
When opening the project with VS Code, it tends to create additional configuration files in this directory. So far I don't think it makes sense to share these settings between contributors, so let's ignore this directory for now.
> NFC: add `.vscode` directory to `.gitignore`

- Sources/PackageGraph/ModuleAliasTracker.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/PackageGraph.swift
- Tests/BuildTests/ModuleAliasingBuildTests.swift
Warn instead of error when non-Swift sources may be included in a target that has module aliases. This helps when a Swift target being aliased in a package is in a dependency graph of another package which contains non-Swift sources.
Resolves rdar://102137567
> Warn instead of error when non-Swift sources may be included in a target with module aliases

- Sources/XCBuildSupport/XcodeBuildSystem.swift
We need to sanitize `DYLD_LIBRARY_PATH` in the environment before launching XCBuild because otherwise just built dependencies of SwiftPM can interfere with the linked dependencies of XCBuild which will typically not end well. This can e.g. happen during bootstrap builds.
In the interest of forward compatibility, we should have this change in 5.8 as well.
> [5.8] Sanitize environment for XCBuild

- CHANGELOG.md
- Documentation/ReleaseNotes/5.8.md
- Sources/Build/BuildPlan.swift
This was a change that landed in #5728 but it has the unintended consequence of generating unfixable warnings for packages which do import Foundation. We can probably solve that with import scanning to decide between the two import types, but given where we are in the 5.8 schedule, this seems to be something better done for a future manifest version.
(cherry picked from commit cb9d03b0aa726434ab1dd0995230e97a7bd0a09b)
> [5.8] Disable implementationOnly Foundation import for resource accessor

- Sources/PackageLoading/ManifestLoader.swift
Looks like we missed enabling this for 5.8, but I think we should land it there.
> Enable Foundation-less manifests

- Sources/PackageLoading/ManifestLoader.swift
Looks like we missed enabling this for 5.8, but I think we should land it there.
(cherry picked from commit f23ab80b32b0fc89b0181602542e8125fd854615)
> [5.8] Enable Foundation-less manifests

- Sources/PackageGraph/ModuleAliasTracker.swift
- Sources/PackageGraph/PackageGraph+Loading.swift
- Sources/PackageGraph/PackageGraph.swift
- Tests/BuildTests/ModuleAliasingBuildTests.swift
Warn instead of error when non-Swift sources may be included in a target that has module aliases. This helps when a Swift target being aliased in a package is in a dependency graph of another package which contains non-Swift sources.
Resolves rdar://102137567
> [5.8] Warn instead of error when non-Swift sources may be included in a target that has module aliases

- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
We are seeing some failures in Swift CI that look similar to the compiler issue being worked around in #5659. For now, we will not assert if that particular part of the test fails and instead use `XCTSkip` plus log the bytes of the serialized diagnostics to the console.
rdar://96517321
> Skip `testCompilationDiagnostics` on certain failures

- Tests/SPMBuildCoreTests/PluginInvocationTests.swift
This is a follow-on to https://github.com/apple/swift-package-manager/pull/6076, which still contained a `XCTUnwrap()` that failed if there were no diagnostics.  See https://smooshbase.apple.com/swiftci/job/swift-pr-smoke-test/1860/console.
> Fix PluginInvocationTests.testCompilationDiagnostics() to avoid throwing if no diagnostics at all are reported

- Sources/PackageLoading/README.md
- Sources/PackageLoading/Target+PkgConfig.swift
- Tests/PackageLoadingTests/PkgConfigAllowlistTests.swift
`unallowed` -> `disallowed`, since `unallowed` is not recognized by system spellcheckers, and is marked in Wiktionary as an obsolete form. Also cleaned up wording in `Sources/PackageLoading/README.md`
> PackageLoading: fix tuple element wording

- Sources/PackageRegistryTool/SwiftPackageRegistryTool.swift
Add the explicit conversion to `DWORD` required on Windows.
> PackageRegistryTool: correct missing type conversion

- Sources/PackageGraph/ModuleAliasTracker.swift
> [NFC] PackageGraph/ModuleAliasTracker.swift: fix typo

- Sources/PackageRegistryTool/SwiftPackageRegistryTool.swift
Add the explicit conversion to `DWORD` required on Windows.
> [5.8] PackageRegistryTool: correct missing type conversion

- Tests/CommandsTests/BuildToolTests.swift
- Tests/FunctionalTests/MiscellaneousTests.swift
- Tests/WorkspaceTests/InitTests.swift
We are requiring tools-version 5.5 for a while, so these checks should not be required anymore.
> Remove checks for pre-5.5 versions of Swift.

- Sources/Basics/Concurrency/ConcurrencyHelpers.swift
- Sources/Basics/Concurrency/ThreadSafeKeyValueStore.swift
- Sources/PackageModel/CMakeLists.txt
- Sources/PackageModel/Manifest/Manifest.swift
- Sources/PackageModel/Manifest/PackageConditionDescription.swift
- Sources/PackageModel/Manifest/PackageDependencyDescription.swift
- Sources/PackageModel/Manifest/PlatformDescription.swift
- Sources/PackageModel/Manifest/ProductDescription.swift
- Sources/PackageModel/Manifest/SystemPackageProviderDescription.swift
- Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
- Sources/PackageModel/Manifest/TargetDescription.swift
- Sources/PackageModel/PackageIdentity.swift
- Sources/PackageModel/PackageReference.swift
- Sources/PackageModel/Product.swift
- Sources/PackageModel/SwiftLanguageVersion.swift
- Sources/PackageModel/ToolsVersion.swift
- Sources/SourceControl/Repository.swift
This is a first step towards making all model types in `PackageModel` compatible with Swift Concurrency. The only state that `class Manifest` had is `private` and is related to caching targets and dependencies. That state uses `ThreadSafeKeyValueStore`, which itself is `Sendable`.
Made `Manifest` conform to `Sendable`, since it's a model type and has no base classes or subclasses and all of its properties are declared with `let`.
`Manifest` is now `Sendable`, which removes a sendability warning when using `func loadRootManifest(at path: AbsolutePath, observabilityScope: ObservabilityScope) async throws -> Manifest` declared on `Workspace`.
> PackageModel: add `Sendable` conformance to `Manifest`

- IntegrationTests/Tests/IntegrationTests/BasicTests.swift
- IntegrationTests/Tests/IntegrationTests/Helpers.swift
- IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
For some reason these warnings were printed only in certain conditions, which may explain why these calls to a deprecated initializer of `AbsolutePath` persisted in the codebase for so long.
> IntegrationTests: fix `AbsolutePath` deprecation warnings

- Sources/PackageRegistry/RegistryClient.swift
- Sources/Workspace/Workspace.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
motivation: avoid unecessary server lookups
changes:
* treat 404 as valid response code
* cache both positive and negative server results to avoid redundant server calls
rdar://104954616
> improve registry identity lookup cache

- Sources/PackageGraph/DependencyMirrors.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageModel/IdentityResolver.swift
- Sources/SPMTestSupport/MockDependency.swift
- Sources/SPMTestSupport/MockPackage.swift
- Sources/SPMTestSupport/MockTarget.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: ease the transition to registry based dependencies
changes:
* extend the mirror API to allow mirror between source control and registry dependencies
* make sure target based dependencies take potentially different identity into account
* add tests
> allow mirror between source control and registry dependencies

- Sources/PackageGraph/DependencyMirrors.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageModel/IdentityResolver.swift
- Sources/SPMTestSupport/MockDependency.swift
- Sources/SPMTestSupport/MockPackage.swift
- Sources/SPMTestSupport/MockTarget.swift
- Sources/SPMTestSupport/MockWorkspace.swift
- Sources/Workspace/Workspace.swift
- Tests/CommandsTests/PackageToolTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
> [5.8] allow mirror between source control and registry dependencies

- Documentation/Plugins.md
- Sources/PackagePlugin/PackageModel.swift
- Tests/CommandsTests/PackageToolTests.swift
This essentially just does a cast to the protocol, but that makes plugin source code slightly nicer to read since this is a very common pattern.
resolves #5504
> Add a convenience accessor for `SourceModuleTarget` nature of a target

- Sources/PackageModel/UserToolchain.swift
- Tests/PackageModelTests/PackageModelTests.swift
Handle `-use-ld=` from the configuration in the selection of the librarian.  We do not honour the `-Xmanifest` or `-Xswiftc` flags being passed on the command line rather than the plist as we cannot pre-compute the flags.
> [5.8] PackageModel: partially address #5719

- Sources/PackageModel/CMakeLists.txt
- Sources/PackageModel/Toolset.swift
- Sources/PackageRegistryTool/SwiftPackageRegistryTool+Publish.swift
- Sources/SPMTestSupport/Observability.swift
- Tests/PackageModelTests/ToolsetTests.swift
As proposed in [SE-0387](https://github.com/apple/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md#toolsetjson-files), toolsets allow us to group paths and options for build tools. Adding this model to the codebase is a required step for fully implementing the proposal in case of its acceptance.
Added `Toolset` and `DecodedToolset` types. The latter is used for decoding from JSON, while the former is produced out of `DecodedToolset` after validation. Warnings are emitted into `ObservabilityScope` if unknown or invalid tools are found in `DecodedToolset`.
`Toolset` type in `PackageModel` can be used for new features as specified in the proposal. Note that it isn't actually used anywhere, so it's technically an NFC.
> [NFC] PackageModel: add `Toolset` model type

- Sources/PackageLoading/CMakeLists.txt
- Sources/PackageLoading/Platform.swift
- Sources/PackageLoading/Target+PkgConfig.swift
`Platform` type was recently moved from TSC to SourceKit-LSP. It should've been moved to SwiftPM for us to be able to share it with SourceKit-LSP.
> Don't use deprecated `Platform` from TSC

- Fixtures/Resources/EmbedInCodeSimple/Package.swift
- Fixtures/Resources/EmbedInCodeSimple/Sources/EmbedInCodeSimple/best.txt
- Fixtures/Resources/EmbedInCodeSimple/Sources/EmbedInCodeSimple/main.swift
- Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
- Sources/Build/LLBuildManifestBuilder.swift
- Sources/PackageDescription/Resource.swift
- Sources/PackageLoading/ManifestJSONParser.swift
- Sources/PackageLoading/PackageBuilder.swift
- Sources/PackageLoading/TargetSourcesBuilder.swift
- Sources/PackageModel/Manifest/TargetDescription.swift
- Sources/PackageModel/ManifestSourceGeneration.swift
- Sources/PackageModel/Resource.swift
- Tests/FunctionalTests/ResourcesTests.swift
Basic support for a new `.embed` resource rule which will allow embedding the contents of the resource into the executable code by generating a byte array, e.g.
```
@_implementationOnly import struct Foundation.Data
struct PackageResources {
static let best_txt = Data([104,101,108,108,111,32,119,111,114,108,100,10])
}
```
Note that the current naïve implementaton will not work well for larger resources as it is pretty memory inefficient.
> Support for embedding resources in an executable

- Sources/Build/BuildOperation.swift
- Sources/SPMBuildCore/BuildParameters.swift
- Sources/SPMBuildCore/PluginInvocation.swift
Hacky support for building plugin dependencies for the host. This is achieved by creating a second build operation with altered build parameters and individually building dependencies using that build operation, somewhat similar to how command plugins operate.
> Support for building plugin dependencies for the host

- Sources/Basics/Concurrency/ThreadSafeArrayStore.swift
- Sources/SPMTestSupport/MockHashAlgorithm.swift
This `Sendable` requirement on `HashAlgorithm` appeared in recent commits of TSC.
> Fix `MockHashAlgorithm` conformance to `Sendable`

- Tests/BasicsTests/ZipArchiverTests.swift
- Tests/CommandsTests/PackageRegistryToolTests.swift
changes: skip new zip compression tests where setting the process working environment is not supported
rdar://105175770
> skip zip compression tests in certain environments

- Sources/PackageRegistry/RegistryClient.swift
- Tests/PackageRegistryTests/RegistryClientTests.swift
- Tests/WorkspaceTests/WorkspaceTests.swift
motivation: adjust client behavior to the spec
changes:
* try to parse server error as defined by sepc and produce a structured error with the information returned from the server
* add tests for error cases
> improve registry client error handling

- Sources/XCBuildSupport/PIF.swift
`PIF.Target`'s Decodable initializer seems to be broken.
The encoder encodes `impartedBuildProperties` properties as `ImpartedBuildProperties` type.
https://github.com/apple/swift-package-manager/blob/2975732421aff9da0c03c66d191710a7e37055d7/Sources/XCBuildSupport/PIF.swift#L635
However, in the current decoder implementation, the decoder tries to decode them as `BuildSettings`.
https://github.com/apple/swift-package-manager/blob/2975732421aff9da0c03c66d191710a7e37055d7/Sources/XCBuildSupport/PIF.swift#L676
These are mismatched. So decoding always failed. As a result,`target.impartedBuildSettings` become always empty.
The decoder has to try to decode `impartedBuildProperties` as `ImpartedBuildPropertis` type instead of `BuildSettings`.
I can decode `PIF.Project` from dumped PIF JSONs.
> Fix PIF.Target model decoder

- Package.swift
- Sources/Basics/FileSystem/FileSystem+Extensions.swift
- Sources/Commands/PackageTools/PluginCommand.swift
- Sources/Commands/PackageTools/SwiftPackageTool.swift
- Sources/CoreCommands/BuildSystemSupport.swift
- Sources/CoreCommands/SwiftTool.swift
- Tests/CommandsTests/PackageToolTests.swift
motivation: improve usability of command plugins
changes: re-parse the arguments that are passed after the plugin name and merge the relevant options before running the command plugin
this allows invocation like `swift package <plugin> --disable-sandbox` (instead of the lest intuitive `swift package --disable-sandbox <plugin> `
> update plugin argument parsing so that execution arguments can be passed after command plugin name

- Sources/Basics/Concurrency/TokenBucket.swift
`CheckedContinuation` is already marked as `Sendable` in Swift 5.6 and later, but with Swift 5.5 on CI we're still seeing warnings related to this.
> Fix `Sendable` warning in `TokenBucket.swift`
