swiftlang/swift-package-manager

Sources/PackageDescription/SupportedPlatforms.swift

motivation: nicer documentation regarding availability
changes: add missing attributes in package description
rdar://96372508

add missing "since" and "availability" tags on platform versions

---

Sources/PackageCollectionsSigning/Utilities/Utilities.swift

Cannot use `extension Data` if `period` is going to be used with `+` operator via leading-dot syntax, for example: `Data(...) + .period` because `+` is declared as `(Self, Other) -> Self` where `Other: RangeReplaceableCollection, Other.Element == Self.Element` which means that `.period` couldn't get `Data` inferred from the first argument.

Declare Data.period property is a way compatitible with `+` operator

---

Sources/Workspace/InitPackage.swift

This seems like a leftover from the days of `generate-xcodeproj`.

Remove *.xcodeproj from default gitignore

---

Documentation/Registry.md

Motivation:
To create a package release, one should do a `PUT /{scope}/{name}/{version}` HTTP request. That's what it's said everywhere in the spec except in the example.
Modification:
Fix example request to be consistent with the spec.

Fix typo in publish API example

---

Sources/Commands/PackageTools/APIDiff.swift
Sources/Commands/PackageTools/Format.swift
Sources/Commands/PackageTools/PluginCommand.swift
Sources/Commands/PackageTools/SwiftPackageTool.swift
Sources/Commands/SwiftRunTool.swift
Tests/CommandsTests/PackageToolTests.swift

motivation: Address warnings
changes: use newer API for retrieving unparsed arguments

update use of argument parser to latest API

---

Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Tests/CommandsTests/PackageRegistryToolTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

motivation: update based on recent spec
changes:
* do not request server requirements, deduce configuration based on user provided flags
* fix issues in publishing logic per testing

update registry publishing

---

Documentation/Registry.md
Sources/PackageRegistry/RegistryClient.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

Motivation:
The 'Content-Version' header is required in all registry server responses to indicate API version. However, it shouldn't be required for responses that don't/can't change, such as the download archive and fetch package manifest endpoints. This may also cause problems for registry that have these files hosted elsewhere, because they may not have full control over response headers.
Modifications:
- Modify registry API spec to make 'Content-Version' optional for the said endpoints
- Adjust `RegistryClient`
rdar://105415468

[Registry] Make 'Content-Version' optional for archive and manifest download API

---

Documentation/Registry.md
Sources/PackageRegistry/RegistryClient.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

Cherry picking https://github.com/apple/swift-package-manager/pull/6153 to 5.8.
The API spec changes are the same, but the implementation is different. 
Motivation:
The 'Content-Version' header is required in all registry server responses to indicate API version. However, it shouldn't be required for responses that don't/can't change, such as the download archive and fetch package manifest endpoints. This may also cause problems for registry that have these files hosted elsewhere, because they may not have full control over response headers.
Modifications:
- Modify registry API spec to make 'Content-Version' optional for the said endpoints
- Adjust `RegistryClient`
rdar://105415468

[5.8][Registry] Make 'Content-Version' optional for archive and manifest download API

---

Sources/PackageModel/UserToolchain.swift
Tests/PackageModelTests/PackageModelTests.swift

Handle `-use-ld=` from the configuration in the selection of the librarian.  We do not honour the `-Xmanifest` or `-Xswiftc` flags being passed on the command line rather than the plist as we cannot pre-compute the flags.

PackageModel: partially address #5719

---

Sources/PackageGraph/CMakeLists.txt
Sources/PackageGraph/RegistryReleaseMetadata.swift
Sources/PackageGraph/ResolvedPackage.swift

This adds optional information about a resolved package if it was obtained from a registry. This information includes metadata, as well as certificate/signing information if the package archive had been signed by the author.

Add optional registry release information to `ResolvedPackage`

---

Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift

- `certificateChainPaths` is an empty array by default (can't be `nil`), so even though neither `privateKeyPath` nor `certificateChainPaths` is specified, thus signing is not needed, the tool fails with missing signing inputs error.
- Fix typo in error message

Fix registry package tool

---

Tests/PackageRegistryTests/RegistryClientTests.swift

Motivation:
Status `404` is not considered an error for "lookup identities" endpoint. As such, when the test generates a random error status in range of 400-500 and lands on `404`, the test doesn't get the error it expects.
Modification:
Change random status code range such that `404` can't be an option.
rdar://105519502

Fix flaky RegistryClientTests.testLookupIdentities_ServerError

---

Sources/Commands/PackageTools/Format.swift

hide the experimental `_format` package command
I want to clean up the CLI face of `swift package`, and the `_format` command stood out undocumented, likely experimental, and with no explanation. Based on the forum thread inquiring about `_format` and it's status, this PR hides the command from being displayed in `--help` and such.
Hides the _format command
`swift package` invocation no longer shows `_format` in the list of available commands.

hide the experimental _format command

---

Sources/PackageRegistry/RegistryClient.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

motivation: base64 emcoding is redundant in this case
changes:
* upload the archive in binary form instead of base64 encoded
* refactor the multi-part form construction logic

do not use base64 encoding when publishing archives

---

Sources/PackageRegistry/RegistryConfiguration.swift
Sources/Workspace/Workspace+Configuration.swift
Tests/PackageRegistryTests/RegistryConfigurationTests.swift

Implement new `security` configuration per registry publish proposal

Registry configuration - security

---

Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/SPMTestSupport/MockRegistry.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

- Update additional metadata to match newly proposed schema
- Update `PackageSearchClient` to use readmeURL from the latest version, if any

Add package release info API to registry client

---

Sources/Basics/Observability.swift
Sources/PackageDescription/BuildSettings.swift
Sources/PackageDescription/CMakeLists.txt
Sources/PackageDescription/LanguageStandardSettings.swift
Sources/PackageDescription/PackageDependency.swift
Sources/PackageDescription/PackageDescription.swift
Sources/PackageDescription/PackageDescriptionSerialization.swift
Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
Sources/PackageDescription/Product.swift
Sources/PackageDescription/Resource.swift
Sources/PackageDescription/SupportedPlatforms.swift
Sources/PackageDescription/Target.swift
Sources/PackageLoading/CMakeLists.txt
Sources/PackageLoading/ContextModel.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageDescriptionSerialization.swift

This will be a fairly large change to refactor the manifest serialization to achieve two goals: 
- get rid of the custom deserialization in `ManifestJSONParser` to use `Codable` throughout
- decouple the user-facing `PackageDescription` model from its serialization.
Tasks:
Both of these have to happen in a single PR because of a few glaring issues with making the PD model fully codable.
There is further work here which can happen in subsequent PRs:
- Relocate business logic from `ManifestJSONParser` into `PackageModel` as much as possible
- Evaluate the existence of `TargetDescription` etc - it feels like we should be able to get rid of one layer of model objects here, potentially
- Evaluate other serialization code in SwiftPM, e.g. for `package describe`, the `ManifestSourceGeneration` …

Refactor manifest serialization

---

Sources/Commands/PackageTools/DumpCommands.swift

Hides the `dump-pif` command from generated help on `swift package`
Clean up the UI/CLI experience.
Hides the `dump-pif` command from --help or the default response from `swift package` with no further subcommands.
`swift package` CLI is a bit cleaner

Hide `dump-pif` command.

---

Package.swift
Sources/PackageDescription/CMakeLists.txt
Sources/PackagePlugin/CMakeLists.txt

Enable library evolution for Linux builds of PackageDescription and PackagePlugin.
Since #3526 was merged, #5874 tried to apply the original idea of using `@_implementationOnly Foundation` in PackageDescription/Plugin to avoid leaking `Foundation` into the manifests.
Related to SR-14718 (#4416).
Reverts 19982848f86d3ce1621e35ac0d8a6ee3f9a9a0a5 / #3526
PackageDescription and PackagePlugin produce `.swiftinterface` files also in Linux, not just macOS.

Pass -enable-library-evolution for PackageDescription/Plugin in Linux

---

CHANGELOG.md
Documentation/Usage.md
IntegrationTests/Tests/IntegrationTests/BasicTests.swift
IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
Sources/Commands/PackageTools/Init.swift
Sources/Workspace/InitPackage.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/InitTests.swift

- Simplify the templates to include only the minimum necessary to get started without making assumptions.
- Use documentation links instead of arbitrary template content to teach people about Swift.
- Improve the "front door" experience with the help usage.
- Remove the `system-module` template.
- Remove the `manifest` template
- Add a `tool` template, an executable that uses `ArgumentParser`
- Remove README generation.
- Don't generate empty directories.
- Don't emit empty dependencies array in manifests.
- Update `library` template content:
- Remove struct definition, use a simple public function instead.
- Include documentation links for TSPL and the Standard Library.
- Include documentation links for XCTest in the generated test case.
- Update `executable` template content
- Use …

Init template cleanup

---

Sources/PackageDescription/PackageDependency.swift
Sources/PackageGraph/DependencyMirrors.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageModel/PackageIdentity.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/RegistryConfiguration.swift
Sources/PackageRegistry/RegistryDownloadsManager.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift
Sources/SPMTestSupport/MockDependency.swift
Sources/SPMTestSupport/MockRegistry.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: make code easier to reason about
changes:
* deprecate scopeAndName accessor in favour of .registry one
* define RegistryIdentity struct to encapsulate such identity
* update call sites and tests

NFC: cleanup usage of registry identifiers

---

CHANGELOG.md

The API is called `.embedInCode`.

Fix `.embedInCode` CHANGELOG record

---

CHANGELOG.md
Documentation/Usage.md
IntegrationTests/Tests/IntegrationTests/BasicTests.swift
IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
Sources/Commands/PackageTools/Init.swift
Sources/Workspace/InitPackage.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/InitTests.swift

Improve the `swift package init` experience using the following criteria:
- Simplify the templates to include only the minimum necessary to get started without making assumptions.
- Use documentation links instead of template content to teach people about Swift.
- Improve the "front door" experience with the help usage.
Detailed list of changes:
- Remove the `system-module` template.
- Remove the `manifest` template
- Add a new `tool` template, an executable that uses ArgumentParser a manifest instead.
- Remove README generation.
- Don't generate empty directories.
- Don't emit empty dependencies array in manifests.
- Update `library` template content:
- Remove struct definition, use a simple public function instead.
- Include documentation links for TSPL and the Standard Library.
- …

[5.8] Init template cleanup (#6144)

---

Sources/Workspace/InitPackage.swift

Update the path to the registries configuration file in the provided `.gitiginore` that is created when a new package is initialized via `swift package init`.
Running `swift package init` then `swift package-registry set ...` might cause the `registries.json` file to be checked into the repository since the ignored path is wrong.
Update the `swift package init` command to generate a file with the proper path to the `registries.json` file.
Changes in the generated .gitignore file.

Fix path to registries configuration file in gitignore

---

Package.swift
Sources/PackageSigning/SigningEntity/FilePackageSigningEntityStorage.swift
Sources/PackageSigning/SigningEntity/PackageSigningEntityStorage.swift
Sources/PackageSigning/SigningEntity/SigningEntity.swift
Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift

Motivation:
A signing entity is one that signs a package. Per the [proposal](https://github.com/apple/swift-evolution/pull/1925), SwiftPM can perform additional TOFU to ensure different versions of a package are signed by the same entity. `PackageSigningEntityStorage` will be used to store data for this purpose.

Add PackageSigningEntityStorage

---

Documentation/Registry.md

Motivation:
The example in section 4.6 might lead reader to think that certain parts of the request body must be base64-encoded.
Modifications:
- Make it clear that base64-encoding is not required. Client might sent binary and server should be able to handle it.
- Make it clear that `boundary` can be any random string and doesn't have to be `boundary`. Server should be able to handle any boundary string.
- Make `Content-Length` optional since it might not be set if request is streamed.

Update registry API spec: base64 encoding not required

---

Sources/PackageFingerprint/PackageFingerprintStorage.swift
Sources/PackageRegistry/CMakeLists.txt
Sources/PackageRegistry/ChecksumTOFU.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift

Motivation:
Checksum TOFU logic is scattered in `RegistryClient`, making it difficult to reason about and maintain.
Modifications:
Refactor checksum TOFU logic into `PackageVersionChecksumTOFU`.

Refactor registry checksum TOFU logic

---

Package.swift
Sources/Build/BuildOperation.swift
Sources/Commands/Utilities/SymbolGraphExtract.swift
Sources/CoreCommands/SwiftTool.swift
Sources/DriverSupport/CMakeLists.txt
Sources/DriverSupport/DriverSupportUtils.swift
Tests/CommandsTests/APIDiffTests.swift

Since this is querying a concrete compiler, it needs to receive the `Toolchain` object from the context in order to query the right one.

Fix `checkSupportedFrontendFlags`

---

Sources/PackageModel/Manifest/Manifest.swift
Sources/PackageModel/Manifest/PackageDependencyDescription.swift
Sources/PackageModel/PackageModel.swift
Sources/PackageModel/Platform.swift
Sources/PackageModel/SwiftLanguageVersion.swift
Sources/PackageModel/ToolsVersion.swift

This doesn't seem to be working well (anymore?), so we should get rid of it to avoid flakiness.
Long term we may want to move the `Version` type to `PackageModel` directly or possibly to `Basics`. We also have a duplicate of it in `PackageDescription`.

Remove re-export of `Version` from `PackageModel`

---

.swiftformat
Sources/CoreCommands/SwiftTool.swift
Sources/CrossCompilationDestinationsTool/ListDestinations.swift
Sources/PackageModel/BuildFlags.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/Toolset.swift
Sources/PackageModel/UserToolchain.swift
Sources/SPMBuildCore/DestinationsBundle.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageModelTests/DestinationTests.swift
Tests/PackageModelTests/PackageModelTests.swift
Tests/SPMBuildCoreTests/PluginInvocationTests.swift

This brings the implementation in line with changes proposed in https://github.com/apple/swift-evolution/pull/1942.

Implement `destination.json` schema v3.0

---

Sources/CrossCompilationDestinationsTool/InstallDestination.swift

Currently, `swift experimental-destination help` produces output that's split into multiple lines at a wrong column:
```
install                 Installs a given destination artifact bundle to a location discoverable by SwiftPM. If the
artifact bundle
is at a remote location, it's downloaded to local filesystem first.
```
By adding a backslash to the help multi-line string we leave the job of splitting this into multiple lines to the terminal renderer.

CrossCompilationDestinationsTool: fix `install` command help formatting

---

Sources/PackageModel/Toolset.swift
Tests/PackageModelTests/ToolsetTests.swift

Currently `DecodedToolset` only decodes `AbsolutePath` directly, while it should be able to support relative paths as well. Let's fix that by decoding to `String` first and then resolving to `AbsolutePath` when creating a `Toolset` value from `DecodedToolset`. Also added a corresponding test assertion that verifies that applied fix works.

PackageModel/Toolset: fix support for relative `rootPath`

---

Sources/Workspace/InitPackage.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/InitTests.swift

The recent changes to templates switched this template away from using `@main` which seems to not be compatible with Xcode's build system. The only non-`@main` way for executables that is supported is naming the primary source file "main.swift", so that is what this PR does.

Change executable template to use `main.swift`

---

Sources/CompilerPluginSupport/CMakeLists.txt
Sources/PackageDescription/CMakeLists.txt
Utilities/bootstrap

We were only doing these for macOS anyway where we throw away the produced content after the build, so there's no reason to do this.

Remove library evolution hacks from CMake build

---

Sources/Commands/Utilities/TestingSupport.swift

This change sets an environment variable before spawning swift-test if the calling process appears to support ANSI control codes in its output.
XCTest does not currently consume this information, but having it will allow for improvements to CLI output during testing.
This change sets an environment variable before spawning swift-test if the calling process appears to support ANSI control codes in its output. This environment variable is then propagated to swift-test/xctest.
With this change, the environment variable `XCTEST_COLOR_DIAGNOSTICS_ENABLED` should be set to `1` in test processes if the calling process (`swift`) supports ANSI control codes (i.e. is a TTY.)

`swift-test` cannot determine if output writes to a terminal (#6081)

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

This adds support for building macros as executables (see https://github.com/apple/swift-syntax/pull/1359).
Right now, this requires adding a package dependency on swift-syntax and corresponding product dependencies to the macro itself which makes testing difficult, so `BUILD_MACROS_AS_DYLIBS` is kept as the default mode.

Support macros as executables

---

Sources/CoreCommands/SwiftToolObservabilityHandler.swift
Sources/CrossCompilationDestinationsTool/InstallDestination.swift

This type uses `ParsableCommand`, not `AsyncParsableCommand`, while the `run` function itself was marked as `async`. Because of this the default implementation of `run` was always called, printing the help description even when correct arguments were passed. Removing the `async` effect from the function fixes the issue, since the function doesn't use `await` in its body anyway (due to unrelated reasons).
Also added quotes around URLs and paths in logging output so that it's easier to parse them visually, especially when those contain spaces.

Fix `InstallDestination.run` function not invoked by ArgumentParser

---

Sources/Workspace/InitPackage.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/InitTests.swift

The recent changes to templates switched this template away from using `@main` which seems to not be compatible with Xcode's build system. The only non-`@main` way for executables that is supported is naming the primary source file "main.swift", so that is what this PR does.
rdar://106044582
(cherry picked from commit 6fd2633da998331adeab25db4bf1df29fa11437d)

[5.8] Change executable template to use `main.swift`

---

Sources/PackageModel/Destination.swift
Sources/PackageModel/Toolset.swift
Tests/PackageModelTests/DestinationTests.swift

Previously, when parsing a destination file that referenced an invalid toolset, a decoding error for the toolset was propagated as a `StringError` that mentioned the destination file, which was quite confusing. It looked as if the destination file itself couldn't be parsed, which wasn't true. Cleaning up error handling here to explicitly mention the toolset file and its path if an error is thrown during its decoding.

PackageModel: fix error reporting for invalid toolsets

---

Utilities/bootstrap

This is currently missing from toolchains.

Install `CompilerPluginSupport` Swift module

---

Sources/DriverSupport/DriverSupportUtils.swift

While launching `swiftc` directly may work when compiling for the same platform where SwiftPM itself is running, cross-compiled builds may need to launch a different `swiftc`. Path to this executable can be easily looked up from the `Toolchain` instance passed to relevant functions.

DriverSupport: fix `swiftc` path in `DriverSupportUtils`

---

Sources/CrossCompilationDestinationsTool/CMakeLists.txt
Sources/CrossCompilationDestinationsTool/DestinationCommand.swift
Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Sources/CrossCompilationDestinationsTool/ListDestinations.swift
Sources/CrossCompilationDestinationsTool/RemoveDestination.swift
Sources/CrossCompilationDestinationsTool/SwiftDestinationTool.swift

Adds new `swift experimental-destination remove` subcommand per [the cross-compilation destinations proposal](https://github.com/apple/swift-evolution/blob/139e51f120b20e2d6aa9a61d44474ec698d9ec8c/proposals/0387-cross-compilation-destinations.md#destination-bundle-installation-and-configuration).

CrossCompilationDestinationsTool: add `remove` subcommand

---

Sources/Basics/SQLite.swift

Basics: fix comment typo in `SQLite.swift`

---

Sources/Basics/SQLite.swift

`SQLite` should be a reference type as it stores a pointer to the database. For some reason it was declared as `struct`, but to indicate its reference semantics it would be cleaner to mark it as `final class`. Additionally, this type should never be `Sendable` as it provides no locking, thus an explicit annotation should be added to indicate this.
Changed the `SQLite` type from `struct` to `final class`  and added a declaration that marks it as non-Sendable.
It's more obvious now that `SQLite` has reference semantics. In the future we could also call `close()` automatically from `SQLite.deinit`, but that needs a separate audit of existing calls to `close()`.

Basics: explicitly mark `SQLite` as non-Sendable reference type

---

Sources/PackageLoading/Platform.swift
Utilities/soundness.sh

The soundness script wasn't passing on `main` due to incorrect license header and files in `.build` having their license headers checked by this script. Also updated formatting in the file that had its license header changed, since the script also applies SwiftFormat on all changed files.

Fix license header, exclude `.build` in `soundness.sh`

---

Sources/CrossCompilationDestinationsTool/ListDestinations.swift

Currently when no CC destinations are installed, `swift experimental-destination list` produces no output, which is confusing. Let's fix that by providing a message that clarifies that no installed destinations are available.

CrossCompilationDestinationsTool: add diagnostics for no destinations

---

Sources/CoreCommands/SwiftTool.swift
Sources/CrossCompilationDestinationsTool/ListDestinations.swift
Sources/PackageModel/ArtifactsArchiveMetadata.swift
Sources/PackageModel/CMakeLists.txt
Sources/PackageModel/DestinationBundle.swift
Sources/PackageModel/DestinationsBundle.swift
Sources/SPMBuildCore/CMakeLists.txt
Tests/PackageModelTests/DestinationTests.swift
Tests/SPMBuildCoreTests/ArtifactsArchiveMetadataTests.swift

For the new `swift experimental-destination configure` subcommand we need to add configuration storage logic, which is tightly coupled to serialized destination data, which is internal to `PackageModel`. It would be beneficial to keep those serialized model types internal, but we also need to be able to access `ArtifactsArchiveMetadata` from the configuration logic.
Since that type seems to be purely a model value type related to packages, it feels reasonable to move it to `PackageModel`. Configuration logic provided in a future PR can then stay in `PackageModel` as well, without a need to expose internal model types, only providing configuration methods as `public`.
Also using this as an opportunity to rename `DestinationsBundle` to `DestinationBundle` for consistency with other model …

[NFC] Move ArtifactsArchiveMetadata to PackageModel

---

Sources/PackageModel/DestinationBundle.swift

We already use singular form everywhere, but somehow this method ended up having a different name, let's clean that up.

[NFC] PackageModel: rename `validateDestinationsBundle` for consistency

---

Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageModelTests/DestinationTests.swift
Tests/PackageModelTests/PackageModelTests.swift
Tests/SPMBuildCoreTests/PluginInvocationTests.swift

For `swift experimental-destination configure` subcommand we need to serialize destination configuration, which can be easily done by converting it to its v3 JSON schema.
Renamed `DecodedDestination` types to `SerializedDestination`, since for some of them we need to support encoding in addition to decoding. Added missing properties to `Destination` type, which now allows us to fully map all `SerializedDestinationV3` properties. Added `serialized` property on `Destination`, which allows serializing multiple destinations together in a future PR. Added new `configurationPathIsNotDirectory` to `enum DestinationError`, this new error will be used in a future PR when validating file system locations where configuration could be stored.
No functional change for the end user, but preparatory …

PackageModel: allow serializing `Destination` back to JSON

---

Package.swift
Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/ResolvedPackage.swift
Sources/PackageLoading/CMakeLists.txt
Sources/PackageLoading/RegistryReleaseMetadataSerialization.swift
Sources/PackageModel/RegistryReleaseMetadata.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/SPMTestSupport/PackageGraphTester.swift
Sources/SPMTestSupport/misc.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/PackageRegistryTests/SignatureValidationTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: clients of SwiftPM may be interested in the registry metadata for presentation
changes: serialize the metadata when downloading registry based  packages and deserializae it when construting the graph

serialize registry metadata and cache it so it can be exposed to clients

---

Package.swift
Sources/PackageModel/Manifest/Manifest.swift
Sources/SPMTestSupport/ManifestExtensions.swift
Sources/SPMTestSupport/MockWorkspace.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/ModuleAliasingBuildTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageModelTests/ManifestTests.swift
Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/XCBuildSupportTests/PIFBuilderTests.swift

motivation: safer code
changes:
* remove nil defaults from manfiest constructor
* update tests to use the test oriented helpers that set the defaults for testing

NFC: cleanup manifest constructor defaults

---

.swiftformat
Sources/Basics/SQLite.swift

Also removed `--varattributes prev-line` setting since it impacts `typealias` declaration that uses `@convention(c)`

[NFC] Basics: reformat `SQLite.swift`

---

Documentation/Plugins.md

- Fix a minuscule typo on documentation

Fix typo on `Plugins.md`

---

Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/XCBuildSupportTests/PIFTests.swift

PIF has headerVisibility for each BuildFile, however, we can't add headerVisibility in any way.
- Enable encoding and decoding of `headerVisibility`
- Add constructors to set `headerVisibility`
- Add tests for encode/decode

Add headerVisibility support on PIFBuilder

---

Package.swift

This will require the CI to update the installed tools to at least 5.7

Bump minimum required tools-version to 5.7

---

Sources/Basics/Triple.swift

Currently when a triple can't be parsed, the only error message the end user sees in the terminal is `Error: badFormat(triple: "ksjnfklsdn")`. This is quite confusing and unreadable.
Add conformance to `CustomStringConvertible` on `Triple.error`.
When a triple can't be parsed, the parsing error is surfaced to the end user in a human-readable form so that it's easier to address the error and find a root cause.

Basics: make `Triple` parsing errors human-readable

---

Sources/PackageMetadata/PackageMetadata.swift

This allows querying the registry for a known identity matching a given SCM URL and vice versa.

Expose identity lookup through `PackageSearchClient`

---

Sources/Basics/Concurrency/ConcurrencyHelpers.swift
Sources/Basics/Concurrency/SendableBox.swift
Sources/Basics/Concurrency/ThreadSafeArrayStore.swift
Sources/Basics/Concurrency/ThreadSafeBox.swift
Sources/Basics/Concurrency/ThreadSafeKeyValueStore.swift
Sources/Basics/Concurrency/TokenBucket.swift
Sources/Basics/FileSystem/AsyncFileSystem.swift
Sources/Basics/FileSystem/TemporaryFile.swift
Sources/Basics/HTTPClient/HTTPClient.swift
Sources/Basics/HTTPClient/HTTPClientConfiguration.swift
Sources/Basics/HTTPClient/HTTPClientRequest.swift
Sources/Basics/HTTPClient/HTTPClientResponse.swift
Sources/Basics/HTTPClient/URLSessionHTTPClient.swift
Sources/Basics/SQLite.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/SPMTestSupport/MockHashAlgorithm.swift
Tests/BasicsTests/FileSystem/AsyncFileSystemTests.swift
Tests/BasicsTests/FileSystem/TemporaryFileTests.swift
Tests/BasicsTests/FileSystem/VFSTests.swift
Tests/BasicsTests/HTTPClientTests.swift
Tests/BasicsTests/URLSessionHTTPClientTests.swift
Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
Tests/PackageSigningTests/SigningTests.swift

SwiftPM now requires 5.7 tools as a minimum, so we can drop any conditionals needed for building with older compilers.

Remove outdated compiler conditionals

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/PackageRegistryTool/PackageRegistryTool+Sign.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift
Sources/PackageSigning/SignatureProvider.swift
Sources/PackageSigning/SigningIdentity.swift
Sources/swift-package-registry/runner.swift

motivation: async-await does not work on our CI systems :(
changes:
* make all commands sync
* changes signing APIs to sync

remove the use of async/await in commands

---

Sources/Commands/PackageTools/Init.swift
Sources/Workspace/InitPackage.swift

Introduce `swift package init --type macro` to create a new package that defines a macro. It contains:
* A macro implementation target
* A library that provides the macro declaration for use by clients
* A "client" executable that imports the library and uses the macro
* A test target for debugging the macro implementation
Note that the test target runs into linking issues because the macro implementation target is an executable, not a library. I believe this is a known issue.
Tracked by rdar://106468626.

Add support for creating a macro package

---

Sources/Commands/ToolWorkspaceDelegate.swift
Sources/CoreCommands/SwiftTool.swift
Sources/CoreCommands/SwiftToolObservabilityHandler.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/SPMTestSupport/MockRegistry.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/SwiftToolTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/PackageRegistryTests/SignatureValidationTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: support the prompt configuration for handling unsigned or untrusted packages
changes:
* handle prompt request via swift-tool delegate
* add input API to swift-tool observability handler

prompt for unsigned or untrusted packages if needed

---

Tests/CommandsTests/PackageRegistryToolTests.swift
Tests/PackageSigningTests/SigningTests.swift

motivation: address warnings and restore tests that can now run due to not using concurrency
changes:
* remove redundant await in tests
* remove conditionals from tets that could not run in CI due to lack of concurrnecy and can now run

cleanup warnings and bring back tests

---

Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/PackageRegistry/SigningEntityTOFU.swift
Sources/PackageSigning/SigningEntity/FilePackageSigningEntityStorage.swift
Sources/PackageSigning/SigningEntity/PackageSigningEntityStorage.swift
Sources/SPMTestSupport/MockPackageSigningEntityStorage.swift
Tests/PackageRegistryTests/PackageSigningEntityTOFUTests.swift
Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift

- Storage now includes source entity origin (i.e., registry)
- Enhance storage data model to support more sophisticated use cases
- Add more details to `RegistryError.signingEntityForReleaseChanged` and `.signingEntityForPackageChanged`

Updates to PackageSigningEntityStorage and signing entity TOFU errors

---

Sources/CrossCompilationDestinationsTool/CMakeLists.txt
Sources/CrossCompilationDestinationsTool/Configuration/ConfigurationCommand.swift
Sources/CrossCompilationDestinationsTool/Configuration/ConfigureDestination.swift
Sources/CrossCompilationDestinationsTool/Configuration/ResetConfiguration.swift
Sources/CrossCompilationDestinationsTool/Configuration/SetConfiguration.swift
Sources/CrossCompilationDestinationsTool/Configuration/ShowConfiguration.swift
Sources/PackageModel/DestinationConfigurationStore.swift

To update destinations configuration we need a new subcommand to complement existing `configuration show` and `configuration reset` subcommands.
Added new `SetConfiguration` type with the implementation. Additionally, new `ConfigurationCommand` protocol was added that inherits from and extends `DestinationCommand` protocol to provide configuration-specific properties and arguments. This new protocol allows reusing common configuration code.
Also improved logging in `ResetConfiguration` to make it clear which properties were reset.
Users can run `swift experimental-destination configuration set` subcommand to customize properties of installed destinations.

Destinations: add `configuration set` subcommand

---

Sources/PackageGraph/PackageGraph+Loading.swift
Tests/PackageGraphTests/PackageGraphTests.swift

Like other diagnostics, the warning "dependency '\<name\>' is not used by any target" should be associated with a package (by specifying the package in its metadata). This allows it to show up in the right place in a package resolution log in IDEs that show such things.
- set the metadata on the diagnostics scope
- extend a unit test to check this metadata
rdar://106678793

The warning "dependency '<name>' is not used by any target" should have package metadata

---

Sources/Commands/SwiftTestTool.swift

motivation: restore funcitonality users came to rely on
changes: when --show-codecov-path is passed, print the path and exit like --show-bin-path

restore the ability to print codecov path without invoking tests first

---

Sources/PackageSigning/SigningEntity/FilePackageSigningEntityStorage.swift
Sources/PackageSigning/SigningEntity/PackageSigningEntityStorage.swift
Sources/PackageSigning/SigningEntity/SigningEntity.swift
Sources/SPMTestSupport/MockPackageSigningEntityStorage.swift
Tests/PackageRegistryTests/PackageSigningEntityTOFUTests.swift
Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift

Motivation:
Signing entity TOFU is really meant for identities we can "trust"--i.e., if they are recognized.
Modifications:
Strictly speaking writing only recognized identities to storage is business logic, so that logic was kept out of `PackageSigningEntityStorage` in previous implementation. However, with the added APIs for writing to storage, the best way to ensure only recognized identities get saved is having the check in the storage implementation.

Only write .recognized signing entity to storage

---

Sources/Basics/Triple.swift
Sources/CoreCommands/SwiftTool.swift
Sources/CrossCompilationDestinationsTool/DestinationCommand.swift
Sources/PackageModel/UserToolchain.swift
Sources/SPMBuildCore/BuildParameters.swift
Sources/swift-bootstrap/main.swift
Tests/BuildTests/MockBuildTestHelper.swift

motivation: avoid crashes, use structured error handling
changes:
* make Triple.getHostTriple throwable and remove use of fatalError
* update call sites
rdar://90317112

do not use fatalError in Triple.getHostTriple

---

Sources/CoreCommands/Options.swift

`configuraiton` -> `configuration`

CoreCommands: fix help string typo in `Options.swift`

---

Sources/Build/BuildOperation.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/SPMBuildCore/PluginScriptRunner.swift
Tests/CommandsTests/PackageToolTests.swift

motivation: surface any plugins compiler errors to users
changes:
* always print compiler output when failing to compile plugins
* restore testPluginCompilationBeforeBuilding test

print compiler output when precompiling plugins

---

Sources/Workspace/Workspace+Configuration.swift

Workspace: fix comment typo in `WorkspaceConfiguration`

---

Sources/Workspace/CMakeLists.txt

The target that was supposed to link against Foundation was Workspace. Because we changed a dependency, the transitive closure happened to make this work.

Workspace: fix `target_link_libraries`

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift
Sources/Workspace/Workspace+Configuration.swift
Tests/CommandsTests/SwiftToolTests.swift
Tests/WorkspaceTests/AuthorizationProviderTests.swift

Motivation:
When running `login` with `--netrc` and `--netrc-file` options and the custom netrc file doesn't exist, the command fails immediately with file not found error:
```
swift-package-registry --netrc --netrc-file ./netrc-test login
Error: Did not find netrc file at /Users/appleseed/netrc-test.
```
Which can be confusing.
Modifications:
Rearrange logic so that we initialize `AuthorizationProvider` first thing and display better error messages to user.
```
Error: credential store is invalid: did not find netrc file at /Users/appleseed/netrc-test
```

Improve error handling for 'package-registry login' command

---

Sources/PackageDescription/BuildSettings.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
Sources/PackageModel/ManifestSourceGeneration.swift
Tests/BuildTests/BuildPlanTests.swift

When importing C language dependencies, the Swift compiler internally runs Clang in C/Objective-C mode by default.
If some of the imported clang modules are actually written in C++, that causes build errors since C++ syntax might be invalid in C/Objective-C. To resolve that, Swift allows the user to explicitly enable C++/Objective-C++ language mode (along with the rest of the Swift/C++ interoperability logic) for clang via a compiler flag. The reason we cannot enable C++/Objective-C++ mode by default is because it changes the way some existing C/Objective-C APIs are imported: for instance, a library header might provide a different definition of a symbol under `#ifdef __cplusplus`.
The user should be able to enable Swift/C++ interoperability for a given Swift target without using unsafe …

Add build setting for enabling C++ interoperability

---

Sources/CrossCompilationDestinationsTool/ListDestinations.swift

This message is user-visible, so it shouldn't contain "info: " string prefix on each line that `emit(info:)` provides. Its initial use could've suggested that this is a debugging info message.

ListDestinations: use `print` instead of `emit(info:)` for output

---

Sources/CrossCompilationDestinationsTool/RemoveDestination.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/DestinationBundle.swift

Currently only removing by bundle name is allowed, but this is confusing since `swift experimental-destination list` doesn't provide bundle names, only destination/artifact IDs. Let's allow removing bundles by providing destination IDs. An appropriate check is done if multiple artifacts are available in a bundle.
Added new logic to `RemoveDestination.swift`, renamed its `bundleName` property to `destinationIDOrBundleName`. Also modified `DestinationBundle.swift` to provide destination name when needed.
Users can now pass artifact ID from `swift experimental-destination list` to `swift experimental-destination remove`.

Destinations: allow removing by artifact ID

---

Sources/PackageModel/ArtifactsArchiveMetadata.swift
Sources/PackageModel/DestinationBundle.swift
Sources/SPMBuildCore/BinaryTarget+Extensions.swift
Sources/SPMTestSupport/misc.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: type safety
changes:
* artifact bundle path is suppose to be relative, use the right type for that
* add extensions for test to use strings as realtive path via ExpressibleByStringLiteral
* update call sites

use relative path in artifact bundles

---

Sources/PackageSigning/SigningEntity/SigningEntity.swift
Tests/PackageRegistryTests/PackageSigningEntityTOFUTests.swift
Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift
Tests/PackageSigningTests/SigningEntityTests.swift

Two ADP signers are equal as long as their team ID (org unit) matches.

Update equality check for SigningEntity

---

Sources/PackageSigning/SigningEntity/SigningEntity.swift

Motivation:
It's strange for a recognized signing entity to have unknown names.
Modification:
Make all properties of recognized signing entity required

Make properties of SigningEntity.recognized required

---

Sources/PackageRegistry/RegistryClient.swift

Add missing boundary to the `metadata-signature` and the `source-archive-signature` parts in the request sent when publishing a package.

Add missing boundary when uploading signatures

---

Sources/PackageRegistry/SignatureValidation.swift
Sources/PackageSigning/SignatureProvider.swift
Sources/PackageSigning/VerifierPolicies.swift
Tests/PackageSigningTests/SigningTests.swift

- OCSP check is done through HTTP requests, add caching to reduce network calls.
- OCSP responder might not be able to provide revocation checking beyond certificate expiration, so check that leaf certificate has not expired before making OCSP requests.

Add caching to OCSP verifier and perform expiry check

---

Sources/LLBuildManifest/CMakeLists.txt

Clean up some bleeding whitespace.

LLBuildManifest: clean up bleeding whitespace (NFC)

---

Sources/Build/CMakeLists.txt
Sources/LLBuildManifest/CMakeLists.txt
Sources/PackageFingerprint/CMakeLists.txt
Sources/PackageGraph/CMakeLists.txt
Sources/PackageLoading/CMakeLists.txt
Sources/PackageRegistry/CMakeLists.txt
Sources/SPMLLBuild/CMakeLists.txt
Sources/SourceControl/CMakeLists.txt

Reduce the overall exported set of libraries.  These are internal to SPM and do not need to be exposed to consumers.

build: stop exporting a couple of targets

---

Sources/Workspace/InitPackage.swift

In the generated `stringify` macro declaration, use triple-slash documentation comments rather than double-slash comments, so we get better documentation.

[Macro package init] Use triple-slash documentation comments

---

Sources/PackageModel/PackageIdentity.swift
Sources/PackageModel/Registry.swift
Sources/PackageRegistry/RegistryClient.swift

This allows capturing `PackageVersionMetadata` in `@Sendable` closures. We still have a couple of warnings related to such closures, but this change is a first step towards resolving those in the future. Also marked `RegistryIdentity` as `Sendable` for the same reason.

PackageRegistry: mark PackageVersionMetadata Sendable

---

CHANGELOG.md
Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift
Sources/Workspace/DefaultPluginScriptRunner.swift
Tests/FunctionalTests/PluginTests.swift

Allow customizing the compilation of plugins by passing `-Xbuild-tools-swiftc` parameters to the `swift build` invocation, the same that customizing the compilation of the manifest was possible with `-Xmanifest` parameters.
For most cases, compiling against the host toolchain does not need extra arguments, but in some complicated setups, the host toolchain might need extra arguments for search paths and such. In the case of the manifest, the option of using `-Xmanifest` arguments to customize the manifest compilation has existed for a while, but in the case of plugins, the same option was not available and made consuming packages with plugins very complicated.
The changes in this commit modify the former `-Xmanifest` to understand an alias `-Xbuild-tools-swiftc` and apply the provided …

Allow passing extra arguments to plugin compilation

---

Sources/PackageGraph/PackageGraph+Loading.swift

Instead we need to raise an error if we end up in that situation.
rdar://106432785

Do not crash on duplicated product names

---

Sources/CoreCommands/Options.swift
Sources/Workspace/Workspace.swift

motivation: swizzling behavior may come surprising, make it the user decision
changes: disable swizzling by default

do not scm->registry swizzle by default

---

Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/Workspace/Workspace.swift

This will allow clients to take the information from specific registry error cases and programmatically accept them as valid. This can be useful if a client wants to offer a way for users to accept an allowed identity change.

Allow clients to programmatically accept an identity change

---

Tests/CommandsTests/PackageRegistryToolTests.swift

changes: skip a couple of new tests that are sensitive to env where we cannot change the working directory

skip a couple of tests when running in an environment that does not support changing the working directory

---

CHANGELOG.md
Sources/PackageLoading/Diagnostics.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest/Manifest.swift
Sources/Workspace/InitPackage.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

After getting some feedback about the added `path` argument for executable packages generated with `swift package init` (#6144), this change allows a target's sources to occupy the entire sources directory when there is only one target in the package. All package types can benefit from this.
When there is more than one target in a package, the existing requirements for target sources still apply.
This change should be compatible with existing layouts as well. If there is only a single target in a package, then sources can of course continue to exist in `./Sources/<target>`.
Amend the `executable` template's generated manifest to not include the `path` argument anymore.
rdar://106829666

Allow sources anywhere in ./Sources when only one target is present

---

Package.swift
Sources/Basics/SwiftVersion.swift

- Use aligned branches for dependencies
- Switch to "release mode" so that 999.0 tools-version becomes not usable

[5.9] Post branch adjustments for 5.9

---

Sources/Workspace/Workspace.swift
Tests/SPMBuildCoreTests/PluginInvocationTests.swift

The Workspace type has a facility for scanning package plugins for imports.  But since it's not passing in the actual plugin directory provided by the caller (whether it's SwiftPM or Xcode), any modules provided by an IDE aren't picked up if they are guarded by `#if canImport()`.  This includes `XcodeProjectPlugin`, which is one of the additional plugin modules provided by Xcode.  The same would be true for other IDEs.
Changes:
- `Workspace.loadPluginImports` now also passes the path of the plugin directory to the import scanning
- extended the `testScanImportsInPluginTargets` unit test to check for this case
rdar://106387043

Plugin import scanner isn't passing in the library directory, making `canImport` not work

---

Sources/CrossCompilationDestinationsTool/RemoveDestination.swift

The `experimental-destination remove` subcommand has two conditions: removing by bundle name or artifact ID. Previously, on successful removal a message was printed only in one of the conditions, which was wrong.
When removing a bundle by artifact ID absence of a printed message is confusing to the user and makes it unclear whether the command invocation had any effect.
rdar://107138636

Destinations: fix missing `remove` command message

---

Sources/Basics/SwiftVersion.swift

It seems like we were a little too quick with this. We do want users to be able to try out macros with the 5.9 toolchain, but they are still a pre-release feature.

[5.9] Turn development mode back on

---

Sources/Workspace/Workspace.swift
Tests/SPMBuildCoreTests/PluginInvocationTests.swift

This is a 5.9 nomination of https://github.com/apple/swift-package-manager/pull/6323.

[5.9] Plugin import scanner isn't passing in the library directory (#6323)

---

Sources/Basics/FileSystem/TemporaryFile.swift
Sources/Basics/FileSystem/VirtualFileSystem.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SourceControl/GitRepository.swift
Tests/BasicsTests/URLSessionHTTPClientTests.swift

None of these types store internal mutable state, so this should be safe. This resolves some of the sendability warnings that we currently have.

Mark types conforming to `FileSystem` as `Sendable`

---

CHANGELOG.md
Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift
Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift
Fixtures/Resources/EmbedInCodeSimple/Package.swift
Sources/PackageDescription/Resource.swift
Sources/PackageModel/PackageModel.swift

- `embedInCode` should be marked as part of 5.9
- `-package-name` hasn't been accepted by evolution, yet, so should be using `vNext`
- support for macros also stays intentionally behind 999.0 tools-version since it hasn't been accepted by evolution yet
- Update `CHANGELOG`

Rearrangement in preparation for 5.9 branching

---

Sources/Basics/Observability.swift
Sources/Build/BuildOperation.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/Workspace/Workspace.swift

Since uses of `DiagnosticsEngine` are deprecated in SwiftPM, with https://github.com/apple/swift-driver/pull/1317 we can remove any traces of it from `Basics/Observability.swift` to clean that up. 
Removed unused deprecated function that returned an instance of `DiagnosticsEngine`. Also broke up `import TSCBasic` into separate type imports to make clear what dependencies on TSC are there remaining.
`TSCBasic.Diagnostic` still remains, but I think long-term we can move that to Swift Driver codebase to reduce dependencies on TSC.

Basics: clean up `DiagnosticsEngine` in `Observability`

---

CHANGELOG.md
Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift
Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift
Fixtures/Resources/EmbedInCodeSimple/Package.swift
Sources/PackageDescription/Resource.swift
Sources/PackageModel/PackageModel.swift

- `embedInCode` should be marked as part of 5.9
- `-package-name` hasn't been accepted by evolution, yet, so should be using `vNext`
- support for macros also stays intentionally behind 999.0 tools-version since it hasn't been accepted by evolution yet
- Update `CHANGELOG`
(cherry picked from commit aa6f358ecb587bb6c7cb58891be322ac8dc14d06)

[5.9] Rearrangement in preparation for 5.9 branching

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/PackageModel/Target.swift

Opt macros into testable executables if we're building them as executables.
(cherry picked from commit e02a8b5323dd096d4a4749c3ce3602690f0958f3)

[5.9] rdar://105991217 (Make macros testable)

---

Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/SPMTestSupport/ManifestExtensions.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: with the intriduction of the regsitry, there is a higher likelyhood of running into duplicate packages
changes: perform a heuristics to try and determine if the packages are duplicate and provide a better diagnostics instead of the standard "duplicate target" one

better diagnostics when potentially duplicate packages are found

---

Sources/PackageLoading/ManifestSignatureParser.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/SignatureValidation.swift
Tests/PackageRegistryTests/SignatureValidationTests.swift

Motivation:
Manifest signature validation works similarly as source archive signature validation, meaning user could see duplicate errors (e.g., source archive not signed).
Modifications:
- Change most error throwing to logging diagnostics for manifest signature validation
- Continue to prompt if that's what user has configured for unsigned packages or untrusted signers; cache responses in memory to prevent repeatedly prompting for manifest and source archive downloads for the same package version.
- Wire up publisher TOFU for manifest signing
- Adjust tests

Reduce errors from manifest signature validation

---

Sources/PackageGraph/PackageGraph+Loading.swift

Motivation:
```
Sources/PackageGraph/PackageGraph+Loading.swift:535:16: error: type 'Pair' does not conform to protocol 'Equatable'
struct Pair: Hashable {
```
Modification:
Move `Pair` out of `createResolvedPackages` method and it seems happy.

Fix compilation error in Swift 5.7.2

---

Sources/Commands/PackageTools/Config.swift
Sources/PackageGraph/DependencyMirrors.swift
Sources/PackageGraph/PinsStore.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/MirrorsConfigurationTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: the mirrors config command no takes both URLs and registry identities
changes:
* nupdate flags to use "original" and "mirror" so it is not URL specific
* update API to not use URL suffix
* update call sites and tests

cleanup mirror config command

---

Sources/PackageGraph/PackageGraph+Loading.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6341 to 5.9

[5.9] Fix compilation error in Swift 5.7.2

---

Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/DestinationBundle.swift
Sources/PackageModel/DestinationConfigurationStore.swift
Tests/PackageModelTests/DestinationBundleTests.swift

`swift experimental-destination install` command doesn't check if a newly installed bundle contains same IDs as already installed bundles.
Moved installation code from `InstallDestination.swift` to separate static functions on `DestinationBundle` to make it testable. Also added tests that exercise these code paths and verify that installation is successful or throws correct errors when needed.
rdar://106090132

Destinations: throw error on duplicate artifact ID

---

Sources/PackageLoading/ManifestSignatureParser.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/SignatureValidation.swift
Tests/PackageRegistryTests/SignatureValidationTests.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6325 to 5.9
Motivation:
Manifest signature validation works similarly as source archive signature validation, meaning user could see duplicate errors (e.g., source archive not signed).
Modifications:
- Change most error throwing to logging diagnostics for manifest signature validation
- Continue to prompt if that's what user has configured for unsigned packages or untrusted signers; cache responses in memory to prevent repeatedly prompting for manifest and source archive downloads for the same package version.
- Wire up publisher TOFU for manifest signing
- Adjust tests

[5.9] Reduce errors from manifest signature validation (#6325)

---

Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
Sources/PackageFingerprint/Model.swift
Sources/PackageFingerprint/PackageFingerprintStorage.swift
Sources/PackageRegistry/ChecksumTOFU.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/RegistryDownloadsManager.swift
Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
Sources/SPMTestSupport/MockRegistry.swift
Sources/Workspace/SourceControlPackageContainer.swift
Sources/Workspace/Workspace.swift
Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Motivation:
Currently fingerprints are for source archive (checksum from registry) and source repo (git hash from SCM) only. Additional content types need to be supported if SwiftPM were to do TOFU for manifest files too.
Modifications:
- Modify fingerprint storage structure to store fingerprint by content type
- Modfiy fingerprint storage API to allow retrieving fingerprints by content type

Package manifest checksum TOFU

---

Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/DestinationBundle.swift
Sources/PackageModel/DestinationConfigurationStore.swift
Tests/PackageModelTests/DestinationBundleTests.swift

`swift experimental-destination install` command doesn't check if a newly installed bundle contains same IDs as already installed bundles.
Moved installation code from `InstallDestination.swift` to separate static functions on `DestinationBundle` to make it testable. Also added tests that exercise these code paths and verify that installation is successful or throws correct errors when needed.
rdar://106090132

[5.9] Destinations: throw error on duplicate artifact ID

---

Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
Sources/PackageFingerprint/Model.swift
Sources/PackageFingerprint/PackageFingerprintStorage.swift
Sources/PackageRegistry/ChecksumTOFU.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/RegistryDownloadsManager.swift
Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
Sources/SPMTestSupport/MockRegistry.swift
Sources/Workspace/SourceControlPackageContainer.swift
Sources/Workspace/Workspace.swift
Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6322 to 5.9
---
Motivation:
SwiftPM should do checksum TOFU for package manifests.
Modifications:
- Modify fingerprint storage structure to store fingerprint by content type
- Modfiy fingerprint storage API to allow retrieving fingerprints by content type
- Add API to `ChecksumTOFU` for manifests
- Wire up manifest TOFU in `RegistryClient`

[5.9] Package manifest checksum TOFU

---

CHANGELOG.md
Sources/Commands/PackageTools/Init.swift
Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift

Adds command plugin and build tool plugin templates to `swift package init`.
rdar://107288352

Add templates for build tool plugins and command plugins

---

Sources/PackageLoading/PackageBuilder.swift

We currently cannot use `..` as a header search path for Windows even though it may be contained within the package root.  This is due to the fact that the path itself was unanchored, and a raw `..` would be treated as the drive root which will almost always be outside of the package root.  Construct the absolute path relative to the target root rather than appending, permitting us to form a well-formed path which can be checked for ancestry.

PackageLoading: anchor relative paths for Windows

---

CHANGELOG.md
Sources/Commands/PackageTools/Init.swift
Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift

This is a cherry-pick of #6111 for nomination to 5.9.
rdar://107288352
Co-authored-by: Anders Bertelrud <anders@apple.com>
(cherry picked from commit f25e1381d288176cd71a91324f7988253456a7f0)

[5.9] Add templates for build tool plugins and command plugins (#6111)

---

Sources/Workspace/Workspace.swift

motivation: avoid crashes
changes: throw and internal error instead of pre-condition when validation fails
rdar://98522178

change validation to throw instead of pre-condition to avoid crashes

---

Sources/PackageLoading/PackageBuilder.swift

Non-throwing `init` of `AbsolutePath` is deprecated, let's not use it.

Fix deprecation warning in `PackageBuilder.swift`

---

Tests/CommandsTests/SwiftToolTests.swift

We can just write those files into /tmp

Do not pollute home directory with test data

---

Sources/Basics/Archiver+Zip.swift

`to used by` -> `to be used by`

NFC: fix comment typo in `ZipArchiver`

---

Sources/PackageModel/RegistryReleaseMetadata.swift
Sources/SPMTestSupport/MockPackage.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This allows clients to pass in a dictionary with expected signing entities that SwiftPM will check after loading the package graph. This can be used by clients to provide a priori configuration of expected signing by the user or provide a way to verify that information that was previously shown to users matches what was verified during signature verification.
Note that since this operates at the workspace level, we're verifying against the data cached during signature verification, not against the actual data.
rdar://107162424
(cherry picked from commit a6fde25cb63ddd50e410691d33723ed51db5def9)

[5.9] Expected signing entity verification

---

Documentation/Registry.md

https://github.com/apple/swift-evolution/blob/main/proposals/0391-package-registry-publish.md

Update registry service spec per SE-0391

---

Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/PackageSigning/SignatureProvider.swift
Sources/PackageSigning/SigningEntity/SigningEntity.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

Clients who are asking for metadata prior to download an archive from the registry may still want to display information from the signature which is non-trivial to extract. This includes it if possible.

Include signing entity in version metadata

---

Sources/PackageMetadata/PackageMetadata.swift

This exposes all of the version-specific metadata, not just the readme URL. For convenience, this is still flattened and only the metadata for the latest version is available, but I have also added a `latestVersion` property if we are taking metadata from a specific version to indicate where it is from.

rdar://107033737 (Expose `PackageVersionMetadata` from `PackageSearchClient`)

---

Sources/Build/BuildOperation.swift

[NFC] BuildOperation.swift: fix comment typo

---

Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/BuildFlags.swift

When computing `SwiftTool/_buildParameters`, command-line options that customize `BuildFlags` values are not merged with `BuildFlags` from the computed toolchain/destination.
rdar://106077959
Added `mutating func append(_: BuildFlags)` on the `BuildFlags` type for easier merging of multiple values into one, which is then used in `SwiftTool/_buildParameters`.

PackageModel, CoreCommands: fix build flags not passed

---

Fixtures/Miscellaneous/TargetGrouping/libPkg/Package.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/Core/Core.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/DataManager/File.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/DataModel/File.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/ExampleApp/main.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/MainLib/Lib.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Tests/BlackBoxTests/BlackBoxTests.swift
Fixtures/Miscellaneous/TargetGrouping/libPkg/Tests/MainLibTests/MainLibTests.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/CompilerPluginSupport/TargetExtensions.swift
Sources/PackageDescription/PackageDescriptionSerialization.swift
Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
Sources/PackageDescription/Target.swift
Sources/PackageGraph/ResolvedProduct.swift
Sources/PackageGraph/ResolvedTarget.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest/TargetDescription.swift
Sources/PackageModel/Target.swift
Sources/SPMTestSupport/MockTarget.swift
Sources/Workspace/Workspace.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageGraphTests/TargetTests.swift
Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift

Support Target Grouping
- Allow opting out of package boundary
- Default set to package boundary
Resolves rdar://107454728

[5.9] Support Target Grouping

---

Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/BuildFlags.swift

When computing `SwiftTool/_buildParameters`, command-line options that customize `BuildFlags` values are not merged with `BuildFlags` from the computed toolchain/destination.
rdar://106077959
Added `mutating func append(_: BuildFlags)` on the `BuildFlags` type for easier merging of multiple values into one, which is then used in `SwiftTool/_buildParameters`.

[5.9] PackageModel, CoreCommands: fix build flags not passed

---

Sources/PackageGraph/PackageGraph+Loading.swift
Tests/PackageGraphTests/PackageGraphTests.swift

For module aliasing, we changed the product lookup to include package identity, but product references can use a local identity as specified by the `name` attribute of the package dependency declaration. So for packages where the local `name` attribute didn't match the identity, we would not longer find the corresponding products at all. This switches us back to use the local identity that is also called `explicitNameForTargetDependencyResolutionOnly` in package reference.
rdar://106578471

Fix product lookup

---

Documentation/PackageRegistryUsage.md

Documentation on registry usage

---

Sources/CompilerPluginSupport/TargetExtensions.swift

Set a default value to the group param for a macro target to un-break macro packages per https://github.com/apple/swift-package-manager/pull/6365

[5.9] Set a default value to the group param for a macro target

---

Sources/CompilerPluginSupport/TargetExtensions.swift

Set a default value to the group param for a macro target to un-break macro packages per https://github.com/apple/swift-package-manager/pull/6365

     Set a default value to the group param for a macro target

---

Sources/CrossCompilationDestinationsTool/DestinationCommand.swift
Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Sources/CrossCompilationDestinationsTool/SwiftDestinationTool.swift
Sources/PackageModel/DestinationBundle.swift
Sources/swift-experimental-destination/SwiftDestinationTool.swift
Sources/swift-package-manager/SwiftPM.swift

`swift experimental-destination` subcommands no longer work and always display help output. This is a regression introduced in https://github.com/apple/swift-package-manager/pull/6362 after making `SwiftDestinationTool` conform to  `AsyncParsableCommand` instead of `ParsableCommand` but not updating `swift-package-manager` command sources to call `async` overload of `main()` function on `SwiftDestinationTool`.
rdar://107618266

Fix symlinked `swift-experimental-destination` invocations

---

Sources/CrossCompilationDestinationsTool/DestinationCommand.swift
Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Sources/CrossCompilationDestinationsTool/SwiftDestinationTool.swift
Sources/PackageModel/DestinationBundle.swift
Sources/swift-experimental-destination/SwiftDestinationTool.swift
Sources/swift-package-manager/SwiftPM.swift

`swift experimental-destination` subcommands no longer work and always display help output. This is a regression introduced in https://github.com/apple/swift-package-manager/pull/6362 after making `SwiftDestinationTool` conform to  `AsyncParsableCommand` instead of `ParsableCommand` but not updating `swift-package-manager` command sources to call `async` overload of `main()` function on `SwiftDestinationTool`.
rdar://107618266

[5.9] Fix symlinked `swift-experimental-destination` invocations

---

IntegrationTests/Tests/IntegrationTests/Helpers.swift
Sources/SPMTestSupport/misc.swift

Rather than relying on UNIX semantics of `cp` which is inherently
platform dependent.  This is required to start experimenting with
getting the SPM test suite running on Windows.

Tests: use `FileManager` instead of `cp`

---

Sources/PackageSigning/SigningEntity/SigningEntity.swift

This fixes a warning currently triggered when building the `PackageSigning` target:
```
PackageSigning/SigningEntity/SigningEntity.swift:19:10: warning: associated value 'recognized(type:name:organizationalUnit:organization:)' of 'Sendable'-conforming enum 'SigningEntity' has non-sendable type 'SigningEntityType'
case recognized(type: SigningEntityType, name: String, organizationalUnit: String, organization: String)
^
PackageSigning/SigningEntity/SigningEntity.swift:79:13: note: consider making enum 'SigningEntityType' conform to the 'Sendable' protocol
public enum SigningEntityType: String, Hashable, Codable {
^
, Sendable
```

PackageSigning: mark `SigningEntityType` as `Sendable`

---

Sources/Basics/Archiver/UniversalArchiver.swift

This was marked as a mutable property by mistake when implementing `Archiver` protocol conformance. This property is assigned an initial value in `UniversalArchiver/init` and isn't supposed to be ever changed for a given archiver.

Basics: make `supportedExtensions` in `UniversalArchiver` constant

---

Tests/PackageModelTests/DestinationBundleTests.swift

These tests currently have `await` before non-`async` functions. Let's clean that up to fix the warning:
```
No 'async' operations occur within 'await' expression
```

PackageModelTests: fix warnings in `DestinationBundleTests`

---

Sources/Workspace/Workspace.swift

motivation: url lookup results should be consistent
changes: sort identities before picking the one to use

sort identities from url lookup to make lookup result consistent

---

Sources/Basics/Cancellator.swift
Sources/CoreCommands/SwiftTool.swift
Tests/CommandsTests/SwiftToolTests.swift

These signal handlers are useful to other tools that don't have access to `SwiftTool`. For example, `DestinationCommand` would benefit from this as it needs to set up its own cancellator for handling archiver processes.
Moved signal handler setup to a new `installSignalHandlers` function on `Cancellator`. Made captures of `Cancellator` in handler closures weak so that it's not referenced indefinitely and is released when no longer needed.
`Cancellator/installSignalHandler` can be used in more places.

Basics: allow reusing cancellator handlers from `SwiftTool`

---

Package.swift

Aliasing `main` is not supported on Windows in SPM as of yet.  This adjusts the build rules to allow building the test suite on Windows in light of that.  While the tests do not yet pass, this allows the package to be built for the remaining tests.

Package: adjust the package definition for Windows

---

Tests/PackageLoadingTests/PD_Next_LoadingTests.swift

This should avoid regressions like the one introduced by #6356

Add a minimal test for the PD macro API

---

Package.swift
Utilities/bootstrap

As long as I'm modifying the Python bootstrap script, clean up some incorrect checks of the host `platform.system()` and replace some unnecessary regexes.
It has always bothered me that since [I suggested this hack of adding this second runpath for the Package libraries a couple years ago](https://github.com/apple/swift-package-manager/pull/3431#issuecomment-835477223), all installed ELF binaries incorrectly have both runpaths:
```
> readelf -d swift-DEVELOPMENT-SNAPSHOT-2023-03-17-a-ubuntu20.04/usr/lib/swift/pm/*I/lib*so swift-DEVELOPMENT-SNAPSHOT-2023-03-17-a-ubuntu20.04/usr/bin/swift-package|ag "File:|runpath"
File: swift-DEVELOPMENT-SNAPSHOT-2023-03-17-a-ubuntu20.04/usr/lib/swift/pm/ManifestAPI/libPackageDescription.so
0x000000000000001d (RUNPATH)            Library runpath: …
```

On ELF platforms, only add runpaths as needed

---

Sources/PackageGraph/PackageGraph+Loading.swift
Tests/PackageGraphTests/PackageGraphTests.swift

For module aliasing, we changed the product lookup to include package identity, but product references can use a local identity as specified by the `name` attribute of the package dependency declaration. So for packages where the local `name` attribute didn't match the identity, we would not longer find the corresponding products at all. This switches us back to use the local identity that is also called `explicitNameForTargetDependencyResolutionOnly` in package reference.
rdar://106578471
(cherry picked from commit afcd86a76b62b382f8ed98ec87b7ce5a67884b19)

[5.9] Fix product lookup

---

Sources/PackageModel/ManifestSourceGeneration.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift

The manifest source generation uses the wrong spelling for this enum.  AFAIK there haven't been any reports of this affecting anyone yet — this was found during code inspection while making another change.  The incorrect spelling is for both the platform version declaration and the spelling in the condition.
This change also adds a unit test to check the latest versions of each of the platforms, and another one to check all the supported platform conditions.
rdar://107795051

ManifestSourceGeneration incorrectly writes out `DriverKit` instead of `driverKit`

---

Sources/PackageModel/ManifestSourceGeneration.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift

This is a SwiftPM 5.9 nomination of #6405.
rdar://107795051
(cherry picked from commit 5d83b595f9650c2f477fe757907d80265df6ad33)

[5.9] ManifestSourceGeneration incorrectly writes out `DriverKit` instead of `driverKit` (#6405)

---

Sources/PackageCollections/Model/PackageTypes.swift
Sources/PackageCollections/PackageCollections.swift
Sources/PackageCollections/PackageIndex.swift
Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Sources/PackageCollections/Providers/PackageMetadataProvider.swift
Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
Tests/PackageCollectionsTests/Utility.swift

Motivation:
Package collection should have information about how a version was created. This includes the creator and timestamp.
- "Who created the package version?": added in this PR
- "When was the version created?": this is version's `createdAt`, which already exists.
rdar://106674475
Modifications:
Extract `author` from GitHub API's release data and make it available through package collection's `Package` model.

Add author to collection package release metadata

---

Documentation/Registry.md
Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/SPMTestSupport/MockRegistry.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Motivation:
Registry should have information about how a package was published. This includes who published it, who signed it, and when it was published.
- "Who published the package release?": this is `metadata.author`, which is already defined in the metadata JSON schema.
- "Who signed the package release?": this can be extracted from the signing certificate if signed (requires rdar://107483043 and will be done in separate PR)
- "When was the release published?": added in this PR
rdar://106674475
Modifications:
- Add `originalPublicationTime` to user-provided metadata during publication
- Add `publishedAt` to registry's package release metadata response
- Update registry API spec

Add publication time to registry package release metadata

---

Sources/Basics/Archiver/UniversalArchiver.swift
Sources/Basics/FileSystem/Path+Extensions.swift
Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Sources/PackageModel/DestinationBundle.swift

Fixes `.tar.gz` archives support in `experimental-destination install` subcommand.
Tweaks multi-component extensions calculation so that at most last 2 components are taken into consideration. This fixes an issue with bundle names that have dots. For example, for `5.7.3-RELEASE_ubuntu_22.04_aarch64.tar.gz` previously `allExtensions` returned `7.3-RELEASE_ubuntu_22.04_aarch64.tar.gz`, and that didn't match any of the archivers, even though the actual extension was valid.
rdar://107485048

Destinations: use `UniversalArchiver` in `install` command

---

Sources/Workspace/InitPackage.swift

- Use 4 spaces instead of 2 to be consistent with the other templates
- Use `BasicMacroExpansionContext(` instead of `BasicMacroExpansionContext.init`
- Add two newlines in the test method to improve readability
- Depend on the latest 509.0.0 prerelease of SwiftSyntax instead of `main`.

Improve Swift Macro template

---

Documentation/Registry.md
Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/SPMTestSupport/MockRegistry.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6407 to 5.9

[5.9] Add publication time to registry package release metadata

---

Package.swift
Utilities/bootstrap

Cherrypick of #6321
__Explanation:__ The bootstrap script currently adds two relative runpaths for ELF platforms, one for the PackageDescription and other libraries and another for the single `swift-package` executable, but since they're applied on the command line, both runpaths are applied to all binaries. This pull separates out the runpaths and only applies each where needed. It also shifts much of the bootstrap script over to applying build flags based on the build target, not on checking the build host platform in Python.
__Scope:__ Should only affect the SPM build on ELF platforms like linux
__Risk:__ low, as it only affects building SPM for ELF platforms
__Testing:__ Passed all CI, including a trunk toolchain build that worked well
__Reviewer:__ @neonichu

[5.9] On ELF platforms, only add runpaths as needed (#6321)

---

Fixtures/Collections/JSON/good.json
Fixtures/Collections/JSON/good_signed.json
Package.swift
Sources/PackageCollections/Model/PackageTypes.swift
Sources/PackageCollections/PackageCollections.swift
Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Sources/PackageCollectionsModel/Formats/v1.md
Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
Sources/PackageMetadata/PackageMetadata.swift
Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift
Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift
Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
Tests/PackageCollectionsTests/Utility.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6415 to 5.9

[5.9] Add author and signer to package collection models

---

Sources/Basics/Cancellator.swift

Looks like there's an iOS angle to the issue in #6414 as well which I hadn't noticed because I was accidentally building for macOS instead.

Fix iOS buid

---

Sources/Basics/Cancellator.swift

Looks like there's an iOS angle to the issue in #6414 as well which I hadn't noticed because I was accidentally building for macOS instead.
(cherry picked from commit 970f7929303cd491b8f1704e23b02ab15091c55a)

[5.9] Fix iOS buid

---

Package.swift
Sources/Basics/Netrc.swift
Sources/Workspace/Workspace.swift
Tests/BasicsTests/NetrcTests.swift
Utilities/bootstrap

It is time that we update our minimum deployment target, we haven't officially supported anything pre-12.0 since the 5.6 release.

Bump SwiftPM's minimum deployment target to macOS 12

---

Sources/Workspace/InitPackage.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6421 to `release/5.9`.

[5.9] Format test target in the macro package consistently with other targets

---

Package.swift

There's a regression in Swift Crypto 2.4.1 on Linux that makes our Linux self-hosted jobs to fail.

Use exact SwiftCrypto version to work around self-hosting failure

---

Package.swift
Sources/PackageCollectionsSigning/Certificate/Certificate.swift
Sources/PackageCollectionsSigning/Key/Key+RSA.swift

Motivation:
swift-crypto 2.4.1 includes updates in BoringSSL that cause `Unsafe*Pointer<EVP_PKEY>` become `OpaquePointer` and without this code adjustment SwiftPM fails to build with `error: cannot find type 'EVP_PKEY' in scope`.
Modifications:
- Update dependency from 2.4.0 to 2.4.1
- Replace `Unsafe*Pointer<EVP_PKEY>` with `OpaquePointer`.

Update to swift-crypto 2.4.1

---

Package.swift
Sources/PackageCollectionsSigning/Certificate/Certificate.swift
Sources/PackageCollectionsSigning/Key/Key+RSA.swift

Cherry pick https://github.com/apple/swift-package-manager/pull/6431 to 5.9
---
Motivation:
swift-crypto 2.4.1 includes updates in BoringSSL that cause `Unsafe*Pointer<EVP_PKEY>` become `OpaquePointer` and without this code adjustment SwiftPM fails to build with `error: cannot find type 'EVP_PKEY' in scope`.
Modifications:
- Update dependency from 2.4.0 to 2.4.1
- Replace `Unsafe*Pointer<EVP_PKEY>` with `OpaquePointer`.

[5.9] Update to swift-crypto 2.4.1

---

Sources/Build/BuildPlan.swift

The way this `switch` is written currently triggers a warning:
```
/Build/BuildPlan.swift:770:22: warning: case is already handled by previous patterns; consider removing it
case .macro:
```
Since this `case .macro` on line 770 is never reached due to another `case .macro` covering it above on line 737, it seems safe to remove the unused case altogether.

Build: fix duplicate `case` of `switch` in `BuildPlan.swift`

---

Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageModel/RegistryReleaseMetadata.swift

Prior changes have laid the groundwork for this, but we haven't actually exposed the signing entity here yet.
rdar://107033737

Expose `SigningEntity` via package metadata

---

Fixtures/DependencyResolution/External/Mirror/App/Package.swift
Tests/FunctionalTests/DependencyResolutionTests.swift

motivaiton: test coverage
change: update fixture to not force package name which is deprecated when using URLs

fix functional test

---

Tests/FunctionalTests/PluginTests.swift

We have recently seen some failures in this test e.g. https://ci.swift.org/job/oss-swift-package-ubuntu-20_04/1779/ -- it is not clear to me why these failures started to appear, but the diagnostic message that seems to be missing is not actually material to the test, so we can change the test to avoid this.
rdar://108091736

Change `testPluginCanBeReferencedByProductName`

---

Sources/swift-bootstrap/main.swift
Utilities/bootstrap

We should use `-Xbuild-tools-swiftc` instead, as the deprecation warning recommends.

bootstrap: fix use of deprecated `-Xmanifest` flag

---

Sources/Workspace/Workspace+BinaryArtifacts.swift

motivation: better ux
changes:
* change un-parsable info.plist warning to debug since its a valid use case and the warning is intended mainly for deubg purposes
* add informational diagnostics with the details of the found  the binary artifact
* formatting
rdar://107669671

quiet down redundant warnings for binary targets with multiple info.plist

---

Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift

Package plugins can be applied to packages in Xcode without any modification.  But Xcode also has an additional `XcodeProjectPlugin` module that provides extra API for applying plugins to Xcode projects.  Since this is a common use case, it makes sense for newly created plugins to have conditional use of that extra API by default.  If there is support for applying plugins to the project formats of other IDEs in the future, it would make sense to add those to the templates as well.
This support is currently always added but we could consider having options in the API for whether to add it.
Changes:
- extended the template-generated source code
- added to the unit tests
rdar://108166582

Newly created build tool and command plugin templates should have conditional support for XcodeProjectPlugin

---

Tests/PackageModelTests/PackageModelTests.swift

Use the unsuffixed version of the tool's spelling.  Although we should accept the suffixed variant (which `clang` does do!) the lookup in SPM currently does not properly handle the path lookup with that.

Tests: adjust windows librarian test slightly

---

Sources/PackageMetadata/PackageMetadata.swift
Sources/PackageModel/RegistryReleaseMetadata.swift

Prior changes have laid the groundwork for this, but we haven't actually exposed the signing entity here yet.
rdar://107033737
(cherry picked from commit 7a8a9e1226bfcf4194afb8f223a22c790669ba87)

[5.9] Expose `SigningEntity` via package metadata

---

Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift

This is a supplemental fix for https://github.com/apple/swift-package-manager/pull/6446 that removes the `async` specifier and corrects the protocol conformance of the Xcode command plug-in.  This change should have been part of that PR.
- remove the `async` specifier since the entry point that XcodeProjectPlugin defines isn't async
- correct the protocol conformance of the Xcode command plug-in
- update the unit tests
rdar://108166582

Supplemental fix for XcodeProjectPlugin support in package init template

---

Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift

This is a SwiftPM 5.9 nomination of #6446 and it's follow-on fix #6451.
Package plugins can be applied to packages in Xcode without any modification. But Xcode also has an additional XcodeProjectPlugin module that provides extra API for applying plugins to Xcode projects. Since this is a common use case, it makes sense for newly created plugins to have conditional use of that extra API by default. If there is support for applying plugins to the project formats of other IDEs in the future, it would make sense to add those to the templates as well.
This support is currently always added but we could consider having options in the API for whether to add it.
* extended the template-generated source code
* added to the unit tests
rdar://108166582

[5.9] Newly created build tool and command plugin templates should have conditional support for XcodeProjectPlugin #6446

---

Tests/BuildTests/BuildPlanTests.swift

This removes some extraneous printing during the test execution which is unnecessary and likely some debugging leftovers.

BuildTests: remove some likely debugging leftovers

---

Sources/CompilerPluginSupport/TargetExtensions.swift
Sources/PackageDescription/Target.swift
Sources/PackageModel/Manifest/TargetDescription.swift
Tests/PackageLoadingTests/PD_Next_LoadingTests.swift

We're amending SE-0394 to allow Swift/linker settings as well as plugin dependencies. This updates the implementation to match.

Update macro API

---

Tests/SPMBuildCoreTests/PluginInvocationTests.swift

motivation: stable CI
changes: disable testCompilationDiagnostics test since 5.8 has mismatched compiler

[5.8] skip testCompilationDiagnostics

---

Package.swift
Utilities/bootstrap

Cherrypick of #6321
__Explanation:__ The bootstrap script currently adds two relative runpaths for ELF platforms, one for the PackageDescription and other libraries and another for the single `swift-package` executable, but since they're applied on the command line, both runpaths are applied to all binaries. This pull separates out the runpaths and only applies each where needed. It also shifts much of the bootstrap script over to applying build flags based on the build target, not on checking the build host platform in Python.
__Scope:__ Should only affect the SPM build on ELF platforms like linux
__Risk:__ low, as it only affects building SPM for ELF platforms
__Testing:__ Passed all CI, including a trunk toolchain build that worked well
__Reviewer:__ @neonichu

[5.8] On ELF platforms, only add runpaths as needed (#6321)

---

Tests/WorkspaceTests/WorkspaceTests.swift

Reuse the base path from a local variable reducing the arcs that we append to reduce the amount of duplication and avoid having multiple sites to modify for changes.

WorkspaceTests: simplify constant construction

---

Sources/CompilerPluginSupport/TargetExtensions.swift
Sources/PackageDescription/Target.swift
Sources/PackageModel/Manifest/TargetDescription.swift
Tests/PackageLoadingTests/PD_Next_LoadingTests.swift

We're amending SE-0394 to allow Swift/linker settings as well as plugin dependencies. This updates the implementation to match.
(cherry picked from commit 1828be2bd6afb0e69dccbc79d6e67d747e024be6)

[5.9] Update macro API

---

Sources/PackageSigning/SigningIdentity.swift
Tests/PackageSigningTests/SigningTests.swift

- Remove macOS 11 check since macOS 12 is required now
- Add test

Minor code cleanup in PackageSigning

---

Package.swift

Motivation:
Windows build is broken due to `CoreFoundation` usage in `swift-certificates`.
Modifications:
https://github.com/apple/swift-certificates/pull/72 is the patch so update to that.

Bump swift-certificates to 0.4.1

---

Package.swift

Cherry pick https://github.com/apple/swift-package-manager/pull/6465 to 5.9
---
Motivation:
Windows build is broken due to `CoreFoundation` usage in `swift-certificates`.
Modifications:
https://github.com/apple/swift-certificates/pull/72 is the patch so update to that.

[5.9] Bump swift-certificates to 0.4.1

---

Sources/Workspace/CheckoutState.swift
Sources/Workspace/Workspace.swift

This makes it easier to diagnose cases where a stale branch was fetched from source control cache. Currently, no revision is printed when a branch is checked out, which makes it hard to understand which exact revision is stored for that branch in the cache.
We have a CI failure, which is likely caused by a stale cache: https://ci.swift.org/job/pr-swift-tools-support-core-macos/254/consoleFull. To confirm this hypothesis, it would be great if exact revision was printed together with a branch when checking out. See current output:
```
Working copy of https://github.com/apple/swift-certificates.git resolved at 0.4.1
Creating working copy for https://github.com/apple/swift-crypto.git
Working copy of https://github.com/apple/swift-crypto.git resolved at 2.5.0
Creating working copy for …
```

Workspace: log both branch and revision during checkout

---

Sources/CompilerPluginSupport/TargetExtensions.swift
Sources/Workspace/InitPackage.swift
Tests/PackageLoadingTests/PD_5_9_LoadingTests.swift

SE-0394 has been accepted, so we're making macros available as part of the 5.9 tools-version.

Add macros to 5.9 tools-version

---

Sources/Basics/Triple.swift
Sources/SPMBuildCore/BinaryTarget+Extensions.swift
Sources/SPMBuildCore/BuildParameters.swift

- Adds preliminary knowledge of armv7em and no os environments to spm. Future diffs will be required to fully support these triples. This change allows a armv7em-apple-none-macho build via a destination v3 bundle to make it further through spm.

Enable armv7em and os none triples

---

Sources/CompilerPluginSupport/TargetExtensions.swift
Sources/Workspace/InitPackage.swift
Tests/PackageLoadingTests/PD_5_9_LoadingTests.swift

SE-0394 has been accepted, so we're making macros available as part of the 5.9 tools-version.
(cherry picked from commit 4dbef25208c030eade3359de2a95d2f44956603b)

[5.9] Enable macros in 5.9 tools-version

---

Fixtures/Miscellaneous/CXX17CompilerCrash/v5_8/Package.swift
Fixtures/Miscellaneous/Plugins/PluginsAndSnippets/Package.swift
Sources/Basics/SwiftVersion.swift
Tests/BuildTests/BuildPlanTests.swift

Also tweak some tests that were either errorneously using 999.0 as their tools-version or those which require it.

Disable development mode for 5.9 branch

---

Tests/CommandsTests/BuildToolTests.swift

The underlying functionality this tests appears to be broken when using certain versions of swift-driver, so we have to disable it for now.

Disable `testImportOfMissedDepWarning`

---

Utilities/bootstrap

This is manifesting itself as `cannot find 'XCTAssertEqual' in scope` on Swift CI again, but instead of disabling these tests wholesale like we did before, we want to take a more targetted approach.
rdar://108519765

Skip SDK dependent tests in macOS bootstrap

---

Tests/CommandsTests/BuildToolTests.swift

The underlying functionality this tests appears to be broken when using certain versions of swift-driver, so we have to disable it for now.
(cherry picked from commit fc1762520803d7315e659b29a430595b82125570)

[5.9] Disable `testImportOfMissedDepWarning`

---

Sources/Basics/Triple.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/PackageModel/UserToolchain.swift
Sources/SPMBuildCore/BuildParameters.swift
Tests/BasicsTests/TripleTests.swift

Fixes a bug where all triples with vendor apple are considered to be os variants of darwin. This change special cases "apple-none" to not match `Triple.isDarwin()`, but all other "apple-*" triples will still be considered to be darwin variant.
Fixes some fallout of making the above change to check for the newly added `Triple.isApple()` instead of `Triple.isDarwin()` to allow the triple "apple-none" to opt into behaviors like dead stripping, using libtool, etc.
As a result of these changes spm no longer appends a macOS version number to the "armv7em-apple-none-macho" triple (e.g. "armv7em-apple-none-macho10.13") removing the work around of passing "-target armv7em-apple-none-macho" via cli args or via a toolset.json.
Additionally spm no longer passes unexpected -rpath args to the linker …

Disambiguate apple and darwin triples

---

Sources/PackagePlugin/PackageModel.swift
Sources/PackagePlugin/PluginContextDeserializer.swift
Sources/PackagePlugin/PluginMessages.swift
Sources/SPMBuildCore/PluginContextSerializer.swift

This currently prevents the use of plugins in any package graph that happens to include one or more macro targets which seems extremely unfortunate.
This fix is slightly ugly because `PackagePlugin` should not concretely know about macros. An alternative could be excluding macros from the project model that plugins see.
rdar://108531004

Support macro targets in plugin context

---

Sources/Workspace/InitPackage.swift

* **Explanation**: SwiftSyntax just introduced an `assertMacroExpansion` function to test macros. The macro temple should use that
* **Scope**: The macro template generated by `swift package init --type macro`
* **Risk**: Low, only affects new macro templates
* **Testing**: Tested that the newly generated template builds and passes tests
* **Issue**: rdar://107971349
* **Reviewer**:

[5.9] Use assertMacroExpansion in test cases of macro template

---

Sources/Workspace/InitPackage.swift

Use the newly introduced `assertMacroExpansion` function in the test cases generated by the macro template. 
Also, clean up some of the macro’s formatting.

Use assertMacroExpansion in test cases of macro template

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/CoreCommands/Options.swift
Sources/SPMBuildCore/BuildParameters.swift

CoreCommands: fix comment typo

---

Sources/PackageGraph/PubGrub/PartialSolution.swift
Sources/PackageGraph/PubGrub/PubGrubDependencyResolver.swift
Sources/PackageGraph/Version+Extensions.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/VersionSetSpecifierTests.swift

motivation: some version calculations were incorrect when dealing with pre-release identifiers, leading to dependency resolution errors
changes:
* fix Version::nextPatch() to take into pre-release identifiers into account
* add tests

fix VersionSetSpecifier calculation for versions with pre-release identifiers

---

Tests/SPMBuildCoreTests/PluginInvocationTests.swift

In the case of a failure in the test, we would previously continue to perform the slice operation which will fail in the case of an Asserts runtime due to an out of bounds access.  The use of `first?` here would unwrap or fail, allowing tests to continue execution.

Tests: prefer to use `first` rather than indexing

---

Sources/PackagePlugin/PackageModel.swift
Sources/PackagePlugin/PluginContextDeserializer.swift
Sources/PackagePlugin/PluginMessages.swift
Sources/SPMBuildCore/PluginContextSerializer.swift

This currently prevents the use of plugins in any package graph that happens to include one or more macro targets which seems extremely unfortunate.
This fix is slightly ugly because `PackagePlugin` should not concretely know about macros. An alternative could be excluding macros from the project model that plugins see.
rdar://108531004
(cherry picked from commit 76744ca25260ca487b6f75f099219cdacb3fd231)

[5.9] Support macro targets in plugin context

---

Sources/PackageGraph/PubGrub/PartialSolution.swift
Sources/PackageGraph/PubGrub/PubGrubDependencyResolver.swift
Sources/PackageGraph/Version+Extensions.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/VersionSetSpecifierTests.swift

[5.9] fix VersionSetSpecifier calculation for versions with pre-release identifiers

---

Sources/PackageGraph/PackageGraph+Loading.swift
Tests/PackageGraphTests/PackageGraphTests.swift

If the computed XCTest minimum deployment target is lower than the oldest supported version of a platform, we should not use it as the basis for deployment targets of test targets.
This issue was actually also present in the tests which were written to expect the incorrect behavior of always preferring the XCTest minimum deployment target.
rdar://108462045

Fix use of XCTest minimum deployment target

---

Sources/Basics/CMakeLists.txt
Sources/Basics/NativePathExtensions.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildPlan.swift

We end up needing these in a few places, and while we could make it `internal` and use `@testable` imports in the tests, this ends up being needed in `Build` and `PackageLoading`.  Ideally, we would give it package visibility, but that functionality would not be backwards compatible.  This is a reluctant approach at solving that problem by using `public` visibility.

Basics: introduce some native path representation helpers

---

Sources/PackageRegistry/RegistryClient.swift

motvation: more verbose error message when availability check fails
changes:
* wrap availability check error handling with explicit error

PackageRegistry: improve error handling of availability check

---

Sources/PackageGraph/PackageGraph+Loading.swift
Tests/PackageGraphTests/PackageGraphTests.swift

If the computed XCTest minimum deployment target is lower than the oldest supported version of a platform, we should not use it as the basis for deployment targets of test targets.
This issue was actually also present in the tests which were written to expect the incorrect behavior of always preferring the XCTest minimum deployment target.
rdar://108462045
(cherry picked from commit 8af71a96ca22e13b32fa64e2c2bc86826fd9fe41)

[5.9] Fix use of XCTest minimum deployment target

---

Package.swift

Looks like these tests are suffering from some of the same problems as `FunctionalTests` which makes sense since they're conceptually very similar.

Put `CommandsTests` behind `SWIFTCI_DISABLE_SDK_DEPENDENT_TESTS`

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/BuildFlags.swift
Sources/PackageModel/UserToolchain.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

Refactors the various compilerArguments and linkerArgument functions
slightly to ensure flags from a user's sdk and cli properly propagate to
the expected subcommand invocations.
Adds a fairly comprehensive test to cover the toolset and cli flag
passing end result.
---
Fixes a bug where clang targets didn't respect the `isCXX` override.
Fixes a bug where cxxCompiler extraCLIFlags where not passed to clang
when building cxx targets. Future work: #6491. cxxCompiler extraCLIFlags
should also be passed to `swiftc` when compiling swift modules to ensure
the clang importer has the same interpretation of the module as the
initial compile.
Fixes a bug where linker extraCLIFlags were not passed to `swiftc`
prefixed by `-Xlinker`. The previous workaround to pass these flags in
swiftCompiler …

Improve handling of tool build flags

---

Sources/PackageDescription/BuildSettings.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/BuildTests/BuildPlanTests.swift

The Swift compiler now supports `-cxx-interoperability-mode=default` flag. It no longer requires passing an explicit version of Swift/C++ interoperability.
This change makes sure SwiftPM accepts `nil` as a version of Swift/C++ interoperability.

Allow enabling C++ interop without explicit version

---

Sources/PackageDescription/BuildSettings.swift
Sources/PackageDescription/PackageDependency.swift
Sources/PackageDescription/PackageDescription.docc/Curation/Extensions/Product-Executable.md
Sources/PackageDescription/PackageDescription.docc/Curation/Platform.md
Sources/PackageDescription/PackageDescription.docc/Curation/Plugin.md
Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
Sources/PackageDescription/PackageDescription.docc/Curation/Product.md
Sources/PackageDescription/PackageDescription.docc/Curation/SupportedPlatforms.md
Sources/PackageDescription/PackageDescription.docc/Curation/Target-Dependency.md
Sources/PackageDescription/PackageDescription.swift
Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
Sources/PackageDescription/Product.swift
Sources/PackageDescription/Resource.swift
Sources/PackageDescription/SupportedPlatforms.swift
Sources/PackageDescription/Target.swift

Cherry-pick documentation updates from `main` into `release/5.9`
I made documentation updates in `main` in 942a1e8 and 7a8f7f6, and now those need to migrate into `release/5.9`.
I cherry-picked 942a1e8 and 7a8f7f6 from `main`.
Only DocC documentation should change, and only in `Source/PackageDescription/`.

[5.9] Cherry-pick documentation updates

---

Sources/PackageDescription/BuildSettings.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/BuildTests/BuildPlanTests.swift

The Swift compiler now supports `-cxx-interoperability-mode=default` flag.
This change makes sure SwiftPM accepts `nil` as a version of Swift/C++ interoperability.
rdar://107908465
(cherry picked from commit a54a87f4dec65ca958bb53a637fc3bdf54856cba)

[5.9] 🍒Allow enabling C++ interop without explicit version (#6416)

---

Fixtures/Miscellaneous/SkipTests/.gitignore
Fixtures/Miscellaneous/SkipTests/Package.swift
Fixtures/Miscellaneous/SkipTests/Sources/Example/Example.swift
Fixtures/Miscellaneous/SkipTests/Tests/ExampleTests/MoreTests.swift
Fixtures/Miscellaneous/SkipTests/Tests/ExampleTests/Tests.swift
Sources/SPMTestSupport/SwiftPMProduct.swift
Sources/SPMTestSupport/XCTAssertHelpers.swift
Sources/SPMTestSupport/misc.swift
Tests/CommandsTests/APIDiffTests.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/PackageRegistryToolTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/CommandsTests/RunToolTests.swift
Tests/CommandsTests/TestToolTests.swift
Tests/FunctionalPerformanceTests/BuildPerfTests.swift
Tests/FunctionalTests/CFamilyTargetTests.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
Tests/FunctionalTests/PluginTests.swift
Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/FunctionalTests/VersionSpecificTests.swift

motivation: these are specific to SwiftPM and should not be in TSC
changes:
* move Product, SwiftPMProductError from TSC to SwiftPM
* refactor how SwiftPMProduct is used in tests
* update all callsites (tests)

move Product, SwiftPMProductError from TSC to SwiftPM

---

Sources/Basics/Sandbox.swift
Sources/Commands/Utilities/DescribedPackage.swift
Sources/PackageDescription/PackageDescriptionSerialization.swift
Sources/PackageDescription/Target.swift
Sources/PackageModel/Manifest/TargetDescription.swift
Sources/PackageModel/Target.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift

TCP and UDP port numbers are unsigned 16-bit integers, but SandboxNetworkPermission uses UInt8s so trying to specify anything but a small subset of low port numbers causes an error:
permissions: [
.allowNetworkConnections(
scope: .all(ports: [443, 8080]),
reason: "This command accesses the network"
)
]
leads to
error: integer literal '443' overflows when stored into 'Array<UInt8>.ArrayLiteralElement' (aka 'UInt8')
error: integer literal '8080' overflows when stored into 'Array<UInt8>.ArrayLiteralElement' (aka 'UInt8')
This commit updates the type definitions and adds some higher-numbered ports to the .allowNetworkConnections test cases.
It is possible to specify that a plugin needs access to ports higher than 255.

sandbox: UInt8 is too small to hold a TCP or UDP port

---

Sources/Basics/Sandbox.swift
Sources/Commands/Utilities/DescribedPackage.swift
Sources/PackageDescription/PackageDescriptionSerialization.swift
Sources/PackageDescription/Target.swift
Sources/PackageModel/Manifest/TargetDescription.swift
Sources/PackageModel/Target.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift

Cherry pick of #6518
TCP and UDP port numbers are unsigned 16-bit integers, but SandboxNetworkPermission uses UInt8s so trying to specify anything but a small subset of low port numbers causes an error:
permissions: [
.allowNetworkConnections(
scope: .all(ports: [443, 8080]),
reason: "This command accesses the network"
)
]
leads to
error: integer literal '443' overflows when stored into 'Array<UInt8>.ArrayLiteralElement' (aka 'UInt8')
error: integer literal '8080' overflows when stored into 'Array<UInt8>.ArrayLiteralElement' (aka 'UInt8')
This commit updates the type definitions and adds some higher-numbered ports to the .allowNetworkConnections test cases.
It is possible to specify that a plugin needs access to higher-numbered ports.

[5.9] sandbox: UInt8 is too small to hold a TCP or UDP port

---

CHANGELOG.md

Close #6522 
Fix the broken links

Fix CHANGELOG.md’s link

---

Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/Workspace/DefaultPluginScriptRunner.swift

This does not seem like a good fallback anymore since e.g. it'll always fail on Apple Silicon machines in case it is reached. Instead, use the default host triple as the fallback.
rdar://109066834

Remove 10.15 fallback for manifest/plugin compilation

---

Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/ToolsVersionParserTests.swift

Tests here verify the paths, which need the native representation.  This ensures that we get the correct spelling of the paths in these tests.
The memory leak on the non-Darwin platforms exists due to the path string not being pushed into an autorelease pool.  The use of `withUnsafeFileSystemRepresentation` ends up mismatching the arc separator resulting in a test failure.

PackageLoadingTests: ensure that we use the correct path spelling

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/SharedTargetBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildDescription/TargetBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/Build/CMakeLists.txt
Sources/Build/LLBuildManifestBuilder.swift

While we intentionally don't support generating C sources from plugins today since we haven't figured out how to deal with headers etc, not running plugins at all without any diagnostics whatsoever seems like an implementation oversight based on the fact that we have two completely different implementations for Swift and C-family targets (which is something we also need to rectify at some point).
With this change, we're running build-tool plugins in the exact same way as we are doing it for Swift targets. We are only doing this for packages with tools-version 5.9 or higher in order to have any unintentional impact on existing packages.
rdar://101671614

Run build tool plugins for C-family targets

---

Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift
Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift
Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Package.swift
Sources/PackageDescription/Target.swift
Sources/PackageModel/PackageModel.swift
Tests/BuildTests/BuildPlanTests.swift

The package visibility proposal has officially been accepted: https://forums.swift.org/t/accepted-se-0386-package-access-modifier/64904
Resolves rdar://109152010

Enable package visibility feature for tools-version 5.9

---

Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/Workspace/DefaultPluginScriptRunner.swift

This does not seem like a good fallback anymore since e.g. it'll always fail on Apple Silicon machines in case it is reached. Instead, use the default host triple as the fallback.
rdar://109066834
(cherry picked from commit 5e2dcee623b30d1c2f1551243b04ecfdaf1e2dec)

[5.9] Remove 10.15 fallback for manifest/plugin compilation

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/SharedTargetBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildDescription/TargetBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/Build/CMakeLists.txt
Sources/Build/LLBuildManifestBuilder.swift

While we intentionally don't support generating C sources from plugins today since we haven't figured out how to deal with headers etc, not running plugins at all without any diagnostics whatsoever seems like an implementation oversight based on the fact that we have two completely different implementations for Swift and C-family targets (which is something we also need to rectify at some point).
With this change, we're running build-tool plugins in the exact same way as we are doing it for Swift targets. We are only doing this for packages with tools-version 5.9 or higher in order to have any unintentional impact on existing packages.
rdar://101671614
Co-authored-by: Max Desiatov <m_desiatov@apple.com>
(cherry picked from commit 678e6831c7b113b9715543f0378c40ef821da71c)

[5.9] Run build tool plugins for C-family targets

---

Sources/SourceControl/GitRepository.swift

Git 2.36.0 renamed `useBuiltinFSMonitor` to `fsmonitor`.  This configuration setting results in a warning.  Given that Git 2.36.0 is now over a year old, rename the option we use to silence the warning. In the case of an installation of git predating the configuration renaming, we could run into issues with git opening the files preventing subsequent git operations, but in the general case, this should be equivalent.

SourceControl: rename `useBuiltinFSMonitor` to `fsmonitor`

---

Sources/Workspace/InitPackage.swift

We do this in all the other templates and it generally makes it easier to add new targets to the template after the fact.

Add comma to executable template

---

Sources/SourceControl/GitRepository.swift

Centralise the git clone command invocation to ensure that we uniformly handle the arguments for the clone.  This sets the stage for further tweaks needed to fix cloning some repositories on Windows.

SourceControl: centralise git cloning

---

Sources/Workspace/InitPackage.swift

We do this in all the other templates and it generally makes it easier to add new targets to the template after the fact.
(cherry picked from commit 2c57ad1d4ff1c40f988c6acfc0aa9fe58c68f25b)

[5.9] Add comma to executable template

---

Sources/SourceControl/GitRepository.swift

Windows paths are limited to 261 characters by default.  Git provides the `core.longpaths` option to use the extended path support.  This should make SPM more reliable on Windows.

SourceControl: attempt to enable long path support for Windows

---

Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
Sources/PackageDescription/Target.swift

Documentation fixes for `PluginNetworkPermissionScope`.
There were two issues with the documentation for `PluginNetworkPermissionScope`:
- It was not curated, and this caused the symbol to show up at the top level of the `PackageDescription` documentation. This was not desired.
- The abstract for the symbol was not on its own line in the DocC comments. This caused the abstract to have multiple sentences, which goes against style.
- The `PluginNetworkPermissionScope` symbol was curated under the `PluginPermission` symbol.
- The DocC documentation for `PluginNetworkPermissionScope` was changed to provide a single sentence abstract on its own line, and one additional sentence on a separate line.
The `PluginNetworkPermissionScope` documentation is now curated in the correct place, and the …

Documentation fixes for `PluginNetworkPermissionScope`.

---

Sources/PackageRegistry/RegistryClient.swift
Tests/PackageRegistryTests/RegistryClientTests.swift

Similar to all other request types, this will guarantee more consistent diagnostics if there are underlying `URLSession` errors etc.

Wrap registry login errors

---

Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
Sources/PackageDescription/Target.swift

Cherry-pick the documentation update from `main` to the `release/5.9` branch.
The recent documentation fix should be included in the 5.9 release.
Commit 0efea68 was cherry-picked.
The `PluginNetworkPermissionScope` documentation fixes will be included in the `release/5.9` branch. Only DocC content changed. Two files changed:
- `Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md`
- `Sources/PackageDescription/Target.swift`

[5.9] Cherry-pick documentation fixes for `PluginNetworkPermissionScope`. (#6555)

---

Sources/Workspace/InitPackage.swift

We are using `pkgname` everywhere as target names and also as dependency references, but plugin targets were using `typeName` which leads to newly created plugin packages being broken if the difference was meaningful (e.g. if the name includes dashes).
(cherry picked from commit 78cceb7b6bd32b334999cb0a4837e970bdce990a)

[5.9] Fix plugin templates

---

Sources/Basics/Triple.swift
Tests/BasicsTests/TripleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6544.
Currently `Triple` is not `CustomStringConvertible`, which leads to issues when using it in string interpolations. It uses default implementation that prints all of the triple components separately, which isn't user-readable.
For example, when using `swift experimental-sdk configuration show` subcommand on a bundle that has wrong triples, an error message is printed which is badly formatted and likely does not show the root cause of the issue.
rdar://107882041
Added `CustomStringConvertible` conformance on `Triple`, which uses underlying `tripleString` as a return value.
`Triple` values are more human-readable when displayed in user-visible strings.

[5.9] Fix `Triple` formatting in error messages

---

Tests/FunctionalTests/PluginTests.swift

We have recently seen some failures in this test e.g. https://ci.swift.org/job/oss-swift-package-ubuntu-20_04/1779/ -- it is not clear to me why these failures started to appear, but the diagnostic message that seems to be missing is not actually material to the test, so we can change the test to avoid this.
rdar://109368270
(cherry picked from commit 96db9f664e7347c403192bd6718435f2a30df69f)

[5.9] Change `testPluginCanBeReferencedByProductName`

---

Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
Tests/PackageGraphTests/PubgrubTests.swift

There's an unfortunate interaction here with the resolver precomputation / `LocalPackageContainer` which leads to us rejecting versions as "not available" if they don't happen to be the currently checked out version. We need a more hollistic change to resolve this issue which is out of scope for 5.9, so we'll revert this change here.
rdar://107895012

[5.9] Revert "missing pinned version" change

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

Currently, when cross-compiling from Darwin to platforms that don't expect `-lc++` by default (e.g. most Linux distributions), the build will fail because `-lc++` is always passed. When should check the destination triple and not the host triple in the build plan code paths.
This leads to confusing build errors when cross-compiling more complex projects like Vapor.
rdar://107487090
Modified `BuildPlan.swift` to check the value of the `triple` property instead of `hostTriple`. Added a test that verifies this cross-compilation case.
Projects that contain C++ can now be cross-compiled from macOS to Linux.

BuildPlan: infer `-lc++` based on run-time triple

---

Sources/PackageModel/SwiftSDKBundle.swift

Some of user-visible strings refer to "cross-compilation destinations", while those are called "Swift SDKs" per the updated SE proposal. Let's update the strings to match the proposal.

SwiftSDKBundle.swift: update strings to use "Swift SDK" naming

---

Sources/PackageModel/SwiftSDKBundle.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6579.
Some of user-visible strings refer to "cross-compilation destinations", while those are called "Swift SDKs" per the updated SE proposal. Let's update the strings to match the proposal.

[5.9] SwiftSDKBundle: update strings to use "Swift SDK" naming

---

Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift

Motivation:
When registry publish fails with client error, the current error message is "Error: failed publishing: invalid registry response status '400', expected '[201, 202]'", which doesn't provide much information on what went wrong.
rdar://109410245
Modifications:
- Wrap 4xx status response in `RegistryError.clientError` and 5xx in `RegistryError.serverError`. Both errors include response body as details.
- Change `package-registry publish` to throw the wrapped `clientError` such that more details (i.e., response body) get displayed.

Improve error message for 'package-registry publish'

---

Sources/PackageDescription/BuildSettings.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
Sources/PackageModel/ManifestSourceGeneration.swift
Tests/BuildTests/BuildPlanTests.swift

The version of C++ interoperability is going to be tied to Swift language version.
This change removes the explicit version parameter for the `.interoperabilityMode(.Cxx)` build setting.
rdar://109525217

Remove the version parameter for C++ interop mode build setting

---

Sources/Basics/Triple.swift
Tests/BasicsTests/TripleTests.swift

Currently `Triple` is not `CustomStringConvertible`, which leads to issues when using it in string interpolations. It uses default implementation that prints all of the triple components separately, which isn't user-readable.
For example, when using `swift experimental-sdk configuration show` subcommand on a bundle that has wrong triples, an error message is printed which is badly formatted and likely does not show the root cause of the issue.
rdar://107882041
Added `CustomStringConvertible` conformance on `Triple`, which uses underlying `tripleString` as a return value.
`Triple` values are more human-readable when displayed in user-visible strings.

Fix `Triple` formatting in error messages

---

Sources/PackageDescription/BuildSettings.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
Sources/PackageModel/ManifestSourceGeneration.swift
Tests/BuildTests/BuildPlanTests.swift

The version of C++ interoperability is going to be tied to Swift language version. This change removes the explicit version parameter for the `.interoperabilityMode(.Cxx)` build setting.
rdar://109525217
(cherry picked from commit fdf39fdd827081938d28f4d57bb7d7acdb47e163)

[5.9]🍒Remove the version parameter for C++ interop mode build setting (#6583)

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6581
Currently, when cross-compiling from Darwin to platforms that don't expect `-lc++` by default (e.g. most Linux distributions), the build will fail because `-lc++` is always passed. When should check the destination triple and not the host triple in the build plan code paths.
This leads to confusing build errors when cross-compiling more complex projects like Vapor.
rdar://107487090
Modified `BuildPlan.swift` to check the value of the `triple` property instead of `hostTriple`. Added a test that verifies this cross-compilation case.
Projects that contain C++ can now be cross-compiled from macOS to Linux.

[5.9] BuildPlan: infer `-lc++` based on run-time triple

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/MockBuildTestHelper.swift

This derives the required `-external-plugin-path` arguments when using an OSS toolchain with SwiftPM.

rdar://109108066 (Derive '-external-plugin-path' compiler arguments in SwiftPM)

---

Sources/Build/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/BuildManifest.swift

This parameter was unused, remove it to simplify he signature. Identified when trying to investigate the removal of the use of the builtin command in llbuild.

Build: remove unused parameter

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/MockBuildTestHelper.swift

This derives the required `-external-plugin-path` arguments when using an OSS toolchain with SwiftPM.
(cherry picked from commit 72d5b34f9a64956b0157d52b0ff9eb4e16aa252b)

[5.9] rdar://109108066 (Derive '-external-plugin-path' compiler arguments in SwiftPM)

---

Sources/PackageModel/SwiftSDKBundle.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

`SwiftSDKBundleTests` should cover the `list` subcommand and verify that all installed Swift SDK bundles are listed.
New `testList` test function was added, while `testInstall` was refactored to share mock Swift SDK generation code with it.
rdar://107882144

Swift SDKs: refactor and extend `SwiftSDKBundleTests`

---

Sources/PackageModel/SwiftSDKBundle.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6588
`SwiftSDKBundleTests` should cover the `list` subcommand and verify that all installed Swift SDK bundles are listed.
New `testList` test function was added, while `testInstall` was refactored to share mock Swift SDK generation code with it.
rdar://107882144

[5.9] Swift SDKs: refactor and extend `SwiftSDKBundleTests`

---

Sources/Basics/Triple.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift
Tests/WorkspaceTests/WorkspaceTests.swift

On macOS hostTriple hardcoded as `x86_64-apple-macosx` which may not reflect the real host triple. As far as I understand the latest Xcode version are shipped with `-print-target-info` compatible compiler which allows to get rid of this `FIXME`
Xcode ships with necessary `-print-target-info` option
Cleanup of small FIXME and misleading hardcoded value
Make a call to swift compiler on macOS to retrieve the triple information
macOS triple now reflects real value received from swift compiler

Delete macOS triple hardcode

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6567 to 5.9

[5.9] Add token-file option to 'package-registry login'

---

IntegrationTests/Tests/IntegrationTests/BasicTests.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/LLBuildManifest/Tools.swift
Tests/CommandsTests/BuildToolTests.swift

This allows us to take control of these compiler invocations and is a first step towards unifying all the various ways of generating compiler arguments that are currently in `SwiftTargetBuildDescription`.
This PR aims to keep the behavior of the existing tool as far as possible, the only known differences are single quotes instead of double for arguments with spaces and the fact that the output file map will be created eagerly.
resolves https://github.com/apple/swift-package-manager/issues/6575

Stop using llbuild's Swift compiler tool

---

Sources/PackageCollectionsSigning/CMakeLists.txt

This was causing our bootstrap build to fail in NixOS packaging.
Doesn't appear to be necessary for `release/5.9` or `main`.

[5.8] Fix linking of bootstrap PackageCollectionsSigning

---

Sources/Commands/SwiftTestTool.swift

Cases of this enum didn't have its doc comments attached, as those where collected in a single comment for the enum itself. Attaching comments to specific cases makes them renderable in IDEs and DocC.

Commands/SwiftTestTool.swift: update TestCaseSpecifier doc comments

---

Package.swift
Sources/PackageCollectionsSigning/CertificatePolicy.swift
Sources/PackageSigning/SignatureProvider.swift
Sources/PackageSigning/VerifierPolicies.swift
Tests/PackageCollectionsSigningTests/Utilities.swift
Tests/PackageSigningTests/SigningTests.swift

`swift-certificates` has released a new version with a couple breaking changes:
- `PolicySet` is deprecated in favour of a [new result builder DSL](https://github.com/apple/swift-certificates/pull/79) and returns an opaque `VerifierPolicy`. Verifier is now generic over the concrete `VerifierPolicy` and uses the `@PolicyBuilder` to constructs its policy.
- `Certificate.Extensions` now [gracefully fails extension serialization](https://github.com/apple/swift-certificates/pull/80) but now needs to return `Result<Certificate.Extensions, any Error>`.
This PR adopts these new changes.

Adopt `swift-certificates` `0.6.0`

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift

Motivation:
`swift package-registry login` in interactive mode truncates input when the provided password/token is more than 128 chars long. This is a limitation of `getpass`.
rdar://109372320
Modifications:
- Use `readpassphrase`, which allows custom input length, instead of `getpass`.
- Improve error message when the provided password/token is too long.
- Increase password/token length limit to 512 chars

Registry login interactive mode cannot read password/token over 128 chars long

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/BuildPlan.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/LLBuildManifest/Tools.swift
Tests/BuildTests/BuildPlanTests.swift

This moves the generation of link file lists into the build system instead of doing it ad-hoc outside of the build. For this, we have a new `WriteAuxiliaryFile` tool and associated command that should be usable for any kind of writing of auxiliary files during the build.
Note that this change opted to not touch the existing infrastructure for in-process tools, so any inputs that are needed for the file generation will need to be flattened into a generic array of input nodes. The different types of file generation are keyed off a virtual node at the start of that array.

Write link file list as a build command

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift

Cherry-pick https://github.com/apple/swift-package-manager/pull/6562

[5.9] Registry login interactive mode cannot read password/token over 128 chars long

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/BuildParameters.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

- Updates swift build with an `-experimental-lto-mode` option which can
be set to either "full" or "thin" enabling the use of llvm LTO for
both swift and c targets. Updates BuildParameters with a matching
linkTimeOptimizationMode and updates SwiftTargetBuildDescription to
use the proper file extension for bitcode objects as well as place
them in the proper output location.

BuildDescription: Set output path for bc files

---

Sources/Basics/Concurrency/NSLock+Extensions.swift

I noticed this through warnings, but I think this also generally makes sense since there isn't a requirement to consume the result here.

`withLock` should be marked as having a discardable result

---

IntegrationTests/Tests/IntegrationTests/Helpers.swift

`RelativePath(validating:)` should be used instead.

IntegrationTests: fix use of deprecated `RelativePath.init`

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

- Fixes a bug where includeSearchPaths and librarySearchPaths defined in
a swift-sdk.json file were not properly respected. Updates
UserToolchain to support these by adding matching properties and
updates SwiftTargetBuildDescription as well as
ClangTargetBuildDescription to pass these toolchain search paths to
the compilers and linkers as expected.

Handle swift-sdk search paths

---

IntegrationTests/Tests/IntegrationTests/BasicTests.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/LLBuildManifest/Tools.swift
Tests/BuildTests/BuildPlanTests.swift

When invoking the driver use file lists rather than passing all the sources on the command line.  This is particularly import for Windows where the command line limit is 32k.  With deep dependency sets and large projects, it is possible to overrun this limit and fail to invoke the command.  The driver itself will invoke the frontend using response files if the invocation will overflow the command line limit.

Build: migrate to file lists for driver invocations

---

Sources/PackageDescription/SupportedPlatforms.swift
Tests/PackageLoadingTests/PD_5_9_LoadingTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift

Add PackageDescription platform constants for the 2023 Apple OS versions.
This is an update that happens every year at Apple's annual WWDC conference, where the Apple platforms usually have their versions incremented.  This allows packages that specify the latest tools version (in this case 5.9) to declare that they require the latest platform versions, which may be appropriate in some cases.  Note that most packages should continue supporting the oldest platform tools version that they can (based on the APIs they use), so that they will be usable to the maximum number of client packages and projects.
- added new platform version number constants for macOS 14, iOS 17, tvOS 17, watchOS 10, macCatalyst 17, and DriverKit 23 (which has its own version number, though it isn't a separate …

Add PackageDescription platform constants for the 2023 Apple OS versions

---

Sources/PackageDescription/SupportedPlatforms.swift
Tests/PackageLoadingTests/PD_5_9_LoadingTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift

This is a 5.9 nomination of #6636.
* Add platform constants for each of the Apple platforms, to match those in the WWDC 2023 Xcode beta release.
* Add a package loading unit test for checking the platform versions allowed in tools version 5.9.
rdar://107794704
(cherry picked from commit 55006dce81ae70cd8f2b78479038423eeebde1e4)

[5.9] Add PackageDescription platform constants for the 2023 Apple OS versions

---

Sources/SPMTestSupport/SwiftPMProduct.swift

Fixes a warning produced during compilation of this file:
```
swiftpm/Sources/SPMTestSupport/SwiftPMProduct.swift:58:16: warning: no calls to throwing functions occur within 'try' expression
return try! AbsolutePath(CommandLine.arguments.first!, relativeTo: localFileSystem.currentWorkingDirectory!)
```

[NFC] SwiftPMProduct.swift: fix use of deprecated initializer

---

Sources/Workspace/InitPackage.swift

The testable module for a macro will only build for the host platform which currently causes somewhat confusing issues if e.g. one is running tests for iOS in Xcode. This change will allow us to skip the tests if they are being run in an unsupported configuration.
rdar://110541100

Improve macros test template

---

Sources/Workspace/InitPackage.swift

The testable module for a macro will only build for the host platform which currently causes somewhat confusing issues if e.g. one is running tests for iOS in Xcode. This change will allow us to skip the tests if they are being run in an unsupported configuration.
rdar://110541100

[5.9] Improve macros test template

---

Tests/BasicsTests/FileSystem/PathTests.swift

The arc separator on Windows is `\` rather than `/`.  The path tests hard coded the expectation that the unix path separator is always used which is not a valid assumption.  Add a branch for windows in a large number of cases.  Although we do not fully pass the tests, this gets us closer.

Tests: attempt to handle arc separators in tests

---

Sources/Basics/FileSystem/FileSystem+Extensions.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Workspace/Workspace+State.swift

When building a project inside of VSCode with the LSP enabled, rebuilding the project would trigger a change to the mtimes of the auxiliary files resulting in an unnecessary rebuilding of targets.  In conjunction with the changes to tools-support-core (apple/swift-tools-support-core#422), incremental builds do not trigger a cascade of rebuilds that are unnecessary.
Extracted from a patch by Ami Fischman!

Workspace,Build: reduce `mtime` updates

---

Documentation/Usage.md

Updates the [usage documentation](Documentation/Usage.md) around requiring system libraries.
I was getting started with Swift package manager, and looking to get a bit more experience using it — and stumbled on #6121, thought I'd play around and try to clean it up. Fixes #6121.
The existing documentation on `main` worked, but following it emitted a build-time warning about wrapping system libraries in a target, instead of it's own package.
I've tried to make things work without warnings, tested the `.systemLibrary` approach, and documented my steps.
No functional changes to the package manager behavior — just the documentation change. After the change, one should be able to follow the docs step by step, and it should work without any build warnings.

[docs] Requiring System Libraries with .systemLibrary targets

---

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Sources/PackageDescription/PackageDescription.docc/Curation/SupportedPlatforms.md
Sources/PackageDescription/SupportedPlatforms.swift
Sources/PackageModel/ManifestSourceGeneration.swift
Sources/PackageModel/MinimumDeploymentTarget.swift
Sources/PackageModel/Platform.swift
Sources/PackageModel/PlatformRegistry.swift
Sources/Workspace/InitPackage.swift
Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/PD_5_9_LoadingTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Tests/XCBuildSupportTests/PIFBuilderTests.swift

Add new enum constants for visionOS in all the places where it is appropriate.
This includes the `platforms` parameter in the manifest, whose purpose is to list the minimum deployment targets that a package requires. Since there is initially only visionOS 1.0, and because absence of a platform in the `platforms` parameter means that the default version is supported (not that the platform is unsupported), all packages implicitly support visionOS 1.0 whether or not they list it in the `platforms` parameter. But having the enum constant alongside those for the other Apple platforms makes everything consistent, and will become important for any future versions.
This change also makes the `visionOS` platform available for use in conditional target dependencies.
Xcode Beta 2, released earlier …

Add `visionOS` as a platform alongside `iOS`, `tvOS`, `watchOS`, and the others

---

Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Sources/PackageDescription/PackageDescription.docc/Curation/SupportedPlatforms.md
Sources/PackageDescription/SupportedPlatforms.swift
Sources/PackageModel/ManifestSourceGeneration.swift
Sources/PackageModel/MinimumDeploymentTarget.swift
Sources/PackageModel/Platform.swift
Sources/PackageModel/PlatformRegistry.swift
Sources/Workspace/InitPackage.swift
Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/PD_5_9_LoadingTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Tests/XCBuildSupportTests/PIFBuilderTests.swift

This is a 5.9 nomination of a cherry-pick of #6662.

[5.9] Add `visionOS` as a platform alongside `iOS`, `tvOS`, `watchOS`, and the others

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Sources/XCBuildSupport/PIF.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

Support building String Catalogs when using XCBuild as the underlying build system (in Swift 5.9 tools).
Xcode 15 introduced String Catalogs, which are also supported in Swift Packages when building with Xcode.
Teach `FileRuleDescription` about the String Catalog file type, similar to other xcbuild-only file types such as Asset Catalogs.
Packages using swift-tools-version 5.9 and later will be able to build String Catalogs without any manual processing rules in the Package manifest.

Support String Catalogs in Packages when using XCBuild

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Sources/XCBuildSupport/PIF.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

This is a cherry-pick of #6645 to Swift 5.9, to add support for building String Catalogs when using XCBuild as the underlying build system.
rdar://105866061

[5.9] Support String Catalogs when using xcbuild

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/BuildParameters.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/SwiftToolTests.swift

Rather than spreading out the flag addition across the various different targets, we can control the flags at the SwiftTool level, driving the necessary flag addition at a single site.  This would allow easier management of the flags as we can see the additions uniformly applied.
The test changes alter the expectations for ordering and additional flags being applied for various compilation cases.

Build: centralise the debug information flag handling

---

Tests/BasicsTests/FileSystem/PathShimTests.swift

Windows does not provide the system directory structure as Unices.  Add a simple test case adjustment to enumerate 2 of the expected directories in `%SystemRoot%`.

Tests: adjust the WalkPath test for Windows

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

Looks like we have been using the full relative path from the target directory as basis for object file paths until now which seems odd and might also cause clashes with other files in the build directory. We should be using the basename here since duplicated basenames in the same Swift module are anyway prohibited.
resolves #6672

Do not store Swift object files in subdirectories

---

Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/SwiftSDKBundle.swift
Sources/PackageModel/SwiftSDKConfigurationStore.swift
Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Sources/SwiftSDKTool/RemoveSwiftSDK.swift
Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageModelTests/DestinationTests.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

Introduced `SwiftSDKMetadataV4` type that uses `targetTriple` instead of `runTimeTriple`. We're keeping the previous v3 schema for better error handling in case v3 schema ended up being used in the wild during Swift 5.9 development cycle. The plan is to deprecate v3 and earlier schemas in a future change.
`buildTimeTriple` and `runTimeTriple` renamed to `hostTriple` and `targetTriple` across the codebase, "destination" renamed to "Swift SDK" where possible without a broader disruption. Full renaming of the `Destination` type to `SwiftSDK` would come in a separate change to reduce the diff for this one.

Update Swift SDK nomenclature

---

Sources/Workspace/Workspace.swift

motivation: code cleanup
changes:
* extract signature validation to a seperate function
* use guards to improve readability

refactor signature handling validations

---

Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift

When defining a custom toolset, a specified librarian shall be given precedence over the platform's librarian.  Use this to repair the toolset test on Windows where `ar` is unavailable.  This test used to succeed due to the leaking of the host tools.

PackageModel: honour `.librarian` for toolsets

---

Sources/Build/LLBuildManifestBuilder.swift

Use target specific build parameters rather than the global ones to define the build target.  This will simplify building multiple variants of the target.

Build: use target properties to define the target

---

Sources/Commands/PackageTools/Update.swift
Sources/PackageGraph/PinsStore.swift
Sources/PackageGraph/PubGrub/ContainerProvider.swift
Sources/PackageGraph/PubGrub/PubGrubDependencyResolver.swift
Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivaiton: nicer code
changes:
* remove uneccesary PinsStore::pins API
* rename PinsStore::pinsMap tp PinsStore::pins

[nfc] cleanup use of pins

---

Sources/PackageLoading/ManifestLoader.swift

Ensure that the path string is escaped when emitting the paths. The VFS paths are serialised as either JSON or YAML, both of which require the path string be escaped.

PackageLoading: enable the manifest VFS on Windows

---

Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/Destination.swift
Sources/PackageModel/SwiftSDKBundle.swift
Sources/PackageModel/SwiftSDKConfigurationStore.swift
Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Sources/SwiftSDKTool/RemoveSwiftSDK.swift
Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
Tests/PackageModelTests/DestinationTests.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6678
Introduced `SwiftSDKMetadataV4` type that uses `targetTriple` instead of `runTimeTriple`. We're keeping the previous v3 schema for better error handling in case v3 schema ended up being used in the wild during Swift 5.9 development cycle. The plan is to deprecate v3 and earlier schemas in a future change.
`buildTimeTriple` and `runTimeTriple` renamed to `hostTriple` and `targetTriple` across the codebase, destinations renamed to Swift SDKs where possible without a broader disruption. Full renaming of the `Destination` type to `SwiftSDK` would come in a separate change to reduce the diff for this one.

[5.9] Update Swift SDK nomenclature

---

Sources/PackageGraph/PackageContainer.swift
Sources/PackageGraph/PubGrub/ContainerProvider.swift
Sources/SPMTestSupport/MockPackageContainer.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/RepositoryManager.swift
Sources/Workspace/ResolverPrecomputationProvider.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/SourceControlTests/GitRepositoryTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift

motivation: improve performance
changes:
* instead of binary update flag, use a strategy that takes into account the version
* implement the update strategy for source control based dependency
* update call sites and tests

optimize repository updates

---

Package.swift

Windows does not have pkg-config by default.  Since the nuget support is still incomplete, prefer to simply disregard the pkg-config spec on Windows.

build: silence a pkg-config warning on Windows

---

Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/BuildParameters.swift
Tests/CommandsTests/SwiftToolTests.swift

Windows does not have a reliable way to strip the binary as stripping is not an operation that MSVC ever performs (PDBs are always externalised and have support for private and public symbols).  This allows us to have builds in release mode which do not embed debug information which would then need to be extricated.

CoreCommands: support `-debug-info-format none` for Windows

---

Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/RegistryConfiguration.swift
Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Tests/CommandsTests/PackageRegistryToolTests.swift
Tests/PackageRegistryTests/RegistryConfigurationTests.swift

(Same as #6711 but for 5.9.)
When using a registry URL that contains a port, ensure the port is preserved when computing the login URL.
Currently if you run the following
```
swift package-registry set https://packages.example.com:8081
swift package-registry login --token XYZ
```
You might get something like 
```
Error: Unable to connect to server: https://packages.example.com
```
That's because the login url is built like this and ignores the port: `URL(string: "https://\(host)\(loginAPIPath ?? "/login")")`
- Use `URLComponents` to build the login URL (which maintains the port)
- Update RegistryConfiguration to compute the storage key
SPM can use registry URLs with ports.

[5.9] Preserve port when computing the login URL

---

Sources/Basics/Triple.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/Commands/PackageTools/PluginCommand.swift
Sources/Commands/Utilities/PluginDelegate.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/SPMBuildCore/BinaryTarget+Extensions.swift
Sources/SPMBuildCore/BuildParameters.swift
Sources/SPMBuildCore/BuildSystem.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/ModuleAliasingBuildTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6438 required by https://github.com/apple/swift-package-manager/pull/6709.
Adds preliminary knowledge of `armv7em` and no OS environments to SwiftPM. Future diffs will be required to fully support these triples. This change allows a `armv7em-apple-none-macho` build via Swift SDK v3 and v4 bundles to make it further through SwiftPM.

[5.9] Enable armv7em CPU and none OS triples

---

Utilities/bootstrap

CMake under various conditions will attempt to use `llvm-ar` and `llvm-ranlib` when it spots that we're building using `clang`, and while that works fine on Linux, it doesn't work so well on Darwin, leaving us with a link failure with a perplexing error message.
The rest of the Swift build is resilient to this problem already, but the `bootstrap` script here doesn't pass the relevant options to CMake, so it's possible to end up with the build failing when trying to link `lib/libCYaml.a` after the build has mangled the static library with `llvm-ranlib`.
rdar://112478653

Fix CMake build to explicitly pick up ar and ranlib from toolchain.

---

Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
Sources/Build/BuildPlan.swift

While fixing this, I also noticed the original issue also exists for executable targets, so this gets fixed here as well.
There's one unfortunate nuance here for test targets since using a macro/plugin is indistinguishable from needing to link it because it is being tested. We err on the side of caution here and will always link.
(sidenote: theoretically, plugins *do* distinguish between linkage and use in the package manifest, but this distinction is not carried forward into the actual model)
Partially fixes https://github.com/apple/swift/issues/67371 since the underlying project also does not declare a dependency on the macro that is being tested.

Fix issues with excluding macros/plugins from dependency computation

---

Sources/SourceControl/GitRepository.swift

My search/replace for `GitURL` was a bit overeager and changed this as well.

Restore `RepositorySpecifier.Location.gitURL`

---

Sources/Basics/Triple.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/PackageModel/UserToolchain.swift
Sources/SPMBuildCore/BuildParameters.swift
Tests/BasicsTests/TripleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6478.
Fixes a bug where all triples with vendor `apple` are considered to be OS variants of `darwin`. This change special cases `apple-none` to not match `Triple.isDarwin()`, but all other "apple-*" triples will still be considered to be a variant `darwin`.
Fixes some fallout of making the above change to check for the newly added `Triple.isApple()` instead of `Triple.isDarwin()` to allow the triple `apple-none` to opt into behaviors like dead stripping, using libtool, etc.
As a result of these changes SwiftPM no longer appends a macOS version number to the `armv7em-apple-none-macho` triple (e.g. `armv7em-apple-none-macho10.13`) removing the work around of passing `-target armv7em-apple-none-macho` as CLI options or via a …

[5.9] fix `apple` and `darwin` triples disambiguation

---

Sources/SPMTestSupport/GitRepositoryExtensions.swift

If this setting is enabled it can break the tests depending on how the user uses gpg.

Disable tag.gpgsign in test git repos

---

Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
Sources/Build/BuildPlan.swift

While fixing this, I also noticed the original issue also exists for executable targets, so this gets fixed here as well.
There's one unfortunate nuance here for test targets since using a macro/plugin is indistinguishable from needing to link it because it is being tested. We err on the side of caution here and will always link.
(sidenote: theoretically, plugins *do* distinguish between linkage and use in the package manifest, but this distinction is not carried forward into the actual model)
Partially fixes https://github.com/apple/swift/issues/67371 since the underlying project also does not declare a dependency on the macro that is being tested.
(cherry picked from commit b31c19ab3154779fc43b51a560260463c5985fc5)

[5.9] Fix issues with excluding macros/plugins from dependency computation

---

Sources/LLBuildManifest/Tools.swift

Passing both results in noisy remarks when building from the command line like:
```
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
```
https://forums.swift.org/t/incremental-compilation-has-been-disabled-it-is-not-compatible-with-whole-module-optimization/66092

Remove -incremental when using -whole-module-optimization

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/BuildFlags.swift
Sources/PackageModel/UserToolchain.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6475.
Refactors the various compilerArguments and linkerArgument functions slightly to ensure flags from a user's sdk and cli properly propagate to the expected subcommand invocations.
Adds a fairly comprehensive test to cover the toolset and cli flag passing end result.
---
Fixes a bug where clang targets didn't respect the `isCXX` override.
Fixes a bug where cxxCompiler extraCLIFlags where not passed to clang when building cxx targets. Future work: #6491. cxxCompiler extraCLIFlags should also be passed to `swiftc` when compiling swift modules to ensure the clang importer has the same interpretation of the module as the initial compile.
Fixes a bug where linker extraCLIFlags were not passed to `swiftc` prefixed by …

[5.9] Improve handling of tool build flags

---

Sources/Basics/ByteString+Extensions.swift
Sources/Basics/CMakeLists.txt
Sources/Basics/FileSystem/NativePathExtensions.swift
Sources/Basics/Serialization/SerializedJSON.swift
Tests/BasicsTests/Serialization/SerializedJSONTests.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift
Tests/PackageModelTests/SwiftSDKTests.swift
Tests/PackageModelTests/ToolsetTests.swift

Currently we have to call `_nativePathString` manually in a lot of places where `AbsolutePath` is interpolated into strings. We also need to take into account whether `_nativePathString` should be called with `escaped: true` or `escaped: false` arguments, which is prone to errors. The serialization format should carry the knowledge of its correct escaping algorithm, not the path representation itself.
We can make this much cleaner if string interpolations call `_nativePathString` automatically where needed, and serialization formats add proper escaping on top of that.
Let's mplements this for JSON, specifically where it is used in Swift SDKs.
Added `SerializedJSON` type as string literal escaping helper.
Also added a custom `AbsolutePath` interpolation to the new type, which removes the …

Add `SerializedJSON` type as string literal escaping helper

---

Utilities/bootstrap

CMake under various conditions will attempt to use `llvm-ar` and `llvm-ranlib` when it spots that we're building using `clang`, and while that works fine on Linux, it doesn't work so well on Darwin, leaving us with a link failure with a perplexing error message.
The rest of the Swift build is resilient to this problem already, but the `bootstrap` script here doesn't pass the relevant options to CMake, so it's possible to end up with the build failing when trying to link `lib/libCYaml.a` after the build has mangled the static library with `llvm-ranlib`.
rdar://112478653

[5.9] Fix CMake build to explicitly pick up ar and ranlib from toolchain.

---

Sources/Basics/Sandbox.swift
Tests/BasicsTests/SandboxTests.swift

Add the com.apple.lsd.mapdb Mach service to the macOS sandbox
Swift package plugins can't use the Uniform Type Identifier API, such as to get a file's type identifier, because they don't have the right entitlement which is normally provided by the App Sandbox.
Allow looking up the com.apple.lsd.mapdb Mach service in the macOS sandbox.
Swift package plugins are able to use the Uniform Type Identifier APIs.

Package plugins can't use the UniformTypeIdentifiers module

---

Tests/BasicsTests/SandboxTests.swift

testUniformTypeIdentifiers can skip the Array -> String conversion for confstring and use String directly.
I didn't see the string version of unsafeUninitializedCapacity: when I first wrote the unit test.
Use String.init(unsafeUninitializedCapacity:initializingUTF8With:) to skip the Array -> String conversion.
testUniformTypeIdentifiers will be a little cleaner.

Clean up the testUniformTypeIdentifiers unit test

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift

This appears to be a copy-pasta induced error message error where `multiple` was being reported as `missing`.

Build: correct a typo in an error message

---

Sources/Basics/FileSystem/NativePathExtensions.swift
Sources/PackageLoading/ManifestLoader.swift

The path representation uses a relative path (`/relative/paths`) as an absolute path due to limitations of Unix systems.  If the source is located in one root and the manifest is built into another root, the path remains a relative path which will fail to match the VFS entry as the relative path is made absolute by normalizing the path to the current drive as per Windows rules.  This then results in the VFS entry not being honoured and the path fails to be found.  More aggressively perform the path normalization when loading the manifest to resolve this issue.

PackageLoading,Basics: properly handle cross-root manifests

---

Sources/Basics/AuthorizationProvider.swift
Tests/BasicsTests/AuthorizationProviderTests.swift

Motivation:
`KeychainAuthorizationProvider` supports HTTPS only and no port. Credentials for URLs that include port or HTTP URLs stored in Keychain are not found.
Changes:
- Support HTTP
- Use URL port as search criteria

Keychain credentials - better support for protocol and port

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6608.
Fixed a bug where `includeSearchPaths` and `librarySearchPaths` defined in a `swift-sdk.json` file were not properly respected. Updates `UserToolchain` to support these by adding matching properties and updates `SwiftTargetBuildDescription` as well as `ClangTargetBuildDescription` to pass these toolchain search paths to  the compilers and linkers as expected.
(cherry picked from commit 38c5c0537d6a894d4946a49996e1be6fd93358e8)
```
#	Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
#	Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
```

[5.9] Swift SDKs: fix search paths handling

---

Sources/Build/BuildPlan.swift

This option is not parsed by the symbol graph extractor, nor does it materially make a difference to the tool.  Filter out this flag on the SPM side to ensure that we are able to properly run the tool.  This partially enables the use of `swift package dump-symbol-graph` on Windows.

Build: filter `-use-ld=lld` from `swift-symbolgraph-extract`

---

Sources/Basics/Sandbox.swift
Tests/BasicsTests/SandboxTests.swift

Cherry pick of #6731 and #6735 for 5.9

Package plugins can't use the UniformTypeIdentifiers module (#6731)

---

Sources/PackagePlugin/PackageModel.swift
Sources/PackagePlugin/Utilities.swift
Tests/CommandsTests/PackageToolTests.swift

These were missing availability and also are more suited for the `Utilities.swift` file.
resolves #6733

Add availability to source module APIs

---

Sources/PackagePlugin/PackageModel.swift
Sources/PackagePlugin/Utilities.swift
Tests/CommandsTests/PackageToolTests.swift

These were missing availability and also are more suited for the `Utilities.swift` file.
resolves #6733
(cherry picked from commit ef91bfb0410cd2799bddd33cc36f0beebf7f044a)

[5.9] Add availability to source module APIs

---

Sources/PackagePlugin/Plugin.swift

The Windows builds spew warnings about deprecated functions.  Use an overload for the name to avoid the warning and prefer the alternate spellings.

PackagePlugin: avoid warnings on Windows by overloading functions

---

Sources/Basics/AuthorizationProvider.swift

Motivation:
A registry URL (i.e., same scheme, host, and port) can have multiple entries in Keychain. Currently we only ask Keychain to return one match when doing a search, but that might not be the one we want.
Modifications:
- Have Keychain search return all matches
- Sort the matches by modification timestamp
- Return the most recently modified match
rdar://112556752

Keychain search to return all matches

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

fix error: scoped imports are not yet supported in module interfaces import class Foundation.Bundle
When building a dynamic library with `swift build --configuration debug -Xswiftc -emit-module-interface -Xswiftc -enable-library-evolution --disable-sandbox`, this error occurs:
```
DerivedSources/resource_bundle_accessor.swift:1:25: error: scoped imports are not yet supported in module interfaces
import class Foundation.Bundle
```
Change `import class Foundation.Bundle` to `import Foundation`
dynamic library can build success

fix dynamic library building issue 

---

Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift

Some newer versions of XCBuild require a new build setting for opting into generation of the resource accessor.
rdar://112991922

Fix an XCBuild compatibility issue

---

Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift

Some newer versions of XCBuild require a new build setting for opting into generation of the resource accessor.
rdar://112991922
(cherry picked from commit 6478e2724b8bf77856ff358cba5f59a4a62978bf)

[5.9] Fix an XCBuild compatibility issue

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

`self.currentToolsVersion >= manifestToolsVersion` will always be true when using the 999.0 tools-version, so also accept a higher tools-version if we're in development mode.

Fix interpreter flags for manifests using pre-release tools-version

---

Fixtures/Miscellaneous/TestDiscovery/Simple/Package.swift
Fixtures/Miscellaneous/TestDiscovery/Simple/Plugins/SimplePlugin/plugin.swift
Sources/Build/BuildOperation.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/Utilities/PluginDelegate.swift
Sources/Commands/Utilities/TestingSupport.swift
Sources/SPMBuildCore/BuildParameters.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift

Sink `shouldSkipBuilding` down into build parameters, so we can respect it whereever we would be trying to build, e.g. when trying to build plugins during build planning.
resolves #6683

Skip compiling plugins when skipping building

---

Sources/XCBuildSupport/PIFBuilder.swift

Similar to #6752, there was another case where we needed the new setting.
rdar://113157040

Fix another XCBuild compatibility issue

---

Sources/XCBuildSupport/PIFBuilder.swift

Similar to #6752, there was another case where we needed the new setting.
rdar://113157040
(cherry picked from commit 2dceb21867508dd7cf30c87f02faae7c61b0f1f9)

[5.9] Fix another XCBuild compatibility issue

---

Sources/Commands/PackageTools/InstalledPackages.swift

Cleaned up the help message to make it clear what executable products are uninstalled.

Update help message in `InstalledPackages.swift`

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

It doesn't make sense to pass `-framework` on platforms that don't support them and might lead to confusing errors, e.g. some linkers will interpret it as `-f` with an option.
rdar://74600880

Only pass `-framework` on platforms that support frameworks

---

Sources/SourceControl/RepositoryManager.swift
Tests/SourceControlTests/RepositoryManagerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: there is some built-in non-determinism where the graph resolution races and sometime one location variant wins in the location -> identity mapping, this can lead to looking up a different storage path since that does not use the normalized form of the location
changes:
* normalize (canonicalize) the repository location when computing the storage path
rdar://112134161

canonicalize repository lcoation for storage path calculation

---

Sources/PackageFingerprint/FilePackageFingerprintStorage.swift

Motivation:
The fingerprint filename for package coming from a Git repository should take the form of `{PACKAGE_NAME}-{REPOSITORY_URL_HASH}.json`. The `REPOSITORY_URL_HASH` part is to distinguish repository URLs with the same last path component (and therefore same package name). For example: https://github.com/apple/swift-nio
https://github.com/yim-lee/swift-nio
`REPOSITORY_URL_HASH` is computed by converting `hashValue` property of the URL string to hexadecimal, but turns out `hashValue` doesn't yield consistent value across program executions (because random seed is used), and as a result multiple fingerprint files get created for the same (package name, repository URL) pair.
Modification:
Generate consistent hash value to be used for fingerprint filename.
rdar://113540625

Fingerprint filename for the same Git repository is not consistent

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: nicer error message to users when dependencies graph has an unresolvable cycle
changes:
* check for cycle prior to loading top level manifests and produce a nicer error message
* add test

better error message when cycle is detected

---

Sources/Basics/FileSystem/FileSystem+Extensions.swift
Sources/Basics/Sandbox.swift
Sources/Build/BuildOperation.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/Workspace/DefaultPluginScriptRunner.swift
Tests/BasicsTests/SandboxTests.swift

The sandbox profile SwiftPM generates curates the directories plugins and manifests are able to write to. Several Foundation APIs use a so-called "item replacement directory" when doing atomic operations and this happens to be a special path on the same volume when performing operations on an external volume. This lead to those operations being blocked in plugins which does not seem right since those item replacement directories are temporary directories in spirit. We now automatically allow writes for those when generating a sandbox profile.
rdar://112217177

Resolve sandbox issues on external volumes

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

This would allow conditionalizing client code using ``#if canImport(:_version:)`` so that different versions of a dependency can be supported within a single codebase.
Note: this is explicitly not passing the flag if pre-releases are in use to avoid any confusion in those cases.
rdar://107077287

Set `-user-module-version` for any version-based package

---

Sources/Basics/HTTPClient/HTTPClient.swift
Sources/Basics/HTTPClient/LegacyHTTPClient.swift
Tests/BasicsTests/HTTPClientTests.swift
Tests/BasicsTests/LegacyHTTPClientTests.swift

motiavtion: do not send empty authorization headers, even if authorization provider returns empty strings
changes:
* do not send authorization header when the authroization provider returns an empty string
* adjust tests
radar/99133141

filter empty authorization tokens from headers

---

Sources/Commands/PackageTools/PluginCommand.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/Triple+Extensions.swift

When cross-compiling, SwiftPM plugins and their dependencies run on the host and so must be compiled for the host OS and architecture, not the cross-compiled target OS and architecture.   SwiftPM will
compile a command plugin for the host but if the plugin depends on an executable it will cross-compile the executable for the target so the plugin will not be able to run it:
error: Error Domain=NSPOSIXErrorDomain Code=8 "Exec format error"
This problem does not affect `binaryTarget` dependencies, which are handled by a different code path which correctly selects the the binary for the host system from the archive.
Command plugin dependencies are already handled specially in `PluginCommand.run`; this commit makes that special build step use the host toolchain instead of the target toolchain. …

plugins: Build command plugin dependencies for the host, not the target

---

Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/PackageGraph.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/ModuleAliasingBuildTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: diagnostics for multiple products conflicts could be fairly confusing with repeated package identities and not enough informaiton about the origin of the conflict
changes:
* use PackageIdentity to track duplicates instead of strings
* use Sets to track duplicates instead of array
* add information about the origin (url) of the conflict
* adjust tests

improve diagnostics when running into multiple product conflicts

---

Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/BuildSettings.swift
Sources/PackageModel/Manifest/PackageConditionDescription.swift
Sources/PackageModel/Platform.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

In #3742, support for custom platforms was added and I think everyone understood it as supporting custom deployment targets, but it actually also added API for custom platform conditionals. Those never actually worked, though, because any platform that the platform registry doesn't know about was dropped when going from `TargetDescription` to `Target`. This fixes it and adds a unit test.
See also https://github.com/RevenueCat/purchases-ios/issues/2998
rdar://113709387

Support custom platforms in conditionals

---

Sources/Workspace/InitPackage.swift

We need to update this before shipping 5.9
rdar://111618457
Putting this up so we have it ready for when we need it -- we'll also need to cherry-pick this into the 5.9 release branch.

Update swift-syntax version in macro template

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

We are not shipping this in 5.9, so we need to tweak this.

Update tools-version for `-user-module-version`

---

Fixtures/Miscellaneous/CXX17CompilerCrash/v5_8/Package.swift
Fixtures/Miscellaneous/Plugins/PluginsAndSnippets/Package.swift

I fixed these up when we enabled development mode on the branch, but we should have these in main as well.
(cherry picked from commit ad4ffe4250a126156d563fd6024f4ec71dfe4caf)

Bring back test fixes from 5.9 branch

---

Sources/Workspace/InitPackage.swift

We need to update this before shipping 5.9
rdar://111618457
(cherry picked from commit da3bdae70cb21d90f8be89e18d236dabd5854364)

[5.9] Update swift-syntax version in macro template

---

Sources/Commands/PackageTools/PluginCommand.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/Triple+Extensions.swift

When cross-compiling, SwiftPM plugins and their dependencies run on the host and so must be compiled for the host OS and architecture, not the cross-compiled target OS and architecture. SwiftPM will compile a command plugin for the host but if the plugin depends on an executable it will cross-compile the executable for the target, so the plugin will not be able to run it:
error: Error Domain=NSPOSIXErrorDomain Code=8 "Exec format error"
Command plugin dependencies are already handled specially in PluginCommand.run; this commit makes that special build step use the host toolchain instead of the target toolchain.
https://github.com/apple/swift-package-manager/pull/6060 handled the equivalent problem for build tool plugins.
(cherry picked from commit 1daaa1c0339584e50d42f62b5a7794a2e97b5782) …

[5.9] Build command plugin dependencies for the host, not the target

---

Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6688.
When defining a custom toolset, a specified librarian shall be given precedence over the platform's librarian.  Use this to repair the toolset test on Windows where `ar` is unavailable.  This test used to succeed due to the leaking of the host tools.
This fixes a bug reproducible when cross-compiling projects with dependencies to any platform, including Linux.
Risk: low, only affects cross-compilation with SwiftPM, which is not widely used yet.
(cherry picked from commit 4d63d6692978a31ec9ecd1d6c3321ee446b7d577)

[5.9] PackageModel: honour `.librarian` for toolsets

---

Package.swift

The changes in #6807 can actually break in this case, moving the new dependency to the correct place.

Fix dependencies in `SWIFTPM_LLBUILD_FWK` case

---

Sources/swift-bootstrap/main.swift
Utilities/bootstrap

We may want to make `--explicit-target-dependency-import-check` the default at some point, so it would be good to get some more testing in practice. We can opt in SwiftPM's CI itself as a starting point.

Opt in to explicit target dependencies

---

Sources/Basics/AuthorizationProvider.swift
Tests/BasicsTests/AuthorizationProviderTests.swift

Motivation:
We update `netrc` by appending new entry to the end of the file (we don't delete or modify existing entries). This means when we look for entries matching a given host in the `netrc` file, we should use the _last_ match for the most recent entry.
Modification:
Check `netrc` lookup to use `last` instead of `first` match.

[netrc] Use the most recent match for auth

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift
Sources/Workspace/Workspace+Configuration.swift

Motivation:
Certain `package-registry` subcommands, such as `set --global` and `login`, work with user-level `registries.json` only and therefore should not require workspace to run.
Modifications:
In those subcommands, do not read local `registries.json`.
rdar://113875867

CLI commands should not require workspace to update user-level registries config

---

Sources/Commands/CMakeLists.txt

This corrects the missing dependency which happens to work currently due to overlinking.  While trying to improve the support for static linking on Windows, this missing dependency was exposed.

Commands: add missing dependency on LLBuildManifest

---

.swiftpm/xcode/xcshareddata/xcschemes/SwiftPM-Package.xcscheme
xcode/SwiftPM-Package.xctestplan

This adds an explicit test plan and scheme so that we can mark test bundles are parallelizable. It's a little unfortunate that this opts us into manual managing these configs, but the alternative of everyone having to do it locally is even worse.

Make SwiftPM test suite run parallel in Xcode

---

Sources/Commands/Utilities/TestingSupport.swift

* **Explanation**: Removes an old workaround that breaks running tests when there's already a swift on PATH that isn't the swift currently being run.
* **Scope**: `swift test` on Linux platforms
* **Risk**: Low, our tests would fail if this was still needed.
* **Testing**: Toolchain build and test on all Linux platforms.
* **Original PR**:  https://github.com/apple/swift-package-manager/pull/6684

[5.9] Remove extra paths added to LD_LIBRARY_PATH on Linux when running tests

---

Sources/Commands/Utilities/TestingSupport.swift

* **Explanation**: Removes an old workaround that breaks running tests when there's already a swift on PATH that isn't the swift currently being run.
* **Scope**: `swift test` on Linux platforms
* **Risk**: Low, our tests would fail if this was still needed.
* **Testing**: Toolchain build and test on all Linux platforms.
* **Original PR**:  https://github.com/apple/swift-package-manager/pull/6684

[5.8] Remove extra paths added to LD_LIBRARY_PATH on Linux when running tests

---

Sources/Commands/Utilities/TestingSupport.swift

* **Explanation**: Removes an old workaround that breaks running tests when there's already a swift on PATH that isn't the swift currently being run.
* **Scope**: `swift test` on Linux platforms
* **Risk**: Low, our tests would fail if this was still needed.
* **Testing**: Toolchain build and test on all Linux platforms. Manually tested that `swift test` works on a SwiftPM project using a toolchain with this change.
* **Original PR**:  https://github.com/apple/swift-package-manager/pull/6684

[5.9.0] Remove extra paths added to LD_LIBRARY_PATH on Linux when running tests

---

Tests/PackageModelTests/SwiftSDKTests.swift

Adjust the path spelling for the native path arc separator and escaping
for the encoding in the JSON.  Windows uses `\` as the path arc
separator which needs to be escaped for ensuring that the JSON is valid.

Tests: adjust PackageModelTests for Windows

---

Sources/Basics/Triple+Basics.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/SPMBuildCore/BinaryTarget+Extensions.swift
Sources/SPMBuildCore/BuildParameters.swift
Sources/SPMBuildCore/XCFrameworkMetadata.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/SPMBuildCoreTests/XCFrameworkMetadataTests.swift

This PR improves the way that iOS and other non-macOS Darwin triples are handled. Somewhat based on #6572, accounting for the changes since then.
We can't assume that darwin == macOS anymore, necessitating a few changes to handle the other OSes.
- Teach Basics about the file extensions for non-macOS Darwin libraries (.dylib) and executables (none)
- Update the target triple based on the supported platform version for all Darwin platforms, not just macOS (e.g. `.iOS(.v16)` now implies `arm64-apple-ios16`)
- Handle xcframeworks for triples other than {arm64,x86_64}-apple-macosx
iOS/tvOS/watchOS libraries and (xc)frameworks are now better supported.

Improve handling of non-macOS Darwin triples (reprise)

---

Tests/BuildTests/BuildPlanTests.swift

The Windows toolchain does not find the default linker by default as
that requires the sourcing of Visual Studio's scripts to setup the
environment.  Adjust the tests to explicitly specify the linker to
ensure that the toolchain is usable on Windows without constraint on the
environment.  While in the area, adjust the expectations to account for
platform path spellings.  This allows us to pass these tests on Windows
now.
Adjust the path representation to account for Windows to allow the
matching to succeed.

Tests: adjust the BuildPlanTests for Windows

---

Tests/BuildTests/ModuleAliasingBuildTests.swift

The path spelling was incorrect for cross-platform cases.  Adjust the test expectations to use `AbsolutePath` to resolve the spelling differences.

Tests: adjust the ModuleAliasingBuildTests for Windows

---

Sources/PackageGraph/PackageGraph+Loading.swift
Tests/BuildTests/ModuleAliasingBuildTests.swift

When we introduced module aliasing, we tried to paper over the fact that there are no product aliases by changing the lookup under certain conditions. It looks like one of these conditions is "one package in the graph uses aliasing" which breaks if the graph contains any packages with pre-5.2 tools-versions because they lack the information to do a identity based lookup.
This changes opts packages with older tools-versions out of the identity based lookup. This implies that it is not possible to use aliasing in certain situations, but that seems preferrable to not being to use aliasing at all in affected package graphs.
rdar://113506853

Do not use product identifier based lookup for older tools-versions

---

Tests/PackageGraphTests/PackageGraphTests.swift

Tweak the expectations to account for the path component separator on Windows.  This improves the test coverage on Windows.

Tests: adjust the tests for path spellings

---

Sources/PackageLoading/ToolsVersionParser.swift
Sources/PackageModel/ToolsVersion.swift
Tests/PackageLoadingTests/ToolsVersionParserTests.swift

Currently, we only pick a non-exact match for version-specific manifests if its tools-version is *higher* than the regular one. That seems like an edge case only and we should *also* pick it if the regular manifest is incompatible. This both matches intuition as well as our current documentation on the topic. It should also be backwards-compatible with the current behavior since the new behavior only comes into play if we would have previously failed to load a manifest at all.

Improve version-specific manifest selection

---

.mailmap
Sources/Build/BuildDescription/ProductBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

Cherrypick of #6824
__Explanation:__ This host-specific toolchain directory was added years ago in #2035 to the list of library directories, but it can cause problems when cross-compiling.
__Scope:__ Right now, nothing is placed in this directory, so remove it before it can cause problems.
__Issue:__ #6767
__Risk:__ low, as nothing relies on it yet
__Testing:__ Passed all CI and I've removed it for my native Android builds of the toolchain for the last four months, without a problem.
__Reviewer:__ @neonichu

[5.9] Remove <toolchain>/usr/bin/../lib/ from directories passed to linker to look up libraries for target triple

---

Sources/Basics/Triple+Basics.swift
Sources/Basics/Vendor/Triple+Platforms.swift
Sources/Basics/Vendor/Triple.swift
Tests/BasicsTests/TripleTests.swift
Utilities/soundness.sh

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6842.
Vendored Swift Driver triple was not checked against a few tests that weren't brought over from TSC after `TSC.Triple` type was deprecated. We should fix those tests, especially as they verified that per-component equality for triples worked instead of the current string-based equality check.
Also fixed some of the `Utilities/soundness.sh` script failures.
(cherry picked from commit cfb7836192d1f59ca0fc28618dd296fd749e9bb8)

[5.9] Add and fix missing Triple tests, fix soundness checks

---

Tests/BasicsTests/Serialization/SerializedJSONTests.swift

The extra Windows specific test cases did not account for the path normalization that occurs as part of the `AbsolutePath` construction. Alter the expectations to match that.  Additionally, on Windows, the `/test\\backslash` path would be normalized to `\test\backslash`.

Tests: adjust the SerializedJSONTests on Windows

---

Sources/Workspace/Workspace.swift

We should rely on the resolved file being accurate for branch dependencies as well since we will not update the revision outside of `swift package update` anyway.

Rely on resolved revision for branch dependencies

---

Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift

Windows spells paths with `\` as the path arc separator rather than `/`. Adjust the expectations to account for this.

Tests: adjust the expectations for Windows

---

Sources/Commands/PackageTools/ArchiveSource.swift
Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/RepositoryManager.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift

motivation: better perforamnce
changes:
* GitRepositoryProvider caches GitRepository
* change order of perations such that when a valid revision is found we do not check for validity of git directory
* check if gitsubmodules are used instead of blindly trying to update them

reduce redundant git operations

---

CHANGELOG.md

motivation: improve CHANGELOG.md
changes:
* add missing features introduced in 5.9
* reorder list chronologically

Update CHANGELOG.md to reflect 5.9 scope

---

Sources/CoreCommands/SwiftTool.swift

- Always pass a `hostTriple` when constructing `BuildParameters`, we know it
- `hostSwiftSDK == swiftSDK` was never true because of minor difference related to option parsing
- Use already computed triple from `hostToolchain()` instead of recomputing
In the common case, this brings us back to a single call to `-print-target-info` which is somewhat expensive.
rdar://114095512

Reduce calls to `getHostTriple()`

---

Sources/Commands/PackageTools/PluginCommand.swift

Printing the list needs to continue beyond the first non-command plugin.
resolves #6804

Fix `swift package plugin --list`

---

Sources/Basics/Triple+Basics.swift
Sources/PackageModel/SwiftSDKBundle.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6819.
When setting host triple in Swift SDKs to `arm64-apple-macosx13.0` to allow cross-compiling from an older version of macOS, this triple is not recognized as directly matching `arm64-apple-macosx14.0` on a newer version of macOS.
We should support backward compatibility with Swift SDKs that were built for older version of macOS.
(cherry picked from commit 82b1e83728092ff82a1941248410832086b6c88a)
```
#	Sources/PackageModel/SwiftSDKBundle.swift
#	Tests/PackageModelTests/SwiftSDKBundleTests.swift
```
Resolves rdar://113967401.

[5.9] Fix backward compatibility in host triple checks

---

Package.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/LLBuildManifest/ManifestWriter.swift
Sources/LLBuildManifest/Tools.swift
Sources/SPMTestSupport/SwiftPMProduct.swift
Sources/dummy-swiftc/main.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/BuildToolTests.swift

The changes in #6585 meant that we are no longer using LLBuild's built-in tracking of Swift compiler versions. We are lacking the infrastructure to really use that for the same purpose since we are now running the Swift compiler as a shell-tool, so this is adding a poor man's version of that.
We have a task that writes the output of `swift -version` for a particular Swift compiler path to the build directory and all Swift tasks that are using that compiler depend on that file as an input. This should give us the desired behavior of the tasks re-running if the Swift version changes.
rdar://114047018

Implement `swift-get-version` in SwiftPM

---

Sources/Basics/Triple+Basics.swift
Tests/BasicsTests/TripleTests.swift

Preserve the `environmentName` part of triples when altering the OS version with `Triple.tripleString(forPlatformVersion:)`
Building for the iOS simulator (and presumably anything other triple with a fourth component) would fail because we would generate the wrong swiftc/clang `-target`, incorrectly excluding the `Triple.environmentName`.
- Modify `tripleString(forPlatformVersion:)` to include `self.environmentName` if it is non-empty.
You can now build for the iOS simulator with
```shell
swift build --triple arm64-apple-ios-simulator --sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)"
```
or if you also pull #6828, just
```shell
swift build --triple arm64-apple-ios-simulator
```

Preserve environment in `tripleString(forPlatformVersion:)`

---

Sources/Commands/SwiftTestTool.swift
Sources/Commands/Utilities/TestingSupport.swift

We should include as much context as possible here to allow users to debug issues like that. One well-known way to run into this is that on non-Darwin, we just execute test executables with `--dump-tests-json` and parse all of their `stdout` as JSON, so if the executable has any output of its own for whatever reason, there would be just a very non-descript `malformed` error emitted to the console.

Improve handling of broken JSON responses from XCTest helpers

---

Sources/Commands/ToolWorkspaceDelegate.swift
Sources/CoreCommands/SwiftTool.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/Workspace/Workspace+Configuration.swift
Sources/Workspace/Workspace.swift
Tests/PackageLoadingTests/PDLoadingTests.swift
Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Tests/PackageLoadingTests/PD_5_7_LoadingTests.swift

motivation: better visibility for performance data
changes:
* expand manifest loader delegate
* wire up the manifest loader delegate to the workspace one
* output performance info
* use weak reference over unowned in delegates since we do not control their lifetime
* rename configuraiton argument to make it more expressive

add performance probes for manifest loading

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

Users can write a function called `fatalError` themselves, we should be resilient against that.
resolves https://github.com/apple/swift/issues/68105
resolves #6846

Qualify use of `fatalError` with `Swift`

---

Sources/dummy-swiftc/main.swift

This fallback was a leftover from earlier development, but should be removed now since it isn't very portable as-is and isn't needed for the currently existing tests.

Remove fallback in `dummy-swiftc`

---

Tests/SPMBuildCoreTests/PluginInvocationTests.swift

The file system on Windows does not have nanosecond granularity (nor is this is a guaranteed file system feature on all file systems).  Add a sleep before the execution to ensure that we have sufficient precision to read a difference.

Tests: adjust SPMBuildCoreTests for Windows

---

Sources/Build/LLBuildManifestBuilder.swift

Remove unused parameter from method signature
Noticed this while working on https://github.com/apple/swift-package-manager/pull/5919.
It looks like it's been unused since at least 2020 (https://github.com/apple/swift-package-manager/commit/1f1e909013bd2886ac86acd8ed8d5e219a953e82)
Remove unused `objectNodes` parameter from private `addSwiftCmdsViaIntegratedDriver` method
NFC. Just minor code cleanup.

[NFC] Remove unused parameter from pvt. method in `LLBuildManifestBuilder.swift`

---

Sources/Basics/FileSystem/AbsolutePath.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildOperation.swift
Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
Sources/PackageGraph/GraphLoadingNode.swift
Sources/PackageGraph/ModuleAliasTracker.swift
Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageGraph/PackageModel+Extensions.swift
Sources/PackageModel/Manifest/Manifest.swift
Sources/SPMBuildCore/Triple+Extensions.swift
Sources/Workspace/Workspace.swift
Sources/swift-bootstrap/main.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalPerformanceTests/BuildPerfTests.swift
Tests/FunctionalTests/CFamilyTargetTests.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
Tests/FunctionalTests/ModuleMapTests.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Tests/WorkspaceTests/InitTests.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Utilities/soundness.sh

motivation: better performance
changes:
* cache manifest dependencies and target computations
* change several functions that return static data to computed properties

small perfromance fixes

---

Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/PackageGraph.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: when a package dependency appears in the graph multiple times, the URL which is eventually chosen depends on the closure resolution order which can result in non-determinstic behavior across changes (eg after swift package update) leading to redundant changes to pacakge.resolved
changes:
* when encountering package dependenices with the same identity but different URL, use a detrminstic sort to decide which variant is prefered
* change a functions to computed properties and loadable results so they are better cached
rdar://112266422

make preference of dependency URL more deterministic

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/BuildPlan.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/Commands/CMakeLists.txt
Sources/Commands/SwiftTestTool.swift
Sources/Commands/Utilities/PluginDelegate.swift
Sources/Commands/Utilities/TestingSupport.swift
Sources/Commands/Utilities/XCTEvents.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/SPMBuildCore/BuildParameters.swift
Sources/SPMBuildCore/BuiltTestProduct.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift

Our current test output is not very readable. This adds an experimental feature for using `XCTestObservation` to print a summary after test execution is done.
rdar://113415965

Add experimental test output

---

IntegrationTests/Package.swift

Not sure why this is only becoming visible now, it seems like this should have been needed since https://github.com/apple/swift-tools-support-core/commit/be6f39691456b6be2a030db22df02173de56ca35

Fix `platforms` declaration in `IntegrationTests` package

---

Sources/Build/BuildPlan.swift

A previous problem here was fixed in #6723, this new fix is attempting to resolve issues where macros are used transitively by a product that a test is depending on. It seems to me that those transitively available macros should not be statically linked into tests and in fact doing so can cause various issues such as linker errors on non-Darwin platforms.
It does feel like eventually we need to get away from `computeDependencies(of:)` being a computation on the entire package graph and instead let each package produce separate products which we can then just use transitively, but that is a much bigger change to SwiftPM's build system.
rdar://115071012

Fix testable executables once more

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/ResolvedProduct.swift
Sources/PackageModel/MinimumDeploymentTarget.swift
Sources/PackageModel/Platform.swift
Sources/SPMTestSupport/PackageGraphTester.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphTests/TargetTests.swift

We never need this for any platform that we're not building for and we also don't really need it for most commands. So we can just move the computation to `SwiftTool` and leave these empty for all other cases.
rdar://64596106

Reduce XCTest minimum deployment target computation

---

Sources/Build/BuildPlan.swift

A previous problem here was fixed in #6723, this new fix is attempting to resolve issues where macros are used transitively by a product that a test is depending on. It seems to me that those transitively available macros should not be statically linked into tests and in fact doing so can cause various issues such as linker errors on non-Darwin platforms.
It does feel like eventually we need to get away from `computeDependencies(of:)` being a computation on the entire package graph and instead let each package produce separate products which we can then just use transitively, but that is a much bigger change to SwiftPM's build system.
rdar://115071012
(cherry picked from commit 00a64dfb4924a2e167d8e91c390b8563bf3d9e79)

[5.9] Fix testable executables once more

---

Package.swift
Sources/SPMTestSupport/Toolchain.swift
Tests/BuildTests/IncrementalBuildTests.swift

This is another set of tests that requires a fully functioning SDK on macOS, so they should be skipped based on `SWIFTCI_DISABLE_SDK_DEPENDENT_TESTS`.

Disable `IncrementalBuildTests` in unsupported environments

---

Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
Tests/PackageGraphTests/PubgrubTests.swift

There's an unfortunate interaction here with the resolver precomputation / `LocalPackageContainer` which leads to us rejecting versions as "not available" if they don't happen to be the currently checked out version. We need a more hollistic change to resolve this issue which is out of scope for 5.9, so we'll revert this change here.
rdar://115303494
(cherry picked from commit 87d65e3da6a128b87f105f579caa58e509962617)

Revert "missing pinned version" change for 5.10

---

Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageLoading/ManifestJSONParser.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/CMakeLists.txt
Sources/PackageModel/DependencyMapper.swift
Sources/SPMTestSupport/MockManifestLoader.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/SPMTestSupport/misc.swift
Sources/Workspace/FileSystemPackageContainer.swift
Sources/Workspace/RegistryPackageContainer.swift
Sources/Workspace/SourceControlPackageContainer.swift
Sources/Workspace/Workspace.swift
Sources/swift-bootstrap/main.swift
Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

We weren't applying mirros to root dependencies so far.
rdar://110869499

Apply mirrors to root dependencies

---

Sources/PackageDescription/PackageDependency.swift

`.upToNextMajor` and `.upToNextMinor` need a `from` argument, but it was missing in the comments.
While I was modifying a `Package.swift` file, I noticed that the comments for `.upToNextMajor` and `.upToNextMinor` were missing the `from` argument. So, I'd like to fix that.

Fix missing `from` arguments in PackageDependency's comments

---

Sources/PackageDescription/Product.swift

There is an issue with the API documentation not rendering correctly due to unnecessary vertical spacing.
As you can see, the description for the "target" parameter is in an incorrect section.
I removed the vertical spacing between the parameters' descriptions

Update Product.swift to render the api description correctly

---

Sources/Commands/SwiftTestTool.swift

This option is only useful when in cases where SwiftPM offers more than a single test product. Currently that requires either using XCBuild or a multi-root data file which are both hidden and experimental, so this option should be hidden, too, in order to not confuse users.
It could be interesting to investigate changing the build model so that we would always build a test product per test target and if that happens we could publicize this option again.

Hide `--test-product` option

---

README.md

Swift Forums are supposed to be mentioned instead, as the mailing list has been retired.

Remove mailing list mention in `README.md`

---

Sources/Commands/SwiftTestTool.swift

This can currently lead to bogus output like
```
error: terminated(1): /Users/neonacho/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-profdata merge -sparse -o /Users/neonacho/Desktop/lunch7/.build/arm64-apple-macosx/debug/codecov/default.profdata output:
error: no input files specified. See llvm-profdata merge -help
```
I would also think even if it succeeded, it could result in incorrect data.
rdar://115436056

Do not process code coverage when tests failed

---

Sources/SPMBuildCore/PluginInvocation.swift

Currently, we're only invoking build tool plugins for reachable targets which does not seem correct based on the fact that we're willing to build targets out of reachable, e.g. when executing a command plugin.
rdar://113264168

Invoke build tool plugins based on `allTargets`

---

Sources/SPMBuildCore/BuildParameters.swift

We now the triple here, so we shouldn't have it be recomputed from scratch.

Avoid host triple computation in `BuildParameters.forTriple()`

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/PackageModel/UserToolchain.swift

This takes a significant amount of time when the selected Xcode doesn't have a `swift-plugin-server` executable:
```
/tmp/exec
❯ time /usr/bin/xcrun --find swift-plugin-server
xcrun: error: sh -c '/Users/neonacho/Downloads/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Users/neonacho/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -find swift-plugin-server 2> /dev/null' failed with exit code 17664: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "swift-plugin-server", not a developer tool or in PATH
/usr/bin/xcrun --find swift-plugin-server  0.34s user 0.17s system 32% cpu 1.579 total
```
Doing this on demand is at least gated on `self.buildParameters.toolchain.isSwiftDevelopmentToolchain` so it shouldn't …

Compute path to `swift-plugin-server` on demand

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/PackageModel/UserToolchain.swift

This takes a significant amount of time when the selected Xcode doesn't have a `swift-plugin-server` executable:
```
/tmp/exec
❯ time /usr/bin/xcrun --find swift-plugin-server
xcrun: error: sh -c '/Users/neonacho/Downloads/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Users/neonacho/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -find swift-plugin-server 2> /dev/null' failed with exit code 17664: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "swift-plugin-server", not a developer tool or in PATH
/usr/bin/xcrun --find swift-plugin-server  0.34s user 0.17s system 32% cpu 1.579 total
```
Doing this on demand is at least gated on `self.buildParameters.toolchain.isSwiftDevelopmentToolchain` so it shouldn't …

[5.9] Compute path to `swift-plugin-server` on demand

---

Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/PackageGraph.swift
Tests/PackageGraphTests/PackageGraphTests.swift

Update error message when there's a package target with a similar name as the one provided in the dependency.
Partially addresses https://github.com/apple/swift-package-manager/issues/4803.
It adds a suggestion for an alternative dependency name when there's a dependency target with similar name as the one provided in the `Package.swift`.
Use the existing `bestMatch(for, from)` from TSCBasic to compare the `productRef.name` and `allTargetNames`. 
However, I'm not sure how and if I can include target from system packages. 
Error messages for package target not found may also suggest an alternative name like: 
`product 'Barx' required by package 'foo' target 'FooTarget' not found. Did you mean 'Bar'?`

Refine error message with package name suggestion

---

Sources/SPMBuildCore/BuildParameters.swift

We know the triple here, so we shouldn't have to recompute from scratch.
(cherry picked from commit 389edb717478e7fc7963eccdc338463321407e75)

[5.9] Avoid host triple computation in `BuildParameters.forTriple()`

---

Sources/SwiftSDKTool/Configuration/ConfigureSwiftSDK.swift
Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Sources/SwiftSDKTool/SwiftSDKSubcommand.swift

Not all of the help strings were updated to use "Swift SDK" instead of "cross-compilation destination" after SE-0387 was accepted.
rdar://115680101

Fix remaining mentions of "cross-compilation destinations"

---

Sources/PackageModel/SwiftSDK.swift
Sources/PackageModel/SwiftSDKBundle.swift
Sources/PackageModel/UserToolchain.swift
Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Sources/SwiftSDKTool/README.md
Sources/SwiftSDKTool/RemoveSwiftSDK.swift
Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageModelTests/PackageModelTests.swift
Tests/PackageModelTests/SwiftSDKTests.swift

Cherry-pick of #6927.
While user-visible strings were cleaned up separately in https://github.com/apple/swift-package-manager/pull/6918, there are still uses of "destinations" left in variable/function naming and comments. Let's clean those up too.

[5.10] Rename "destination" to "Swift SDK" in comments and code

---

Sources/SwiftSDKTool/Configuration/ConfigureSwiftSDK.swift
Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Sources/SwiftSDKTool/SwiftSDKSubcommand.swift

Cherry-pick of #6918.
Not all of the help strings were updated to use "Swift SDK" instead of "cross-compilation destination" after SE-0387 was accepted.
rdar://115680101

[5.10] Fix remaining mentions of "cross-compilation destinations"

---

Sources/Basics/Triple+Basics.swift
Sources/PackageModel/SwiftSDKBundle.swift
Tests/BasicsTests/TripleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6819.
When setting host triple in Swift SDKs to `arm64-apple-macosx13.0` to allow cross-compiling from an older version of macOS, this triple is not recognized as directly matching `arm64-apple-macosx14.0` on a newer version of macOS.
We should support backward compatibility with Swift SDKs that were built for older version of macOS.
Resolves rdar://113967401.
```
#	Sources/PackageModel/SwiftSDKBundle.swift
```

[5.10] Fix backward compatibility in host triple checks

---

Sources/Basics/Sandbox.swift
Sources/Build/BuildOperation.swift
Sources/Build/LLBuildManifestBuilder.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/Workspace/DefaultPluginScriptRunner.swift
Tests/BasicsTests/SandboxTests.swift

The sandbox profile SwiftPM generates curates the directories plugins and manifests are able to write to. Several Foundation APIs use a so-called "item replacement directory" when doing atomic operations and this happens to be a special path on the same volume when performing operations on an external volume. This lead to those operations being blocked in plugins which does not seem right since those item replacement directories are temporary directories in spirit. We now automatically allow writes for those when generating a sandbox profile.
rdar://112217177

[5.9] Resolve sandbox issues on external volumes

---

Sources/PackageModel/SwiftSDK.swift
Sources/PackageModel/SwiftSDKBundle.swift
Sources/PackageModel/UserToolchain.swift
Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Sources/SwiftSDKTool/README.md
Sources/SwiftSDKTool/RemoveSwiftSDK.swift
Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageModelTests/PackageModelTests.swift
Tests/PackageModelTests/SwiftSDKTests.swift

While user-visible strings were cleaned up separately in https://github.com/apple/swift-package-manager/pull/6918, there are still uses of "destinations" left in variable/function naming and comments. Let's clean those up too.

Rename "destination" to "Swift SDK" in comments and code

---

Sources/PackageDescription/PackageDependency.swift

These were public for implementation reasons, likely because of how the old serialization code worked which I refactored in 5.9
fixes #6911

Package-level `moduleAliases` should be internal

---

Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift

This PR implements support for the `linker.path` field in the Swift SDK toolset spec.
Depends on https://github.com/apple/swift/pull/68495 and https://github.com/apple/swift-driver/pull/1441.
This field was previously parsed but not respected.
Add `-ld-path=\(linker.path)` to the toolchain's Swift flags if a linker path override is supplied
The linker path is now respected.

Swift SDKs: fix `toolset.linker.path` not passed to `-ld-path`

---

Sources/PackagePlugin/Plugin.swift
Sources/Workspace/DefaultPluginScriptRunner.swift

This is the potential source of a crash on x86_64 using the rebranch branch of Swift.
rdar://115675736

load => loadUnaligned

---

Sources/SPMTestSupport/Toolchain.swift
Tests/FunctionalTests/MiscellaneousTests.swift

I filed an issue about this separately, but in the meantime we need a way to get to passing tests.

Skip tests which need `-suppress-warnings` to work if it doesn't work

---

Sources/Basics/Triple+Basics.swift
Sources/PackageModel/SwiftSDKBundle.swift
Tests/BasicsTests/TripleTests.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

When setting host triple in Swift SDKs to `arm64-apple-macosx13.0` to allow cross-compiling from an older version of macOS, this triple is not recognized as directly matching `arm64-apple-macosx14.0` on a newer version of macOS.
We should support backward compatibility with Swift SDKs that were built for older version of macOS.
Resolves rdar://113967401.

Fix backward compatibility in host triple checks

---

Sources/Basics/Triple+Basics.swift
Sources/Basics/Vendor/Triple+Platforms.swift
Sources/Basics/Vendor/Triple.swift
Tests/BasicsTests/TripleTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6843
Vendored Swift Driver triple was not checked against a few tests that weren't brought over from TSC after `TSC.Triple` type was deprecated. We should fix those tests, especially as they verified that per-component equality for triples worked instead of the current string-based equality check.
(cherry picked from commit 8de70d36ae2b210ff1b505768526621ec4acd4d1)
```
#	Tests/BasicsTests/TripleTests.swift
```
Related to rdar://113967401
May be related to rdar://115731621

[5.10] Add and fix missing `Triple` tests

---

Sources/Build/BuildPlan.swift

This fixes an issue introduced in #6849 and noticed in the cherry-pick to 5.9 in #6886.

Fix XCTest deployment target computation in `BuildPlan`

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildPlan.swift
Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/ResolvedProduct.swift
Sources/PackageModel/MinimumDeploymentTarget.swift
Sources/PackageModel/Platform.swift
Sources/SPMTestSupport/PackageGraphTester.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphTests/TargetTests.swift

We never need this for any platform that we're not building for and we also don't really need it for most commands. So we can just move the computation to SwiftTool and leave these empty for all other cases.
rdar://64596106
(cherry picked from commit 019a6fb4b396a1cb5cb64ef8c0ba02cd580fc14a)

[5.9] Reduce XCTest minimum deployment target computation

---

Sources/PackageModel/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift

This reverts commit d328002c7a255efb79618f7775ee561a6448b469.
This broke existing Swift SDKs:
```
ld.lld: error: unable to find library -ld-path=/Users/neonacho/Library/org.swift.swiftpm/swift-sdks/5.8-RELEASE_rhel_ubi9_aarch64.artifactbundle/5.8-RELEASE_rhel_ubi9_aarch64/aarch64-unknown-linux-gnu/swift.xctoolchain/usr/bin/ld.lld
```

Revert "Swift SDKs: fix `toolset.linker.path` not passed to `-ld-path` (#6719)"

---

Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/A/Package.swift
Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/A/Plugins/A.swift
Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/B/Package.swift
Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/B/Plugins/B.swift
Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Package.swift
Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Sources/main.swift
Sources/Commands/PackageTools/PluginCommand.swift
Sources/Commands/PackageTools/SwiftPackageTool.swift
Tests/CommandsTests/PackageToolTests.swift

This adds a `--package` option to the plugin command which will limit the set of available plugins to those inside a package with the given identity.
The identity is not validated in any way, it will just be applied as a filter on all relevant packages. The option does apply to `--list` as well which seems a bit odd but a consequence of making listing an option rather than a command.
rdar://99887952
Previously:
```
❯ swift-package plugin B --help            
error: 2 plugins found for ‘B’
Usage: swift package <options> <subcommand>
See 'package -help' for more information.
```
Now:
```
❯ swift-package plugin --package B B --help
Hello, World!
```

Support qualifiers for ambiguous plugin commands

---

Package.swift
Utilities/bootstrap

This is currently flagging wrong dependencies, enable it again once it works.
@neonichu, reverting for now as you suggested.

Disable the bootstrap checking for explicit target dependencies and remove wrong llbuild dependency

---

IntegrationTests/Package.swift

This reverts commit ab9581041386e0bd5ccc0acf4251aac378ae55b1.
This shouldn't have been necessary since the automatic raise of test deployment targets should be sufficient here.

Revert "Fix `platforms` declaration in `IntegrationTests` package (#6873)"

---

Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
Tests/PackageGraphTests/PubgrubTests.swift

There's an unfortunate interaction here with the resolver precomputation / `LocalPackageContainer` which leads to us rejecting versions as "not available" if they don't happen to be the currently checked out version. We need a more hollistic change to resolve this issue which is out of scope for 5.9, so we'll revert this change here.
We need to cherry-pick this to main to make the main => 5.10 automerger viable.
(cherry picked from commit 87d65e3da6a128b87f105f579caa58e509962617)

Revert "missing pinned version" change for main

---

Sources/PackageModel/SwiftSDKBundle.swift
Sources/SwiftSDKTool/ListSwiftSDKs.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

With a lot of Swift SDKs installed it's not as easy to navigate through a long unsorted list of strings.

Sort `swift experimental-sdk list` stdout output

---

.gitignore
Sources/Commands/PackageTools/Init.swift
Sources/PackageModel/CMakeLists.txt
Sources/PackageModel/InstalledSwiftPMConfiguration.swift
Sources/PackageModel/Toolchain.swift
Sources/PackageModel/UserToolchain.swift
Sources/SPMTestSupport/misc.swift
Sources/Workspace/InitPackage.swift
Tests/BuildTests/MockBuildTestHelper.swift
Tests/WorkspaceTests/InitTests.swift
Utilities/InstalledSwiftPMConfiguration/Package.swift
Utilities/InstalledSwiftPMConfiguration/Sources/InstalledSwiftPMConfiguration.swift
Utilities/InstalledSwiftPMConfiguration/Sources/exec.swift
Utilities/bootstrap
Utilities/config.json

In 5.9 we're using a version that's hard-coded in the template, but that is annoying to maintain. It also seems like ideally we would be using a version that's aligned with the toolchain that's being used. This adds a new configuration file that we can ship as 'usr/share/pm/config.json' in the toolchain to configure this. There's a fallback to the 5.9 version if we can't find the config and also a way to customize it when instantiating a `UserToolchain` in case a client needs to do that.
rdar://113287350

Read SwiftSyntax version for macro template from a configuration file

---

Sources/Workspace/Workspace.swift

motivation: better diagnostics
changes:
* check for previous errors when updating dependencies and terminate early if core update/checkout dependencies error occurred
* return state changes so that dry run actually works

do not emit "exhausted attempts to resolve the dependencies graph" when previous errors occurred

---

Sources/Build/BuildPlan.swift

In #6726, I discovered that an issue I was fixing for macros and plugins could also apply to executables. That fix was incorrect and would drop legitimate linkage of transitive dependencies when testing executables. The logic here is pretty gnarly, so the most reasonable cause of action seems to be to revert that part of the change.
resolves #6940

Partially revert #6726

---

Sources/Basics/AuthorizationProvider.swift
Sources/Basics/HTTPClient/HTTPClientResponse.swift
Sources/Basics/JSONDecoder+Extensions.swift
Sources/Commands/PackageTools/DumpCommands.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
Sources/PackageCollectionsTool/SwiftPackageCollectionsTool.swift
Sources/PackageDescription/PackageDescription.swift
Sources/PackageLoading/ContextModel.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/BasicsTests/AuthorizationProviderTests.swift
Tests/BasicsTests/HTTPClientTests.swift
Tests/BasicsTests/LegacyHTTPClientTests.swift
Tests/BasicsTests/URLSessionHTTPClientTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/XCBuildSupportTests/PIFTests.swift

change to Non Optional Function from Optional Function
- `String(data:encoding)?` -> `String(decoding:as)`
- `String.data(using)?` -> `Data(String.utf8)`
- remove extra Error

Use non-optional functions for `Data` conversion

---

Documentation/Usage.md

Add a section containing and describing `swift package init --type macro`.
I was looking for the documentation and it wasn't there.
Added the section by copying the Library Package and Executable Package sections' format, showing the command line input and output, describing the output of [InitPackage.swift](https://github.com/apple/swift-package-manager/blob/main/Sources/Workspace/InitPackage.swift) and linking to documentation for the sample macro.
Only one file is changed, which is documentation, so no change in behaviour of Swift Package Manager.

Add "Creating a Macro Package" to `Usage.md`

---

Sources/Build/BuildPlan.swift

In #6726, I discovered that an issue I was fixing for macros and plugins could also apply to executables. That fix was incorrect and would drop legitimate linkage of transitive dependencies when testing executables. The logic here is pretty gnarly, so the most reasonable cause of action seems to be to revert that part of the change.
resolves #6940
(cherry picked from commit 7c1cbeb59a1f2066de1d64c08ceca4c75b135ac4)

[5.9] Partially revert #6726

---

Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: better diagnostics when depdendcy graph fails to resolve. the "exhausted attempts" error message should normally not be encountered, other than in edge cases where the graph is not resolvable. nevertheless, it should be readable by users
changes:
* conslidate the formatting of the "exhausted attempts" error message
* format the "exhausted attempts" more clearly so it is more readable
* update test
rdar://112134269

improve "exhausted attempts" diagnostics

---

Sources/PackagePlugin/Command.swift

Removed misleading and unneeded words; made the doc follow the Swift API Guidelines.
Similar cleanup for prebuildCommand is possible.

Clarify/correct buildCommand docs

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift

This reverts commit 33e05c74e00dc485e55ecdc758ff4e72debf2c52.
We should not make this suggestion without better contextual awareness because it can often be confusing, e.g. when someone is already using a module alias in a case where it isn't supposed to work (see #6841).
If we could find a way to confidently make the suggestion, we could bring it back, but currently it can be more confusing than not.

Revert "Add diagnostics to use module aliasing when duplicate targets found (#5606)"

---

Sources/Commands/PackageTools/Config.swift
Sources/PackageGraph/DependencyMirrors.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/Workspace/Workspace+Configuration.swift
Tests/WorkspaceTests/MirrorsConfigurationTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This appears to be *very* expensive, so we should cache.

Cache `mirrorIndex` in `DependencyMirrors`

---

Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift

motivation: reduce redundant git operations
changes:
* before updating a local checkout, confirm the action is nevessary
* update test to check for revision and not tag

only update local checkout if necessary

---

Sources/Commands/SwiftTestTool.swift

motivation: nicer user experience when terminating tests
changes: filter out logging of signal used when terminating tests normally
radar/113751498

filter out expected signals when logging test crashing

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Commands/SwiftTestTool.swift

As `triple` was deprecated with the recommendation to use explicit `targetTriple` property instead, we should update all of our code to get rid of the remaining deprecation warnings.

[NFC] Build/Commands: fix `triple` property deprecation warnings

---

Sources/PackageGraph/ModuleAliasTracker.swift
Sources/PackageGraph/PackageGraph+Loading.swift

Declaring a module alias for a target that isn't a recursive dependency of the product the alias is being defined for doesn't actually work, instead it gets silently skipped. This adds a diagnostic for this case.
I don't know if this scenario *should* work, but it doesn't in practice, so even if it is supposed to, a diagnostic seems better than nothing.
Separately, it seems problematic that the `duplicateModule` diagnostic contains a completely context-free suggestion to use module aliases. This leads to the very confusing outcome that it is being suggested in this particular case which cannot be resolved using a module alias.
rdar://114200576

Diagnose invalid module alias

---

Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/Repository.swift
Sources/SourceControl/RepositoryManager.swift
Sources/Workspace/Workspace.swift
Tests/SourceControlTests/GitRepositoryTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

motivation: fix edge cases where checkouts point to the wrong repository
changes:
* update WorkingCheckout::isAlternateObjectStoreValid to take an expected repository path
* create an API on RepositoryManager to make sure the checkout aligns with the locall repository
rdar://112134161

[5.9] improve validation of existing checkouts

---

Sources/XCBuildSupport/XCBuildDelegate.swift

When `XCBuildDelegate` receives a `taskComplete` message, it calls `buildSystem(:didStartCommand:)` of `BuildSystemDelegate`. 
However, it should probably call `buildSystem(:didFinishCommand:)`.
Since there doesn't seem to be any concrete type conforming to `BuildSystemDelegate`, this change doesn't appear to have any impact on the behavior of existing code.

Fix to call `didFinishCommand`

---

.swiftpm/xcode/xcshareddata/xcschemes/SwiftPM-Package.xcscheme
Package.swift
Sources/LLBuildManifest/BuildManifest.swift
Sources/LLBuildManifest/Node.swift
Sources/LLBuildManifest/Tools.swift
Tests/LLBuildManifestTests/LLBuildManifestTests.swift

For enabling backtraces on macOS we need to grant a certain entitlement on executables built with SwiftPM. For that we need to write out a plist file with this entitlement setting.
This new auxiliary file type allows writing an entitlements plist file during the build process.
Related to rdar://112065568.
Added `WriteAuxiliary.EntitlementPlist` with a corresponding test, moved `LLBuildManifestTests` into its own test target that depends only on the `LLBuildManifest` target and few required targets such as `Basics` and test support target.
A corresponding build step can be added to build description and build planning in a subsequent PR.

[NFC] LLBuildManifest: add `WriteAuxiliary.EntitlementPlist`

---

Tests/PackageLoadingTests/PkgConfigAllowlistTests.swift

Use an `AbsolutePath` for the literal representation to allow for the appropriate conversion to apply to the expectation.  This repairs the test failure on Windows.

Tests: adjust tests for Windows path expectations

---

Tests/BuildTests/BuildPlanTests.swift

The content being compared here is the actual file content which is apparently not escaped.  This matches the expectations by explicitly converting the string form of the path rather than the default which escapes it.

Tests: special case deserialisation on Windows

---

Sources/Commands/SwiftTestTool.swift
Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/SwiftSDK.swift

We have been seeing this issue for a while when using SwiftPM from the CommandLineTools package:
```
❯ /usr/bin/xcrun --sdk macosx --show-sdk-platform-path
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```
This changes SwiftPM to handle this gracefully during builds (a warning gets emitted) and to fail properly when running `swift test`.
rdar://107479428

Handle macOS CLT `--show-sdk-platform-path` issues

---

Package.swift
Sources/PackageCollectionsSigning/CertificatePolicy.swift
Sources/PackageCollectionsSigning/X509Extensions.swift
Sources/PackageSigning/VerifierPolicies.swift
Sources/PackageSigning/X509Extensions.swift
Tests/PackageSigningTests/SigningTests.swift

rdar://113969026
rdar://115794818
**This PR requires update-checkout changes**

Update swift-certificates to 1.0.1, swift-crypto to 3.0.0

---

Package.swift
Sources/PackageCollectionsSigning/CertificatePolicy.swift
Sources/PackageCollectionsSigning/X509Extensions.swift
Sources/PackageSigning/VerifierPolicies.swift
Sources/PackageSigning/X509Extensions.swift
Tests/PackageSigningTests/SigningTests.swift

This reverts commit d90d52ee2374785f6fd10b7bb474652093d108df.
Until update-checkout supports this change in 5.10.

[5.10] Revert "Update swift-certificates to 1.0.1, swift-crypto to 3.0.0 (#6949)"

---

Sources/Commands/SwiftTestTool.swift
Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/Destination.swift

We have been seeing this issue for a while when using SwiftPM from the CommandLineTools package:
```
❯ /usr/bin/xcrun --sdk macosx --show-sdk-platform-path
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```
This changes SwiftPM to handle this gracefully during builds (a warning gets emitted) and to fail properly when running `swift test`.
rdar://107479428
(cherry picked from commit 3ab568e1a27ec01c4515caf9475e4460d4f8c15b)

[5.9] Handle macOS CLT `--show-sdk-platform-path` issues

---

IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift

`<<<` operator is deprecated and should be replaced with `.send(_: String)`

[NFC] Fix deprecation in `IntegrationTests/SwiftPMTests.swift`

---

Sources/SPMBuildCore/Plugins/PluginScriptRunner.swift

`exectutable` -> `executable`, `callbackq` -> `callback`

[NFC] Fix typos in `PluginScriptRunner.swift` comments

---

Tests/BuildTests/BuildPlanTests.swift

Use `AbsolutePath` to convert path to a portable spelling.  This repairs some test failures on Windows.

BuildTests: adjust the path rendering for Windows

---

Sources/PackageModel/PackageIdentity.swift
Sources/SourceControl/RepositoryManager.swift
Tests/PackageModelTests/CanonicalPackageLocationTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

In #6780, we switched to using the canonical location of a package for the checkouts paths, but that can lead to mixing up checkouts storage when there has been a legitimate change to locations that isn't reflected in the canonical location (most prominently switching from SSH to HTTPS or vice versa). Because of that, we should undo that change.
rdar://116534183

Do not use canonical location for checkouts

---

Tests/BasicsTests/LegacyHTTPClientTests.swift

The legacy client can block several threads by semaphore and the test case itself blocks a thread per request. The test case waits until all requests go in the middle of the process, but some of requests won't be started due to a lack of available threads on a machine with a few cores. Reducing the number of concurrent requests does not solve the root issue (it ultimately requires lock/wait free implementation and I think it's not worth it just for legacy one), but should be enough to repair CI.

Tests: mitigate progressivity issue in LegacyHTTPClientTests

---

Sources/Commands/SwiftBuildTool.swift

Swift no longer supports Ubuntu 14.04, the latest supported version is 18.04, so this check should no longer be needed.

Remove outdated check for Ubuntu 14.04 and Clang 3.6

---

Sources/Workspace/InitPackage.swift

`swift package init` creates files without a trailing newline, so if you create a git repository when instantiating the template, there is an immediate diff.
Resolves rdar://111333801.

Add trailing newlines consistently in `InitPackage.swift`

---

Sources/Basics/SourceControlURL.swift
Sources/PackageGraph/PubGrub/ContainerProvider.swift
Sources/PackageModel/PackageIdentity.swift
Sources/PackageModel/PackageReference.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace+Manifests.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

motivation: when changing between canonical dependency URLs SwiftPM over-caches and ignores changes in manifest until local cache is deleted. this can lead to auth issues when switching between https and ssh for example
changes:
* take into account URL scheme when comparing dependency locations
* always prefer root dependencies when computing preferred URLs
* clean up call sites that compare dependecy location
* add and expand tests
rdar://105732543

refine location comparison when pre-loading package state from local state

---

Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Since TSC is deprecated, we should avoid redundant imports for its modules and types.

[NFC] Remove unused imports of `TSCUtility.Diagnostics{Engine,}`

---

Sources/PackageModel/InstalledSwiftPMConfiguration.swift
Tests/PackageModelTests/InstalledSwiftPMConfigurationTests.swift

This fixes a regression I believe was introduced in #6774 where the new macro package template has its dependency on swift-syntax expressed as `from: "509.0.0."`, including an unncessary trailing period character. This causes an error reading the manifest.
I have not tested this, but I experienced the bug and from source inspection believe this is likely the issue.
Resolves rdar://117132800

SwiftSyntax version in new macro template has trailing period in dependency version, causing error reading manifest

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift

This function is unused and refers to `Format.asRepeating` from TSC, which itself should be deprecated.
This also removes our single use of `TSCBasic.ByteStreamable` and allows us to deprecate it in TSC.

[NFC] Build: remove unused `TestBuildCommand.indent` function

---

Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Commands/Utilities/DOTManifestSerializer.swift
Sources/LLBuildManifest/CMakeLists.txt
Sources/LLBuildManifest/LLBuildManifest.swift
Sources/LLBuildManifest/LLBuildManifestWriter.swift
Sources/LLBuildManifest/ManifestWriter.swift
Sources/LLBuildManifest/Node.swift
Sources/LLBuildManifest/Tools.swift
Tests/LLBuildManifestTests/LLBuildManifestTests.swift

Dependency of https://github.com/apple/swift-package-manager/pull/7010.
Added per the llbuild documentation at https://github.com/apple/swift-llbuild/blob/a3b8d34be319f1b3ba8de53c434386419dec1f4f/docs/buildsystem.rst#L387 and a corresponding test at https://github.com/apple/swift-llbuild/blob/a3b8d34be319f1b3ba8de53c434386419dec1f4f/tests/BuildSystem/Build/mutable-outputs.llbuild#L66.
Newly introduced attributes are not used anywhere yet in this PR, so technically it is NFC.
I also took the opportunity to get rid of deprecated TSC dependencies in `ManifestWriter.swift`, replacing it with string interpolation instead.

llbuild: Support `is-mutated`/`is-command-timestamp` nodes

---

Tests/PackageModelTests/SwiftSDKBundleTests.swift

This test uses `TSCBasic.Process` which is unavailable on Darwin platforms with the exception of macOS, so we should not attempt to run this test on those platforms.

Conditionalize `testInstallRemote` correctly

---

Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift

Improve diagnostics if `testPackageContextName` fails

---

CHANGELOG.md
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Product.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/BuildParameters/BuildParameters+Debugging.swift
Sources/SPMBuildCore/BuildParameters/BuildParameters.swift
Sources/SPMBuildCore/CMakeLists.txt
Tests/BuildTests/LLBuildManifestBuilderTests.swift
Tests/BuildTests/MockBuildTestHelper.swift
Tests/CommandsTests/BuildToolTests.swift

The new Swift backtracer will only function on macOS if:
1. `SWIFT_BACKTRACE` environment variable has its `enable` option set to `yes` or `tty`, and
2. The program you are running was signed with the `com.apple.security.get-task-allow` entitlement.
Xcode automatically signs all local builds with that entitlement by default; without it the Swift backtracer won't work.
SwiftPM should sign Debug binaries with the entitlement by default. It should also have an _option_ to sign Release binaries with the entitlement, noting that they should not be distributed in that state but that crashes may only manifest in release builds (where the optimizer is fully enabled).
Added new `--enable-get-task-allow-entitlement` and `--disable-get-task-allow-entitlement` CLI flags. Made it enabled by default …

Codesign w/ debugging entitlement for backtraces on macOS

---

Sources/Commands/PackageTools/ArchiveSource.swift
Sources/PackageLoading/ManifestLoader+Validation.swift
Sources/PackageMetadata/PackageMetadata.swift
Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/Repository.swift
Sources/SourceControl/RepositoryManager.swift
Tests/PackageLoadingTests/PDLoadingTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift

Currently, it is impossible to figure out any failures of these, despite them stopping any package operations entirely if they fail. Instead, we should make them throwing and bubble up any errors.
rdar://117442702

`isValidDirectory` and `isValidRefFormat` should be throwing

---

Sources/PackageGraph/PubGrub/ContainerProvider.swift
Sources/PackageModel/PackageIdentity.swift
Sources/PackageModel/PackageReference.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace+Dependencies.swift
Sources/Workspace/Workspace+Manifests.swift
Sources/Workspace/Workspace+Pinning.swift
Tests/WorkspaceTests/WorkspaceTests.swift

I've verified that the reverted commit removes required packages from `Package.resolved` in certain dependency graphs.
This reverts commit 1491d340eb995aa3f5c0950e4587f64014522683.
```
#	Sources/Workspace/Workspace+Manifests.swift
#	Sources/Workspace/Workspace.swift
```
Resolves rdar://117381924.

Revert "refine location comparison when pre-loading package (#7002)"

---

Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift

Following up on feedback to https://github.com/apple/swift-package-manager/pull/7010, it's better to have a single optional boolean flag than two non-optional booleans.
Replaced `var enableGetTaskAllowEntitlement = false` and `var disableGetTaskAllowEntitlement = false` with `var getTaskAllowEntitlement: Bool? = nil`, which has an additional `inversion: .prefixedEnableDisable` configuration.
Code that handles these flags is simpler and easier to read.

[NFC] CoreCommands: simplify `*get-task-allow-entitlement` flags

---

Tests/WorkspaceTests/WorkspaceTests.swift

Rather than using the forced unwrap, use `XCTUnwrap` to allow the test suite to continue in the case of a failure.

Tests: avoid abnormal exit on failure

---

Sources/PackageLoading/ManifestLoader+Validation.swift
Tests/FunctionalTests/MiscellaneousTests.swift

This validation happens unconditionally after parsing a manifest, so even if a dependency may be unused or overidden which is undesirable and unexpected. We need to either provide context or move the validation, but this currently breaks builds in environments where the validation doesn't succeed, so to unblock, we can disable it.
rdar://117330410

Disable branch name validation

---

Sources/PackageGraph/PubGrub/ContainerProvider.swift
Sources/PackageModel/PackageIdentity.swift
Sources/PackageModel/PackageReference.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace+Dependencies.swift
Sources/Workspace/Workspace+Manifests.swift
Sources/Workspace/Workspace+Pinning.swift
Tests/WorkspaceTests/WorkspaceTests.swift

bring back #7002 which was reverted in #7031 and include the fix from #7034

bring back #7002

---

Package.swift
Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Resources.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/CMakeLists.txt
Sources/LLBuildManifest/LLBuildManifest.swift
Sources/PackageLoading/ModuleMapGenerator.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageLoadingTests/ModuleMapGenerationTests.swift

This moves generation of module maps for Clang targets into the build process.

Generate Clang module maps during the build

---

Sources/Commands/Utilities/TestingSupport.swift

Currently, some of our code paths that run test targets don't correctly set the `DYLD_FRAMEWORK_PATH` and `DYLD_LIBRARY_PATH` arguments on macOS. This hasn't been a problem in practice because the XCTest helper tool is able to sort it out for us, but my plan with swift-testing is to run an executable directly (like we do for corelibs-xctest.) That means we'll have a code path that could potentially rely on XCTest or other Apple SDK bits, but which is not calling through the XCTest helper tool.
This change hoists our setting of those arguments to a position where they are always set (on macOS only!) before we run a test target, regardless of build style.

Ensure Xcode SDK paths are set when running test targets.

---

Package.swift
Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Resources.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/LLBuildManifest/CMakeLists.txt
Sources/LLBuildManifest/LLBuildManifest.swift
Sources/PackageLoading/ModuleMapGenerator.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageLoadingTests/ModuleMapGenerationTests.swift

Reverts apple/swift-package-manager#6983
We're seeing errors like
```
fatal error: module map file '/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swiftdriver-macosx-x86_64/x86_64-apple-macosx/release/llbuildBasic.build/module.modulemap' not found
```
on various CI jobs and should revert this to unblock.

Revert "Generate Clang module maps during the build"

---

Sources/Build/BuildPlan/BuildPlan+Test.swift
Sources/PackageGraph/ResolvedProduct.swift

Right now, when we construct the derived test target used on Linux/Windows with corelibs-xctest, we don't preserve the `platforms` property. The toolchain then infers a value for it based on the current OS. Since Swift doesn't currently support versioning on those platforms, the end result is the same.
However, if we want to start using a derived test target with swift-testing on Apple platforms, we need to propagate this information correctly. This PR does that.

Infer properties of derived test target.

---

Tests/FunctionalTests/PluginTests.swift

This test has proven to be flaky, disable it until we can fix it.
rdar://114411011

Disable `testCommandPluginInvocation`

---

Sources/Workspace/Workspace+Manifests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Support additional dependencies in forced resolution mode

---

Sources/Commands/Utilities/TestingSupport.swift

Reverts apple/swift-package-manager#7040
This is very speculative revert at this point since I am unable to reproduce, but since last Wednesday, we have been seeing this issue on the nightly toolchain CI:
```
error: error while executing `/Applications/Xcode.app/Contents/Developer/usr/bin/xctest -XCTest WorkspaceTests.PinsStoreTests/testLoadingSchema2 /Users/ec2-user/jenkins/workspace/oss-swift-package-macos/build/buildbot_osx/swiftpm-macosx-x86_64/apple/Products/Release/WorkspaceTests.xctest`: close error: Bad file descriptor (9)
```
and this change seems to fit in timeline wise and also as it affects testing, so it becomes the most relevant candidate for a speculative revert. The process invocation code hasn't changed in a meaningful way in a long time, so it seems unlikely that the …

Revert "Ensure Xcode SDK paths are set when running test targets."

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift
Sources/SPMBuildCore/BuildParameters.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/MockBuildTestHelper.swift

[5.9] pass -fno-omit-frame-pointer in support of new backtracer (#7042)

---

Sources/XCBuildSupport/PIFBuilder.swift

`Web Assembly` -> `WebAssembly`

[NFC] XCBuildSupport: fix comment typo in `PIFBuilder.swift`

---

Sources/PackageModel/Toolset.swift

Previously the only available initializer allowed creating toolsets from serialized form stored on a file system. This initializer allows creating `Toolset` values directly with given build flags and toolchain binaries directory path, which may be needed by libSwiftPM clients.

PackageModel: make `Toolset.init(toolchainBinDir:buildFlags:)` public

---

Tests/BasicsTests/URLSessionHTTPClientTests.swift

Seems like this tends to be flaky on CI.
rdar://118135091

Skip `testDownloadDefaultAuthenticationSuccess` on CI

---

Sources/PackagePlugin/PackageModel.swift

It's a little perverse that I can't even ask if the `FileList` `isEmpty`—currently I'm doing `.contains(where: {_ in true})` and `RandomAccessCollection` conformance is even simpler to achieve than `Sequence` conformance.  If you really don't want to expose `RandomAccessCollection` conformance to preserve your ability to change the representation arbitrarily, at *least* make it conform to `Collection`, since it is multi-pass.

FileList should conform to Collection

---

Sources/Commands/PackageTools/Update.swift

motivation: consistent behavior between pacakge update and package resolve
changes: do not attempt to load the dependencies graph (which performs additional validations), this means validation is deferred until build is attempted
rdar://113413552

remove graph loading on package update

---

Tests/BuildTests/BuildPlanTests.swift

We're seeing errors like
```
error: Failed to clone repository /private/var/folders/7n/r31lzfjx6556jgc6vg55_cg80000gn/T/Miscellaneous_PackageNameFlag.qKbjHI/barPkg:
fatal: destination path '/private/var/folders/7n/r31lzfjx6556jgc6vg55_cg80000gn/T/Miscellaneous_PackageNameFlag.qKbjHI/appPkg/.build/repositories/barPkg-5f2fb998' already exists and is not an empty directory.
```
on CI that are currently unexplained.

Disable `testPackageNameFlag`

---

Utilities/bootstrap

This reverts commit a38a0b705730851e241411b53293ab2877677d95.
The root cause of the issue was identified to lie outside of SwiftPM, so we can re-enable this.

Revert "Update bootstrap script to disable --parallel for testing by default"

---

Utilities/bootstrap

It sounds as if we shouldn't need this anymore.

Disable CMake bootstrap by default

---

Tests/BuildTests/BuildPlanTests.swift

Escape the path string to match the read content.  This allows this test to pass on Windows improving test coverage.

tests: repair `BuildPlanTests.testSnippets` on Windows

---

Sources/LLBuildManifest/LLBuildManifestWriter.swift
Tests/LLBuildManifestTests/LLBuildManifestTests.swift

sets file-system as device-agnostic in build manifest  
This is the default mode in XCBuild, and allows incremental builds to work across reboots on APFS. It would also likely address https://github.com/apple/swift-package-manager/issues/4651.
sets file-system as device-agnostic in build manifest
Restarting your system (or inode changes) doesn't invoke unnecessary builds
Related to rdar://96403757.

Set `file-system` as `device-agnostic` in build manifest

---

Sources/SourceControl/GitRepository.swift

The contents of a symlink is the path to which it points.  We can simply read the contents as a new path, and use `getEntry` to get the contents of the symbolic link.  This implementation should also fully traverse any path that is a series of symbolic link.  This does allow for a DoS attack by creating a recursive symbolic link cycle (e.g. `a` -> `b` -> `a`).
Fixes: #7081

SourceControl: add basic support for symlinks

---

Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift

This is currently not supported and we should show a proper error message in this case.
Resolves rdar://117908112.

Disallow static linking core libraries in `swift test`

---

Sources/SourceControl/GitRepository.swift

motivation: do not use fatalError (which will crash the program) with no additional information
changes:
* throw InternalError instead of fatalError
* use correct version of AbsolutePath

small cleanup after 7092

---

Sources/PackagePlugin/Plugin.swift

Prefer to use the microsoft recommended function for errno string description conversion. This silences a warning and relies on "safer" alternatives (at least ones which will not use a global shared buffer).

PackagePlugin: silence a deprecation warning on Windows

---

Documentation/README.md

Fix broken link to 'Swift Package Registry Service Specification'

Fix broken link to 'Swift Package Registry Service Specification'

---

Tests/BuildTests/LLBuildManifestBuilderTests.swift
Tests/BuildTests/ModuleAliasingBuildTests.swift

The expectations sort differently on Windows due to the path separator being different. This also impacts the expectations. Adjust the path spellings to use `AbsolutePath(_:)` to get the canonical path spelling for the platform.

Tests: adjust for sorting and path representation

---

Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/Repository.swift
Sources/SourceControl/RepositoryManager.swift
Tests/SourceControlTests/RepositoryManagerTests.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift

motivation: in some edge cases, the local repository may be partially valid (the containing directory is a legit git repo, but the repository directory is not), or otherwise point to a remote different than the one expected
changes:
* validate that the local repository remote aligns with the expected one, not just that the directory is a valid git repo
* refactor validation flow to be more streamlined

validate local repository has the correct remote

---

Sources/Basics/Archiver/Archiver.swift
Sources/Basics/AuthorizationProvider.swift
Sources/Basics/Concurrency/ConcurrencyHelpers.swift
Sources/SPMTestSupport/XCTAssertHelpers.swift
Tests/BasicsTests/Archiver/TarArchiverTests.swift
Tests/BasicsTests/Archiver/UniversalArchiverTests.swift
Tests/BasicsTests/Archiver/ZipArchiverTests.swift
Tests/BasicsTests/AuthorizationProviderTests.swift

Start using async/await in testing
This should start to make easier to adopt async/await by reducing the number non-async callers
1 commit which adds async/await bridges
1 commit which adopts the bridges in a test target (BasicTests)
reduce usage of temp_await

Replace some uses of `temp_await` with `await` in tests

---

Utilities/bootstrap

Reverts apple/swift-package-manager#7089
This is incomplete and needs a significant amount of work to actually do what we want.

Revert "Disable CMake bootstrap by default"

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift

With recent changes linker/compiler errors are silently consumed and don't appear in stdout or stderr.
This reverts commit 4c3549144733d8042a0c08d59938b505431cf12c.
Resolves https://github.com/apple/swift-package-manager/issues/7114.

Revert "Only show command output in verbose mode (#7078)"

---

Sources/Commands/SwiftTestTool.swift

motivation: fix cases where test output is formatted incorrectly due to excessive newline addition
changes: preserve output from test hartness as-is without attempting to remove oradd newlines

improve handling of test output

---

CMakeLists.txt

Swift now requires CMake 3.19.6 to build.  Update the CMake requirement to 3.19 to allow us to simplify the build logic by removing the workarounds for older releases.

build: simplify the build rules with newer CMake

---

Sources/PackageSigning/SigningEntity/PackageSigningEntityStorage.swift
Sources/SPMTestSupport/misc.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift
Tests/PackageSigningTests/SigningTests.swift

Adopt async/await in PackageSigningTests
Continue my efforts to replace temp_await with actual await 
Add async alternatives to PackageSigningEntityStorage
Mark non-async methods noasync
Improve the fixture method to return the result of the body
No temp_await usage in PackageSigningTests

Move PackageSigningTests to async/await

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift

Cherry-pick of #7130.
With recent changes linker/compiler errors are silently consumed and don't appear in stdout or stderr.
This reverts commit 4c3549144733d8042a0c08d59938b505431cf12c.
Resolves https://github.com/apple/swift-package-manager/issues/7114.

[5.10] Revert "Only show command output in verbose mode (#7078)"

---

Sources/XCBuildSupport/XCBuildDelegate.swift
Sources/XCBuildSupport/XCBuildMessage.swift

We want this to be extensible, and so we shouldn't fail when encountering an unknown/future message type.
rdar://118856310

Skip unknown XCBuild message types

---

Sources/Basics/Concurrency/ConcurrencyHelpers.swift
Sources/Basics/FileSystem/TemporaryFile.swift
Sources/PackageRegistry/ChecksumTOFU.swift
Sources/PackageRegistry/RegistryClient.swift
Sources/PackageRegistry/RegistryDownloadsManager.swift
Sources/PackageRegistry/SignatureValidation.swift
Sources/PackageRegistry/SigningEntityTOFU.swift
Sources/PackageSigning/SigningEntity/PackageSigningEntityStorage.swift
Sources/SPMTestSupport/MockPackageSigningEntityStorage.swift
Sources/SPMTestSupport/misc.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageRegistryTests/PackageSigningEntityTOFUTests.swift
Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift
Tests/PackageRegistryTests/RegistryClientTests.swift
Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
Tests/PackageRegistryTests/SignatureValidationTests.swift
Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift
Tests/PackageSigningTests/SigningTests.swift

Move PackageRegistryTests to async/await
To keep moving things from temp_await to actual await
Add async alternatives to registry methods
Mark non-async methods noasync to encourage migration
All, but one use of temp_await is removed from the tests

Async package registry tests

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift

This PR renames the entry point function used by SwiftPM to call into swift-testing such that it does not need to be SPI. By marking it SPI, we unintentionally made it very difficult to use with a toolchain that does not include private module information.
swift-testing will continue to export the old symbol name as used by SwiftPM until this change has firmly landed in toolchains, after which we will remove the old function.
See: https://github.com/apple/swift-testing/pull/141

Rename the swift-testing entry point.

---

Sources/XCBuildSupport/XCBuildDelegate.swift
Sources/XCBuildSupport/XCBuildMessage.swift

We want this to be extensible, and so we shouldn't fail when encountering an unknown/future message type.
rdar://118856310
(cherry picked from commit 6bc77dc745d7075078c9bf073551f0f5671ecd6f)
Same as #7136 from main

[5.10] Skip unknown XCBuild message types

---

Sources/Commands/PackageTools/DumpCommands.swift

We only build a module for executable targets in very limited cases (when a test target depends on it), so we can't generally expect them to be available for dumping their symbol graph.

Fix dump symbol graph target list

---

Sources/Commands/PackageTools/DumpCommands.swift
Sources/Commands/Utilities/SymbolGraphExtract.swift
Tests/CommandsTests/PackageToolTests.swift

We were ignoring exit codes and output here, making the corresponding tests impossible to debug (and probably also making the command hard to use).

Fix error handling for dump symbol graph

---

Documentation/ReleaseNotes/5.9.md

motivation: make sure 5.9 release notes are published
changes:
Document key 5.9 features per https://www.swift.org/blog/swift-5.9-released and https://github.com/apple/swift-package-manager/blob/main/CHANGELOG.md

add 5.9 release notes

---

Sources/Commands/PackageTools/ComputeChecksum.swift
Sources/Commands/ToolWorkspaceDelegate.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/SourceControl/RepositoryManager.swift
Sources/Workspace/Workspace+BinaryArtifacts.swift
Sources/Workspace/Workspace+Configuration.swift
Sources/Workspace/Workspace+Delegation.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

[5.10] cache binary artifact globally

---

Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/Repository.swift
Sources/SourceControl/RepositoryManager.swift
Tests/SourceControlTests/RepositoryManagerTests.swift
Tests/WorkspaceTests/SourceControlPackageContainerTests.swift

[5.10] validate local repository has the correct remote

---

Sources/PackageGraph/GraphLoadingNode.swift
Sources/PackageGraph/PackageGraph+Loading.swift
Sources/Workspace/Workspace+Manifests.swift

`GraphLoadingNode`s in the same graph always use same file system instance, there's no need to store references to it in each node.
Removed `fileSystem` property on `GraphLoadingNode`, as it also simplifies `Equatable` and `Hashable` implementations on this type.
`GraphLoadingNode` is now a true value type, with no need to define `Equatable` and `Hashable` manually on it.

[NFC] Remove unused `fileSystem` from `GraphLoadingNode`

---

Sources/SourceControl/GitRepository.swift
Sources/SourceControl/RepositoryManager.swift

motivation: new git call added does not work with older git clients (eg Centos7)
changes: use "git config --get remote.origin.url" instead of "git remote get-url origin"
```
[root@d6ebe024717b code]# cat /etc/*-release
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
[root@d6ebe024717b code]# git remote get-url origin
error: Unknown subcommand: …
```

adjust git call supported by older git clients

---

Sources/SourceControl/GitRepository.swift
Sources/SourceControl/RepositoryManager.swift

[5.10] adjust git call supported by older git clients

---

Sources/Basics/Concurrency/ConcurrencyHelpers.swift
Sources/PackageCollections/API.swift
Sources/PackageCollections/PackageCollections.swift
Sources/PackageCollections/PackageIndexAndCollections.swift
Sources/PackageCollections/Providers/PackageCollectionProvider.swift
Sources/PackageCollections/Storage/PackageCollectionsSourcesStorage.swift
Sources/PackageCollections/Storage/PackageCollectionsStorage.swift
Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Sources/SPMTestSupport/misc.swift
Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Tests/PackageCollectionsTests/PackageCollectionsSourcesStorageTest.swift
Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
Tests/PackageCollectionsTests/PackageIndexTests.swift

Adopt proper async/await for PackageCollectionsTests 
Move more of the testing to be async/await native to make it easier to migrate to async/await in the core libraries
1 commit that adds an async fixture variant
1 commit that replaces a lot of temp_await
Less than 100 uses of temp_await in the repo

Async package collections tests

---

Sources/Commands/Utilities/PluginDelegate.swift

Doesn't seem likely that symbol graph extraction process exit code was ignored on purpose, especially since `extractSymbolGraph` started returning process execution result recently.
Explicitly checked whether process exit code is 0.
Non-zero exit code from symbol graph extraction process launches are no longer ignored.

Fix ignored symbol graph extraction exit code

---

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/Build/BuildPlan/BuildPlan+Test.swift

This PR removes the empty test discovery target created when running swift-testing-based tests. This target is necessary on ~Linux~ non-Darwin targets when running XCTest-based tests, but since swift-testing performs all its own discovery, it's just overhead there.
Fixed by @neonichu, editorialized here by @grynspan (in case GitHub gets confused about it.)

Remove discovery target in swift-testing case

---

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/BuildPlan/BuildPlan+Test.swift
Sources/LLBuildManifest/Tools.swift
Sources/SPMBuildCore/BuildParameters/BuildParameters.swift
Sources/SPMBuildCore/BuiltTestProduct.swift
Sources/SPMTestSupport/SwiftPMProduct.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/RunToolTests.swift

Currently, SwiftPM is using the same path to build swift-testing and XCTest content. This works about 90% of the time because we only need one or the other at any given moment, but it causes some workflows to fail on Linux because the build system sees the existing build product and assumes the build has already completed, which is incorrect. Darwin doesn't seem to be affected (because the XCTest build product is a bundle rather than an executable.)
This PR selects a different path extension, ".swift-testing", for swift-testing's build product.

Use a different path extension for swift-testing builds

---

CMakeLists.txt

With this tweak, we should be able to build the package in debug mode even on Windows. We always use the release mode DLL form of the C/C++ runtime on Windows and can build the Swift code in Debug or Release mode optimizations.

build: allow building in Debug mode on Windows

---

Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/Resolution/ResolvedTarget.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/BuildSettings.swift
Sources/PackageModel/Manifest/PackageConditionDescription.swift
Sources/PackageModel/Target/Target.swift
Sources/SPMBuildCore/Plugins/PluginInvocation.swift
Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

Unblocks `PackageGraph` value types refactoring in https://github.com/apple/swift-package-manager/pull/7160 and macros cross-compilation fix in https://github.com/apple/swift-package-manager/pull/7118.
Multiple places in our codebase pass around and store `[any PackageConditionProtocol]` arrays of existentials with `FIXME` notes that those should be sets and not arrays.
We also can't convert types containing these arrays to value types with auto-generated `Hashable` conformance, since neither elements of these arrays nor arrays themselves are `Hashable`. Adding `Hashable` requirement to `PackageConditionProtocol` doesn't fix the issue, since existentials of this protocol still wouldn't conform to `Hashable`.
A simple alternative is to create `enum PackageCondition` with cases for each …

[NFC] Replace `PackageConditionProtocol` with `PackageCondition`

---

Fixtures/Miscellaneous/LTO/SwiftAndCTargets/.gitignore
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Package.swift
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/cLib/cLib.c
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/cLib/include/cLib.h
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/exe/main.swift
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/swiftLib/swiftLib.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Tests/FunctionalTests/MiscellaneousTests.swift

Adds a test covering experimental lto mode and fixes a bug where the
lto mode was not passed to the linker.
Fixes #6888

Add test fixture for experimental-lto-mode

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
Sources/Build/BuildPlan/BuildPlan.swift
Sources/Commands/PackageTools/DumpCommands.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
Tests/WorkspaceTests/InitTests.swift
Utilities/bootstrap

While working on #7090, we noticed that any builds of Swift sources will currently find lots of unrelated module maps because of the structure of the build arena. We pass a `-I` to the top-level of the arena which leads to *everything* being recursively searched for modules, so the compiler will find module maps that aren't intended to be included at all.
Changing this so that the search paths won't include random module maps should actually solve various issues around seeing incomplete module maps, such as ones referring to ObjC compatibility headers that haven't been written, yet.
rdar://89082987

Move .swiftmodule output directory

---

Sources/Basics/Archiver/Archiver.swift
Tests/CommandsTests/PackageRegistryToolTests.swift

Follow up to https://github.com/apple/swift-package-manager/pull/7009, which provides the detailed motivation: we should avoid `temp_await` as it can lead to deadlocks when combined with Swift Concurrency.

Avoid use of `temp_await` in `PackageRegistryToolTests.swift`

---

Sources/SPMTestSupport/SwiftPMProduct.swift

A fix for incorrectly overriding environment variables rdar://118814900
In SwiftPMProduct.swift, the environment variables are overridden irrespective of the "env" variables provided.
Move the code snippet that fills the environment variable array to an appropriate place
Environment variables are correctly populated

A fix for incorrectly overriding environment variables rdar://118814900

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildPlan/BuildPlan+Test.swift
Sources/Build/BuildPlan/BuildPlan.swift

The Swift compiler supports disabling sandboxing for macros now, so we should opt-in to that if the selected toolchain supports it and the user has disabled sandboxing. We warn if macros are being used and disabling sandboxing was requested but isn't available.
rdar://118851130

Pass `-disable-sandbox` to Swift compiler if requested

---

Package.swift
Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/TargetBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift
Sources/SPMTestSupport/MockBuildTestHelper.swift
Sources/SourceKitLSPAPI/BuildDescription.swift
Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
xcode/SwiftPM-Package.xctestplan

Until now, SourceKit-LSP has been using a couple of internal data structures of the build plan, which were incidentally public, for this. This changes exposes a new public API for accessing information about build targets, including those for plugins.
Note that this API is part of a new module which could be the start of a "proper" public API for SwiftPM. That said, right now it depends on several types of existing modules in its public interface and that isn't likely to be resolved as part of this particular change.
rdar://112120976

Public API for getting information about build targets

---

Fixtures/Miscellaneous/LTO/SwiftAndCTargets/.gitignore
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Package.swift
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/cLib/cLib.c
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/cLib/include/cLib.h
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/exe/main.swift
Fixtures/Miscellaneous/LTO/SwiftAndCTargets/Sources/swiftLib/swiftLib.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Tests/FunctionalTests/MiscellaneousTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/6891.
Adds a test covering experimental lto mode and fixes a bug where the LTO mode was not passed to the linker.
Fixes #6888

[5.10] Add test fixture for `--experimental-lto-mode` option

---

Sources/Commands/PackageTools/PluginCommand.swift
Tests/CommandsTests/PackageToolTests.swift

Cherry-pick of https://github.com/apple/swift-package-manager/pull/7151
motivation: The 'network' plugin permission in SwiftPM allows a plugin to request external network access to all or to a set of ports, but the command line flag does not allow to specify ports forcing users to allow all
changes:
* support passing ports to `local` and `all` --allow-network-connections flag
* write parsing logic to extract ports from `local:port,port,port` and `all:port,port,port`
* update remedy description to accurately specify the usage
* update tests
rdar://116241125

[5.10] make it possible to specify permitted network port access at runtime

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

If a Swift module is built with C++ interop enabled, all of its dependencies must also be built with C++ interop enabled.
Swift packages that use test discovery get a synthesized "PackageDiscoveredTests" target which is built by SwiftPM when someone runs `swift test` command. This module is currently always built without C++ interop, which is causing issues for projects that rely on it. ### Modifications:
This patch makes sure that the `-cxx-interoperability-mode=` command line flag gets propagated to the test discovery target.
Packages that use both C++ interop and test discovery can now be built successfully by SwiftPM.
rdar://117078320 / resolves https://github.com/apple/swift-package-manager/issues/6990
Original PR: https://github.com/apple/swift-package-manager/pull/7165
(cherry …

🍒[cxx-interop] Make test discovery compatible with C++ interop

---

Utilities/bootstrap

When using XCBuild, we don't segment Swift modules into a "Modules" subdirectory, so we have to special case this during installation.
This should fix the same issue as the revert in https://github.com/apple/swift-package-manager/pull/7173

Fix modules path for XCBuild

---

Sources/Basics/Archiver/Archiver.swift
Tests/CommandsTests/PackageRegistryToolTests.swift

This reverts https://github.com/apple/swift-package-manager/pull/7169 with build issues fixed, which itself was a revert of https://github.com/apple/swift-package-manager/pull/7015.

Re-revert "Avoid use of temp_await in `PackageRegistryToolTests.swift`"

---

Sources/SPMBuildCore/Plugins/PluginInvocation.swift
Sources/SPMBuildCore/Plugins/PluginScriptRunner.swift
Sources/SPMTestSupport/misc.swift
Sources/SourceControl/RepositoryManager.swift
Tests/CommandsTests/PackageRegistryToolTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/PluginTests.swift
Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

Adopt async/await in more tests
Same as before. async/await good
Moved multiple test targets to async/await
Only three uses of `temp_await` remain in test targets after this PR.

Adopt `async`/`await` in more tests

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

This fixes the Swift PR testing failures.
If C++ interop is not enabled, SwiftPM should not pass `-Xcc -std=c++17` flags.
Only pass these flags if C++ interop is enabled.

[cxx-interop] Do not pass the C++ standard if C++ interop is not enabled

---

Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift
Sources/swift-package-manager/SwiftPM.swift
Sources/swift-package-registry/runner.swift

Move PackageRegistryTool to async/await
Continue replacing older concurrency primitives with native async/await
Replace all usage of temp_await with actual async/await in the PackageRegistryTool
One additional executable target that is natively async/await

Move PackageRegistryTool to async/await

---

Sources/Commands/PackageTools/Init.swift
Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift
Sources/SPMTestSupport/misc.swift
Sources/Workspace/InitPackage.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/InitTests.swift

This PR adds `-enable-experimental-swift-testing` (and `-disable-xctest` and their inverses) to `swift package init`. These options behave, broadly, the same as they do for `swift test`. They determine which testing library a new package will use and adjust the generated template to match.
It is important to note that any combination of the two libraries is supported: a developer may wish to use only one or the other, or both, or may wish to opt out of a test target entirely. All four combinations are supported, however for simplicity's sake if both libraries are enabled, we only generate example code for swift-testing.
Note that right now, correct macro target support is impeded by https://github.com/apple/swift-syntax/issues/2400. I don't think that issue blocks a change here (since …

Allow specifying testing libraries for `swift package init`

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

This fixes the Swift PR testing failures.
If C++ interop is not enabled, SwiftPM should not pass `-Xcc -std=c++17` flags.
Only pass these flags if C++ interop is enabled.
Original PR: https://github.com/apple/swift-package-manager/pull/7188
(cherry picked from commit 351222f5b0d7dc9b1bbdffe6c86c1ec97659b36b)

🍒[cxx-interop] Do not pass the C++ standard if C++ interop is not enabled

---

Sources/Commands/SwiftTestTool.swift
Sources/swift-package-manager/SwiftPM.swift
Sources/swift-test/CMakeLists.txt
Sources/swift-test/main.swift

Reverts apple/swift-package-manager#7016 to fix macOS CI regression:
```
duplicate symbol '_async_MainTu' in:
/Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_package.build/Entrypoint.swift.o
/Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_test.build/Entrypoint.swift.o
duplicate symbol '_async_Main' in:
/Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-apple-macosx/debug/swift_package.build/Entrypoint.swift.o
/Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx/branch-main/swiftpm/.build/x86_64-appl …
```

Revert "Avoid using `temp_await` in `SwiftTestTool.swift`"

---

Sources/LLBuildManifest/LLBuildManifestWriter.swift
Tests/LLBuildManifestTests/LLBuildManifestTests.swift

Cherry-pick of  #7052.
This is the default mode in XCBuild, and allows incremental builds to work across reboots on APFS. It would also likely address https://github.com/apple/swift-package-manager/issues/4651.
Set `file-system` as `device-agnostic` in the generated build manifest
Restarting your system (or inode changes) doesn't invoke unnecessary builds
Related to rdar://96403757.

[5.10] Set `file-system` as `device-agnostic` in build manifest

---

Tests/FunctionalTests/PluginTests.swift

It seems like there's some flakiness with these log statements on Linux, but since they're not material for the test (which mostly wants to test that the build succeeds), we can remove the assertions for them for now to avoid blocking CI.

Adjust `testURLBasedPluginAPI` logging checks

---

Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/ToolchainConfiguration.swift
Sources/PackageModel/UserToolchain.swift
Sources/Workspace/DefaultPluginScriptRunner.swift

When using SwiftPM `PackageDescription` or `PackagePlugin` libraries in an inferior, the corresponding modules are now found in a "Modules" subdirectory, but I didn't adjust the include paths being used for this. It appears that prior versions of the Swift compiler would search for modules recursively but recent versions of 5.11 have stopped doing so, unmasking this existing issue.

Bifurcate SwiftPM library locations

---

Package.swift

Traditionally, we have tried to keep swift-driver and llbuild dependencies out of the `libSwiftPMDataModel` product, in fact that is the main motivation for its existence. `SourceKitLSPAPI` depends on the build parts of SwiftPM, so it should not be part of the data model library.

Move the `SourceKitLSPAPI` target to the `SwiftPM` product

---

Sources/PackageGraph/GraphLoadingNode.swift
Sources/PackageGraph/PackageGraph+Loading.swift
Sources/PackageGraph/Resolution/ResolvedTarget.swift
Sources/SPMTestSupport/ResolvedTarget+Mock.swift
Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Tests/PackageGraphTests/ResolvedTargetTests.swift

A serious performance regression was introduced for deep target dependency graphs in https://github.com/apple/swift-package-manager/pull/7160. After converting `ResolvedTarget` to a value type, its synthesized `Hashable` conformance traversed the whole dependency tree multiple times when using `topologicalSort`. This made package resolution seemingly hang for packages that had a lot of nested target graphs.
We already have an implementation of `topologicalSort` on `Identifiable`, so we're using that now instead. I've also added a performance test for this in `PackageGraphPerfTests` to prevent future regressions in this area.
Resolved rdar://119807385.

Use `topologicalSort` with `Identifiable` on `ResolvedTarget`

---

Sources/Basics/Vendor/Triple.swift
Sources/Commands/PackageTools/Init.swift
Sources/Commands/Utilities/APIDigester.swift
Sources/CoreCommands/Options.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
Sources/SPMBuildCore/XCFrameworkMetadata.swift
Sources/SPMTestSupport/misc.swift
Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Sources/swift-bootstrap/main.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/TopologicalSortTests.swift

Swift snapshots off `main` warn about `@retroactive` attribute not present on retroactively added protocol conformance, i.e. when a type and a protocol it conforms to are coming from different modules.
Added `@retroactive` attribute conditionally when built with Swift versions lower than 5.10. Also fixed a few other warnings that were introduced recently with an unused `let` binding and an unused `Comparable` conformance.
Reduced number of warnings when building with Swift `main` snapshots. New concurrency warnings appearing in Swift `main` are untouched here, as they require much more invasive changes to fix `Sendable` conformances.

[NFC] Fix some of the new Swift `main` snapshots warnings

---

Sources/Build/BuildDescription/TargetBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/PackageModel/ToolsVersion.swift
Tests/FunctionalTests/PluginTests.swift

It is possible to declare build commands without outputs and the expectation is that those would still run. Currently, that is not the case, since the only condition that makes llbuild run build commands is that there's a client for the output files (either compilation or copying of resources).
This change adds a phony output to any command that has no declared outputs and declares these phony outputs as input for any targets that are asking for the plugin to be applied. This will lead to these commands running unconditionally, fixing the current silent failure to run these.
rdar://100415491

Run build commands without declared outputs

---

Sources/Commands/SwiftTestTool.swift

This PR causes `swift test` to check the dependencies of the package under test; if they include an explicit reference to the public swift-testing repository on GitHub, then `--enable-experimental-swift-testing` is assumed. A developer can still opt out by explicitly writing `--disable-experimental-swift-testing`.
Resolves rdar://99155992.

Automatically enable swift-testing support in `swift test` when it's a dependency.

---

Sources/PackageLoading/ManifestLoader.swift

Manifest loading dumps serialized diagnostics files into the manifest cache, that's why the sandbox needs an exception for that. This generally seems a bit odd, but firstly, we can limit the access to the subdirectory that is actually being used instead of the entire cache.

Limit cache directories

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildPlan/BuildPlan+Test.swift
Sources/Build/BuildPlan/BuildPlan.swift

The Swift compiler supports disabling sandboxing for macros now, so we should opt-in to that if the selected toolchain supports it and the user has disabled sandboxing. We warn if macros are being used and disabling sandboxing was requested but isn't available.
(cherry picked from commit 23042d62a0f37fadd021b3f8ce717f1d2d949180)

[5.10] Pass `-disable-sandbox` to Swift compiler if requested

---

Sources/Basics/Archiver/ZipArchiver.swift
Sources/Basics/Cancellator.swift

Motivation:
`swift package-registry publish` tool doesn't work in Amazon Linux 2 because it has an older version of Glibc that doesn't support `posix_spawn_file_actions_addchdir_np`.
Modifications:
Add workaround in `ZipArchiver` that does `cd <working directory> && zip ...` when `posix_spawn_file_actions_addchdir_np` is not available.

Workaround in ZipArchiver when posix_spawn_file_actions_addchdir_np is unavailable

---

Sources/Commands/SwiftTestTool.swift
Tests/CommandsTests/TestToolTests.swift

This PR makes the `--parallel` flag on the swift-test subtool invertible with a "no" prefix.
We want swift-testing to default to enabling parallelization, but we don't want to break XCTest (which for historical reasons strongly prefers serial testing.) Deprecating `--parallel` and replacing it with `--{enable,disable}-parallelism` or similar seems a bit heavy-handed. Swift Argument Parser gives us the option to use a "no" prefix instead which means that the existing `--parallel` option will continue to work as intended.
Support for `--no-parallel` in swift-testing is here: https://github.com/apple/swift-testing/pull/174

Add `swift test --no-parallel`

---

Sources/Commands/SwiftTestTool.swift

Follow-up to #7220. swift-testing itself should get swift-testing support enabled by default, but it doesn't list itself as a dependency. This change extends the code in that PR to also check the identities of the packages being built (rather than just their dependencies.) If the package being built is named "swift-testing", then support is enabled.

Automatically enable swift-testing support when building swift-testing

---

Sources/CoreCommands/SwiftTool.swift

Emit a deprecation warning for `--skip-update`

---

Sources/PackageModel/MinimumDeploymentTarget.swift
Sources/PackageModel/ToolchainConfiguration.swift

This should avoid repeated shelling out to determine these versions.
rdar://114095947

Cache SwiftPM library deployment targets

---

Sources/PackageLoading/ToolsVersionParser.swift
Sources/PackageModel/ToolsVersion.swift
Tests/PackageLoadingTests/ToolsVersionParserTests.swift

It doesn't seem particularly necessary to require tools-versions to be specified in the first line of the manifest, e.g. users may want to write comments at the top of the file. This changes the parsing to look at all lines of the manifest subsequently in case of errors. If no tools-version is found in the entire file, the original error as determined by the first line will be thrown. If a tools-version specification is found, but is for a version prior to 5.11, a specific error message is thrown to avoid users to write backwards-incompatible manifests when using 5.11.
rdar://118484544

Allow tools-versions to be specified later in the manifest

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/FunctionalTests/ResourcesTests.swift

It is possible to declare references to resources outside of ones target and it doesn't seem like that should be problematic in any way. Currently, these declarations essentially get ignored because the algorithm looks at files inside the target and applies rules to them, so any unmatched rules simply get ignored. In the grand scheme of things it may make sense to change that approach in a more fundamental way, but to fix this particular problem we can simply record all rules that were used and apply the unmatched rules after that initial processing has finished. Since this is a significant behavior change, we only do it for tools-version 5.11 or later.
rdar://119040426
resolves #6982

Include out-of-target resources

---

CHANGELOG.md
Package.swift
Sources/PackageDescription/Context.swift
Sources/PackageLoading/ContextModel.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/ToolsVersion.swift
Sources/SourceControl/GitRepository.swift
Tests/PackageLoadingTests/PD_5_11_LoadingTests.swift

This adds a few bits of information about a package's git repository to the context accessible to package manifests:
- the current commit
- the current tag (if any)
- whether or not there are uncommited changes
rdar://111523616

Add git information to PD context

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift

This should ensure a stable order for the results of `TargetSourcesBuilder`.
rdar://113607400

Sort results of `TargetSourcesBuilder`

---

Tests/BasicsTests/URLSessionHTTPClientTests.swift

This test sporadically fails on CI because of the timeouts, so I am going to increase them.
rdar://108795267

Bump test timeout

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

Newer versions of clang add builtin modules for its C Standard Library headers. This creates problems* when building with a single module map that tries to absorb all of the OS/SDK dependencies, which is what all non-Apple platforms currently do in SwiftPM.
This works for Swift targets because the Swift compiler injects module maps via vfs for non-Apple platforms. However, clang doesn't do anything similar for C-based targets, and so they fail to build.
For now, don't build with modules for any SwiftPM C-based targets on non-Apple platforms.
\* Some problems are module cycles and headers being absorbed into unexpected modules. clang modules generally expect that OS/SDK headers are covered by module maps, and _not_ absorbed into whatever module happens to include them first. …

Linux packages fail to build with LLVM 18 and Apple 2023 versions of clang

---

CMakeLists.txt
Sources/Basics/CMakeLists.txt
Sources/Basics/OSSignpost.swift
Sources/SPMTestSupport/GitRepositoryExtensions.swift
Sources/SPMTestSupport/MockArchiver.swift

Reverts apple/swift-package-manager#7240

Revert "Start using `package` for some APIs"

---

Fixtures/Miscellaneous/Plugins/CommandPluginDiagnosticsStub/Package.swift
Fixtures/Miscellaneous/Plugins/CommandPluginDiagnosticsStub/Plugins/diagnostics_stub.swift
Fixtures/Miscellaneous/Plugins/CommandPluginDiagnosticsStub/Sources/main.swift
Tests/CommandsTests/PackageToolTests.swift

This test exercises command plugin console output under different verbosity settings:
There doesn't seem to be a test which checks the handling of diagnostic messages from command plugins in a once place.   This test will help to avoid regressions in this area.
* A new stub plugin prints to standard output or sends diagnostic output, depending on its arguments
* A new test uses the stub to generate outputs and checks what `swift package` prints to the console at different verbosity levels
This test verifies existing functionality.    No change in Swift Package Manager.

Tests: Exercise output and diagnostic messages from command plugins

---

Sources/Basics/Collections/IdentifiableSet.swift
Sources/Build/BuildPlan/BuildPlan.swift
Sources/PackageGraph/PackageGraph.swift
Sources/SPMTestSupport/MockBuildTestHelper.swift
Tests/FunctionalTests/PluginTests.swift

There are certain build configurations that currently fail due to the use of `package`. We can use `@_spi(SwiftPMInternal)` in the meantime.

Replace uses of `package` with `@_spi(SwiftPMInternal)`

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

Disable clang modules for C++ compilation on Apple platforms
I didn't realize that there were some circumstances where passing `-fmodules` would enable clang modules for C++ on Apple platforms.
Go back to not passing `-fmodules` for Apple platforms.
C++ packages should be able to build properly again.

Some C++ packages fail to build on Apple platforms

---

Sources/Basics/EnvironmentVariables.swift

Yet another environment variable that shouldn't trigger full package rebuilds.
Resolves rdar://107029374

Add `SSH_AUTH_SOCK` to `EnvironmentVariables.nonCachableKeys`

---

Tests/BasicsTests/FileSystem/PathShimTests.swift
Tests/BuildTests/BuildPlanTests.swift

Since we don't run this script on CI right now, we have to fix regressions with manual runs of this script and separate PRs created for the fixes in the meantime.

Fix `./Utilities/soundness.sh` regressions

---

Sources/Workspace/InitPackage.swift

template resulting from `swift package init --type command-plugin` did not auto generate the extension name and used boilerplate instead. 
Seems like a small oversight, not an intentional difference. 
InitPackage.swift line 553 goes from `extension MyCommandPlugin: XcodeCommandPlugin {` to `extension \(typeName): XcodeCommandPlugin {`
Template generates correctly.

command plugin Xcode extension name fixed

---

Sources/Basics/FileSystem/FileSystem+Extensions.swift
Sources/CoreCommands/SwiftTool.swift

Currently, concurrent execution of SwiftPM can easily break the state in .build irreparably. This is especially in conjunction with tools using file watching to trigger package resolution which is something that e.g. the Swift VS Code plugin does.
We can resolve this by locking the .build directory for the duration of execution of any `SwiftTool` such that any following access will do a blocking wait until unlock. This is using the same infrastructure that we are already using for the shared repository cache. Unlike the shared cache, tool execution can take a long time, so we'll inform the user about the waiting process so that they can decide to cancel instead.
rdar://113964179

Lock scratch directory during tool execution

---

Utilities/bootstrap
Utilities/build-using-self

This codepath could regress since we previously didn't run it in our PR testing.
With this change on macOS we always try to bootstrap SwiftPM with XCBuild on top of the usual llbuild build and test run.
It does increase the time spent on the macOS self-hosted job, but that job was already multiple times faster than our smoke test jobs, thus we have enough leeway to make it longer with the benefit of better PR testing.

Exercise bootstrapping with the XCBuild codepath in `build-using-self`

---

Sources/Basics/FileSystem/FileSystem+Extensions.swift
Sources/CoreCommands/SwiftTool.swift

We're seeing hangs in self-hosted jobs since merging this and I can't repro locally, so let's try this speculative revert to see whether it resolves the issues.
Reverts apple/swift-package-manager#7269

Revert of "Lock scratch directory during tool execution"

---

Sources/SPMTestSupport/Toolchain.swift
Tests/FunctionalTests/MiscellaneousTests.swift

This reverts commit 6ba5b96ab587c204bd7a799ccaf2ae24be208853 since the underlying issue has since been fixed.

Revert "Skip tests which need `-suppress-warnings` to work if it doesn't work"

---

Fixtures/Miscellaneous/DoNotFilterLinkerDiagnostics/Package.swift
Fixtures/Miscellaneous/DoNotFilterLinkerDiagnostics/Sources/DoNotFilterLinkerDiagnostics/main.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Tests/BuildTests/BuildSystemDelegateTests.swift

Right now we end up with this output on relink:
```
/Users/neonacho/Projects/public/swift-package-manager/.build/arm64-apple-macosx/debug/swift-bootstrap: replacing existing signature
```
This change specifically filters any output from `codesign` commands which haven't failed and we aren't in verbose mode.
This should eventually be possible at the command level, but for the time being this allows us to avoid shipping SwiftPM with this messy output.
rdar://118937939

Filter `codesign` messages

---

Sources/PackageModel/UserToolchain.swift
Tests/PackageModelTests/PackageModelTests.swift

Fix `PATH` executable selection in `UserToolchain`
When `swiftc` is not in the toolchain bin directory of Swift SDK, system swiftc in PATH should be used. But the current implementation of `UserToolchain` always picks the last found entry in the PATH instead of the first one. This behavior was introduced by 22c249317fa5171f17a0e41efe81e69e054a3d75
The causes actual issues when:
1. More than two `swiftc` are in `PATH`
2. The invoked `swift-build` is placed from outside of toolchain bin directory
Then it uses the last found `swiftc` in `PATH` even though we expect the first one.
Fixed the order of `PATH` selection to prefer the first entry.
The first found `swiftc` is used as well as shell PATH selection.

Fix swiftc selection for the case no swiftc found in Swift SDK

---

Fixtures/Miscellaneous/Plugins/CommandPluginTestStub/Plugins/diagnostics-stub/diagnostics_stub.swift
Sources/Commands/Utilities/PluginDelegate.swift
Sources/PackagePlugin/Diagnostics.swift
Sources/PackagePlugin/PluginMessages.swift
Sources/SPMBuildCore/Plugins/PluginInvocation.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/PluginTests.swift

This change adds a 'progress' message to the diagnostics which a plugin can send back to SwiftPM.   This message is printed to standard error at the default verbosity level.
Currently, a plugin can write output to standard output or send diagnostics which SwiftPM writes to standard error.   If the plugin spawns long-running operations we might want to print progress messages to let the user know that it is still running.   The existing options all have compromises:
* Anything the plugin prints to its standard output or standard error is echoed to SwiftPM's standard output, but we may want to keep progress information separate from other plugin outputs - the plugin might be called as part of a shell pipeline where a downstream process will consume its output, for example.
* The existing …

command plugins: Add a 'progress' diagnostic message at default verbosity

---

Sources/CoreCommands/SwiftTool.swift
Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
Tests/PackageModelTests/SwiftSDKBundleTests.swift

Fallback to host SDK tools if target SDK doesn't have tools.
Currently, Swift SDK fallbacks to system `PATH` search path for tools that are not found in the SDK. Usually, host compiler tool is capable to cross compile but just lacks some of artifacts like platform libraries.
In that case, we don't need to have a separate compiler tools in target-specific Swift SDK, so we can share the host compiler tools as long as the host Swift and target Swift are the same version.
This patch makes Swift SDK fallback to host Swift SDK tools if the target Swift SDK doesn't have such tools. 
This unlocks eliminating compiler tools from target-specific Swift SDKs, and will result in a smaller SDK size. Also makes it easier to build host platform independent Swift SDK.

 Inherit host Swift SDK's toolset paths to fallback to host tools

---

Fixtures/Miscellaneous/DoNotFilterLinkerDiagnostics/Package.swift
Fixtures/Miscellaneous/DoNotFilterLinkerDiagnostics/Sources/DoNotFilterLinkerDiagnostics/main.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Tests/BuildTests/BuildSystemDelegateTests.swift

* **Explanation**: 
SwiftPM is code signing any binaries it produces on macOS in 5.10. Whenever a binary get relinked and resigned during incremental builds, it verbatim emits informational diagnostics to the log, which should only happen in verbose mode. Especially in projects which multiple binaries, this can make the log difficult to follow and may lead to confusion of users.
* **Scope**: Any users on macOS will see this issue.
* **Risk**: In theory, this change could lead to other diagnostics not being emitted, but the change is scoped to only code signing tasks, so the risk for this is very low.
* **Testing**: Some new tests for SwiftPM's logging were added as part of this.
* **Reviewer**: @MaxDesiatov
* **Main branch PR**: https://github.com/apple/swift-package-manager/pull/7285

[5.10] Filter `codesign` messages

---

Fixtures/Miscellaneous/Plugins/CommandPluginTestStub/Plugins/diagnostics-stub/diagnostics_stub.swift
Sources/Commands/Utilities/PluginDelegate.swift
Sources/PackagePlugin/PackageManagerProxy.swift
Sources/PackagePlugin/PluginMessages.swift
Sources/SPMBuildCore/Plugins/PluginInvocation.swift
Tests/CommandsTests/PackageToolTests.swift

This commit adds the option for a build run on behalf of a command plugin to echo logs to the console as they are produced, in addition to the current behaviour of accumulating them in a buffer.   Console echoing is turned off by default.
When a plugin asks for a target to be built by calling `packageManager.build`, SwiftPM accumulates the build log in a buffer and returns the whole log when the build completes.   No feedback is printed on the console while the build is running, so if the target is large the user can't tell whether the build is making progress or is stuck.
* Added `TeeOutputByteStream`, an `OutputByteStream` which copies its inputs to a set of output streams
* Added an `echoLogs` parameter to `packageManager.build`, defaulting to `false` to match the current behaviour.
* …

command plugins: Optionally print build logs during packageManager.build

---

Sources/PackageDescription/Target.swift
Sources/PackageLoading/ManifestLoader+Validation.swift

As part of https://github.com/apple/swift-evolution/blob/main/proposals/0339-module-aliasing-for-disambiguation.md, a new API with an optional `package` parameter was accidentally added. We can safely remove this API since #4203 added validation that prohibited the use of product declarations without a package anyway. As part of this, I also cleaned up that diagnostic since "unknown package 'unknown package name'" looks quite ugly.
rdar://114303935
fixes #7158

Clean up product dependency API

---

Sources/Build/BuildOperation.swift

There's a missing space, which results in squashing the display name with the "Running" word like this
>info: RunningMyCoolTool
**Expected:**
>info: Running MyCoolTool
**Result:**
Fixed logging behavior

Fix logging of "Running..." for plugins

---

Tests/BuildTests/BuildSystemDelegateTests.swift

(cherry picked from commit 8bc47da51b786171795b18ce8d203df3fc9d12db)
* **Explanation**: 
We have been seeing flakiness of tests requiring the SDK (e.g. compiling manifests or running tests) for quite some time on the smoke test macOS CI. Some new tests were recently added which fall under this category but haven't been marked with the appropriate skipping clauses.
* **Scope**: smoke test CI runs on macOS
* **Risk**: none, this is a test-only change
* **Testing**: this is a test-only change
* **Reviewer**: @bnbarham 
* **Main branch PR**: https://github.com/apple/swift-package-manager/pull/7305

[5.10] Gate new tests on `supportsSDKDependentTests()`

---

Package.swift
Sources/Basics/FileSystem/TSCAdapters.swift
Sources/Basics/JSON+Extensions.swift
Sources/PackageRegistryTool/PackageRegistryTool.swift
Tests/BasicsTests/NetrcTests.swift
Tests/CommandsTests/TestToolTests.swift
Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift

Allows us to delete some existing backwards compatibility code.

Update minimum deployment target to macOS 13

---

Sources/Basics/CMakeLists.txt
Sources/Basics/ProgressAnimation.swift
Sources/PackageModel/SwiftSDKs/SwiftSDKBundleStore.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Tests/BasicsTests/ProgressAnimationTests.swift

The download operation takes a while, and it makes users feel like SwiftPM is stuck. 
This patch adds a progress indicator to the download operation to make it clear that SwiftPM is still working and how much work is left.
https://github.com/apple/swift-package-manager/assets/11702759/c535ede4-3d11-4992-9314-55a4e1e864d6

Show progress bar while downloading Swift SDK bundles

---

.dir-locals.el
Utilities/Emacs/swiftpm-project-settings.el

Directory-local variables have been moved so that they are set directly
in `.dir-locals.el`.
The variables set in `swiftpm-project-settings.el` can be set directly
in `dir-locals.el`. There is no reason to move them to a separate file,
and in fact doing that will automatically make Emacs flag the dir-locals
as unsafe, since it will be being requested to evaluate a block of code,
instead of setting known-safe variables.
`Utilities/Emacs/swiftpm-project-settings.el` has been removed. All variables
set in it have been moved to `.dir-locals.el` itself. This allows the evaluation
of all directory locals to be considered safe.
Additionally, `swift-basic-offset` was changed to `swift-mode:basic-offset`.
That appears to be the proper variable for setting indent width for Swift in Emacs.
Emacs …

Move `swiftpm-project-settings.el` settings to `.dir-locals.el`

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/CMakeLists.txt
Sources/Build/ClangSupport.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/ClangTargetBuildDescriptionTests.swift

Today, the index store is only enabled on Darwin by default and needs a manual opt-in on other platforms. We can instead switch this to enabling it based on whether the used clang supports `-index-store-path`.
rdar://117744039

Enable index store based on Clang feature detection

---

Sources/SPMTestSupport/Observability.swift
Sources/SPMTestSupport/Toolchain.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ResourcesTests.swift

This reverts commit ac8806fd94feee971e1c608d6dec658d5d451a80 since it is no longer needed with more recent Swift compilers.

Revert "Filter superfluous diagnostics"

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildOperation.swift
Sources/SPMTestSupport/MockRegistry.swift
Sources/SourceControl/GitRepository.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/RunToolTests.swift
Tests/FunctionalTests/PluginTests.swift

This is really just a start, there are a few hundred more occurences of raw `\n` in the codebase that may or may not be problematic.

Reduce use of raw `\n` to improve cross-platform compatibility

---

Sources/Basics/FileSystem/FileSystem+Extensions.swift
Sources/CoreCommands/SwiftTool.swift

This reverts commit e92df2d2a0c639a8f478f80d2838370d451de5da and brings back the changes from #7269.

Bring back "Lock scratch directory during tool execution"

---

Sources/CoreCommands/SwiftTool.swift

It seems like for reasons we have a fallback scratch directory even if we couldn't determine a package root, but it doesn't seem as if we should lock that since it is likely not the scratch directory we want.

Don't lock if we don't have a package root

---

Sources/Basics/CMakeLists.txt
Sources/Basics/ProgressAnimation/NinjaProgressAnimation.swift
Sources/Basics/ProgressAnimation/PercentProgressAnimation.swift
Sources/Basics/ProgressAnimation/ProgressAnimationProtocol.swift
Sources/Basics/ProgressAnimation/SingleLinePercentProgressAnimation.swift
Sources/Basics/ProgressAnimation/ThrottledProgressAnimation.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Commands/SwiftTestTool.swift
Sources/CoreCommands/SwiftTool.swift
Sources/CoreCommands/SwiftToolObservabilityHandler.swift
Sources/PackageModel/SwiftSDKs/SwiftSDKBundleStore.swift
Sources/SwiftSDKTool/InstallSwiftSDK.swift
Sources/XCBuildSupport/XCBuildDelegate.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift
Tests/BasicsTests/ProgressAnimationTests.swift

SwiftPM uses ProgressAnimation from TSCUtilities in a variety of inconsistent manners across various swift-something commands. This commit replaces the uses of ProgressAnimation throughout SwiftPM with common entrypoints and lays the ground work for creating multi-line parallel progress animations as seen in tools like `bazel build` and `docker build`.

Move and refactor `ProgressAnimation` code from TSC

---

Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftTool.swift

This is obviously dangerous, but arguably has been the default behavior of SwiftPM for many years, so offering an escape hatch seems appropriate.

Add hidden `--ignore-lock` escape hatch

---

Utilities/config.json

(cherry picked from commit db00c3e1947aeb9c1906ee6330fb587eda940f02)
* **Explanation**: Bumps the swift-syntax version in the macro template to 5.10. `-latest` allows using pre-release tags until 510 is tagged in swift-syntax.
* **Scope**: Templates
* **Risk**: Very low - updates a template to use the tag corresponding to this release.
* **Testing**: Manual testing with a modified config in the toolchain
* **Reviewer**: @bnbarham 
* **Main branch PR**: https://github.com/apple/swift-package-manager/pull/7339
* **Radar**: rdar://121857631

[5.10] Bump swift-syntax version in the macro template

---

Utilities/config.json

We use the "-latest" signifier to avoid confusion here, but basically this means we'll use any "-prerelease" tags and also the final release once it is out.

Bump swift-syntax version in the macro template

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/TestObservation.swift

The test runner build was failing on WASI after the introduction of the experimental summary output.
This PR fixes several minor issues to pass `--build-tests` build on WASI:
* Missing `WASILibc` import
* The use of `flock` which is not available on WASI.
* Signature incompatibility of `XCTMain` on WASI.
`swift build --build-tests --triple wasm32-unknown-wasi` will pass when compiler supports the target

Fix test runner build on WASI

---

Package.swift
Sources/PackageModel/UserToolchain.swift

https://github.com/apple/swift-package-manager/pull/7337 is breaking toolchain builds, so we should pass `SKIP_RESOURCE_SUPPORT` by default to avoid that.

Make `PackageModel` resources optional

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Target/BinaryTarget.swift
Sources/PackageModel/Target/ClangTarget.swift
Sources/PackageModel/Target/PluginTarget.swift
Sources/PackageModel/Target/SwiftTarget.swift
Sources/PackageModel/Target/SystemLibraryTarget.swift
Sources/PackageModel/Target/Target.swift
Tests/BuildTests/ProductBuildDescriptionTests.swift

Without passing this flag, Swift Driver links such products as if they're not built for embedded platforms at all, passing incorrect flags to the linker. This is not reproducible when using plain `swiftc`, as that combines both compile and link jobs by default, but SwiftPM prefers to run those separately, which requires this special handling.
Directly checking in `ProductBuildDescription/linkArguments` whether all of the product's targets are built in the embedded mode. If so, we're passing the embedded mode flag to Swift Driver.
Unfortunately, `BuildSettings.AssignmentTable` is formed too early in the build process right in `PackageModel`, while we still need to run checks specific build settings quite late in the build stage. Because of that, there's no clean way to check if `Embedded` …

Build: pass through `Embedded` flag to link jobs

---

Sources/Build/BuildDescription/ProductBuildDescription.swift
Tests/BuildTests/CrossCompilationBuildPlanTests.swift

Enable `--gc-sections` back for WebAssembly targets
We disabled `--gc-sections` for Wasm targets due to a lack of features in the object file format. However, we recently added the missing piece in wasm object file format, so we no longer have any reason to disable it.
This effectively reverts 3a366cc7fa5daf38476af6627a3881f04e50bb05. After https://github.com/apple/swift/pull/71768, we don't have any reason to disable `--gc-sections` for WebAssembly targets. Note that the new wasm segment flags are only supported by the latest LLVM and wasm-ld, but we can assume that toolchains or Swift SDKs for WebAssembly have wasm-ld built from the latest LLVM.
Allow dead code stripping at link time for WebAssembly targets.

Enable `--gc-sections` for WebAssembly targets

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

We're seeing a large amount of issues created that are unrelated to this repository. We need to add a clear warning to our issue template that such issues will be closed.

Clarify that Xcode issues are not tracked in `BUG_REPORT.yml`

---

Sources/SourceControl/GitRepository.swift
Tests/SourceControlTests/GitRepositoryTests.swift

786c5131ed5ec823d3be90ad31923123fcaccd56 added support for symlinks, but didn't handle `executableBlob` in the added `switch`. `executableBlob` is the returned type for a file with the executable bit set, so needs to be handled in the same way as a regular `blob`.

Allow reading `Package.swift` with the executable bit set

---

Tests/FunctionalTests/MiscellaneousTests.swift

The regular expression matching the compiler's output depends on the existing "LLVM" diagnostic style, and does not work with the new "Swift" style.
Split regex into two independent pieces.
The test succeeds with both compiler diagnostic styles.

Generalize test to handle the compiler's new diagnostic printing style

---

Benchmarks/Benchmarks/PackageGraphBenchmarks/PackageGraphBenchmarks.swift
Benchmarks/Package.swift

This adds a dependency on the [`package-benchmark`](https://github.com/ordo-one/package-benchmark) library, isolated to the new `Benchmarks` folder. Thus it doesn't touch CMake or self-hosted builds, and one can only pull the library if they run `swift package benchmark` in the `Benchmarks` directory.
A single benchmark is added that loads SwiftPM's `Package.swift` and builds a package graph for it. For posterity, here's the output we get from it:
```
╒══════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│ Metric                           │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │
╞══════════════════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════ …
```

Benchmarks: add `PackageGraphBenchmarks` target

---

Sources/SPMTestSupport/InMemoryGitRepository.swift
Sources/SPMTestSupport/ManifestExtensions.swift
Sources/SPMTestSupport/MockArchiver.swift
Sources/SPMTestSupport/MockBuildTestHelper.swift
Sources/SPMTestSupport/MockDependency.swift
Sources/SPMTestSupport/MockDependencyGraph.swift
Sources/SPMTestSupport/MockHTTPClient.swift
Sources/SPMTestSupport/MockHashAlgorithm.swift
Sources/SPMTestSupport/MockManifestLoader.swift
Sources/SPMTestSupport/MockPackage.swift
Sources/SPMTestSupport/MockPackageContainer.swift
Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
Sources/SPMTestSupport/MockPackageGraphs.swift
Sources/SPMTestSupport/MockPackageSigningEntityStorage.swift
Sources/SPMTestSupport/MockProduct.swift
Sources/SPMTestSupport/MockRegistry.swift
Sources/SPMTestSupport/MockTarget.swift
Sources/SPMTestSupport/MockWorkspace.swift
Sources/SPMTestSupport/Observability.swift
Sources/SPMTestSupport/PIFTester.swift
Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift
Sources/SPMTestSupport/PackageGraphTester.swift
Sources/SPMTestSupport/ResolvedTarget+Mock.swift
Sources/SPMTestSupport/Resolver.swift
Sources/SPMTestSupport/SwiftPMProduct.swift
Sources/SPMTestSupport/Toolchain.swift
Sources/SPMTestSupport/XCTAssertHelpers.swift
Sources/SPMTestSupport/misc.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift

All of the declarations in this module are never supposed to leak outside of the SwiftPM package.

Adopt `package` in the test support module

---

Package.swift
Sources/SourceKitLSPAPI/BuildDescription.swift
Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift

This prevents unnecessary API details from leaking outside of the SwiftPM package via `SourceKitLSPAPI` product.

Enable `AccessLevelOnImport` in `SourceKitLSPAPI`

---

Sources/SourceKitLSPAPI/BuildDescription.swift
Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift

The compiler itself is part of the command line invocation, not an argument in itself.
rdar://123765692

Don’t include compiler in the command line arguments

---

Sources/Commands/PackageCommands/Init.swift
Sources/Commands/SwiftBuildCommand.swift
Sources/Commands/SwiftTestCommand.swift
Sources/CoreCommands/Options.swift

This PR generalizes the enable/disable XCTest/swift-testing options from `swift test` and `swift package init` and adds them to `swift build --build-tests` so that it is possible to build all test content without actually running the tests. If neither flag is specified, the default test content is built (always XCTest, and swift-testing if it's a dependency, same as `swift test`.)
I don't have unit tests for this work because SwiftPM cannot currently reference or link to swift-testing in CI. I'm open to ideas here.
Resolves #7375.

Add swift-testing support to `swift build --build-tests`

---

Sources/Basics/FileSystem/FileSystem+Extensions.swift

As discussed in #6204, users would like to have a clean home directory.
And in the discussions following the merge of #3430, it seems there is a willingness to adhere to the XDG spec, and support `~/.config/swiftpm`.
If the `XDG_CONFIG_HOME` environmental variable is defined, use `$XDG_CONFIG_HOME/swiftpm` as the root `dotSwiftPM` directory.
The symlinks that were previously stored in `~/.swiftpm` are now stored in `$XDG_CONFIG_HOME/swiftpm` when this variable is defined, therefore not cluttering the home directory of users.
Closes #6204

Add XDG Base Directory Specification support

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildDescription/PluginDescription.swift
Sources/Build/BuildDescription/ProductBuildDescription.swift
Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Sources/Build/BuildDescription/TargetBuildDescription.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
Sources/Build/BuildOperation.swift
Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Sources/Build/BuildPlan/BuildPlan.swift
Sources/Build/ClangSupport.swift
Sources/Build/SwiftCompilerOutputParser.swift
Sources/Build/TestObservation.swift
Sources/LLBuildManifest/Command.swift
Sources/LLBuildManifest/LLBuildManifest.swift
Sources/LLBuildManifest/LLBuildManifestWriter.swift
Sources/LLBuildManifest/Node.swift
Sources/LLBuildManifest/Target.swift
Sources/LLBuildManifest/Tools.swift

These APIs should not be marked `public` to prevent SwiftPM clients from adopting them by accident.

Hide more llbuild-specific APIs

---

Sources/Basics/Concurrency/ConcurrencyHelpers.swift
Sources/Build/BuildPlan/BuildPlan.swift
Sources/Commands/PackageCommands/Format.swift
Sources/Commands/SwiftTestCommand.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PkgConfig.swift
Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
Sources/SPMBuildCore/BuildSystem/BuildSystem.swift
Sources/SourceControl/RepositoryManager.swift
Sources/Workspace/DefaultPluginScriptRunner.swift
Sources/Workspace/Workspace+Configuration.swift
Sources/XCBuildSupport/XcodeBuildSystem.swift
Tests/CommandsTests/APIDiffTests.swift
Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift

This fixes some `ProcessEnv.vars` warnings without more intrusive breaking changes for SwiftPM clients, as previously attempted in https://github.com/apple/swift-package-manager/pull/7364.
Also fixed some formatting inconsistencies.

Replace `ProcessEnv.vars` with `block` w/o API breakage

---

Sources/Build/BuildPlan/BuildPlan+Test.swift
Sources/Commands/Utilities/TestingSupport.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftCommandState.swift
Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift
Tests/CommandsTests/TestCommandTests.swift
Tests/FunctionalTests/TestDiscoveryTests.swift

This flag was deprecated for 4 years since Swift 5.4, Swift 6.0 is a good opportunity to remove it.
Closes https://github.com/apple/swift-package-manager/issues/7389.

Remove previously deprecated `--enable-test-discovery`

---

Sources/Build/BuildPlan/BuildPlan+Test.swift
Sources/Commands/Utilities/TestingSupport.swift
Sources/CoreCommands/Options.swift
Sources/CoreCommands/SwiftCommandState.swift
Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift
Tests/CommandsTests/TestCommandTests.swift
Tests/FunctionalTests/TestDiscoveryTests.swift

Reverts apple/swift-package-manager#7391, which blocks CI as various projects are still using `--enable-test-discovery`.

Revert "Remove previously deprecated `--enable-test-discovery`"

---

Fixtures/Miscellaneous/TestDiscovery/IgnoresLinuxMain/Package.swift
Fixtures/Miscellaneous/TestDiscovery/IgnoresLinuxMain/Tests/IgnoresLinuxMainTests/SomeTest.swift
Fixtures/Miscellaneous/TestDiscovery/IgnoresLinuxMain/Tests/LinuxMain.swift
Sources/Commands/SwiftBuildCommand.swift
Tests/CommandsTests/BuildCommandTests.swift

Ensures that a fully-initialized `TestingParameters` structure is used with `swift build --build-tests` instead of using any default parameters (which will tend us toward the wrong output with packages that use `--enable-test-discovery` and still have LinuxMain.swift files.)
Tested with swift-numerics on Ubuntu 22.04 aarch64; before the change, we'd hit the `fatalError()` call in that package's LinuxMain.swift file. After the change, we correctly run XCTest-based tests.
Resolves #7389.

Pass all arguments when initing testing parameters in `swift build`

---

Documentation/PackageDescription.md

I fixed a grammatical error in PackageDescription.
Specifically, I changed the part that says `to let to let` to `to let`.

Fix remove `to let` from parameter description

---

Sources/Commands/SwiftRunCommand.swift

I've had to make this change on my Android CI since #7369 was merged a couple weeks ago, finagolfin/swift-android-sdk@c5828e4, as Bionic doesn't have this function. I found that [Chromium had switched to this years ago](https://codereview.chromium.org/349323003), can replace `getdtablesize()` altogether instead if wanted.
@MaxDesiatov, let me know what you think.

Replace getdtablesize() on Android

---

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift

This change makes the XCTest entrypoint async on WASI, as it is required to not block the main thread. The entrypoint has been changed during the upstreaming work for WebAssembly support in XCTest.
This change should be merged with https://github.com/apple/swift-corelibs-xctest/pull/478

Fix XCTest entrypoint for WASI by making it async

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift

There are two subtle changes in behavior here:
- This call will fail if the file system doesn’t support atomic operations. I’m not sure if we need to support file systems that don’t allow atomic operations here.
rdar://124727242

Write output-file-map.json atomically

---

Sources/Basics/HTTPClient/URLSessionHTTPClient.swift

`DownloadTaskManager` had a strong reference to `URLSession`, which retained its delegate, which was the `DownloadTaskManager`. This formed a retain cycle.
Make the reference from `URLSession` to the delegate weak and only keep `DownloadTaskManager` alive as long as `DownloadTask`s need it. This causes the `DownloadTaskManager` to be deallocated once nobody holds a reference to it anymore and all the tasks it manages are finished.
Finally, we need to call `invalidate` on the `URLSession` to tell it that we’re done and that it should release its delegate (which is now the `WeakDownloadTaskManager`wrapper).
This retain cycle was causing a leak in sourcekit-lsp. I verified that the leak no longer exists with this patch.
rdar://125012584

Fix a memory leak in `DownloadTaskManager` and `DataTaskManager`

---

Sources/Basics/Sandbox.swift

Fix doc comment typo in `Sandbox.swift`

---

Tests/PackageModelTests/MinimumDeploymentTargetTests.swift

Resolve warnings in `Tests/PackageModelTests/MinimumDeploymentTargetTests.swift` .
3 warnings were displayed indicating that a deprecated function is being used and suggesting the use of an alternative function.
Following the suggestion, the warning was resolved.
The following warnings have been resolved:
> `init(arguments:environment:exitStatus:output:stderrOutput:)` is deprecated: use `init(arguments:environmentBlock:exitStatus:output:stderrOutput:)`

PackageModelTests: fix warnings

---

Sources/Basics/HTTPClient/URLSessionHTTPClient.swift

* **Explanation**: `DownloadTaskManager` had a strong reference to `URLSession`, which retained its delegate, which was the `DownloadTaskManager`. This formed a retain cycle.
Make the reference from `URLSession` to the delegate weak and only keep `DownloadTaskManager` alive as long as `DownloadTask`s need it. This causes the `DownloadTaskManager` to be deallocated once nobody holds a reference to it anymore and all the tasks it manages are finished.
Finally, we need to call `invalidate` on the `URLSession` to tell it that we’re done and that it should release its delegate (which is now the `WeakDownloadTaskManager` wrapper).
This retain cycle was causing a leak in sourcekit-lsp. I verified that the leak no longer exists with this patch.
* **Scope**: The change should be transparent to all …

[6.0] Fix a memory leak in `DownloadTaskManager` and `DataTaskManager`

---

Sources/Workspace/InitPackage.swift

`argumentList` has been deprecated. We should use `arguments` instead.

Use `arguments` instead of `argumentList` in the macro template

---

Sources/Commands/SwiftTestCommand.swift
Sources/Commands/Utilities/TestingSupport.swift
Sources/PackageModel/SwiftSDKs/SwiftSDK.swift

This PR removes the constraint on Darwin that XCTest.framework must be present in order to build tests using swift-testing. On Darwin, XCTest is included as a framework inside Xcode, but if a developer installs the Xcode Command Line Tools instead of the full IDE, XCTest is not included. They then get a diagnostic of the form:
> error: XCTest not available: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
>    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
>    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk'
Which is a poor experience if they aren't even using XCTest.
This change, as a (positive) side effect, suppresses the same diagnostic when running …

On Darwin, allow XCTest to be missing if we're only building swift-testing tests.

---

Sources/PackageDescription/Product.swift

Fix indentation in `Product.swift`
Fix indentation in `Product.swift`

Fix indentation in `Product.swift`

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Sources/Build/BuildPlan/BuildPlan.swift
Sources/SPMTestSupport/MockBuildTestHelper.swift
Tests/BuildTests/ClangTargetBuildDescriptionTests.swift

CoreFoundation depends on dispatch, this dependency is implicit
and dispatch itself is bundled with swift toolchains. Let's add
a package specific workaround for Linux/Android targets to add
toolchain resources directory to search paths of clang build targets.
This is also a prerequisite for https://github.com/apple/swift-package-manager/pull/7423

Add a `swift-corelibs-foundation` specific workaround

---

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
Tests/BuildTests/ClangTargetBuildDescriptionTests.swift

This mirrors behavior of remote swift targets which suppress warnings as well.

Suppress warnings for remote Clang targets

---

Sources/Commands/SwiftTestCommand.swift
Sources/Commands/Utilities/TestingSupport.swift
Sources/PackageModel/SwiftSDKs/SwiftSDK.swift

**Explanation:** This PR removes the constraint on Darwin that XCTest.framework must be present in order to build tests using swift-testing. On Darwin, XCTest is included as a framework inside Xcode, but if a developer installs the Xcode Command Line Tools instead of the full IDE, XCTest is not included.
**Scope:** Improves swift-testing functionality by allowing developers to build test targets that use swift-testing without an implicit XCTest dependency. No source- or language-breaking changes.
**Issue:** N/A
**Original PR:** https://github.com/apple/swift-package-manager/pull/7426
**Risk:** Low; only impacts developers using Xcode CLTools on Darwin.
**Testing:** At-desk testing as well as CI runs. It is not possible to test the environment where the issue manifests in our CI because it …

[6.0] On Darwin, allow XCTest to be missing if we're only building swift-testing tests.

---

Sources/PackageModel/ArtifactsArchiveMetadata.swift
Sources/PackageModel/SwiftSDKs/SwiftSDKBundle.swift
Sources/SPMBuildCore/BinaryTarget+Extensions.swift
Tests/PackageModelTests/SwiftSDKTests.swift
Tests/SPMBuildCoreTests/ArtifactsArchiveMetadataTests.swift

Make `supportedTriples` optional in artifactbundle metadata
We don't have a good way to express a Swift SDK that can be used on any host platform except for listing up all possible platforms.
This change allows `supportedTriples` field to be null or missing to express that the SDK is universally usable.
Also this fixes a minor issue around `swift experimental-sdk configuration`, that did not take care of runtime compatibility of OS version in host triples.
SwiftPM now accepts host-platform independent Swift SDK

Make `supportedTriples` optional in artifactbundle metadata

---

Sources/PackageGraph/ModulesGraph+Loading.swift
Sources/PackageGraph/ModulesGraph.swift
Tests/PackageGraphTests/ModulesGraphTests.swift

Fixed a bug in the productDependencyNotFound error message
fix https://github.com/apple/swift-package-manager/issues/7398
The above issue suggests the following two defects.
1. package dependency resolution changes depending on the order of packages (alphabetical order)
2. the phrase "Did you meen..." in the error message in the error message is not on target.
The first problem is as described in the issue, if users rename the directory containing Package.swift from repro to zzz, the "Did you meen..." will appear. will appear. Essentially, the error minutes should be displayed in full, regardless of the name of the directory. This is due to the fact that the loop used to resolve dependencies depends on the alphabetical order of the directories and the side effect on allTargetName inside …

Improve error message about the PackageGraphError.productDependencyNotFound 

---

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Tests/BuildTests/BuildPlanTests.swift

**Explanation**: Projects that use C++ interop for some of the Swift targets were failing to build in test mode (`swift test`) because the generated test entry point target wasn't being compiled with C++ interop enabled.
**Scope**: Flags that are being passed to the entry point test target.
**Risk**: Low, this only affects projects that explicitly enable C++ interop in the package manifest on non-Darwin platforms only.
**Testing**: Added a build plan test.
**Issue**: rdar://125498997
**Reviewer**: @MaxDesiatov approved https://github.com/apple/swift-package-manager/pull/7428.
(cherry picked from commit f529daef40418e143ed501ff245109e061db190a)

🍒[cxx-interop] Propagate interop flag to the test entry point target
