swiftlang/swift-package-manager

Sources/Build/TestObservation.swift
🍒 https://github.com/apple/swift-package-manager/pull/7341
* **Explanation**:  `swift build --build-tests` fails on WASI after the experimental summary output, which is introduced in 5.10. This affects not only experimental-summary mode but also the default output mode.
* **Scope**: Test build targeting WebAssembly
* **Risk**: Low, only affects to WebAssembly targets
* **Testing**: Integration test with WebAssembly Swift SDK on CI is infeasible, so I manually tested. We can ensure there is no breakage on other platforms on CI.
* **Reviewer**: @MaxDesiatov 
* **Main branch PR**: https://github.com/apple/swift-package-manager/pull/7341
=> [5.10] Fix test runner build on WASI

.swiftformat
We require Swift 5.9 to build the package, so we can adopt 5.9-specific formatting tweak as well.
=> Update Swift version to 5.9 in `.swiftformat`

Sources/Basics/AuthorizationProvider.swift, Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/Basics/HTTPClient/URLSessionHTTPClient.swift, Sources/Build/BuildOperation.swift, Sources/PackageRegistry/RegistryClient.swift
Converted `DownloadTask` and `DataTask` to value types and added more `Sendable` annotations where needed.
=> Fix sendability warnings in `URLSessionHTTPClient`

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/PackageDescription/BuildSettings.swift, Sources/PackageDescription/LanguageStandardSettings.swift, Sources/PackageDescription/PackageDescriptionSerialization.swift, Sources/PackageDescription/PackageDescriptionSerializationConversion.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageModel/SwiftLanguageVersion.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
[Swift Forums pitch thread](https://forums.swift.org/t/pitch-swiftpm-swift-language-version-per-target/71067)
Add a new Swift target setting API, similar to `enable{Upcoming, Experimental}Feature`,
to specify a Swift language version that should be used to build the target, if such
version is not specified, fallback to the current language version determination logic.
Resolves: rdar://125732014
=> Implement per target swift version selection

Sources/PackageGraph/ModulesGraph.swift, Tests/FunctionalTests/PluginTests.swift
Bringing back `computeTestTargetsForExecutableTargets` on `ModulesGraph` via `@_spi(SwiftPMInternal)`.
=> Expose `computeTestTargetsForExecutableTargets` via SPI

Sources/XCBuildSupport/PIFBuilder.swift
In the process of generating PIF, I identified a missing case for VisionOS in the implementation of the `[PackageConditionProtocol].toPlatformFilters()`, which led to assertionFailure when Package's platforms included VisionOS. 
- Added a new case `.visionOS` in the switch statement within the `toPlatformFilters()` extension for `[PackageCondition]`. 
- Added a new static property `visionOSFilters` within `PIF.PlatformFilter` to define filters specific to VisionOS.
With these changes, PIFBuilder can now generate PIF without errors for packages that include VisionOS as a target
=> Add VisionOS platform support to `PIF.PlatformFilter`

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan.swift, Tests/BuildTests/ClangTargetBuildDescriptionTests.swift
- Explanation:
This mirrors behavior of remote swift targets which suppress warnings as well. Remote package warnings are generally not addressible anyway at the moment.
- Scope: Remote class targets.
- Main Branch PRs: https://github.com/apple/swift-package-manager/pull/7423
- Risk: Very Low
- Reviewed By: @bnbarham @MaxDesiatov   
- Testing: Added test-cases to the test suite.
=> [6.0]  Suppress warnings for remote Clang targets

Sources/PackageRegistryCommand/PackageRegistryCommand+Auth.swift
Fix empty token when adding a new package-registry and adding token interactively on release builds
When executing swift package-registry login it asks for a token but fails to retrieve it properly. It sends an empty string to the registry server and login therefore fails. (see https://github.com/apple/swift-package-manager/issues/7453)
I've debugged the code a bit and found out, that somehow `buffer` and `passwordPtr` don't seem to be holding correct values after the `readpassphrase` call.
- An easy quick fix is to make sure that `buffer` doesn't get deallocated by adding smth like `_ = buffer` after the String init. This works but is not nice.
- My first try was to use `buffer` instead of  `passwordPtr`  to create the string. These works, but I remember reading somewhere that `&` can be …
=> Fix empty token on swift package-registry login (Issue #7453)

Sources/Basics/CMakeLists.txt, Sources/Basics/Graph/AdjacencyMatrix.swift, Sources/Basics/Graph/DirectedGraph.swift, Sources/Basics/Graph/LinkageGraph.swift, Sources/Basics/Graph/UndirectedGraph.swift, Tests/BasicsTests/Graph/AdjacencyMatrixTests.swift, Tests/BasicsTests/Graph/DirectedGraphTests.swift, Tests/BasicsTests/Graph/UndirectedGraphTests.swift
`DirectedGraph` can be used to represent the existing modules graph in the `PackageGraph` module hopefully with better performance due to reduced number of allocations. `UndirectedGraph` could represent a new linkage graph concept, which would help with breaking dependency cycles for certain packages with products that don't have a linkage cycle.
=> Add `UndirectedGraph` and `DirectedGraph` data structures

Sources/Workspace/Workspace+State.swift
This "Returns true if the state file exists on the filesystem" doc comment was copy-pasted from a function above and is clearly wrong: `reload()` function doesn't return any values.
=> Remove outdated doc comment in `Workspace+State.swift`

Benchmarks/Benchmarks/PackageGraphBenchmarks/PackageGraphBenchmarks.swift, Benchmarks/README.md, Benchmarks/Thresholds/PackageGraphBenchmarks.PackageGraphLoading.p90.json
This records thresholds for two relatively stable metrics: total malloc count and total number of syscalls. We don't run these benchmarks on CI yet, but now it allows tracking regressions locally.
=> Add basic thresholds for `PackageGraphBenchmarks.swift`

Sources/PackageLoading/PkgConfig.swift, Tests/PackageLoadingTests/PkgConfigParserTests.swift, Tests/PackageLoadingTests/pkgconfigInputs/case_insensitive.pc, Tests/PackageLoadingTests/pkgconfigInputs/deps_variable.pc, Tests/PackageLoadingTests/pkgconfigInputs/double_sysroot.pc, Tests/PackageLoadingTests/pkgconfigInputs/dummy_dependency.pc, Tests/PackageLoadingTests/pkgconfigInputs/empty_cflags.pc, Tests/PackageLoadingTests/pkgconfigInputs/escaped_spaces.pc, Tests/PackageLoadingTests/pkgconfigInputs/failure_case.pc, Tests/PackageLoadingTests/pkgconfigInputs/not_double_sysroot.pc, Tests/PackageLoadingTests/pkgconfigInputs/quotes_failure.pc
Cherry pick of #7461 
SwiftPM's pkg-config implementation sets the `pc_sysrootdir` variable, but most `.pc` files do not use this variable directly. Instead, they rely on
the pkg-config tool rewriting the generated paths to include the sysroot prefix when necessary. SwiftPM does not do this, so it does not generate the correct compiler flags to use libraries from a sysroot.
This problem was reported in issue
https://github.com/apple/swift-package-manager/issues/7409
There are two major pkg-config implementations which handle sysroot differently:
*  `pkg-config` (the original https://pkg-config.freedesktop.org implementation) prepends sysroot after variable expansion, when it creates the compiler flag lists
*  `pkgconf` (the newer http://pkgconf.org implementation) prepends sysroot to …
=> [6.0] pkgconfig: Apply PKG_CONFIG_SYSROOTDIR when generating paths

Sources/Commands/PackageCommands/AddTarget.swift, Sources/PackageModelSyntax/AddPackageDependency.swift, Sources/PackageModelSyntax/AddTarget.swift, Sources/PackageModelSyntax/SyntaxEditUtils.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
When editing a package manifest to add a new macro target, also create a package dependency on swift-syntax and import CompilerPluginSupport. We need both so that the macro will build.
=> When adding a macro target to a package, create a dependency on swift-syntax

Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/AddProduct.swift, Sources/Commands/PackageCommands/SwiftPackageCommand.swift, Sources/PackageModelSyntax/AddProduct.swift, Sources/PackageModelSyntax/CMakeLists.txt, Sources/PackageModelSyntax/ProductDescription+Syntax.swift, Sources/PackageModelSyntax/SyntaxEditUtils.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
Introduce support for adding a new product to the package manifest,
both programmatically (via PackageModelSyntax) and via the
`swift package add-product` command. Help for this command is:
OVERVIEW: Add a new product to the manifest
USAGE: swift package add-product <name> [--type <type>] [--targets <targets> ...] [--url <url>] [--path <path>] [--checksum <checksum>]
ARGUMENTS:
<name>                  The name of the new product
OPTIONS:
--type <type>           The type of target to add, which can be one of
'executable', 'library', 'static-library',
'dynamic-library', or 'plugin' (default: library)
--targets <targets>     A list of targets that are part of this product
--url <url>             The URL for a remote binary target
--path <path>           The path to a local binary target …
=> [SE-0301] Add swift package add-product command and supporting library

Sources/PackageModelSyntax/CMakeLists.txt
Also, use `SPMSwiftSyntax::` namespace to avoid potential name conflict issues.
=> Only export required SwiftSyntax targets

Sources/Basics/Errors.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Resources.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/Resolution/ResolvedPackage.swift, Tests/BuildTests/ClangTargetBuildDescriptionTests.swift, Tests/CommandsTests/PackageCommandTests.swift
Modified `ResolvedModule` build triples were not reflected in `ResolvedPackage`, which excluded those modules from the build graph.
Verified manually with `swift-foundation` and `swift-testing` packages. More comprehensive automated tests will be included in a future PR.
Resolves https://github.com/apple/swift-package-manager/issues/7479.
=> Include host triple test modules in `ResolvedPackage`

BuildSupport/SwiftSyntax/CMakeLists.txt, Utilities/bootstrap
In the case that a shared copy of swift-syntax is being used to build, allow the sources to be unavailable. If the user specifies `SWIFTPM_PATH_TO_SWIFT_SYNTAX_SOURCE`, that will be preferred, otherwise, we fallback to the upstream git repository.
=> build: remove the requirement to checkout swift-syntax

Sources/PackageDescription/BuildSettings.swift, Sources/PackageDescription/Context.swift, Sources/PackageDescription/Product.swift, Sources/PackageDescription/Resource.swift, Sources/PackageDescription/SupportedPlatforms.swift, Sources/PackageDescription/Version.swift
- Explanation:
In preparation to enable Swift language version 6 when tools version allows we need to proactively annotate `PackageDescription` APIs with `Sendable`.
- Scope: `PackageDescription` APIs.
- Main Branch PRs: https://github.com/apple/swift-package-manager/pull/7475
- Risk: Very Low
- Resolves: N/A
- Reviewed By: @MaxDesiatov 
- Testing: Non-functional changes.
=> [6.0] NFC: Add `Sendable` annotations to PackageDescription APIs

Utilities/bootstrap, Utilities/build-using-self
This allows us to work around the following issue in CI: The self-hosted SwiftPM job has Xcode 15.3 (Swift 5.10) installed and builds a Swift 6 SwiftPM from source. It then tries to build itself as a fat binary using the just-built Swift 6 SwiftPM, which uses xcbuild from Xcode as the build system. But the xcbuild in the installed Xcode is too old and doesn't know about Swift 6 mode, so it fails with: SWIFT_VERSION '6' is unsupported, supported versions are: 4.0, 4.2, 5.0 (rdar://126952308). This is fixed by setting `SWIFTSYNTAX_DISABLE_SWIFT_6_MODE` in `build-using-self`.
The source compat suite is seeing the same issue, just by using `bootstrap`, so set it there as well.
Accompanies https://github.com/apple/swift-syntax/pull/2621
=> Set environment variable to disable building swift-syntax in Swift 6 mode

Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Target/SwiftTarget.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
XCBuild has its own notion of supported Swift versions which can differ from the ones SwiftPM's own build system and the used compiler support. Using a version outside of the supported range prevents building, so we'll try to obtain the list of supported versions and intersect it with the versions supported by a given package to find the best version supported by both.
=> Handle Swift versions unsupported by XCBuild

Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Target/SwiftTarget.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
XCBuild has its own notion of supported Swift versions which can differ from the ones SwiftPM's own build system and the used compiler support. Using a version outside of the supported range prevents building, so we'll try to obtain the list of supported versions and intersect it with the versions supported by a given package to find the best version supported by both.
(cherry picked from commit 3f9587c3930b2b910635ffeab05339d3c5c6c86d)
*Explanation*: XCBuild has its own notion of supported Swift versions that can be different from the toolchain/SwiftPM. To support packages that support multiple language versions, including Swift 6, we need to allow falling back to an older language version if the newest supported one is not supported by XCBuild.
*Scope*: Anyone using XCBuild from …
=> [6.0] Handle Swift versions unsupported by XCBuild

Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/TestingSupport.swift
After #7353 landed, I noticed that the build products for test targets were not being emitted correctly. swift-testing and XCTest produce separate build products (with distinct names) but this wasn't happening as intended. It turns out that the changes to split `buildParameters` into `productsBuildParameters` and `toolsBuildParameters` weren't fully propagated to our testing infrastructure.
I also noticed `SWIFT_PM_SUPPORTS_SWIFT_TESTING` wasn't being set correctly anymore (same root cause) although we've decided to ignore that flag over in swift-testing anyway (see https://github.com/apple/swift-testing/pull/376.)
This regression caused build failures in swift-testing (e.g. [here](https://ci.swift.org/job/pr-swift-testing-macos/663/console)) with the telltale failure signature:
> …
=> Fix test targets that depend on macros and `swift-testing`

Utilities/bootstrap, Utilities/build-using-self
Companion of https://github.com/apple/swift-syntax/pull/2627
- **Explanation**: This allows us to work around the following issue in CI: The self-hosted SwiftPM job has Xcode 15.3 (Swift 5.10) installed and builds a Swift 6 SwiftPM from source. It then tries to build itself as a fat binary using the just-built Swift 6 SwiftPM, which uses xcbuild from Xcode as the build system. But the xcbuild in the installed Xcode is too old and doesn't know about Swift 6 mode, so it fails with: SWIFT_VERSION '6' is unsupported, supported versions are: 4.0, 4.2, 5.0 (rdar://126952308). This is fixed by setting `SWIFTSYNTAX_DISABLE_SWIFT_6_MODE` in `build-using-self`.
The source compat suite is seeing the same issue, just by using `bootstrap`, so set it there as well.
- **Scope**: The build of SwiftPM …
=> [6.0] Set environment variable to disable building swift-syntax in Swift 6 mode

Sources/PackagePlugin/PluginContextDeserializer.swift, Tests/CommandsTests/PackageCommandTests.swift
SwiftPM sends information about the origin of each package dependency to the plugin process, but the `PluginContext` passed to the plugin function incorrectly shows all origins as `root`.
The necessary information is included correctly in the serialized structure sent to the plugin by SwiftPM.    The startup wrapper code in the plugin process correctly deserializes it but does not copy it into the final `PluginContext` struct which is passed to the plugin function; instead, `origin` is hard-coded to `.root`.
This change copies the dependency information into the final context struct.
Plugins receive correct information about package dependencies - `local`, with a local path, or `repository` with a URL, version number and revision hash.
=> plugins: Pass correct dependency origin information to plugins

Sources/PackagePlugin/PluginContextDeserializer.swift, Tests/CommandsTests/PackageCommandTests.swift
Cherry pick of https://github.com/apple/swift-package-manager/pull/7506
**Explanation**: SwiftPM sends information about the origin of each package dependency to the plugin process, but the `PluginContext` passed to the plugin function incorrectly shows all origins as `root`.
**Scope**: Isolated to `PackagePlugin/PluginContextDeserializer.swift`
**Risk**: Low, isolated to plugins.
**Testing**: Existing end-to-end automated test was modified to cover the fix.
**Issue**: rdar://127104161
**Reviewer**: @MaxDesiatov 
The necessary information is included correctly in the serialized structure sent to the plugin by SwiftPM.    The startup wrapper code in the plugin process correctly deserializes it but does not copy it into the final `PluginContext` struct which is passed to the plugin …
=> [6.0] plugins: Pass correct dependency origin information to plugins

Sources/PackageModel/ArtifactsArchiveMetadata.swift, Sources/PackageModel/SwiftSDKs/SwiftSDKBundle.swift, Sources/SPMBuildCore/BinaryTarget+Extensions.swift, Tests/PackageModelTests/SwiftSDKTests.swift, Tests/SPMBuildCoreTests/ArtifactsArchiveMetadataTests.swift
Cherry-pick of https://github.com/apple/swift-package-manager/pull/7432.
**Explanation**:  We don't have a good way to express a Swift SDK that can be used on any host platform except for listing up all possible platforms.  This change allows `supportedTriples` field to be null or missing to express that the SDK is universally usable. Also this fixes a minor issue around `swift experimental-sdk configuration`, that did not take care of runtime compatibility of OS version in host triples.
**Scope**: Isolated to Swift SDKs.
**Risk**: Low due to limited scope. Incubated on the `main` branch for 30 days with no known regressions.
**Testing**: Automated. New test cases to `ArtifactsArchiveMetadataTests.swift` and `SwiftSDKTests.swift`.
**Issue**: N/A
**Reviewer**: @MaxDesiatov on the original …
=> [6.0] Make `supportedTriples` optional in artifactbundle metadata

Fixtures/SwiftSDKs/Package.swift, Sources/SPMTestSupport/SwiftPMProduct.swift, Tests/CommandsTests/SDKCommandTests.swift
Previously these commands weren't covered with end-to-end tests. Now we verify that installation/listing/removal of a fixture Swift SDK succeeds, and also verify that `experimental-sdk` invocations issue a deprecation warning.
=> Add end-to-end tests for `sdk` and `experimental-sdk` commands

Sources/Commands/SwiftBuildCommand.swift, Tests/CommandsTests/BuildCommandTests.swift
This PR adds the `--enable-code-coverage` flag (from `swift test`) to `swift build` so that code coverage can be used in a two-stage build process (build, then execute later.)
Resolves rdar://127309781.
=> Add `swift build --enable-code-coverage`

Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMTestSupport/MockPackageGraphs.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/PackageGraphTests/CrossCompilationPackageGraphTests.swift
Library products declared with `.static` or `.dynamic` linkage didn't have a `-tools` suffix in their file names when built as dependencies of macros. This change resolves the inconsistency and adds corresponding build plan tests.
The regression in question broke the compatibility test suite, which had [an old version of `swift-power-assert`](https://github.com/kishikawakatsumi/swift-power-assert/blob/a60cb50/Package.swift) depending on an old version of `swift-syntax` with explicit `.static` linkage for its products.
rdar://127170225
=> Fix incorrect paths for library products with explicit linkage

Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
This is used so we don’t search for tests in targets of package dependencies.
Companion of https://github.com/apple/sourcekit-lsp/pull/1201
rdar://126965614
=> Report whether a target is part of the root package in the sourcekit-lsp API

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/PackageModel/Toolchain.swift, Sources/PackageModel/UserToolchain.swift, Sources/SPMTestSupport/MockBuildTestHelper.swift
SDK macro plugins are now provided within
`Platforms/<Platform>.platform/Developer/usr/lib/swift/host/plugins` now, which is always added by the driver.
=> Remove the addition of external-plugin-path for dev toolchains

BuildSupport/SwiftSyntax/CMakeLists.txt, Sources/PackageModelSyntax/CMakeLists.txt, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
- **Explanation**: Cherry-pick the following to PRs which are companions of https://github.com/apple/sourcekit-lsp/pull/1213
- https://github.com/apple/swift-package-manager/pull/7505
- https://github.com/apple/swift-package-manager/pull/7492
- **Scope**: CMake build and SourceKit-LSP API
- **Risk**: Low, the SourceKit-LSP API is only used by SourceKit-LSP and the CMake build changes will all be caught at build-time
- **Testing**: n/a
- **Issue**: n/a
- **Reviewer**:   @DougGregor and @MaxDesiatov on https://github.com/apple/swift-package-manager/pull/7505 and https://github.com/apple/swift-package-manager/pull/7492
=> Cherry-picks to `release/6.0` for sourcekit-lsp update

Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
The exportability rules around `package` access level are updated in a way that an `@_spi public` can't be bound to a `package` var, similar to how `@_spi public` can't be bound to a `public` var.  For reference, see https://github.com/apple/swift/pull/73161. 
This PR corrects such use case.
=> package -> @_spi public due to package exportability rule updates

Sources/Basics/SwiftVersion.swift
Add `Sendable` annotations to `SwiftVersion`.
I fixed warning for preparing Swift 6.
<table>
<thead>
<tr>
<td>Before</td>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
The warning has been corrected.
=> Add `Sendable` annotations to SwiftVersion

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/PackageModel/Toolchain.swift, Sources/PackageModel/UserToolchain.swift, Sources/SPMTestSupport/MockBuildTestHelper.swift
**Explanation**:  SDK macro plugins are now provided within `Platforms` and are added by default. There's no need to add an additional path to the toolchain. Doing so prevents the macros in the dev toolchain from being picked up.
**Scope**: Macros
**Risk**: Low, this path was added prior to macros moving into `Platforms`.
**Testing**: Source compat suite passes (which has various macro projects). We could theoretically test we're not adding the argument, but seems a bit weird to do so.
**Original PR**: https://github.com/apple/swift-package-manager/pull/7524
**Reviewer**: @MaxDesiatov
=> [6.0] Remove the addition of external-plugin-path for dev toolchains

Sources/swift-experimental-sdk/Entrypoint.swift, Sources/swift-package-manager/SwiftPM.swift, Tests/CommandsTests/SDKCommandTests.swift
Tools and scripts may rely on command output to remain parseable, so printing these warnings on `stdout` can break such workflows. We should output these warnings on `stderr` instead.
As these warnings are emitted before any logging is available, we're using `fputs` for output on `stderr`
=> `swift sdk`: print warnings on stderr instead of stdout

Sources/Commands/PackageCommands/AddTarget.swift, Sources/PackageModel/InstalledSwiftPMConfiguration.swift, Sources/PackageModelSyntax/AddTarget.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift, Utilities/config.json
Introduce a command-line argument `--testing-library` to the add-target
command to specify which test library to generate the test for. This
can be 'xctest' (the prior XCTest behavior), 'swift-testing' (to use the
new swift-testing library), or 'none' (for no test library at all).
For the new swift-testing generation, also add the appropriate package
and test target dependency, along with a stub testsuite to start from.
Fixes https://github.com/apple/swift-package-manager/issues/7478
=> Teach swift package add-target --type test about swift-testing 

Sources/Commands/PackageCommands/AddTarget.swift, Sources/PackageModel/InstalledSwiftPMConfiguration.swift, Sources/PackageModelSyntax/AddTarget.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift, Utilities/config.json
**Explanation**: Introduce a command-line argument `--testing-library` to the new add-target command to specify which test library to generate the test for. This can be 'xctest' (the prior XCTest behavior), 'swift-testing' (to use the new swift-testing library), or 'none' (for no test library at all).
**Original PR**: https://github.com/apple/swift-package-manager/pull/7481
**Risk**: Low. Extends new functionality in a new package command.
**Testing**: New tests.
=> [6.0] Teach swift package add-target --type test about swift-testing  (#7481)

Sources/Commands/SwiftTestCommand.swift
This PR adds two undocumented/unsupported experimental options to `swift test` to allow passing through JSON files/streams for input and output. These streams are still under development in swift-testing, so these options are not yet supported, but this change will allow interested coders to experiment with them.
=> Pass through swift-testing's experimental JSON streams from `swift test`

CHANGELOG.md, Sources/Basics/CMakeLists.txt, Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Commands/PackageCommands/CompletionCommand.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/PackageCommands/ShowDependencies.swift, Sources/Commands/Utilities/DependenciesSerializer.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/PackageGraph/Resolution/ResolvedPackage.swift, Sources/SPMBuildCore/Plugins/PluginContextSerializer.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/SPMTestSupport/PackageGraphTester.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/Workspace/Workspace+Signing.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/MermaidPackageSerializerTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
It should be possible for packages to depend on each other if such dependence doesn't introduce cycles in the build graph.
- Introduced a new DFS method to walk over graphs that breaks cycles.
- Replaces use of `findCycle` + `topologicalSort` with `DFS` while building manifest and package graphs. This allows cycles in dependencies to be modeled correctly.
- Removes some of the redundant data transformations from modules graph.
- Modifies `ResolvedPackage` to carry identities of its dependencies instead of resolved dependencies themselves. This helps to simplify logic in `createResolvedPackages`.
- Adds detection of target cycles across packages.
Makes it possible for package A to depend on package B and B to depend on A if their targets don't form a cycle.
=> [Package/ModuleGraph] Allow cyclic package dependencies if they don't introduce a cycle in a build graph

Sources/swift-experimental-sdk/Entrypoint.swift, Sources/swift-package-manager/SwiftPM.swift, Tests/CommandsTests/SDKCommandTests.swift
Cherry-pick of #7532.
**Explanation**: Tools and scripts may rely on command output to remain parseable, so printing these warnings on `stdout` can break such workflows. We should output these warnings on `stderr` instead.
As these warnings are emitted before any logging is available, we're using `fputs` for output on `stderr`
**Scope**: Isolated to `swift sdk` command and subcommands.
**Risk**: Low, the actual change is only 4 lines touching `print` and `import`, code coverage for those is present.
**Testing**: End-to-end test cases present in `Tests/CommandsTests/SDKCommandTests.swift`
**Issue**: N/A
=> [6.0] `swift sdk`: print warnings on stderr instead of stdout

Sources/Build/BuildDescription/ProductBuildDescription.swift, Sources/PackageModel/Target/Target.swift
**Explanation**: `buildSettingsDescription` needs to be accessed in SwiftPM client code.
**Scope**: a single property of `PackageModel.Target`.
**Risk**: none, change is NFC and builds successfully.
**Testing**: NFC.
**Issue**: rdar://127782783
=> [6.0] Mark `buildSettingsDescription` as `@_spi` in `Target.swift`

Sources/Build/BuildDescription/ProductBuildDescription.swift, Sources/PackageModel/Target/Target.swift
=> Mark `buildSettingsDescription` as `@_spi` in `Target.swift`

Sources/PackageGraph/ModulesGraph.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
- Add an API to get the name of a target from SourceKit-LSP 
- We will need this API to prepare a target for indexing.
- Add an API to get all the targets in a build description / modules graph in a topological order
- We need this for background preparation for indexing so that we can prepare and index lower-level targets first.
=> Add API for background preparation in SourceKit-LSP

Fixtures/Miscellaneous/Plugins/DependentPlugins/Package.swift, Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MySourceGenBuildTool/main.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MySourceGenBuildTool/main.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPluginUsingURLBasedAPI/Sources/MySourceGenBuildTool/main.swift, Fixtures/Miscellaneous/Plugins/PluginWithInternalExecutable/Sources/PluginExecutable/main.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SPMTestSupport/XCTSkipHelpers.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/BuildSystemDelegateTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/ResourcesTests.swift, Tests/PackageLoadingTests/ManifestLoaderCacheTests.swift, Tests/PackageLoadingTests/PD_6_0_LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageModelTests/ToolsVersionTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
We missed updating this when adding 6.0. The change itself is extremely
simple, with the bulk being updates to our tests so they don't fail on
old compiler versions (where language version "6" is unknown).
Also removes disabling the concurrency and string processing imports
from manifest loading, as this was causing the `package` global to not
be main actor isolated by default and thus error in Swift 6. They seemed
to have been disabled to avoid erroring in SDKs that didn't have them,
but that is definitely not an issue any longer.
=> Update -swift-version to default to 6 for swift-tools-version 6

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Target/SwiftTarget.swift, Sources/SPMTestSupport/ResolvedTarget+Mock.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
The value of this field is computed based on the tools version of the manifest and is intended to be used as a fallback if there is no swift language version specified in the build settings for a swift target.
Renamed `SwiftTarget.swiftVersion` field and `PackageBuilder.swiftVersion()` method to `toolsSwiftVersion`.
Code better reflects meaning and intended uses of the data.
=> [PackageModel] SwiftTarget: Rename `swiftVersion` into `toolsSwiftVersion`

Sources/Commands/SwiftTestCommand.swift
Follow-on to #7534. swift-testing has an additional argument specifying the schema version of the JSON being used that we also need to pass through SwiftPM.
See: https://github.com/apple/swift-testing/pull/383
=> Pass through `--experimental-event-stream-version` to swift-testing.

Sources/PackageLoading/Platform.swift, Sources/PackageLoading/TargetSourcesBuilder.swift
- Mark `FileRuleDescription` as `Sendable`
- Make `Platform` sendable and make `Platform.current` a constant
=> Add two `Sendable` annotations to enable building SourceKit-LSP in Swift 6 mode

Utilities/bootstrap, Utilities/build-using-self
This shouldn’t be needed anymore with https://github.com/apple/swift-package-manager/pull/7504.
=> Don’t disable Swift 6 mode in swift-syntax

Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
If we have a package like this
```swift
name: "MyLibrary",
targets: [
.target(name: "Lib"),
.executableTarget(name: "MyExec", dependencies: ["Lib"]),
.plugin(
name: "MyPlugin",
capability: .command(
intent: .sourceCodeFormatting(),
permissions: []
),
dependencies: ["MyExec"]
)
]
)
```
Then the package graph contains two targets for `Lib`. We need to be able to differentiate them in SourceKit-LSP. For that, we need to expose the build triple of a `BuildTarget`.
=> Expose the build triple of a `BuildTarget` in `SourceKitLSPAPI`

Sources/PackageModelSyntax/AddTargetDependency.swift, Sources/PackageModelSyntax/CMakeLists.txt, Sources/PackageModelSyntax/ManifestEditError.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
As a convenience for when we want to be able to add new target dependencies, introduce a manifest editing API that adds a new target dependency to an existing target in the manifest.
=> Introduce manifest editing API for "add target dependency"

CODEOWNERS
- Removes Tom Doron
- Adds Jake Petroules and Francesco Mikulis-Borsoi
=> NFC: Updates to code owners file

Sources/PackageGraph/ModulesGraph.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
- **Explanation**: Adds a couple of APIs to the `SourceKitLSPAPI` module that are needed for background indexing in SourceKit-LSP
- **Scope**: Purely additive API
- **Risk**: Very low, just adds new API
- **Testing**: n/a
- **Issue**: n/a
- **Reviewer**: @MaxDesiatov and @bnbarham on https://github.com/apple/swift-package-manager/pull/7540 https://github.com/apple/swift-package-manager/pull/7555 respectively
=> Add API needed for background indexing in SourceKit-LSP

Sources/Commands/SwiftTestCommand.swift
Explanation: Pass through `--experimental-configuration-path`, `--experimental-event-stream-output`, and `--experimental-event-stream-version` as used by swift-testing. These flags are needed for continued experimental support of swift-testing when using the Swift 6 toolchain.
Scope: Hidden flags in `swift test`.
Original PR: #7534, #7551
Risk: No obvious risk. These flags have no effect on `swift test` itself and are simply passed through verbatim to the swift-testing test executable.
Testing: Tested at-desk that the flags are seen by swift-testing with an appropriate toolchain.
Reviewer: @bnbarham, @MaxDesiatov, @stmontgomery
=> [6.0] Pass through experimental swift-testing flags

Sources/Commands/SwiftBuildCommand.swift, Tests/CommandsTests/BuildCommandTests.swift
Explanation: Add `--enable-code-coverage` to `swift build`. This flag allows enabling code coverage when splitting a test run between `swift build` and `swift test --skip-build`.
Scope: New option for the `swift build` command.
Original PR: #7508 (partial), #7518
Risk: Low. Behaviour is identical for `swift build` without the new flag, and the new flag must be explicitly specified.
Testing: Ran `swift build` unit tests at desk and in CI.
Reviewer: @bnbarham, @MaxDesiatov, @stmontgomery
=> [6.0] Add `--enable-code-coverage` to `swift build`

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Tests/CommandsTests/TestCommandTests.swift
On Linux, Windows, etc. (anywhere that uses swift-corelibs-xctest instead of XCTest.framework), SwiftPM is responsible for generating an entry point function that passes in all tests discovered at compile time. The compiler cannot tell whether the generated code is concurrency-safe. This PR modifies the generated code and makes it main-actor-isolated. Since it's only ever used in the program's main function, this is safe.
Note that `@main func main()` is implicitly main-actor-isolated per [SE-0323](https://github.com/apple/swift-evolution/blob/main/proposals/0323-async-main-semantics.md).
Resolves #7556.
=> Generated code for XCTest on non-Darwin needs to be actor-isolated.

Sources/PackageLoading/Platform.swift, Sources/PackageLoading/TargetSourcesBuilder.swift
* **Explanation**: Mark `FileRuleDescription` and `Platform` as `Sendable` and make `Platform.current` a constant. This allows us to build SourceKit-LSP in Swift 6 mode
* **Scope**: `FileRuleDescription` and `Platform` if SwiftPM is used as a library
* **Risk**: Very low, adding `Sendable` conformances is safe and I don’t expect anyone to modify `Platform.current`
* **Testing**: Verified that this helps us build SourceKit-LSP in Swift 6 mode
* **Issue**: n/a
* **Reviewer**:  @xedin on https://github.com/apple/swift-package-manager/pull/7553
=> Add two Sendable annotations to enable building SourceKit-LSP in Swift 6 mode

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift, Tests/CommandsTests/TestCommandTests.swift
Explanation: Ensure that the synthesized entry point for swift-corelibs-xctest is concurrency-safe by marking it `@MainActor`.
Scope: All XCTest-based tests built/run on non-Darwin platforms.
Original PR: #7566
Risk: Low. The change is necessary to suppress a concurrency diagnostic. The synthesized `main()` function is implicitly main-actor-isolated.
Testing: Added unit test to check for the diagnostic, verified it did not occur anymore with the change in place.
Reviewer: @bnbarham, @MaxDesiatov, @stmontgomery, @briancroom
=> [6.0] Generated code for XCTest on non-Darwin needs to be actor-isolated.

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift, Sources/Build/BuildDescription/PluginDescription.swift, Sources/Build/BuildDescription/ProductBuildDescription.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildDescription/TargetBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/PackageCommands/DumpCommands.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/PackageGraph/Resolution/PlatformVersionProvider.swift, Sources/PackageGraph/Resolution/ResolvedPackage.swift, Sources/PackageGraph/Resolution/ResolvedProduct.swift, Sources/PackageGraph/Resolution/ResolvedTarget.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SPMBuildCore/Plugins/PluginContextSerializer.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/SPMBuildCore/ResolvedPackage+Extensions.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Sources/XCBuildSupport/PIFBuilder.swift
- Explanation:
With host/target triples separation in the SwiftPM codebase, it gets very confusing whether at a given moment "target" refers to a module, a triple, or a low level build system target.
Renamed `ResolvedTarget` to `ResolvedModule`. Added a deprecated `typealias ResolvedTarget = ResolvedModule` to allow graceful migration for users of this type.
Confusion between target triples and package targets is reduced.
This has no impact on how these concepts are named in user-visible APIs like `PackageDescription` and `PackagePlugin`, target there can stay as "target" for as long as needed.
Remaining internal uses of "target" outside of "target triple" context, like `*TargetBuildDescription` will be renamed in future PRs.
- Scope: NFC change
- Main Branch PRs: …
=> [6.0] NFC: Rename `ResolvedTarget` to `ResolvedModule`

Sources/PackageGraph/ModulesGraph.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
=> Update diagnostics for duplicated product/target names

Fixtures/Miscellaneous/CheckTestLibraryEnvironmentVariable/Package.swift, Fixtures/Miscellaneous/CheckTestLibraryEnvironmentVariable/Tests/CheckTestLibraryEnvironmentVariableTests/CheckTestLibraryEnvironmentVariableTests.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/TestingSupport.swift, Tests/CommandsTests/TestCommandTests.swift
This PR sets a new environment variable `"SWIFT_PM_TEST_LIBRARY"` to the name of the active testing library (`"XCTest"` or `"swift-testing"`.) Code in these libraries can then use the presence of this environment variable to adjust their behaviour.
Resolves rdar://128272138.
=> Set an environment variable in `swift test` to indicate which testing library is in use.

Fixtures/Miscellaneous/CheckTestLibraryEnvironmentVariable/Package.swift, Fixtures/Miscellaneous/CheckTestLibraryEnvironmentVariable/Tests/CheckTestLibraryEnvironmentVariableTests/CheckTestLibraryEnvironmentVariableTests.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/TestingSupport.swift, Tests/CommandsTests/TestCommandTests.swift
**Explanation**: Allows swift-testing and XCTest to detect at runtime which testing library SwiftPM is trying to run so that they can adjust their behaviour (e.g. `XCTestScaffold`) appropriately.
**Scope**: Test build products at runtime.
**Risk**: Low. No obvious risk here to adding a new environment variable nobody is looking for.
**Testing**: New unit test (tested at desk, but must be temporarily disabled in CI until CI is running a version of SwiftPM that includes the change.)
**Original PR**: https://github.com/apple/swift-package-manager/pull/7573
=> [6.0] Set an environment variable in `swift test` to indicate which testing library is in use.

Sources/PackageGraph/ModulesGraph.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- Explanation:
Improves diagnostic messages for duplicate product/target to include involved packages and other useful information.
- Scope: Package manifests/graphs with duplicate product/target names.
- Main Branch PRs: https://github.com/apple/swift-package-manager/pull/7572
- Resolves: rdar://127623219
- Risk: Very Low
- Reviewed By: @xedin 
- Testing: New tests were added to the suite and existing tests updated.
(cherry picked from commit e5123e483c18bff7afdc3b2029f9e1924779bbc8)
=> [6.0] Update diagnostics for duplicated product/target names

Fixtures/Miscellaneous/Plugins/DependentPlugins/Package.swift, Fixtures/Miscellaneous/Plugins/MyBuildToolPluginDependencies/Sources/MySourceGenBuildTool/main.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MySourceGenBuildTool/main.swift, Fixtures/Miscellaneous/Plugins/MySourceGenPluginUsingURLBasedAPI/Sources/MySourceGenBuildTool/main.swift, Fixtures/Miscellaneous/Plugins/PluginWithInternalExecutable/Sources/PluginExecutable/main.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageModel/ToolsVersion.swift, Sources/SPMTestSupport/XCTSkipHelpers.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/BuildSystemDelegateTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/ResourcesTests.swift, Tests/PackageLoadingTests/ManifestLoaderCacheTests.swift, Tests/PackageLoadingTests/PD_6_0_LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageModelTests/ToolsVersionTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
**Explanation**: Changes packages to default to swift version 6 when `swift-tools-version` is set `>= 6.0`. Without this change, all packages will be swift version 5 unless otherwise specified via `swiftLanguageVersions`. Packages default to `swift-tools-version: 6.0` with `swift package init`. Users can opt-out via specifying `swiftLanguageVersions: [.v5]`.
**Scope**: New packages/those updated to 6.0.
**Risk**: Medium. There's inherent risk due to the language mode bump. The change also removes disabling implicit imports for concurrency and string processing in manifest files, which hasn't been widely tested outside of ...
**Testing**: New regression tests. Source compatibility suite run.
**Original PR**: https://github.com/apple/swift-package-manager/pull/7469
=> [6.0] Update -swift-version to default to 6 for swift-tools-version 6

Sources/Commands/PackageCommands/CompletionCommand.swift, Tests/CommandsTests/PackageCommandTests.swift
Rename `swift package completion-command` back to `swift package completion-tool`.
The subcommand seems accidentally renamed to `swift package completion-command` while renaming the type name in https://github.com/apple/swift-package-manager/pull/7336
This change renames it back to `swift package completion-tool` to keep compatibility with the previous version.
This should be cherry-picked to release/6.0 too.
Keep command name compatibility
=> Rename back to `swift package completion-tool`

Sources/PackageLoading/TargetSourcesBuilder.swift
I found that the `FileRuleDescription` doesn't conform to `Sendable`; due to this, some products fail to build for Swift 6.
Some structs conform to `Sendable`
I passed to build on the latest Swift 6.0 snapshot.
```
TOOLCHAINS=org.swift.600202404301a swift build
```
=> Add Sendable to FileRuleDescription

Sources/Commands/PackageCommands/CompletionCommand.swift, Tests/CommandsTests/PackageCommandTests.swift
**Explanation**: Renames the accidentally renamed subcommand back to `swift package completion-tool` keep compatibility with the previous version.
**Scope**: Shell completion helper tool
**Risk**: Low. 
**Testing**: Added a new test to ensure the subcommand name
**Original PR**: https://github.com/apple/swift-package-manager/pull/7600
**Reviewers**: @MaxDesiatov
=> [6.0] Rename back to `swift package completion-tool`

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildOperation.swift, Sources/CoreCommands/BuildSystemSupport.swift, Sources/swift-bootstrap/main.swift, Tests/BuildTests/BuildOperationTests.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/LLBuildManifestBuilderTests.swift
The build database should be shared between different triple builds to re-generate the build manifest correctly.
With the current implementation, the following build command sequence fails:
```
$ swift build --experimental-swift-sdk wasm32-unknown-wasi
$ swift build
$ swift build --experimental-swift-sdk wasm32-unknown-wasi
$ swift build
$ swift build --experimental-swift-sdk wasm32-unknown-wasi
```
This changes the llbuild build database to be placed under `.build/build.db` instead of `.build/<product triple>/build.db`.
Also this change splits llbuild target names for each triple to avoid cache invalidation when switching triple.
`build.db` will be shared across product target triples, and SwiftPM will keep consistent cache state when switching triples.
=> Place build.db under the scratch directory

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Tests/BuildTests/BuildPlanTests.swift
Cherry-pick of https://github.com/apple/swift-package-manager/pull/7263.
**Explanation**:  `#if canImport(LibFoo, _version: "1.2.3")` is not currently supported by SwiftPM, as this feature was gated on `.vNext`, even though it landed before SwiftPM 5.10 branched off.
**Scope**: Isolated to llbuild build manifests and packages that have 6.0 set as their tools version.
**Risk**: Low as covered with a test and gated to 6.0 tools version, so shouldn't impact existing packages.
**Testing**: Existing `testPackageDependencySetsUserModuleVersion` case updated to check for 6.0 version.
**Issue**: rdar://121124842
=> [6.0] Enable `-user-module-version` for 6.0

Package.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift
This PR makes a necessary update to the source in order to support building against swift-collections 1.1
swift-collections added a new API in v1.1:
```swift
extension OrderedSet {
@inlinable
public func filter(
_ isIncluded: (Element) throws -> Bool
) rethrows -> Self
}
```
swift-package-manager was previously calling `filter` on an `OrderedSet` and expecting to get back an `Array` (via the extension on `Sequence`) however with this new swift-collections change, the returned value of `filter` became an `OrderedSet`. This caused build failures when the `+=` operator (which exists for `Array` but not `OrderedSet` operands) was used on the return value.
We should update this code to support swift-collections 1.1 so that we can begin using swift-collections 1.1 in toolchain builds.
The code …
=> Add support for swift-collections 1.1

CHANGELOG.md, Sources/Basics/CMakeLists.txt, Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Commands/PackageCommands/CompletionCommand.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/PackageCommands/ShowDependencies.swift, Sources/Commands/Utilities/DependenciesSerializer.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/PackageGraph/Resolution/ResolvedPackage.swift, Sources/SPMBuildCore/Plugins/PluginContextSerializer.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/Workspace/Workspace+Signing.swift, Sources/Workspace/Workspace.swift, Tests/CommandsTests/MermaidPackageSerializerTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- Explanation:
It should be possible for packages to depend on each other if such
dependence doesn't introduce cycles in the build graph.
- Introduced a new DFS method to walk over graphs that breaks cycles.
- Replaces use of `findCycle` + `topologicalSort` with `DFS` while
building manifest and package graphs. This allows cycles in dependencies
to be modeled correctly.
- Removes some of the redundant data transformations from modules graph.
- Modifies `ResolvedPackage` to carry identities of its dependencies
instead of resolved dependencies themselves. This helps to simplify
logic in `createResolvedPackages`.
- Adds detection of target cycles across packages.
Makes it possible for package A to depend on package B and B to depend
on A if their targets don't form a cycle.
- Scope: Package …
=> [6.0][Package/ModuleGraph] Allow cyclic package dependencies if they don't introduce a cycle in a build graph

Package.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift
Cherry pick of https://github.com/apple/swift-package-manager/pull/7607
**Explanation:**  SwiftPM fails to build against swift-collections@1.1, this change allows SwiftPM to be compatible with both swift-collections@1.0 and swift-collections@1.1
**Scope:** Isolated to one specific line where the build failure occurred and initializes the return value to an `Array` explicitly
**Risk:** Low as the change is minimal and has been validated via testing
**Testing:** Existing SwiftPM testing has passed and I have been able to build a toolchain locally with the change
**Reviewer:** @MaxDesiatov
=> [6.0] Add support for swift-collections 1.1

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/LLBuildManifest/LLBuildManifest.swift, Tests/FunctionalTests/ResourcesTests.swift
SwiftPM's incremental build did not detect changes in embedded resources.
SwiftPM's `embedInCode` feature did not detect changes in the resource files and it led to using old resource contents even though they were modified.
You can reproduce it with the fixture in this repository like below:
```console
$ rm -rf Fixtures/Resources/EmbedInCodeSimple/.build
$ swift run --package-path Fixtures/Resources/EmbedInCodeSimple
hello world
$ echo "update 1" > Fixtures/Resources/EmbedInCodeSimple/Sources/EmbedInCodeSimple/best.txt
$ swift run --package-path Fixtures/Resources/EmbedInCodeSimple
update 1
$ echo "update 2" > Fixtures/Resources/EmbedInCodeSimple/Sources/EmbedInCodeSimple/best.txt
$ swift run --package-path Fixtures/Resources/EmbedInCodeSimple
update 1
```
The first update ("update 1") …
=> Fix incremental builds for `embedInCode` resources

.gitignore, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildOperation.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/LLBuildManifest/LLBuildManifest.swift, Sources/LLBuildManifest/Tools.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Debugging.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/PrepareForIndexTests.swift
This will be used by sourcekit-lsp to build the swiftmodule files it needs for indexing.
Adds experimental-prepare-for-indexing flag to swift build. Creates a llbuild manifest specific for the prepare build that skips generating object files and linking of those files and calls swiftc to only create the swiftmodule as quickly as it can.
To support background indexing in sourcekit-lsp, it will request a prepare for index build to build the swiftmodule files it needs to do indexing. This build should be minimal to ensure indexing is fast so it can respond to language server requests that require the index as soon as possible.
- Add an experimental-prepare-for-indexing flag to the BuildOptions and pass it around to every that needs it.
- Build a custom llbuild manifest so that only the …
=> Add prepare for index experimental build argument

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Reverts unifying `main` to be async.
Amazon Linux 2 has been crashing (see below) in almost every test run since this change. It appears the crash existed before it, it's just *much* more consistent now.
Not clear if this is the backtrace every time, it's almost always just `getrn`, but we have seen this once:
```
0      0x0000ffffa4e4b948 getrn + 136 in libcrypto.so.1.0.2k
1 [ra] 0x0000ffffa4e4bddc lh_delete + 55 in libcrypto.so.1.0.2k
2 [ra] 0x0000ffffa4e4eaac int_thread_del_item + 123 in libcrypto.so.1.0.2k
3 [ra] 0x0000ffffa4e4f564 ERR_error_string + 151 in libcrypto.so.1.0.2k
4 [ra] 0x0000ffffa5316d68 Curl_close + 135 in libcurl.so.4.8.0
5 [ra] 0x0000ffffa52c2374 Curl_conncache_close_all_connections + 371 in libcurl.so.4.8.0
6 [ra] 0x0000ffffa52f8884 curl_multi_cleanup + 215 in …
```
=> Partially revert #7566 to fix amazon linux 2 crash

Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Reverts unifying `main` to be async.
Amazon Linux 2 has been crashing (see below) in almost every test run since this change. It appears the crash existed before it, it's just *much* more consistent now.
Not clear if this is the backtrace every time, it's almost always just `getrn`, but we have seen this once:
```
0      0x0000ffffa4e4b948 getrn + 136 in libcrypto.so.1.0.2k
1 [ra] 0x0000ffffa4e4bddc lh_delete + 55 in libcrypto.so.1.0.2k
2 [ra] 0x0000ffffa4e4eaac int_thread_del_item + 123 in libcrypto.so.1.0.2k
3 [ra] 0x0000ffffa4e4f564 ERR_error_string + 151 in libcrypto.so.1.0.2k
4 [ra] 0x0000ffffa5316d68 Curl_close + 135 in libcurl.so.4.8.0
5 [ra] 0x0000ffffa52c2374 Curl_conncache_close_all_connections + 371 in libcurl.so.4.8.0
6 [ra] 0x0000ffffa52f8884 curl_multi_cleanup + 215 in …
```
=> [6.0] Partially revert #7566 to fix amazon linux 2 crash

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildDescription/TargetBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Tests/BuildTests/BuildPlanTests.swift
In order to extract symbol graphs for modules with transitive imports on C++ modules we need parse headers in C++ interop mode using the option: `-cxx-interoperability-mode=default`. This commit updates `swift-symbolgraph-extract` to pass the option when there is a C++ module in the import graph.
This option is a new addition to `swift-symbolgraph-extract` added in apple/swift#73963.
Prior to this option's introduction, extracting the symbol graph for C++ dependent modules would fail with an error similar to: "unknown type name 'namespace'".
With this SwiftPM commit and `swift-symbolgraph-extract` _prior_ to apple/swift#73963, users will instead see an argument parsing error like: "unknown option -cxx-interoperability-mode".
With this change and `swift-symbolgraph-extract` change in …
=> Add cxx interop support to symbolgraph-extract

Package.swift, Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/AddTargetDependency.swift, Sources/Commands/PackageCommands/SwiftPackageCommand.swift, Tests/CommandsTests/PackageCommandTests.swift
Introduce a command to add a new dependency to a target in the manifest file, exposing the newly-added API to the command line. Here's the help output:
OVERVIEW: Add a new target dependency to the manifest
USAGE: swift package add-target-dependency <dependency-name> <target-name> [--package <package>]
ARGUMENTS:
<dependency-name>       The name of the new dependency
<target-name>           The name of the target to update
OPTIONS:
--package <package>     The package in which the dependency resides
--version               Show the version.
-h, -help, --help       Show help information.
=> Add `swift package add-target-dependency` command to edit the manifest

Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Tests/BuildTests/PrepareForIndexTests.swift
This allows the C module to be targeted directly with the --target argument. It is a no-op however, since the output of C modules are not required for indexing.
=> Add destination C module targets so you can prepare them directly.

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/LLBuildManifest/LLBuildManifest.swift, Tests/FunctionalTests/ResourcesTests.swift
**Explanation**: Fix a build system hole that incremental build did not detect changes in embedded resources.
**Scope**: Incremental build with `embedInCode` feature
**Risk**: Low. 
**Testing**: Added a new test to cover the incremental build case.
**Original PR**: https://github.com/apple/swift-package-manager/pull/7616
**Reviewers**: @MaxDesiatov
=> [6.0] Fix incremental builds for `embedInCode` resources

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildDescription/TargetBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Tests/BuildTests/BuildPlanTests.swift
Fixes an architecture and implementation bug where the include paths
for `swift-symbolgraph-extract` were being determined inside build plan
instead of by the target build description. This bug resulted in the
wrong set of paths being determined.
The new code moves the path determination logic into the proper target
build descriptions and releverages the already computed include paths.
The result of this is symbol graphs can be generated for Swift and C
targets properly now without duplicate module in the search paths and
with correct `-fmodule` usage.
=> Fix `swift-symbolgraph-extract` search paths

Sources/Basics/Collections/IdentifiableSet.swift
Turns `IdentifiableSet` into an ordered collection which should cut on flakiness in tests and other spots that expect certain ordering of elements.
Changes `storage` of `IdentifiableSet` from `Dictionary` to `OrderedDictionary`.
Less flakiness throughout.
=> [Basics] Switch `IdentifiableSet` to use `OrderedDictionary`

Package.swift, Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/AddTargetDependency.swift, Sources/Commands/PackageCommands/SwiftPackageCommand.swift, Tests/CommandsTests/PackageCommandTests.swift
**Explanation**: Building on SE-0301, add a new command `swift package add-target-dependency` to edit the package manifest and add a new dependency to a given target. 
**Original** PR: https://github.com/apple/swift-package-manager/pull/7594
**Risk**: Low. New, very simple code path to edit the package manifest in a narrow way.
**Reviewed by**: @MaxDesiatov
=> [6.0] Add `swift package add-target-dependency` command to edit the manifest

Utilities/bootstrap
llbuild's `utils/adjust-times` executable can't be linked on Ubuntu Jammy with a plain `clang` invocation, which doesn't link C++ standard library. Replacing that `clang` invocation with `clang++` fixes the issue.
=> Fix `clang` linker driver issue in the bootstrap script

Utilities/Docker/Dockerfile
Versions of Swift and Ubuntu specified in this `Dockerfile` are too old to successfully build SwiftPM. Let's update them to make this `Dockefile` usable again.
=> Update versions in `Utilities/Docker/Dockerfile`

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
I have confirmed it's no longer necessary in latest 6.0 toolchain.
=> Remove --enable-library-evolution flag on prepare.

BuildSupport/SwiftSyntax/CMakeLists.txt, CMakeLists.txt
Versions older than 3.24 don't support `GLOBAL` argument of `find_package` and this leads to obscure errors with older versions of CMake. See https://cmake.org/cmake/help/latest/release/3.24.html#commands for the detailed CMake 3.24 changelog. We should specify the required version explicitly to avoid this.
=> Require CMake 3.24 in `CMakeLists.txt`

Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Stop using a fake invalid module to satisfy `canImport` check for testing as swift compiler will start to evaluate such checks to false in the future.
Instead, using a valid swift interfacefile to satisify the external module import dependency.
In order for change in https://github.com/apple/swift/pull/74199 to land, update swiftpm tests to stop using invalid swiftmodule.
=> [Tests] Don't use invalid module to satisfy `canImport` check

Sources/Build/BuildOperation.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/SPMTestSupport/MockPackageGraphs.swift, Tests/BuildTests/BuildOperationTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/PackageGraphTests/CrossCompilationPackageGraphTests.swift
This is a temporary fix until we can figure out a proper way to
handle situations were all we get is a name of a product or a
target.
Callers or `ModulesGraph.{product, target}(for:destination:)` cannot always know the right `destination` to use at the moment because i.e. for test products and targets its contextual. We need a proper fix for this at the level or BuildSystem but for now sinking the logic down into `ModulesGraph` is the safest option.
- `ModulesGraph.{product, target}(for:destination:)` can handle fallback if product/target turn out to be a macro, a plugin or a test.
`--target` and `--product` options should work correctly regardless of underlying product/target kind.
Resolves: rdar://129400066
=> [Build/PackageGraph]  Sink fallback logic for macro/plugin/test products and packages identification into `ModulesGraph`

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Foundation added this conformance on their side in `main` (https://github.com/apple/swift-corelibs-foundation/pull/4963) and `release/6.0` (https://github.com/apple/swift-corelibs-foundation/pull/4978).
rdar://129599679
=> Remove `Sendable` conformance on `Bundle` from SwiftPM

Package.swift
This replaces #7649 (which proposed the same change on the 5.10 branch, I'l open a PR to cherry-pick back to 5.10 and 6.0 as well)
Referencing the rationale from the original PR:
We're currently being held back from pulling in Vapor and NIO updates due to tighter dependency clauses on swift-system and swift-certificates in SwiftPM.
We need to depend on SwiftPM in order to use the package collection signing module. We do this by depending on `revision: "swift-5.10.1-RELEASE"` in the SwiftPackageIndex server project.
=> Relax version ranges for dependencies in `Package.swift`

Package.swift, Sources/PackageGraph/PubGrub/PubGrubDependencyResolver.swift
Cherry-pick of #7655 and 1c626233f51e66af2e08f3a6d0939504a0fe476a
**Explanation**: Swift Package Index is currently held back from pulling in Vapor and NIO updates due to tighter dependency clauses on `swift-system` and `swift-certificates` in SwiftPM, as it needs to depend on SwiftPM in order to use the package collection signing module.
**Scope**: isolated to versions of dependencies in `Package.swift`
**Risk**: very low, the actual versions in toolchain builds are untouched as they're pinned in the `update-checkout-config.json` file of `swift` repository.
**Testing**: covered by existing tests and the compat suite.
**Issue**: N/A
**Reviewer**: @MaxDesiatov, @bnbarham
=> [5.10] Relax version ranges for dependencies in `Package.swift`

Package.swift
Cherry-pick of #7655
**Explanation**: Swift Package Index is currently held back from pulling in Vapor and NIO updates due to tighter dependency clauses on `swift-system` and `swift-certificates` in SwiftPM, as it needs to depend on SwiftPM in order to use the package collection signing module.
**Scope**: isolated to versions of dependencies in `Package.swift`
**Risk**: very low, the actual versions in toolchain builds are untouched as they're pinned in the `update-checkout-config.json` file of `swift` repository.
**Testing**: covered by existing tests and the compat suite.
**Issue**: N/A
**Reviewer**: @MaxDesiatov, @bnbarham
=> [6.0] Relax version ranges for dependencies in `Package.swift`

.gitignore, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildOperation.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/LLBuildManifest/LLBuildManifest.swift, Sources/LLBuildManifest/Tools.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Debugging.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/PrepareForIndexTests.swift
- Explanation: Adds a hidden experimental-prepare-for-indexing flag to `swift build` that builds only the parts needed for semantic functionality/indexing (ie. modules of dependencies, but no object files/libraries/etc).
- Scope: Builds
- Main Branch PR: https://github.com/apple/swift-package-manager/pull/7574, https://github.com/apple/swift-package-manager/pull/7627, https://github.com/apple/swift-package-manager/pull/7635
- Risk: Low - experimental option that doesn't impact anything when the option is disabled
- Reviewed By: @MaxDesiatov, @xedin 
- Testing: New tests covering the experimental option
=> [6.0] Add prepare for index experimental build argument

Sources/Build/BuildDescription/ClangTargetBuildDescription.swift, Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Sources/Build/BuildDescription/TargetBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Tests/BuildTests/BuildPlanTests.swift
**Explanation:** Updates `swift package dump-symbol-graph` to pass the correct set of include and cxx interoperability mode flags. This fixes a bug where were are unable to extract the symbol graph from swiftmodules with transitive cxx modules because we parsed cxx headers as c headers.
With these changes `swift-mmio` is able to generate symbol graphs and documentation using the `swift package dump-symbol-graph` and `swift package generate-documentation` commands.
**Scope:** Documentation generation
**Issue:** 
**Original PR**: #7610, #7621
**Risk**: Low
**Testing:** CI & at desk usage directly and via SwiftPM
**Reviewer:** @xedin
=> [6.0] Symbol graph cherry picks

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
Cherry-pick of #7652.
**Explanation**: We shouldn't have two `Sendable` conformances on `Bundle` at the same time, and Foundation added this on their side in `main` (https://github.com/apple/swift-corelibs-foundation/pull/4963) and `release/6.0` (https://github.com/apple/swift-corelibs-foundation/pull/4978).
**Scope**: isolated to bundle resources.
**Risk**: low, the corresponding change on `main` branch of `swift-corelibs-foundation` was there for 3 weeks.
**Testing**: covered by existing tests and the compat suite.
**Issue**: rdar://129599679
**Reviewer**: @parkera, @bnbarham
=> [6.0] Remove `Sendable` conformance on `Bundle` from SwiftPM

Sources/Commands/PackageCommands/Init.swift, Sources/Commands/Utilities/APIDigester.swift, Sources/CoreCommands/Options.swift, Sources/PackageRegistryCommand/PackageRegistryCommand+Publish.swift, Sources/SPMTestSupport/misc.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace.swift, Sources/swift-bootstrap/main.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/TopologicalSortTests.swift
`#if swift(<6.0)` is a wrong check to apply, since it has no effect with 6.0 compiler versions, unlike `#if compiler(<6.0)`.
=> Fix retroactive conformance warnings for 6.0+ compilers

Sources/Build/BuildOperation.swift, Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Trying to make it possible to share `createBuildOperation` between multiple implementations of `SPMCoreBuild.BuildSystem` in preparation to introduce an operation that would build plugin tools.
- Rename `BuildOperationBuildSystemDelegateHandler` into `LLBuildProgressTracker` which is a more neutral name that could be used by different llbuild operations if necessary.
- Integrate `commandFailureHandler` into the progress tracker
- Make `BuildOperation.createBuildSystem` stateless and use a single member to set both a new build system and its tracker.
The change it make it much easier to move `createBuildSystem` out of `BuildOperation` and into `SPMCoreBuild.BuildSystem` itself.
=> [Build] NFC: A few minor refactorings to build operation state tracking

Sources/Basics/AuthorizationProvider.swift, Tests/BasicsTests/AuthorizationProviderTests.swift
Use bearer auth when pulling binary targets or a package from a package registry and the user is `token`.
When logging in to a package registry bearer auth works. However when fetching binaryTargets or pulling packages from a registry basic auth is used always.
This either breaks services that don't use basic auth or leads to nasty workarounds like first creating a netrc file with "token" as the user and after login changing the user back to the actual user. Assuming that basic auth is allowed with an identiy token.
Check if the user is `token` when creating the authorization header and use Bearer auth in these cases.
When the user is `token` the `Authorization` header will be set to `Bearer {{access_token}}` instead of `Basic token:{{access_token}}`. 
Before:
After:
=> Fix: use bearer auth when pulling binaryTarget or packages from a package registry

Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Tests/WorkspaceTests/WorkspaceTests.swift
If a server returns an error when trying to download a binaryTarget an invalid file remains in the artifacts cache.
If the download of a binaryTarget fails a cache file still remains in the artifact cache.
The file only contains the server's response which is usually the status code and the error message.
Example:
```
$ ls ~/Library/Caches/org.swift.swiftpm/artifacts
.
..
https___test_example_local_foo_zip
$ cat ~/Library/Caches/org.swift.swiftpm/artifacts/https___test_example_local_foo_zip
404 page not found
```
Worse, all following `resolve` calls therefore fail because the cached file is used but is an invalid archive.
If the download fails the cache file in the artifacts cache is deleted.
As expected, the artifacts folder is empty.
Example:
```
$ ls …
```
=> Fix: cache not cleaned up if download fails

Sources/PackageDescription/PackageDescriptionSerialization.swift, Sources/PackageLoading/ManifestJSONParser.swift
We are caching manifest JSONs to speed up loading. It can happen that we cached a manifest with an older SwiftPM version and have to load the manifest from JSON with a newer SwiftPM version. With the first traits PR we made the new fields non-optional. This led to failures when loading the manifest from the cache https://github.com/apple/swift-package-manager/pull/7680.
This PR makes the fields optional and we default to empty sets after loading deserialization.
=> Make traits optional in manifest deserialization

Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Explanation: This is a test-only change to allow for `canImport` change https://github.com/apple/swift/pull/74519
Scope: Test only. Update a test that relies on an invalid module as test input. Replace that with a swiftinterface.
Original PR: https://github.com/apple/swift-package-manager/pull/7647
Test: Unit-Test
Reviewer: @tshortli
=> [6.0][Test-only] Don't use invalid module to satisfy `canImport` check (#7647)

Examples/package-info/Package.swift
Update swift-tools-version and platform version for Example package-info project
I needed to run the  Examples/package-info project fails with following the [readme](https://github.com/apple/swift-package-manager/blob/main/Documentation/libSwiftPM.md).
Update swift-tools-version and platform version for Example package-info project to be able to buld with the current SwiftPM.
The Examples/package-info project builds succesfully
=> Update versions in `Examples/package-info/Package.swift`

Sources/PackageDescription/PackageDependency.swift
* Remove mention of `nil` name which is not allowed due to the parameters being non-optional.
* Synchronize wording describing local package paths.
=> Fix parameter documentation in `PackageDependency.swift`

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Tests/BuildTests/PrepareForIndexTests.swift
When enable-testing is turned on, the test modules need access to the non exportable decls. Make sure we aren't skipping them in this case.
=> [Prepare] Don't skip non-exportable-decls when enable-testing

Sources/SPMTestSupport/MockWorkspace.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Cherry-pick of https://github.com/apple/swift-package-manager/pull/7663.
**Explanation**: If a server returns an error when trying to download a binaryTarget an invalid file remains in the artifacts cache.
**Scope**: Isolated to binary targets cache.
**Risk**: Low, scope is isolated, and the change has a corresponding test.
**Testing**: Automated with an existing test case refined.
**Issue**: rdar://123897276
**Reviewer**: @MaxDesiatov
=> [6.0] Fix cache not cleaned up if download fails

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
Since some newly reported issues still don't include SwiftPM CLI reproduction steps and only provide Xcode-specific steps, let's make this requirement more visible in the template.
=> Clarify reproduction steps requirements in `BUG_REPORT.yml`

Sources/PackageModel/BuildConfiguration.swift, Sources/PackageModel/BuildEnvironment.swift, Sources/PackageModel/BuildSettings.swift, Sources/PackageModel/Manifest/PackageConditionDescription.swift, Sources/PackageModel/PackageModel.swift, Sources/PackageModel/Product.swift, Sources/PackageModel/Target/BinaryTarget.swift, Sources/PackageModel/Target/ClangTarget.swift, Sources/PackageModel/Target/PluginTarget.swift, Sources/PackageModel/Target/ProvidedLibraryTarget.swift, Sources/PackageModel/Target/SwiftTarget.swift, Sources/PackageModel/Target/SystemLibraryTarget.swift, Sources/PackageModel/Target/Target.swift
The conformances are unused and pull in an additional `TSCUtility.PolymorphicCodableProtocol` dependency. This change removes about 0.2-0.4 MB from final executables on macOS when comparing with `swift build -c release` to `main`.
Also allows us to rename these types more easily to disambiguate between host/target triples and manifest targets/modules in our code.
If there's an existing user of this JSON manifest serialization we're unaware of, they should rely on `swift package describe --type json` instead, which has stable, consistent, and tested output.
=> Remove unused `Codable` conformances on `PackageModel` types

CHANGELOG.md
A link to a PR at the top was missing, which broke Markdown rendering. Additionally, the top section was removed apparently by accident, making it unclear where entries at the top belong.
=> Fix a link and top section in `CHANGELOG.md`

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
The determination for executable targets isn't limited to Swift files, it will also find 'main.m' for example. This was originally reflected in the diagnostic, but #3254 updated it incorrectly.
=> Fix incorrect executable target diagnostic

Fixtures/DependencyResolution/External/Complex/FisherYates/src/Fisher-Yates_Shuffle.swift, Fixtures/Miscellaneous/EchoExecutable/Sources/secho/main.swift, Sources/Build/TestObservation.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageDescription/PackageDescription.swift, Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
This adds the overlay to four of the six files that currently `import Glibc`, with those last two showing no difference if this _wasn't_ added, like `PackageDescription.swift`.
=> Add support for new Android overlay (`import Android`)

Sources/Commands/PackageCommands/AddProduct.swift
Remove unused options from `add-product` subcommand.
There are options (url, path, checksum) being used in the `add-product` subcommand that are not defined in [SE-0301 proposal](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0301-package-editing-commands.md#detailed-design).
I suspect these options were mistakenly implemented in `add-product` when they are actually used in the `add-target` subcommand. They appear in the command's help text but are not actually utilized, which could potentially confuse users. Therefore, I believe they should be removed to avoid misleading users.
Here is the current output of the `add-product` help:
```
OVERVIEW: Add a new product to the manifest
USAGE: swift package add-product <name> [--type <type>] [--targets <targets> ...] [--url …
```
=> Remove unused options from `add-product` subcommand

Sources/Build/BuildOperation.swift, Sources/Build/LLBuildDescription.swift, Sources/Commands/PackageCommands/APIDiff.swift, Sources/Commands/PackageCommands/DumpCommands.swift, Sources/Commands/PackageCommands/InstalledPackages.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/Snippets/Cards/SnippetCard.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftRunCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/APIDigester.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageGraph/CMakeLists.txt, Sources/PackageGraph/GraphLoadingNode.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/TraitConfiguration.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/Workspace/Workspace.swift, Sources/swift-bootstrap/main.swift, Tests/FunctionalTests/TraitTests.swift
When building, testing or running a root package we want users to be able to change the traits enabled in the packages. This allows them to build binaries with different traits enabled or run tests with different traits.
This PR adds trait options to a few commands and wires them through to the ModuleGraph loading and the build description caching. The latter is important to trigger rebuilds when the trait configuration has changed. Along the way I refactored the `GraphLoadingNode` and externalised the logic to calculate traits since I need slightly different logic for the root nodes and for the dependency nodes.
`swift build/run` now support passing trait configuration.
=> [Traits] Add experimental flags to enable specific or all traits, disable default traits

Sources/Build/BuildDescription/ProductBuildDescription.swift, Tests/BuildTests/LLBuildManifestBuilderTests.swift, Tests/CommandsTests/PackageCommandTests.swift
Given the following conditions:
- `--static-swift-stdlib` is enabled (it only affects "target" destination products, "host" destination products are always dynamic)
- the building subset contains both "host" and "target" destination products derived from the same product.
- the product imports `Foundation` (that has private dependency libs)
then the build randomly failed due to the race condition of the Objects.LinkFileList creation.
Reproducible project https://github.com/kateinoigakukun/swift-autolink-issue-repro
This commit fixes the issue by distinguishing the temporary link file list response file name by the `-tool` suffix.
I think it would be better to add assertions in `LLBuildManifest` to avoid such unintentional target overwrites later.
Fix the build for the above case.
=> Fix build of host&target destination products with `--static-swift-stdlib`

Sources/LLBuildManifest/LLBuildManifest.swift
Add debug assertion to avoid llbuild command name conflicts.
Depends on https://github.com/apple/swift-package-manager/pull/7695
One of the reasons we couldn't reveal https://github.com/apple/swift-package-manager/pull/7695 issue for long time (at least past 2 releases) is that we overlooked name conflicts on `addWriteLinkFileListCommand`. 
Looking into the manifest builder, some of the commands also forgot to assert name conflicts, so it was error-prone.
Add a convenience method to perform assertions consistently
NFC for release build. Just add debug assertions
=> NFC: Assert that we don't add llbuild commands with the same name twice

Sources/PackageModel/Manifest/Manifest.swift, Sources/PackageModel/Manifest/TraitDescription.swift, Tests/FunctionalTests/TraitTests.swift
We need to encode all trait related package manifest configuration so that it shows up in the `dump-package` output.
This PR encodes the missing `traits` property of the manifest.
=> [Traits] Encode all trait information for package dump

Sources/PackageDescription/Context.swift
Should improve things like https://developer.apple.com/documentation/packagedescription/gitinformation/currentcommit?changes=latest_minor
=> Add doc comments to the `GitInformation` PD API

Sources/PackageGraph/ModulesGraph+Loading.swift, Tests/FunctionalTests/TraitTests.swift
We are currently diagnosing unused dependencies by looking at the list of products used by the final modules and check if for every root dependency we are using at least one product of that package. This incorrectly diagnosis unused dependencies if the usage of the dependency is either:
- Just declared to enable a trait if down the graph another package is depending on it
- Used as an optional dependency and the trait is disabled
This PR adds two more checks to the diagnostic pass to find unused dependencies. We first create a set of dependency products that are guarded by a trait. When checking each dependency we then check if we enabled any trait on the dependency since this means it is used for setting a trait. We also check if any product of the dependency is guarded by a trait to …
=> [Traits] Correctly diagnose unused dependency with traits

Sources/Build/TestObservation.swift, Tests/CommandsTests/TestCommandTests.swift
Using the upcoming existential any feature via
'-Xswiftc -enable-upcoming-feature -Xswiftc ExistentialAny' causes build failures on non-Darwin platforms as a test observer class is generated which doesn't use explicit 'any'.
This is an issue for library maintainers who want to enforce this in CI.
=> Add 'any' to generated test runner code

Fixtures/Traits/Example/Package.swift, Fixtures/Traits/Example/Tests/ExampleTests/Tests.swift, Sources/Commands/SwiftTestCommand.swift, Tests/FunctionalTests/TraitTests.swift
It is useful to be able to configure the traits of the root package when running tests.
This PR adds the trait CLI options to the `swift test` command to enable specific traits or all traits, or to disable the default traits.
`swift test` now supports configuring the root traits.
=> [Traits] Enable trait configuration for `swift-test`

CODEOWNERS
Current `CODEOWNERS` file is invalid, as `@apple/swift-branch-managers` is an invalid codeowner team after a transfer to the `swiftlang` org.
=> [6.0] Update `CODEOWNERS` after `swiftlang` transfer

Fixtures/Traits/Example/Package.swift, Fixtures/Traits/Package3/Package.swift, Fixtures/Traits/Package4/Package.swift, Sources/PackageDescription/PackageDependencyTrait.swift, Sources/PackageDescription/PackageDescriptionSerialization.swift, Sources/PackageDescription/PackageDescriptionSerializationConversion.swift, Sources/PackageDescription/Trait.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/ManifestLoader+Validation.swift, Sources/PackageModel/Manifest/TraitDescription.swift, Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift, Tests/FunctionalTests/TraitTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/PackageLoadingTests/TraitLoadingTests.swift
The current spelling uses `isDefault` per trait to declare the default traits. This makes it hard to see which traits are actually the default traits.
Instead of using an explicit `isDefault` per trait this PR now uses a `.defaults(enabledTraits:)` overload which just uses the `"default"` trait under the hood. This simplifies the logic tremendously to handle default traits.
Nicer spelling for default traits and easier implementation.
=> [Traits] Replace `isDefault` with `default` trait

Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/PackageGraph/Resolution/ResolvedModule.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/SPMTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/PluginsBuildPlanTests.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
An attempt to simplify `invokeBuildToolPlugins` and avoid having to use a separate BuildOperation to build plugin accessible tools.
This is the first step towards the world where plugins are going to be invoked during BuildPlan construction as the modules/products are discovered.
- Instead of having to pass PluginModule around together with ModulesGraph, refactor accessible tool inference to be based on ResolvedModules.
- BuildOperation: organize various build options and configurations into `LLBuildSystemConfiguration`
- Extract build of plugin tools from `invokeBuildToolPlugins` into a separate method on `BuildOperation`
Better concern separation for plugins which enabled further refactoring and plugin integration into the build plan.
=> [Build/Plugins] Separate plugin tool builds from plugin invocations

Sources/PackageGraph/Resolution/PubGrub/Assignment.swift, Sources/PackageGraph/Resolution/PubGrub/DiagnosticReportBuilder.swift, Sources/PackageGraph/Resolution/PubGrub/Incompatibility.swift, Sources/PackageGraph/Resolution/PubGrub/PartialSolution.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubPackageContainer.swift, Sources/PackageGraph/Resolution/PubGrub/Term.swift
`tracking know assignments` -> `tracking known assignments`
=> [NFC] Fix typo, make formatting in PubGrub code consistent

Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift, Tests/BuildTests/PrepareForIndexTests.swift
Explanation: @testable doesn't work if you skip non-exportable-decls. Make sure we don't turn on that flag if the target is enable-testing.
Scope: Prepare for indexing only
Risk: isolated to prepare for indexing with is behind an experimental flag
Original PR: https://github.com/apple/swift-package-manager/pull/7675
Testing: Unit-Test
=> [6.0/Prepare] Don't skip non-exportable-decls when enable-testing (#7675)

Sources/CoreCommands/Options.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift
This allows e.g. `swift build --build-system xcode --triple arm64-apple-iphoneos` to work, slightly improving the ergonomics here and reducing hard-coded values.
=> Improve cross-compilation when using experimental XCBuild support

Sources/PackageDescription/PackageDescription.docc/Curation/SystemPackageProvider.md
Fix the docs so "nuget" shows up under the "Providing Hints to Users of System Packages" heading along with the other cases instead of being off by itself.
=> Add missing nuget case to system package provider docs

Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/PackageIndexAndCollections.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Sources/PackageCollectionsCommand/PackageCollectionsCommand.swift, Sources/PackageMetadata/PackageMetadata.swift
Move PackageCollectionsProtocol to async/await
async/await is easier to read and reason about then the callback APIs
PackageCollectionsProtocol is now expressed in terms of async methods instead of callbacks 
callback to async bridge methods are removed
Replaced usage of DispatchGroup with async let
PackageMetadata init has default values for optional and array values
More readable code
=> Move PackageCollectionsProtocol to async/await

Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/Basics/Vendor/Triple+Platforms.swift, Sources/Basics/Vendor/Triple.swift
Fixed Sendable warnings
Get SPM ready to adopt swift 6 mode
Added Sendable annotations to several clearly Sendable/safe types
Fewer warnings that will be errors in Swift 6
=> Fix a bunch of concurrency related warnings

Sources/Commands/PackageCommands/AddProduct.swift
Cherry-pick of #7693 
**Explanation**: I removed the mistakenly implemented options (`url`, `path`, `checksum`) that were not used in the `add-product` subcommand.
**Scope**: `add-product` subcommand.
**Issue**: N/A
**Original PR**: #7693 
**Risk**: No risk. Because it just removes unreferenced code.
**Testing**: covered by existing tests
=> [6.0] Remove unused options from `add-product` subcommand

Sources/Commands/PackageCommands/PluginCommand.swift
As part of codes used deprecated `PluginTarget`, I fixed it using `PluginModule`
```
'PluginTarget' is deprecated: renamed to 'PluginModule'
```
=> fix: warning using PluginTarget 

xcode/SwiftPM-Package.xctestplan
As title said.
If you look at SwiftPM-Package.xctestplan in Xcode, you can see PackageLoadingPerformanveTests is no longer needed. 
So I removed it from xctestplan.
Nothing
=> chore: remove unused Tests (PackageLoadingPerformanceTests)

.gitignore, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildOperation.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Debugging.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/PrepareForIndexTests.swift
The flags for lazy type checking and function body skipping are still experimental and haven’t been thoroughly tested in the wild yet. In case they are causing issues, add an option to prepare a target without these flags, which users could enable as a workaround.
rdar://130333568
=> Add a `--experimental-prepare-for-indexing-no-skipping` command line option to prepare a target without function body skipping

Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/Basics/HTTPClient/LegacyHTTPClientRequest.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/PackageIndex.swift, Sources/PackageCollections/PackageIndexAndCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift, Tests/PackageCollectionsTests/PackageIndexTests.swift, Tests/PackageCollectionsTests/Utility.swift
Move more of the PackageCollection APIs to native async/await
More modern code that will be able to adopt swift 6 data race safety eventually
PackageMetadataProvider APIs are all now async/await
PackageIndexProtocol APIs are all now async/await
Added question about the need for returning PackageMetadataProviderContext when PackageBasicMetadata can not be read
More readable code
=> Move getPackageMetadata to async/await

Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/Basics/HTTPClient/LegacyHTTPClientRequest.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/PackageIndex.swift, Sources/PackageCollections/PackageIndexAndCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/PackageCollectionsSourcesStorage.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift, Tests/PackageCollectionsTests/PackageIndexTests.swift, Tests/PackageCollectionsTests/Utility.swift
Move PackageCollectionsSourcesStorage to async/await
async/await is more readable than concurrency
Replace all completionHandler APIs with async/await
5 fewer callback APIs
=> Async file package collections sources storage

Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/Basics/HTTPClient/LegacyHTTPClientRequest.swift, Sources/PackageCollections/API.swift, Sources/PackageCollections/PackageCollections.swift, Sources/PackageCollections/PackageIndex.swift, Sources/PackageCollections/PackageIndexAndCollections.swift, Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift, Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageCollectionProvider.swift, Sources/PackageCollections/Providers/PackageMetadataProvider.swift, Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift, Tests/PackageCollectionsTests/PackageCollectionsTests.swift, Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift, Tests/PackageCollectionsTests/PackageIndexTests.swift, Tests/PackageCollectionsTests/Utility.swift
Async package collection provider
Safer more readable code ready for Swift 6
Moved PackageCollectionProvider to async/await
Removed numerous completion handler methods
=> Convert more package collections code to `async`/`await`

Sources/Build/LLBuildProgressTracker.swift, Sources/Build/SwiftCompilerOutputParser.swift
=> Handle the "abnormal-exit" status kind from the Swift compiler's parseable output

README.md
As the title says.
Due to the original documentation link becoming invalid, there is a need to update it to ensure users have access to the most current and accurate system requirements.
Replaced the link as follows:
- Old: https://github.com/apple/swift#system-requirements
- New: https://github.com/swiftlang/swift/blob/main/docs/HowToGuides/GettingStarted.md#system-requirements
The link correction ensures access to accurate system requirements.
=> Update link to Swift system requirements

Sources/Build/BuildDescription/ProductBuildDescription.swift, Tests/BuildTests/LLBuildManifestBuilderTests.swift, Tests/CommandsTests/PackageCommandTests.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/7695.
**Explanation**: Given the following conditions:
- `--static-swift-stdlib` is enabled (it only affects "target" destination products, "host" destination products are always dynamic)
- the building subset contains both "host" and "target" destination products derived from the same product.
- the product imports `Foundation` (that has private dependency libs)
then the build randomly failed due to the race condition of the `Objects.LinkFileList` creation.
Reproducible project
https://github.com/kateinoigakukun/swift-autolink-issue-repro
**Scope**: isolated to packages with plugins
**Risk**: low, the change was incubated on `main` for a few weeks now
**Testing**: Added a new automated test case 
**Issue**: N/A …
=> [6.0] Fix host/target products with `--static-swift-stdlib`

Sources/CoreCommands/Options.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift
Cherry-pick to 6.0 branch.
Explanation: XCBuild support was hardcoded to use a macOS triple. Base this on the build request so it can be used for testing other scenarios as well.
Scope: Changes are isolated to less commonly used option.
Risk: Very low, since changes are isolated to a less commonly used option.
Testing: Tested manually end-to-end.
Issue: N/A
Reviewer: @MaxDesiatov
=> [6.0] Improve cross-compilation for experimental XCBuild support

Sources/Basics/Archiver/Archiver.swift, Sources/Commands/PackageCommands/ComputeChecksum.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift
This feature [was specified in the corresponding proposal for Swift SDKs](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md#swift-sdk-installation-and-configuration):
> For Swift SDKs installed from remote URLs an additional `--checksum` option is required, through which users of a Swift SDK can specify a checksum provided by a publisher of the SDK. The latter can produce a checksum by running `swift package compute-checksum` command (introduced in [SE-0272](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0272-swiftpm-binary-dependencies.md)) with the Swift SDK bundle archive as an argument.
Currently, `swift package compute-checksum` is unable to handle `.tar.gz` bundles, which is a commonly used format for Swift …
=> Fix checksum computation for Swift SDK bundles

Sources/Basics/Archiver/Archiver.swift, Sources/Commands/PackageCommands/ComputeChecksum.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/7748.
**Explanation**: This feature [was specified in the corresponding proposal for Swift SDKs](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md#swift-sdk-installation-and-configuration):
> For Swift SDKs installed from remote URLs an additional `--checksum` option is required, through which users of a Swift SDK can specify a checksum provided by a publisher of the SDK. The latter can produce a checksum by running `swift package compute-checksum` command (introduced in [SE-0272](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0272-swiftpm-binary-dependencies.md)) with the Swift SDK bundle archive as an argument.
Currently, `swift package …
=> [6.0] Fix checksum computation for Swift SDK bundles

Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/swift-bootstrap/main.swift
`swift-bootstrap` currently can't handle dependencies with plugins, which prevents us from bumping Swift Argument Parser to a newer version, which did add a dependency on a plugin. The easiest workaround is to exclude plugins from the modules graph only when building with `swift-bootstrap`.
=> Work around `swift-bootstrap` inability to handle plugins

Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/swift-bootstrap/main.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/7750.
**Explanation**: `swift-bootstrap` currently can't handle dependencies with plugins, which prevents us from bumping Swift Argument Parser to a newer version, which did add a dependency on a plugin. The easiest workaround is to exclude plugins from the modules graph only when building with `swift-bootstrap`.
**Scope**: isolated to the `swift-bootstrap` command.
**Risk**: low due to isolated scope and the NFC nature of the change for all non-bootstrap builds (which are all of the common builds, `swift-bootstrap` is only used to build SwiftPM itself).
**Testing**: automated, `swift-bootstrap` is exercised in every CI build.
**Issue**: rdar://118081439
=> [6.0] Work around `swift-bootstrap` inability to handle plugins

Tests/PackageLoadingTests/ManifestLoaderCacheTests.swift, Tests/PackageLoadingTests/PD_6_0_LoadingTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
`UserToolchain.default.skipUnlessAtLeastSwift6` is not `async`, which triggers multiple warnings in tests.
=> Fix warnings caused by unused `await`

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/ManifestLoaderCacheTests.swift
The manifest cache key should take into account flags passed to `-Xbuild-tools-swiftc`
SwiftPM did not re-evaluate manifests even after changing `-Xbuild-tools-swiftc`
Hash those extra flags into manifest cache key
Manifest will be properly re-evaluated after changing `-Xbuild-tools-swiftc`.
=> Invalidate manifest cache when `-Xbuild-tools-swiftc` changes

Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/Install.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/7744.
**Explanation**: One would almost always install the release binary, as opposed to debugging binaries when building locally for development. Thus `release` should be the default for `swift package experimental-install`.
**Scope**: Changes are isolated to an experimental and hidden subcommand.
**Risk**: Very low, since changes are isolated to an experimental and hidden subcommand.
**Testing**: Tested manually end-to-end, also covered by existing tests, which caught a regression during development.
**Issue**: rdar://130922365
=> [6.0] Use `release` build configuration in `experimental-install`

CHANGELOG.md
Importing macro modules directly to use those macros was never supposed to work, and now with macro modules built for the host triple, importing such macro modules in modules built for the target triple will fail.
=> Clarify unsupported direct macro module imports in `CHANGELOG.md`

Sources/PackageLoading/ManifestLoader.swift, Tests/PackageLoadingTests/ManifestLoaderCacheTests.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/7760
**Explanation**: The manifest cache key should take into account flags passed to `-Xbuild-tools-swiftc`, but it didn't. so SwiftPM did not re-evaluate manifests even after changing `-Xbuild-tools-swiftc`. Fix the incorrect cache by hashing those extra flags into manifest cache key.
**Scope**: Affects only when `-Xbuild-tools-swiftc` is used.
**Risk**: low due to isolated less used option
**Testing**: Added a new test case to cover the senario
**Issue**: N/A
**Reviewer**: @xedin
=> [6.0] Invalidate manifest cache when `-Xbuild-tools-swiftc` changes

Fixtures/DependencyResolution/External/Complex/FisherYates/src/Fisher-Yates_Shuffle.swift, Sources/Basics/Environment/Environment.swift, Sources/Build/TestObservation.swift, Sources/CoreCommands/SwiftCommandState.swift
Also, add the import in `Environment.swift` too
@rauhul, you added that last file just after I got these imports in with #7615, so I recently had to add this too to keep it building on Android.
=> Import new Bionic module from Android overlay instead where possible

Fixtures/DependencyResolution/External/Complex/FisherYates/src/Fisher-Yates_Shuffle.swift, Fixtures/Miscellaneous/EchoExecutable/Sources/secho/main.swift, Sources/Basics/Environment/Environment.swift, Sources/Build/TestObservation.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageDescription/PackageDescription.swift, Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
__Explanation:__ Now that this new overlay was merged into the 6.0 compiler too in swiftlang/swift#74758, this adds the overlay to five of the seven files that currently `import Glibc`, with those last two showing no difference if this _wasn't_ added, like `PackageDescription.swift`, so remove most of those imports.
__Scope:__ Add imports on Android and remove a handful in two files that were unused
__Original PRs:__ #7615 and #7755
__Risk:__ Very low
__Testing:__ Passed all CI on trunk, plus on my daily Android CI
__Reviewer:__ @bnbarham
=> [6.0] Add support for new Bionic module from Android overlay (`import Bionic`) (#7615)

Sources/Commands/SwiftTestCommand.swift
This PR adds `--configuration-path`, `--event-stream-output-path`, and `--event-stream-version` to `swift test`.
For more information, see the Swift Testing API proposal [here](https://github.com/apple/swift-testing/blob/main/Documentation/Proposals/0002-json-abi.md).
=> Add the formalized Swift Testing event stream arguments to `swift test`.

Sources/Commands/SwiftTestCommand.swift
Cherry-picks #7768 to release/6.0.
**Explanation**: Adds tools-facing command-line arguments for Swift Testing to `swift test` and `swift test list`. These arguments are passed through verbatim to Swift Testing and are not directly used by SwiftPM.
**Scope**: Affects `swift test` and `swift test list`.
**Risk**: Low—these arguments are wholly ignored by SwiftPM, and just need to be allowed through.
**Testing**: Existing test coverage for `swift test`, plus tests on the Swift Testing side for actually handling the arguments. Since SwiftPM ignores them, additional unit testing on the SwiftPM side would be tautological.
**Issue**: https://github.com/apple/swift-testing/pull/479
**Reviewer**: @bnbarham, @briancroom, @stmontgomery, @dennisweissmann
=> [6.0] Add the formalized Swift Testing event stream arguments to `swift test`.

Sources/Commands/SwiftTestCommand.swift
This PR detects when a Swift Testing run returns `EXIT_NO_TESTS_FOUND` and treats it as a successful test run.
This change handles the change from https://github.com/apple/swift-testing/pull/536. Separately, the refactor in #7766 stops Swift Package Manager from reporting `"No matching test cases were run"` when XCTest has no tests matching passed `--filter` arguments. A third PR after these two have been merged will restore that functionality by collating results from both XCTest and Swift Testing.
> [!NOTE]
> Test coverage can be added after Swift Testing is in the Swift toolchain.
This change partially resolves rdar://131704587.
=> Detect when Swift Testing returns `EXIT_NO_TESTS_FOUND`.

Package.swift, Sources/swiftpm-testing-helper/Entrypoint.swift, Utilities/bootstrap
Since the xctest and swift-testing are being unified into one product we need an additional tool (just like `swiftpm-xctest-helper`) to load and run swift-testing tests from the unified bundle.
- Added `swiftpm-testing-helper` that accepts a bundle path as an argument.
swift-testing tests can be run from the unified bundle.
=> Add a helper tool for swift-testing

Package.swift, Sources/swiftpm-testing-helper/Entrypoint.swift, Utilities/bootstrap
- Explanation: Since the xctest and swift-testing are being unified into one product we need an additional tool (just like `swiftpm-xctest-helper`) to load and run swift-testing tests from the unified bundle.
- Main Branch PR: https://github.com/swiftlang/swift-package-manager/pull/7771
- Risk: Low
- Reviewed By: @bnbarham @grynspan  
- Testing: This change doesn't impact SwiftPM functionality *yet*, it's merely hosting the executable.
(cherry picked from commit 6021057af1d6e4ecb39a5e253913edae6cce2a54)
=> [6.0] Add a helper tool for swift-testing

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Build/LLBuildCommands.swift, Sources/Build/LLBuildDescription.swift, Sources/Commands/PackageCommands/Init.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/TestingSupport.swift, Sources/CoreCommands/Options.swift, Sources/PackageModel/UserToolchain.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMBuildCore/BuiltTestProduct.swift, Sources/Workspace/InitPackage.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Sources/swiftpm-testing-helper/Entrypoint.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/WorkspaceTests/InitTests.swift
This PR refactors the previously-experimental Swift Testing support logic so that only a single build product is produced when using both XCTest and Swift Testing, and detection of Swift Testing usage is no longer needed at compile time.
On macOS, Xcode 16 is responsible for hosting Swift Testing content, so additional changes may be needed in Xcode to support this refactoring. Such changes are beyond the purview of the Swift open source project.
Resolves rdar://120864035.
=> Build one test product for both Swift Testing and XCTest (with Swift Testing enabled by default.)

Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/Toolchain.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
Prefer the toolchain provided in the build plan rather than the default host toolchain so that the returned arguments align with the toolchain used to construct the build plan.
=> Pass through the toolchain to use for manifest loading

Sources/Commands/PackageCommands/Init.swift
This PR turns Swift Testing back off by default when running `swift package init` because it's not available in the toolchain yet and the package dependency may come as a surprise (also, it breaks CI, but who's counting?)
Follow-up to #7766.
=> Disable Swift Testing by default in `swift package init`.

Sources/PackageLoading/TargetSourcesBuilder.swift
**Explanation**: `TargetSourcesBuilder.swift`: Stored property 'rule' of 'Sendable'-conforming struct 'FileRuleDescription' has non-sendable type 'FileRuleDescription.Rule'; this is an error in the Swift 6 language mode.
**Scope**: Non-functional change.
**Risk**: Very low as it's an NFC change removing a compiler warning.
**Testing**: Manually verified that the warning is resolved.
**Issue**: rdar://131439553
=> [6.0] NFC: Make 'FileRuleDescription.Rule' conform to `Sendable`

Sources/Commands/SwiftBuildCommand.swift
The enable/disable testing library options are no longer used by `swift build` and can be removed.
=> Remove `--enable-swift-testing` _et al._ from `swift build`.

Sources/Basics/OSSignpost.swift
=> Fix warning in `OSSignpost.swift` w/ `@preconcurrency import`

Sources/Basics/OSSignpost.swift
Cherry-pick of #7785.
**Explanation**: Fixes a Swift Concurrency warning for an import of a preconcurrency module.
**Scope**: Isolated to a warning in a single file.
**Risk**: Very low, change is NFC.
**Testing**: Manually verified that the warning is gone.
**Issue**: rdar://131432130
**Reviewer**: @xedin
=> [6.0] Fix warning in `OSSignpost.swift` w/ `@preconcurrency import`

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Build/LLBuildCommands.swift, Sources/Build/LLBuildDescription.swift, Sources/Commands/PackageCommands/Init.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/TestingSupport.swift, Sources/CoreCommands/Options.swift, Sources/PackageModel/UserToolchain.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMBuildCore/BuiltTestProduct.swift, Sources/Workspace/InitPackage.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/WorkspaceTests/InitTests.swift
Revert #7766 and #7783, merged prematurely by mistake.
=> Revert #7766 and #7783.

Sources/Commands/SwiftTestCommand.swift
This PR forces Swift Testing to write its xUnit output to a different path from what the user specifies.
In the future, we should have the two testing libraries collate their XML output into a single file, but that requires the ability to parse and reformat XML output and that's a little beyond the capabilities of this feature right now. Since we expect most uses of xUnit output right now are existing ones with existing XCTest-based tests, moving Swift Testing aside seems like the right call.
(If XCTest is explicitly disabled, the exact specified path is used.)
=> Don't stomp on xUnit output from XCTest when running Swift Testing.

Sources/Basics/Environment/Environment.swift, Sources/DriverSupport/DriverSupportUtils.swift, Sources/DriverSupport/SPMSwiftDriverExecutor.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/Workspace/DefaultPluginScriptRunner.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Cherry-pick of #7780.
**Explanation**: Initializers for this type should be available via `@_spi` for clients to consume.
**Scope**: Limited to a single type and relevant initializers.
**Risk**: Very low, change is NFC.
**Testing**: Verified through existing test suite.
**Issue**: rdar://131407852
=> [6.0] NFC: Expose `Environment` with `@_spi`

Sources/PackageLoading/ManifestLoader.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fixes issue #7688
SwiftPM was implicitly prepending the manifest with 'import Foundation' for toolchains using Swift toolchain versions 5.7 and under. The original file itself was never overwritten, thus the diagnostics being reported would always present on the next line.
This is a quick fix that appends the same line to the end of the manifest; doing so assures that the intended behaviour doesn't change, but allows for correct diagnostics to be reported.
Diagnostics would present on the incorrect line for Package.swift files using tools version 5.7 and under.
When evaluating the manifest, a temporary directory copies the contents of the manifest to a temporary file; rather than prepending the import to Foundation at the top of the file (causing all lines in the diagnostic reports to be …
=> Fix Package.swift diagnostics line off by 1 for tools versions <= 5.7

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Build/LLBuildCommands.swift, Sources/Build/LLBuildDescription.swift, Sources/Commands/PackageCommands/Init.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/TestingSupport.swift, Sources/CoreCommands/Options.swift, Sources/PackageModel/UserToolchain.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMBuildCore/BuiltTestProduct.swift, Sources/Workspace/InitPackage.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/WorkspaceTests/InitTests.swift
**Explanation:** Refactors the previously-experimental Swift Testing support logic so that only a single build product is produced when using both XCTest and Swift Testing, and detection of Swift Testing usage is no longer needed at compile time.
**Scope:** Implementation of Swift Testing/SwiftPM integration; touches mostly `swift test` but affects `swift build` and `swift package init` as well.
**Issue:** rdar://120864035
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7777, https://github.com/swiftlang/swift-package-manager/pull/7789, https://github.com/swiftlang/swift-package-manager/pull/7796
**Risk:** Moderate—refactors how we build and run tests.
**Testing:** Existing test coverage in the package as well as test coverage in the Swift Testing package; …
=> [6.0] Build one test product for both Swift Testing and XCTest (with Swift Testing enabled by default.)

Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/PackageGraph/Resolution/PubGrub/Term.swift, Sources/PackageGraph/VersionSetSpecifier.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/PackageGraphTests/VersionSetSpecifierTests.swift
Pre-release decisions are valid if the derived range they were inferred from supports pre-release versions.
Currently, after deriving a pre-release assignment, the solver would assert
in some circumstances depending on order in which the dependencies are
specified in the manifest.
This change makes it possible to infer pre-release verison of a package 
even when intermediate derivations did not support pre-release versions.
For example one package could declare `swift-syntax` dependency as
`508.0.1` ..< `601.0.0` and another could narrow it to `600.0.0-latest` ..< `601.0.0`.
Since the most constrained range in such case supports pre-releases a decision
to use the lastest pre-release version of `600.0.0` should be valid if there
is no `600.0.0` release yet.
It's important to note that on …
=> [PubGrub] Narrow down cases when pre-release decisions are marked invalid

Sources/Commands/SwiftTestCommand.swift, Tests/CommandsTests/TestCommandTests.swift
Fixes a logic error in deciding when to log the "no matching test cases were run" diagnostic if `--disable-swift-testing` is passed.
=> Don't log "no matching tests" diagnostic when running XCTest only.

Sources/Commands/SwiftTestCommand.swift, Tests/CommandsTests/TestCommandTests.swift
**Explanation:** Fixes a logic error in deciding when to log the "no matching test cases were run" diagnostic if `--disable-swift-testing` is passed.
**Scope:** Bug fix in `swift test`.
**Issue:** N/A (noticed locally, opened PR)
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7803
**Risk:** Low
**Testing:** Added unit test.
**Reviewer:** @MaxDesiatov @bnbarham
=> [6.0] Don't log "no matching tests" diagnostic when running XCTest only.

Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/Install.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift
One would almost always install the release binary, as opposed to debugging binaries when building locally for development. Thus `release` should be the default for `swift package experimental-install`.
rdar://130922365
=> Use `release` build configuration in `experimental-install`

Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/_InternalTestSupport/Observability.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
=> Handle `.xcprivacy` files in `TargetSourcesBuilder.swift`

Sources/PackageLoading/TargetSourcesBuilder.swift, Sources/SPMTestSupport/Observability.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift
Cherry-pick of #7807.
**Explanation**:  There should be a file rule to automatically include or ignore privacy manifests, given that we know the file name
**Scope**: isolated in code to a single file, only affects packages that include privacy manifests.
**Risk**: low due to isolated scope.
**Testing**: added new test cases.
**Issue**: rdar://111119227
=> [6.0] Handle `.xcprivacy` files in `TargetSourcesBuilder.swift`

Sources/Commands/SwiftBuildCommand.swift
For the benefit of the VSCode Swift plugin, we need to keep this flag around (but as a no-op and hidden from documentation) until the plugin drops support for earlier Swift 6 prereleases.
Resolves rdar://132408655.
=> Add back `--enable-experimental-swift-testing` to `swift build` as a no-op.

Sources/Commands/SwiftBuildCommand.swift
**Explanation:** Adds back some no-op arguments to `swift build` so that the VSCode plugin stays happy.
**Scope:** Bug fix in `swift build`.
**Issue:** rdar://132408655
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7817
**Risk:** Low
**Testing:** N/A (no-op arguments, they do nothing)
**Reviewer:** @MaxDesiatov @bnbarham
=> [6.0] Add back `--enable-experimental-swift-testing` to `swift build` as a no-op.

Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/PackageGraph/Resolution/ResolvedModule.swift, Sources/PackageGraph/Resolution/ResolvedPackage.swift, Sources/PackageGraph/Resolution/ResolvedProduct.swift
(cherry picked from https://github.com/swiftlang/swift-package-manager/pull/7819)
**Explanation**: NFC changes to expose a few properties with `@_spi(SwiftPMInternal)`.
**Scope**: limited to a few property declarations.
**Risk**: very low, the change is NFC
**Testing**: N/A
**Issue**: N/A
**Reviewer**: @francescomikulis
=> 6.0: [NFC] Expose `platformVersionProvider` with `@_spi(SwiftPMInternal)`

Fixtures/Miscellaneous/Plugins/DependentPlugins/Package.swift, Sources/PackageDescription/BuildSettings.swift, Sources/PackageDescription/LanguageStandardSettings.swift, Sources/PackageDescription/PackageDescription.swift, Sources/PackageDescription/PackageDescriptionSerializationConversion.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
This PR implements the package manager changes in Swift evolution proposal [SE-0441](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0441-formalize-language-mode-terminology.md).
=> Adopt language mode naming in `PackageDescription` API

Sources/Commands/PackageCommands/Init.swift, Sources/Commands/SwiftTestCommand.swift, Sources/CoreCommands/Options.swift
This PR checks if XCTest is available before invoking XCTest-based tests on Darwin. There are three possible outcomes:
1. If XCTest is available, we will run XCTest-based tests (as we have historically.)
2. If XCTest is not available and the user explicitly passed `--enable-xctest`, we will attempt to run XCTest-based tests, but in general this code path will continue to fail as `swift test` has historically done when XCTest is not available.
3. If XCTest is not available and the user did not pass `--enable-xctest`, we skip running any XCTest logic.
On Linux/Windows/etc., XCTest is always present via swift-corelibs-xctest and so this change has no practical effect there. On Darwin, XCTest may be missing if the user has installed the Xcode Command Line Tools, but not the full Xcode IDE. …
=> Detect if XCTest is installed on Darwin

Sources/Basics/OSSignpost.swift
```
'@preconcurrency' attribute on module 'os' has no effect
```
=> Fix `OSSignpost.swift` concurrency warning

Sources/Basics/Archiver/Archiver.swift, Sources/Commands/PackageCommands/ComputeChecksum.swift, Sources/PackageModel/SwiftSDKs/SwiftSDK.swift, Sources/PackageModel/SwiftSDKs/SwiftSDKBundleStore.swift, Sources/SwiftSDKCommand/Configuration/DeprecatedSwiftSDKConfigurationCommand.swift, Sources/SwiftSDKCommand/InstallSwiftSDK.swift, Sources/SwiftSDKCommand/ListSwiftSDKs.swift, Sources/SwiftSDKCommand/RemoveSwiftSDK.swift, Sources/SwiftSDKCommand/SwiftSDKCommand.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Tests/PackageModelTests/SwiftSDKBundleTests.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/7722.
**Explanation**: This option [was specified in the corresponding proposal for Swift SDKs](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md#swift-sdk-installation-and-configuration):
> For Swift SDKs installed from remote URLs an additional `--checksum` option is required, through which users of a Swift SDK can specify a checksum provided by a publisher of the SDK. The latter can produce a checksum by running `swift package compute-checksum command` (introduced in [SE-0272](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0272-swiftpm-binary-dependencies.md)) with the Swift SDK bundle archive as an argument.
**Scope**: the change is isolated to …
=> [6.0] Implement `--checksum` option on `swift sdk install`

Sources/Basics/Netrc.swift, Sources/_InternalTestSupport/MockArchiver.swift, Tests/BasicsTests/CancellatorTests.swift, Tests/CommandsTests/PackageRegistryCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift
Assorted fixes for sendability warnings.
=> NFC: Resolve some `Sendable`-related warnings

Sources/Basics/Graph/UndirectedGraph.swift
`UndirectedGraph` uses an adjacency matrix not adjacency list for edges representation. The link in its doc comment should be corrected.
=> NFC: Fix doc comment link in `UndirectedGraph.swift`

Package.swift
=> NFC: Fix comment typo in `Package.swift`

Sources/Commands/SwiftTestCommand.swift
In #6894, code coverage processing was disabled because it produces spurious output. This PR just adds a comment to the current source that links back to that one for future reference.
=> Add a comment to explain why we don't process code coverage on test fail

Sources/Basics/Archiver/Archiver.swift, Sources/Basics/Archiver/TarArchiver.swift, Sources/Basics/Archiver/UniversalArchiver.swift, Sources/Basics/Archiver/ZipArchiver.swift, Sources/Basics/AuthorizationProvider.swift, Sources/Basics/Concurrency/ConcurrencyHelpers.swift, Sources/Basics/Concurrency/ThreadSafeBox.swift, Sources/Basics/Concurrency/ThreadSafeKeyValueStore.swift, Sources/Commands/PackageCommands/ArchiveSource.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/PackageCommands/SwiftPackageCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/PackageRegistryCommand/PackageRegistryCommand+Publish.swift, Sources/_InternalTestSupport/MockArchiver.swift, Sources/_InternalTestSupport/MockRegistry.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/CommandsTests/PackageRegistryCommandTests.swift, Tests/PackageGraphTests/PubgrubTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Remove both temp_await and safe_async in favor of broader adoption of async/await
This change was originally developed as one large PR. To make testing, reviewing, and landing these changes simpler the PR has been broken down into about a dozen individual PRs that are stacked
`temp_await` is very dangerous API that blocks the current thread and is not marked as unavailable from async methods.  The only need for temp_await is because LLBuild only supports non-async methods so any llbuild commands that call async methods have to block waiting. 
Because `temp_await` is liberally spread across the code base there are a number of async methods that may indirectly call into `temp_await` and indefinitely block a swift concurrency thread. This risks a deadlock. To prevent the deadlock the …
=> Remove `temp_await` [part 1]

Sources/Commands/SwiftTestCommand.swift
A previous PR, #7796, avoided Swift Testing stomping on XML output from XCTest when both libraries were running tests. However, there's a bug in the implementation where if you pass `--disable-xctest`, we don't end up telling Swift Testing to write any XML at all. This PR fixes that.
Tested with:
```sh
swift build
$(pwd)/.build/debug/swift-test --package-path /Volumes/Dev/Source/swift-testing --disable-xctest --xunit-output /dev/stdout
```
To confirm that XML output was produced for Swift Testing's test target (as an exemplar package that uses Swift Testing.)
=> Restore XML output for Swift Testing when `--disable-xctest` is passed.

Sources/Commands/PackageCommands/AddDependency.swift, Sources/PackageModelSyntax/PackageDependency+Syntax.swift, Tests/CommandsTests/PackageCommandTests.swift
Fix issue https://github.com/swiftlang/swift-package-manager/issues/7738
Conversation regarding approach in previous PR #7769
Allow user to add `.package(path:)` and `.package(id, ...)` dependencies using `swift package add-dependency`
I wanted to be able to add  `.package(path:)` using the command line and was unable to do so with the given parsing.
This PR adds `--type` argument allowing user to choose dependency type. 
- Introduces `--type` argument which defaults to `url` 
- accepts `url`, `path` and `registry`
- Uses `--type` argument to determine what type of dependency to create
- Adds `SwiftSyntax` for:
- `PackageDependency.FileSystem`
- `PackageDependency.Registry`
- `PackageDependency.Registry.Requirement`
- Adds more unit test coverage
- Runs `SwiftFormat` in the files that …
=> Add `--type` argument to `swift package add-dependency`

Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubgrubTests.swift
Remove temp_await from pubgrub
temp_await is unsafe and it would be better to use true async methods
Remove 5 usages of temp_await from pub_grub
=> Remove `temp_await` from PubGrub code

Sources/Commands/PackageCommands/APIDiff.swift, Sources/Commands/PackageCommands/DumpCommands.swift, Sources/Commands/PackageCommands/Install.swift, Sources/Commands/PackageCommands/Learn.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/Snippets/Card.swift, Sources/Commands/Snippets/CardStack.swift, Sources/Commands/Snippets/Cards/SnippetCard.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftRunCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/APIDigester.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubgrubTests.swift
Remove temp_await from Snippets
temp_await is unsafe and it would be better to use true async methods
Remove usages of temp_await from Snippets
=> Remove `temp_await` from Snippets

Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Build/BuildPlan/BuildPlan.swift
This way we can compute destinations as we go instead of relying on `buildTriple` computed during graph construction.
- Adds a new static method on `BuildPlan` to traverse modules graph and compute destinations for each product and module.
- Switches `BuildPlan.init` from using `allProducts` and `allModules` flat lists over the new incremental destination computation.
Removes one of the last places were `buildTriple` is required.
=> [BuildPlan] Switch build plan construction to use graph traversal

Sources/Commands/Utilities/TestingSupport.swift, Sources/PackageModel/Toolchain.swift, Sources/PackageModel/ToolchainConfiguration.swift, Sources/PackageModel/UserToolchain.swift, Sources/PackageModel/WindowsToolchainInfo.swift
Properly handle swift-testing installations in toolchain/SDK.
On macOS SwiftPM should prefer swift-testing installed into a custom toolchain when used. On Windows we need special logic to discover swift-testing location.
- Add special swift compiler "extra" flags to favor swift-testing installed in a toolchain.
- Inject `-I`, `-L` on Windows that point to where swift-testing is installed in SDKROOT.
- Inject a path to testing on `PATH` environment variable on Windows to make sure that the library is always discoverable.
Resolves: rdar://132828246
=> [PackageModel] Support swift-testing installed in a toolchain

Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Build/LLBuildCommands.swift, Sources/Build/LLBuildProgressTracker.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/BuildOperationTests.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/BuildTests/LLBuildManifestBuilderTests.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift, Tests/BuildTests/PrepareForIndexTests.swift, Tests/CommandsTests/SwiftCommandStateTests.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
Remove `temp_await` from build related code
`temp_await` is unsafe and it would be better to use true async methods
Remove `temp_await` from BuildPlan
Remove `temp_await` from BuildOperation
=> Remove `temp_await` from `Build`/`BuildPlan`/`*Command`/`Workspace`

Sources/PackageRegistry/ChecksumTOFU.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/SignatureValidation.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
Remove temp_await from RegistryClient
`temp_await` is unsafe and it would be better to use true async methods
Remove `temp_await` from RegistryClient
=> Refactor `temp_await` out of RegistryClient

Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/Resolution/PubGrub/DiagnosticReportBuilder.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubPackageContainer.swift, Sources/PackageRegistry/ChecksumTOFU.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/SignatureValidation.swift, Sources/Workspace/PackageContainer/FileSystemPackageContainer.swift, Sources/Workspace/PackageContainer/RegistryPackageContainer.swift, Sources/Workspace/PackageContainer/SourceControlPackageContainer.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/_InternalTestSupport/MockPackageContainer.swift, Tests/PackageGraphTests/PubGrubTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Remove usage of `temp_await` in PackageContainer
`temp_await` is unsafe and it would be better to use true async methods
Remove `temp_await` from PackageContainer
=> Remove usage of `temp_await` in PackageContainer

Package.swift, Sources/CoreCommands/SwiftCommandState.swift, Tests/BuildTests/PrepareForIndexTests.swift
The prepare build need to be able to run tools to generate code they are preparing. As such when prepareForIndexing is enabled ensure the tools target builds have it turned off.
Fixes: #7842
=> Ensure tools builds never build in prepare mode.

Sources/Basics/Concurrency/ConcurrencyHelpers.swift, Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/Build/BuildOperation.swift, Sources/Commands/PackageCommands/APIDiff.swift, Sources/Commands/PackageCommands/DumpCommands.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/Snippets/Cards/SnippetCard.swift, Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/SwiftRunCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/Commands/Utilities/APIDigester.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Sources/_InternalTestSupport/MockPackageSigningEntityStorage.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Sources/swift-bootstrap/main.swift, Tests/BasicsTests/AsyncProcessTests.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/BuildTests/BuildOperationTests.swift, Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
Remove all remaining usages of `temp_await` and `safe_async`
`temp_await` can cause deadlocks when called from swift concurrency and `safe_async` can cause thread explosion. Replacing the usage of  these methods 
Vendor topological sort so that we can have an async/await version
Replace use of safe_async with withCheckedThrowingContinuation
Remove temp_await and safe_async methods
Remove uses of unsafe_await in package graph resolution
No `temp_await` 
No `safe_async`
Only one usage of `unsafe_await` which is exclusively called from the C++ llbuild
=> Remove all remaining usages of `temp_await` and `safe_async`

Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/SwiftTestCommand.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Sources/swift-bootstrap/main.swift, Tests/PackageGraphTests/PubGrubTests.swift
Replace withCheckedThrowingContinuation with native async/await
Replace callback and continuation usage with async/await
Replaced calls to `withCheckedThrowingContinuation` on APIs that have async alternatives 
Replaced 3 completion handler APIs in swift-bootstrap making it fully async/await
11 fewer continuation usages
1 fewer unstructured Task
3 fewer completion handler APIs
=> Replace withCheckedThrowingContinuation with native async/await

Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift, Sources/PackageCollections/Storage/PackageCollectionsStorage.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Finish moving package collections to async/await
Finish the replacement of callback/result APIs with async/await
Move SQL queries off of the Swift concurrency queue
Move PackageCollectionsStorage protocol to async/await
No more callback based APIs in package collections
=> Finish moving package collections to async/await

Sources/Build/BuildDescription/ClangModuleBuildDescription.swift, Sources/Build/BuildDescription/ModuleBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/PackageCommands/DumpCommands.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift
Yet another step on the path to remove `buildTriple` from `Resolved{Product, Module}`.
Instead of trying to lookup modules in the module graph and then going the build plan for their descriptions, symbol-graph-extract should refer to the build plan directly.
- Adds a new protocol `ModuleBuildDescription` to SPMBuildCore
- Conforms `Build.ModuleBuildDescription` to `SPMCore.ModuleBuildDescription`
- Adds a new field to BuildPlan and its protocol to expose build modules
- Uses buildModules to implement symbol graph extraction as a replacement for module graph + build plan lookups.
One less place that replies on `buildTriple` which brings us closer to its eventual removal.
=> [Build/Commands] Switch `SymbolGraphExtract` to use build plan

Package.swift, Sources/Basics/SQLite.swift, Tests/BasicsTests/Environment/EnvironmentKeyTests.swift
This adds a dependency on the new swift-toolchain-sqlite package, which allows swift-package-manager to build using swift build on Windows (including tests) without any additional flags or preinstalled dependencies.
It's "partial" because there is still one final blocker, which is that linking fails because we exceed the 65k exported symbol limit due to limitations in the build system, which can be addressed separately.
=> Add (partial) support for building on Windows using SwiftPM

Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Tests/BuildTests/BuildPlanTraversalTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
This is going to be used by sourcekit-lsp to build a graph/dictionary
of all the targets and depths they appear during package loading and
replaces the need for topological sort and `buildTriple`.
- Introduces a new `depthFirstSearch` variant which traverses all of the nodes in the graph.
- Adds a new method to `BuildPlan` - `traverseModules` which goes over the graph, computes destinations and returns modules with their parents and depths they appear at (the method looks though products).
This make it possible to switch sourcekit-lsp away from using topological sort and relying on `buildTriple`.
Paired with https://github.com/swiftlang/sourcekit-lsp/pull/1621
=> [BuildPlan] Add a way to traverse the graph and compute destinations for all modules

Sources/Commands/Utilities/TestingSupport.swift, Sources/PackageModel/Toolchain.swift, Sources/PackageModel/ToolchainConfiguration.swift, Sources/PackageModel/UserToolchain.swift, Sources/PackageModel/WindowsToolchainInfo.swift
- Explanation:
On macOS SwiftPM should prefer swift-testing installed into a custom toolchain when used. On Windows we need special logic to discover swift-testing location.
- Add special swift compiler "extra" flags to favor swift-testing installed in a toolchain.
- Inject `-I`, `-L` on Windows that point to where swift-testing is installed in SDKROOT.
- Inject a path to testing on `PATH` environment variable on Windows to make sure that the library is always discoverable.
- Main Branch PR: https://github.com/swiftlang/swift-package-manager/pull/7840
- Resolves: rdar://132828246
- Risk: Medium (Although changes are only viable with toolchains have certain directories in them and test we could do for testing was manual validation).
- Reviewed By: @MaxDesiatov @rintaro 
- Testing: Existing …
=> [6.0] Properly handle swift-testing installations in toolchain/SDK

Package.swift
This continues from the support added in #7866.
While we can't build on Windows as-is due to exceeding the 65k exported symbol limit, in turn due to limitations in the build system, we can apply -static to all of the library targets which are known to be linked statically, in order to get that symbol count down.
Note that this uses unsafeFlags, which is normally not recommended, however given that we are already using unsafeFlags elsewhere in the manifest, this seems reasonable enough for now until we can improve support for static linking on Windows.
Building the test targets still exceeds the symbol count though.
=> Add more support for building on Windows using SwiftPM

Sources/Basics/Collections/IdentifiableSet.swift, Sources/Build/BuildDescription/ClangModuleBuildDescription.swift, Sources/Build/BuildDescription/ModuleBuildDescription.swift, Sources/Build/BuildDescription/ProductBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildPlan/BuildPlan+Clang.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan+Swift.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/BuildPlanTraversalTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
This is yet another step (if not the last one) on the path to remove
`buildTriple` from `Resolved{Product, Module}` identifiers and switch
everything that requires destination to use information from the build
plan.
- Makes build descriptions identifiable just like `Resolved{Product, Module}.ID`
- Adds a way to traverse module  (both direct and recursive) dependencies starting from a module build description.
- Switches `BuildPlan.{target, product}Map` to `IdentifiableSet<{Product, Module}BuildDescription`.
`BuildTriple` is no longer used for build related operations such as planning and forming llbuild manifests.
=> [Build] Free `BuildPlan` from `BuildTriple`

Sources/Basics/Collections/IdentifiableSet.swift, Sources/Build/BuildDescription/ClangModuleBuildDescription.swift, Sources/Build/BuildDescription/ModuleBuildDescription.swift, Sources/Build/BuildDescription/ProductBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Clang.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildPlan/BuildPlan+Clang.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan+Swift.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Sources/_InternalTestSupport/MockPackageGraphs.swift, Tests/BuildTests/BuildPlanTraversalTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/PackageGraphTests/CrossCompilationPackageGraphTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
Reverts swiftlang/swift-package-manager#7882
The CI problem associated with this revert actually stems from swift-foundation hard-coding a path that is no longer valid because some tests in `FoundationEssentialsTests` test macros which means that xctest bundle is going to be built for `host` and get `-tool` suffix for its resources directory. Using non-prefixed directory was incorrect because it's not related to the bundle that would actually be run.
=> Un-Revert "[Build] Free `BuildPlan` from `BuildTriple`"

Tests/CommandsTests/TestCommandTests.swift
Remove some assertions from `testSwiftTestXMLOutputWhenEmpty()` that aren't strictly necessary and which have started to fail as we add Swift Testing to the toolchain.
=> Disable part of a test that fails with Swift Testing in the toolchain.

Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan.swift
Now that we have all the tools to compute destinations for dependencies of a product, 
we no longer need `buildTriple` here and dynamic/static library results could be represented
by build descriptions as a bonus.
- `BuildPlan.computeDependencies(of:)` has been updated to take a `ProductBuildDescription` and use depth first scan that computes destination;
- Further, dynamic and static library dependencies are now presented by build descriptions which means that we no longer need to look stuff up while planning.
One more use of `buildTriple` is gone.
=> [Build] NFC: Remove uses of `buildTriple` from `computeDependencies(of:)`

Sources/_AsyncFileSystem/AsyncFileSystem.swift, Sources/_AsyncFileSystem/MockFileSystem.swift, Sources/_AsyncFileSystem/OpenReadableFile.swift, Sources/_AsyncFileSystem/OpenWritableFile.swift, Sources/_AsyncFileSystem/ReadableFileStream.swift
Address some `InternalImportsByDefault` diagnostics in the `_AsyncFileSystem` which have crept in because the Swift 6 toolchain isn't enforcing `.enableExperimentalFeature("InternalImportsByDefault")`.
Both the `StrictConcurrency` and `InternalImportsByDefault` features became "upcoming" features instead of "experimental" features in the Swift 6 compiler. This means that specifying those features with `.enableExperimentalFeature()` no longer works with newer toolchains, and therefore these settings in SwiftPM's `Package.swift` have become inactive. I'm making the compiler more lenient, so that `-enable-experimental-feature` will enable the corresponding upcoming feature if relevant (https://github.com/swiftlang/swift/pull/75962) but in the meantime it appears that some of the code in …
=> Fix `InternalImportsByDefault` diagnostics in _AsyncFileSystem

CHANGELOG.md
There was a missing entry for SE-0441 and recursive dependencies entry was in "Next" but it's implemented in 6.0.
- Added an entry about SE-0441
- Moved the entry about recursive dependency support to Swift 6.0 section.
=> [CHANGELOG] NFC: Add an entry for SE-0441 and mark recursive dependencies as implemented in Swift 6

Tests/CommandsTests/TestCommandTests.swift
**Explanation:** Disables a non-critical bit of a test that's now failing in CI due to the addition of Swift Testing.
**Scope:** Bug fix in unit test.
**Issue:** N/A
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7885
**Risk:** Low
**Testing:** Self-testing.
**Reviewer:** @MaxDesiatov @bnbarham @rintaro
=> [6.0] Disable part of a test that fails with Swift Testing in the toolchain.

Sources/_AsyncFileSystem/AsyncFileSystem.swift, Sources/_AsyncFileSystem/ConcurrencySupport.swift, Sources/_AsyncFileSystem/ReadableFileStream.swift, Sources/_AsyncFileSystem/WritableStream.swift
SwiftPM doesn't build with all toolchains when the `InternalImportsByDefault` upcoming feature is properly enabled.
With the upcoming feature `InternalImportsByDefault` enabled, some versions of the Swift compiler diagnose this pattern:
```
import protocol _Concurrency.Actor
// error: package protocol cannot refine an internal protocol
package protocol Proto: Actor {
// ...
}
```
Address these diagnostics by using correct access levels for direct imports of `_Concurrency`.
SwiftPM builds with all relevant Swift compilers with `InternalImportsByDefault` enabled.
=> Fix more `InternalImportsByDefault` errors

Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
This setting shouldn't normally be overridden (except one edge case I'm leaving in for now because I haven't investigated to know whether it's safe to remove the ".o" suffix from the PRODUCT_NAME of library targets, which can be a separate step.
=> Remove redundant EXECUTABLE_NAME overrides in PIF

Sources/PackageModel/UserToolchain.swift, Tests/BuildTests/BuildPlanTests.swift
- Explanation:
Fixes a bug where keeping them together broke Symbol Graph Extract tool because it cannot handle `-Xlinker` flags.
- Main Branch PR: https://github.com/swiftlang/swift-package-manager/pull/7903
- Resolves: rdar://134406349
- Risk: Low (This is technically an NFC since it only re-arranging how to the flags are propagated but doesn't change them).
- Reviewed By: @MaxDesiatov 
- Testing: New tests were added to the test suite.
=> [6.0][PackageModel] Toolchain: Split SwiftTesting flags between swift compiler and linker

Fixtures/Miscellaneous/TestDiscovery/SwiftTesting/Package.swift, Sources/Commands/PackageCommands/Init.swift, Sources/PackageModelSyntax/AddTarget.swift, Sources/Workspace/InitPackage.swift, Sources/_InternalTestSupport/misc.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift, Tests/WorkspaceTests/InitTests.swift
This PR updates the package templates used by `swift package init` to use Swift Testing by default where possible, and to not add a package dependency on the Swift Testing open-source repository since it is now building in the toolchain.
Resolves rdar://128272585.
=> Update package templates to use Swift Testing in the toolchain rather than as a package dependency.

Fixtures/Miscellaneous/TestDiscovery/SwiftTesting/Package.swift, Sources/Commands/PackageCommands/Init.swift, Sources/PackageModelSyntax/AddTarget.swift, Sources/SPMTestSupport/misc.swift, Sources/Workspace/InitPackage.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift, Tests/WorkspaceTests/InitTests.swift
**Explanation:** Changes package templates to use Swift Testing by default instead of XCTest and removes package dependencies on the swift-testing package.
**Scope:** `swift package init`, `swift package add-target`
**Issue:** [N/A](rdar://128272585)
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7872
**Risk:** Moderate
**Testing:** Original PR tested with toolchain builds.
**Reviewer:** @bnbarham @briancroom @xedin
=> [6.0] Update package templates to use Swift Testing in the toolchain rather than as a package dependency.

Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
Reverts swiftlang/swift-package-manager#7906, which is causing failures in toolchain builds.
=> Revert "Remove redundant EXECUTABLE_NAME overrides in PIF"

Tests/CommandsTests/TestCommandTests.swift, Tests/WorkspaceTests/InitTests.swift
`canImport(Testing)` currently fails on the full toolchain test jobs due to various issues when building for both x86 and arm64. Temporarily remove this check until we can fix the underlying problems there.
=> Temporarily disable new Swift Testing tests

Tests/CommandsTests/TestCommandTests.swift, Tests/WorkspaceTests/InitTests.swift
**Explanation:** Disables non-critical tests that's now failing in Swift CI macOS packages due to the addition of Swift Testing.
**Scope:** Tests
**Issue:** N/A
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7916
**Risk:** Low, there's integration tests covering this case. The main downside is a lack of PR testing.
**Testing:** Will run the full package test to make sure this fixes the issue
**Reviewer:** TBD
=> [6.0] Temporarily disable new Swift Testing tests

Fixtures/Miscellaneous/TestDiscovery/SwiftTesting/Package.swift, Sources/Commands/PackageCommands/Init.swift, Sources/PackageModelSyntax/AddTarget.swift, Sources/SPMTestSupport/misc.swift, Sources/Workspace/InitPackage.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift, Tests/WorkspaceTests/InitTests.swift
**Explanation:** Changes package templates to use Swift Testing by default instead of XCTest and removes package dependencies on the swift-testing package.
**Scope:** `swift package init`, `swift package add-target`
**Issue:** [N/A](rdar://128272585)
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7872
**Risk:** Moderate
**Testing:** Original PR tested with toolchain builds.
**Reviewer:** @bnbarham @briancroom @xedin
=> [6.0.0] Update package templates to use Swift Testing in the toolchain rather than as a package dependency.

Tests/BasicsTests/AsyncProcessTests.swift
This API is not used anywhere in the SwiftPM codebase, but tests covering it are flaky.
rdar://133548796
=> Disable `testAsyncStream*` in `AsyncProcessTests.swift`

Sources/QueryEngine/CacheKey.swift, Sources/QueryEngine/Query.swift, Sources/QueryEngine/QueryEngine.swift, Tests/QueryEngineTests/QueryEngineTests.swift
This vendors fixes to `HashEncoder` from `swift-sdk-generator` introduced in https://github.com/swiftlang/swift-sdk-generator/pull/97 and https://github.com/swiftlang/swift-sdk-generator/pull/134.
=> Fix direct `FilePath` hashing in `QueryEngine`

Sources/_AsyncFileSystem/AsyncFileSystem.swift, Sources/_AsyncFileSystem/OpenReadableFile.swift, Sources/_AsyncFileSystem/ReadableFileStream.swift
AsyncFileSystem is going to be vendored into swift-sdk-generator (https://github.com/swiftlang/swift-sdk-generator/pull/136), and the tool is built with bootstrapping toolchain that is Swift 5.8 on ci.swift.org. This commit makes the vendored AsyncFileSystem compatible with Swift 5.8 by avoiding the use of SE-0380
=> Keep loose compatibility with Swift 5.8 in AsyncFileSystem

Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
Used by https://github.com/swiftlang/sourcekit-lsp/pull/1643
Allows us to achieve parity between sourcekit-lsp's configuration options and SwiftPM's `--triple`/`--swift-sdk`.
Make `SwiftSDK.deriveTargetSwiftSDK` public
See https://github.com/swiftlang/sourcekit-lsp/pull/1643
=> Make deriveTargetSwiftSDK public

Sources/Basics/AuthorizationProvider.swift, Tests/BasicsTests/AuthorizationProviderTests.swift
Reverts swiftlang/swift-package-manager#7662
It would be a breaking change if someone is using `token` as their username, and we don't have a migration path or any other means to clarify this breaking change to the users.
=> Revert "Fix: use bearer auth when pulling binaryTarget or packages from a package registry"

Sources/PackageDescription/BuildSettings.swift
This fixes confusing wording in a documentation comment: `.interoperabilityMode` enables interoperability _between_ Swift and C++.
This also changes the doc comment for a parameter of this method: the actual value of `InteroperabilityMode` is spelled as `Cxx`, not `CXX`.
=> [cxx-interop] Improve wording of doc comment

Sources/_InternalTestSupport/XCTAssertHelpers.swift
Unsure where `CI` is being set, but it doesn't seem to be on Linux at the very least. `SWIFTCI_USE_LOCAL_DEPS` is definitely set everywhere, use it instead.
=> Use `SWIFTCI_USE_LOCAL_DEPS` as the CI check

CHANGELOG.md
`CHANGELOG.md` had a broken link. Additionally, `swift sdk install --checksum` change introduced in #7722 seems to be changelog-worthy, but was previously missing.
=> Fix link in `CHANGELOG.md`, add `swift sdk install --checksum` item

IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift, Tests/XCBuildSupportTests/PIFTests.swift
This reverts commit 9608baf9d0b774a9f43b2239162c418765b8be5b.
This version is a bit more thorough. Tested that it's able to build SwiftPM itself and a couple other packages.
=> Reapply "Remove redundant EXECUTABLE_NAME overrides in PIF" (#7915)

Sources/PackageLoading/ManifestLoader.swift
ManifestLoaderProtocol.load was forwarding a checked continuation's resume method directily as a completion handler, resulting in the warning:
```
converting a value of type '(__shared sending Result<Manifest, any Error>) -> ()' to type '(Result<Manifest, any Error>) -> Void' risks causing data races; this is an error in the Swift 6 language mode
```
=> ManifestLoader.swift: Address concurrency warning

Sources/Basics/Concurrency/AsyncProcess.swift, Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift, Sources/PackageRegistry/ChecksumTOFU.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/SPMBuildCore/Plugins/PluginScriptRunner.swift, Sources/Workspace/PackageContainer/FileSystemPackageContainer.swift, Sources/Workspace/PackageContainer/RegistryPackageContainer.swift, Sources/Workspace/PackageContainer/SourceControlPackageContainer.swift, Sources/Workspace/Workspace+Editing.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockWorkspace.swift
Fix the rest of the concurrency warnings caused by directly passing a continuation's resume method.
Follow on to #7961
=> Address concurrency warnings

Tests/BasicsTests/AsyncProcessTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Fixes up a few different types of warnings in the tests:
- Unused variables are replaced with `_`
- Continuation handlers are not passed through directly (follows on from #7961)
- Removes unnecessary `await`s from functions that are now synchronous
=> Fixup warnings in tests

Sources/Build/LLBuildCommands.swift
**Explanation:** Remove `@MainActor` annotations from corelibs-xctest glue functions that are no longer needed.
**Scope:** corelibs-xctest glue code
**Issue:** [N/A](rdar://130066460)
**Original PR:** N/A
**Risk:** Unknown
**Testing:** Existing CI jobs
**Reviewer:** @bnbarham @briancroom @DougGregor @shahmishal
=> [6.0.1] Remove `@MainActor` from XCTest glue.

Sources/PackageDescription/SupportedPlatforms.swift
Resolves https://github.com/swiftlang/swift-package-manager/issues/7968
rdar://136209148
=> PackageDescription: add 2024 Darwin OS versions to `SupportedPlatforms`

Sources/PackageDescription/SupportedPlatforms.swift
Cherry-pick of #7969.
**Explanation**: New versions of Darwin OSes are not available as supported platforms in package manifest APIs.
**Scope**: isolated to `SupportedPlatforms.swift` in `PackageDescription` public API.
**Risk**: low, no existing code was changed, new constants were defined in the same way as they were defined for previous versions.
**Testing**: manually verified new versions are available.
**Issue**: rdar://136209148
**Reviewer**: @plemarquand
=> [6.0.0] Add 2024 Darwin OS versions to `SupportedPlatforms`

Sources/Commands/PackageCommands/EditCommands.swift, Sources/Workspace/Workspace+Editing.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Sources/_InternalTestSupport/PackageGraphTester.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fixes #7931
`swift package edit` was reliant on the user-passed `packageName` argument to be able to both find the dependency (which needs the identity) as well as to match the manifest display name.
Default to treating the user-passed argument as a package identity, and fix the comparisons made to the manifest by instead assuring that the canonical locations for the manifest and the dependency match. The display name was intended to be deprecated.
The vscode-swift extension made use of of the package identities when listing dependencies in its UI. When a user would execute a `Use Local Version` on one of these dependencies, it would call `swift package edit <package-name>` under the hood, using the identity for the package-name argument. However, this would fail as the `edit` command …
=> Fix discrepancies with usage of package display name/package identity in `swift package edit` command

Sources/PackageDescription/SupportedPlatforms.swift
Cherry-pick of #7969.
**Explanation**: New versions of Darwin OSes are not available as supported platforms in package manifest APIs.
**Scope**: isolated to `SupportedPlatforms.swift` in `PackageDescription` public API.
**Risk**: low, no existing code was changed, new constants were defined in the same way as they were defined for previous versions.
**Testing**: manually verified new versions are available.
**Issue**: rdar://136209148
**Reviewer**: @plemarquand
=> [6.0.1] Add 2024 Darwin OS versions to `SupportedPlatforms`

README.md
Update the "Getting Started" guide link.
The README for this project was using an outdated link to the "Getting Started" page on swift.org
Updated the link
Link now points to the correct page
=> #7975 Update "Getting Started" guide link

Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Tests/BuildTests/BuildPlanTraversalTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
Companion of https://github.com/swiftlang/sourcekit-lsp/pull/1683
---
Opening the SourceKit-LSP workspace using a debug build of sourcekit-lsp takes about 35s because `traverseModules` generates about 800,000 callback calls. All SourceKit-LSP needs now are the modules and their dependencies, so we can refactor `traverseModules` to just return that information avoid visiting the same modules multiple times. With theses changes getting all modules and their dependencies only takes ~0.013s.
rdar://136107035
=> Change `traverseModules` to return modules with their dependencies

Tests/PackageSigningTests/SigningTests.swift
`swift-certificates` now implements initializer that accepts `Date` and doesn't throw which means this method is redundant but also incorrect because overloading only on `throws` is ambiguous in most cases due to throws checking not being part of the expression checking.
Uses of this overload type-checked only because it was always preferred before due to old type-checker hacks that we are trying to remove.
- Removes `GeneralizedTime.init(_:) throws` that was added before `swift-certificates` introduced their own non-throwing version.
No more duplicate code that is less safe than what `swift-certificates` vends.
=> [Tests] NFC: Remove overload of `GeneralizedTime.init(_:)`

Sources/_AsyncFileSystem/MockFileSystem.swift, Sources/_AsyncFileSystem/OSFileSystem.swift, Sources/_AsyncFileSystem/OpenWritableFile.swift, Tests/_AsyncFileSystemTests/AsyncFileSystemTests.swift
This expands available `AsyncFileSystem` APIs and brings them in sync with `swift-sdk-generator` as implemented in https://github.com/swiftlang/swift-sdk-generator/pull/136.
=> Add `OSFileSystem` to complement `MockFileSystem`

Sources/SPMBuildCore/Plugins/PluginContextSerializer.swift
Avoid using `String(describing:)` to create strings that can be utilized by consumers.
Version and revision strings with `Optional(...)` in them look less-than-great
Utilized `thing?.description ?? "nil"` rather than `String(describing: thing)`.
Improved the readability of `displayVersion` and `scmRevision` in a `Package`'s `origin: PackagePlugin.PackageOrigin`.
=> Improve displayVersion and scmRevision description exposed by PluginContextSerializer

Sources/Build/LLBuildCommands.swift
Removes `@MainActor` and adds `nonisolated(unsafe)` to suppress concurrency diagnostics in the XCTest glue code generated when using corelibs-xctest.
See also #7960.
=> Remove `@MainActor` from XCTest glue.

Sources/Build/LLBuildCommands.swift
**Explanation:** Remove `@MainActor` annotations from corelibs-xctest glue functions that are no longer needed.
**Scope:** corelibs-xctest glue code
**Issue:** [N/A](rdar://130066460)
**Original PR:** https://github.com/swiftlang/swift-package-manager/pull/7967
**Risk:** Unknown
**Testing:** Existing CI jobs
**Reviewer:** @bnbarham @briancroom @DougGregor @shahmishal
=> [6.0] Remove `@MainActor` from XCTest glue.

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Tests/BuildTests/BuildPlanTests.swift
Updates SwiftPM to enable WMO for targets with experimental-feature Embedded. Unifies the logic to enable WMO into
SwiftModuleBuildDescription.
=> Enable WMO for Embedded targets automatically

Sources/PackagePlugin/PackageModel.swift
The directoryURL property was added to all of the concrete Target implementations, such as SwiftSourceModuleTarget, ClangSourceModuleTarget, and so on, but not to the base protocol itself.
This means you need a bunch of conditional casts when trying to access the directoryURL in a package plugin.
Closes: #8001
=> directoryURL is missing from the Target protocol in the PackagePlugin APIs

Sources/Basics/CMakeLists.txt, Sources/Basics/URL.swift, Sources/PackagePlugin/Context.swift, Sources/PackagePlugin/PackageManagerProxy.swift, Sources/PackagePlugin/Path.swift, Sources/PackagePlugin/Plugin.swift, Sources/PackagePlugin/PluginContextDeserializer.swift, Sources/SPMBuildCore/Plugins/PluginContextSerializer.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Due to RFC8089 compliance changes for Foundation.URL in Swift 6, URL.path does _NOT_ behave as one might expect, producing a path with a leading slash which will be interpreted by Windows as relative.
Closes #6851
=> Fix path handling for plugins on Windows

Sources/PackageDescription/SupportedPlatforms.swift
Also update the text for previously deprecated APIs to match the now oldest supported version (12.0 for either of these OSes).
This change previously landed in Xcode 15.
rdar://108752382
=> Deprecate tvOS 11.0 and iOS 11.0 deployment target API

Sources/Basics/HTTPClient/LegacyHTTPClientRequest.swift
`LegacyHTTPClientRequest` can be trivially Sendable.
This suppresses some warnings in `LegacyHTTPClient` which itself should also be made concurrecy safe eventually, but it holds some static shared state and so isn't a straightforward conversion.
=> Mark `LegacyHTTPClientRequest` as Sendable

Sources/Build/TestObservation.swift
Compiling test runners with `import Bionic` worked till July, then the compiler started requiring the larger `import Android` overlay.
`import Android` instead in the test runner
Compiling the tests for Android works again.
This is part of a larger patch I needed to natively run SwiftPM 6 on Android, but I want to get this into the 6.0 patch releases quickly first because it also breaks cross-compilation of packages' tests to Android.
@bnbarham, can we get this into 6.0.2 next?
=> Fix compiling test runners for Android by using the full overlay

Sources/Build/TestObservation.swift
__Explanation:__ Compiling test runners with `import Bionic` worked till July, then the compiler started requiring the larger `import Android` overlay.
__Scope:__ Only affects Android
__Original PR:__ #8018
__Risk:__ None
__Testing:__ I built and ran the SwiftPM tests natively on Android with this patch.
__Reviewer:__ @bnbarham 
Since this issue broke cross-compiling all packages' tests for Android and presents no risk for other platforms, I'd like to get it in quickly for the next patch release.
=> [6.0.2] Fix compiling test runners for Android by using the full overlay

Sources/Build/TestObservation.swift
__Explanation:__ Compiling test runners with `import Bionic` worked till July, then the compiler started requiring the larger `import Android` overlay.
__Scope:__ Only affects Android
__Original PR:__ #8018
__Risk:__ None
__Testing:__ I built and ran the SwiftPM tests natively on Android with this patch.
__Reviewer:__ @bnbarham
I will submit for 6.0.2 next, if that's okay.
=> [6.0.3] Fix compiling test runners for Android by using the full overlay

Sources/Basics/Triple+Basics.swift, Tests/BasicsTests/TripleTests.swift
Adds a fake extension for none os dynamic libraries to avoid a SwiftPM crash during build planning when cross compiling to none OS with a dylib product in the graph.
Fixes #7893
=> Add a fallback extension none os dylibs

Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/ResourcesTests.swift
Such tests cause the driver to take a code-path that results in a warning: `warning: Unable to locate libSwiftScan. Fallback to `swift-frontend` dependency scanner invocation.`
This needs to be taken into account.
=> Add an expectation of a warning diagnostic to tests that hide `libSwiftScan`.

Fixtures/Miscellaneous/CheckTestLibraryEnvironmentVariable/Tests/CheckTestLibraryEnvironmentVariableTests/CheckTestLibraryEnvironmentVariableTests.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/CommandsTests/TestCommandTests.swift
The autoclosure expression `{ throw error }` just creates a closure that won't be executed. It leads to the test always succeeding even if the `expression` throws an error.
Fortunately, I didn't find any issue to enable the assertion except for a single case (https://github.com/swiftlang/swift-package-manager/pull/8026/commits/ab1e7849216aba671ed031993972c03f643649cf)
=> Tests: Fix always succeeding `XCTAssertAsyncNoThrow`

Sources/swift-bootstrap/main.swift, Utilities/bootstrap
These modules are well established now, so this hack should no longer be needed
=> Stop disabling implicit import of _Concurrency and _StringProcessing in bootstrap

Package.swift
When `SWIFTSYNTAX_BUILD_DYNAMIC_LIBRARY` is specified, change swift-syntax dependencies to depend on a single `_SwiftSyntaxDynamic` product instead of separate products for each module.
This allows us to build SourceKit-LSP on Windows using SwiftPM without exceeding the maximum symbol limit and thus run SourceKit-LSP tests on Windows.
See https://github.com/swiftlang/sourcekit-lsp/pull/1754 and https://github.com/swiftlang/swift-syntax/pull/2879.
=> Allow building against a single dynamic swift-syntax library

Sources/PackageModel/SwiftSDKs/SwiftSDK.swift, Tests/PackageModelTests/SwiftSDKBundleTests.swift
When cross-compiling with `--triple` CLI option, an implicit toolset is created as an exact copy of the host Swift SDK toolset.  This is wrong, since CLI options used for the host toolset don't always make sense for the target toolset. `-fPIC` is one example, which is an option always used for both host and target toolchains even when cross-compiling. Embedded targets, like `wasm32-unknown-none-wasm` don't support certain codegen features (like `-mreference-types`) when `-fPIC` is enabled.
With this patch, host toolchains still pass `-fPIC` to clang, but target options for clang and other tools are empty by default and are no longer populated with host toolset extra CLI options, when `--triple` CLI option is specified.
Cross-compiling with `--triple wasm32-unknown-none-wasm` and `-Xcc …
=> Fix target toolsets polluted with host toolset extra CLI options

Fixtures/Miscellaneous/Plugins/CommandPluginTestStub/Package.swift, Fixtures/Miscellaneous/Plugins/CommandPluginTestStub/Plugins/check-testability/main.swift, Fixtures/Miscellaneous/Plugins/CommandPluginTestStub/Sources/InternalModule/InternalModule.swift, Fixtures/Miscellaneous/Plugins/CommandPluginTestStub/Tests/InternalModuleTests/InternalModuleTests.swift, Sources/Build/BuildDescription/ProductBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Build/LLBuildCommands.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/TestingSupport.swift, Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+Testing.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/SPMBuildCoreTests/BuildParametersTests.swift
When building a SwiftPM target through PackagePlugin APIs and overall configuration is debug, they were built with `-enable-testing` even with plugins requests building with release configuration.
This mis-configuration led performance and code size regression only when building through package plugins.
The root problem is that some of the properties under `BuildParameters` store values derived from other properties. 
`buildParameters.testing.enableTestability` was one of them. It depends on `configuration` but it's computed only in `BuildParameters.Testing` initializer. Therefore the property was not updated after `PluginDelegate` modifies `configuration` for requested builds.
https://github.com/swiftlang/swift-package-manager/blob/23fa2816afb930d98f529026f4809cc781fb2e2f/Sources/Commands …
=> Plugin: Stop building with `-enable-testing` even with release config

Sources/Commands/PackageCommands/Init.swift, Sources/Commands/SwiftTestCommand.swift, Sources/CoreCommands/Options.swift, Sources/PackageModel/UserToolchain.swift
- Explanation:
On macOS SwiftPM should use the swift-testing installed into a CommandLineTools when it exists and skip xctest if it isn't available.
- Main Branch PR: https://github.com/swiftlang/swift-package-manager/pull/7840 (was previously only partially cherry-picked) and https://github.com/swiftlang/swift-package-manager/pull/7805
- Resolves: rdar://136424541
- Risk: Low
- Reviewed By: @MaxDesiatov @rintaro 
- Testing: Existing tests and manual validation using new toolchain
=> [6.0][PackageModel] UserToolchain: Add -F when building with CommandLineTools

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Method [generateManifestFileContents(packageDirectory:)](https://github.com/swiftlang/swift-package-manager/blob/80b1e179bef19e6eb71b0d20b2cb471053ae1b2c/Sources/PackageModel/ManifestSourceGeneration.swift#L33) is generating invalid manifest if the manifest has a ProductDescription with a library with dynamic type.
Specificaly the in the generated Manifest it places the type: .dynamic, after the targets.
The problem in [here](https://github.com/swiftlang/swift-package-manager/blob/80b1e179bef19e6eb71b0d20b2cb471053ae1b2c/Sources/PackageModel/ManifestSourceGeneration.swift#L204) where the code that adds the dynamic type is after the code that adds the targets.
=> When generating manifest the type should be before the targets

Sources/Commands/PackageCommands/AddProduct.swift, Sources/Commands/PackageCommands/AddTarget.swift, Sources/Commands/PackageCommands/Describe.swift, Sources/Commands/PackageCommands/ShowDependencies.swift, Sources/CoreCommands/Options.swift, Sources/swift-bootstrap/main.swift
The swift-argument-parser library will automatically show the available values for options that implement the CaseIterable protocol. There are options in SwiftPM that do either list the available values statically in the help message, which can be stale, or don't provide a list at all, which leaves the user to guess the value that they want. Sweep these options, removing the static list, sometimes adding the help message based on the swift documentation. Since the CaseIterable doesn't provide a description of each value, leave the options alone that provide detail for each of their available values.
The result of these changes is that the online help (and content assist) is able to automatically display all of the available values for certain options. Also, some of the options have a help …
=> Use `CaseIterable` to auto-generate CLI `--help` entries

Sources/Basics/Concurrency/AsyncProcess.swift
Using `availableData` causes parallel XCTest execution to hang on Windows if the tests output significant data to stderr.
=> Use `readData` to read data from a pipe instead of `availableData`

Sources/Build/BuildOperation.swift, Sources/Build/LLBuildProgressTracker.swift
If a PackageStructure build needs to occur during a `swift test list --skip-build` command there is no newline printed to the terminal, causing the first line of listed tests to appear on the same line as the progress, i.e:
`[1/1] Planning buildTestPackageTests.example()`
This doesn't occur when you omit `--skip-build` because there is code in the `LLBuildProgressTracker.swift` that calls
`progressAnimation.complete(success:)` when a build completes. Ideally I'd like to contain this logic to the LLBuildProgressTracker, however for a PackageStructure build the relevant buildComplete delegate method is never called.
=> Ensure a newline is printed after Planning build

Sources/Commands/PackageCommands/CompletionCommand.swift
Follow on to #8045 to make the completion-list tool use the CaseIterable support in swift-argument-parser to automatically enumerate the options.
`list-snippets` was missing from the list, and is now added.
=> Update completion-list help string

Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageModel/SwiftSDKs/SwiftSDK.swift, Sources/PackageModel/Toolset.swift, Sources/PackageModel/UserToolchain.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/SwiftCommandStateTests.swift, Tests/PackageModelTests/SwiftSDKBundleTests.swift, Tests/PackageModelTests/ToolsetTests.swift
The only feature proposed in [SE-0387](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md) that remains unimplemented is the `--toolset` CLI option:
> We propose that users also should be able to pass `--toolset <path_to_toolset.json>` option to `swift build`, `swift test`, and `swift run`.
>
> We'd like to allow using multiple toolset files at once. This way users can "assemble" toolchains on the fly out of tools that in certain scenarios may even come from different vendors. A toolset file can have an arbitrary name, and each file should be passed with a separate `--toolset` option, i.e. `swift build --toolset t1.json --toolset t2.json`.
>
> All of the properties related to names of the tools are optional, which allows merging …
=> SE-0387: add `--toolset` option to build-related subcommands

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/SourceKitLSPAPI/BuildDescription.swift
We currently always write the output file map when calling `SwiftModuleBuildDescription.emitCommandLine`. This means that every time SourceKit-LSP queries build settings for a source file, we write the output file map. This is causing issues in SourceKit-LSP on Windows because we might be running a build (eg. for target preparation), which writes an output file map and at the same time try to get build settings for that file inside SourceKit-LSP, which calls into `emitCommandLine`, also trying to write an output file map, which fails because the output file map is exclusively opened by the build and thus cannot also write the output file map.
While this might seem like a more theoretical race condition, this caused multiple tests to fail when running SourceKit-LSP tests locally on my …
=> Don’t write output file map when getting compiler arguments for SourceKit-LSP

Sources/Basics/SwiftVersion.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Utilities/build-using-self
Running `swift package --version` indicate it is in development mode, while `swift --release` does not.
```
❯ swift --version  
Apple Swift version 6.0.1 (swift-6.0.1-RELEASE)
Target: arm64-apple-macosx15.0
❯ swift package --version
Swift Package Manager - Swift 6.0.1-dev
```
Toggling `isDevelopment` boolean to `false` in `SwiftVersion` struct extension.
```
❯ swift build --show-bin-path
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/.build/arm64-apple-macosx/debug
❯ /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/.build/arm64-apple-macosx/debug/swift-package --version
Swift Package Manager - Swift 6.0.2
```
=> Disable SwiftVersion development mode

Sources/Basics/SQLiteBackedCache.swift, Tests/BasicsTests/SQLiteBackedCacheTests.swift
When `--scratch-path` is set to a directory whose parent directory does not exist and `--manifest-cache local` is set, the initial manifest cache creation fails with the following warning:
```
warning: 'tmp.vulugm1mqv': failed loading cached manifest for 'tmp.vulugm1mqv': Error Domain=NSCocoaErrorDomain Code=4 "The file “check” doesn’t exist." UserInfo={NSFilePath=/private/var/folders/k2/q6yzck31253_q1j4kxkzq5jh0000gn/T/tmp.vUlUgM1Mqv/.build/check, NSUnderlyingError=0x600001072ac0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
warning: 'tmp.vulugm1mqv': failed storing manifest for 'tmp.vulugm1mqv' in cache: Error Domain=NSCocoaErrorDomain Code=4 "The file “check” doesn’t exist." UserInfo={NSFilePath=/private/var/folders/k2/q6yzck31253_q1j4kxkzq5jh0000gn/T/tmp.vUlUgM1 …
```
=> Fix initial manifest caching with nested scratch dir and local cache

Fixtures/Miscellaneous/Errors/FatalErrorInSingleXCTest/TypeLibrary/.gitignore, Fixtures/Miscellaneous/Errors/FatalErrorInSingleXCTest/TypeLibrary/Package.swift, Fixtures/Miscellaneous/Errors/FatalErrorInSingleXCTest/TypeLibrary/Sources/TypeLibrary/TypeLibrary.swift, Fixtures/Miscellaneous/Errors/FatalErrorInSingleXCTest/TypeLibrary/Tests/TypeLibraryTests/TypeLibraryTests.swift, Package.swift, Sources/_InternalTestSupport/misc.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/_InternalTestSupportTests/Misc.swift
Add an automated tests that ensures swift-build and swift-test emit the expected amount of `error: fatalError` message on the console output.
Issue #6605  reported `error: fatalError` was emitted twice to the console output, and has since been fixed.  We should ensure the issue does not regress.
Add an automated tests that verifies `swift-build` does not emit a `error: fatalError` in `stdout` or `stderr` when a building a test that does not compile.
```
❯ swift test --filter TestGetNumberOfMatches --filter testFatalErrorDisplayedOnlyOnceWhenSingleXCTestHasFatalErrorInBuildCompilaation
Building for debugging...
[10/10] Linking SwiftPMPackageTests
Build complete! (9.88s)
Test Suite 'Selected tests' started at 2024-10-25 13:59:47.463.
Test Suite 'SwiftPMPackageTests.xctest' started at …
```
=> Test: ensure swift-[build|test] emit expected number of fatal error on console

Sources/Basics/Concurrency/ThreadSafeBox.swift, Sources/Workspace/Diagnostics.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/_InternalTestSupport/MockHTTPClient.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
To adopt Swift concurrency in `ManifestLoader`, we need to convert `RegistryClient` first, which then would require use of `HTTPClient` instead of `LegacyHTTPClient`. That would also cascade to `BinaryArtifactsManager`, so I'm starting there first to make PRs smaller.
Converted (and as a consequence, simplified) code in `Workspace+BinaryArtifacts.swift`, also adopted `HTTPClient` in `WorkspaceTests` to fix tests after the change.
Converted some error diagnostics to conform to `Error`, which makes control flow with `ObservabilityScope.trap` wrapper easier to write and read.
One major previous adopter of `LegacyHTTPClient` is now compatible with Swift concurrency.
Since `BinaryArtifactsManager` was blocking Swift concurrency thread pool and also used `.sharedConcurrent` dispatch queue, this …
=> Use async `HTTPClient` in `BinaryArtifactsManager`

Package.swift
Loosen version constraint on swift-system
Allow adoption of build fixes from swift-system-1.4.0 in clients. Does not update update-checkout at this time
=> Loosen swift-system version constraint

Documentation/PackageRegistry/registry.openapi.yaml
The OpenAPI document for Swift Package Registry was incomplete and didn't contain all the requirements described in the related Swift Evolution proposals.
Rewrote the OpenAPI document based on the current reading of all the Swift Package Registry Swift Evolution proposals and documentation in this repository.
You can view the rendered version of the docs at: https://editor.swagger.io/?url=https://raw.githubusercontent.com/czechboy0/swift-package-manager/refs/heads/hd-refresh-registry-openapi/Documentation/PackageRegistry/registry.openapi.yaml
A much more accurate OpenAPI doc, one that can be used for code generation.
=> Refresh the Swift Package Registry OpenAPI document

Sources/Workspace/InitPackage.swift
https://github.com/swiftlang/sourcekit-lsp/pull/1803 is moving `.index-build` to be a subdirectory of `.build`.
=> Remove `/.index-build` from the `.gitignore` generated by `swift package init`

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Tests/BuildTests/WindowsBuildPlanTests.swift
On Windows, there is a limit of around 64K to the number of symbols a DLL/EXE can export. We hit that regularly with large projects like SwiftPM itself. This hides those symbols and only exposes the ones requested for a DLL.
For Windows triples only, creates a parallel build graph for Swift modules, one for static linking using -static, and one for exporting linking which is the default. DLL products consume their direct target dependencies as exporting. All other dependencies use the static versions to eliminate unnecessary symbol exports.
The bulk of this is managed by the SwiftModuleBuildDescription which will create a duplicate of itself for the exporting case and set its own type to static linking. Both modules are fed to the planner to create llbuild swift command tasks. Code is …
=> Support separate modules for static and dynamic exporting symbols for Windows

Sources/Build/BuildDescription/ClangModuleBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
Add `resources`, `ignored`, and `other` files to `BuildTarget` for use by SourceKit-LSP.
This is tracked by rdar://139431738 as part of swiftlang/vscode-swift#562
SourceKit-LSP needs to be able to determine which target contains a given DocC catalog in order to fulfill documentation related requests. However, the catalog is not listed as one of the `sources` or `headers`. Rather, it is part of `other` files in most cases. Expose all file types to SourceKit-LSP so that it can properly determine which target a given file belongs to.
Added three new properties to `BuildTarget`: `resources`, `ignored`, and `other` which are arrays of `URL` pointing to the given file types in the target.
SourceKit-LSP will be able to see all files contained within a given target.
=> Expose all target files to SourceKit-LSP

Sources/Basics/Netrc.swift, Tests/BasicsTests/NetrcTests.swift
Hash symbols were always treated as the beginning of a comment even if they were in the middle of a username or password. To address this require some whitespace before a hash character before a comment is parsed.
That patch also implements support for quoted fields so that passwords can contain the sequence "foo #bar" without dropping "bar" as a comment.
Issue: #8090
=> Handle hash characters (#) in netrc fields

Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
`URL.path` returns a URL path with forward slashes. We need to go through `withUnsafeFileSystemRepresentation` to get a Windows file system path with backslashes.
Fixes https://github.com/swiftlang/sourcekit-lsp/issues/1775
=> Use Windows-style paths with backslashes in SourceKit-LSP compiler arguments for plugins

Sources/Workspace/Workspace+Manifests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fixes #8079
Allows unsafe flags for edited packages
Edited packages in SwiftPM should be allowed to use unsafe flags.
Adjusted logic in `unsafeAllowedPackages` to add `.edited` packages to the allowed list, alongside the root package and `.fileSystem` packages
After this change, edited packages will be permitted to use unsafe flags.
=> Add Package edit support for packages with unsafe flags

Utilities/bootstrap, Utilities/helpers.py
This enables detailed analysis of timings of different build phases of the bootstrap scripts.
Log messages as produced by `Utilities/helpers.py` also output timestamps in the ISO format.
It's easier to analyze build phases timing.
=> Log timestamps in the bootstrap scripts

Tests/FunctionalTests/TraitTests.swift
Disable assertion in `TraitTests`, which was never executed on macOS due to the self-hosted macOS pipeline running Swift 5.9..2, and test being wrapped around `#if compiler(>=6.0)` pre-processor.
The assertion in `TraitTets` that ensured warnigs do not appear in stderr are failing against the 6.1 toolchain.  Since 1) this test was never executed against macOS, since the self-hosted macOS pipeline was running Swift 5.9.2, and 2) work is underway to productive the Traits feature, it was decided to disable the assert for now, and open a GitHub issue to re-enable the assert with the production work.
This change removes the assert for GitHub issue 8131, which must be re-enabled when the respective issue is fixed.
Disabled assertion the the `TraitTests`
```
swift test --filter "TraitTests"
``` …
=> Tests: Disable assert in TraitTests

Sources/Basics/SwiftVersion.swift
https://github.com/swiftlang/swift/pull/77799
=> Bump the Swift version to 6.2

Sources/PackageLoading/ManifestLoader.swift, Sources/SPMBuildCore/Plugins/DefaultPluginScriptRunner.swift
Builds of packages using package plugins may fail on Windows with the following error:
```
error: plugin process ended by an uncaught signal: 309 <command: C:\foo\.build\plugins\cache\myplugin.exe>, <output:
>
```
309 translates to 0x135, which maps to 0xc0000135 aka STATUS_DLL_NOT_FOUND.
This is due to the following code in DefaultPluginScriptRunner.swift:
```swift
#if os(Windows)
let pluginLibraryPath = self.toolchain.swiftPMLibrariesLocation.pluginLibraryPath.pathString
var env = ProcessInfo.processInfo.environment
if let Path = env["Path"] {
env["Path"] = "\(pluginLibraryPath);\(Path)"
} else {
env["Path"] = pluginLibraryPath
}
process.environment = env
#endif
```
Environment variable names are case-insensitive on Windows. On a real Windows host, it tends to be spelled "Path". In a …
=> Package plugins don't work on Windows if the PATH environment variable isn't accessed with the right case

Package.swift, Sources/Basics/SQLite.swift
I've been building with this patch both natively on Android and [on my Android CI](https://github.com/finagolfin/swift-android-sdk/blob/3493a85cd1ae767792ba01c8634e3d9456d19901/swift-android-ci-except-release.patch#L34), confirming that it [got rid of the external dependency on `libsqlite3.so`](https://github.com/finagolfin/swift-android-sdk/actions/runs/12095721068/job/33729218006#step:8:20591) and works well.
@jakepetroules, along with your recent llbuild pull, this gets rid of the external SQLite3 dependency for the Android toolchain except for one llbuild executable, `swift-build-tool`, whose build is configured by CMake and appears to be unused, so we can clean that up last.
=> Android: switch to the new swift-toolchain-sqlite package instead of requiring an external dependency

Utilities/bootstrap
This is a prerequisite for enabling incremental builds when running `./Utillities/bootstrap build --release` and `./Utilities/bootstrap test --release` in a sequence.
Environment variables passed to `swift-bootstrap` from `./Utilities/bootstrap build` and `./Utilities/bootstrap test` commands unnecessarily differed slightly, which caused generated build manifests to be different. This precluded incremental builds when running these commands in a sequence one after each other, slowing down our CI jobs.
Moved env var computation logic to the existing `get_swiftpm_env_cmd` function in `Utilities/bootstrap`.
`swift-bootstrap` is consistently called with the same environment variables, ensuring that generated build manifests can be the same, eventually enabling incremental builds.
=> Unify env vars for `Utilities/bootstrap` commands

Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift
Use `AbsolutePath.asURL` instead of creating a new URL from the path string.
The original PR that added `resources`, `ignored`, and `other` files to `BuildTarget` should have used `AbsolutePath.asURL` instead of creating a new URL from the path string. This PR fixes that in order to maintain a single location where absolute paths can be converted to URLs.
I've replaced the `AbsolutePath` to `URL` mappings in `SourceKitLSPAPI` with calls to `AbsolutePath.asURL`.
This PR does not have an affect on the functionality of Swift Package Manager.
=> Use `AbsolutePath.asURL` instead of creating a new URL from the path string

Sources/SourceControl/GitRepository.swift, Tests/SourceControlTests/GitRepositoryProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift
Show human-readable git errors
I noticed that when swiftpm cache is empty and there's a network issue, then `swift build` throws an error which is not helpful, something like this:
```
error: GitShellError(result: <AsyncProcessResult: exit: terminated(code: 128), output:
>)
```
where it does say "output" but doesn't actually include output or show any details about what dependency caused the error.
- `GitShellError` now conforms to CustomStringConvertible protocol, so that when it is thrown then it will print what was the git error
- `GitShelError` has now package access to allow catching it explicitly.
Errors now tell details of the failure: 
```
error: Git command 'git -C /Users/yy/Library/Caches/org.swift.swiftpm/repositories/postgres-kit-e4358808 config --get remote.origin.url' …
```
=> Show human-readable git errors

Sources/Workspace/InitPackage.swift
When using VS Code, this directory gets created, but generally isn't meant to be checked in, similar to Xcode' xcuserdata.
Added .vscode to the generated .gitignore for new packages.
When creating a new package, when an adopter uses VS Code, they won't have to add this entry into their .gitignore by hand.
=> Workspace/InitPackage: Add `.vscode` to `.gitignore`

Sources/CoreCommands/SwiftCommandState.swift
`the manifest file should *not* present` -> `the manifest file should *not* be present`
=> Fix comment typo in `SwiftCommandState.swift`

Sources/Workspace/Workspace+Manifests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Currently, when there‘s a syntax error in a package manifest, we don’t get any build settings from it in SourceKit-LSP and thus loose almost all semantic functionality. If we can’t parse the package manifest, fall back to providing build settings by assuming it has the current Swift tools version.
Fixes swiftlang/sourcekit-lsp#1704
rdar://136423767
=> Return compiler arguments for invalid package manifests

Sources/Commands/SwiftTestCommand.swift
This PR adds the given experimental command-line argument to `swift test` to allow writing attachments to a user-supplied directory when using Swift Testing. In the future, we will formally propose this flag as part of the attachments feature.
XCTest on Darwin would need separate changes to support this argument and they are beyond the scope of this PR. XCTest on non-Darwin platforms (corelibs-xctest) does not support attachments.
Resolves rdar://141225464.
=> Add `--experimental-attachments-path` to `swift test`.

Sources/PackageLoading/ManifestLoader+Validation.swift, Tests/PackageLoadingTests/TraitLoadingTests.swift
During the proposal review it was brought up that the rules around trait names wasn't inline with Swift identifiers. Neither was the implementation which was inline with the proposal.
This PR changes our validation logic to only allow valid Swift identifiers.
Only allows trait names that can be used as Swift identifiers.
=> [Traits] Only allow valid Swift identifiers

Fixtures/Miscellaneous/TestableAsyncExe/Package.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Utilities/bootstrap, Utilities/build-using-self, Utilities/helpers.py
Make changes to ensure success of the self-hosted macOS pipeline that executes using the nightly toolchain.
When enabling the nightly toolchain build, the CI build does not set SDKROOT environment variable on Darwin, which causes some tests to fail 
1.  Set SDKROOT in build-using-self when on Darwin. When using the nightly toolchain, the `SDKROOT` environment variable was not set.  Explicitely set this to the default xcode installation only when on Darwin.
2. Run the testTestsCanLinkAgainstAsyncExecutable only if it's executed on macOS 15 or never.
3. Add additional logging to troubleshoot the bootstap failure and convert to use python's logging module instead of print statements.
Verifies #8137
=> pipeline: changes to support nightly toolchain

Tests/CommandsTests/PackageCommandTests.swift
The issue to reenable the test is tracked by
https://github.com/swiftlang/swift-package-manager/issues/8180
=> Skip flakey PackageCommandTests.testCommandPluginDiagnostics test

CODEOWNERS
Although I don't have commit access, yet, I've been working on trying to get the self-hosted macOS pipeline to use the nightly toolchain.  Updating the `CODEOWNERS` file will hopefully allow me to trigger the macOS self-hosted nightly toolchain without depending/waiting on another developer to do it for me.
=> Update owners file

Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/TraitTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fixes some warnings in the tests around unused variables and string conversions.
=> Fixup some build warnings in tests

Sources/PackageModel/ToolsVersion.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Utilities/build-using-self
Update the `ToolsVersion` data structure to include the 6.1.0 release, and update some references to ToolsVersion.vNext and 999.0 to non-development releases.
References:
- https://github.com/swiftlang/swift-package-manager/pull/8139
- https://github.com/swiftlang/swift-package-manager/pull/8074
=> Tool version updates

Sources/Workspace/PackageContainer/RegistryPackageContainer.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Let's take the following `Package.swift`:
```swift
// swift-tools-version: 5.7
import PackageDescription
name: "Library",
.package(id: "AliSoftware.OHHTTPStubs", exact: "9.0.0")
]
)
```
You can find the `OHHTTPStubs` dependency at that version [here](https://github.com/AliSoftware/OHHTTPStubs/tree/e92b5a5746ef16add2a1424f1fc19529d9a75cde).
The dependency has two manifests:
- `Package.swift` with `swift-tools-version` at `4.0`
- `Package@swift-5.swift` with `swift-tools-version` at `5.0`
When resolving packages via the registry, SwiftPM should use the `Package@swift-5.swift`. However, instead SwiftPM fails with:
```
Running resolver because the following dependencies were added: 'AliSoftware.OHHTTPStubs' (AliSoftware.OHHTTPStubs)
Computing version for …
```
=> Fix registry resolution of major alternate package manifests 

Sources/Workspace/Workspace+Registry.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fix resolve failing when package from registry is referenced by name
When running `swift package --replace-scm-with-registry --default-registry-url {our-registry-url} resolve`, the command fails when depending on packages that reference their transitive dependencies by name.
I created a [demo](https://github.com/fortmarek/spm-registry-by-name-references) where you can reproduce the issue by running `swift package --replace-scm-with-registry --default-registry-url {our-registry-url} resolve`. You should see the following error:
```
error: 'cpisciotta.xcbeautify': unknown dependency 'Colorizer' in target 'XcbeautifyLib'; valid dependencies are: 'swift-argument-parser' (from 'https://github.com/apple/swift-argument-parser.git'), 'getGuaka.Colorizer', 'MaxDesiatov.XMLCoder'
error: …
```
=> Fix resolve failing when package from registry is referenced by name

Sources/Commands/Utilities/TestingSupport.swift, Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
This modifies the logic which sets the value of the `DYLD_FRAMEWORK_PATH` environment variable when launching test runners on Darwin when Xcode is installed: currently it includes the path to the platform's developer "Frameworks" directory, and this change adds the sibling "PrivateFrameworks" directory as well.
XCTest includes some private support frameworks, and these frameworks must be aligned with the public framework for testing to work correctly. This ensures that if the path to the (public) frameworks directory is specified, the aligned private frameworks directory is also included.
- Add `$PLATFORM/Developer/Library/PrivateFrameworks` to the `DYLD_FRAMEWORK_PATH` env var.
Resolves rdar://141564191
=> Include the path to the platform's PrivateFrameworks directory in DYLD_FRAMEWORK_PATH when launching test runners

Sources/Basics/SwiftVersion.swift
Update the branch to accurately reflect the version.
Need to accurately display the version
Reverted https://github.com/swiftlang/swift-package-manager/pull/8135 
N/A
=> version: set the version back to 6.1.0

Sources/Commands/Utilities/TestingSupport.swift, Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
- **Explanation**: This modifies the logic which sets the value of the `DYLD_FRAMEWORK_PATH` environment variable when launching test runners on Darwin when Xcode is installed: currently it includes the path to the platform's developer "Frameworks" directory, and this change adds the sibling "PrivateFrameworks" directory as well.
- **Scope**: Affects tests run on Darwin only, when Xcode is installed.
- **Issues**: n/a
- **Original PRs**: https://github.com/swiftlang/swift-package-manager/pull/8199
- **Risk**: Low. Including this runtime framework search path should have no effect when running tests for any supported version of Xcode.
- **Testing**: I validated this works as expected using a local build.
- **Reviewers**: @briancroom, @grynspan, @plemarquand, @jakepetroules 
Resolves …
=> [6.1] Include the path to the platform's PrivateFrameworks directory in DYLD_FRAMEWORK_PATH when launching test runners

Sources/Basics/SwiftVersion.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Disable development mode in the release 6.1 branch.
We should never release Swift Package Manager in development mode. So this disables dev mode and brings in the functionality of `999.0` over being introduced specific swift tool version (primarily in tests)
Modify `SwiftVersion` `isDevelopment` to `false` and update references to swift tool version `999.0` to  a specific version.
`swift test`
=> Disable development mode

Sources/Commands/SwiftRunCommand.swift
Use `closefrom(2)` instead of `close(2)` in a loop to reduce the window of race condition with other part of the process cloud be polling/processing the file descriptors. 
Currently, a loop is used to close all possible file descriptors prior to `execve(2)` being called. This has the side effect that file descriptors owned by different components of the same process is being closed unexpectedly, which cause issue #8197.
Use `closefrom(2)` instead of `close` in a loop to significantly reduce the window between closing the file descriptors and calling `execve(2)`, to minimize the impact.
In #8197, linking a debug build of `libdispatch` can randomly crash `swift-run`, due to dispatch catching that the file descriptors it works on no longer being valid, which causes an assertion and crash the …
=> use closefrom(2) on platforms supports it to reduce race condition window

Sources/Workspace/Workspace+Dependencies.swift
Retrieve resolved package versions in parallel to improve package resolve performance
When running `swift package resolve`, resolved package versions are retrieved sequentially. This is not a big problem when using source control resolution as in that case, the deep clones are [done in parallel](https://github.com/swiftlang/swift-package-manager/blob/0401a2ae55077cfd1f4c0acd43ae0a1a56ab21ef/Sources/Workspace/Workspace%2BDependencies.swift#L367) when SwiftPM tries to resolve the required versions.
However, when resolving packages using registry, the download of the source archive happens after the required version is resolved. That happens sequentially: https://github.com/swiftlang/swift-package-manager/blob/0401a2ae55077cfd1f4c0acd43ae0a1a56ab21ef/Sources/Workspace/Workspace%2BDependencies …
=> Retrieve resolved package versions in parallel

Sources/Workspace/Workspace+Dependencies.swift
Reverts swiftlang/swift-package-manager#8203
This is causing crashes in SwiftPM during the parallelized checkout. The checkouts update the workspace state and then save it. The workspace save data is not protected against multi-thread access while the save is walking the data which is causing the crash.
=> Revert "Retrieve resolved package versions in parallel"

Package.swift
Clean up the dependency list because 'DriverSupport' is not used by 'XCBuildSupport'.
=> Removed unused dependency 'DriverSupport' from 'XCBuildSupport'.

Tests/BasicsTests/SampleTests.swift
Add a canary swift testing tests to ensure we do not regress.
This test will be removed sometime after #8092, #8093 or #8100 are merged
=> Tests: Canary Swift Testing test

Tests/BuildTests/BuildPlanTests.swift
Add a test for https://github.com/swiftlang/swift-package-manager/issues/8055 that checks we can successfully generate a manifest for a target -> static product -> binary artifact dependency.
=> Add a test case for static products with a binary artifact dependency

Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/Workspace/ManagedPrebuilt.swift, Sources/Workspace/Workspace+Configuration.swift, Sources/Workspace/Workspace+Prebuilts.swift, Sources/Workspace/Workspace+State.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
Re-enable use of prebuilts for tests that depend on macro targets. These are guaranteed to be built for host as the macros are.
Add a hidden option to override the prebuilts download URL for swift-syntax for testing. Also added support for this to be a file URL.
Add support for using the ssh GitHub URL for swift-syntax, allowing multiple PackageReferences for prebuilts. Also elevated the PackageIdentity to the root structures that need it.
Fixed the build prebuilts script to generate into a versioned directory so we can support generating multiple versions at the same time.
=> Use prebuilts for macro tests. Add debug URL for swift-syntax.

Sources/Basics/CMakeLists.txt, Sources/Basics/FileSystem/FileSystem+Extensions.swift, Sources/QueryEngine/CacheKey.swift, Sources/QueryEngine/FileCacheRecord.swift, Sources/QueryEngine/Query.swift, Sources/QueryEngine/QueryEngine.swift, Sources/_AsyncFileSystem/CMakeLists.txt, Sources/_AsyncFileSystem/ReadableFileStream.swift
`SystemPackage` is only used as an internal implementation detail here. This package is not needed for the public API surface. Furthermore, as this dependency is a single use dependency, we are able to save some nominal space on the builds with this:
Pre:
SystemPackage.dll: 212992 bytes
_AsyncFileSystem.dll: 60416 bytes
Post:
SystemPackage.dll: 0 bytes (static)
_AsyncFileSystem.dll: 217600
This effectively shaves ~56K off the toolchain.
=> Basics,_AsyncFileSystem: internalise SystemPackage

Sources/PackageModel/Manifest/PackageDependencyDescription.swift, Sources/Workspace/Workspace+Registry.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fix registry package swizzling when package name casing differs
When swizzling dependencies when running `swift package --replace-scm-with-registry resolve`, package references that have different casing don't get swizzled.
You can find an example of this scenario in the [Firebase SDK](https://github.com/firebase/firebase-ios-sdk/blob/main/Package.swift) that boils down to:
```swift
import PackageDescription
name: "Firebase",
.package(
url: "https://github.com/google/promises.git", // lowercase
"2.4.0" ..< "3.0.0"
),
],
targets: [
.target(
name: "FirebaseCrashlytics",
.product(name: "FBLPromises", package: "Promises"), // uppercase
]
)
]
)
```
The `.product(name: "FBLPromises", package: "Promises")`should be swizzled to use the …
=> Fix registry package swizzling when package name casing differs

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildOperation.swift, Tests/BuildTests/PrepareForIndexTests.swift
Eliminate the special generatePrepareManifest and just reuse the real one and add a couple of checks for the target/product prepareForIndexing buildParameter instead. This then enables us to make sure we're doing a full build of the plugin tools so they can generate code to be properly indexed.
Addresses #8216 for openapi generator.
=> Fix prepare for indexing so plugin tools are properly built.

Fixtures/Miscellaneous/APIDiff/CIncludePath/Package.swift, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/include/CSample.h, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/include/config.h, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/vendorsrc/include/vendor.h, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/vendorsrc/src/vendor.c, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/Sample/Sample.swift, Sources/Build/BuildPlan/BuildPlan.swift, Tests/CommandsTests/APIDiffTests.swift
Fixes #8073: Update include paths for clang module in `diagnose-api-breaking-changes` command.
Swift package manager's command `diagnose-api-breaking-changes` is a wrapper on top of `swift-api-digester`. Purpose of `swift-api-digester` is to detect API incompatible changes between two revisions of code. `diagnose-api-breaking-changes` makes it more convenient to use with packages and does a few things under the hood:
- it copies git repo into temp dir and checks out its working dir to "baseline" commit
- it calls `swift-api-digester` to compare current package to the baseline commit
- it calls `swift-api-digester` with necessary build flags determined by toolchain, configuration and environment 
@PeterAdams-A reported in #8073 that `swift-api-digester` failed to build a baseline commit …
=> Add include dir from a clang module into the build args in `diagnose-api-breaking-changes` command.

Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/Workspace/ManagedPrebuilt.swift, Sources/Workspace/Workspace+Prebuilts.swift, Sources/Workspace/Workspace+State.swift, Sources/_InternalTestSupport/ManifestExtensions.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
Assume dependent products from prebuilts are being used.
=> Clean up warnings, fix handling of dep version changes

Sources/SourceKitLSPAPI/CMakeLists.txt
This is consumed by SourceKit-LSP, so export the library target to allow the library to be consumed properly to manage dependencies and flags.
=> SourceKitLSPAPI: export library as an interface

Sources/_AsyncFileSystem/ReadableFileStream.swift
This reduces the visibility of the import as it is only used in internal declarations. This cleans up a recently introduced warning.
=> _AsyncFileSystem: reduce visibility of import (NFCI)

Sources/Build/BuildManifest/LLBuildManifestBuilder.swift, Sources/Build/BuildOperation.swift, Tests/BuildTests/PrepareForIndexTests.swift
Back port of #8230 to release/6.1
Eliminate the special generatePrepareManifest and just reuse the real one and add a couple of checks for the target/product prepareForIndexing buildParameter instead. This then enables us to make sure we're doing a full build of the plugin tools so they can generate code to be properly indexed.
Addresses #8216 for openapi generator.
=> Fix prepare for indexing so plugin tools are properly built. (#8230)

Package.swift, Sources/Build/CMakeLists.txt, Sources/PackageGraph/CMakeLists.txt, Sources/SPMBuildCore/CMakeLists.txt, Sources/Workspace/CMakeLists.txt, Sources/XCBuildSupport/CMakeLists.txt
The `OrderedCollections` module has been more aggressively adopted in SPM. Update the dependencies to reflect this dependency.
=> build: add missing dependencies

Sources/PackageModel/Manifest/PackageDependencyDescription.swift, Sources/Workspace/Workspace+Registry.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Description: Fixes a case sensitivity issue when swizzling package names during a package resolution from a package registry.
Scope: Packages
Risk: Low
Testing: New test for this specific case
Issue: https://github.com/swiftlang/swift-package-manager/pull/8194
Author: @fortmarek
Reviewer: @plemarquand
=> [6.1] Fix registry package swizzling when package name casing differs

Fixtures/Miscellaneous/APIDiff/CIncludePath/Package.swift, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/include/CSample.h, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/include/config.h, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/vendorsrc/include/vendor.h, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/CSample/vendorsrc/src/vendor.c, Fixtures/Miscellaneous/APIDiff/CIncludePath/Sources/Sample/Sample.swift, Sources/Build/BuildPlan/BuildPlan.swift, Tests/CommandsTests/APIDiffTests.swift
- Description: Fix build error for `diagnose-api-breaking-changes` command when C code is in non-standard location
- Scope: Package
- Risk: Low
- Testing: New test for this specific scenario. However, the test suite is deactivated in 6.1 unless [#8196](https://github.com/swiftlang/swift-package-manager/pull/8196) is cherry-picked too.
- Issue: https://github.com/swiftlang/swift-package-manager/issues/8073
- Cherry-picked from: https://github.com/swiftlang/swift-package-manager/pull/8209
- Author: @yyvch 
- Reviewers: @plemarquand @jakepetroules
=> [6.1] Add include dir from a clang module into the build args.

Utilities/bootstrap
Yams is no longer a dependency for swift-driver, remove the dependency building to reduce the build times.
=> Utilities: remove Yams from the bootstrap script

Sources/Basics/Concurrency/SendableBox.swift, Sources/Workspace/Workspace+Prebuilts.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
I was using my fork of swift-syntax to host my test artifacts. Switch that to a more realistic yet not yet approved one.
Also cuts down how often we reach out to fetch a manifest. We instead create an empty one in the scratch directory if it's not found on the download site. And we always now check the scratch directory first.
=> Set candidate URL for prebuilts download.

Sources/Commands/SwiftRunCommand.swift
Suspend all other threads first before closing file descriptors and exec.
See #8197 #8180, `swift run` can crash due to race condition between libdispatch controlled threads. To properly mitigate this, suspend all other threads (including those managed by libdispatch) before closing the file descriptors.
Call `pthread_suspend_all_np` before closing file descriptors, this api is not portable but exists on both FreeBSD and OpenBSD. However, since the Glibc overlay for OpenBSD does not include <pthread_np.h>, we guard this and make it available for FreeBSD only.
=> [FreeBSD] suspend all other threads before closing file descriptors

Tests/CommandsTests/TestCommandTests.swift
A clarifying comment referred to a non-existent file `runner.sh`, it should've been `echo.sh`.
=> NFC: Fix comment typo in `TestCommandTests.swift`

Sources/Workspace/Workspace+Prebuilts.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift
Fix layout of artifacts in build prebuilts script so that it replicates what we hope on the downloads site. Facilitates local builds the using that for testing.
Also a fix in the manifest downloader to remove the old version of the manifest before copying the new one over.
=> Fix layout of artifacts in build prebuilts script.

Tests/BasicsTests/SampleTests.swift
Reverts swiftlang/swift-package-manager#8222
Reverting this as it appears to be causing a toolchain build failures.
=> Revert "Tests: Canary Swift Testing test"

Sources/PackageMetadata/PackageMetadata.swift, Sources/PackageRegistry/RegistryClient.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
In [4.1 List Package
Releases](https://github.com/swiftlang/swift-package-manager/blob/main/Documentation/PackageRegistry/Registry.md#41-list-package-releases) it is stated that a server may respond with a `Link` header that contains a pointer to a subsequent page of results. SwiftPM is not checking for the `next` link in the `Link` header and so if a registry returns paginated results, only the first page of versions is searched when resolving. This would result in a "version not found" error when in reality the version is present in a subsequent page of results.
Respect the `next` link in the `Link` header by loading the next page of results and building up a list of versions, continuing until there is no `next` link present in the `Link` header of the last result.
Registry servers that …
=> [6.1] Handle paginated registry metadata responses (#8219)

Sources/Workspace/Workspace+Prebuilts.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
Made discovery of the Linux distro reusable for the build-prebuilts script. Changed it to use arch and os conditions instead of the host toolchain.
Added support for Ubuntu noble, Fedora and Debian.
Removed the deletion of the stage directory so we can share it across docker invocations for each distro. Fixed the Modules directory name which wasn't working on case sensitive file systems.
=> Enable building prebuilts on linux hosts without docker.

Sources/Basics/Archiver/ZipArchiver.swift, Tests/BasicsTests/Archiver/ZipArchiverTests.swift
This PR fixes #8248, by adding the `y` flag to the `zip` command that is executed when archiving a package's sources for publication to a registry on a non-Windows OS.
Without this change, packages which contain symlinks in their sources will produce invalid and potentially non-buildable archives when publishing to a registry, since any symlinks are currently transformed into duplicate files during the archive creation, instead of being preserved.  
I've added the following flag to the `zip` call:
>   -y   store symbolic links as the link instead of the referenced file
I've additionally modified the associated `testCompress()` test case, adding logic to ensure that symlinks are preserved correctly. 
With this change, the resulting zipfile that is uploaded to a registry will contain …
=> Fix: preserve symlinks in ZipArchive compress function

Fixtures/Miscellaneous/TestMultipleFailureSwiftTesting/Package.swift, Fixtures/Miscellaneous/TestMultipleFailureSwiftTesting/Tests/TestMultipleFailureSwiftTestingTests/TestMultipleFailureSwiftTestingTests.swift, Fixtures/Miscellaneous/TestMultipleFailureXCTest/Package.swift, Fixtures/Miscellaneous/TestMultipleFailureXCTest/Tests/TestMultipleFailureXCTestTests/TestMultipleFailureXCTestTests.swift, Fixtures/Miscellaneous/TestSingleFailureSwiftTesting/Package.swift, Fixtures/Miscellaneous/TestSingleFailureSwiftTesting/Tests/TestFailuresSwiftTestingTests/TestFailuresSwiftTestingTests.swift, Fixtures/Miscellaneous/TestSingleFailureXCTest/Package.swift, Fixtures/Miscellaneous/TestSingleFailureXCTest/Tests/TestFailuresTests/TestFailuresTests.swift, Sources/Commands/SwiftTestCommand.swift, Sources/_InternalTestSupport/SwiftPMProduct.swift, Tests/CommandsTests/TestCommandTests.swift
Modify the XCTest xUnit failure message to display the test result.
The generated xUnit XML file is not helpful when tests fail as it contains the message "failure", which is redundant with the test results.
Update the XML output to display the result output instead of static "failure" message.  The failure message may contain irrelevant output, but it's better than the current message of `failure`.
```
swift test 
```
Requires: https://github.com/swiftlang/swift/pull/78300
=> Update xUnit to display output on failures

Sources/CoreCommands/Options.swift
_2/10/25: Updated example output to match changes._
Adds titles to the option groups that comprise the `GlobalOptions` struct, for better help screen formatting.
The current help screen includes a long list of flags and options, with no categorization, making it hard for users to understand what kinds of options are available.
This change adds titles to all the `@OptionGroup` declarations inside the global options struct, which results in each group being labeled in the help screens for `swift package`, `swift run`, etc.
The new, categorized screen for `swift run` is below.
> [!NOTE]  
> These are just initial guesses at what the appropriate names should be – reviewers, please discuss/revise what's here!
```
OVERVIEW: Build and run an executable product
SEE ALSO: swift build, swift …
```
=> Add titles to global option groups for better help screens

Sources/Commands/PackageCommands/AddDependency.swift, Sources/PackageModelSyntax/AddPackageDependency.swift, Sources/PackageModelSyntax/AddTarget.swift, Sources/PackageModelSyntax/PackageDependency+Syntax.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
Enable passing relative path into `swift package add-dependency`
Currently only `AbsolutePath`s are supported with `--type path` flag
```bash
swift package add-dependency /packagePath --type path
```
There is a need to support `RelativePath` because it's not uncommon to have a package structure inside of an xcodeproj as shown below.
```bash
LocalPackages
├── ChildPackage
│   ├── .gitignore
│   ├── .swiftpm
│   ├── Package.swift
│   ├── Sources
│   └── Tests
└── ParentPackage
   ├── .build
   ├── .gitignore
   ├── .swiftpm
   ├── Package.swift
   ├── Sources
   └── Tests
```
If we want to open `ParentPackage` by itself, it will not be able to resolve that package.
This pr allows for the user to add a package with a `RelativePath` path via the `swift package add-dependency --type path` …
=> Allow relative path with `swift package add-dependency` command

Utilities/bootstrap, Utilities/helpers.py
There have been cases where CI build failurse did not have sufficient logs when it failed during a Swift PM build/test. Augment the Swift PM build/test by enabling verbosity.  Update `Utilities/bootstrap` to call swift pm executable targets using `--very-verbose` instead of `--versobe` when the tool is invoked with `--verbose`.
Requires https://github.com/swiftlang/swift/pull/79330
=> Add additional information

Utilities/bootstrap
Add new swift-crypto on asn1 to the bootstrap script
The newest version of swift-crypto has a dependency on swift-asn1. Without providing the directory the CMakeLists.txt of swift-crypto will attempt to vendor a specific version of that library that may not match what is in the update-checkout version using in Swift CI, which can lead to mismatched symbols during linking.
This fix adds the swift-asn1 dependency to swift-crypto by adding the directory for swift-asn1 to cmake when building swift-crypto.
After the change the new dependency from swift-crypto should be ready for when the new version of the lib is adopted.
=> Add new swift-crypto on asn1 to the bootstrap script

Sources/Commands/Utilities/PluginDelegate.swift, Sources/Commands/Utilities/SymbolGraphExtract.swift, Sources/PackagePlugin/PackageManagerProxy.swift, Sources/PackagePlugin/PluginMessages.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift
Currently the symbol graph generator defaults to "public" minimum access level even if the user tries to initialize the options with "package" this is because the internal enums representing access level don't have a notion of `package` access control.
Currently it is not possible to generate documentation only for `package` and `public` symbols. This changes that
Adds `package` values to enums representing access control along the symbol graph generation code path.
When invoking [swift-docc-plugin](https://github.com/apple/swift-docc-plugin) with `--symbol-graph-minimum-access-level package` the resulting documentation contains `public` and `package` access controlled symbols.
=> Add `package` access level to access level enums

Fixtures/Miscellaneous/CheckTestLibraryEnvironmentVariable/Tests/CheckTestLibraryEnvironmentVariableTests/CheckTestLibraryEnvironmentVariableTests.swift, Sources/Commands/Utilities/TestingSupport.swift, Sources/PackageModel/UserToolchain.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/TestCommandTests.swift
This was added so that test binaries could find swift-testing, but we should insert those paths into `DYLD_*_PATH` rather than add to the rpath. The current behavior adds an absolute rpath to *all* binaries, not even just test binaries.
=> Do not add rpath to swift-testing for CLT or custom toolchains

Tests/FunctionalTests/MiscellaneousTests.swift
This test seems to be broken with the latest CI infrastructure changes.
Skip it until we can figure out why.
=> Disable the testLTO test in MiscellaneousTests

Sources/XCBuildSupport/XcodeBuildSystem.swift
Some Xcode installation no longer have `xcbuild` binary, and instead contain a `swbuild`.  Update the path to look for `swbuild` first, and then fall back to `xcbuild`.
=> Update path to support swbuild if available

Sources/Build/LLBuildProgressTracker.swift
- **Explanation**: `self.taskTracker.onTaskProgressUpdateText` captured `self` strongly, creating a reference cycle in `LLBuildProgressTracker`, which caused it to never get deallocated.
- **Scope**: Manifested as a memory leak in SourceKit-LSP
- **Issue**: n/a
- **Original PR**: https://github.com/swiftlang/swift-package-manager/pull/8305
- **Risk**: Low, just captures a delegate weakly
- **Testing**: Verified that this fixes the memory leak we saw
- **Reviewer**: @MaxDesiatov
=> [6.1] Fix retain cycle in `LLBuildProgressTracker`

Sources/CoreCommands/SwiftCommandState.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SPMBuildCore/Triple+Extensions.swift, Sources/swift-bootstrap/main.swift
There are a few places that check the BuildSystemProvider.Kind is Xcode to determine the build directory structure.  With the upcoming Swift Build integration, which uses the "Xcode path" structure, we would need to update all instances to check the two build system provider kinds.
Add an extension on the BuildSystemProvider.Kind that create a boolean variable `useXcodeBuildEngine`, which determines whether the build system should use the xcode path structure or not.  In addition, update the code that requires a  "isXcodeBuildSystemEnabled" to return this build system provider variable.
This will hopefully help address #8272 when #8271 is merged and added `case .swiftbuild: return true` to the `useXcodeBuildEngine `
Fixes #8272
rdar://144023142
=> build: define build path structure in BuildSystemProvider.Kind

Sources/PackageModel/InstalledSwiftPMConfiguration.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
Fixed SwiftPM macro template manifest depending on new swift syntax release
Use the latest version of swift-syntax package in SwiftPM macro templates
changed the default version to 601 and edited a test case to reflect change
If user does not have a toolchain with a config.json, the default version of swift-syntax is 601
=> Fixed update of swift-syntax package version in swiftpm macro templates

Sources/Build/LLBuildProgressTracker.swift
`self.taskTracker.onTaskProgressUpdateText` captured `self` strongly, creating a reference cycle in `LLBuildProgressTracker`, which caused it to never get deallocated.
=> Fix retain cycle in `LLBuildProgressTracker`

Sources/XCBuildSupport/PIFBuilder.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
Fix a bug where builds using --build-system xcode would fail if a target was configured to use a language mode which was not also specified at the top level of the package manifest
=> Align --build-system xcode language mode validation with --build-system native

Sources/Basics/Cancellator.swift, Sources/Basics/HTTPClient/HTTPClient.swift, Sources/Basics/HTTPClient/LegacyHTTPClient.swift, Sources/PackageRegistry/ChecksumTOFU.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/PackageRegistry/RegistryDownloadsManager.swift, Sources/PackageRegistry/SignatureValidation.swift, Sources/_InternalTestSupport/MockRegistry.swift, Tests/BasicsTests/CancellatorTests.swift, Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/PackageRegistryTests/SignatureValidationTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Deprecate the synchronous methods in RegistryClient and move the logic from then sync versions in to the async versions. This async-ifys the previously callback based methods, flattening them out.
The synchronous versions of these methods will now warn when they're used. After some time they can be removed completely.
=> Deprecate sync methods in RegistryClient

Sources/PackageDescription/LanguageStandardSettings.swift
update `CLanguageStandard` description for `c89`
update typo in `CLanguageStandard` description.
- Update description for `c89` standard to use correct year, 1989, instead of 1990.
- Documentation is improved!
=> update CLanguageStandard c89 description

Sources/PackageGraph/ModulesGraph+Loading.swift, Tests/PackageGraphTests/ModulesGraphTests.swift
Correct "Did you mean XYZ" messages when a dependency is not found.
I found that "Did you mean XYZ" messages quite often aren't helpful. Specifically, scenarios which I found very frustrating:
*Scenario 1*:
- I have a package MylibKit, and I forgot to declare a product there. I have a module Awesomeness there.
- I have a package NeatPak and I want to use Awesomeness there. I add package dependency to MylibKit and a product dependency `.product(name="Awesomeness", package="MylibKit")`
- SwiftPM errors out and adds `Did you mean '.product(name="Awesomeness", package="MylibKit")'`. I triple-checked what it suggested vs what I had, and after some staring, I checked MylibKit and indeed, it was missing a product definition. It was pretty frustrating that it errored out with suggestion which …
=> Correct "Did you mean XYZ" messages when a dependency is not found.

Utilities/config.json
Updates the config.json to swift-syntax 601.
=> Found another place where we specify the swift-syntax version.

Sources/XCBuildSupport/XcodeBuildSystem.swift
Update path to support swbuild if available (#8306)
Some Xcode installation no longer have `xcbuild` binary, and instead
contain a `swbuild`. Update the path to look for `swbuild` first, and
then fall back to `xcbuild`.
=> Cherry pick swbuild support to 6.1

Sources/Basics/Concurrency/AsyncProcess.swift, Sources/Basics/FileSystem/AbsolutePath.swift, Sources/Basics/FileSystem/NativePathExtensions.swift, Sources/Basics/Netrc.swift, Sources/Basics/Sandbox.swift, Sources/Basics/Serialization/SerializedJSON.swift, Sources/Commands/Utilities/DOTManifestSerializer.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageLoading/ModuleMapGenerator.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/SourceControl/GitRepository.swift, Sources/_InternalTestSupport/misc.swift
Prefer to use `String.replacing(_:with:)` instead of the `NSString` operations for the strings.  This should avoid an unnecessary use of Foundation API and a dispatch to the `NSString` API.
=> Remove use of `NSString.replacingOccurrences(of:with:)`

Sources/Basics/FileSystem/FileSystem+Extensions.swift, Sources/PackageRegistry/RegistryDownloadsManager.swift, Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
Deprecate the synchronous methods in RegistryDownloadsManager and move the logic from the existing sync methods to the async methods.
The synchronous methods in RegistryDownloadsManager will now warn when used. After some time they can be removed completely.
This patch follows the same refactoring conventions as https://github.com/swiftlang/swift-package-manager/pull/8263
=> Deprecate sync methods in RegistryDownloadsManager

Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
To facilitate https://github.com/swiftlang/sourcekit-lsp/pull/2017.
=> Add a SourceKit-LSP API to get the output paths of a clang target

Fixtures/Traits/DisablingEmptyDefaultsExample/Package.swift, Fixtures/Traits/DisablingEmptyDefaultsExample/Sources/DisablingEmptyDefaultsExample/Example.swift, Fixtures/Traits/Package11/Package.swift, Fixtures/Traits/Package11/Sources/Package11Library1/Library.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/_InternalTestSupport/ManifestExtensions.swift, Sources/_InternalTestSupport/MockPackage.swift, Tests/FunctionalTests/TraitTests.swift
Traits are a great way for package authors to offer customization of the functionality they provide. However, moving existing API behind a trait is considered an API breaking change since packages that depend on them might have disabled all default traits. This makes it almost impossible for existing packages to adopt traits for existing code.
This PR disallows disabling the default traits for packages with no traits at all. This allows package authors to move existing API behind traits once since no consumer can disable the default traits before.
With this change we create a migration path for existing packages to traits without them breaking their APIs.
=> [Traits] Disallow disabling default traits of a package without traits

Utilities/bootstrap, Utilities/build-using-self, Utilities/helpers.py
Update the bootstrap and helpers script to add verbose logging to help troubleshoot the code path taken.
Also, update the build-using-self to add command line option to enable xctest/swift-testing tests.
=> Improve debug logging

CONTRIBUTING.md
While we recommend running SwiftFormat, the contribution guidelines should also clarify that formatting changes should be minimized in a given PR to make PR diffs smaller and more readable.
=> Clarify formatting changes in `CONTRIBUTING.md`

Sources/PackageRegistry/RegistryDownloadsManager.swift
This restores the ability to build SwiftPM using a Swift 6.0 compiler.
=> Remove trailing comma in RegistryDownloadsManager.swift

Documentation/Design/EvolutionIdeas.md, Documentation/Usage.md
I periodically run a broken link checker over swiftlang repositories. There were a few links pointing to outdated locations in swift-package-manager.
=> Fix some broken links in Documentation

Sources/PackageRegistry/RegistryDownloadsManager.swift
Fix build error on `main` branch.
I was debugging https://github.com/swiftlang/swift-package-manager/issues/8341 and noticed that I could not build `swift-package-manager` on the `main` branch.
Simple build error fix.
`main` now builds correctly.
=> Fix Swift 6.0 trailing comma compatibility

Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/swift-bootstrap/main.swift, Utilities/bootstrap
Stop setting SWIFTPM_NO_SWBUILD_DEPENDENCY in the bootstrap script - we've made changes to Swift Build which should allow it to be bootstrapped in these environments (it's still not part of swift-bootstrap itself though).
=> Include Swift Build support in second stage bootstrap builds

Sources/Commands/PackageCommands/Init.swift, Sources/Commands/Snippets/Colorful.swift, Sources/CoreCommands/Options.swift, Sources/PackageRegistryCommand/PackageRegistryCommand+Publish.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/misc.swift, Sources/swift-bootstrap/main.swift, Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift, Tests/PackageGraphTests/PubGrubTests.swift
Several extensions to conform to common Swift protocols were unnecessarily marked as `@retroactive`, causing compiler warnings. The `@retroactive` annotation is only necessary when the type being extended is defined outside the package.
=> Remove unnecessary `@retroactive` conformances

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
https://github.com/swiftlang/swift-package-manager/pull/8366 is a revert, but it reverted back to a point before there was an outer `withService` block wrapping the code. As a result a `self` is missing on `buildParameters`, causing a build failure.
=> Add missing `self` in SwiftBuildSystem

Package.swift, Sources/AppleProductTypes/Product.swift, Sources/PackageDescription/PackageDescriptionSerialization.swift, Sources/PackageDescription/PackageDescriptionSerializationConversion.swift, Sources/PackageDescription/Product.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageModel/Manifest/ProductDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Sources/PackagePlugin/Context.swift, Sources/PackagePlugin/Errors.swift, Sources/PackagePlugin/PackageModel.swift, Sources/PackagePlugin/Plugin.swift, Sources/PackagePlugin/PluginContextDeserializer.swift, Sources/PackagePlugin/PluginMessages.swift, Sources/SPMBuildCore/CMakeLists.txt, Sources/SPMBuildCore/Plugins/PluginContextSerializer.swift, Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Sources/SPMBuildCore/XcodeProjectRepresentation.swift, Sources/SwiftBuildSupport/PIF.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/XCBuildSupport/PIF.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/BasicsTests/CancellatorTests.swift, Tests/BasicsTests/PhonyTest.swift, Tests/PackageLoadingTests/PDAppleProductLoadingTests.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
A previous PR #8271 created an alternate SwiftPM build system called Swift Build. This change adds necessary infrastructure for updates to the PIF Builder using this build system.
=> Add infrastructure for updates to new Swift Build build system.

Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift
This is a followup to #8333 based on feedback from there.
=> Followup to increasing swift-build test coverage

Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/swift-bootstrap/main.swift, Utilities/bootstrap
This reverts commit 6a2e45f2a625cb9920285f77c638c342b837e382.
- Stop setting SWIFTPM_NO_SWBUILD_DEPENDENCY in the bootstrap script
- Copy resource bundles required by Swift Build into the toolchain when installing
There is one additional fix to the bootstrap script to allow overwriting directories when installing, to fix the incremental buildbot CI configuration.
=> Reapply "Include Swift Build support in second stage bootstrap builds"

Sources/Commands/SwiftRunCommand.swift, Sources/PackageModel/Toolchain.swift
Swift Build doesn't set the rpath of the generated executable to point at the toolchains swift standard library. We shouldn't be hardcoding those paths anyway since that restricts deployment options. Instead we point the LD_LIBRARY_PATH at swift run time to pick them up.
=> Add toolchain swift stdlib to env when swift run.

Sources/SwiftBuildSupport/PIFBuilder.swift, Tests/PackageRegistryTests/RegistryClientTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
Handled case where SwiftBuild is run on a freeBSD OS.
Currently, when using the new build system, you come across the following fatal error when building on a freeBSD OS:
Fatal error: Unhandled platform condition: Platform (name: "free bsd", oldestSupportedVersion: PackageModel.PlatformVersion(version: 0.0.0))
All I have done is, similar to Sources/XCBuildSupport/PIFBuilder, I added the case and handled it just like XCBuild's PIFBuilder does.
After changes, no more fatal error occurs and building proceeds as it should.
=> Fix unhandled platform condition w/ `freeBSDFilters` for `PIFBuilder` 

Package.swift
Update the git url of `swift-llbuild` and `swift-tools-support-core` so they point to the swiftlang github orginization.
=> Fix dependency conflict warnings

Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/RunCommandTests.swift
Now that `swift run` is working with the swiftbuild build system enable more tests that require that functionality.
=> Add more swiftbuild tests for functions that require swift run

Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SourceKitLSPAPI/PluginTargetBuildDescription.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
We need the mapping from source file to output file in SourceKit-LSP, so the old approach of returning all output paths in a separate property does not work. Return them in a single property instead.
This will be used in SourceKit-LSP by https://github.com/swiftlang/sourcekit-lsp/pull/2038.
=> Include the output paths for clang files in the `sources` property of a `BuildDescription`

IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
This section of the test will compile on Windows, but it doesn't succeed with Windows. Do an OS condition on there to avoid failures when tests are run with Windows.
=> Avoid testing library package with swiftbuild build system on Windows

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
The default linker for Windows in swift-build is now lld-link so this is no longer needed.
=> Remove ALTERNATE_LINKER build setting when building for Windows

Sources/swiftpm-testing-helper/Entrypoint.swift
For precedent see https://github.com/swiftlang/swift-build/blob/1d88f6d4dedc780d0399c4434d8fe51b03037818/Sources/SWBUtil/Library.swift#L41-L46
=> Fixes for platforms that do not have RTLD_FIRST (e.g., Android)

Package.swift, Sources/Basics/Concurrency/ConcurrencyHelpers.swift, Sources/Basics/SendableTimeInterval.swift, Sources/Commands/PackageCommands/AddDependency.swift, Sources/QueryEngine/QueryEngine.swift, Sources/_AsyncFileSystem/MockFileSystem.swift, Sources/_AsyncFileSystem/OpenWritableFile.swift, Sources/_AsyncFileSystem/ReadableFileStream.swift, Sources/_InternalTestSupport/misc.swift
- Remove now-redundant Sendable conformances
- Remove unused variables
- Fix a few missed unnecessary `@retroactive` conformances
- Use swiftlang/swift-llbuild.git instead of apple/swift-llbuild.git
=> Fixup several classes of warnings

Sources/Commands/SwiftRunCommand.swift, Sources/PackageModel/Toolchain.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/RunCommandTests.swift
Revert https://github.com/swiftlang/swift-package-manager/pull/8364 (and https://github.com/swiftlang/swift-package-manager/pull/8375)
This is causing a runtime dynamic linking error in swift-syntax PR testing:
https://ci.swift.org/job/swift-syntax-PR-Linux/4674/console
```
/home/build-user/build/buildbot_incremental/toolchain-linux-x86_64/usr/bin/swift: symbol lookup error: /home/build-user/build/buildbot_incremental/earlyswiftdriver-linux-x86_64/release/dependencies/llbuild/lib/libllbuildSwift.so: undefined symbol: $sSayxG10Foundation15ContiguousBytesABs5UInt8VRszlWP
```
=> Revert "Add toolchain swift stdlib to env when swift run."

Package.swift
This restores the ability to build SwiftPM using a Swift 6.0 compiler.
=> Remove trailing comma

Package.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift
The native build system will output the time it took building. This can be
useful for ad-hoc measurement of the time. Add the same kind of measurement
for build times of the swiftbuild build system.
=> Add build times to swiftbuild build system

Sources/Commands/PackageCommands/Init.swift, Sources/CoreCommands/SwiftCommandState.swift, Tests/BuildTests/PrepareForIndexTests.swift, Tests/CommandsTests/SwiftCommandStateTests.swift
Running `swift package init --package-path <dir-does-not-exists>` results in an error when SwiftPM attempts to change directories in to the directory that doesn't exist.
It is rare that a user wants to do a `swift package init` in a folder that already has content. A typical pattern is to `mkdir mypackage && cd my package && swift package init`. SwiftPM already has a `--package-path` flag indicating the package folder that the command should operate on, but attempting to use this to create a folder that doesn't exist during `swift package init` results in an error when SwiftPM attempts to chdir to the --package-path that doesn't exist.
Add a new boolean to the `_SwiftCommand` protocol that lets commands opt in to creating the directory at `--package-path` if it doesn't exist. Opt in …
=> Allow creation of non-existent directory during `swift package init`

Sources/PackageDescription/BuildSettings.swift, Sources/PackageLoading/ManifestJSONParser.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift, Sources/PackageModel/ManifestSourceGeneration.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
Add a `defaultIsolation` static method on `SwiftSetting` to allow specifying default actor isolation within a module.
This is part of https://forums.swift.org/t/pitch-control-default-actor-isolation-inference/77482. Please leave feedback on the API shape in the pitch thread.
I added a `defaultIsolation` case to `TargetBuildSettingDescription` and a corresponding static method to `SwiftSetting`.
Programmers will be allowed to set `defaultIsolation` per target in a package manifest, e.g.:
```swift
swiftSettings: [
.enableExperimentalFeature("StrictConcurrency"),
.defaultIsolation(MainActor.self),
]
```
=> Add a `defaultIsolation` static method on `SwiftSetting`.

IntegrationTests/Sources/IntegrationTestSupport/SkippedTestSupport.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift
In some testing environments, network access is limited not allowing for hosts to access the public internet.  Add a testing condition trait that can be used to determine if the test has unrestricted network access.
Environments that have this constraint can set `SWIFTCI_RESTRICTED_NETWORK_ACCESS=1` to affect this condition.
=> Add testing trait to indicate a CI environment that has restricted network access

Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageModel/Manifest/Manifest.swift, Tests/PackageModelTests/ManifestTests.swift
Fixes #8398 
Used package dependencies of a manifest were considered trait-guarded if a target dependency in the manifest:
1. used a product from said package and
2. was trait-guarded
regardless as to whether the same package dependency was used elsewhere (whether in the same target or another in the same manifest) and was not guarded by traits.
This change ensures that this is considered when doing the calculations for package dependencies that should be omitted if *every* target dependency that uses said package dependency is guarded.
=> [Traits] Fix traits omitting used package dependencies

Sources/PackageGraph/Resolution/ResolvedModule.swift, Sources/SwiftBuildSupport/BuildSystem.swift, Sources/SwiftBuildSupport/CMakeLists.txt, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Plugins.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder.swift
Introduces the new PIF builder for packages in `SwiftBuildSupport`.
This continues the work started by [PR 8271](https://github.com/swiftlang/swift-package-manager/pull/8271), introducing now our new *PIF builder* for packages. As expected, this will happen in the new `SwiftBuildSupport` target, introduced to support the just released **Swift Build** project. 
This 1st PR *only* includes the new code in the corresponding `SwiftBuildSupport/PIFPackageBuilder*.swift` source files. The code isn't actually being used (or unit tested) just yet.
The code still uses the older `SWBProjectModel.PIF` API to build the PIF data model. In an upcoming PR, I will be migrating this over to the newer `SwiftBuild.ProjectModel` API, and then finally replacing the original code to actually use the PIF …
=> Introduces the new PIF builder for SwiftBuild

Sources/PackagePlugin/Context.swift
Setting `path` directly in the initializer of PluginContext.Tool triggers a deprecation warning, because `path` is marked as deprecated. Set a private field, and have the deprecated public field use a getter to access it. This resolves the warning.
=> Fixup deprecation warning in PluginContext.Tool initializer

Tests/CommandsTests/BuildCommandTests.swift
We have to ensure LD_LIBRARY_PATH is set correctly on linux, until then, skip a test
=> Test: disable a SwiftBuild test on linux

Sources/Commands/PackageCommands/AddTarget.swift, Sources/PackageModelSyntax/AddTarget.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
Currently running `swift package init --type executable` in a folder called `Example` creates a project with the following structure:
```
./Example/Sources
./Example/Sources/main.swift
./Example/Package.swift
```
Following this up with a `swift package add-target Foo` produces a package that no longer builds. It now has the structure:
```
./Example/Sources
./Example/Sources/main.swift
./Example/Sources/Foo/Foo.swift
./Example/Package.swift
```
Packages with multiple targets cannot have code directly in `./Sources`, and the user gets the error:
`Source files for target Example should be located under 'Sources/Example'`
To work around this in the AddTarget command we can check if a package is structured as a single target package with sources directly in `./Sources` and move these files …
=> Move files when using `package add-target` on single target package

Documentation/Usage.md
`Avoiding specifying` -> `Avoid specifying`
Also reordered words in this somewhat convoluted sentence. "provided by the library in the `module.modulemap`" could've been read as if the library provides something in such modulemap file. But in fact, "in the `module.modulemap`" is related to the first part of the sentence. Moving it there makes the sentence less ambiguous.
=> Fix typo, refine wording in `Usage.md`

Package.swift
The SwiftBuild project has a dependency on Swift Driver, which has a dependency on Swift Tools Support Core (STSC).  Swift Package Manager (SwiftPM) executable targets also have a dependency on STSC.
Sever SwiftPM package depenedency on STSC if the
`SWIFTPM_SWBUILD_FRAMEWORK` environment variable is set so we can indirectly pull the STCS dependency on the dynamic library that will be pulled in via SwiftDriver.
=> Sever the package dependency if using SwiftBuild Framework

Sources/PackagePlugin/Plugin.swift, Utilities/bootstrap
Removing the definition of `_GNU_SOURCE` is no longer needed since swiftlang/swift-tools-support-core#500 made sure the right `strerror_r()` is used, and `dlerror()` has to be unwrapped because of its `_Nullable` annotation.
=> Android: remove build flags that are no longer needed and force unwrap dlerror()

Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Tests/BuildTests/PluginInvocationTests.swift
Somewhere along the way earling in the 6.1 branch changes were made to how the prebuild commands did their check to make sure the executable invoked in the command existed in the scratch dir.
It had always used a trick that kept track of whether a tool was a vendored binaryTarget or built. And only succeed if it was vendored. That information was lost in the restructuring.
This change stores whether a tool comes from a executable target (built tool) or a binary target (vended) and properly checks to make sure the tool is vended.
This was detected when the SwiftLint prebuild command target was failing when a user upgraded to 6.1. This change will need to be cherry picked back to the 6.1 branch for the next point release.
=> Fix prebuild commands

Sources/Workspace/InitPackage.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/WorkspaceTests/InitTests.swift, Tests/WorkspaceTests/WorkspaceStateTests.swift
Since `@main` is the general purpose way of marking the entry point to executables, use it over top level code when generating an executable template.
Update the template output when the specified `--type` is executable.
The template is now:
```swift
@main
struct MyProject {
static func main() {
print("Hello, world!")
}
}
```
This patch reverts https://github.com/swiftlang/swift-package-manager/pull/6197 and partially reverts https://github.com/swiftlang/swift-package-manager/pull/6144
=> Use `@main` instead of top level code when initializing executable

Utilities/bootstrap
PR #8373 (commit ID: 0193d5fb8) updated a `shutil.copytree(...)` command to pass in the `dirs_exists_ok=True` argument.  However, Python added support for the `dirs_exists_ok` argument to `shutil.copytree` in 3.8.
Update the function call to inspect the python version, and only add the argument if the script is running in a Python version equal, or higher than 3.8.
- Python 3.7 documentation: https://docs.python.org/3.7/library/shutil.html#shutil.copytree
- Python 3.8 documentation: https://docs.python.org/3.8/library/shutil.html#shutil.copytree
rdar://147297864
=> Bootstrap: update logic to support pre-and post python 3.8

Sources/swift-build-prebuilts/BuildPrebuilts.swift
Adds the latest version. Had to change how the package manifest for it gets edited since swift package add-product doesn't work anymore since the format of the file has changed.
This doesn't get distributed in the toolchain. It's only to generate the prebuilts for swift-syntax.
=> Add swift-syntax 601.0.1 to the prebuilts generator.

Sources/SwiftBuildSupport/PIF.swift
Some of the `SwiftBuildSupport/PIFBuilder.swift` encoding/decoding code was using unsafe string keys. This replaces with proper typesafe keys.
This part of the ground work to support the new PIF builder in `SwiftBuildSupport` (i.e., rdar://147527170).
When conforming to `Codable`, replace string keys with `enum` based keys instead.
The resulting code is safer and easier to understand.
Tracked by rdar://148546582.
=> Minor Codable conformance improvements in SwiftBuildSupport

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Plugins.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder.swift
The goal is to adopt the new `SwiftBuild.ProjectModel` API. This new API provides a *typesafer* and *modern* way of building PIFs programmatically.
This continues the work I started in PR #8405, introducing now our new PIF builder for packages.
Replaces all `SwiftBuild.PIF` (aka, `SWBProjectModel.PIF`) API usage, in `PackagePIFBuilder`, with the new `SwiftBuild.ProjectModel` API instead.
PS. I did run `swiftformat` in all new/changed code, as indicated by the *contributors* guide.
`PackagePIFBuilder` is now modernized... but still not actually used. This will come in my next pull request.
Tracked by rdar://147526957.
=> Adopt SwiftBuild.ProjectModel API in the new PIF builder in SwiftBuildSupport

Tests/SourceControlTests/GitRepositoryTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift
Some tests in Tests/SourceControlTests are passing on Windows since upgrading the Git Version in the associated docker image, which was completd in https://github.com/swiftlang/swift-docker/pulls/452
Enable the tests that are skipped.
Relates to: #8433 
=> Tests: Enabled SourceControlTests on Windows

Sources/swift-build-prebuilts/BuildPrebuilts.swift
We were focused on including things for macros but missed a number of products, including new ones for 601. With this change we now just include all the products and make sure all the targets they depend on end up in the library.
=> Add missing products from the swift-syntax prebuilts.

Documentation/Usage.md
This updates and clarifies the [Version-specific Manifest Selection](https://github.com/swiftlang/swift-package-manager/blob/main/Documentation/Usage.md#version-specific-manifest-selection) section of the usage documentation to clarify the behavior when having either newer or older tools versions.
In general, when using the versioned manifest feature, it's preferable to have the unversioned `Package.swift` represent the newest-supported tools version, and only use version-specific manifest files for older versions. This provides a better workflow because it allows you to more easily drop support for older versions when ready (by avoiding the need to modify the unversioned file), among other benefits.
- "Reverse" the example shown in this documentation by having the unversioned file be …
=> Clarify documented behavior of versioned manifest files in usage docs

Tests/WorkspaceTests/WorkspaceTests.swift
Enable WorkspaceTests on Windows that, for some reason, previously failed.
Relates: #8433
=> Tests: Enable some WorkspaceTests on Windows

Tests/BasicsTests/AsyncProcessTests.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/BuildTests/BuildSystemDelegateTests.swift, Tests/BuildTests/LLBuildManifestBuilderTests.swift, Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
Enable additional tests on Windows host platform
- Enable a few `AsyncProcessTests`
- Enable the lone skipped test in `EnvironmentTests`
- Enable the only skipped test in  `Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift`
- Enable the only skipped test in `Tests/BuildTests/BuildSystemDelegateTests.swift`
- Enable the lone skipped test in `Tests/BuildTests/LLBuildManifestBuilderTests.swift`
- Replace usages of `fixwin` with `AbsolutePath.pathString`
Related to: #8433
=> Tests: Enable tests on Windows

Sources/_InternalTestSupport/Process.swift, Sources/_InternalTestSupport/SkippedTestSupport.swift
Until #8223 is fixed copy some helpers from `IntergrationTests/Source/IntegrationTests` to `Test/_InternalTestSupport` so we can re-use the functionality.
Related to: #8433
=> Copy helpers internally

Sources/Basics/Graph/GraphAlgorithms.swift, Sources/Build/BuildDescription/ModuleBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan+Swift.swift, Sources/Build/BuildPlan/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/BuildPlanTraversalTests.swift
We were including flags to hook up modulemaps and include files to C library dependencies in macros and plugin tools through to the modules that depend on those. This adds the capability to prune the depth first searches through the dependencies to ensure these are skipped when crossing macro and plugin boundaries.
=> Fix duplicate modulemap errors with macro and plugin deps

Sources/SwiftBuildSupport/README.md
Fixed up incorrect wording:
1. Wasm is not an acronym, thus it's not uppercased [per the spec](https://webassembly.github.io/spec/core/intro/introduction.html#wasm).
2. Existing Swift SDKs support only WASI, while WASI-less Wasm modules can be created with Embedded Swift and Swift SDKs are not needed for that.
=> Fix `SwiftBuildSupport/README.md`

Package.swift, Sources/SPMSQLite3/CMakeLists.txt, Utilities/bootstrap
Ensure swiftpm bootstraps successfully to fully build an OpenBSD toolchain.
* Add the nobtcfi linker flag to the bootstrap script for OpenBSD. This is unconditional for now since swiftpm uses Concurrency liberally and this triggers #80059, so swiftpm only builds on the configuration where BTCFI is disabled. We can revisit some of that perhaps later.
* Ensure SPMSQLite3 builds with the correct link library search path flag in CMakeLists.txt.
* Update Package.swift conditionals for SPMSQLite3.
swiftpm successfully builds and bootstraps on OpenBSD.
=> Fix bootstrapping on OpenBSD

Tests/CommandsTests/TestCommandTests.swift
The TestCommandTests fail on Linux due to a common linker problem with swift build build system,
which is the missing 'main' symbol problem. This is described further detail in #8439.
Provide the link in the skip messages and remove the TODO tags since the investigation is complete
and the reason for the failures is now known.
Update the common test case logic so that it dumps the command execution stdout and stderr
in the case of failure to help diagnose these result.xml failures immediately in the logs.
=> Link test command test failures on Linux to issue

Tests/BasicsTests/Serialization/SerializedJSONTests.swift
Split the SerializedJSONTests into tests that pass and fail on Windows
Related: #8433
=> Tests: Split SerializedJSONTests

IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/_InternalTestSupport/Observability.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
This improves a bit the error/warning output when building with the new `--build-system swiftbuild`. 
This was the current output:
```shell
warning: unknown Enabling the Swift language feature 'MemberImportVisibility' is recommended; set 'SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY = YES' []
error: path("/Users/pmattos/Development/SampleProjects/SamplePackages/PackageAccessCLI/Sources/ExampleApp/main.swift", fileLocation: Optional(SwiftBuild.SwiftBuildMessage.DiagnosticInfo.Location.FileLocation.textual(line: 6, column: Optional(5)))) cannot find 'bar' in scope []
```
...and this is the improved one: 
```shell
warning: Enabling the Swift language feature 'MemberImportVisibility' is recommended; set 'SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY = YES' 
error: …
```
=> Improve Swift Build error formatting

CONTRIBUTING.md
The Swift toolchain installation on swift.org indicate to use swiftly to install the toolchain on macOS and Linux. Update the CONTRIBUTING.md file to refer to swiftly for toolchain management.
=> Docs: Refer to swiftly in CONTRIBUTING.md

Sources/Build/BuildPlan/BuildPlan+Swift.swift, Tests/BuildTests/BuildPlanTests.swift
I had mucked with the fix to finish some testing and forgot to put the fix back. And the test didn't properly catch that. Fixing both.
=> Really fix duplicate module maps this time.

Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift
- this also fixes -enable-library-evolution when used as a unsafeFlags
Closes: #8337
sets SWIFT_EMIT_MODULE_INTERFACE build setting when option is set
the build option will include the .swftinertface files in the module folder
=> Implement --enable-parseable-module-interfaces for swift-build buildsystem

Sources/Commands/SwiftTestCommand.swift
This PR adds support for the `--attachments-path` CLI argument on `swift test` as approved in [ST-0009](https://github.com/swiftlang/swift-evolution/blob/main/proposals/testing/0009-attachments.md). We will maintain support for the older `--experimental-attachments-path` version through Swift 6.2.
The implementation of this option is held entirely in Swift Testing at this time, so no actual code is needed to support it, we just need to make sure Swift Argument Parser doesn't complain about it.
Resolves rdar://147753584.
@plemarquand has integration tests but they're blocked on a newer toolchain; unit testing of this argument exists in the Swift Testing repo.
=> Add `swift test --attachments-path`.

Sources/_InternalTestSupport/misc.swift, Tests/CommandsTests/BuildCommandTests.swift
When running tests ensure the *test fixtures* we copy over to temporary directories don't carry over any previous build information.
When copying packages from `/Fixtures/**` we now ensure we delete any `.build` or `.swiftpm` directories, if any.
Safer tests hopefully :-)
PS. This was driving me nuts as I was playing around with a given `/Fixtures/Foo` but also running tests against it! The tests behaviour would vary depending on what `swift` commands I had previously ran in `/Fixtures/Foo`... fun times! 🙃
=> Tests: Ensure we get clean test fixtures

Sources/Build/BuildPlan/BuildPlan+Swift.swift, Tests/BuildTests/BuildPlanTests.swift
Reverts swiftlang/swift-package-manager#8498
Broke swift-foundation build.
=> Revert "Really fix duplicate module maps this time."

Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/PackageModel/Module/SwiftModule.swift, Tests/BuildTests/BuildPlanTests.swift
For Windows and Linux, SwiftPM generates modules for test discovery and the test entry point. When testing macro targets, we add the swift-syntax prebuilt Modules directory to the include path for the test target. We also need to do this for the generated modules.
As a side effect, this also adds all include directories to the include path for these generated modules to ensure they build for other use cases that may need this.
=> Ensure prebuilt Modules include path added to generated modules

Tests/CommandsTests/BuildCommandTests.swift
Reduce noise from solvable warnings.
We should `throw XCTSkip("...")` but `try XCTSkipIf(true, "...")`. The `BuildCommandTests` was mixing both (i.e., `try XCTSkip("...")`), making the test a nop actually.
Less 22 warnings I guess -:)
=> Tests: Fix 22 warning in BuildCommandTests

Sources/Basics/CMakeLists.txt, Sources/Workspace/Workspace+BinaryArtifacts.swift
The workspace state needs to be saved even if the updateBinaryArtifacts call exits early.
If we delete old artifacts, and then the new versions fail to download, without a save() call the workspace state will not know the artifact is no longer there.
Move the `save()` call to a `defer` block so it always gets called.
There should be fewer inconsistencies between workspace state and what is actually on disk.
=> Make sure the workspace state is saved after adding/removing artifacts.

Sources/SPMBuildCore/Plugins/PluginInvocation.swift, Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Somewhere along the way earling in the 6.1 branch changes were made to how the prebuild commands did their check to make sure the executable invoked in the command existed in the scratch dir.
It had always used a trick that kept track of whether a tool was a vendored binaryTarget or built. And only succeed if it was vendored. That information was lost in the restructuring.
This change stores whether a tool comes from a executable target (built tool) or a binary target (vended) and properly checks to make sure the tool is vended.
This was detected when the SwiftLint prebuild command target was failing when a user upgraded to 6.1. This change will need to be cherry picked back to the 6.1 branch for the next point release.
=> [6.1] Fix prebuild commands (#8440)

Tests/CommandsTests/BuildCommandTests.swift
A SwiftBuild test is currently failing on Amazon Linux 2.  Disable this test for now and link it to a GitHub issue.
=> Disable failing SwiftBuild test on AmazonLinux 2

IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
Increase code coverage for our integration tests.
This is an issue I introduced in #8454 while ignoring `--build-system swiftbuild` issues on Windows (i.e., actually this specific issue #8514). I accidentally skipped the `packageInitExecutable` test for `--build-system native` as well (which should be green). This PR fixes that.
Swift Testing currently doesn't support combining *conditional traits* (e.g.,`skipHostOS(.windows)`) with *parametric tests* — I double-checked with @stmontgomery. So the 2nd best approach is to split the tests as I just did. 
Slightly Increased test coverage for integration tests :-)
=> Tests: Run packageInitExecutable test on all platforms for native build system

IntegrationTests/Tests/IntegrationTests/Helpers.swift, Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/PackageModel/Module/SwiftModule.swift, Tests/BuildTests/BuildPlanTests.swift, Utilities/build-using-self, Utilities/helpers.py
Cherry pick #8485 for 6.1.1. Fixes tests on Linux and Windows while using prebuilts.
=> [6.1.1] Ensure prebuilt Modules include path added to generated modules (#8485)

Sources/Build/BuildPlan/BuildPlan.swift, Tests/BuildTests/BuildPlanTests.swift
This uses the /ALTERNATENAME flag to link.exe, which is roughly equivalent to -alias/--defsym. This has been verified to work in a sample project.
See https://devblogs.microsoft.com/oldnewthing/20200731-00/ for more info.
Closes #6367
=> Add support for testable executables on Windows

Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift
Add **FreeBSD** support to SwiftBuild PIF builder (i.e., when using `--build-system swiftbuild`).
Just a quick change in how we map a `PackageModel.Platform` value to a `SwiftBuild.ProjectModel.BuildSettings.Platform` one.
=> Add FreeBSD support to SwiftBuild PIF builder

Tests/CommandsTests/TestCommandTests.swift
rdar://149936169
This test is currently failing on CI (https://ci.swift.org/job/oss-swift-package-amazon-linux-2-aarch64/4188) and blocks toolchain builds for swift.org.
=> Skip failing test in `TestCommandTests.swift`

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift
Adds a flag and entry into outputs file map per file in a swift module to emit any diagnostics in serialized form.
This is preliminary work to for future `swift migrate` command that needs serialized diagnostics to get the fix-its and enables future improvements like diagnostic de-duplication.
- Add a new flag to `compileArguments` : `-serialize-diagnostics`
- Add an entry per source file an swift module that presents a path to a `.dia` file where the diagnostic information should be stored.
- Add a computed property to fetch diagnostic file locations per swift module
The build would now emit serialized diagnostic files for every swift module.
=> [Build] Enable diagnostic serialization by default for swift modules

Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/AddSetting.swift, Sources/Commands/PackageCommands/SwiftPackageCommand.swift, Sources/PackageModelSyntax/AddSwiftSetting.swift, Sources/PackageModelSyntax/CMakeLists.txt, Sources/PackageModelSyntax/ManifestEditError.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
Adds a way to programmatically insert new settings into a package manifest.
Currently only some Swift settings are supported, namely: `enable{Upcoming, Experimental}Feature`, `swiftLanguageMode` and `strictMemorySafety`; but the command could be expanded to support more Swift (C, C++, linker) settings in the future.
- Add a new "package" sub-command named "add-setting" that accepts a target and a list of `--swift Name[=Value]?` pairs for each new swift setting to add. Each setting would make sure that manifest is new enough to support it.
- Add new manifest refactoring action - AddSwiftSetting that would add `swiftSettings:` to a target or modify the existing one.
- Expands existing way to check whether manifest is too old to support custom versions. This is doe to make sure that users …
=> [Commands] Initial implementation of `swift package add-setting` command

Sources/Commands/SwiftBuildCommand.swift, Sources/Commands/Utilities/DOTManifestSerializer.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SwiftBuildSupport/DotPIFSerializer.swift, Sources/SwiftBuildSupport/PIF.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift
Improve visualization/debuggability of the **PIF JSON** sent over to Swift Build (when using the new `--build-system swiftbuild` option).
This PR introduces the `--print-pif-manifest-graph` option to write out the PIF JSON sent to Swift Build as a [Graphviz file](https://graphviz.org) file. This follows a similar design we used for the existing `--print-manifest-job-graph` option.
All the serialization happens in the new `DotPIFSerializer.swift` file, with this function as the entry point:
```swift
func writePIF(_ workspace: PIF.Workspace, toDOT outputStream: OutputByteStream)
```
With [Graphviz tool](https://graphviz.org) installed (i.e., provides the `dot` command below), we can then run commands like this:
```shell
swift build --build-system swiftbuild --print-pif-manifest-graph | dot …
```
=> Output Swift Build PIF JSON for Graphviz visualization

Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift
There are tests that were formerly failing due to missing support for plugins in the old PIF builder.
Enable these test for better coverage with the new builder.
* Fix spelling in one of the APIs
* Remove macOS-specific linker flag in the PIF builder and use a setting that is target platform neutral
* Update skip comments for tests based on new analysis of the failures
=> Enable more plugin related tests for non-macOS platforms

Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift
Reverts swiftlang/swift-package-manager#8477 due to Amazon Linux 2 failures https://ci.swift.org/job/oss-swift-package-amazon-linux-2/4177/console
=> Revert "Enable more plugin related tests for non-macOS platforms"

Sources/PackageLoading/ManifestLoader+Validation.swift, Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/ModulesGraphTests.swift
Prevent non-targets from depending on test targets
Fix for rdar://149007214 
Currently, only test targets are allowed to have dependencies on other test targets.
Simply checked for each non-test target, if their dependency is of type test. If it is, throw an error.
Swift package manager will give an error explaining that only testTargets can depend on other testTargets
Fixes #8478
=> Prevent non-targets from depending on test targets

Package.swift, Sources/PackageManagerDocs/Documentation.docc/SwiftPackageManager.md
Adds a `Documentation.docc` directory (a bare DocC catalog) as a stub for migrating existing content in `Documentation/` from general markdown into DocC, as well as providing a base for expanding that documentation. Follow up PRs will bring over and convert content from the `Documentation` directory more piecemeal
=> Adds DocC catalog to host SwiftPM documentation

IntegrationTests/Sources/IntegrationTestSupport/Helpers.swift, IntegrationTests/Tests/IntegrationTests/BasicTests.swift, IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift, IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift, Utilities/bootstrap
SPM has functionality to skip a set of tests
using an undocumented environment variable,
'_SWIFTPM_SKIP_TESTS_LIST'.  The presence of this variable causes test output to change around starting/ending of test suites.
Test Suite 'All tests' started
vs.
Test Suite 'Selected tests' started
* Remove checking for the 'All tests' string.
* Check the return code of the test execution.
* Set up environment variables to match bootstrap in the IntegrationTests execution.
* Change bootstrap to use a call() instead of call_output() as call_output will block until the process has finished. A swift-test may take a long time.  Certain CI environments expects output to stream out, and will cancel the build if none is detected for 30 mins.
* Update tests with using the 'checker', to output stdout/stderr …
=> Closes  #8520  - Fix up test execution for IntegrationTests

Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift
There are tests that were formerly failing due to missing support for plugins in the old PIF builder.
Enable these test for better coverage with the new builder.
* Fix spelling in one of the APIs
* Remove macOS-specific linker flag in the PIF builder and use a setting that is target platform neutral
* Update skip comments for tests based on new analysis of the failures
* Skip test that's failing on Amazon Linux 2
=> Re-enable more plugin related tests for non-macOS platforms

Sources/Commands/SwiftTestCommand.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/SourceControlTests/GitRepositoryProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Utilities/build-using-self
The investigation is pointing to running git commands in parallel that is causing the hang with the Windows CI. Turn them off until we can figure out how to serialize them across xctest processes.
Once they completed, fixed the BuildPlanTests which were matching with backslashes.
Also had backslash issues when launching the integration tests.
=> Re-enable tests in Windows CI

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/FunctionalTests/MiscellaneousTests.swift
When using the swiftbuild build system, and building all targets with a project
that contains a target that is depended on only when on a specific platform that
target should be skipped. Make the All(Excluding|Including)Tests generated
targets depend only on targets that are reachable from the roots through
dependencies that are either unconditional or are conditioned on the current
platform.
=> Avoid building targets that are conditional on platform when building all

Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift
Also skips on OpenBSD, which has the same issue.
=> Factor the working directory skip into a common function

Sources/_InternalTestSupport/MockWorkspace.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Sources/_InternalTestSupport/misc.swift, Tests/BasicsTests/FileSystem/InMemoryFilesSystemTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Many WorkspaceTests instantiate a MockWorkspace, which takes a path as an input. The tests were defining a POSIX-like path as the sandbox directory, however, some assertions were incorrect as, on these *nix like filesystem, the canonical path name and the path were identical.
Update the WorkspaceTests expectation accordingly, and add some automated tests to cover the InMemoryFileSystem (which is commented out as a crash occurs in the Linux Platform CI build with Swift Testing tests).
Relates: #8433
=> Tests: Enable more WorkspaceTests on Windows

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Plugins.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder.swift
Ensure the PIF builder follows the same `FileSystem` as the remaining code in the `SwiftBuildSupport` target.
Keep around a file system reference in `PackagePIFBuilder` and use that across the PIF builder.
All code in `SwiftBuildSupport` is now based on the same `FileSystem`.
=> Use correct FileSystem in the PIF builder for Swift Build

Sources/PackageModelSyntax/AddPackageDependency.swift, Sources/PackageModelSyntax/ManifestEditError.swift, Tests/CommandsTests/PackageCommandTests.swift
If the same dependency is added twice with different version specifiers the manifest is no longer valid. If the same dependency is added twice with the same version specifier it remains valid, but less maintainable.
If a manifest already contains the exact dependency and version that is being added via a `add-dependency` call, don't add it twice. Instead, do nothing.
If a manifest contains a dependency with the supplied URL but a different version qualifier then throw an error explaining that the supplied dependency has already been added.
A manifest that continues to parse correctly.
Issue: #8519
=> Make add-dependency idempotent

Utilities/build-using-self, Utilities/helpers.py
Update the build-using-self to support accepting a triple and a build system, which some self hosted CI environments might want to set.
=> pipeline: support additional args in build-using-self

Sources/_InternalTestSupport/XCTAssertHelpers.swift, Sources/_InternalTestSupport/misc.swift, Tests/BasicsTests/AsyncProcessTests.swift, Tests/BasicsTests/FileSystem/PathTests.swift, Tests/BasicsTests/FileSystem/VFSTests.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/BasicsTests/LegacyHTTPClientTests.swift, Tests/BasicsTests/Serialization/SerializedJSONTests.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/BuildSystemDelegateTests.swift, Tests/BuildTests/PluginsBuildPlanTests.swift, Tests/BuildTests/PrepareForIndexTests.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/RunCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift, Tests/PackageLoadingTests/PackageBuilderTests.swift, Tests/PackageLoadingTests/PkgConfigParserTests.swift, Tests/PackageLoadingTests/PkgConfigTests.swift, Tests/QueryEngineTests/QueryEngineTests.swift, Tests/SourceControlTests/GitRepositoryProviderTests.swift, Tests/SourceControlTests/GitRepositoryTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/SourceControlPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift, Utilities/README.md
Update the GitHub issue reference on some skipped tests, and also merge the skipIfOnWindowsBecause..() and XCTSkipOnWindows() helper functions to make aid with discoverability.
Also, update the Git Tests to be skipped only in the self hosted pipelines, as that is the environment where the tests are hanging.
=> Tests: Merge Windows helper function and update GH issues

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift
Fixes a few issues introduced by #8441, where the PIF model transitioned from *reference types* to *value types* (i.e., the new `SwiftBuild.ProjectModel` API.)
Just a couple of changes in the `PackagePIFBuilder.BuildDelegate` protocol, ensuring we can actually mutate the `ProjectModel.Project` value.
=> Some PIF delegate fixes for Swift Build 

Sources/Build/BuildDescription/ClangModuleBuildDescription.swift, Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift, Sources/XCBuildSupport/PIFBuilder.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/CrossCompilationBuildPlanTests.swift, Tests/XCBuildSupportTests/PIFBuilderTests.swift
Introduce Swift compilation conditions to support `#bundle` in Foundation.
This is the SwiftPM companion to `#bundle`.
Pitch: https://forums.swift.org/t/pitch-introduce-bundle-macro/79288
Proposal: https://github.com/swiftlang/swift-foundation/pull/1251
Implementation: https://github.com/swiftlang/swift-foundation/pull/1274
Define `SWIFT_MODULE_RESOURCE_BUNDLE_AVAILABLE` when we'd like `#bundle` to call our generated `Bundle.module`.
Define `SWIFT_MODULE_RESOURCE_BUNDLE_UNAVAILABLE` when there are no resources and `#bundle` should complain about that.
Leave them both undefined when we'd like `#bundle` to keep its default behavior of using the same bundle where the source code lives.
`#bundle` will point to the correct resource bundle when called from Swift Packages.
=> Introduce new defines to enable #bundle in Swift Packages

Tests/WorkspaceTests/WorkspaceTests.swift
Rename remaining occurrences of the old helper.
My local test failed to build after #8569 with
```
…/Tests/WorkspaceTests/WorkspaceTests.swift:16148:13: error: cannot find 'skipOnWindowsAsTestCurrentlyFails' in scope
16146 | 
16147 |     func testInvalidTrait_WhenParentPackageEnablesTraits() async throws {
16148 |         try skipOnWindowsAsTestCurrentlyFails(because: #"\tmp\ws doesn't exist in file system"#)
|             `- error: cannot find 'skipOnWindowsAsTestCurrentlyFails' in scope
16149 | 
16150 |         let sandbox = AbsolutePath("/tmp/ws/")
```
I checked, and it appears to be leftovers after  #8569:
```
% rg skipOnWindowsAsTestCurrentlyFails
Tests/WorkspaceTests/WorkspaceTests.swift
16148:        try skipOnWindowsAsTestCurrentlyFails(because: #"\tmp\ws doesn't exist in file …
```
=> Rename remaining occurrences of the old helper.

Sources/Basics/Archiver/TarArchiver.swift, Sources/Basics/Archiver/ZipArchiver.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/BasicsTests/Archiver/TarArchiverTests.swift, Tests/BasicsTests/Archiver/UniversalArchiverTests.swift, Tests/BasicsTests/Archiver/ZipArchiverTests.swift, Tests/_InternalTestSupportTests/Misc.swift, Tests/_InternalTestSupportTests/XCTAssertHelpersTests.swift
The Archiver tests has a dependency on a system binary being available on the host.  Update the archiver test to skip the test is the required executable is not available on the system.
Fixes: #8586
Issue: rdar://150414402
Required for: https://github.com/swiftlang/swift/pull/80405
=> Tests: Conditionally skip the Archiver tests

Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Binaries/MyVendedSourceGenBuildTool.artifactbundle/info.json, Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Binaries/MyVendedSourceGenBuildTool.artifactbundle/mytool-windows/mytool.bat, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/PluginsBuildPlanTests.swift, Tests/BuildTests/PrepareForIndexTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- Enable the BuildPlanTests on Windows
- Split a PrepareForIndexTests tests into two withthe passing, and failing on Windows
- update/add a message on some skipped windows tests, with a reference to GitHub Issue
Related to: #8433
Depends on: #8569
=> Tests: Enable some BuildTests/**/*.swift tests on Windows

Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
A few SourceControlPackageContainerTests fail for the same reason.  Keep skipping them but add a GitHub issue and the error that occurs to the skip reason
Relates to: #8433
Issue: rdar://148248105
Depends on: #8569
=> Tests: Reference issue in skipped SourceControlPackageContainerTests

Tests/BasicsTests/FileSystem/FileSystemTests.swift, Tests/BasicsTests/FileSystem/InMemoryFilesSystemTests.swift, Tests/BasicsTests/FileSystem/PathShimTests.swift, Tests/BasicsTests/FileSystem/PathTests.swift, Tests/BasicsTests/FileSystem/TemporaryFileTests.swift, Tests/BasicsTests/FileSystem/VFSTests.swift
Convert posted test from XCTest to Swift Testing, while updating to ensuring we mark the tests that currently fail on windows.
Tests/BasicsTests/FileSystem/FileSystemTests.swift
Tests/BasicsTests/FileSystem/PathShimTests.swift
Tests/BasicsTests/FileSystem/PathTests.swift
Tests/BasicsTests/FileSystem/TemporaryFileTests.swift
Tests/BasicsTests/FileSystem/VFSTests.swift
Depends on https://github.com/swiftlang/swift/pull/81217
Partially Addresses: #8433
Issue: rdar://148248105
=> Tests: Enable BasicsTests/FileSystem/* Tests on Windows (Swift Testing)

Package.swift, Sources/SwiftFixIt/CMakeLists.txt, Sources/SwiftFixIt/SwiftFixit.swift, Tests/SwiftFixItTests/SwiftFixItTests.swift
This is part of the [migration tooling](https://github.com/swiftlang/swift-evolution/pull/2673) initiative for Swift features.
For now, this API accepts a collection of `.dia` files, deserializes them, and applies fix-its in place. Eventually, it is expected to serve the upcoming `swift fixit` and `swift migrate` subcommands and support various filtering options, as well as a stateful, interactive workflow similar to `git add --patch`.
=> Implement SwiftFixIt — a library for deserializing diagnostics and applying fix-its

Sources/_InternalTestSupport/misc.swift, Tests/PackageSigningTests/FilePackageSigningEntityStorageTests.swift, Tests/PackageSigningTests/SigningEntityTests.swift, Tests/PackageSigningTests/SigningIdentityTests.swift, Tests/PackageSigningTests/SigningTests.swift, Tests/QueryEngineTests/QueryEngineTests.swift, Tests/SourceControlTests/GitRepositoryProviderTests.swift, Tests/SourceControlTests/InMemoryGitRepositoryTests.swift
Convert additional suites from XCTest to Swift Testing
The XCTest run, by default, sequentially.  Convert some suites from XCTest to Swift Testing to make use of parallel execution and, in some cases, test parameterization.
Not all Test Suite in the respective folders have been converted as some use helpers in swift-tools-core-support, which don't have a matching  swift testing helper.
Convert XCTest to Swift Testing
Ran the equivalent of the following and ensured there were no test-related failures
```
for _ in $(seq 0 100);
do
swift test --enable-swift-testing --disable-xctest
done
```
Blocked by #8137 
Blocked by  https://github.com/swiftlang/swift/pull/78300
Blocked by https://github.com/swiftlang/swift/pull/81217
=> Test: Convert more tests to Swift Testing

Package.swift
=> Bump iOS deployment target to 17 to match dependencies

Tests/WorkspaceTests/AuthorizationProviderTests.swift, Tests/WorkspaceTests/MirrorsConfigurationTests.swift, Tests/WorkspaceTests/ToolsVersionSpecificationGenerationTests.swift, Tests/WorkspaceTests/ToolsVersionSpecificationRewriterTests.swift, Tests/WorkspaceTests/WorkspaceStateTests.swift
Convert most of the WorkspaceTests from XCTests to Swift Testing to make use of parallelism and, in some cases, test parameterization.
The XCTest run, by default, sequentially.  Convert most of the WorkspaceTests from XCTests to Swift Testing to make use of parallelism, and in some cases, parameterized test cases.
Not all Test Suites in WorkspaceTests have been converted as some use helpers in swift-tools-core-support, which don't have a matching Swift Testing helper.
Convert XCTests to Swift Testing
Ran the equivalent of 
```
for _ in $(seq 0 100); 
do
swift test --enable-swift-testing --disable-xctest
done
```
and ensured there were no test-related failures.
Blocked by #8137 
Blocked on https://github.com/swiftlang/swift/pull/78300
Blocked on …
=> Tests: Convert some WorkspaceTests module tests to Swift Testing

Tests/BasicsTests/ByteStringExtensionsTests.swift, Tests/BasicsTests/ConcurrencyHelpersTests.swift, Tests/BasicsTests/DictionaryTest.swift, Tests/BasicsTests/DispatchTimeTests.swift, Tests/BasicsTests/NetrcTests.swift, Tests/BasicsTests/PhonyTest.swift, Tests/BasicsTests/SampleTests.swift, Tests/BasicsTests/TripleTests.swift
Convert the following test suites to Swift Testing
- Tests/BasicsTests/ByteStringExtensionsTests.swift
- Tests/BasicsTests/ConcurrencyHelpersTests.swift
- Tests/BasicsTests/DictionaryTest.swift
- Tests/BasicsTests/DispatchTimeTests.swift
- Tests/BasicsTests/NetrcTests.swift
- Tests/BasicsTests/TripleTests.swift
Also, remove the phony and sample Swift Testing tests, which were used to ensure we don't regress.
=> Tests: Convert more BasicTests to Swift Testing

Sources/SwiftFixIt/SwiftFixit.swift, Tests/SwiftFixItTests/SwiftFixItTests.swift
Helps with applying only certain fix-its i.e. for features in migration mode or concurrency.
- Add `categories: Set<String>` parameter to `SwiftFixIt` initializers that is defaulted to `[]`.
`swift migrate` can use this to filter based on the feature categories to avoid applying unrelated fix-its.
=> [SwiftFixIt] Allow filtering diagnostics by category

Tests/SPMBuildCoreTests/ArtifactsArchiveMetadataTests.swift, Tests/SPMBuildCoreTests/BuildParametersTests.swift, Tests/SPMBuildCoreTests/XCFrameworkMetadataTests.swift, Tests/_InternalTestSupportTests/Misc.swift
Convert the Tests/SwiftBuildCoreTests/*.swift, and Tests/_InternalTestSupport/Misc.swift to Swift Testing.
=> Tests: Convert SPMBuildCoreTests to Swift Testing

Sources/CoreCommands/SwiftCommandState.swift
Displays the PID of the other SwiftPM instance currently holding the lock
- Fixes #8528 
When we try to run different SwiftPM processes we already see notes like 
```
Another instance of swiftPM is already running using '/Users/louissssss/swift-package-manager/.build', waiting until that process has finished execution...
```
I'll be nice to also have info about PID so I can choose to terminate it or wait for it to finish, so it might display smt like:
```
Another instance of SwiftPM (PID: 3404) is already running using '/Users/louissssss/swift-package-manager/.build', waiting until that process has finished execution...
```
My approach was trying to write process id from the process that acquires the lock to the lock file and then let other processes read from it and get the pid.
If …
=> Display PID of other running SwiftPM processes

Sources/Basics/Concurrency/ConcurrencyHelpers.swift, Sources/Commands/PackageCommands/ResetCommands.swift, Sources/PackageLoading/ManifestLoader.swift, Sources/PackageMetadata/PackageMetadata.swift, Sources/PackageRegistry/RegistryClient.swift, Sources/Workspace/PackageContainer/FileSystemPackageContainer.swift, Sources/Workspace/PackageContainer/RegistryPackageContainer.swift, Sources/Workspace/PackageContainer/SourceControlPackageContainer.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/Workspace/Workspace+Editing.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/Workspace/Workspace+Registry.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockManifestLoader.swift, Sources/swift-bootstrap/main.swift, Tests/PackageLoadingTests/ManifestLoaderCacheTests.swift, Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
This follows on from my work to convert the registry code to `async` methods.
Switch to using async methods when loading manifests, converting synchronous code to the simpler async equivalents and converting sync API calls to their synchronous versions.
This resolves several warnings and FIXMEs, makes the code easier to read and generally implements concurrency in a more idiomatic way.
=> Use async methods when loading manifests

Package.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/BasicsTests/SQLiteBackedCacheTests.swift, Tests/BuildTests/BuildPlanTraversalTests.swift, Tests/BuildTests/LLBuildManifestBuilderTests.swift, Tests/BuildTests/SwiftCompilerOutputParserTests.swift, Tests/BuildTests/WindowsBuildPlanTests.swift, Tests/_AsyncFileSystemTests/AsyncFileSystemTests.swift
Continue to test conversion to Swift Testing.
- Tests/BasicsTests/HTTPClientTests.swift
- Tests/BasicsTests/SQLiteBackedCacheTests.swift
- Tests/BuildTests/BuildPlanTraversalTests.swift
- Tests/BuildTests/LLBuildManifestBuilderTests.swift
- Tests/BuildTests/SwiftCompilerOutputParserTests.swift
- Tests/BuildTests/WindowsBuildPlanTests.swift
- Tests/_AsyncFileSystemTests/AsyncFileSystemTests.swift
=> Tests: Convert more tests to Swift Testing

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift
Just a minor cleanup in `SwiftBuildSupport/SwiftBuildSystem.swift` file.
Move the `extension PIFBuilderParameters` helper to `PIFBuilder.swift` instead.
=> Minor improvement in SwiftBuildSupport helpers

Sources/PackageModel/Manifest/TargetDescription.swift, Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift, Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
Add more context for validation errors for target properties.
I came across a post https://forums.swift.org/t/getting-error-on-package-resolve/75419 which reports the error message to be not clear. I thought I could clarify the message.
```
error: 'xerr': target 'Penny' contains a value for disallowed property 'settings'
```
I've updated the message for the error, so it includes more details to narrow down what is the culprit:
- highlight that the property depends on the target type
- show the value of the property, so that there's a hint what line in the Package.swift lead to the error (for example, linkerSettings or cxxSettings)
Before:
```
error: 'xerr': target 'Penny' contains a value for disallowed property 'settings'
```
After:
```
error: 'xerr': target 'Penny' is assigned a …
```
=> Add more context for validation errors for target properties.

Sources/PackageModel/SwiftSDKs/SwiftSDKBundleStore.swift, Tests/PackageModelTests/SwiftSDKBundleTests.swift
Swift SDK artifact bundle for WASI now supports both embedded and non-embedded modes. Majority of their content is overlapping, thus to avoid duplication they live in the same source tree.
Currently, SwiftPM requires that Swift SDKs are located in separate directories, with `swift-sdk.json` metadata at the root of each directory.
SwiftPM can now parse Swift SDK metadata that points directly to metadata JSON files instead of their root directories.
We can avoid changing file system layout in the artifact bundles for WASI and just place sibling `nonembedded.json` and `embedded.json` Swift SDK metadata files in the same directory in their existing layout.
The change is transparent to Swift SDK users and is an optional and incremental addition for Swift SDK authors.
As Swift SDKs are required …
=> Support Swift SDKs w/ many metadata files in same directory

Package.swift
Sourcekit-lsp was a consumer of SwiftPM and the project moved to 6.1.
Update SwiftPM to the same version.
=> Set tools version to 6.1

Sources/Build/BuildDescription/ProductBuildDescription.swift, Tests/BuildTests/BuildPlanTests.swift
Updates the ProductBuildDescription linkArgument's logic to avoid adding local rpaths for noneOS which does not support dynamically linked executables.
=> Do not try to add rpath arguments on noneOS

Sources/_InternalTestSupport/Observability.swift, Tests/BasicsTests/Environment/EnvironmentKeyTests.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/BasicsTests/Graph/AdjacencyMatrixTests.swift, Tests/BasicsTests/Graph/DirectedGraphTests.swift, Tests/BasicsTests/Graph/UndirectedGraphTests.swift, Tests/BasicsTests/ObservabilitySystemTests.swift, Tests/BasicsTests/ProgressAnimationTests.swift, Tests/BasicsTests/StringExtensionsTests.swift
Reverts swiftlang/swift-package-manager#8624 as https://ci.swift.org/job/swift-bootstrap-ubuntu-24_04-x86_64/129/ failed with.
```
[2025-05-09T09:18:51.687Z] /home/build-user/swiftpm/Sources/_InternalTestSupport/Observability.swift:21:8: error: no such module 'Testing'
[2025-05-09T09:18:51.687Z]  19 | 
[2025-05-09T09:18:51.687Z]  20 | import TSCTestSupport
[2025-05-09T09:18:51.687Z]  21 | import Testing
[2025-05-09T09:18:51.687Z]     |        `- error: no such module 'Testing'
[2025-05-09T09:18:51.687Z]  22 | 
[2025-05-09T09:18:51.687Z]  23 | extension ObservabilitySystem { 
```
We should update the Jenkins build presets to treat Swift Testing the same as XCTest, or maybe update SwiftPM to to build the targets meant to be use only by test targets.
=> Revert "Tests: Convert Environment/Graph and other suites to ST"

Sources/SwiftFixIt/CMakeLists.txt
This is currently only intended to be used by a few commands and shouldn't be vended.
=> [cmake] Turn `SwiftFixIt` into a static library

CMakeLists.txt, Package.swift, Sources/SwiftBuildSupport/CMakeLists.txt, Sources/SwiftBuildSupport/DotPIFSerializer.swift, Sources/SwiftBuildSupport/PIF.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Plugins.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/TestCommandTests.swift, Utilities/bootstrap
Build on https://github.com/swiftlang/swift-build/pull/376 to begin building Swift Build during the CMake bootstrap of SwiftPM
Depends on: https://github.com/swiftlang/swift-installer-scripts/pull/417
=> Build SwiftBuild as part of CMake bootstrapping

Package.swift
A `swift-numerics` package dependency was added to convert an XCTest `XCTAssertEqual(_:_:accuracy:_:file:line:)` API do use the `isApproximatelyEqual()` API in `swift-numerics`, but converting that test resulted in a flaky behaviour.  As such, the test was not converted to Swift Testing, but the swift-numerics dependency remained.
This change removes the swift-numerics dependency as it's no currently required.
=> Remove Swift-numerics dependency

Sources/_InternalTestSupport/Observability.swift, Tests/BasicsTests/Environment/EnvironmentKeyTests.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/BasicsTests/Graph/AdjacencyMatrixTests.swift, Tests/BasicsTests/Graph/DirectedGraphTests.swift, Tests/BasicsTests/Graph/UndirectedGraphTests.swift, Tests/BasicsTests/ObservabilitySystemTests.swift, Tests/BasicsTests/ProgressAnimationTests.swift, Tests/BasicsTests/StringExtensionsTests.swift
Convert `BasicsTests/Environment/*.swift`, `BasicsTests/Graph/*.swift` and a couple other in BasicsTests to Swift Testing
Depends on: https://github.com/swiftlang/swift/pull/81401
Reverts #8647
=> Tests: Convert Environment/Graph and other suites to ST

CONTRIBUTING.md
SwiftPM's contributor documentation should clarify that in general changes should be submitted against the `main` branch first, with organization-wide PR description templates to be followed for release branch cherry-picks.
Added a paragraph to `CONTRIBUTING.md` clarifying the process of the `swiftlang` GitHub org for release branches.
Contributors documentation is more clear and it's more obvious how a change could be cherry-picked to release branches.
=> Clarify release branch cherry-picks process in `CONTRIBUTING.md`

Sources/_InternalTestSupport/SkippedTestSupport.swift
Until #8223 is fixed copy some helpers from
`IntergrationTests/Source/IntegrationTests` to
`Test/_InternalTestSupport` so we can re-use the functionality.
Same as: #8467 - without the `Process.swift` since it's already in the destination branch
Related to: #8433
Depends on: https://github.com/swiftlang/swift/pull/81401
=> Copy helpers internally - take 3

Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift
Update `LD_RUNPATH_SEARCH_PATHS` of executable built using the new Swift Build backend.
For the **Swift Build** backend, fix a runtime issue when building & running an executable linked against a dynamic library. Given the following packages:
```swift
name: "App",
.package(path: "../Lib")
],
targets: [
.executableTarget(
name: "App",
.product(name: "Utils", package: "Lib")
]
)
]
)
```
```swift
name: "Lib",
products: [
.library(
name: "Utils",
type: .dynamic,
targets: ["Utils"]
)
],
targets: [
.target(name: "Utils")
]
)
```
This the error that I get:
```shell
$ swift run --package-path /App --build-system swiftbuild
dyld[89079]: Library not loaded: @rpath/libUtils.dylib
Referenced from: …
```
=> SwiftBuild: Fix executable can't find dynamic lib runtime error

Documentation/PackageRegistry/PackageRegistryUsage.md, Documentation/PackageRegistry/Registry.md
I came across these issues while researching existing package registry implementations.
=> Fix typos in package registry documentation

Sources/PackageModel/UserToolchain.swift, Tests/BuildTests/BuildPlanTests.swift
This modifies the logic for determining compiler flags for locating Swift Testing content such that it will always include a search path for Swift Testing's macro plugin at its newer, testing-specific location in the toolchain, if that directory exists.
Swift Testing installs a macro plugin library named `TestingMacros` into the official Swift toolchains for several platforms. By convention, most Swift macro plugins are installed into the toolchain's `usr/lib/swift/host/plugins` directory. However, testing libraries are somewhat special in the sense that they should generally only be available for use in "non-product" targets, i.e. targets which are not intended for distribution and only intended for use in qualifying the main product targets which _will_ be distributed.
For that reason, …
=> Include search path for Swift Testing's macro plugin from toolchain if present

Sources/SwiftBuildSupport/DotPIFSerializer.swift
Improve **PIF** debugging capabilities (when using the new `--build-system swiftbuild` option).
Adds the `ProjectModel.TargetCommon.name` property to the graphviz output (i.e., `--print-pif-manifest-graph`).
This also slightly improves the `DotPIFSerializer.swift` code.
A sample output:
```shell
$ swift build --package-path /FooPackage --build-system swiftbuild --print-pif-manifest-graph  
```
=> Add target name to PIF graphviz output

Sources/Basics/Cancellator.swift, Sources/Basics/DispatchTimeInterval+Extensions.swift, Sources/Basics/JSON+Extensions.swift, Sources/SPMBuildCore/Plugins/DefaultPluginScriptRunner.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift
We should prefer not to list out Darwin-derived platforms, and remove some old conditional code for versions we no longer support.
=> Clean up some Darwin platform conditions

Tests/PackageRegistryTests/RegistryClientTests.swift
Continue the test conversion to Swift Testing
- Tests/PackageRegistryTests/RegistryClientTests.swift
=> Tests: Convert RegistryClientTests to Swift Testing

Sources/Commands/PackageCommands/Migrate.swift
If migrate fails to insert one or more features into the manifest for a target, let's produce a single error that lists all of the features, this makes the logging less noisy.
- Update `SwiftPackageCommand` to request manifest to all of the features related to a target and produce a single error if that fails.
If manifest has some non-standard ways of defining targets or settings that cannot be updated by `AddSettting`, migration logging is going to be more organized and less noisy.
=> [Commands] Migrate: Group manifest update errors per target

Sources/CoreCommands/Options.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageModel/UserToolchain.swift, Sources/Workspace/Workspace+Prebuilts.swift, Sources/Workspace/Workspace.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/SwiftCommandStateTests.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
Prebuilts for macros and the automated downloading of SwiftSDKs need to know the version of the compiler so we can fetch compatible binaries. The swiftc compiler has a --print-target-info options which dumps out a JSON structure that contains the compilerVersion. We already use info in this structure to determine the hostTriple for the UserToolchain.
This adds the swiftCompilerVersion to UserToolchain that uses a couple of regex's to pull out the Swift compiler version. This is then used by the prebuilts feature instead of our current hardcodeing of the swift toolchain version.
This also turns the prebuilts feature on by default which was supposed to be done in the last update.
=> Dynamically determine the swift compiler version.

Tests/BasicsTests/AsyncProcessTests.swift, Tests/BasicsTests/Environment/EnvironmentTests.swift, Tests/CommandsTests/RunCommandTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/TraitTests.swift
The AsyncProcess Tests were using a TSCTestSupport method to temporarily change the PATH env but seems to have a bug where it removes the variable instead of restoring resulting in any future test needing PATH to fail.  This switches it to using the similar method that is in SwiftPM Environment.swift
=> Fix issue with running test on windows w/no-parallel

Fixtures/SwiftMigrate/InferIsolatedConformancesMigration/Package.swift, Fixtures/SwiftMigrate/InferIsolatedConformancesMigration/Sources/Fixed/Test.swift, Fixtures/SwiftMigrate/InferIsolatedConformancesMigration/Sources/Test.swift, Fixtures/SwiftMigrate/StrictMemorySafetyMigration/Package.swift, Fixtures/SwiftMigrate/StrictMemorySafetyMigration/Sources/Fixed/Test.swift, Fixtures/SwiftMigrate/StrictMemorySafetyMigration/Sources/Test.swift, Sources/Commands/PackageCommands/AddSetting.swift, Sources/Commands/PackageCommands/Migrate.swift, Sources/PackageModel/Toolchain+SupportedFeatures.swift, Sources/PackageModelSyntax/AddSwiftSetting.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
In addition to upcoming and experimental features, handle migration for "optional" features (the only one now being StrictMemorySafety). Read optional features from the supported-features JSON coming from the compiler and use their provided flags.
While here, use the newly-introduced "categories" field from the JSON to filter the list of categories rather than assuming it's the same as the feature name.
=> [Swift migrate] Handle migration for optional features

Sources/Commands/PackageCommands/Migrate.swift, Sources/SwiftFixIt/SwiftFixIt.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/SwiftFixItTests/BasicTests.swift, Tests/SwiftFixItTests/CategoryTests.swift, Tests/SwiftFixItTests/FilteringTests.swift, Tests/SwiftFixItTests/Utilities.swift
* E.g. `> Applied 3 fix-its in 1 file (0.001s)`.
* Don’t output messages with a period for consistency with other commands.
* Minor optimization for fix-it application. 
`SwiftIDEUtils.FixItApplier.applyFixes` performs some O(n^2) filtering based on `SwiftDiagnostics.FixItMessage` messages, which we don't need. Use the overload that directly takes an array of source edits instead.
Sits on top of https://github.com/swiftlang/swift-package-manager/pull/8683.
=> swift-package-migrate: Report a fix-it application summary

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
This patch ensures that the Swift Build SDK and platform name are set correctly for embedded Apple platforms (iOS, tvOS, watchOS) and Android, that the SDK variant is set correctly for Mac Catalyst, and that the deployment target version is correctly propagated from the `--triple` argument specified on the command line.
=> Swift Build: pass some additional settings needed for cross-compilation

Sources/PackageModel/Toolchain.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift
SwiftBuild can be initialized with either an Xcode-based developer directory for a Swift toolchain based developer directory, pass the right flags to initialize properly based on what kind of toolchain is in use.
=> Pass the correct toolchain path to SwiftBuild

Sources/SwiftFixIt/SwiftFixIt.swift, Tests/SwiftFixItTests/BasicTests.swift, Tests/SwiftFixItTests/CategoryTests.swift, Tests/SwiftFixItTests/FilteringTests.swift, Tests/SwiftFixItTests/Utilities.swift
As it turns out, contrary to an old comment in the diagnostic deserializer, the Swift compiler *does* serialize the offset of a source location, so stop assuming that it may have been left blank.
This slightly simplifies the diagnostic conversion logic and also enables us to stop hashing the line and column in the diagnostic filter.
=> SwiftFixIt: Always rely on the UTF-8 offset of an input source location

Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift
Until we get https://github.com/swiftlang/swift-evolution/blob/main/proposals/0487-extensible-enums.md or a similar mechanism, add some redundant default clauses so that changes like https://github.com/swiftlang/swift-build/pull/526 can be staged in without revlock.
=> Allow staging in new BuildSettings.Declaration cases without introducing failures

Sources/Workspace/Workspace+Manifests.swift, Tests/BasicsTests/FileSystem/InMemoryFilesSystemTests.swift, Tests/BasicsTests/TripleTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fix warnings in the repo
Warnings are lame
Remove unused code
Removed unneeded try
Use unforced unwraps in tests
Fewer warnings
=> Fix several warnings across the codebase

Sources/Commands/CommandWorkspaceDelegate.swift, Sources/Workspace/Workspace+Delegation.swift, Sources/Workspace/Workspace+Prebuilts.swift, Sources/_InternalTestSupport/MockWorkspace.swift
In order to associate what prebuilt artifact goes with what package, add the `PackageIdentity` as a parameter to the delegate methods for prebuilts on `WorkspaceDelegate`.
=> Add PackageIdentity to Workspace prebuilt delegate methods

Tests/PackageCollectionsTests/TrieTests.swift
Move to TrieTest to swift-testing
swift-testing is nicer to read and faster to run
Removes DispatchGroup in favor of TaskGroup
use expect(throws:) with type to make tests more readable
More idiomatic swift tests
=> Move to TrieTest to swift-testing

Fixtures/SwiftMigrate/InferIsolatedConformancesMigration/Package.swift, Fixtures/SwiftMigrate/InferIsolatedConformancesMigration/Sources/Fixed/Test.swift, Fixtures/SwiftMigrate/InferIsolatedConformancesMigration/Sources/Test.swift, Fixtures/SwiftMigrate/StrictMemorySafetyMigration/Package.swift, Fixtures/SwiftMigrate/StrictMemorySafetyMigration/Sources/Fixed/Test.swift, Fixtures/SwiftMigrate/StrictMemorySafetyMigration/Sources/Test.swift, Sources/Commands/PackageCommands/AddSetting.swift, Sources/Commands/PackageCommands/Migrate.swift, Sources/PackageModel/Toolchain+SupportedFeatures.swift, Sources/PackageModelSyntax/AddSwiftSetting.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift
Explanation: Expand migration support to cover optional features like strict memory safety, in addition to upcoming features. While here, also add a test for migration to inferring isolated conformances.
Scope: Limited to the migrator.
Original PR: https://github.com/swiftlang/swift-package-manager/pull/8711
Risk: Very low; it's limited to the migrator.
Testing: CI
Reviewed by: @xedin, @AnthonyLatsis
=> [6.2] [Swift migrate] Handle migration for optional features (#8711)

Sources/CoreCommands/BuildSystemSupport.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/swift-bootstrap/main.swift, Tests/FunctionalTests/PluginTests.swift
* Add disable-able sandboxing to the custom tasks in the PIF with the
declared input and output files.
* Add more test coverage of plugin scenarios
* Capture child diagnostics from Swift Build and emit those through
equivalent observability scope in SwiftPM
=> Add sandboxing to build tool plugins in swiftbuild build system

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan+Product.swift, Sources/PackageModel/Module/Module.swift
SwiftPM currently only detects Embedded Swift set via a swift settings and uses this to enable/disable a couple features. This is nice, but doesn't handle the case where Embedded is enabled via a user flag, typically set in a toolset.json. This commit updates the logic to also search for "-enable-experimental-feature Embedded" in the various place user flags can be placed.
=> Detect embedded swift in flags

Sources/PackageManagerDocs/Documentation.docc/GettingStarted.md, Sources/PackageManagerDocs/Documentation.docc/IntroducingPackages.md
Migrate content from https://www.swift.org/documentation/package-manager/ to DocC into an article `Getting Started`
Added getting started article, with updated content to align to examples - two of the 3 updated to reference Swift 5.10 to show more recent dependency declarations in a `Package.swift` manifest.
resolves #8702
=> migrated, and updated, swift package manager getting started content

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder.swift, Tests/FunctionalTests/PluginTests.swift
This test case did not work until https://github.com/swiftlang/swift-build/pull/541 was merged.
=> Enable contrived test plugin test case

Tests/BuildTests/BuildPlanTests.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/PackageCommandTests.swift
Now that llbuild has fork/exec support, the tests can be enabled on Amazon Linux 2, OpenBSD, etc.
Closes #8499
=> Unskip tests blocked by requireThreadSafeWorkingDirectory

Sources/PackageModel/Toolchain+SupportedFeatures.swift
- Fix "supported features" parsing with older toolchains. `-print-supported-features` flag used to output "enabled_in" version as an integer (major only).
- Handle absence of optional features section. `JSON.get` would throw if the key couldn't be found, let's handle that gracefully for an optional "optional features" section.
- Update `Toolchain.swiftCompilerSupportedFeatures` to use `try?` when querying JSON for an optional "optional" key.
- Update `Toolchain.swiftCompilerSupportedFeatures` to attempt to retrieve "enabled_in" key as a String first and if that fails - as an integer.
`swift package migrate` can now support older toolchains that have "enabled_in" printed as an integer and have no "optional features" section in their `-print-supported-features` output.
=> [PackageModel] Toolchain: A few fixes for features supported by Swift compiler

Sources/PackageModel/Toolchain+SupportedFeatures.swift
- Explanation:
`swift package migrate` is broken when used with older toolchains.
- Fix "supported features" parsing with older toolchains. `-print-supported-features` flag used to output "enabled_in" version as an integer (major only).
- Handle absence of optional features section. `JSON.get` would throw if the key couldn't be found, let's handle that gracefully for an optional "optional features" section.
- Main Branch PR: https://github.com/swiftlang/swift-package-manager/pull/8761
- Risk: Low (only `swift package migrate` is affected by this changes).
- Resolves: rdar://152533205
- Reviewed By: @dschaefer2 
- Testing: Updated existing tests in the suite, added new test-cases.
=> [6.2][PackageModel] Toolchain: A few fixes for features supported by Swift compiler

Package.swift, Sources/BinarySymbols/CMakeLists.txt, Sources/BinarySymbols/ClangHostDefaultObjectsDetector.swift, Sources/BinarySymbols/LLVMObjdumpSymbolProvider.swift, Sources/BinarySymbols/ReferencedSymbols.swift, Sources/BinarySymbols/SymbolProvider.swift, Sources/CMakeLists.txt, Sources/Commands/CMakeLists.txt, Sources/Commands/PackageCommands/AuditBinaryArtifact.swift, Sources/Commands/PackageCommands/SwiftPackageCommand.swift, Sources/PackageModel/UserToolchain.swift, Sources/Workspace/Workspace+BinaryArtifacts.swift, Tests/BinarySymbolsTests/LLVMObjdumpSymbolProviderTests.swift
This is an implementation of the auditing tool described in [SE-0482](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0482-swiftpm-static-library-binary-target-non-apple-platforms.md).
As part of SE-0482 and https://github.com/swiftlang/swift-package-manager/pull/8639 we introduced the ability to depend on prebuilt static libraries (that expose a C interface) and that don't have any dependencies outside of the C standard library. This PR introduces an auditing tool that checks the ABI of static library artifact bundle and checks if it's compatible with the current host platform.
- Create a new package subcommand that checks a local artifact bundle for unexpected external dependencies.
- New internal APIs to inspect the ABI of a binary object (object file, static archive, …
=> Binary Static Library Artifact auditing tool

Sources/PackageManagerDocs/Documentation.docc/ContinuousIntegration.md, Sources/PackageManagerDocs/Documentation.docc/Documentation.md
migrates content from documentation/continuousintegration.md
- convert to DocC format
- minor wording and format adjustments
resolves #8587
=> migrates documentation/continuousintegration.md

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
Add TODO's to mark BuildParameters options not currently handled in the Swift Build backend, and fill in overrides for a few of the trivial ones.
=> SwiftBuildSupport: Cover additional BuildParameters options

Sources/Basics/Environment/EnvironmentKey.swift, Sources/PackageModel/Toolchain.swift, Sources/PackageModel/UserToolchain.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/_InternalTestSupport/MockBuildTestHelper.swift, Tests/CommandsTests/SwiftSDKCommandTests.swift, Tests/FunctionalTests/PluginTests.swift
Linux build tool plugins won't work because they require a library
path to the Swift standard libraries. Add the toolchain's library path
to the environment for the custom task. Enable the tests that cover
this area for non-macOS platforms.
=> Provide library paths to plugin tools when run as custom tasks

Sources/Basics/Concurrency/ConcurrencyHelpers.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageMetadata/PackageMetadata.swift, Sources/PackageRegistry/RegistryDownloadsManager.swift, Sources/SourceControl/Repository.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/Workspace/Workspace+Editing.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/Workspace/Workspace+PackageContainer.swift, Sources/Workspace/Workspace+Registry.swift, Sources/Workspace/Workspace+SourceControl.swift, Sources/_InternalTestSupport/MockPackageContainer.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/BasicsTests/ConcurrencyHelpersTests.swift, Tests/PackageGraphTests/PubGrubTests.swift, Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
The `RepositoryProvider` protocol's `open` method is defined as synchronous. Convert this to `async` to avoid concurrency workarounds in clients that might be prone to deadlocks.
This involved porting `RepositoryManager.lookup` to structured concurrency. The method has some concurrency constraints that are preserved:
- There is a limit (`maxConcurrentOperations`) on how many simultaneous lookups can be performed concurrently.
- If a lookup is requested and one is in flight for the same `RepositorySpecifier`, the in flight request completes before the new one is started.
=> Async git repository opening

Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/CommandsTests/RunCommandTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/ResourcesTests.swift, Tests/FunctionalTests/TraitTests.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Required for https://github.com/swiftlang/swift/pull/80405
=> Disable some tests when running on Windows platform smoke test

Sources/Workspace/Workspace+Prebuilts.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift
One thing we're finding with snapshot toolchain builds is that not all platforms are completed at the same time. The prebuilts publishing job builds for the libraries using the latest available toolchains and then merges them together when signing. Havoc ensues when the toolchains aren't all the same version.
This change adds more metadata to the per zip json files including the swiftVersion used to build the library. The signing task will then see if a manifest already exists for that version and merge in the new platforms. If it doesn't it creates a new manifest from the other metadata in the zip json files. This takes out the use of the current swiftVersion when signing since it may not have been the version that created the libraries.
Cherry-pick from main …
=> [6.2] Allow prebuilt manifests to be updated as platforms are added.

Package.swift
This will make it accessible to clients like sourcekit-lsp
=> Add SwiftBuildSupport to the primary libSwiftPM product

Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/CommandsTests/PackageCommandTests.swift
A test fails in certain CI environmnents.  Introduce an `XCTExhibit...` call that would skip a test if an environment variable is set.
(cherry picked from commit ae31314d46777451398ba56933baed5727fe3498 - #8783)
=> [6.2] Tests: Add "XCTSkipExhibits" call

Sources/Commands/PackageCommands/AddSetting.swift, Sources/Commands/PackageCommands/Migrate.swift
The inconsistency in argument formatting came up as part of SE-0486 review. This is the first step in a direction to make command formatting more consistent.
- `swift package migrate`:
- Rename `--targets` to `--target`
- Change `--target` and `--to-feature` to accept space separated argument lists
- `swift package -add-setting`:
- Switch to `.upToNextOption` formatting. Instead of `--swift A=B --swift C=D` switch to `--swift A=B C=D`.
- Update `MigrateOptions` to use `.upToNextOption` for targets and features.
- Update `SwiftPackageCommand`'s `_swiftSettings` option to use `.upToNextOption`
The `swift package migrate` and `swift package add-setting` command line is now shorter and has consistent formatting.
Resolves: rdar://152687586
=> Unify argument formatting for add setting and migrate

Sources/Build/LLBuildCommands.swift
Normalize any build parameters whose modifications do not need to cause a recompilation. For instance, building with or without `--verbose` should not cause a full rebuild.
Issue: #8690
=> Adding --verbose to swift build triggers a full rebuild instead of incremental

Sources/_InternalTestSupport/XCTAssertHelpers.swift, Tests/CommandsTests/PackageCommandTests.swift
A test fails in certain CI environmnents.  Introduce an `XCTExhibit...` call that would skip a test if an environment variable is set.
=> Tests: Add "XCTSkipExhibits" call

Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Tests/CommandsTests/PackageCommandTests.swift
Command plugins should use the user specified build system when building any dependencies, and if the command plugin requests a build of its own. Supporting the full range of command plugin functionality with the Swift Build backend will take a little more work, but this patch gets the fundamentals wired up
=> Command plugins should respect --build-system selection

Package.swift
We should avoid adding a dependency on Swift Tools Support Core in SwiftPM.  If we need to, we ought to use the `swiftTSCBasicsDeps` and `swiftToolsCoreSupportAutoDeps` variables.
=> Update Package.swift dependency

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/PackageModel/Sanitizers.swift, Tests/BuildTests/BuildPlanTests.swift
I hope that this should fix https://github.com/swiftlang/swift-package-manager/issues/8731, and make it easier to build with libFuzzer.
Add support for a `-sanitize=fuzzer` option in `swift-build`, that sets the correct flags (including `-parse-as-library`) to build a binary for fuzzing. Add an additional test to make sure that these flags get set.
=> Add support for a `--sanitize=fuzzer` flag

Sources/Build/BuildPlan/BuildPlan+Test.swift, Sources/Commands/PackageCommands/AddSetting.swift, Sources/Commands/PackageCommands/Migrate.swift, Sources/PackageGraph/ModulesGraph+Loading.swift, Sources/PackageGraph/Resolution/ResolvedModule.swift, Sources/PackageLoading/PackageBuilder.swift, Sources/PackageModel/Module/BinaryModule.swift, Sources/PackageModel/Module/ClangModule.swift, Sources/PackageModel/Module/Module.swift, Sources/PackageModel/Module/PluginModule.swift, Sources/PackageModel/Module/SwiftModule.swift, Sources/PackageModel/Module/SystemLibraryModule.swift, Sources/_InternalTestSupport/ResolvedModule+Mock.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/ClangTargetBuildDescriptionTests.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/8800, https://github.com/swiftlang/swift-package-manager/pull/8806
Fixes for the following problems:
- Sometimes if the previous build was unsuccessful subsequent `swift package migrate` invocation fails with `error: did not compute a build plan yet`.
- Implicitly generated targets (currently only test targets) are included in migration which results in extraneous warnings and failures (i.e. to update the manifest).
The inconsistency in argument formatting came up as part of SE-0486 review. This is the first step in a direction to make command formatting more consistent.
- `swift package migrate`:
- Rename `--targets` to `--target`
- Change `--target` and `--to-feature` to accept space separated argument lists
- `swift …
=> [6.2] Fixes a few issues with `swift package {migrate, add-setting}` commands

Sources/PackageGraph/ModulesGraph+Loading.swift
Cherry-pick of https://github.com/swiftlang/swift-package-manager/pull/8824
---
- Explanation:
The original check was about system libraries only, the new one filters all of the implicit modules (including snippets) which is incorrect. The is a follow-up to https://github.com/swiftlang/swift-package-manager/pull/8812
- Main Branch PR: https://github.com/swiftlang/swift-package-manager/pull/8824
- Risk: Low
- Reviewed By: @bnbarham 
- Testing: No testing was added, speculative fix.
(cherry picked from commit 68d07f24e363e4e001f1d216ce02e5503df32ec1)
=> [6.2][ModuleGraph] Bring back original check for implicit system libraries

Sources/PackageDescription/BuildSettings.swift
adds documentation to define the default value for target isolation
Following up from [my question in the Swift Forums about the default value for "isolation mode"](https://forums.swift.org/t/what-is-the-default-isolation-mode-for-swift-packages-6-2/80453) for Swift packages.
The default is defined in the [proposal SE-0466](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0466-control-default-actor-isolation.md), but wasn't reflected in PackageDescription documentation.
Updated the documentation for `defaultIsolation` to describe the default.
PackageDescription documentation reflects the default choice if unspecified or set to `nil`
=> adds documentation to define the default value for target isolation

Sources/PackageGraph/ModulesGraph+Loading.swift
The original check was about system libraries only, the new one checks all of the implicit modules.
=> [ModuleGraph] Bring back original check for implicit system libraries

Fixtures/Miscellaneous/Plugins/SwiftFilePlugin/Package.swift, Fixtures/Miscellaneous/Plugins/SwiftFilePlugin/Plugins/MyCustomBuildTool/SwiftToolsBuildPlugin.swift, Fixtures/Miscellaneous/Plugins/SwiftFilePlugin/SimpleSwiftScript.swift, Sources/Basics/Sandbox.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Tests/FunctionalTests/PluginTests.swift
A Swift file can be executed directly in the shell. Typically the file begins with a `#/usr/bin/swift` or an equivalent `xcrun` incantation, and then simply running `swift MyFile.swift` will automatically compile and execute it.
Build tool plugins often leverage Swift, but to do so they add two targets, a `.plugin` and an `.executableTarget`. The executable target builds a binary that the plugin tool then calls during a build.
Often this is more heavyweight than needed. By passing the path to a Swift file to the `executable` argument of the `.buildCommand` returned from your build tool plugin, you could bypass the need to create a separate executable target and just execute the file directly.
However, because SwiftPM executes build tool plugins within a sandbox the sandbox script needs to …
=> Support using a Swift file as a build tool plugin executable

Fixtures/Miscellaneous/APIDiff/WithPlugin/Package.swift, Fixtures/Miscellaneous/APIDiff/WithPlugin/Plugins/BuildPlugin/BuildToolPlugin.swift, Fixtures/Miscellaneous/APIDiff/WithPlugin/Sources/BuildTool/BuildTool.swift, Fixtures/Miscellaneous/APIDiff/WithPlugin/Sources/TargetLib/TargetLib.swift, Sources/Build/BuildPlan/BuildPlan.swift, Tests/CommandsTests/APIDiffTests.swift
Do not include all of the build dir for API digester to avoid conflicting definitions.
Issue #8081 : when a package or its dependencies define a tool plugin, then diagnose-api-breaking-changes report false API breakage.
Investigation shown that diagnose-api-breaking-changes passes for analysis (with `-I`) all of the build dir, with all of the dependencies. When a tool plugin is in the dependency tree, then dependencies for the plugin itself are built with `.host` destination. If it happens that these modules are also built for `.target` destination, then `swift-api-digester` fails to analyze them, and public API declared there is printed as removed.
```
/Users/yy/work/pub/tst/.build/arm64-apple-macosx/debug/MyLib-tool.build/module.modulemap:1:8: error: redefinition of module 'MyLib' …
```
=> Do not include all of the build dir for API digester to avoid conflicting definitions.

Sources/Workspace/InitPackage.swift
Migrate the template code generated by `swift package init --type build-tool-plugin` to use URL instead of Path, fixing compile warnings.
Fixes https://github.com/swiftlang/swift-package-manager/issues/8797
=> Fix warnings in generated build-tool-plugin template code

Sources/_AsyncFileSystem/CMakeLists.txt
This adds a missing file to the target. This was detected by attempting to claw back some of the time in CI and re-use the existing build artifacts.
=> _AsyncFileSystem: add missing file in the CMake build

CMakeLists.txt
This simplifies the build logic and properly adds the linker search path to the build when building for FreeBSD.
=> build: avoid duplicating all the flags for FreeBSD

CMakeLists.txt
This was caught by the attempt to claw back some of the build time by
re-using the artifacts. The package name did not match across SPM and
CMake resulting in the API being unavailable to the tests.
=> build: correct the package name for SPM

Utilities/build-using-self
Update `build-using-self` to include the ignore argument in the process which executes the test and also include an execution duration in the emitted "Done" log.
=> CI: Minor improvement to build-using-self

Tests/FunctionalTests/TraitTests.swift
The TraitTests.traits_whenNoFlagPassed(buildSystem:) is known to fail in some SwiftPM CI environent, however, the known issue is not recorded in some OSS pieplines. namely when running in a Linux host.
=> Tests: Mark test as intermittent failing

Tests/FunctionalTests/PluginTests.swift
This test will fail (or pass) intermittently depending on the Linux builder.
Mark it as intermittent so that it no longer blocks anyone.
=> Mark known issue as intermittent for plugin test

Sources/PackageDescription/BuildSettings.swift
In order to reference `MainActor.Type` in certain circumstances `_Concurrency` must be imported.
=> Explicitly import _Concurrency in PackageDescription/BuildSettings.swift

Sources/Basics/Concurrency/ConcurrencyHelpers.swift, Sources/PackageGraph/PackageContainer.swift, Sources/PackageMetadata/PackageMetadata.swift, Sources/PackageRegistry/RegistryDownloadsManager.swift, Sources/SourceControl/Repository.swift, Sources/SourceControl/RepositoryManager.swift, Sources/Workspace/ResolverPrecomputationProvider.swift, Sources/Workspace/Workspace+Dependencies.swift, Sources/Workspace/Workspace+Editing.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/Workspace/Workspace+PackageContainer.swift, Sources/Workspace/Workspace+Registry.swift, Sources/Workspace/Workspace+SourceControl.swift, Sources/_InternalTestSupport/MockPackageContainer.swift, Sources/_InternalTestSupport/MockWorkspace.swift, Tests/BasicsTests/ConcurrencyHelpersTests.swift, Tests/PackageGraphTests/PubGrubTests.swift, Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift, Tests/SourceControlTests/RepositoryManagerTests.swift, Tests/WorkspaceTests/RegistryPackageContainerTests.swift
The `RepositoryProvider` protocol's `open` method is defined as
synchronous. Convert this to `async` to avoid concurrency workarounds in
clients that might be prone to deadlocks.
This involved porting `RepositoryManager.lookup` to structured
concurrency. The method has some concurrency constraints that are
preserved:
- There is a limit (`maxConcurrentOperations`) on how many simultaneous
lookups can be performed concurrently.
- If a lookup is requested and one is in flight for the same
`RepositorySpecifier`, the in flight request completes before the new
one is started.
=> [6.2] Async git repository opening (#8721)

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
Reorganize some of the SwiftBuildSystem code so we can share the implementation of
- session creation
- writing PIF
- build request construction
There should be no functional change to SwiftPM
=> SwiftBuildSystem: Expose public API for reuse by  SourceKit-LSP/BSP

Sources/PackageDescription/PackageDescription.swift
Deletes a sentence from the doc comments for `Package.name` that wrongly talks about the possibility of `name` being `nil`.
`Package.name` is a non-Optional property so it can never be `nil`, so [the current documentation for it](https://developer.apple.com/documentation/packagedescription/package/name) is factually wrong:
> The name of the Swift package.
>
> **Discussion**
>
> If the name of the package is `nil`, Swift Package Manager deduces the name of the package using its Git URL.
- Deleted part of a doc comment.
=> Delete wrong doc comment for Package.name

Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift
Extends **arm64e** support for **macOS & visionOS** apps, besides the existing iOS support.
SwiftPM currently only supports building **arm64e** packages for iOS.
In Xcode 26 we added support to building packages for arm64e targeting macOS & visionOS platforms too.
Conditionally adds `"arm64e"` to the `ARCHS` build settings in the `PackagePIFBuilder` used to interface with Swift Build.
PIF builder nows had the capability of builds packages for arm64e. Note, for now, that this is currently disabled in SwiftPM.
I validated this by building a simple macOS executable for arm64e:
```shell
$ swift package init --type executable --name HelloWorld
$ swift run swift-build --package-path HelloWorld --build-system swiftbuild
```
...and then I inspected the generated binary:
```shell
$ lipo -archs …
```
=> Extends support for arm64e to macOS & visionOS platforms 

Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMBuildCore/BuiltTestProduct.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/TestDiscoveryTests.swift, Tests/FunctionalTests/TraitTests.swift
Still needs a fair amount of work and cleanup, I'll look at breaking off some parts that can land independently. Depends on the larger patch in https://github.com/swiftlang/swift-build/pull/499
=> Non-darwin test discovery with Swift Build

Sources/SPMBuildCore/BuildParameters/BuildParameters.swift
This default value is not currently used, and removing it helps prevent accidentally introducing a dependency on the .native build system
=> Require explicit build system when initializing BuildParameters

Sources/Commands/PackageCommands/PluginCommand.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/SPMBuildCore/Plugins/DefaultPluginScriptRunner.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/TraitTests.swift
Be consistent in the detection of the build system settings so that both the
build system and the build parameters are using the same setting. Use the
build system setting given after the command plugin name as the highest
precedence, followed by the one (if any) provided after the package subcommand.
When building a specific target with the swiftbuild build system, set the configured
target in the build request to be the one that isn't a dynamic target.
Tag the `TraitTest.packagePluginGetSymbolGraph_enablesAllTraits` with a known
issue when using the swiftbuild build system since the symbol graph extraction
is not yet working there.
Add the toolchain's runtime environment to the environment used when running
command plugins so that the tools have the necessary runtime dependencies when …
=> Activate swift build support for command plugins

Utilities/build-using-self
The SWIFTPM_CUSTOM_BIN_DIR environment variable was set as it was required by the Integration Tests when they were standalone Package. Since merging the Integration Tests Package with the SwiftPM package Tests, setting the environment variable is no longer necessary.
Update the `build-using-self` script to no longer set this environment variable.
=> build-using-self: Do not set unnecessary env var

Sources/CoreCommands/BuildSystemSupport.swift, Tests/FunctionalTests/TraitTests.swift
When Creasting the SwiftBuildSystem Factory, the traits configuration was not passed when loading the package graph.
Update the factory to pass the traits configuration during package resolution, and remove the `withKnownIssues` in TraitTests as it relates to SwiftBuild.
There are some know issues, which are tracked via the automated tests.
=> SwiftBuild: Enable traits support

Package.swift
This reverts commit f8104e54c9f27983455bc88f05a0be5decfdae68.
=> Revert "Add SwiftBuildSupport to the primary libSwiftPM product (#8780)"

Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift
Cherry picks #8550 *again* to `main`.
PS. Looks like my previous `main`PR (ie, #8550) got lost somehow during merging/rebasing, etc...
=> Cherry picks FreeBSD fix to main

Sources/Build/BuildOperation.swift, Sources/Commands/PackageCommands/APIDiff.swift, Sources/Commands/Utilities/APIDigester.swift, Sources/CoreCommands/BuildSystemSupport.swift, Sources/CoreCommands/SwiftCommandState.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters+APIDigester.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SPMBuildCore/BuildSystem/BuildSystemCommand.swift, Sources/SPMBuildCore/BuildSystem/DiagnosticsCapturingBuildSystemDelegate.swift, Sources/SPMBuildCore/CMakeLists.txt, Sources/SourceKitLSPAPI/BuildDescription.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Sources/swift-bootstrap/main.swift, Tests/CommandsTests/APIDiffTests.swift
depends on https://github.com/swiftlang/swift-build/pull/601
closes https://github.com/swiftlang/swift-package-manager/issues/8847
Swift Build has builtin support for generating and comparing to API/ABI baselines. Wire this up to the diagnose-api-breaking-changes command. Notably, we now have a mechanism for running a Swift Build based build and collecting serialized diagnostics, which should be reusable in the implementation of the migrate command.
=> Implement diagnose-api-breaking-changes support with --build-system swiftbuild

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan+Clang.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift
Address two issues preventing a C source file to import the generated compatibility header:
1. Don't mark the module map generated for the compatibility header as `requires objc`. This triggers an error when importing it from a C source file. The compatibility header is already printed in a way where the Objective-C code is protected behind a language check. C clients can safely import it even if they may not see any content. Plus we're adding C content to the compatibility header with the official support for `@cdecl` that is independent of Objective-C.
2. Emit the generated compatibility header and module map in a new `include` directory under the temporary build directory of each Swift library. This directory is then used as a header search path for the dependent clang targets.
This …
=> Allow C targets to import the compatibility header generated for Swift libraries

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Sources/Build/BuildPlan/BuildPlan+Clang.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/ModuleAliasingBuildTests.swift
Cherry-pick #8736 to 6.2
Address two issues preventing a C source file to import the generated compatibility header:
Don't mark the module map generated for the compatibility header as requires objc. This triggers an error when importing it from a C source file. The compatibility header is already printed in a way where the Objective-C code is protected behind a language check. C clients can safely import it even if they may not see any content. Plus we're adding C content to the compatibility header with the official support for @cdecl that is independent of Objective-C.
Emit the generated compatibility header and module map in a new include directory under the temporary build directory of each Swift library. This directory is then used as a header search path for the dependent clang …
=> Cherry-pick Allow C targets to import the compatibility header generated for Swift libraries #8736

Sources/PackageLoading/PkgConfig.swift, Tests/PackageLoadingTests/PkgConfigParserTests.swift, Tests/PackageLoadingTests/PkgConfigTests.swift
We were not handling Windows line endings properly. It's a pretty simple one line fix to separate the lines by newlines.
Re-enabling the pkgconfig tests on Windows.
=> Fix pkgconfig file parsing on Windows.

Sources/PackageLoading/PkgConfig.swift, Tests/PackageLoadingTests/PkgConfigParserTests.swift, Tests/PackageLoadingTests/PkgConfigTests.swift
Cherry-pick #8904 to 6.2.
We were not handling Windows line endings properly. It's a pretty simple one line fix to separate the lines by newlines.
Re-enabling the pkgconfig tests on Windows.
=> Cherry-pick Fix pkgconfig file parsing on Windows. (#8904)

Sources/Workspace/Workspace.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Fix `swift package describe` for packages with binary artifacts that has a .zip extension.
Fixes #4387
I want to avoid an error when running `swift package describe` on a package that contains a binary artifact target with a `.zip` extension.
I modified the `Workspace.loadRootPackage(at:observabilityScope:completion)` method. Specifically, I updated the logic for local binary targets to also return a `BinaryArtifact` object when the file extension is `.zip`.
This change is also based on the comment referenced [here](https://github.com/swiftlang/swift-package-manager/pull/5826#issuecomment-1282990236).
When running `swift package describe` on a package that contains a binary artifact target with a `.zip` extension, the package description is now output without throwing an error.
=> Fix `swift package describe` for packages with binary artifacts that has a .zip extension.

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
As discussed in the Swift forums below, a number of projects require the use of "unsafe" flags. A common example is the use of absolute header include paths set via an environment variable that project consumers agree to use. As such, the flags can be safely used under those circumstances.
This change disables the one line that was doing the check.
We will further study the issue and come up with other mechanisms to ensure the challenges some flags have on quality of the package ecosystem are mitigated.
https://forums.swift.org/t/pitch-disable-checks-for-unsafe-flags-in-swiftpm/80698
=> Disable check for unsafe flags.

Sources/SwiftBuildSupport/PIFBuilder.swift, Tests/FunctionalTests/PluginTests.swift
The native build system is extending the calling environment, such as the
PATH to the build tool invocations. Update the PIF Builder to do the same.
Enable testing of vendored binary build tools on macOS with the swiftbuild
build system.
=> Inherit current environment in build tool plugin custom tasks

Fixtures/SwiftMigrate/ExistentialAnyWithCommonPluginDependencyMigration/Package.swift, Fixtures/SwiftMigrate/ExistentialAnyWithCommonPluginDependencyMigration/Plugins/Plugin/Plugin.swift, Fixtures/SwiftMigrate/ExistentialAnyWithCommonPluginDependencyMigration/Sources/CommonLibrary/Common.swift, Fixtures/SwiftMigrate/ExistentialAnyWithCommonPluginDependencyMigration/Sources/Library/Test.swift, Fixtures/SwiftMigrate/ExistentialAnyWithCommonPluginDependencyMigration/Sources/Tool/tool.swift, Fixtures/SwiftMigrate/ExistentialAnyWithPluginMigration/Package.swift, Fixtures/SwiftMigrate/ExistentialAnyWithPluginMigration/Plugins/Plugin/Plugin.swift, Fixtures/SwiftMigrate/ExistentialAnyWithPluginMigration/Sources/Library/Test.swift, Fixtures/SwiftMigrate/ExistentialAnyWithPluginMigration/Sources/Tool/tool.swift, Sources/Build/BuildOperation.swift, Sources/Commands/PackageCommands/Migrate.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/SwiftFixIt/SwiftFixIt.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/SwiftFixItTests/Utilities.swift
Similar to the API digester integration, pass along a build system delegate to capture serialized diagnostic paths from the build and pass them to the fix-it application infra.
Builds on the changes in https://github.com/swiftlang/swift-package-manager/pull/8857, only the second commit is new
=> Support swift package migrate with --build-system swiftbuild

Sources/Commands/Utilities/TestingSupport.swift, Sources/_InternalTestSupport/SwiftTesting+TraitConditional.swift, Tests/IntegrationTests/SwiftPMTests.swift
The current setting for `LLVM_PROFILE_PATH`, used for code coverage, leads to corrupt profile data when tests are run in parallel or when writing "exit tests" with Swift Testing. This also results in the `swift test --enable-code-coverage` command to fail.
The `LLVM_PROFILE_PATH` environment variable is used by the runtime to write raw profile files, which are then processed when the test command finishes to produce the coverage results as JSON. The variable supports several pattern variables[^1], including `%Nm`, which is currently set, and is documented to create a pool of files that the runtime will handle synchronisation of. This is fine for parallelism within the process but will not work across different processes. SwiftPM uses multiple invocations of the same binary for parallel …
=> Add %p to LLVM_PROFILE_FILE pattern when running tests with coverage

Sources/Commands/Utilities/TestingSupport.swift, Sources/_InternalTestSupport/SkippedTestSupport.swift, Tests/IntegrationTests/SwiftPMTests.swift
Cherry-pick of #8894 
---
The current setting for `LLVM_PROFILE_PATH`, used for code coverage, leads to corrupt profile data when tests are run in parallel or when writing "exit tests" with Swift Testing. This also results in the `swift test --enable-code-coverage` command to fail.
The `LLVM_PROFILE_PATH` environment variable is used by the runtime to write raw profile files, which are then processed when the test command finishes to produce the coverage results as JSON. The variable supports several pattern variables[^1], including `%Nm`, which is currently set, and is documented to create a pool of files that the runtime will handle synchronisation of. This is fine for parallelism within the process but will not work across different processes. SwiftPM uses multiple invocations of the …
=> [6.2] Add %p to LLVM_PROFILE_FILE pattern when running tests with coverage

Sources/PackageModel/InstalledSwiftPMConfiguration.swift, Tests/PackageModelSyntaxTests/ManifestEditTests.swift, Utilities/config.json
`swift package init --type macro `generates a manifest that still points to swift-syntax version 6.0.0 although main has moved on to 6.0.2.
Motivation:
`swift package init --type macro` is outdated
Modifications:
Modified config.json that is shipped as part of the SDK and version provided by InstalledSwiftPMConfiguration
Result:
Locally verified that swift package init --type macro generates a manifest with the updated version. 
Performed a `swift build` using the updated manifest and confirmed version 6.2 of swift-syntax was used:
> MacBook-Pro-207:package-testing rconnell$ swift build
> Fetching https://github.com/swiftlang/swift-syntax.git from cache
> Fetched https://github.com/swiftlang/swift-syntax.git from cache (0.65s)
> Computing version for …
=> Bump swift-syntax in template to 602.0.0-latest

Sources/Commands/PackageCommands/Migrate.swift, Tests/CommandsTests/PackageCommandTests.swift
Currently, options that are specific to `swift package migrate` are shown at the very bottom, following all the global options.
All anonymous option groups get coalesced into the default "OPTIONS" section, which always comes last. So there is no proper way to hoist subcommand options above all the base/global options other than giving the subcommand option group a title.
Using "options" as the title would give us 2 "OPTIONS" sections, whereas a custom title, such as "migrate options", would introduce yet another design inconsistency. Instead, address this by hiding global options, as most other package subcommands do.
=> swift-package-migrate: Hide global options

Fixtures/Miscellaneous/SwiftBuild/Package.swift, Fixtures/Miscellaneous/SwiftBuild/main.swift, Sources/Basics/Observability.swift, Sources/Build/BuildOperation.swift, Sources/Build/LLBuildProgressTracker.swift, Sources/CoreCommands/SwiftCommandObservabilityHandler.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/XCBuildSupport/XCBuildDelegate.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/RunCommandTests.swift
Cherry-pick #8858 to 6.2.
Fixes an issue where the --quiet option had no effect when used with swift run and swift build command.
Motivation:
When using the --quiet option with swift run only error messages should be logged.
Modifications:
Add isQuiet property to filter out messages based on the log level during build phases of the native, xcode and swiftbuild build system.
Remove duplicated declaration of the isVerbose property from different targets.
Result:
When the --quiet option is used with the swift run and swift build command only error messages are logged.
=> Cherry-pick Fix --quiet option not working with swift run #8844 (#8858)

Sources/Commands/SwiftTestCommand.swift
This modifies the `swift test` command line `@Option` properties which represent a Swift Testing event stream version (primarily `--event-stream-version <...>`) to accept arbitrary `String` arguments.
In Swift Testing we are moving towards making the entry point and event stream versions aligned with the Swift version, rather than having an independent versioning scheme which users must look up or keep track of. Once this and other work lands, this means that in order to use the event stream format included in (for example) Swift 6.2, a user would pass `--event-stream-version 6.2`.
However, until now these CLI options have required an integer argument like `--event-stream-version 0`. This change relaxes this requirement so that any arbitrary string will be accepted. In a separate PR, the …
=> Accept arbitrary strings in Swift Testing event stream version options

Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift
Fix a silly typo I did in #8539 (i.e., `Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift`), where I removed the`freebsd` platform by mistake 🫠
Add back `freebsd`to the `SwiftBuild.ProjectModel.BuildSettings.Platform` value we sent over to Swift Build.
Tracked by **rdar://151042619**.
=> Add FreeBSD platform again to SwiftBuild PIF builder

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
As we disable checking for unsafe flags, make sure they are still checked when the swift-tools-version is earlier than 6.2. This ensures consumers of the package don't get unsafe flags errors when using older toolchains. They will need to upgrade their toolchains to use packages with unsafe flags.
=> Only enable unsafe flags if version 6.2 or newer.

Sources/PackageLoading/PackageBuilder.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
Cherry pick of #8951 
As we disable checking for unsafe flags, make sure they are still checked when the swift-tools-version is earlier than 6.2. This ensures consumers of the package don't get unsafe flags errors when using older toolchains. They will need to upgrade their toolchains to use packages with unsafe flags.
=> Cherry pick: Only enable unsafe flags if version 6.2 or newer

Sources/SwiftBuildSupport/BuildSystem.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift
We couldn't call `SwiftBuildSupport.PackagePIFBuilder` from `SwiftBuildSupport/BuildSystem.swift` given the prior `#if canImport(SwiftBuild)` checks in former. This is no longer the case.
Provides a minor code cleanup in `PackagePIFBuilder+Helpers.swift`.
This is tracked by: rdar://139545019
=> SwiftBuildSupport: Revert patch required when we were using '#if canImport(SwiftBuild)' checks

Sources/PackageModel/UserToolchain.swift, Sources/Workspace/Workspace+Prebuilts.swift, Tests/WorkspaceTests/PrebuiltsTests.swift
The swiftCompilerTag field has been recently added to the swiftc -print-target-info JSON we use to determine the swift compiler version for prebuilts. Use this field as the default value, falling back to extracting the swift compiler version from  the compilerVersion field using a regex.
This gives us much better version numbers since it matches the tags for the toolchain.
Also add in the redirect url, https://github.com/apple/swift-syntax.git, as a supported option.
=> Use swiftCompilerTag for the swift compiler version

Fixtures/SwiftMigrate/UpdateManifest/Package.swift, Fixtures/SwiftMigrate/UpdateManifest/Package.updated.targets-A-B.swift, Fixtures/SwiftMigrate/UpdateManifest/Package.updated.targets-A.swift, Fixtures/SwiftMigrate/UpdateManifest/Package.updated.targets-all.swift, Fixtures/SwiftMigrate/UpdateManifest/Sources/A/File.swift, Fixtures/SwiftMigrate/UpdateManifest/Sources/B/File.swift, Fixtures/SwiftMigrate/UpdateManifest/Sources/CannotFindSettings/File.swift, Fixtures/SwiftMigrate/UpdateManifest/Sources/CannotFindTarget/File.swift, Sources/Commands/PackageCommands/Migrate.swift, Tests/CommandsTests/PackageCommandTests.swift
- **Explanation**:
* Improve command-line option descriptions. Be clear that both options accept a comma-separated list, which is not at all obvious, and also state the default for `--target`.
* Add tests for feature resolution errors. This change also extracts feature resolution into a method and removes a superfluous colon from the 'unsupported feature' error message.
* Add more clarity to manifest update error message along with some tests for it.
- **Scope**: `swift package migrate`, essentially diagnosticQoI changes and NFC amendments to string literals.
- **Issues**: —
- **Original PRs**: https://github.com/swiftlang/swift-package-manager/pull/8965.
- **Risk**: Very low.
- **Testing**: Regression test added.
- **Reviewers**: @bkhouri
=> [6.2] swift-package-migrate: Miscellaneous low-risk improvements and more tests

Sources/SwiftBuildSupport/PackagePIFBuilder.swift
I extended **arm64e** support for macOS & visionOS apps in my previous PR #8837. When enabled, that patch *only* produced the arm64e slice but... 
The App Store will now accept **arm64e** for macOS, iOS, and visionOS — arm64e is optional and off by default. But when you turn on arm64e support for packages (ie, using `shouldPackagesBuildForARM64e` PIF builder delegate method) we expect *both* slices in the binary now.
Changes the PIF builder to update the `ARCHS` settings without overriding it completely, ensuring we get all required slices (ie, a so called fat binary).
PIF builder nows has the capability of building packages for arm64 *and* arm64e. (Note, for now, that this is currently disabled in SwiftPM.)
I validated this by building a simple macOS executable for arm64e (and force …
=> Build fat packages when shouldPackagesBuildForARM64e is set

Sources/Basics/Sandbox.swift
Cannot use Metal properly with Swift Packages — even with Apple-recommended plugin workaround
The summary here is that when using xcrun to locate metal, xcodebuild is invoked which queries MobileAssets for the location of the metal toolchain. The query to MobileAssets requires the added entitlement.
Reference: https://github.com/swiftlang/swift-package-manager/issues/8930
Add expected entitlement
=> Cannot use Metal properly with Swift Packages

Sources/Build/BuildOperation.swift, Sources/Build/BuildPlan/BuildPlan.swift, Sources/Commands/SwiftRunCommand.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/XCBuildSupport/XcodeBuildSystem.swift, Sources/_InternalTestSupport/PackageGraphTester.swift, Sources/_InternalTestSupport/PackageGraphTesterXCTest.swift, Sources/_InternalTestSupport/SwiftTesting+TraitConditional.swift, Tests/BuildTests/BuildPlanTests.swift, Tests/BuildTests/PluginInvocationTests.swift, Tests/CommandsTests/RunCommandTests.swift, Tests/PackageGraphTests/CrossCompilationPackageGraphTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
The `swift run --repl` was explicitly using the Native build system. This change modified the `swift run --repl` command to respect the `--build-system <arg>` command line option.  The change introduces a new build output request `replArguments`.  When provided, the build system is responsible for providing the arguments required for the REPL in the
BuildResult.
The Swift Run Command will inspect the build result for this property. If it's unavailable, the command provides an error indicating repl support is unavailable.
A caveat, more work is required to get proper REPL integration with the Package.  At the moment, the System Library paths are not provided by the SwiftBuild System when a repl session is requested via the `run` command.
Relates to: #8846
issue: rdar://153822861
Depends on …
=> Run Command: Add SwiftBuild repl support

Sources/Workspace/Workspace.swift
Both `loadPackage` and `loadRootPackage` specified all traits as enabled when loading a package. Narrow this to only the enabled traits so that the returned `Package` accurately reflects the enabled traits.
=> Use only enabled traits when loading package

Sources/PackageManagerDocs/Documentation.docc/ModuleAliasing.md
Conflicts can arise due to duplicate module names within a package graph. Module aliases themselves if they are not globally unique can introduce further conflicts. The documentation for the module aliases feature can describe a technique for the naming that can help to reduce the likelihood of further collisions by recommending the use of the package identifier as a qualifier to the alias. As other packages in the graph encounter the collision, this system can help for there to be a broader agreement on the new name, which should lessen the cases where module alias chaining is needed.
Update the correct ModuleAliases.md file so that the changes will be shown in the new documentation system.
=> New technique for resolving module name conflicts to module alias docs

Sources/_InternalTestSupport/SwiftTesting+TraitConditional.swift, Sources/_InternalTestSupport/XCTAssertHelpers.swift, Sources/_InternalTestSupport/misc.swift, Tests/BuildTests/BuildSystemDelegateTests.swift, Tests/BuildTests/IncrementalBuildTests.swift, Tests/BuildTests/PluginsBuildPlanTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/CommandsTests/PackageRegistryCommandTests.swift, Tests/FunctionalPerformanceTests/BuildPerfTests.swift, Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/MacroTests.swift, Tests/FunctionalTests/MiscellaneousTests.swift, Tests/FunctionalTests/ModuleAliasingFixtureTests.swift, Tests/FunctionalTests/ModuleMapTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/ResourcesTests.swift, Tests/FunctionalTests/ToolsVersionTests.swift, Tests/FunctionalTests/VersionSpecificTests.swift, Tests/IntegrationTests/BasicTests.swift, Tests/IntegrationTests/SwiftPMTests.swift, Tests/WorkspaceTests/InitTests.swift
Many of the `executeSwift*` command helpers accept a build system provider, which was defaulted to the native build system.  Since we are augmenting the tests to also run against the SwiftBuild, setting a default value may lead to an undesirable test behaviour.
Update all the `executeSwift*` commands to no set a default build system provider.
=> test helpers: do not use default build system

Sources/Basics/HTTPClient/URLSessionHTTPClient.swift, Tests/BasicsTests/URLSessionHTTPClientTests.swift
Fix download of private artifact bundles on GitHub; which now involves a redirect to another domain to which authentication header should not be sent. Fixes https://github.com/swiftlang/swift-package-manager/issues/8946
GitHub API redirects private artifact bundle downloads to Azure Storage, but GitHub authentication headers are sent to Azure Storage domain, resulting in `403` errors:
```
error: failed downloading 'https://api.github.com/repos/ordo-one/model/releases/assets/273301740-linux-313.1.0.zip' which is required by binary target 'Ordo': badResponseStatusCode(403)
```
The issue occurs because Azure Storage rejects GitHub authentication that was set for api.github.com domain; there should be no header set as the redirect comes with a [SAS …
=> fix: DownloadTaskManager handle redirect authentication

Utilities/build-using-self
The build-using-self script was always using macos arm64 as a cross compile host.
Modify the build-using-self's cross compile host to use x86_64 when on ARM, arm64 when on x86_64, and raise an exception when an any other architecture.
=> pipeline: Run proper cross compile host

Sources/PackageModel/UserToolchain.swift, Sources/Workspace/Workspace+Prebuilts.swift, Sources/Workspace/Workspace.swift
We added fetching of the swift compiler version using swiftc -print-target-info in the init of UserToolchain so that it can be passed to the PrebuiltsManager to calculate the manifest and prebuilts zip file names.
However, there are cases where we pass in the triple for the current SDK which was intended to avoid the call to swiftc. We now call it all the time which causes an extra call to swiftc that isn't always needed.
To address this, we make the calculation of the target info lazy and move the call to fetch the swift version to the point we need it in the PrebuiltsManager. If prebuilts aren't required, the call is avoided.
To properly test this we need to run a test that calls out to swiftc. However, we don't have integration tests yet for prebuilts since they would take a long time …
=> Only fetch swiftc target info when needed.

Sources/CoreCommands/Options.swift
Previously, these would fallback to --build-system Xcode, which isn't necessary since Swift Build can build universal binaries
=> Allow use of swiftbuild backend when multi-arch builds are explicitly requested

Utilities/SwiftPM+SwiftBuild.xcworkspace/contents.xcworkspacedata
This is actually a copy of the one in the swift-build repo. But for those of us who start in SwiftPM, it's convenient to have it here too. We'll probably add more for other repo combinations over time.
=> Add an Xcode project to help codevelop SwiftBuild

Sources/Build/LLBuildProgressTracker.swift
Frequent crashes in LLBuildProgressTracker while building swift-java on linux and swift 6.1.2
> Thread 4 crashed:
> 
> 0                         0x00007f1559da359a swift_slowAlloc + 74 in [libswiftCore.so](http://libswiftcore.so/)
> 1 [ra]                    0x00007f1559da3877 swift_allocObject + 38 in [libswiftCore.so](http://libswiftcore.so/)
> 2 [ra]                    0x00007f1559b85571 _allocateStringStorage(codeUnitCapacity:) + 160 in [libswiftCore.so](http://libswiftcore.so/)
> 3 [ra]                    0x00007f1559d03452 _StringGuts.grow(_:) + 273 in [libswiftCore.so](http://libswiftcore.so/)
> 4 [ra]                    0x00007f1559bf7e88 specialized static String._fromUTF8Repairing(_:) + 999 in [libswiftCore.so](http://libswiftcore.so/)
> 5 [ra] [inlined] [system] …
=> Frequent crashes in LLBuildProgressTracker while building swift-java on linux and swift 6.1.2

Sources/_InternalTestSupport/SwiftTesting+Helpers.swift, Sources/_InternalTestSupport/SwiftTesting+Tags.swift, Sources/_InternalTestSupport/SwiftTesting+TraitConditional.swift, Tests/CommandsTests/MermaidPackageSerializerTests.swift, Tests/CommandsTests/PackageRegistryCommandTests.swift, Tests/WorkspaceTests/WorkspaceStateTests.swift
Migrate additional suites to Swift Testing.  Namely `MermaidPackageSerializerTests`, `PackageRegistryCommandTests` and `WorkspaceStateTests`.
Where applicable, augment the test suites to buid against the Native and Swift Build build engines, and to build using the `debug` and `release` configurations.
Depends on #8988
Relates to #8997
=> Tests: Migrate more suites to Swift Testing

Package.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift, Sources/swift-build-prebuilts/build.sh
Removes the hardcoding of the contents of the prebuilt libraries.
Adds a --version argument to specify which versions of swift-syntax you want to build for. You can have multiple of these. We add a sample build.sh script to the folder to show an example, including finding the most recent prerelease of 602.
Also removes the hardcoding of the list of products that go into the library. Instead we ask the package for its list of library products and add them all.
Finally, removes the header files since SwiftPM now hooks up the include paths to the CModules from the source in the checkouts.
=> Add build prebuilts support for any version of swift-syntax.

Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift, Tests/CommandsTests/PackageCommandTests.swift
WMO builds have a single frontend invocation and produce a single diagnostic file named after the module.
Resolves https://github.com/swiftlang/swift-package-manager/issues/9006.
=> SwiftModuleBuildDescription: Fix diagnostic file paths for WMO builds

Tests/PackageGraphTests/ModulesGraphTests.swift
The ModulesGraphTests have been converted to swift-testing, but they still use `testDiagnostics` which will call XCTFail instead of the failing with a swift-testing expectation.
=> Fix testDiagnostics usages in ModulesGraphTests

Sources/PackageManagerDocs/Documentation.docc/SwiftVersionSpecificPackaging.md
applies proofreading fixes to the existing article on version-specific swift packages
Spotted a typo and wanted to resolve it
grammar, punctuation, and typos changes
clearer content
=> proofreading fixes on the version-specific manifests article

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
This will need to be cleaned up later as we refine how target triples are communicated through the build request, but will allow us to start experimenting with more Swift Embedded workflows in the meantime.
=> Add initial support for "none" triples using the Swift Build backend

Sources/Build/LLBuildProgressTracker.swift
(cherry picked from commit 16452e1305d5f635cc714146201ca9753bcfea3f)
Frequent crashes in LLBuildProgressTracker while building swift-java on linux and swift 6.1.2
This was a race condition because the 
Command is associated with a handle (pointer) that may be reclaimed when this function finishes.
Minimal, copy variables into locals before accessing them from async block.
https://github.com/swiftlang/swift-java/issues/314 almost all CI runs fail with this race condition due to the timing of the command being influenced by the gradle build in swift-java.
https://github.com/swiftlang/swift-package-manager/pull/8998
Minimal.  Change explicitly copies variables prior to usage in async block. This avoided a race condition that would manifest before as null pointer crashes when trying to access …
=> [6.1] Frequent crashes in LLBuildProgressTracker while building swift-java on linux and swift 6.1.2

Sources/Workspace/InitPackage.swift, Tests/WorkspaceTests/InitTests.swift
Updated `InitPackage` to handle `.executable` and `.tool` types when generating test files with SwiftTesting. Added corresponding tests to verify correct test file content for these package types.
The `swift package init` command did not generate a `Tests` directory for executable or tool packages when the `--enable-swift-testing` flag was used. This was caused by logic in `Sources/Workspace/InitPackage.swift` that incorrectly skipped test generation for these package types. This change fixes that behavior, ensuring that tests are created as expected.
- In `Sources/Workspace/InitPackage.swift`, the `writeTests()` function was modified to proceed with test generation for `.executable` and `.tool` package types.
- In the same file, the `writeTestFileStubs()` function was updated to include …
=> Fix: Generate tests for executable/tool with `--enable-swift-testing`

Sources/PackageLoading/TargetSourcesBuilder.swift
Libraries should never call print. Emit this diagnostic message to the observability scope instead.
=> Emit "Found unhandled resource" to observability scope

Sources/Commands/Utilities/DependenciesSerializer.swift, Tests/CommandsTests/PackageCommandTests.swift
Adds traits to the output of the show-dependencies command for `--text` and `--json` output.
Exposes the default traits, if any, that are enabled by the dependencies a package.
Resolves: #9033 
Extended the logic in show-dependencies to add in the `enabledTraits` for a resolved package.
The output of show-dependencies includes output akin to `(traits: FirstTrait, SecondTrait)` is the resolved package has traits and includes the traits that it has. If the package doesn't offer traits, no additional/new content is displayed in `--text`.
The JSON provided from `show-dependencies --json` includes a `traits` property, empty if there aren't any traits enabled.
=> adds traits to dependency output in show-dependencies --json and --text

Fixtures/PIFBuilder/UnknownPlatforms/Package.swift, Fixtures/PIFBuilder/UnknownPlatforms/Sources/UnknownPlatforms/UnknownPlatforms.swift, Package.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Sources/SwiftBuildSupport/PackagePIFBuilder.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Products.swift, Tests/SwiftBuildSupportTests/PIFBuilderTests.swift
Some existing packages use `.when(platforms: [.custom("DoesNotExist")])` to unconditionally deactivate settings. Stop asserting on these unknown platforms
=> Drop unknown platforms when generating PIF

Tests/BuildTests/BuildSystemDelegateTests.swift
A test recently started failing as the expected output now contains a file path.  Update the impacted test to be more robust to such a change as SwiftPM does not generate this output.
=> Test: Update test expectation to be more flexible

Package.swift, Sources/Workspace/Workspace+Prebuilts.swift, Sources/swift-build-prebuilts/BuildPrebuilts.swift, Sources/swift-build-prebuilts/build.sh
Cherry pick of #8994 and #9127 to 6.2.1
8994 added the ability to build prebuilts and pass in the swift-syntax versions to build for. This was added to 6.2 after the 6.2.1 branch was created. We should make sure 6.2.1 has the same features in case we want to build the prebuilts from that branch. It also avoids a merge conflict with 9127.
9127 Fixes a bug where if Windows prebuilts built last, the include path to the C shims had backslashes in them instead of slashes. This forces them the other way. That unfortunately breaks the signature on the Windows client so this fixes the client to switch them back after signature verification.
=> 6.2.1 fix prebuilts slashes

Fixtures/ModuleAliasing/DirectDeps2/AppPkg/Package.swift, Sources/PackageGraph/Resolution/ResolvedProduct.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
Ensure the SwiftBuild integratation support the same Module Aliasing feature set as the native build system.
Fixes: #8987
Issue: rdar://157315793
=> SwiftBuild: Support Module aliasing

Sources/Commands/SwiftTestCommand.swift, Sources/PackageModel/SwiftSDKs/SwiftSDK.swift, Tests/PackageModelTests/SwiftSDKTests.swift
`wasmkit` expects executable arguments to be passed after `--` delimiter. Additionally, we need to bridge current directory to the host with the additional `--dir .` option.
Fixed https://github.com/swiftlang/swift-package-manager/issues/9113
rdar://160218251
=> swift test: Fix incorrect `wasmkit` arguments

Fixtures/Traits/Example/Package.swift, Fixtures/Traits/Example/Sources/Example/Example.swift, Fixtures/Traits/Package10/Package.swift, Fixtures/Traits/Package10/Sources/Package10Library2/Library.swift, Fixtures/Traits/PackageConditionalDeps/Package.swift, Fixtures/Traits/PackageConditionalDeps/Sources/PackageConditionalDeps/PackageConditionalDeps.swift, Sources/PackageGraph/ModulesGraph.swift, Sources/PackageGraph/PackageGraphRoot.swift, Sources/PackageGraph/PackageModel+Extensions.swift, Sources/PackageModel/EnabledTraitsMap.swift, Sources/PackageModel/Manifest/Manifest+Traits.swift, Sources/Workspace/Workspace+Manifests.swift, Sources/_InternalTestSupport/MockPackage.swift, Sources/_InternalTestSupport/SwiftTesting+TraitArgumentData.swift, Tests/FunctionalTests/TraitTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift, Tests/PackageModelTests/ManifestTests.swift, Tests/WorkspaceTests/WorkspaceTests.swift
- **Explanation**:
Addresses multiple traits issues:
- Changes the check for trait-guarded target dependencies to determine whether the package dependency from which it derives is used in the parent package; prior to this change, the check was asserting that *all* traits in the `when` condition of a target dependency were enabled for the dependency to be considered unguarded, but now the check confirms that *at least one* trait in the condition is enabled.
- Fixes some errors in trait computation that hadn't considered when default traits ["default"] were being appended to the EnabledTraitsMap, which should only consider a list of flattened traits + explicitly enabled traits by a user/parent package. The inclusion of default in this dictionary was resulting in an inaccurate computation of …
=> [6.2.1] Cherry-pick: Fix traits .when(traits:) condition; pre-computation when loading dependency manifests

Sources/Workspace/InitPackage.swift, Tests/WorkspaceTests/InitTests.swift
When running `swift package init --type executable --enable-swift-testing` an example test is generated but the test target is not created in the manifest.
Add the missing test target to the manifest when these types are initialized with swift-testing tests. This applies to the `tool` and `executable` types.
Packages are initialized with a test target and running `swift test` runs the generated test successfully.
Issue: #9149
=> Add missing `testTarget` for package init swift-testing tests

Sources/PackageManagerDocs/Documentation.docc/AddingDependencies.md
=> Documentation.docc/AddingDependencies.md: fix typo

Tests/IntegrationTests/BasicTests.swift
The test `testExamplePackageDealer` was failing on Amazon Linux and not in Swift.org's CI 
See https://github.com/swiftlang/swift-package-manager/issues/9126
The reason why the test is working on Swift.org's CI is because it silently ignores outbound connection issues.  The test fails to clone the project on github.com and silently stops.
When the clone operation succeed, the test fails. This is the case on macOS and Amazon Linux 2023, probably others OSes too.
I observed multiple problems in this test.
1. the test was not marked `async` and the `withTemporaryDirectory` was not await. The test completed execution before the `git clone` operation finished.
2. The `git clone` operation requires an environment variable `HOME` to be defined
3. On Swift 6.1 and later, the second build …
=> [test] Fix testExamplePackageDealer

Sources/_InternalTestSupport/SwiftTesting+Helpers.swift, Tests/CommandsTests/APIDiffTests.swift
- Add throwing and non-throwing overloads for expectThrowsCommandExecutionError in SwiftTesting+Helpers
- Remove duplicate implementation from APIDiffTests
- Simplify call sites by using appropriate overload without unnecessary `try`s where appropriate
=> [Tests] Consolidate expectThrowsCommandExecutionError usage

Fixtures/PartiallyUnusedDependency/Dep/Package.swift, Fixtures/PartiallyUnusedDependency/Dep/Sources/MyDynamicLibrary/Dep.swift, Fixtures/PartiallyUnusedDependency/Dep/Sources/MySupportExecutable/exe.swift, Fixtures/PartiallyUnusedDependency/Package.swift, Fixtures/PartiallyUnusedDependency/Plugins/dump-artifacts-plugin.swift, Fixtures/PartiallyUnusedDependency/Sources/MyExecutable/PartiallyUnusedDependency.swift, Sources/Build/BuildOperation.swift, Sources/Commands/Utilities/PluginDelegate.swift, Sources/SPMBuildCore/BuildSystem/BuildSystem.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/PackageCommandTests.swift
Depends on https://github.com/swiftlang/swift-build/pull/801
By querying the build system for the artifacts, we ensure we only report any we will actually produce in the current build. At the same time, pull in an alternative fix for https://github.com/swiftlang/swift-package-manager/pull/9121 which restores the original behavior of the native build system when considering products in dependency packages.
=> Use SwiftBuild API to reliably compute built artifacts

Sources/Build/BuildDescription/ProductBuildDescription.swift, Tests/BuildTests/BuildPlanTests.swift
**Explanation**: SwiftPM's native build system does not have the concept of embedding the compatibility libraries for distribution, so add rpaths to the span back deploy library in the toolchain when targeting macOS < 26. 
- **Scope**: Default package rpaths
- **Issues**: https://github.com/swiftlang/swift-package-manager/issues/9163
- **Original PRs**: https://github.com/swiftlang/swift-package-manager/pull/9164
- **Risk**: Low, this change follows an established pattern used by the concurrency back deployment library
- **Testing**: Updated unit tests, manual testing on older macOS versions
- **Reviewers**: @jakepetroules 
---
Original:
SwiftPM's native build system does not have the concept of embedding the compatibility libraries for distribution, so add rpaths to the span back deploy …
=> [6.2.1][native] Add toolchain span back deployment rpaths when required (#9164)

Sources/SwiftBuildSupport/SwiftBuildSystem.swift
This change removes the progress bar from the output generated when we use the SwiftBuild build system in SwiftPM. The progress bar tears and affects the format of the emitted logs and diagnostics.
=> Remove animated progress bar from SwiftBuild output

Sources/Workspace/Workspace.swift
Both `loadPackage` and `loadRootPackage` specified all traits as enabled when loading a package. Narrow this to only the enabled traits so that the returned `Package` accurately reflects the enabled traits.
=> [6.2] Cherry Pick - Use only enabled traits when loading package (#8970)

Sources/PackageModel/ManifestSourceGeneration.swift, Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Use `custom` notation for platform conditions where necessary in manifest code generation
Currently, for platform cases that are known but not yet available, or entirely unknown, the generated code becomes invalid.
Change the implementation so that such cases are expressed using `custom` notation.
Manifest code generation will correctly handle known-but-unavailable and unknown platform conditions by outputting them with `custom` notation.
In practice, `swift-subprocess` includes `.custom("freebsd")` in its manifest.
When this is imported, source code is generated, and then reloaded with SwiftPM, the following error occurs:
```
PackageDescription.Platform.freebsd:3:21: note: 'freebsd' was introduced in PackageDescription 999.0
```
This change prevents such errors by ensuring unsupported or …
=> Use `custom` notation for platform conditions where necessary in manifest code generation

Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/CommandsTests/PackageCommandTests.swift
When building with the swiftbuild build system there can be a compilation problem with the
plugin.swift with one of the plugins. However, you won't discover that unless you run the
command plugin specifically. This is not the behaviour of the existing native build system
that does a plugin pass at the start of a build.
Implement a similar plugin pass with the swiftbuild system to catch problems with the plugin
code when building the packages.
Fixes #8977
=> Compile all of the plugins at the start of a build with swiftbuild

Sources/PackageLoading/ModuleMapGenerator.swift, Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift
- Windows paths need to be escaped
=> fix modulemap generation on window using swift-build

Sources/PackageRegistry/RegistryClient.swift, Tests/PackageRegistryTests/RegistryClientTests.swift
Cherry pick of #9144
In `RegistryClient.swift` there is an in-memory package metadata cache expiration check 
```swift
let cacheKey = MetadataCacheKey(registry: registry, package: package)
if let cached = self.metadataCache[cacheKey], cached.expires < .now() {
return cached.metadata
}
```
The logic for `cached.expires < .now()` appears to be inverted, e.g. if a cache is found for the cacheKey, the initial values look like this `2389992062152` < `2303592072235` which equates to false, because [`cached.expires`](https://github.com/swiftlang/swift-package-manager/blob/18bc4801d1e0aa02ca69633c3c12d5d1135b65bc/Sources/PackageRegistry/RegistryClient.swift#L443) is set with a TTL of [60*60 seconds](https://github.com/swiftlang/swift-package-manager/blob/18bc4801d1e0aa02ca69633c3c12d5d1135b65bc/So …
=> [6.2] Cherry Pick - Fix inverted logic on registry cache expiration #9144

Fixtures/Coverage/Simple/Package.swift, Fixtures/Coverage/Simple/Sources/Simple/Simple.swift, Fixtures/Coverage/Simple/Tests/SimpleTests/SimpleTests.swift, Sources/Commands/SwiftTestCommand.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Sources/_InternalTestSupport/SwiftTesting+TraitsBug.swift, Tests/BasicsTests/FileSystem/PathTests.swift, Tests/BasicsTests/HTTPClientTests.swift, Tests/BuildTests/PluginsBuildPlanTests.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/CoverageTests.swift, Tests/CommandsTests/RunCommandTests.swift, Tests/CommandsTests/Sanitizer+ExtensionsTests.swift, Tests/CommandsTests/TestCommandTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/TraitTests.swift, Tests/IntegrationTests/SwiftPMTests.swift, Tests/PackageGraphTests/ModulesGraphTests.swift
Ensure the SwiftBuild build system has feature parity with the Native build system as it relates to coverage.
Fixes: #9077
Fixes: #9197
Depends on: https://github.com/swiftlang/swift-build/pull/844
Issue: rdar://159461439
=> Add SwiftBuild coverage support

Sources/_InternalTestSupport/SwiftTesting+TraitsBug.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/TraitTests.swift, Tests/IntegrationTests/SwiftPMTests.swift
The change in #8884 fixed the root cause, but did not update all the tests accordingly as some tests unnecessarily contained a `withKnownIssue` block.
Remove the remaining `withKnownIssues` and the defect trait from the test.
Closes: #8416
=> Clean up test traits

Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift, Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift, Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Sources/MyLocalTool/bar.in, Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Sources/MyLocalTool/main.swift, Fixtures/Miscellaneous/Plugins/PrebuildDependsExecutableTarget/Package.swift, Fixtures/Miscellaneous/Plugins/PrebuildDependsExecutableTarget/Plugins/MyPlugin/plugin.swift, Fixtures/Miscellaneous/Plugins/PrebuildDependsExecutableTarget/Sources/MyClient/client.swift, Fixtures/Miscellaneous/Plugins/PrebuildDependsExecutableTarget/Sources/MyExecutable/tool.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftBuildSupport/SwiftBuildSystem.swift, Tests/FunctionalTests/PluginTests.swift
Add prebuild command support for build tool plugins with the swiftbuild build system.
Include a test case that verifies that referring to a tool through context fails in both
major build systems. Test that tools made available through binary artifact dependencies
with an artifact bundle work with both build systems.
=> Prebuild plugin support for swiftbuild build system

Fixtures/Miscellaneous/Plugins/BinaryTargetExePlugin/Dependency/MyBinaryTargetExeArtifactBundle.artifactbundle/info.json, Fixtures/Miscellaneous/Plugins/BinaryTargetExePlugin/Dependency/MyBinaryTargetExeArtifactBundle.artifactbundle/mytool-linux/mytool, Fixtures/Miscellaneous/Plugins/BinaryTargetExePlugin/Dependency/MyBinaryTargetExeArtifactBundle.artifactbundle/mytool-macos/mytool, Fixtures/Miscellaneous/Plugins/BinaryTargetExePlugin/Package.swift, Fixtures/Miscellaneous/Plugins/BinaryTargetExePlugin/Plugins/MyPlugin/plugin.swift, Fixtures/Miscellaneous/Plugins/BinaryTargetExePlugin/Sources/MyPluginExe/main.swift, Sources/SwiftBuildSupport/PackagePIFBuilder+Helpers.swift, Tests/SwiftBuildSupportTests/PIFBuilderTests.swift
Fix a crash when unwrapping an optional 'mainModule' of a module. In the case where a plugin has a dependency on a 'binaryTarget' there is no main module.
This only presents itself when you have defined the binaryTarget as both a product and target.
* Update method that determines plugin dependencies to handle binaryTarget types explicitly.
* Add a PIF generation test that captures this behaviour.
=> Fix crash in PIF generation

Sources/_InternalTestSupport/SwiftTesting+Traits.swift, Tests/CommandsTests/APIDiffTests.swift, Tests/CommandsTests/BuildCommandTests.swift, Tests/CommandsTests/CoverageTests.swift, Tests/CommandsTests/PackageCommandTests.swift, Tests/CommandsTests/PackageRegistryCommandTests.swift, Tests/FunctionalTests/CFamilyTargetTests.swift, Tests/FunctionalTests/DependencyResolutionTests.swift, Tests/FunctionalTests/MacroTests.swift, Tests/FunctionalTests/ModuleAliasingFixtureTests.swift, Tests/FunctionalTests/PluginTests.swift, Tests/FunctionalTests/TestDiscoveryTests.swift, Tests/FunctionalTests/TraitTests.swift, Tests/FunctionalTests/VersionSpecificTests.swift
The Windows self hosted pipeline occassionally has a test hanging.  In order to prevent this from occurring, run some `large` (ie: end-to-end) tests serially on Windows.
=> Tests: Run some test serially on Windows

Fixtures/Miscellaneous/RequiresOlderDeploymentTarget/Foo.swift, Fixtures/Miscellaneous/RequiresOlderDeploymentTarget/Package.swift, Sources/Basics/Triple+Basics.swift, Sources/Commands/PackageCommands/AuditBinaryArtifact.swift, Sources/PackageModel/UserToolchain.swift, Sources/SPMBuildCore/BuildParameters/BuildParameters.swift, Sources/SPMBuildCore/Plugins/DefaultPluginScriptRunner.swift, Sources/SwiftBuildSupport/PIFBuilder.swift, Sources/SwiftSDKCommand/ConfigureSwiftSDK.swift, Sources/SwiftSDKCommand/SwiftSDKSubcommand.swift, Tests/CommandsTests/BuildCommandTests.swift
Default to an unversioned triple if the user hasn't provided one so we don't raise the deployment target to a version the package may not support
closes https://github.com/swiftlang/swift-package-manager/issues/9095
=> [Swift Build] Default to the package's declared deployment target if none is explicitly specified
