Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

Generated Xcode project has an incorrect linkage on an executable.  The Xcode project model does not tie the concepts of dependency and linkage together; this was a problem in the logic that constructed that model.  It unconditionally added a linkage, but should only do so for dependencies on library modules.
Verified that the newly added unit test fails without the fix.

SR-3001: Generated Xcode project has an incorrect linkage on an executable

---

Utilities/bootstrap

Generating xcconfig file post project generation doesn't work now
because we started checking if the file exists.

[bootstrap] Generate xcconfig file before generating the project

---

Package.swift
Sources/TestSupport/misc.swift
Tests/POSIXTests/EnvTests.swift
Tests/UtilityTests/PkgConfigParserTests.swift

To test the correct pkg config file search paths, the environment variables should be changed during the tests. This PR adds functionality to temporary override the environment and should restore the environment afterwards. This will be used by #731 (or its successor) to verify the correct search order. This PR is based upon #743 (setenv / unsetenv).

Test pkg config environment search paths

---

Sources/Commands/SwiftTestTool.swift
Utilities/bootstrap

Related radar: <rdar://problem/27791475>
This patch allows SwiftPM to run tests in release mode with testability enabled. The testable feature is enabled by passing `-Xswiftc -enable-testing` while bootstrapping SwiftPM.
This is only working on macOS as of now. Linux has some compiler failure in XCTest corelibs: https://bugs.swift.org/browse/SR-3034

Make SwiftPM testable in release mode

---

Sources/Commands/Describe.swift
Sources/Commands/SwiftPackageTool.swift
Sources/PackageModel/Module.swift
Sources/TestSupport/JSONExtensions.swift
Sources/Utility/StringExtensions.swift
Tests/CommandsTests/PackageToolTests.swift

This subcommand outputs information about the current package's modules,
including things like source files etc.
```json
{
"modules":[
{
"c99name":"Basic",
"is_test":false,
"module_type":"SwiftModule",
"name":"Basic",
"path":"/Users/ankit/workspace/swift.org/swiftpm/Sources/Basic",
"sources":[
"ByteString.swift",
"CollectionAlgorithms.swift",
"Condition.swift",
"DictionaryExtensions.swift",
"FileSystem.swift",
"FixableError.swift",
"GraphAlgorithms.swift",
"JSON.swift",
"KeyedPair.swift",
"LazyCache.swift",
"Lock.swift",
"OptionParser.swift",
"OrderedSet.swift",
"OutputByteStream.swift",
"Path.swift",
"PathShims.swift",
"Result.swift",
"StringConversions.swift",
"SynchronizedQueue.swift",
"TemporaryFile.swift",
"TerminalController.swift",
"Thread.swift"
],
"type":"library"
},
{ …
```

[PackageTool] Add describe subcommand to swift package

---

Sources/TestSupport/SwiftPMProduct.swift
Sources/TestSupport/XCTAssertHelpers.swift
Tests/FunctionalTests/MiscellaneousTests.swift

This will allow inspecting output if SwiftPM product execution fails.

[TestSupport] Throw error with execution output

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/ConventionTests.swift

Diagnostic about renaming a directory is better than renaming a module.
- <rdar://problem/27890022> Make error message more prescriptive

[PackageBuilder] Emit clearer error message

---

Sources/SourceControl/InMemoryGitRepository.swift
Tests/SourceControlTests/InMemoryGitRepositoryTests.swift
Tests/SourceControlTests/XCTestManifests.swift

This implements a basic in-memory implementation of git. Currently,
It will be useful in workspace tests which uses real filesystem for
git operation. Using in memory implementation makes the tests around
22.5 times faster which means we can test much more number of things
without worrying about the increase in test time. We anyway add
functional tests in all our tools so we will not be losing any test
coverage.

[SourceControl] Add basic in-memory git implementation

---

Sources/Build/Command.link(ClangModule).swift
Tests/BuildTests/DescribeTests.swift

The language link flags was lost at some point and c++ was never being
linked.
- https://bugs.swift.org/browse/SR-3152

[Build] Add language link arguments for clang modules

---

Sources/Get/Range.swift

Now that [SR-1009](https://bugs.swift.org/browse/SR-1009) is resolved, we can remove the FIXME and the extension can constrain to  the concrete `Version` type without using any protocols.

Use concrete constrained extensions to get rid of protocol conformance trick

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

When external packages are present, add a `Dependencies` group, and add modules from the external packages to appropriate directories underneath.  This is just a structure navigator change; there is no change to linkage semantics.  The structure of the groups tries to respect whether the package uses shallow or deep package format, but does not depend on all of the package dependencies ending up inside a `Packages` subdirectory in the source.
This addresses https://bugs.swift.org/browse/SR-3086
The diffs are staged into three separate commits to make them easier to read.

SR-3086: Xcode project generation puts modules from external packages together with local ones

---

Sources/PackageGraph/DependencyResolver.swift
Tests/CommandsTests/WorkspaceTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

- Previously we would fail to resolve any situations that would have required
the resolver to backtrack.
- This commit just switches us to use the naive implementation which enumerates
all possible solutions in a preferred order, and returns the first complete
one. This is simple, but can perform very poorly in situations which
backtrack frequently, as it makes very little attempt to early-exit when
pursuing an infeasible solution, or to cache partial solutions to the
constraint solving problem. OTOH, it is easy! :)
- The one thing the algorithm *does* do is eagerly merge all constraints at the
level of any individual package, before initiating the native recursive
search. The upshot of this is that in the cases of real performance problems
in the backtracking, it should always be …

[DependencyResolver] Implement backtracking support.

---

Documentation/Usage.md

The documentation had gone out of date. Add an example with libgit2 and
update the example of libjpeg with proper instructions.
- <rdar://problem/29229825> Fix documentation and or update for JPEG
module map example

[Documentation] Update system-module documentation

---

Tests/BasicTests/ByteStringPerfTests.swift
Utilities/bootstrap

This flag will enable performance tests in the generated SwiftPM
Xcodeproject using conditional compilation flag 'ENABLE_PERF_TESTS'.

Add a flag to enable performance tests in generated Xcode project

---

Documentation/Usage.md

- https://bugs.swift.org/browse/SR-3115

[Documentation] Add package edit documentation

---

Sources/Commands/SwiftTool.swift
Sources/SourceControl/GitRepository.swift
Sources/Utility/Verbosity.swift
Tests/FunctionalTests/MiscellaneousTests.swift

Switch to using correct system() and popen() methods.
- <rdar://problem/28699965> Warnings when using new resolver

Fix warnings emitted when using the new resolver

---

Sources/Utility/StringMangling.swift
Tests/UtilityTests/StringConversionTests.swift

I believe we are currently too greedy in replacing invalid prefix characters, only the first one needs to be replaced in order to form a valid C99 identifier.

Only replace first invalid prefix character

---

Sources/SourceControl/GitRepository.swift
Tests/SourceControlTests/GitRepositoryTests.swift

git ls-tree lists type as commit and we were assuming type as fixed 4
bytes.
- https://bugs.swift.org/browse/SR-3238

[GitRepository] Add commit case in GitRepository.Tree.Entry.EntryType

---

Tests/FunctionalTests/MiscellaneousTests.swift

https://bugs.swift.org/browse/SR-3122 is fixed

[Tests] Enable the disabled test

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/ConventionTests.swift

We need to check for loose source files if there is atleast one module
inside Sources/ and not when there is exactly one.
Related radar: <rdar://problem/29228963>

[PackageBuilder] Fix a broken logic

---

Sources/TestSupport/MockDependencyResolver.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

This will help in sharing these objects between perf and unit tests

Move some of the dep resolution mock objects to TestSupport

---

Sources/Basic/Path.swift
Sources/Commands/UserToolchain.swift
Tests/CommandsTests/UserToolchainTests.swift

There was wrong assumption that all paths inside PATH are
absolute paths.
- https://bugs.swift.org/browse/SR-3283

[Commands] Fix PATH env parsing

---

Tests/BasicPerformanceTests/ByteStringPerfTests.swift
Tests/BasicPerformanceTests/OutputByteStreamPerfTests.swift
Tests/BasicPerformanceTests/PathPerfTests.swift
Tests/BasicPerformanceTests/StringConversionsPerfTests.swift

These tests are completely disabled, move them under ENABLE_PERF_TESTS
define and to perf test module.

[PerfTests] Move old disabled perf tests to perf test module

---

Sources/Commands/SwiftPackageResolveTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/TestSupport/MockDependencyResolver.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

This will allow specifying the exact requirement of a version, useful in
cases like pinning.
- https://bugs.swift.org/browse/SR-3171

[Resolver] Add unit/singleton set

---

Sources/SourceControl/RepositoryManager.swift
Tests/CommandsTests/WorkspaceTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

After this change lookup() will only 'fetch' repository once per
session.

[RepositoryManager] Update repositories only once per session

---

Tests/CommandsTests/PinsStoreTests.swift

Since pins file might be checked in by clients, this test will make
sure we can parse v1 pins file in case we need to
migrate or add/remove properties.

Add v1 pinsfile test

---

Sources/Utility/StringMangling.swift
Sources/Xcodeproj/pbxproj().swift
Tests/UtilityTests/StringConversionTests.swift

Underscores are illegal in bundle identifiers, so we should post process the C99 identifiers and replace them. Xcode uses dashes, so let's use those, too.

Fix generated `PRODUCT_BUNDLE_IDENTIFIER`

---

Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/Commands/UserToolchain.swift
Sources/Get/Git.swift
Sources/POSIX/popen.swift
Sources/POSIX/system.swift
Sources/SourceControl/GitRepository.swift
Sources/TestSupport/SwiftPMProduct.swift
Sources/TestSupport/XCTAssertHelpers.swift
Sources/TestSupport/misc.swift
Sources/Utility/Git.swift
Sources/Utility/Platform.swift
Sources/Utility/Verbosity.swift
Tests/BuildTests/IncrementalBuildTests.swift
Tests/FunctionalPerformanceTests/BuildPerfTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/XcodeprojTests/FunctionalTests.swift

- <rdar://problem/29462783>
Unless an env is specified, propagate complete env by default.
This is also the default behavior in NSTask API and python's
subprocess

[POSIX] Propagate complete env when lauching subprocess

---

Sources/TestSupport/SwiftPMProduct.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/ClangModuleTests.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleMapTests.swift
Tests/FunctionalTests/ValidLayoutTests.swift
Tests/UtilityTests/ShellTests.swift

This was causing issues when running tests via Xcode
due to NSUnbufferedIO being passed down..

[Tests] popen in tests with empty env

---

Sources/SourceControl/GitRepository.swift
Tests/SourceControlTests/GitRepositoryTests.swift

git remote set-url is better to change the remote URL because removing
the remote and then adding it causes issues when the remote is
referenced in the global git config.
- https://bugs.swift.org/browse/SR-3402

[GitRepository] Prefer set-url instead of adding/removing remotes

---

Sources/PackageGraph/DependencyResolver.swift
Tests/FunctionalTests/VersionSpecificTests.swift

The resolver keeps on looking for a valid solution even when it
encounters an error. I introduced this bug when fixing the lazy
behaviour of resolver.
At the time, I thought this was valid behaviour, see: 79c1de3

[Resolver] Stop computing after encountering error

---

Sources/Basic/Await.swift
Tests/BasicTests/AwaitTests.swift
Tests/BasicTests/XCTestManifests.swift

This is a common pattern used in some of the places, this utility will
avoid the repititive code.

[Basic] Add await() to convert async methods to sync

---

Fixtures/ClangModules/ObjCmacOSPackage/Package.swift
Fixtures/ClangModules/ObjCmacOSPackage/Sources/HelloWorldExample.m
Fixtures/ClangModules/ObjCmacOSPackage/Sources/Include/HelloWorldExample.h
Fixtures/ClangModules/ObjCmacOSPackage/Tests/ObjCmacOSPackageTests/HelloWorldTest.m
Sources/Build/Command.link(ClangModule).swift
Tests/FunctionalTests/ClangModuleTests.swift

This addresses 
https://bugs.swift.org/browse/SR-3413
https://bugs.swift.org/browse/SR-3408
This only works on macOS with the Objective-C XCTest. 
Tested with this. 
https://github.com/masters3d/SwiftPackageManagerSamples/tree/master/ObjC-PackageAcronym
```
Compile AcronymTests AcronymTest.m
Linking AcronymPackageTests
Test Suite 'All tests' started at 2016-12-14 09:57:15.866
Test Suite 'AcronymPackageTests.xctest' started at 2016-12-14 09:57:15.867
Test Suite 'AcronymTest' started at 2016-12-14 09:57:15.867
Test Case '-[AcronymTest testAcronymAbbreviateTest1]' started.
Test Case '-[AcronymTest testAcronymAbbreviateTest1]' passed (0.000 seconds).
Test Case '-[AcronymTest testAcronymAbbreviateTest2]' started.
Test Case '-[AcronymTest testAcronymAbbreviateTest2]' passed (0.000 seconds). …
```

Clang Module XCTest support on macOS

---

Fixtures/DependencyResolution/External/DuplicateModules/Bar/Package.swift
Fixtures/DependencyResolution/External/DuplicateModules/Bar/Sources/Bar/Bar.swift
Fixtures/DependencyResolution/External/DuplicateModules/Bar/Sources/app/main.swift
Fixtures/DependencyResolution/External/DuplicateModules/Foo/Sources/Bar/Bar.swift
Fixtures/DependencyResolution/External/DuplicateModules/Foo/Sources/Biz/Biz.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift

And add unit test instead. This test doesn't need to be functional as we
now have infrastructure to test unit test it.
PS: This test was broken anyway as the Package.swift was empty :(

[Tests] Remove duplicate module functional test

---

Sources/Commands/SwiftBuildTool.swift
Sources/PackageGraph/PackageGraphLoader.swift
Tests/FunctionalTests/MiscellaneousTests.swift

We're already printing empty sources warning from package builder so
this warning isn't needed in package graph loader. The exit() is removed
and we check at tool level if there are no root modules which can be
built.

[PackageGraphLoader] Remove stray exit()

---

Sources/Commands/Error.swift
Sources/PackageLoading/ManifestLoader.swift
Tests/PackageLoadingTests/ManifestTests.swift

Instead of directly printing on stdout/stderr throw any errors
from swift interpreter

[ManifestLoader] Throw any manifest loading errors

---

Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Module.swift
Tests/BuildTests/DescribeTests.swift
Tests/PackageLoadingTests/ModuleDependencyTests.swift
Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
Tests/PackageModelTests/ModuleTests.swift

initializer isn't needed to be throwable anymore.

[PackageModel] Remove throws from Module init

---

Sources/PackageLoading/Module+PkgConfig.swift
Tests/PackageLoadingTests/Inputs/Bar.pc
Tests/PackageLoadingTests/Inputs/Foo.pc
Tests/PackageLoadingTests/PkgConfigTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

The current helper always iterates over the recursive dependencies, this
introduces a method to get pkgconfig flags for one module at a time.
tests coming soon

[PkgConfig] Add simplified pkgConfig support

---

Sources/Basic/ObjectIdentifierProtocol.swift
Tests/BasicTests/ObjectIdentifierProtocolTests.swift
Tests/BasicTests/XCTestManifests.swift

This protocol implements Hashable based on ObjectIdentifier so classes
can auto conform to it, avoiding boilerplate code.

[Basic] Add ObjectIdentifierProtocol

---

Tests/UtilityTests/ProcessTests.swift

This is more deterministic than using getpgid() for linux.

[ProcessTests] Use ps -p to check if subprocess is running

---

Sources/Build/misc.swift
Tests/BuildTests/DescribeTests.swift

-lc++ doesn't work on linux where as -lstdc++ works on both platforms.

[Build] Use -lstdc++ instead of -lc++

---

Sources/Commands/SwiftPackageResolveTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/TestSupport/MockDependencyResolver.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift

Since we need resolver to give us more information about the binding,
make BoundVersion enum public and return that in resolver result instead
of just version.

[Resolver] Return return as container and binding

---

Sources/Build/Command.link(SwiftModule).swift
Sources/PackageLoading/ModuleMapGenerator.swift
Tests/BuildTests/DescribeTests.swift
Tests/PackageLoadingTests/ModuleMapGenerationTests.swift

This will get rid of current autolinking for linking Clang modules in
Swift modules. This will help when the product proposal is implemented, i.e.
when we statically link ClangModules we won't need to create .a files.
This also means that all users using a custom modulemap will need to
remove the link statement from their modulemap.
- <rdar://problem/30016942> Link C language libraries via Build instead
of using autolinking via modulemaps

[Build] Manually link ClangModules in Swift products

---

Sources/Xcodeproj/XcodeProjectModel.swift
Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

Some frameworks are contains ObjC target. And these are almost requires ARC.

[Xcodeproj] Add "CLANG_ENABLE_OBJC_ARC = YES" as default

---

Fixtures/ClangModules/SwiftCMixed2/Package.swift
Fixtures/ClangModules/SwiftCMixed2/Sources/SeaExec/main.swift
Fixtures/ClangModules/SwiftCMixed2/Sources/SwiftLib/lib.swift
Sources/Build/Command.link(SwiftModule).swift
Tests/BuildTests/DescribeTests.swift

CLibrary
↑
SwiftLibrary
↑
SwiftExe
The above graph resulted in undefined symbols because SwiftExe never
linked with the CLibrary.

[Build] Fix for linking C targets recursive dependencies

---

Sources/Workspace/Workspace.swift

We don't actually use the payload. We might want to have a payload which
can represent version as well as git hashes in future but no payload
should work for now.

[Workspace] Remove version payload from unchanged case

---

Tests/FunctionalTests/MiscellaneousTests.swift
Tests/XcodeprojTests/FunctionalTests.swift

This removes the dependency on dylib being created by swift build
invocation.

[Tests] Create a dylib by hand instead of depending on SwiftPM

---

Fixtures/Products/DynamicLibrary/Package.swift
Fixtures/Products/StaticLibrary/Package.swift
Package.swift
Sources/PackageDescription/Package.swift
Sources/PackageDescription/Product.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest.swift
Sources/PackageModel/Product.swift
Tests/PackageLoadingTests/ConventionTests.swift
Tests/PackageLoadingTests/JSONSerializationTests.swift
Tests/PackageLoadingTests/ManifestTests.swift
Utilities/bootstrap

This API was removed when implementing the product proposal but is being
restored to keep compatibility with current Swift 3 packages. The new
API will be introduced in the PackageDescription4 module.

[PackageDescription] Restore the old product API

---

Sources/Build/Command.link(SwiftModule).swift
Tests/BuildTests/DescribeTests.swift

Missed adding -l in test products when we switched to manually adding
the link flags instead of generating the link directive in modulemap.
Fixes: https://bugs.swift.org/browse/SR-3816

[Build] Add link argument for C dependencies in test products

---

Fixtures/Miscellaneous/MissingDependency/Bar/Package.swift
Fixtures/Miscellaneous/MissingDependency/Bar/main.swift
Sources/Commands/Error.swift
Sources/SourceControl/GitRepository.swift
Tests/FunctionalTests/MiscellaneousTests.swift

- resolves https://bugs.swift.org/browse/SR-3275
- handing through process result utf8output to error for more informative string result
- adds functional test fixture that will intentionally fail
- adds test to validate error from underlying git is propogated on failure
- adds Error capture for tool commands to handle pretty-print of output

improving failure output per SR-3275

---

Sources/Xcodeproj/generate().swift
Tests/XcodeprojTests/FunctionalTests.swift

I broke this when rolling test property on modules to module type enum.

[Xcodeproj] Generate Info.plist for library and test modules

---

Sources/Build/BuildPlan.swift
Sources/Build/llbuild.swift
Sources/Commands/SwiftTestTool.swift
Sources/PackageGraph/PackageGraph.swift
Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/ResolvedModels.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/ConventionTests.swift
Tests/PackageLoadingTests/ManifestTests.swift
Tests/PackageModelTests/ModuleTests.swift

Instead of creating target dependency for each external target, allow
targets to have a product dependency. We implicitly create products for
each external package containing all library modules and then establish
a dependency. This will be more explicit in Swift 4 manifest.

[PackageModel] Add product dependencies

---

Utilities/bootstrap

- This fixes non-null builds when using the SwiftPM build as part of another
build script.
- <rdar://problem/30450144> SwiftPM is always rebuilding

[bootstrap] Don't copy unnecessarily.

---

Package.swift
Sources/TestSupport/XCTestCasePerf.swift
Tests/BasicPerformanceTests/ByteStringPerfTests.swift
Tests/BasicPerformanceTests/OutputByteStreamPerfTests.swift
Tests/BasicPerformanceTests/PathPerfTests.swift
Tests/BasicPerformanceTests/StringConversionsPerfTests.swift
Tests/FunctionalPerformanceTests/BuildPerfTests.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift

They will still run only when ENABLE_PERF_TESTS is defined.

[PerfTests] Add workaround to always build the perf tests

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

Fix https://bugs.swift.org/browse/SR-3913

[Xcodeproj] Add "@loader_path/Frameworks" to `LD_RUNPATH_SEARCH_PATHS` in test target

---

Sources/SourceControl/GitRepository.swift
Sources/Utility/ProcessSet.swift
Tests/UtilityTests/ProcessSetTests.swift

Clients are no longer required to call remove on a process set.

[Utility] Cleaned up api for ProcessSet.

---

Sources/Basic/JSON.swift
Tests/BasicTests/JSONTests.swift

The `Package.pins` file is currently written without a newline character
on the last line.
Make it a proper text file by appending one `\n` to the `ByteString`
which is generated from the JSON.

[Basic] Add trailing newline to pretty-printed JSON

---

Package.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Workspace/InitPackage.swift
Sources/Workspace/ToolsVersionWriter.swift
Tests/CommandsTests/XCTestManifests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/WorkspaceTests/InitTests.swift
Tests/WorkspaceTests/ToolsVersionWriterTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This pull request is motivated by the ongoing hoisting of functionality that may be of use to clients other than the command line tools into the SwiftPM library.
The main change here is to move the InitPackage class from the Commands module to the Workspace module so it will be included in the library. This required also moving the new ToolsVersionWriter. Some tests were migrated as well, and a new test suite was added to test the InitPackage class directly as part of WorkspaceTests in addition to the command-line based tests in CommandsTests for package creation.
The pull request is split into two commits. The first moves all the functional code and the second moves and adds tests.

Init package refactor

---

Sources/Commands/Error.swift
Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/PackageGraph.swift
Sources/PackageGraph/PackageGraphLoader.swift
Sources/TestSupport/misc.swift
Sources/Workspace/Workspace.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Tests/XcodeprojTests/PackageGraphTests.swift

This will continue loading all root manifests even if one of them fail
to load.

[Workspace] Don't abort loading graph on first error

---

Sources/PackageGraph/PackageGraphLoader.swift

The flatMap works because of the implicit optional promotion, but is
entirely not necessary, and can be replaced with a simple map.

Replacing unnecessary flatMap with a map

---

Sources/Build/BuildPlan.swift
Sources/PackageDescription/Package.swift
Sources/PackageDescription4/Package.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/PackageLoading/PackageDescriptionLoader.swift
Sources/PackageModel/Manifest.swift
Sources/PackageModel/Module.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/PackageLoadingTests/ConventionTests.swift
Tests/PackageLoadingTests/ManifestTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift

This was incorrectly named.
- https://bugs.swift.org/browse/SR-4125

Rename compatibleSwiftVersions to swiftLanguageVersions

---

Sources/Utility/ArgumentParser.swift
Tests/CommandsTests/BuildToolTests.swift

We now support -h, -help and --help to print usage.
- https://bugs.swift.org/browse/SR-4121

[Utility] Add -help option to print usage

---

Sources/PackageLoading/PackageBuilder.swift
Sources/Utility/PkgConfig.swift
Sources/Utility/StringExtensions.swift
Sources/Utility/misc.swift
Sources/swiftpm-xctest-helper/main.swift

It is possible that at some point in future substring will be a separate type. This changes are not strictly necessary at the moment, but make the package manager codebase future-proof.
In short, it's just a bunch of calls to `String.init(_:String)` which are highly likely to be optimized away and not have any runtime impact whatsoever.

Explicit handling of substrings

---

Sources/PackageLoading/ToolsVersionLoader.swift
Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift

Previously we only considered misspellings if we at least matched
'// swift-tools-version:', with this change we will consider a tools
version comment a misspelling if the first line starts with // and
contains the string 'swift-tools-version' (but doesn't match our regex).
- https://bugs.swift.org/browse/SR-4134

Try to diagnose more misspellings of the swift-tools-version comment

---

Sources/Basic/NSRegularExpressionShim.swift
Sources/PackageLoading/ToolsVersionLoader.swift
Sources/PackageModel/ToolsVersion.swift
Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift
Tests/PackageModelTests/ToolsVersionTests.swift
Tests/WorkspaceTests/ToolsVersionWriterTests.swift

This will make tools version accept prerelease and build identifier i.e.
tools version can be formed using a valid semver 2.0 string. However we
will ignore these extra information right now, and only consider the
major, minor and patch part of the versions. For e.g.:
|Input| Interpreted Version|
|-----| -------------------|
|3.0.0                    |         3.0.0|
3.1.0-dev             |          3.1.0|
|3.1-dev+sha.123|           3.1.0|
- https://bugs.swift.org/browse/SR-4129

Accept prerelease and build identifier in tools version

---

Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Utility/ArgumentParser.swift
Sources/Utility/ArgumentParserShellCompletion.swift
Tests/UtilityTests/ArgumentParserTests.swift

This is in addition to the work done in [PR#703][1]. The status of this PR is WIP and pushed to get feedback from the maintainers.
I've made a few changes to the public API of ArgumentParser to get all the meta data required to generate the scripts, as well as the descriptions that zsh shows. For the SwiftPM tools, this means no duplication of the arguments anymore inside SwiftPM.
Things left to tackle:
Not handled in this PR, requires further discussion:
* Compiler flags are still duplicated; should we add some sort of "discovery" based on the output of `swift -h`? -- What to do with flags we cannot handle (nicely), like `-l<name>`?
* How to include this in the toolchain?
* How to generate the full completion script, including setup code? (see `_swift` functions in the current scripts …

Generate shell completion scripts

---

Sources/SourceControl/GitRepository.swift
Sources/Utility/Git.swift

This will make git error out when it needs user/pass input.
This isn't ideal because we should be able to accept these inputs from
swift tools but it is better than just hanging which happens currently.
See https://bugs.swift.org/browse/SR-3981

[SourceControl] Set GIT_TERMINAL_PROMPT=0 when launching git

---

Sources/Commands/SwiftTestTool.swift
Sources/Commands/UserToolchain.swift
Sources/TestSupport/Resources.swift

This might mean we will fail to run test when SDK is not present but
swift build will still work.
- <rdar://problem/30813768>

[Commands] Add sdk platform path only if its present

---

Sources/Commands/UserToolchain.swift
Sources/Utility/misc.swift
Tests/UtilityTests/miscTests.swift

- resolved several FIXME with isExecutableFile checks
- added a directory check for the SDK
- updated variable names to better represent what was being passed
- updated corresponding tests
changes pulled out from https://github.com/apple/swift-package-manager/pull/994 into their own PR

expanding guards in UserToolchain

---

Sources/Utility/Process.swift
Tests/UtilityTests/ProcessTests.swift

- created enum with new error set for Process prior to a result being
created
- guards to validate that at least one argument is provided, and that
it isn't an empty string
- corresponding tests to validate

adding guards for missing inputs into Process

---

Sources/Xcodeproj/XcodeProjectModel.swift
Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift
Tests/XcodeprojTests/XcodeProjectModelTests.swift

This adds to the Xcode project generation logic so that, after adding all the targets for the modules in a package and its dependencies, it also adds an aggregate target for each of the products that doesn’t already have a target with the same name.  This makes it possible to build all the modules that go into a defined product in a single build in Xcode.
As for the implementation: I am on the fence about whether it's most appropriate to say that an aggregate target has no product type (i.e. to make the product type optional) or whether to say that there is a new product type called "none".  The former feels to be a philosophically better fit, and is what diffs show.  If there is a lot of feedback that the other way is better, then we could certainly implement it that way instead.

SR-4083 Generated projects should have an aggregate target for every product that doesn't have any other target

---

Sources/Basic/DiagnosticsEngine.swift
Tests/BasicTests/DiagnosticsEngineTests.swift
Tests/BasicTests/XCTestManifests.swift

This is a basic diagnostic engine which will be used to emit warnings
and errors in a more structured manner so it can be rendered in fancy
ways by different clients.

[Basic] Add DiagnosticsEngine

---

Sources/Basic/JSONMapper.swift
Tests/BasicTests/JSONMapperTests.swift
Tests/BasicTests/XCTestManifests.swift

This will help us remove a lot of boilerplate when mapping json to model
objects.

[Basic] Add a basic JSON mapper

---

Sources/Commands/SwiftTool.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

-- <rdar://problem/30953155> Should always be able to instantiate a
Workspace (its initializer shouldn't throw)

[Workspace] Make workspace init non throwing

---

Sources/Commands/Error.swift
Sources/Utility/Process.swift
Sources/Utility/misc.swift
Tests/UtilityTests/ProcessTests.swift
Tests/UtilityTests/miscTests.swift

Following on from earlier PR (https://github.com/apple/swift-package-manager/pull/921) and bug SR-3275 - adding in the mechanisms to support the extra guard logic for validating that an executable file (i.e. git, etc) exists, and making the results when it doesn't exist more consistent across all the various underlying toolchains.
Here for visibility and feedback...
Next steps:

Extra process guards

---

Sources/Basic/DiagnosticsEngine.swift
Sources/Utility/Diagnostics.swift
Sources/Workspace/Diagnostics.swift

This protocol will let us convert and dynamically emit native
Swift.Errors as DiagnosticData.
Swift.Error types can conform to this protocol and return a
DiagnosticData object.

Add DiagnosticDataConvertible protocol

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/ConventionTests.swift

This removes the implicitly added dependency for a test target 'FooTests' to a
target 'Foo' for v4 manifests.

[PackageBuilder] Remove implicit test target dependency

---

Sources/Build/BuildPlan.swift

This strips the -wmo flag from link command if it was manually passed
during swift build invocation. It causes compilation failure right now.
We might not want to keep this long term once compiler strips the flag
itself so this is workaround for now. Having wmo in debug mode is a
valid use-case which we plan to properly support using build settings in
future.
-- <rdar://problem/30985305>

[BuildPlan] Strip invalid flags from link command

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/Workspace/Workspace.swift
Tests/PackageLoadingTests/ConventionTests.swift

Clients can set createMultipleTestProducts to true to get one test
product per test target.
-- <rdar://problem/30913360>

[PackageLoading] Add option to create multiple test products

---

Sources/Commands/SwiftBuildTool.swift

- adds usage to expose `--build-tests` to `swift build -h`
- resolves [SR-4327](https://bugs.swift.org/browse/SR-4327)

[SR-4327] adding usage to swift-build CLI for --build-tests

---

Sources/Basic/Await.swift
Sources/Basic/DiagnosticsEngine.swift
Sources/Basic/GraphAlgorithms.swift
Sources/Basic/KeyedPair.swift
Sources/PackageGraph/DependencyResolver.swift

A new version of the compiler probably generated a new warning when generic type protocol conformance constraints are redundant. Example:
```
func foo<T,E : Error>(r: Result<T,E>) { }
//             ^ Error is redundant because Result already declares that conformance
```

Fix new redundant conformance constraint warnings

---

Tests/PackageGraphTests/DependencyResolverTests.swift

I forgot to fix the new redundant conformance warning in test targets. It is now done.

Fix redundant conformance warning in test targets

---

Sources/Basic/TemporaryFile.swift
Sources/Basic/Thread.swift
Sources/Build/BuildPlan.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/Module+PkgConfig.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/Workspace/PinsStore.swift
Sources/Workspace/Workspace.swift
Sources/Xcodeproj/generate().swift
Sources/Xcodeproj/xcscheme().swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageLoadingTests/ConventionTests.swift
Tests/PackageLoadingTests/PkgConfigTests.swift
Tests/UtilityTests/ArgumentParserTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift

I renamed boolean properties to follow the guideline: “Uses of Boolean methods and properties should read as assertions about the receiver when the use is nonmutating, e.g. x.isEmpty, line1.intersects(line2).”
I followed a convention of naming Option properties with should (ex: `shouldPrintVersion`) for clarity.

Rename boolean properties to follow guidelines

---

Sources/TestSupport/misc.swift

Makes it easier to copy/paste the generated path in the terminal without confusing bash.

Removed special characters from the mktmpdir

---

Sources/PackageLoading/ManifestLoader.swift

We don't need mach* and it is very unsecure because it allows
communication to processes like nsurlsessiond.
-- <rdar://problem/31213658>

[ManifestLoader] Further restrict the sandbox profile

---

Tests/FunctionalTests/ClangModuleTests.swift
Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift

It looks like a simple case of out of date ModuleCache. These tests shouldn't
fail unless the cache is still outdated, in which case we should purge it from
the CI machine.
-- https://bugs.swift.org/browse/SR-4419

[Tests] Re-enable the two disabled tests causing CI failure

---

Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift

As a way to encourage people to document their packages, start new packages off with a skeletal README.md.
Extend the tests too validate this. (I also tweaked the library test to do the same kind of manifest content validation that the executable test was already doing so that these two primary package types have the same level of validation.)

Make package initialization create a default README.md

---

Sources/SourceControl/RepositoryManager.swift
Sources/TestSupport/XCTAssertHelpers.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

Callbacks on a concurrent queue caused test failures sometimes because the
delegate block was not guaranteed to be dispatched before the completion block.
Moving this to a serial queue resolves the issue, however this also means that
recursive lookups are not possible.
-- - https://bugs.swift.org/browse/SR-4496

[RepositoryManager] Dispatch callbacks on a serial queue

---

Sources/Commands/SwiftPackageTool.swift
Sources/Utility/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Made Workspace.clean non-throwing and accept a `DiagnosticsEngine`.
While doing so, I found it quite useful to define a `wrap` method on `DiagnosticsEngine` that allows us to wrap a throwing function into a Optional returning function, feeding the engine on error. It’s a more generally useful version of `LoadableResult.load(diagnostics:)`, so took the liberty to remove that function.

Migrate Workspace.clean to the diagnostics system

---

Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

Take out PackageBuilderV4Tests from PackageBuilderTests so we can test the two
convention system separately.

[PackageLoadingTests] Add PackageBuilderV4Tests

---

Sources/Utility/Diagnostics.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This change is required for future improvements to the Workspace support of the DiagnosticsEngine.

Rewrite Workspace errors as DiagnosticData structs

---

Sources/Commands/SwiftTool.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

-- <rdar://problem/31573326> Workspace should have a method that returns PackageGraph + mapping of ResolvePackage -> ManagedDependency

[Workspace] Add loadGraphData() method

---

Sources/TestSupport/XCTestCasePerf.swift

[TestSupport] Use XCTestSuite(name:) instead of XCTestSuite()

---

Sources/Commands/SwiftPackageTool.swift
Sources/Utility/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Added an override of `DiagnosticsEngine.wrap` that helps wrapping Void returning throwing closures.

Migrate Workspace reset & edit to use diagnostics

---

Sources/Workspace/Workspace.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

-- <rdar://problem/31286403> Unedited Swift package sources should be read-only

[Workspace] Make non-editable checkouts immutable

---

Package.swift
Utilities/bootstrap

-- <rdar://problem/31685673>
Since Swift compiler needs to see the public interface of every imported target,
we need to copy the include directory of C targets into the libSwiftPM install
directory.

[Bootstrap] Copy headers of C targets in libSwiftPM install directory

---

Sources/Build/BuildPlan.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Module.swift
Sources/PackageModel/Product.swift
Sources/PackageModel/ResolvedModels.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift
Tests/XcodeprojTests/FunctionalTests.swift

XCTest on linux doesn't support dynamic test discovery and requires the list of
test cases in order to run them. The Package Manager allows declaring the test
cases using `LinuxMain.swift` file. This file is expected to be found in Tests
directory, but with custom target layouts feature, it is possible to relocate
the test targets. To handle this, expand the rule for finding `LinuxMain.swift`.
The new rule searchs for `LinuxMain.swift` adjacent to any test target,
iterating upto the package root. It is an error to have multiple
`LinuxMain.swift` files.
-- <rdar://problem/31585721> Figure out how to handle LinuxMain with custom targets layout

[PackageBuilder] Add new search rules for linux main file

---

Utilities/build_ubuntu_cross_compilation_toolchain

To cross compile a binary, you will need a cross compilation toolchain which consists of the toolchain itself and an SDK. For example compiling an iPhone binary from your Mac will use `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk` or similar. If you want to compile a Swift binary for say Ubuntu Xenial on your Mac, you'll need the following pieces of software
- a compiler being able to cross compile ✅ (`swiftc` and `clang` are able to do that)
- the basic Swift libraries (like `libswiftCore`) for Ubuntu ✅ (that's part of the Swift distribution for Ubuntu)
- an SDK for Ubuntu Linux ✅ (that can be assembled from the `.deb` packages available from Ubuntu)
- an ELF linker that runs on macOS ✅ (the [gold …

add script to build Ubuntu cross compilation toolchain

---

Sources/PackageModel/Module.swift

-- <rdar://problem/31725795> Compile LinuxMain.swift with same swift version as the test targets it contains

[PackageModel] Use correct swiftVersion for linux main targets

---

Sources/Build/BuildPlan.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/TestSupport/FileSystemExtensions.swift
Sources/TestSupport/GitRepositoryExtensions.swift
Tests/WorkspaceTests/WorkspaceTests.swift

I am not sure why this was done in the first place. This causes issues when
local packages are symlink.
-- <rdar://problem/30119928> Handle /tmp paths being normalized into
/private/tmp on macOS

[PackageLoading] Do not call realpath() the base URLs

---

Sources/Commands/SwiftPackageResolveTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/TestSupport/MockDependencyResolver.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift

This gives us a performance boost when we are iterating versions because we
don't need to parse the tools version of versions who will always be rejected
anyway.
-- <rdar://problem/31652875> Turn PackageContainer's versions property into a method which accepts a filter closure

[Resolver] Add option to pre-filter the container versions

---

Utilities/build_ubuntu_cross_compilation_toolchain

apologies, forgot to add the `-tools-directory` flag which would result in the toolchain only working if `ld.gold` is in your `$PATH` (which is unlikely).

add tools-directory to Ubuntu cross toolchain builder

---

Sources/Basic/DiagnosticsEngine.swift
Sources/Commands/Error.swift
Sources/Utility/Diagnostics.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift

This adds path of the package to the diagnostics of manifest parse errors for
the manifests loaded inside workspace, which includes root and the edited
manifests.
Part of <rdar://problem/31342256> SwiftPM diagnostics should have proper location where possible

[Workspace] Add diagnostics location for manifests loaded by workspace

---

Sources/Workspace/InitPackage.swift

workaround for <rdar://problem/31725325> Swift compiler does not infer XCTest related types in -swift-version 4

[Workspace] Fix package init

---

Sources/Commands/SwiftTool.swift
Sources/Commands/UserToolchain.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/TestSupport/Resources.swift

Also separate out manifest resource provider from user toolchain.

[PackageLoading] Allow passing -sdk to compiler when parsing manifest

---

Sources/Build/BuildPlan.swift
Sources/Build/Toolchain.swift
Sources/Commands/Destination.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/Commands/UserToolchain.swift
Sources/PackageModel/Product.swift
Sources/TestSupport/Resources.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/XcodeprojTests/FunctionalTests.swift
Utilities/build_ubuntu_cross_compilation_toolchain

This adds _experimental_ support for cross compilation or more precisely configurable destinations for binaries to SwiftPM. The basic idea is that you hand a JSON file in the format described below to SwiftPM (ie. `swift build --destination my-destination.json`). SwiftPM will then invoke the `swiftc`/`clang` with the appropriate arguments. The `--destination` switch is optional and if omitted SwiftPM will use the destination as appropriate for the host OS as it previously did.
{
"version": 1,
"sdk": <path to the SDK for the target platform: String>,
"toolchain-bin-dir": <path to the toolchain's bin dir: String>,
"target": <LLVM target triple: String>,
"extra-cc-flags": <extra C compiler arguments: [String]>,
"extra-swiftc-flags": <extra Swift compiler arguments: [String]>, …

cross compilation support (configurable destinations)

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift

-- <rdar://problem/31814079> Target path is able to specify target above the directory containing package manifest

[PackageLoading] Don't allow targets to be outside the package root

---

Sources/SourceControl/RepositoryManager.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

This property doesn't work well when the RepositoryManager object is long lived.
There could be updates published to a dependency and we won't fetch it until
RepositoryManager is recreated.

[SourceControl] Remove "needsFetch" from RepositoryManager

---

Utilities/bootstrap

swiftc is a symlink to swift, but the program name is significant to
the Swift driver. If realpath ends up picking "swift", turn it back
into "swiftc". This makes SWIFT_EXEC usable with the bootstrap script.

[Bootstrap] Fix SWIFT_EXEC so it builds with "swiftc" rather than "swift"

---

Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/Manifest.swift
Sources/Workspace/Workspace.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

-- <rdar://problem/31858267> libSwiftPM should expose a way to get manifest interpreter flags

Expose a way to get manifest interpreter flags

---

Sources/Commands/SwiftPackageTool.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Simplify the `Workspace.pinAll` API to only require a `WorkspaceRoot` instead of the pinsStore and the dependencies.

Simplify the Workspace.pinAll API

---

Sources/Basic/Process.swift

-- <rdar://problem/31889690> Sandbox makes command line build failures unreadable

[Process] Make logs pretty again

---

Sources/Workspace/Workspace.swift

The old `WorkspaceError` enum is not used anymore.

Remove old Workspace errors

---

Sources/Basic/ByteString.swift
Sources/Basic/JSON.swift
Sources/Basic/Path.swift
Sources/PackageDescription/Package.swift
Sources/PackageDescription/Target.swift
Sources/PackageDescription/Version.swift
Sources/PackageDescription4/Version.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageModel/Package.swift
Sources/SourceControl/Repository.swift
Sources/TestSupport/MockManifestLoader.swift

Fix small inconsistency when using operators required by Protocol outside of the adopter’s scope

Fix inconsistency when using operators outside of the scope

---

Sources/Xcodeproj/generate().swift

Doing this so this scheme name doesn't collide with autocreated schemes in case
name of a target or product is same as name of the package.

[Xcodeproj] Add suffix -Package to default scheme name

---

Sources/Commands/Destination.swift

I'm no expert but this seems to better correspond to the documentation for targe triples.

Fix linux clang/LLVM target triple

---

Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/TestSupport/misc.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/ClangModuleTests.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleMapTests.swift
Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/FunctionalTests/ValidLayoutTests.swift
Tests/WorkspaceTests/InitTests.swift
Tests/XcodeprojTests/FunctionalTests.swift
Utilities/bootstrap

Reverts apple/swift-package-manager#1181
This is causing perf and unit test failures when running from Xcode project. Reverting for now.

Revert "Segregate builds into target platform sub-folders"

---

Sources/Basic/OutputByteStream.swift

-- <rdar://problem/31777022> Redundant same-type constraints in swiftpm

[Basic] Remove same type constraints

---

Sources/Commands/Options.swift
Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift

Will improve later work on `swift run` and build folder target segregation.

Refactor SwiftTool building to accept a buildPlan

---

Sources/Commands/Destination.swift
Sources/Commands/SwiftTool.swift

- This fixes the host destination binary path resolution when the tool is used
with -C.
- https://bugs.swift.org/browse/SR-4910

[Commands] Fix host destination resolution w.r.t. relative launch path.

---

Sources/Xcodeproj/XcodeProjectModel.swift
Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Sources/Xcodeproj/pbxproj().swift

- Objects where can be referenced across projects should have stable IDs,
because Xcode will embed the references to these targets by their ID. We want
those references to remain stable even as the project evolves under
regeneration.
- <rdar://problem/31019219> Generated .xcodeproj needs to use stable object IDs

[Xcodeproj] Assign stable object IDs to critical objects.

---

Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Solves https://bugs.swift.org/browse/SR-3689 
This PR persists the editable package state in the `managedDependecies` even when the package no longer exist in manifest.

[SR-3689] Persist editable package state when the package is not in Manifest

---

Sources/Basic/SortedArray.swift
Tests/BasicPerformanceTests/SortedArrayPerfTests.swift
Tests/BasicTests/SortedArrayTests.swift

Uses the equivalent of a single pass of a merge-sort to make the `SortedArray.insert(contentsOf:)` more efficient.
This allows the algorithm to go from `O((a+b) log(a+b))` to `O(a + b log (b))`. Where `a` is the size of the current array, and `b` is the size of the new elements. If `b` is already sorted (i.e. another `SortedArray`) then an efficient `sort` function will mean this runs in `O(a + b)`.
The new performance tests should demonstrate the improvements when compared, assuming the element count is suitably large:
> testPerformanceOfSortedArrayInsertWithDuplicates()
> testPerformanceOfSortedArrayInsertContentsOfWithDuplicates()
**Note** I needed to add `-swift-version 3` to `Other Swift Flags`
**Note** Insertion times are negligible for a `magnitude` of less than 1000. Performance …

More efficient SortedArray.insert(contentsOf:)

---

Sources/Basic/OutputByteStream.swift
Tests/BasicTests/OutputByteStreamTests.swift

-- <rdar://problem/32315728> Make stdoutStream and stderrStream thread safe
(cherry picked from commit fad2d4648f6292c9a16d6ce6517084a326b54c26)
-- <rdar://problem/32315972> swift-4.0-branch: Make stdoutStream and stderrStream thread safe

[Basic] Make OutputByteStream thread safe

---

Sources/Basic/SortedArray.swift

@ddunbar we missed some indices before https://github.com/apple/swift-package-manager/pull/1190 was merged, I think the code is sound without this, but it is more consistent :)

Consistent indices in SortedArray.insert(contentsOf:)

---

Sources/SourceControl/GitRepository.swift
Tests/SourceControlTests/GitRepositoryTests.swift

> **SR-2815**: GitRepository.hasUnpushedCommits() can not detect commits made when on a detached head
> The current method used to detect unpushed commits doesn't work if the commit was made from a detached head.
Closes [SR-2815](https://bugs.swift.org/browse/SR-2815).

FIX: hasUnpushedCommits for detatched HEAD

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift

Reverts apple/swift-package-manager#1205
Unfortunately there is a non-deterministic test failure on linux.
https://ci.swift.org/job/swift-PR-Linux-smoke-test/8102/console
https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_10/3821/
```
Test Suite 'Selected tests' started at 2017-05-22 20:54:56.411
Test Suite 'PackageToolTests' started at 2017-05-22 20:54:56.412
Test Case 'PackageToolTests.testUpdate' started at 2017-05-22 20:54:56.414
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swiftpm/Tests/CommandsTests/PackageToolTests.swift:75: error: PackageToolTests.testUpdate : XCTAssertEqual failed: ("["1.2.3"]") is not equal to ("["1.2.3", "1.2.4"]") - 
Test Case 'PackageToolTests.testUpdate' failed (1.032 seconds)
Test Suite 'PackageToolTests' failed …
```

"Revert "[Resolver] Turn on parallel cloning by default""

---

Sources/PackageGraph/DependencyResolver.swift
Sources/TestSupport/misc.swift
Sources/Utility/Version.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ValidLayoutTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
Tests/UtilityTests/VersionTests.swift

-- <rdar://problem/31214600> Allow picking prerelease tags only when there is a prerelease in the version range
-- https://bugs.swift.org/browse/SR-1039

[PackageGraph] Fix prerelease resolution behaviour

---

Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftTool.swift
Sources/Utility/ArgumentParser.swift
Tests/UtilityTests/ArgumentParserTests.swift

Here is a list of modifications:
* Created `ParserOptionArgument` and `ParserPositionArgument` structs so that `ArgumentParser` can store additional settings about arguments.
* The `ParsingStrategy` setting allows `ArgumentParser` to store the number of values a multiple-value option or positional argument is expecting:
* `one`: for values which needs to be parsed one-by-one (i.e., `-Xcc`)
* `multiple`: for values which parse until a non-positional argument
* `remainder`: for values which will parse all remaining arguments
* Simplified `ArgumentKind` with default implementations of the parser initializer.

Add multiple-value arguments to ArgumentParser

---

Sources/Commands/SwiftPackageResolveTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/TestSupport/MockDependencyResolver.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift

-- <rdar://problem/32343476> Enabling prefetching causes non-deterministic test failure on linux CI
There was a small race in previous code where we would not (git) update
a container if the prefetch request is completed after the regular
request.
The new logic sends only one request and if a particular container is
required, it waits for its prefetching to complete.

[PackageGraph] Rework prefetching container logic

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift

-- <rdar://problem/31714451> [SR-5002]: Poor diagnostic with legacy layout and unspecified source path
-- <rdar://problem/31936923> [SR-5003]: Awkward issue text for missing source folders
-- https://bugs.swift.org/browse/SR-5002
-- https://bugs.swift.org/browse/SR-5003

[PackageGraph] Improve some error description

---

Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/ToolsVersionLoader.swift
Sources/PackageModel/Manifest.swift
Sources/PackageModel/ToolsVersion.swift
Sources/Workspace/ToolsVersionWriter.swift
Tests/PackageLoadingTests/ToolsVersionLoaderTests.swift

- Add `Manifest.versionSpecificManifest(path:fileSystem:)`
- Use `Manifest.versionSpecificManifest(path:fileSystem:)` instead of manipulating path with `Manifest.filename`
- Remove `ToolsVersion.toolsVersionFileName`

Fix SR-5031

---

Sources/Commands/SwiftTool.swift

We need to resolve symlinks of allowed dir in sandbox otherwise we don't
get write access to them.
-- <rdar://problem/32761929> [SR-5155]: Cannot use symlinked .build folder
-- https://bugs.swift.org/browse/SR-5155

[Commands] Resolve symlinks of allowed dir

---

Sources/Basic/DiagnosticsEngine.swift
Sources/Workspace/ManagedDependency.swift

DiagnosticData already contain information to conform it to
CustomStringConvertible. This is useful when a DiagnosticData is being
used as an Swift.Error.
-- <rdar://problem/32742631> Improve error text when a dependency is not in edit mode

[Basic] Conform diagnostic data to CustomStringConvertible

---

Documentation/PackageDescriptionV4.md

I think it's a small thing, but I fix Markdown in PackageDescription API Version 4.

Fix Markdown in PackageDescription API Version 4

---

Sources/Build/BuildPlan.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Tests/BuildTests/BuildPlanTests.swift

-- <rdar://problem/32618121> [SR-648]: swift package manager should produce statically linked binaries

[Build] Link static swift stdlib by default on macOS

---

Sources/Utility/PkgConfig.swift
Tests/PackageLoadingTests/Inputs/Dependency.pc
Tests/PackageLoadingTests/Inputs/Dependent.pc
Tests/PackageLoadingTests/PkgConfigTests.swift

When loading dependencies of a `PkgConfig` file, the `additionalSearchPaths` and `fileSystem` arguments were ignored.  This was causing problems with a  Homebrew-installed OpenSSL, since's it's `.pc` file just depends on `libssl` and `libcrypto`, which were not found since their path was in `additionalSearchPaths`.

Include additionalSearchPaths when loading PkgConfig dependencies

---

Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageLoading/Diagnostics.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This is a first pass on the text of diagnostics to make them follow the style convention: https://github.com/apple/swift/blob/master/docs/Diagnostics.md
Some errors are still defined using the `FixableError` protocol. That's my next step.

Improve diagnostic messages

---

Sources/Build/Command.swift
Sources/Build/ToolProtocol.swift
Sources/Build/llbuild.swift

Contains two improvements:
* Remove `swift.o` target ouputs (only `.swiftmodule` is necessary for Swift)
* Generate a LLBuild target for each SwiftPM target
The `main` and `test` targets are kept to allow building the whole package in a single llbuild command.

Improve the manifest generation

---

Sources/Build/Command.swift
Sources/Build/ToolProtocol.swift
Sources/Build/llbuild.swift

Reverts apple/swift-package-manager#1265
Reverting until we can figure out why are we getting such errors on incremental builds:
https://ci.swift.org/job/swift-PR-Linux/8955/consoleFull#-1176476349ee1a197b-acac-4b17-83cf-a53b95139a76
```
<unknown>:0: error: cycle detected while building: target 'test' -> node '<Basic.module>' -> command '<Basic.module>' -> node '/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/swiftpm-linux-x86_64/x86_64-unknown-linux/release/Basic.swiftmodule' -> command '<Basic.module>'
```

Revert "Improve the manifest generation"

---

Documentation/Development.md

'-s' option is deprecated, so it is better to use '--filter' option instead.

Use --filter instead of deprecated option

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

-- <rdar://problem/33395793> Unable to run test targets having dynamic library as a dependency on linux

[Build] Fix rpath path for linux

---

Documentation/PackageDescriptionV3.md

This pull request fixes a link to the section about C language targets. The link got broken by [renaming files](https://github.com/apple/swift-package-manager/commit/4ee5feda08e7f9d760a4bc1397500fc23ec5bb29).

Fix a link to the section for C language targets.

---

Sources/PackageDescription/Version.swift
Sources/PackageDescription4/Version.swift
Sources/Utility/Version.swift

We can switch back to the new methods once we start building in the Swift 4 mode.

Use truncatingBitPattern instead of the newer methods

---

Sources/Commands/SwiftPackageResolveTool.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageGraph/RawPackageConstraints.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/PinsStore.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Introduce Package Identity
Package identity will be used to uniquely identify packages during
dependency resolution.
By default, the package identity is the basename of the package
repository URL. In future, the package references in the manifest file
will be allowed to override the name that should be used instead of the
basename. The package identity should always match (case insenstive for
now) the name of the package. This will be enforced via error checking
in future, i.e., once we have the API for overriding.
The commit will make dependency resolver to use the package identity
instead of package URL. The package graph is still constructed using the
package URL but that will be updated as well in upcoming commits.

Introduce Package Identity

---

Sources/Basic/StringConversions.swift
Sources/Xcodeproj/Plist.swift
Sources/Xcodeproj/XcodeProjectModelSerialization.swift

This also resolves the String.ini warning.
See: <rdar://problem/33771896> Possibly bogus String.init is deprecated warning in Swift 3 mode

Take advantage of the new String API

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

The root packages do not have a managed dependency entry so we can't
associate all packages in the graph with a managed dependency. This was
a regression from package identity refactor. Updated the graph data test
to have a root package, so this doesn't happen in future.

[Workspace] Don't try to associate all packages with managed dependency

---

Sources/PackageGraph/DependencyResolver.swift

They're no longer required because SR-2221 was fixed.

Remove the unrequired `default:` from switch cases

---

Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageGraph/RawPackageConstraints.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/TestSupport/MockDependencyResolver.swift
Sources/TestSupport/MockManifestLoader.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

A local package is a package present on the file system which may or may
not be under a git repository. These packages should be used as-is and
should not be cloned or managed by SwiftPM. Example of such packages
are: root, edited, local dependencies and multi-package packages.
So far, we only cared about edited packages during the resolution and
used unversioned requirement to handle them. This commit extends that
logic but instead of pre-loading the requirements from an unversioned
package, the container API now has a method to fetch dependencies of
unversioned package.

[PackageGraph] Add support for "local" packages in resolver

---

Documentation/Usage.md
Sources/Commands/Completions+bash.swift
Sources/Commands/Completions+zsh.swift
Sources/Commands/Describe.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftRunTool.swift
Sources/Commands/show-dependencies.swift
Sources/Utility/ArgumentParser.swift
Sources/Utility/ArgumentParserShellCompletion.swift

This PR enables shell completions for dependencies:
```
$ swift package edit A[tab]
$ swift package edit Alamofire
```
and executables:
```
$ swift run [tab]
$ swift run lark-generate-client
```

Shell completion of dependencies and executables

---

Sources/Basic/DictionaryLiteralExtensions.swift
Sources/Basic/JSON.swift
Sources/Commands/show-dependencies.swift
Tests/BasicTests/DictionaryLiteralExtensionsTests.swift
Tests/BasicTests/JSONTests.swift
Tests/BasicTests/XCTestManifests.swift

- https://bugs.swift.org/browse/SR-5624
Note: I created https://github.com/apple/swift-package-manager/pull/1306 before but as I got https://github.com/apple/swift-package-manager/pull/1306 feedback so re-created new PR.
Again, this PR includes the following attempt.
- Fix to bring "dependencies" key to the last order of output json.
- Add orderedDictionary to JSON which holds an ordered dictionary with DictionaryLiteral.
- conform CustomStringConvertible and Equatable protocols to DictionaryLiteral.
- Fix to use orderedDictionary in JSONDumper to hold an order of json.
- Add unit tests for the changes.

[SR-5624] Fix to bring "dependencies" key to the last order of json 

---

Sources/Utility/SimplePersistence.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/UtilityTests/SimplePersistenceTests.swift

The save state method of persistence did not create the parent directory
before writing the disk. This causes an error when build directory is
not present and the save state method is called.

[Utility] Create directory before writing the persistence file

---

Sources/Basic/DictionaryExtensions.swift
Tests/BasicTests/DictionaryExtensionsTests.swift

This simple pattern is used all over our codebase and this extention
just simplifies the boilerplate.

[Basic] Add extention to create dictionary from array

---

Sources/PackageGraph/PackageGraphLoader.swift
Tests/WorkspaceTests/WorkspaceTests.swift

We were relying on the fact that the manifests are topologically sorted
when creating the package graph. This is needlessly complex and the
builder pattern is simple and easier to maintain. This will also help in
establishing dependencies between the root packages.

[PackageGraph] Use build pattern to build the package graph

---

Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Product.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift

Now, we will always generate a package product in v3 packages even if
the package is a root. This is needed because roots can be used as
dependencies.

[PackageBuilder] Generate V3 product for root package as well

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/WorkspaceTests2.swift

Since root packages can be used as dependencies, we needed to switch to
computing missing package identities and not missing URLs.

[Workspace] Compute missing package identity instead of missing URL

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests2.swift
Tests/WorkspaceTests/XCTestManifests.swift

Handles the case when a dependency is added to root package which was
previously resolved from remote.

[Workspace] Remove managed dependency when present in root

---

Sources/Commands/SwiftTool.swift

- <rdar://problem/33861492> -static-swift-stdlib doesn't work

[SwiftTool] Pass static stdlib option to build plan

---

Tests/BasicTests/CStringArrayTests.swift
Tests/BasicTests/CollectionAlgorithmsTests.swift
Tests/BasicTests/CollectionExtensionsTests.swift
Tests/BasicTests/DictionaryExtensionsTests.swift
Tests/BasicTests/GraphAlgorithmsTests.swift
Tests/BasicTests/KeyedPairTests.swift
Tests/BasicTests/OrderedSetTests.swift
Tests/BasicTests/ProcessSetTests.swift
Tests/BasicTests/ProcessTests.swift
Tests/BasicTests/RegExTests.swift
Tests/BasicTests/ResultTests.swift
Tests/BasicTests/SHA256Tests.swift
Tests/BasicTests/StringConversionsTests.swift
Tests/BasicTests/miscTests.swift

- Sorry for nitpicking...
- I just found some of test doc were not well formatted so align each format of test classes under BasicTests package.

align format of test classes under BasicTests package

---

README.md
Utilities/bootstrap

SwiftPM bootstrap script uses `swiftc` invocation to infer clang flags to pass to clang invocation afterwards. However, since `swiftc` wasn't told we are trying to build a library, it would default to an executable and add `-pie` flag, which isn't appropriate.
See: https://github.com/apple/swift/pull/11669 for more details of why was this causing (minor) problems.

Respect swiftc flags for building shared libs

---

Sources/Commands/SwiftTool.swift

- <rdar://problem/34130627> [SR-5788]: SwiftPM uses global tmp directory
- https://bugs.swift.org/browse/SR-5788

[Commands] Use user namespaced temporary directory

---

Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift

This PR changes pbxproj generation to output targets in a sorted order.
It would be nice to do the same for the Xcode schemes, but given that they are left alone across regenerations I haven't attempted to tackle that.

Ensure that targets in the generated Xcode project are output in a sorted order

---

Sources/Basic/FileSystem.swift

This method is similar to the unix program `tree`. Useful for debugging
in memory filesystem.

[Basic] Add dumpTree method to FileSystem

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

I ran into this while trying to allow a project to link against `libclang.dylib`.
In my `--xcconfig-overrides`, I included `LD_RUNPATH_SEARCH_PATHS = ... $(inherited)`, but those search paths were being completely overwritten by the target's settings.

[Xcodeproj] Allow adding to LD_RUNPATH_SEARCH_PATHS with a custom xcconfig

---

Documentation/Usage.md

Hey guys! I was browsing the documentation and found two broken links for Target Format Reference. They were targeting (now) non-existing `Reference.md` file, so I've changed it to `PackageDescriptionV3.md`. I figured that `Usage.md` still uses V3 syntax so I pointed to V3 instead of V4.
As this is my first PR, please let me know if I messed up anything 😅 Cheers!

[Documentation] Fix broken links to Target Format Reference in Usage.md

---

Documentation/Development.md

I believe the build script command should assume the command is launched in the SPM
directory or that the user is in the swift directory, in the Swift README the following path is used: utils/build-script.
What do you think?

Change build script path

---

Sources/Build/ToolProtocol.swift
Tests/BuildTests/BuildPlanTests.swift

- <rdar://problem/35042923> swiftpm is hardcoded to utilize 8 cores

[Build] Do not hardcode CPU count

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

<rdar://problem/28109524> [SR-6178]: Pass -fblocks to clang for C language targets
Currently, blocks in C libraries will only work if the C target is being imported by a Swift target and that Swift target imports Dispatch. This isn't very optimal but its better than passing -Xcc -fblocks on the command line. This will not cause any issues if the C target is not using blocks. We can track always linking against blocks runtime as an enhancement.

[BuildPlan] Always add -fblocks when compiling C targets

---

Sources/Basic/Await.swift

We don't need to couple the await API with Result

[Basic] Decouple await from Result

---

Sources/Utility/ArgumentParser.swift

- <rdar://problem/33851991> `swift run --help` says COMMANDS where it should say OPTIONS

 [Utility] Rename COMMANDS to POSITIONAL ARGUMENTS

---

Sources/Build/BuildPlan.swift

- https://bugs.swift.org/browse/SR-6164

[BuildPlan] Moved -Xcxx flags to the end of the chain of arguments

---

Fixtures/DependencyResolution/External/Complex/FisherYates/src/Fisher-Yates_Shuffle.swift
Fixtures/DependencyResolution/External/IgnoreIndirectTests/FisherYates/src/Fisher-Yates_Shuffle.swift
Sources/Basic/OutputByteStream.swift

A PR on the swift repo, https://github.com/apple/swift/pull/12641, attempts to remove `IndexDistance`.
SwiftPM currently has a couple of places where it constrains `IndexDistance` to `Int`. This PR changes those places to work with any `IndexDistance` so we can remove it on the swift repo without source-breaking SwiftPM.
(we're working on the source compatibility story for this for other code outside swift-* stuff, but would be good to be able to test/land the change on master in the mean-time)

Make algorithms generic over IndexDistance

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift

Fixes [SR-5918](https://bugs.swift.org/browse/SR-5918) by @lightsprint09, @hartbit and myself at [Swift Alps](https://theswiftalps.com).

[SR-5918] Add diagnostic error for duplicate product names

---

Sources/Basic/FileSystem.swift
Sources/SourceControl/InMemoryGitRepository.swift
Tests/BasicTests/FileSystemTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/FunctionalTests/VersionSpecificTests.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/UtilityTests/SimplePersistenceTests.swift
Tests/WorkspaceTests/InitTests.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

The FileSystem protocol is now class only.
The RootedFileSystem is now a class.
All tests pass.

[SR-6049] Made FileSystem into a reference type to fix crash

---

Sources/Commands/UserToolchain.swift

Fixes [SR-6371](https://bugs.swift.org/browse/SR-6371)

Use `SWIFT_EXEC` for executing `swift-build-tool` and importing `PackageDescription`

---

Sources/Basic/TerminalController.swift
Sources/Build/BuildPlan.swift

Hi.
This PR addresses [this ticket](https://bugs.swift.org/browse/SR-4830).
I'm not personally sure if `terminalController != nil` is best check possible, but i had a problem where in more specific check `isatty(fileno(stream.filePointer)) != 0` actual `filePointer` is internal for another target, so we're not able to access it from BuildParameters.
Would appreciate feedback before i will dig into tests for this.

[WIP] [SR-4830] Propagate colors from compiler output for swiftc

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift

Reverts apple/swift-package-manager#1393
Reverting because this broke the [Plank](https://github.com/pinterest/plank) package. While re-fixing this issue, we should make sure we have a test case that would have caught the failure in the plank package.
```
git clone https://github.com/pinterest/plank
cd plank
git checkout 91d26a0974583e7d216b5192f738c5d9dd57da6a
swift build
error: multiple products named 'plank'
```
See: https://bugs.swift.org/browse/SR-6488

Revert "[SR-5918] Add diagnostic error for duplicate product names"

---

Fixtures/DependencyResolution/External/IgnoreIndirectTests/deck-of-playing-cards/Tests/LinuxMain.swift
Fixtures/Miscellaneous/UnreachableTargets/A/Package.swift
Fixtures/Miscellaneous/UnreachableTargets/A/Sources/ATarget/main.swift
Fixtures/Miscellaneous/UnreachableTargets/B/Package.swift
Fixtures/Miscellaneous/UnreachableTargets/B/Sources/BTarget1/BTarget1.swift
Fixtures/Miscellaneous/UnreachableTargets/B/Sources/BTarget2/main.swift
Fixtures/Miscellaneous/UnreachableTargets/C/Package.swift
Fixtures/Miscellaneous/UnreachableTargets/C/Sources/CTarget/main.swift
Sources/Build/BuildPlan.swift
Sources/Build/llbuild.swift
Sources/Commands/SwiftRunTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/PackageGraph.swift
Sources/Xcodeproj/generate().swift
Sources/Xcodeproj/pbxproj().swift
Sources/Xcodeproj/xcscheme().swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/RunToolTests.swift

This reintroduces PR #1284 that was reverted before the release of Swift 4 because of a bug referenced in [SR-5595](https://bugs.swift.org/browse/SR-5595). The original code was modified to pass the new test that was added in 4b74cec60b6f2211804380fc6a3504058318f8ea to support external test targets on Linux.
This resolves [SR-5597](https://bugs.swift.org/browse/SR-5597).

Allow build & run to reference unreachable targets

---

Sources/PackageGraph/PackageGraphLoader.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Fixed at SwiftAlps with the help of @JohnSundell, @melbic, @mekanics and two other attendees.
It was chosen to not trigger this warning when the unused-dependency contains an executable product, to not warn on the valid use-case that #1381 allows.

[SR-6064] Warn on unused dependencies

---

Sources/Build/BuildPlan.swift
Sources/Build/llbuild.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Module.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageLoadingTests/ModuleMapGenerationTests.swift

We were adding language standard flag per target which is wrong because
a Clang target can contain mixed C and C++ files.
- <rdar://problem/35782488> [SR-6430]: [SwiftPM] Build error passing invalid C standard to a C source file

[Build] Add lang std flag per source file

---

Tests/XcodeprojTests/GenerateXcodeprojTests.swift

Looks like Xcode now auto-generates schemes for all targets.
- <rdar://problem/35814586> Swift CI: Swift incremental (Tools Opt+Assert, Stdlib Opt+Assert) (internal-swift-4.1-branch)

[XcodeprojTests] Fix parse it test

---

Sources/Basic/PathShims.swift
Sources/Build/llbuild.swift
Sources/Commands/SwiftPackageTool.swift

The pretty outpath is computed wrong when we change the working
directory during execution. This patch uses the original cwd to compute
the outpath.
- <rdar://problem/35841891> swift package generate-xcodeproj outputs location without accounting for --package-path

[Commands] Use the original cwd to compute outpath

---

Tests/BuildTests/BuildPlanTests.swift

These tests were asserting when run in Xcode because Xcode has TTY
during unit tests.
- <rdar://problem/35862665>

[BuildTests] Adjust some assertions

---

Sources/PackageGraph/PackageGraph.swift
Sources/TestSupport/PackageGraphTester.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageGraphTests/PackageGraphTests.swift

This fixes [SR-6559](https://bugs.swift.org/browse/SR-6559) so that `PackageGraph` does not list test targets and test products from non-root packages. As a result, `swift-test` will not find any when looking for test products.

Don’t include test targets from non-root packages

---

Sources/Utility/Git.swift

`checkRefFormat` launches a git process using a string literal executable name `"git"`, but a public var `tool` with the same value is declared only a few lines above. It seems like the intent was to use that variable to specify the git executable.

Use `tool` variable rather than hard-coded executable name

---

Fixtures/Miscellaneous/ParallelTestsPkg/Tests/ParallelTestsPkgTests/ParallelTestsFailureTests.swift
Sources/Commands/SwiftTestTool.swift
Tests/FunctionalTests/MiscellaneousTests.swift

From the ticket:
> The ‘swift test --parallel’ command currently discards the output of successful tests and instead shows a status bar, only showing full output for failed tests.
> 
> It would be useful for debugging/analysis purposes to be able to access test output for both successful and unsuccessful tests

Collect output from successful tests in parallel execution mode [SR-6487]

---

Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Tests/XcodeprojTests/FunctionalTests.swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift

It is Xcode's behavior to generate xcodeproj files with Release being the default configuration for command line builds.   When you use Swift Package Manager however to generate an xcodeproj file it sets the default (i.e. command line) build to be Debug.   This causes problems when other projects depend on this default value.   For example apple/swift-protobuf#708 -- in that case the xcodeproj file was changed but if swift package manager were ever used to regenerate the project file then the expected default of Release would get overwritten.

Generate xcodeproj files with defaultConfigurationName set to Release

---

Sources/Basic/Process.swift

This is identical to issue as https://bugs.swift.org/browse/SR-6409; the resolution is to change SIGUNUSED to SIGSYS which is defined with the same value (31).

SIGUNUSED was removed in glibc 2.26, replaced with SIGSYS

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/FunctionalTests.swift
Utilities/bootstrap

Instead of using the resolved path at time of generating, use
TOOLCHAIN_DIR macro which has the correct value according to the
toolchain selected in Xcode.
https://bugs.swift.org/browse/SR-6190

[Xcodeproj] Use TOOLCHAIN_DIR macro for manifest indexing

---

Sources/Utility/ArgumentParser.swift

This removes the sorting of positional arguments in the help output for `ArgumentParser`, as they are positional and order has a meaning

Preserve positional argument order

---

Sources/Utility/ArgumentParser.swift
Tests/UtilityTests/ArgumentParserTests.swift

Fixed a formatting bug in `ArgumentParser.printUsage` where `maxWidth` only took argument name width into account, ignoring the width of the argument short name and `", "` separator.
Incorrect output was produced, like the following:
```
OPTIONS:
--bar, -b
The bar option
--foo     The foo option
```
After this fix, the output is:
```
OPTIONS:
--bar, -b   The bar option
--foo       The foo option
```
Since there isn't a dedicated test case for `printUsage`, I edited an existing parser test to check for this correct functionality.

[Utility] Fix `printUsage` for ArgumentParser

---

Sources/Basic/Process.swift

- This description probably should never be what we display to the user, but
currently it sometimes is, and when subprocesses fail for obscure reasons it
can be impossible to diagnose the issue since we don't show the captured
output.

[Process] Include failing command output in error description.

---

Sources/Basic/EditDistance.swift
Tests/BasicTests/EditDistanceTests.swift

This can be used by argument parser to implement a spellcheck and
suggest possible miscorrections.

[Basic] Add edit distance algorithm

---

Sources/PackageLoading/ManifestLoader.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift

We end up thinking there are parsing errors if compiler spits out some
warnings.
- <rdar://problem/36324891> Warnings in Package.swift break build

[PackageLoading] Supress warnings in Package.swift

---

Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/TestSupport/MockDependencyResolver.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

The package name will now be available in the dependency resolver
result. We can eventually store the package name in our state file to
look up packages by their name.

[PackageGraph] Include package name in the package reference

---

Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

- <rdar://problem/35853802> swift package edit <package-name> --path <path> fails
Edit had stopped working with package names when I landed package
identity. This patch fixes that problem.

[Workspace] Make (un)edit work with package name

---

Documentation/Development.md
Sources/Commands/UserToolchain.swift

This is useful for Swift compiler developers when they want to use
a custom compiler with existing SwiftPM.
<rdar://problem/36166118> Add support for SWIFT_EXEC_COMPILE_ONLY, which is like SWIFT_EXEC but not for the manifest

[Commands] Add env to override compile only swiftc

---

Sources/PackageLoading/Module+PkgConfig.swift
Tests/PackageLoadingTests/WhitelistTests.swift

This allows projects that link with C and C++ libraries to suppress linker warnings because of these dependencies. [LLVMSwift](https://github.com/llvm-swift/LLVMSwift), for example, currently builds with around 200 linker warnings because LLVM is built against the macOS 10.12 SDK by default.

Whitelist linker warning suppression flag

---

Fixtures/ValidLayouts/SingleModule/ExecutableNew/.gitignore
Fixtures/ValidLayouts/SingleModule/ExecutableNew/Package.swift
Fixtures/ValidLayouts/SingleModule/ExecutableNew/README.md
Fixtures/ValidLayouts/SingleModule/ExecutableNew/Sources/ExecutableNew/main.swift
Sources/Build/BuildPlan.swift
Sources/Build/ToolProtocol.swift
Sources/Build/llbuild.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftRunTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/PackageGraph.swift
Tests/CommandsTests/BuildToolTests.swift

This uses the new directory structure feature of llbuild to compute if
manifest generation is required. We use a command to write a token file
inside the build directory and regenerate the manifest file if the token
file is written. This saves a lot of time in builds where directory
structure hasn't changed. This feature is off by default and can be
enabled by using the flag --enable-build-manifest-caching.

Implement llbuild manifest caching

---

Sources/Build/llbuild.swift
Sources/Commands/SwiftTool.swift

Previously, we would fail while switching between swift build and swift
build --enable-build-manifest-caching. This should fix that problem.

[Commands] Ignore regen check failures

---

Fixtures/Miscellaneous/MultipleExecutables/Package.swift
Sources/Commands/SwiftTool.swift
Tests/CommandsTests/BuildToolTests.swift

Currently, we link automatic products statically so it is not possible
to build them via --product option
<rdar://problem/36509350> [SR-6758]: Fatal error when building single product

[Commands] Build default target if specified product is automatic

---

Sources/SourceControl/RepositoryManager.swift
Tests/SourceControlTests/RepositoryManagerTests.swift

We were basically not updating checkout-state.json when we removed
repositories.
<rdar://problem/36705254> SwiftPM isn't removing things from checkouts-state.json even when it removes the repo

[RepositoryManager] Update serialized repo dictionary on repo removal

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

We were not properly checking the root manifest constraints to compute
if a resolution is required.
<rdar://problem/36752736> swift package resolve doesn't perform resolution if root manifest is changed

[Workspace] Fix re-resolution when root manifest is edited

---

Sources/Workspace/InitPackage.swift

- <rdar://problem/36920438> SwiftPM generated projects should follow SwiftPM one XCTestManifest.swift per test arget style

[Workspace] Include XCTestManifest.swift in test target template

---

Sources/PackageGraph/DependencyResolver.swift
Tests/WorkspaceTests/WorkspaceTests.swift

<rdar://problem/36921520> Fatal error: This should never be called: file Sources/PackageGraph/RepositoryPackageContainerProvider.swift, line 210
This fatal error happens under the following conditions:
1. You have an edited dependency
2. The edit dependency is in the root package
3. Your dependency graph is unresolvable

[PackageGraph] Remove all unversioned constraints from debugging algo

---

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift

Currently, the resolver can do a lot of lookups (even when it doesn't
need to) and it translates to a lot of git calls for tools version
check. We can simply cache the result to avoid these git calls.
<rdar://problem/36777215>

[PackageGraph] Cache the result of tools version check

---

Utilities/bootstrap

- This is useful for running a small set of tests via `bootstrap test`.

[bootstrap] Add support for --test-filter.

---

Sources/PackageGraph/DependencyResolver.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

This avoid a lot of unnecessary work done by the resolver when there are
shared dependencies in a package graph. The resolver resolves the
subtree recursively everytime a dependency is encountered, so this
provides very very good performance in shared dependencies cases.
This patch was originally written by Daniel Dunbar.

[PackageGraph] Cache resolved subtree assignment set sequences

---

Sources/SourceControl/GitRepository.swift
Sources/SourceControl/InMemoryGitRepository.swift
Sources/SourceControl/Repository.swift
Sources/Workspace/Workspace.swift
Tests/SourceControlTests/GitRepositoryTests.swift
Tests/SourceControlTests/InMemoryGitRepositoryTests.swift

There's a typo in the spelling of `hasUncommitedChanges` (sic). Here's to hoping that this PR doesn't remain long as an uncommitted change.

[gardening] Fix typo in method name

---

Sources/Basic/CollectionAlgorithms.swift
Sources/Basic/DictionaryLiteralExtensions.swift
Sources/Basic/JSON.swift
Tests/BasicTests/DictionaryLiteralExtensionsTests.swift

When the standard library adds a member to one of its own types, extension methods can cause ambiguity at the call site. For end user code, this is mitigated by availability annotations.
However, for this project, we'd like to be able to build with earlier revisions on `master` that don't have their own version number. Because of this unique requirement, we must rename the conflicting methods here.
(While we're at it, I've done one item of gardening--namely, I've removed an extraneous `public` access modifier in front of an extension.)

[WIP] Rename DictionaryLiteral extensions

---

Sources/Basic/CollectionAlgorithms.swift
Sources/Basic/DictionaryLiteralExtensions.swift
Sources/Basic/JSON.swift
Tests/BasicTests/DictionaryLiteralExtensionsTests.swift

Reverts apple/swift-package-manager#1494. We shouldn't need it for implementation of conditional conformance, and it will be a good test that we're not breaking end users' code.

Revert "[WIP] Rename DictionaryLiteral extensions"

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

Make sure that OTHER_CFLAGS starts out with `$(inherited)`, as OTHER_LDFLAGS and OTHER_SWIFT_FLAGS do.  This is appropriate even if there is no other addition to OTHER_CFLAGS; in that case it is a no-op but serves as an indication that if anything else is added by hand, `$(inherited)` needs to be included to avoid masking underlying values.

Swift package manager generate-xcodeproj writes out OTHER_CLFAGS entries, which overrides the default [R-37354691]

---

Sources/Commands/SwiftTestTool.swift

This was making swift test to load the package graph even on options
like --version.

[Commands] Don't load the package graph on every command

---

Sources/Basic/SHA256.swift
Tests/BasicTests/SHA256Tests.swift

The padding function wasn't written correctly to handle cases when mod
of input length was greater than 448.

[Basic] Fix the SHA256 padding function

---

Sources/Utility/ArgumentParser.swift
Tests/UtilityTests/ArgumentParserTests.swift

> Note that this PR aims to improve the public `Utility` library for 3rd parties.
At the moment the only way to get access to the parsed arguments from `ArgumentParser.Result` is to pass in the original argument instance. This method of argument lookup becomes tricky in more dynamic uses of the parser, for example when different arguments are generated at runtime, or many commands share the same arguments.
Currently the argument instance must be saved somewhere so it can be passed into the `ArgumentParser.Result` after parsing. This is hard  as there are many different types of arguments, and they don't all fit nicely into a standard Array or Dictionary. 
This could be solved by making `AnyArgument` public (increases public API surface area and leaks an implementation detail)) or with the …

Allow dynamic access to parsed arguments by name

---

Sources/Commands/Error.swift
Sources/PackageModel/Package.swift
Tests/PackageLoadingTests/ManifestTests.swift

Solution to [SR-6737](https://bugs.swift.org/browse/SR-6737)
Previously No manifest File error was
```sh
error: noManifest(baseURL: " https://github.com/BVPMOSC/members.git", version: Optional("1.0.0"))
```
now it shows like
```
https://github.com/BVPMOSC/members.git @ 1.0.0: error: https://github.com/BVPMOSC/members.git has no manifest for version 1.0.0
```

[SR-6737] [Commands] [PackageModel] fix noManifest Description Error

---

Sources/Utility/ArgumentParserShellCompletion.swift
Tests/UtilityTests/ArgumentParserTests.swift

Solved [SR-7053](https://bugs.swift.org/browse/SR-7053) by adding escaping `[` and `]`.
Before:
```zsh
$ swift build
$ ./.build/debug/swift-package completion-tool generate-zsh-script>/usr/local/share/zsh/site-functions/_swift
$ zsh
$ swift package --[TAB]
_arguments:comparguments:319: invalid option definition: --enable-build-manifest-caching[Enable llbuild manifest caching [Experimental]]
```
After:
```zsh
$ swift build
$ ./.build/debug/swift-package completion-tool generate-zsh-script>/usr/local/share/zsh/site-functions/_swift
$ zsh
$ swift package --[TAB]
option
--build-path                                                        # Specify build/cache directory                                         
--configuration                                                     # Build with …
```

[SR-7053] Fix zsh completion script

---

Sources/Commands/SwiftTool.swift
Utilities/bootstrap

https://gitHub.com/apple/swift regularly uses `SWIFT_BUILD_DIR` to refer to, e.g., `.../build/Ninja-ReleaseAsserts/swift-linux-x86_64/` and thus the variable was introduced to swiftpm. Thus `swift_build_path` in swiftpm is being renamed to `swiftpm_build_dir` to differentiate between the two variables more clearly.

Rename swift_build_path to swiftpm_build_dir to agree with other projects naming schemes

---

Utilities/bootstrap

While debugging a crash in the stage 1 bootstrap swiftpm, I noticed that the stage 1 bootstrap is not compiled with debug info even when it is compiled in debug mode. This PR adds such support.

[bootstrap] Emit debug info when compiling a debug stage1 swiftpm.

---

Sources/Basic/Path.swift
Tests/BasicTests/PathTests.swift

Add static method to validate AbsolutePath throwing PathValidationError

[Basic] Add `AbsolutePath` validate(pathString:) method

---

Documentation/PackageDescriptionV4.md

It was decided to not include root directory to the list of pre-defined paths in the [discussion](https://github.com/apple/swift-package-manager/pull/1499). So I updated the documentation to reflect this fact.

[Docs] Update list of pre-defined paths in the documentation

---

Sources/Basic/Path.swift

This PR corrects a recently introduced spelling error, as explained in the title. NFCI.

[gardening] Fix spelling of "tilde"

---

Utilities/build_ubuntu_cross_compilation_toolchain

The prior version used Gold to build a cross-platform toolchain, but this uses a precompiled version from the main Clang distribution to provide `lld` instead of `gold` as a linker.

Update cross-platform linker to use lld instead of gold

---

Sources/Basic/Path.swift
Sources/Workspace/ManagedDependency.swift
Tests/BasicTests/PathTests.swift
Tests/BasicTests/miscTests.swift

Based on a comment of https://github.com/apple/swift-package-manager/pull/1536 elevated the validate API to the init() level.

Lifted the validation API

---

Documentation/PackageDescriptionV4.md

target dependency cannot be a target in a package dependency, it can be a product in a package dependency
Consider this example, _packageA_ depends on a target in _packageB_:
_packageB_:
```swift
name: "packageBPackageName",
products: [             
.library(
name: "packageBLibrary",
targets: ["packageBTarget"]),
],
```
_packageA_:
```swift
name: "packageA",
.package(url: "../packageB", from: "0.0.0"),
],
targets: [
// Targets are the basic building blocks of a package. A target can define a module or a test suite.                               
// Targets can depend on other targets in this package, and on products in packages which this package depends on.                 
.target(
name: "packageA",
dependencies: …
```

clarify target dependency in a package dependency

---

Tests/WorkspaceTests/WorkspaceTests.swift

Disabling this test because it intermittently fails on linux. This is
tracked by <rdar://problem/38647101> Intermittent lit test failure. SwiftPMPackageTests. HashedCollections.swift, line 6567

[WorkspaceTests] Disable a test on linux

---

Sources/PackageGraph/DependencyResolver.swift
Tests/WorkspaceTests/WorkspaceTests.swift

The ordering of its elements is not an essential part of a Dictionary;
two dictionaries with the same elements compare equal even if they're in
a different order. We must also produce hash values independent of element
ordering, or we will run afool of Hashable requirements.
Re-enable the test that was failing nondeterministically in previous commits.
rdar://problem/38647101

[PackageGraph] Fix hashing for PackageContainerConstraintSet

---

Sources/Basic/SHA256.swift

In general endianness only needs to be specified if there is an unsafe
conversion to or from a byte array taking place.

Fix SHA-256 on big endian machines

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift

I found the "could not find target(s)" diagnostic a bit misleading. This changes it to "could not find source files for target(s)" which seems more clear to me.

Improve diagnostic for missing source files

---

Documentation/Usage.md

Updates the docs to the current (4.1) syntax

Fix documentation for autocomplete scripts

---

Sources/Basic/Lock.swift

We were previously using `fopen` but `close`, instead we should be using matching syscalls.

Fix open/close issue in `Lock`

---

Sources/Commands/SwiftTool.swift

[SR-7375](https://bugs.swift.org/browse/SR-7375?jql=project%20%3D%20SR%20AND%20component%20%3D%20%22Package%20Manager%22)
This removes the default `static-swift-stdlib` command line option since it does nothing.
It may break scripts that rely on this command - an alternative may just be to hide it from `--help`?

[SR-7375] Remove default static-swift-stdlib option

---

Sources/Basic/CacheableSequence.swift

Accidentally spotted a missing "e" in "sequence" (I made the same typo in a search ;-)
If I could only be as sure that "ExprSequnceContext" in the compiler source is a typo as well... ;-)

Trivial typo in a source comment

---

Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/Manifest.swift
Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
Tests/PackageLoadingTests/ManifestTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift

This is better because we need to add a case for 4.2

[PackageModel] Rename ManifestVersion enum cases

---

Sources/Basic/PathShims.swift

When building SwiftPM using the `--destination` feature, and the
cross-compiled toolchain from `build_ubuntu_cross_compilation_toolchain`
the Basic module fails to compile due to not being able to resolve
the correct struct for `stat`.
Effectively in-line the test so that `isFile` and `isDirectory` work
as expected.

Ensure cross-compilation works for Basic module

---

Sources/Build/Triple.swift
Utilities/bootstrap

My [RaspberryPi cross compiler toolchain instructions](https://github.com/AlwaysRightInstitute/swift-mac2arm-x-compile-toolchain/tree/swift-4.1-release) break in SPM 4.1 because it hardcodes(!) the architecture. The proper fix would be to remove all this hardcoding, but meanwhile, this adds the specific target triple, similar to what people do for S/390 and PPC.

Add host target triple for RaspberryPi arm-linux-gnueabihf

---

Sources/Basic/DictionaryLiteralExtensions.swift

Currently there seems to be a limitations on typealias where they need their generics parameters declared.
Related:
https://github.com/apple/swift/pull/16577

add generic params to DictionaryLiteral<Key,Value>

---

Sources/Basic/FileSystem.swift
Sources/Basic/Process.swift
Sources/Utility/Platform.swift

Fixed memory leaks reported in [SR-7592](https://bugs.swift.org/browse/SR-7592) and other memory leaks reported by Instruments. This also moves `posix_spawn*_destroy()` calls to be defered with their `posix_spawn*_init()` calls to prevent memory leaks when exiting scope early.

[SR-7592] and other memory leaks fixes

---

Sources/PackageDescription4/Package.swift
Sources/PackageDescription4/PackageDependency.swift
Sources/PackageDescription4/PackageRequirement.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageGraph/RawPackageConstraints.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/PinsStore.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

<rdar://problem/39418745> [SR-7433]: Implement SE-201 Package Manager Local Dependencies

Implement local dependencies proposal

---

Sources/Commands/SwiftTool.swift
Sources/TestSupportExecutable/main.swift
Sources/Utility/ArgumentParser.swift
Tests/UtilityTests/ArgumentParserTests.swift

The custom body functions that binder accepts has to be non-throwing. This is not very handy if we want to do things like validating parameters, checking URLs well-formedness, etc.
This patch offers a backward-compatible way to catch errors in the throwing body functions: we introduce a throwing `binder.fill()` in addition to the deprecating the non-throwing `fill`.

Add binder.tryFill to allow catching the errors up the chain

---

Tests/UtilityTests/ArgumentParserTests.swift

Swift generates a warning when testing a depcrecated API 😭

[UtilityTests] Remove test for the deprecated API

---

Sources/Build/Triple.swift
Utilities/bootstrap

Added host target triple for arm64/aarch64.
Fixed incorrect armv7 triple.
Refactored bootstrap "compute the build paths"
Refactored Triple.swift "os and machine" dif's
New OS's and processor/machine types are currently being added in an addhoc manner. Refactoring the Utilities/bootstrap and Triple.swift addresses [[SR-7612]](https://bugs.swift.org/browse/SR-7612). While this solution is still hardcoded it provides conformity between machines and a consistent naming type for triples. 
i.e [machine][OS] - x86Linux, arm64Linux.
This will provide an easy path for adding new machines and OS's in the future.

[SR-7612] Add host target triple for arm64/aarch64 machines.

---

Sources/Basic/FileSystem.swift
Sources/Basic/PathShims.swift
Sources/Basic/Process.swift
Sources/Basic/misc.swift
Sources/Commands/Destination.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftRunTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/Commands/UserToolchain.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/InMemoryGitRepository.swift
Sources/Utility/ArgumentParser.swift
Tests/BasicTests/PathShimTests.swift
Tests/UtilityTests/ArgumentParserTests.swift

When a directory gets removed from under the running SwiftPM-based application, an irrecoverable error is generated. We'd like to be able to catch the error earlier.
* deprecated stand-alone `currentWorkingDirectory`
* introduced per-`FileSystem` `currentWorkingDirectory` which returns an *optional* `AbsolutePath` result.
* made a bunch of changes throughout the code which made sense. In some cases an explicit unwrapping is added, in some other a semantically reasonable behavior is codified.

Deprecate stand-alone currentWorkingDirectory

---

Documentation/Development.md

Fixed path of `docker-utils` written on documentation.

Fix path of docker-utils

---

Documentation/Usage.md

Completions can be loaded directly instead of using a second file.
This also has the advantage of updating automatically when completions change
with updates.

Add completions directly to bash

---

Sources/Build/BuildPlan.swift
Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftRunTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/PackageLoading/Target+PkgConfig.swift
Sources/Utility/PkgConfig.swift
Sources/Xcodeproj/generate().swift
Sources/Xcodeproj/pbxproj().swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageLoadingTests/PkgConfigTests.swift
Tests/UtilityTests/PkgConfigParserTests.swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Tests/XcodeprojTests/PackageGraphTests.swift

When users require system packages, they will typically want to use `pkg-config`
to help identify the location of libraries on the system to link to. We will
now print a warning to let users know they should install this tool if they
are running into link errors.

[PkgConfig] Print warning message when pkg-config not found

---

Documentation/README.md
README.md

For grammatical consistency in documents, two periods at the end of a couple of bullet points should be added.

Bullet point periods.

---

Utilities/bootstrap

[SR-7559] rsync: Use check_output instead of open & check_call

---

Documentation/Development.md

Hey folks, another small PR here. The link currently goes to the releases page of swift.org rather than the snapshots page that is being referred to.

link directly to snapshots section of swift.org

---

Sources/Basic/Path.swift
Tests/BasicTests/PathTests.swift

Validating RelativePath checks first symbols not to be "/" or "~" and throws `PathValidationError.invalidRelativePath` otherwise

Add RelativePath validating init

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageGraphTests/PackageGraphTests.swift

Change the error message from:
```
jmsmith@SFO-M-JSMITH01 ~/w/B/T/CombinedPackage (master)>
../../apple/swift-package-manager/.build/x86_64-apple-macosx10.10/debug/swift-build
'FirstPackage' /Users/jmsmith/workspace/Baseline/TwoTargets/CombinedPackage/.build/checkouts/FirstPackage--6769754764505680219: error: multiple targets named 'FirstTarget'
```
to:
```
jmsmith@SFO-M-JSMITH01 ~/w/B/T/CombinedPackage (master) [1]>
../../apple/swift-package-manager/.build/x86_64-apple-macosx10.10/debug/swift-build
'FirstPackage' /Users/jmsmith/workspace/Baseline/TwoTargets/CombinedPackage/.build/checkouts/FirstPackage--6769754764505680219: error: multiple targets named 'FirstTarget' in: ["SecondPackage", "FirstPackage"]
```

[SR-7834] Specify which packages contain the duplicate target

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift

Referencing `target path` with `AbsolutePath` is error prone and should be avoided.

[SR-4793] Add check that target path is not referenced by absolute path

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

This was a regression caused when the DEBUG define was added as debug
settings overrides the common settings
<rdar://problem/41168212> [SR-7965]: Xcode Project generated by SwiftPM 4.2 can't build when package depends on Yams

[Xcodeproj] Add SWIFT_PACKAGE define in debug config

---

Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/PackageGraphTests.swift

<rdar://problem/41168106> [SR-7993]: generate-xcodeproj seems to set SWIFT_VERSION to 4.0 and not 4.2

[Xcodeproj] Fix logic for generating SWIFT_VERSION setting

---

Sources/Workspace/InitPackage.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/WorkspaceTests/InitTests.swift

<rdar://problem/36554558> Default executable SwiftPM package should have tests

[Workspace] Add tests in executable template

---

Sources/PackageGraph/DependencyResolver.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

The previous logic wasn't able to detect when a dependency was switched
between version and revision.
<rdar://problem/40628265> Switching a dependency from .revision to .exact doesn't rerun dependency resolution

[Workspace] Improve isResolutionRequired check

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This cleans up the method and makes it work for some of the edge cases
that were being missed before.
<rdar://problem/40507594> swift package resolve doesn't realizes local <-> version requirement changes

[Workspace] Make isResolutionRequired more robust

---

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/Utility/Git.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift

This implements support for simultaneous vX.X.X and X.X.X style tags and fixes a bug that was discovered in the original PR for this bug where prerelease tags were handled incorrectly. An additional test case was made to test for prerelease tags.

 [SR-6978] Implement support for simultaneous vX.X.X and X.X.X style tags with fix for prerelease tags

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

This is required for packages with large number of dependencies which
may cause the command line invocation to surpass the arg max limit.
<rdar://problem/38803919> Unable to compile the code via terminal using swift test

[Build] Pass object files via a file to Swift compiler

---

Sources/Xcodeproj/SchemesGenerator.swift

<rdar://problem/41452061> Generated executable schemes don't have launch action entry

[Xcodeproj] Add launch action to executable schemes

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/PackageBuilderV4Tests.swift

There was an edge case where which lead swiftpm to escape the root package while searching for LinuxMain.
<rdar://problem/41444373> [SR-8072]: 4.2 dev hangs on `swift build` on mac and linux

[PackageLoading] Don't escape root package when searching for LinuxMain

---

Sources/Basic/TemporaryFile.swift
Tests/BasicTests/TemporaryFileTests.swift

It's sometimes useful to create a temp file but keep it around for a little bit longer, instead of automatically deleting it on dealloc. `TemporaryDirectory` already has a similar option.

Add an option to not delete TemporaryFile on dealloc

---

Sources/Commands/SwiftPackageTool.swift

* Load manifest instead of loading package graph
(cherry picked from commit d1625514175be9b7e46830d24c3392334a8b9755)

Mute non-json output from dump-package

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

This leads to faster build times when WMO is off.
<rdar://problem/39262812> SwiftPM should build using multifile mode (batch mode)

[Build] Enable Swift compiler's batch mode

---

Sources/PackageGraph/DependencyResolver.swift
Tests/WorkspaceTests/WorkspaceTests.swift

<rdar://problem/39616386> Crash under BasePackageContainer.versions(filter:)
https://bugs.swift.org/browse/SR-8177

[PackageGraph] Filter unversioned pins before running the debug algo

---

Package.swift
Sources/SPMLLBuild/llbuild.swift
Utilities/bootstrap

This target is a bridge between llbuild library and rest of the swiftpm
targets. The llbuild module is re-exported by the module.

Create a shim target for llbuild library

---

Utilities/bootstrap

Also adds an option to add rpath to libSwiftPM during installation

[bootstrap] Remove llbuild absolute rpath when installing

---

Sources/PackageLoading/Diagnostics.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

<rdar://problem/42138100> Incorrect product reference in Package.swift caused failed build on linux, succeeded on macOS

[PackageLoading] Diagnose bad executable products

---

Documentation/Development.md
Documentation/Internals/PackageManagerCommunityProposal.md
README.md

I noticed a few small documentation issues while reading the docs to get started with contributing to SwiftPM. I figured I'd put up a fix while I wait for Xcode beta to download. 😄 
Note: the broken link on the main README points to a file that is noted as "for historical purposes only", so perhaps the correct fix is to the content of the README itself, not just the link. But I figure a working link is better than a broken one.

[Documentation] Fix broken link in README

---

Documentation/Development.md
Utilities/bootstrap

<rdar://problem/42350010> Emit a script allow self-hosting SwiftPM after bootstrap
SwiftPM allowed using the built/inferior swift-{build, package, run, test} to
iterate on the package manager codebase. This is going to break now because we
adopted llbuild as a link time dependency. To resolve this, the bootstrap
script will emit a script that will call the swiftpm tool with the additional
flags that are required to allow self-hosting. This can be removed once we have
actual support for build settings.

Emit a script allow self-hosting SwiftPM after bootstrap

---

Utilities/bootstrap

This was added to stage linking llbuild with SwiftPM. Now that staging
is complete, we will always link llbuild and this flag is no longer
required.

[bootstrap] Remove usage of --link-llbuild

---

Sources/PackageLoading/PackageBuilder.swift
Sources/Xcodeproj/generate().swift

I think I broke this method when removing PD v3. We need to ignore
predefined directories while creating the Xcode project.
<rdar://problem/42134605> The generated Xcode project has blue folders for Sources and Tests in SwiftPM

[Xcodeproj] Fix extra directories method

---

Sources/PackageLoading/ManifestLoader.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

<rdar://problem/42399854> swift-package crash on clean
This avoids creating the build engine when its not really needed.

[PackageLoading] Initialize build engine lazily

---

Sources/PackageGraph/PackageGraphRoot.swift

<rdar://problem/40617721> [SR-7796]: Assertion failed: : file /Users/buildnode/jenkins/workspace/oss-swift-4.2-package-osx/swiftpm/Sources/PackageGraph/PackageGraphRoot.swift, line 124
I was overly strict and added an assertion to check that revision
dependencies have git hash length of 40. I don't think that check is
actually needed because we do validate the git ref.

[PackageGraph] Remove a unnecessary assertion

---

Sources/SourceControl/Repository.swift

<rdar://problem/41863472> Use a stable hash for repository directories
For the suffix, we now use first 8 chars of the url's SHA256 hash.
Technically, this can lead to a collision but that shouldn't matter
anyway because we just need a unique suffix.

[SourceControl] Use stable hash for filesystem ident

---

Utilities/bootstrap

This will keep llbuild separate for different platform so it is possible
to use the same build directory without cleaning.

[bootstrap] Build llbuild at a more appropriate location

---

Sources/Commands/GenerateLinuxMain.swift
Tests/FunctionalTests/MiscellaneousTests.swift

<rdar://problem/40489163> [SR-7754]: Generating LinuxMain breaks when renaming a test
This prevents the generated entries to be considered as source code on
macOS as that can lead to compilation errors when a test is renamed or
removed.

[Commands] Move generated __allTests entries under #if

---

Sources/Commands/SwiftTestTool.swift
Tests/CommandsTests/TestToolTests.swift
Tests/CommandsTests/XCTestManifests.swift

This adds --num-workers option to specify how many workers we want in the test.
Example: `swift test --num-workers 4`

[SR-8138] add --num-workers option to limit the parallelism of `swift test --parallel`

---

Sources/Commands/Error.swift
Sources/Commands/SwiftTool.swift
Sources/Commands/WatchmanHelper.swift
Tests/CommandsTests/TestToolTests.swift

The Diagnostics.fatalError error is used to abort the execution. The
actual diagnostics are expected to be present in the DiagnosticsEngine.
<rdar://problem/42511641> [SR-8338]: 'Diagnostics.fatalError' should not print out to console

[Commands] Don't print fatalError diagnostic

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/XCTestManifests.swift

<rdar://problem/33057869> [SR-5383]: Display appropriate message when trying to build system module packages

[Build] Diagnose graphs that have no buildable targets

---

Sources/Commands/GenerateLinuxMain.swift

This prevents a crash when a test class doesn't contain any test
methods.
<rdar://problem/42554220> swift test --generate-linuxmain can't handle tests with underscores in the name

[Commands] Skip test cases with no tests

---

Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftTool.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/XCTestManifests.swift

<rdar://problem/42583418> Remove build manifest caching
The build manifest caching provides a preformance win but creating build
plan is now faster (than build manifest caching) because of package
manifest caching. The difference is about 100ms and we can bring the
time down by optimizing the tools lookup. However, this feature is not
critical anymore because the performance is decent with package manifest
caching. We can add it back in the future when required.
￼

[Commands] Remove build manifest caching

---

Sources/Build/BuildPlan.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/XCTestManifests.swift

<rdar://problem/41342798> SwiftPM is not warning about non whitelisted flags
<rdar://problem/40260898> [SR-7690]: SwiftPM does not print any warnings which is must be emitted at all during `build plan` including message about pkg-config provider hinting feature

[Build] Emit BuildPlan diagnostics to DiagnosticsEngine

---

Sources/Commands/SwiftTool.swift
Sources/Commands/UserToolchain.swift

<rdar://problem/42590491> SwiftPM shouldn't lookup clang on every getClangCompiler() invocation

[Commands] Store path to clang compiler after lookup

---

Sources/Build/BuildDelegate.swift
Sources/Build/llbuild.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/BuildToolTests.swift

I've opened the Pull Request to get some initial feedback. I've got it working by setting up `llbuildSwift` as a dependency in the `Package.swift` (not committed), but I'll need some help for the remaining steps.
What's left to do that I can do:
What's left to do that requires outside help:

Introduce option to use llbuild as a library

---

Sources/PackageGraph/PackageGraphLoader.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageGraphTests/XCTestManifests.swift

<rdar://problem/39954169> [SR-7597]: Running 'swift build' crashes with segmentation fault when dependency name equals project's name

[PackageGraph] Fix crash when there is a cycle in root package

---

Sources/Commands/GenerateLinuxMain.swift
Tests/FunctionalTests/MiscellaneousTests.swift

- Replaced `__allTests` by `__<className>` 
- Updated the tests to fit this new naming method
Bug report by @aciidb0mb3r : https://bugs.swift.org/browse/SR-8459

[SR-8459] fix --generate-linuxmain when testing subclasses

---

Sources/TestSupport/PseudoTerminal.swift
Tests/BasicTests/TerminalControllerTests.swift
Tests/UtilityTests/ProgressBarTests.swift

Add 'PseudoTerminal' to 'TestSupport' so it can be shared across different test targets 
[ @aciidb0mb3r suggestion ]

Add 'PseudoTerminal' to 'TestSupport'

---

Sources/Commands/SwiftTestTool.swift

1. Added DiagnosticsEngine parameter to TestRunner and ParallelTestRunner.
2. Added emitting errors with DiagnosticsEngine.
3. Formatted TestRunner init and calls to improve readability.

Improving test tool diagnostics

---

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/PackageLoading/Diagnostics.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/TestSupport/MockManifestLoader.swift
Sources/Workspace/Workspace.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift

We were supressing the warnings while loading the manifests because we
considered any type of output from the compiler as a sign of error. This
changes the error state to depend on the exit code. The warnings will be
printed when loading a resolved package graph and not during dependency
resolution. This makes sense because the manifest we look at during
dependency resolution might not be used in the final resolved graph.
<rdar://problem/41180566> SwiftPM should not suppress compiler warnings in the manifest file

[PackageLoading] Print warnings when loading manifests

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This correctly computes the pinning logic when there are managed
dependencies which are not required in the package graph.

[Workspace] Improve pinAll logic

---

Tests/CommandsTests/PackageToolTests.swift

This replaces the use of `-C` with `--package-path` in this tests; the former being deprecated.

Update `execute(_:)` calls in `PackageToolTests` to use `execute(_:packagePath:)`

---

Sources/Commands/Options.swift

The implementation seems to work fine with several community packages. We
should be able to deal with any bugs we discover at this point.

[Commands] Use library based llbuild by default

---

Utilities/bootstrap

<rdar://problem/43234168> git hash is absent from swiftpm version in toolchains created by Swift CI

[bootstrap] Fix swiftpm version when building on CI

---

Sources/Basic/OutputByteStream.swift
Tests/BasicPerformanceTests/OutputByteStreamPerfTests.swift
Tests/BasicTests/OutputByteStreamTests.swift

`OutputByteStream` and the `<<<` operator have many overloads that seem to have been created for two main reasons: to resolve performance issues, and to resolve a compiler ambiguity error with types that are both `ByteStreamable` and `TextOutputStreamable`, as can be seen by the following comment note:
```swift
// NOTE: It would be nice to use a protocol here and the adopt it by all the
// things we can efficiently stream out. However, that doesn't work because we
// ultimately need to provide a manual overload sometimes, e.g., TextOutputStreamable, but
// that will then cause ambiguous lookup versus the implementation just using
// the defined protocol.
```
Since now, the performance problems seem to have been resolved and the ambiguity issue can be resolved with an override which …

OutputByteStream overloads refactoring

---

Sources/Basic/CollectionAlgorithms.swift
Sources/Basic/StringConversions.swift
Sources/Commands/Destination.swift
Sources/Workspace/ToolsVersionWriter.swift

This patch aims to make `swiftpm` adapted to [this PR](https://github.com/apple/swift/pull/18623), which produces warnings for redundant access-level modifiers.
@aciidb0mb3r Hi Ankit, would you help take a look at this, please?

Fix redundant access-level modifiers.

---

Sources/Basic/Process.swift

Sometimes there is a need to create child processes and ensure they will die together with their parent. By default, both `NSTask` and `SPM.Process` 'detach' the new subprocess from the current process' group. By adding a new flag `startsNewProcessGroup: Bool` we allow child process to inherit the process group from its parent.
Similar effect can be achieved on `NSTask` by calling `-[NSConcreteTask setStartsNewProcessGroup:]` private API.

Allow to create child processes in the same process group

---

Documentation/PackageDescriptionV4_2.md

Search results and my desire to use the latest version made me think that I could find everything I needed to use in the 4.2 documentation.
Come to find out most it and the specs are in PackageDescriptionV4.md with 4.2 documentation being a supplement. 
Thinking a link near the top might help call this out. Or some copy mentioning that this is a modification to the full set of docs.

Link back to full docs.

---

Sources/Basic/OrderedDictionary.swift
Sources/PackageGraph/DependencyResolver.swift
Tests/BasicTests/OrderedDictionaryTests.swift
Tests/BasicTests/XCTestManifests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

The assignments were stored in a regular dictionary which caused
non-deterministic crashes when a package graph contained dependencies
that were required via a revison and version in different subtrees.
Since the order in which the constrained appear matters, the assignment
also needs to be stored in order.
Cherry-picked from 1c482a5
<rdar://problem/43699736>

[PackageGraph] Use OrderedDictionary to store assignments

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

<rdar://problem/43700179> isResolutionRequired is non-deterministic when a graph contains both revision and version based dependency requirements

[Workspace] Use topological sort when creating DependencyManifests

---

Utilities/bootstrap

This adds an option to the `bootstrap` script to show the `bin` directory in the build folder.
We will need this to find the just built SwiftPM executables in the build script of `apple/swift` so that we can build SwiftSyntax after it has moved to its own repository.

Add option to show bin build directory

---

Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift

For applications using libSwiftPM it may be appropriate to use a different environment than the one of the calling process.

Allow a custom env for various `xcrun` invocations

---

Sources/Utility/ProgressBar.swift

This fixes a small output glitch of parallel testing.

Add an additional newline after progress bar

---

Sources/Xcodeproj/XcodeProjectModelSerialization.swift

This avoids the Swift upgrade warning for the generated project, analogous to us already setting `LastUpgradeCheck`.

Set `LastSwiftMigration` to 9999

---

CHANGELOG.md

* #1485 `LinuxMain` generation
* #1435 `llbuild` manifest caching
* #1416 Xcode default config
* #1411 multiple products, same name error
* I wasn't sure about Docker 🐳 support (#1372) since it isn't necessarily end-user related, but might be cool to call out.
* #1524 Mix versions
* #1566 No absolute path
* #1575  xUnit output (Do we actually want this since it's not in the help output? 🤔 )
* #1482, #1546, #1587 `ppc64le`, `arm`, `arm64`, and `aarch64` support.
* #1489 Simple Progress Bar
* What about #1543, did that get attempted again somewhere?
* I didn't quite grok #1518, should we mention that?

[SR-8108] CHANGELOG for Swift 4.1 and 4.2 from commit logs.

---

Sources/Build/BuildPlan.swift
Sources/Build/Triple.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/XCTestManifests.swift

This PR implements support for a Windows target, which enables cross-compiling SwiftPM projects to Windows. 
Note that this PR only goes so far as to get things working – I've left some things such as changing file extensions for static/dynamic libraries since functionality isn't impacted by e.g. libraries ending with .a instead of .lib.

Add basic support for Windows targets

---

Sources/Utility/ProgressBar.swift

This currently messes up the progress bar, this change makes it so that long output gets head truncated with ellipsis.

Fix progress bar if output exceeds terminal width

---

Sources/Workspace/UserToolchain.swift

Basically a continuation of #1766

Allow a custom env for more `xcrun` invocations

---

Sources/Commands/SwiftPackageTool.swift
Sources/Xcodeproj/generate().swift
Sources/Xcodeproj/pbxproj().swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift

In #1507, we started adding "extra" files to the generated Xcode
project. This makes some enhancements to that feature:
- Introduce a new CLI flag `--skip-extra-files` to go back to the pre-4.2 behaviour (best behaviour) of not including these files at all
- Do not add a file reference for "Package.resolved" since this shouldn't be edited by hand and most people also never have to read it
- Move the "extra" file references after the products group. This may be debatable, but I think it is more clean to have all file references related to the package manifest grouped together at the top instead of having these interspersed throughout the main group

Improve handling of "extra" files

---

Sources/SourceControl/GitRepository.swift

On `FileSystem` protocol, `removeFileTree` method is throwable.
```swift
func removeFileTree(_ path: AbsolutePath) throws
```
So I think it is better to throw `FileSystemError.unsupported`. instead of calling `fatalError`

Throwing errors instead of calling fatalError

---

Sources/Basic/OutputByteStream.swift
Sources/Basic/TerminalController.swift
Sources/Build/BuildDelegate.swift
Sources/Build/BuildPlan.swift
Sources/Commands/Error.swift
Sources/Commands/SwiftTool.swift
Sources/Utility/ProgressBar.swift
Tests/BasicTests/OutputByteStreamTests.swift

To support Thread-safe around any OutputByteStream, and after a design discussion with @aciidb0mb3r, I implemented the following solution:
- renamed `OutputByteSteam` into `OutputByteStreamBase`
- introduced a new `OutputByteStream` protocol that `OutputByteStreamBase` conforms to
- removed thread-safety from `OutputByteStream`
- introduced a new `ThreadSafeOutputByteStream` class that wraps any `OutputByteStream` around a queue
- removed the `<<<` override for `TextOutputStreamable` as its generic signature doesn't play well with the `OutputByteStream` protocol (a protocol can't *yet* conform to itself).

Thread-safe Output Byte Stream

---

Sources/Basic/FileSystem.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/InMemoryGitRepository.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift

According to [the documentation](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4_2.md#local-dependencies), local dependencies are available on SPM DescriptionV4_2.
However, we can't declare paths which start with `~`.
```swift
// swift-tools-version:4.2
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription
name: "myexecutable",
// Dependencies declare other packages that this package depends on.
.package(path: "~/work/MyPackage"),
],
targets: [
// Targets are the basic building blocks of a package. A target can define a module or a test suite.
// Targets can depend on other targets in this package, and on products in packages which this …
```

Support tilde expansion for local dependencies on DescriptionV4_2

---

Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This switches the method from providing a set of missing identities to
provide a set of missing package references. This should eventually help
in resolving the issue where we don't re-resolve when a package url is
changed without affecting the identity.

[Workspace] Use PackageRef to compute missing packages

---

Sources/TestSupport/MockManifestLoader.swift
Sources/TestSupport/TestWorkspace.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

Instead of identity, this will key managed dependencies by the package
URLs. This will help us to distingush between forks and also resolves
this bug:
<rdar://problem/34302690> Detect changes in dependency URLs when the package identity remains same

[Workspace] Key managed dependencies by the URL

---

Sources/Workspace/PinsStore.swift
Tests/WorkspaceTests/PinsStoreTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

<rdar://problem/44761993> SwiftPM shouldn't write a Package.resolved with zero objects

[Workspace] Don't generate Package.resolved when there are zero pins

---

Sources/Build/BuildPlan.swift
Sources/Commands/SwiftRunTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Product.swift
Sources/TestSupport/misc.swift
Sources/Workspace/Workspace.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/XCTestManifests.swift

This adds a --repl option to `swift run` which will build the package
and launch the Swift REPL. All reachable library modules will be
accessible in the REPL. It works by generating a special dylib product
that contains all of the library targets of the root package.
https://bugs.swift.org/browse/SR-1573

Add support for Swift REPL

---

Package.swift

The runtimes are separated from libSwiftPM so there is no need to
include it in the libSwiftPM product.

Remove PackageDescription4 from libSwiftPM

---

Sources/Commands/SwiftPackageTool.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageGraph/RawPackageConstraints.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/SourceControl/SwiftPMConfig.swift
Sources/TestSupport/TestWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/CommandsTests/XCTestManifests.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

<rdar://problem/42511642> [SR-8328]: Implement SE-0219 Package Manager Dependency Mirroring
https://bugs.swift.org/browse/SR-8328

Implement SE-0219 Package Manager Dependency Mirroring

---

Sources/Commands/GenerateLinuxMain.swift

It is common to have test classes with no tests to provide support code.

[Commands] Don't warn for empty test classes when generating linuxmain

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

<rdar://problem/44929423> Error when compiling products with dashes(`-`) in the name

[Build] Products should use c99name for -module-name

---

Sources/SPMLLBuild/llbuild.swift

JSONEncoder does not guarantee stable element ordering unless we specifically ask for the keys to be sorted.
This gets especially important as we plan to enable per-instance hash seeding for Dictionary, which breaks llbuild's rule keys on Linux without this change.

[PackageLoading] Make sure JSON-encoded rule keys are stable

---

Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This fixes the issue when we would end up using a dependency URL from an
outdated Package.resolved file for a transitive dependency. Since the
resolver clones the first package identity it encounters, we would not
clone the right thing and then would end up in a broken state in later
stages.
The patch will basically re-run the resolver once we have enough
information to correctly determine the correct path of the trasitive
dependency.
<rdar://problem/44948545>

[Workspace] Resolve correctly with outdated Package.resolved file

---

Sources/PackageLoading/Diagnostics.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

<rdar://problem/45211659> `swift run --repl` crashes when there are zero library targets in the root package

[PackageLoading] Diagnose zero library target packages for REPL

---

Sources/Basic/TerminalController.swift

Now TerminalWidth default to 80 if it's nil or zero. This prevent the update progress bar function to crash.

[SR-8993] - Progress bar update crash when running tests in Xcode

---

Sources/Build/Triple.swift
Utilities/bootstrap

Makes the basic changes required to build on 32-bit x86 Linux as i686. 
There's some underlying issues with LLVM as a JIT on 32-bit x86 that prevents SwiftPM from completing bootstrapping, but this change is required to unblock things far enough to test/investigate those issues.

Implement i686 support

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Sources/TestSupport/TestWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This adds a new flag `--force-resolved-versions` which will force
resolve to versions recorded in the Package.resolved file.
The entries in Package.resolved can be considered as "soft" pins.  Since
the requirements in root manifest and Package.resolved can change
anytime, most SwiftPM operations (that load the package graph) first
check if the current state of things is still correct. However, it is
sometimes useful to force resolve to the dependencies recorded in the
resolved file by entirely bypassing the dependency resolution.
<rdar://problem/45290071> Add option to not re-resolve, but use Package.resolved explicitly

[Commands] Add an option to force resolution to Package.resolved

---

Sources/Basic/Path.swift

Stumbled upon the TODO that was on `PathImpl`.
It directed to [SR-3009](https://bugs.swift.org/browse/SR-3009). The example project from @aciidb0mb3r now builds and running the same `swift build` command on the package manager also succeeds.

[SR-3009] Made PathImpl private

---

Sources/Basic/TemporaryFile.swift
Sources/Build/BuildPlan.swift
Sources/Commands/SwiftTool.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/Utility/Platform.swift
Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This assumption is not always true and we shouldn't be crashing in such
cases.
<rdar://problem/45198013> Turn precondition in determineTempDirectory into a runtime throw

[Basic] Convert precondition in determineTmpDir into a runtime error

---

Sources/Commands/SwiftPackageTool.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/ToolsVersion.swift
Sources/TestSupport/TestWorkspace.swift
Sources/Workspace/InitPackage.swift
Sources/Workspace/ToolsVersionWriter.swift
Sources/Workspace/Workspace.swift
Tests/FunctionalTests/VersionSpecificTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
Tests/WorkspaceTests/ToolsVersionWriterTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This assumption is not always true and we shouldn't be crashing in such
cases.
<rdar://problem/45198013> Turn precondition in determineTempDirectory into a runtime throw

[PackageLoading] Filter versions containing older tools version

---

Sources/Basic/CollectionAlgorithms.swift
Sources/Basic/Path.swift
Tests/BasicTests/CollectionAlgorithmsTests.swift
Tests/BasicTests/XCTestManifests.swift

The implementation of `spm_rindex()` was almost identical to the implementation in of `lastIndex()` from the standard library's extensions for `BidirectionalCollection`.

removed spm_rindex and replaced usage with lastIndex(of:) from the standard library

---

Documentation/Development.md
Sources/Workspace/UserToolchain.swift

Exposes an env variable SWIFTPM_PD_LIBS to allow overriding path to the
runtime libraries.
<rdar://problem/45327949>

[Workspace] Allow overriding path to runtime libraries

---

Sources/TestSupport/TestWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This API is not really required and can be removed.
<rdar://problem/45384503> Remove loadGraphData API from Workspace

[Workspace] Remove graph data API

---

Sources/Basic/FileSystem.swift

I removed the FIXME from the error handling case since none of the man page errors seem recoverable.
* According to the man pages on macOS and Linux `readdir_r()` can fail with several errno values when given invalid pointers.
* On macOS it can also fail by returning `EIO` for I/O failures.
* On linux it can also fail by returning `ENAMETOOLONG` because the directory name is too long for the OS.

fixed usage of readdir_r() to match the man page

---

Sources/Commands/GenerateLinuxMain.swift
Tests/BasicTests/XCTestManifests.swift
Tests/BuildTests/XCTestManifests.swift
Tests/CommandsTests/XCTestManifests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/XCTestManifests.swift
Tests/POSIXTests/XCTestManifests.swift
Tests/PackageDescription4Tests/XCTestManifests.swift
Tests/PackageGraphTests/XCTestManifests.swift
Tests/PackageLoadingTests/XCTestManifests.swift
Tests/PackageModelTests/XCTestManifests.swift
Tests/SourceControlTests/XCTestManifests.swift
Tests/TestSupportTests/XCTestManifests.swift
Tests/UtilityTests/XCTestManifests.swift
Tests/WorkspaceTests/XCTestManifests.swift
Tests/XcodeprojTests/XCTestManifests.swift

Currently, projects that use `--generate-linuxmain` will generate a file that breaks iOS and other platforms.
There may be more things that need to be fixed here, but this is a start. I noticed that throughout this project things are cased on `os(macOS)` a _lot_. Perhaps an audit is a good idea?

Prefer "#if os(Linux)" to "#if !os(macOS)

---

Sources/Basic/DiagnosticsEngine.swift
Sources/Basic/FileSystem.swift
Sources/Basic/LazyCache.swift
Sources/Basic/OutputByteStream.swift
Sources/Basic/Path.swift
Sources/Basic/TemporaryFile.swift
Sources/Build/BuildPlan.swift
Sources/PackageDescription4/JSON.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/RepositoryManager.swift
Sources/SourceControl/SwiftPMConfig.swift
Sources/Utility/ArgumentParser.swift
Sources/Utility/BuildFlags.swift
Sources/Utility/PkgConfig.swift
Sources/Workspace/Workspace.swift
Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Sources/Xcodeproj/generate().swift
Sources/Xcodeproj/pbxproj().swift

I've only moved FIXMEs that were on a line with a normal comment (`//`) that were directly after a doc comment (`///`) which breaks documentation linking to the declaration they are for.

Moved // FIXME: lines that broke doc comments

---

Utilities/bootstrap

Update the library search paths to ensure that we use the new library paths from
the CMake based builds.  This is a pure cleanup patch to remove some legacy
cruft from libdispatch.

build: do not consult the legacy locations for libraries

---

Sources/PackageLoading/Target+PkgConfig.swift
Tests/PackageLoadingTests/PkgConfigTests.swift
Tests/PackageLoadingTests/WhitelistTests.swift

The presence of a non-whitelisted flag in a .pc file caused Swift PM to remove all other valid flags. This issue has been described in several bug reports:
- [SR-8822](https://bugs.swift.org/browse/SR-8822)
- [SR-2481](https://bugs.swift.org/browse/SR-2481)
- [SR-4195](https://bugs.swift.org/browse/SR-4195)
- [SR-7689](https://bugs.swift.org/browse/SR-7689)
This fixes the issue by doing some more advanced filtering of invalid flags where the valid flags aren't thrown away anymore (and invalid flags still emit a diagnostic).

[FIX] Issue where the presence of non-whitelisted flags would remove all other flags detected from .pc files

---

Sources/Workspace/InitPackage.swift

These files previously didn't have a newline at the end of the file.

Update whitespace in generated Linux test files

---

Sources/Basic/OutputByteStream.swift
Tests/BasicTests/OutputByteStreamTests.swift

LocalFileOutputStream copies collections into [UInt8] before calling
fwrite in writeImpl. This overhead can be avoided when an ArraySlice is
available. Further, the write() method is always buffered, which
potentially incurs another copy overhead. This change adds an
ArraySlice<UInt8> specialization for OutputStreams and adds an
'unbuffered' option for the accompanying write() method. The combination
of these two changes yielded a 10x performance improvement in a tool
utilizing these from Basic.
rdar://problem/45592874

[Basic] Add ArraySlice<UInt8> specialization for OutputStreams

---

Sources/Utility/Git.swift

SwiftPM currently hangs if git is expecting an input on stdin. This
isn't great as that can happen if the ssh key is password protected or
if the host fingerprint isn't known. We should ideally ask user for
input but shouldn't at least hang in the meantime.
<rdar://problem/30661854> [SR-3981]: Swift package manager doesn't prompt for SSH keys passphrase

[Utility] Use ssh's batch mode option when cloning repos

---

Tests/BasicTests/StringConversionsTests.swift
Tests/BasicTests/XCTestManifests.swift

Supersedes an accidentally closed https://github.com/apple/swift-package-manager/pull/1849

Add tests for spm_localizedJoin(type:)

---

Sources/PackageLoading/Target+PkgConfig.swift
Sources/Utility/PkgConfig.swift
Tests/PackageLoadingTests/PkgConfigTests.swift
Tests/UtilityTests/PkgConfigParserTests.swift
Tests/UtilityTests/XCTestManifests.swift

To be able to test this, I had to funnel through the file system to `Process` and implement support for  `chmod` to the file system.
See <rdar://problem/45825273>

Allow overriding path to Homebrew

---

Sources/Commands/SwiftTool.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This flag is similar to the previous --force-resolved-versions except
that now we error out if see that the Package.resolved file is out-of-date.
<rdar://problem/45822895>

[Workspace] Add --disable-automatic-resolution flag

---

Sources/PackageLoading/ManifestLoader.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

Many packages use env variables to perform conditionals in the manifest
file. This basically means that we need to invalidate the manifest cache
if the env changes. Ideally, SwiftPM should provide an API in
PackageDescription that will allow us to keep track of the exact
variables used by the manifest but this should be good enough for now.
<rdar://problem/45931785> SwiftPM should invalidate manifest cache when the process env changes

[PackageLoading] Invalidate manifest cache when env changes

---

Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

These are two cases that need to be handled separately.
<rdar://problem/45944227> Bad error when a package is using newer tools version than installed

[Workspace] Improve incompatible tools version diagnostics

---

Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

<rdar://problem/45786628> ManagedDepenency needs to be resilient against having the the state file removed underneath it

[Workspace] Make managed dependencies state file resilient

---

Sources/PackageLoading/ManifestLoader.swift
Utilities/bootstrap

This will add the arguments that are required to import Foundation in
PackageDescription library when bootstrapping on the CI. It should be
now possible to use Codable for generating JSON in the runtime
libraries.
<rdar://problem/45975602> Allow importing Foundation in the PackageDescription library

[PackageLoading] Allow using Foundation in PackageDescription

---

Utilities/bootstrap

SwiftPM's bootstrap script derives the linking command by calling
swiftc with -###. I think this was needed in the past because we
couldn't forward the -Xlinker args to the linker on linux. This no
longer seems to be true since Swift is using clang++ on linux as the
linker. The -Xlinker args are correctly forwarded to clang++ so we can
stop using this hack. This hack surfaced an issue when trying to land
the Codable in PackageDescription PR as we were dropping the swiftrt.o
file during linking.
<rdar://problem/45976814> SwiftPM shouldn't need to derive the linking command when producing its runtimes on linux

[bootstrap] Remove PackageDescription linking hack

---

Sources/Build/Sanitizers.swift

Please test with following pull request:
https://github.com/apple/swift/pull/18553

Add UBSan support for C family languages

---

Sources/Basic/FileSystem.swift
Tests/BasicTests/FileSystemTests.swift

It is not sufficient to look for the 'x' bit to check for an executable
file, since directories typically have 'x' set as well.

[Basic] Fix isExecutableFile on directories

---

Sources/Basic/JSONMapper.swift
Sources/PackageDescription4/ManifestVersion.swift
Sources/PackageDescription4/Package.swift
Sources/PackageDescription4/SupportedPlatforms.swift
Sources/PackageLoading/ManifestBuilder.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/PackageModel/Manifest.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

This adds API for declaring platforms in the PackageDescription module.
The API is currently underscored because proposal is going through Swift
evolution.

Add API for platforms in PackageDescription

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/Manifest.swift
Sources/PackageModel/Platform.swift
Sources/PackageModel/Target.swift
Sources/TestSupport/DiagnosticsEngine.swift
Sources/TestSupport/Manifest.swift
Sources/TestSupport/MockDependencyGraph.swift
Sources/TestSupport/TestWorkspace.swift
Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This will fill the platform information in the package model and start
making use of it to reject incompatible packages in a graph. This patch
doesn't use the deployment information during the build.

[PackageModel] Load platform information into the package model

---

Sources/PackageDescription4/BuildSettings.swift
Sources/PackageDescription4/SupportedPlatforms.swift
Sources/PackageDescription4/Target.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/PackageModel/Manifest.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

This adds the build settings API that is currently being pitched on
Swift evolution. The intent is to add the required infrastruture for
build settings even if we don't end up with an accepted proposal before
the next Swift release. The APIs currently have an underscore to
indicate that they're not officially supported and will be removed if we
don't go through the evolution process.

[WIP][PackageDescription] Add target-specific build settings API

---

Sources/PackageLoading/PackageBuilder.swift
Sources/PackageModel/BuildSettings.swift

This is probably a better model than shoving all conditions into
a single struct.

[PackageModel] Use separate type for each build setting condition

---

Sources/Build/llbuild.swift
Tests/BuildTests/IncrementalBuildTests.swift
Tests/CommandsTests/RunToolTests.swift
Utilities/bootstrap

This only applies to Clang targets. Swift targets will be fixed in llbuild separately, but the tests have been modified in preperation.

Rename Compile to Compiling to fix tense

---

Sources/PackageDescription4/SupportedPlatforms.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift

The version string of an Apple platform is a dot-separated series of
2 or 3 positive integers. This improves the validation to ensure that
the version components are non-negative, and that the version number is
within the range of publicly-deployable versions that actually existed
for that platform (this is different from the minimum *supported*
version).
For example, the minimum versions in this validations are the minimum
versions that any API can be documented as being available on:
- iOS 2.0+
- macOS 10.0+
- tvOS 9.0+
- watchOS 2.0+
This also deduplicates the code.

Improve OS version number validation in SupportedPlatforms

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

If two or more targets provide the same linker flags, we should
deduplicate them.
<rdar://problem/46365576> Deduplicate build settings where possible

[Build] Deduplicate linker flags when building products

---

Sources/Basic/misc.swift
Sources/PackageModel/PackageModel+Codable.swift

Extending stdlib types is not a good idea due to the leakage problem.
<rdar://problem/46156789> Remove Codable conformance from Range

[Basic] Avoid extending stdlib types

---

Utilities/bootstrap

This is a simple change to use 'normpath', for removing '..' from the stdlib path, instead of 'realpath',
which allows installing swiftpm using a setup where the Swift stdlib is symlinked in.
Without this change RPATH modification fails because the real path string is not found in the binary
(the absolute stdlib RPATH in the binary is relative to the swift binary).
This should have no effect in existing setups.

[bootstrap] Allow modifying the stdlib RPATH using a build where the stdlib is symlinked into the toolchain

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/XCTestManifests.swift

Avoid prefixing -Xlinker to search paths otherwise they get appended to
the end of the search list which can lead to linking system libraries
instead of user ones.
<rdar://problem/46408766> Pass -L flags directly to the swift compiler
https://bugs.swift.org/browse/SR-9347

[Build] Pass -L flag directly to Swift compiler

---

Utilities/bootstrap

Previously, we would only care if "CMakeCache.txt" exists, this adds a check for whether we are using the correct `swiftc`. This resolves and issue when switching between different versions of Xcode.
rdar://problem/46454067

[bootstrap] Improve CMake caching

---

Sources/Utility/ProgressAnimation.swift
Tests/UtilityTests/ProgressAnimationTests.swift
Tests/UtilityTests/XCTestManifests.swift

While adding a test that verifies the fix, I refactored the progress tests to avoid repetition.

Avoid new-line on progress when never updated

---

Sources/Build/Triple.swift

Change enum Arch case ppc64le to powerpc64le for PowerPC(ppc64le)

Change enum Arch case ppc64le to powerpc64le for PowerPC(ppc64le)

---

Sources/Commands/SwiftTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/SourceControl/RepositoryManager.swift
Sources/TestSupport/MockDependencyResolver.swift
Sources/Workspace/Workspace.swift
Tests/BasicTests/AwaitTests.swift
Tests/BasicTests/ResultTests.swift

SZE-0235 is implemented in https://github.com/apple/swift/pull/20958, and successfully makes SwiftPM's usages of its own `Result` ambiguous.

Prepare SwiftPM for the addition of Result to the stdlib

---

Sources/Workspace/InitPackage.swift

There are a bunch of platforms which are not macOS and still have the ObjC runtime. This also brings this check in line with the `generate-linuxmain` command.
See rdar://problem/46739400

Use `!canImport(ObjectiveC)` instead of `!os(macOS)`

---

Sources/Commands/SwiftTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/SourceControl/RepositoryManager.swift
Sources/TestSupport/MockDependencyResolver.swift
Sources/Workspace/Workspace.swift
Tests/BasicTests/AwaitTests.swift
Tests/BasicTests/ResultTests.swift

Reverts apple/swift-package-manager#1912. The compiler change in https://github.com/apple/swift/pull/21370 is meant to keep existing `Result` types working by introducing an appropriate name-shadowing rule.

Revert "Prepare SwiftPM for the addition of Result to the stdlib"

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/Pubgrub.swift
Sources/PackageModel/Manifest.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphTests/PubgrubTests.swift

This is a first of probably a few PRs to implement a new dependency resolution algorithm in SwiftPM (my project whilst interning at Apple). It's based on [Pubgrub](https://medium.com/@nex3/pubgrub-2fb6470504f).
The major upside to this will be more descriptive and actionable diagnostics in error cases. Better performance is another side goal. Currently, in the case that dependency resolution fails, SwiftPM is unable to explain to the user why it did, just that it is so. This aims to improve that.
Please note that the code here is still very much a work in progress. It is as of yet still non-functional, but includes necessary types, API and several building blocks. It however currently stills fails at its actual job, resolving dependencies. There are also several TODOs, FIXMEs, fatalError …

[WIP] Improve dependency resolver

---

Sources/Workspace/Workspace.swift

<rdar://problem/47011812> SwiftPM removes the resolved file when the manifest has parsing errors

 [Workspace] Don't validate the pins when there are errors

---

Sources/SourceControl/Repository.swift
Sources/Workspace/Workspace.swift

We don't expect to ever have two checkouts with same name at a time so
there is no need of a suffix for them.
<rdar://problem/46423708>

[Workspace] Eliminate suffix from checkouts dirname

---

Sources/Build/BuildPlan.swift

[SR-8646] BuildPlan.Error.missingLinuxMain description rephrasing
Make it clear that LinuxMain.swift must be at the top level of the Tests directory.
Tests do not appear to quote error messages.

[Build] Clarify `BuildPlan.Error.missingLinuxMain`

---

Package.swift

As discussed [here](https://forums.swift.org/t/using-swiftpm-from-carthage/18912/4).
This will make it easier for command-line tools like Carthage to use code from SwiftPM.

Add a static version of libSwiftPM

---

Package.swift
Sources/Basic/ByteString.swift
Sources/Utility/Version.swift

This will also simplify slightly the following PR that implements `hash(into:)`.

Drop support for swift language version 4.0

---

Sources/Basic/KeyedPair.swift
Sources/Basic/ObjectIdentifierProtocol.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageModel/Package.swift
Sources/Utility/ArgumentParser.swift
Sources/Xcodeproj/XcodeProjectModelSerialization.swift

Took the opportunity to resolve a few FIXMEs that still did not use Swift 4.2's automatic Hashable synthesis.

Resolve Hashable related warnings

---

Utilities/Docker/docker-utils

Fix the docker-utils script to replace the `swift-build`, `swift-test` and `swift-run` commands with a single `spm` command to execute the `spm` script in the container.

Fix docker-utils to use the new spm script

---

Sources/PackageGraph/PackageGraphLoader.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageGraphTests/XCTestManifests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

These errors are pointless when there are already errors in the graph
and they make it difficult to focus on the real issues.
<rdar://problem/47410017> Supress "product dependency not found" errors when there are already errors in the graph

[PackageGraph] Supress product dependency not found errors

---

Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift
Utilities/bootstrap

On Apple platforms, Clang accepts -isysroot to indicate the sysroot,
while on Linux, it is --sysroot. Similarly, on Apple platforms the
environment variable SDKROOT indicates the sysroot, while on Linux it is
SYSROOT.
rdar://47367002

Use the correct sysroot spellings on Darwin and Linux

---

Sources/PackageGraph/DependencyResolver.swift
Sources/PackageModel/ToolsVersion.swift
Sources/Workspace/PinsStore.swift

While looking through the source, I noticed that some of these could be removed.

Synthesize Equatable where possible

---

Sources/Workspace/Destination.swift

Make `DestinationError` public so it can be catch outside.

public DestinationError

---

Fixtures/Miscellaneous/ParseableInterfaces/Package.swift
Sources/Build/BuildPlan.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/XCTestManifests.swift

Teach SwiftPM to pass `-emit-parseable-module-interface-path` if the
`--enable-parseable-module-interfaces` option is set.

[build] Add flag to enable parseable module interfaces

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

The issue is that even when a custom target path is specified in manifest,
it still shows an error message asking to specify a path. The fix is to check
if a path is already specified but does not exist, then it indicates the path
dose not exist. 
A test is added for the fix.
Resolves [SR-9558](https://bugs.swift.org/browse/SR-9558).

[PackageLoading] Improve error message when a custom target path does not exist

---

Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/PackageGraph/Pubgrub.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/SourceControl/InMemoryGitRepository.swift
Sources/TestSupport/MockDependencyResolver.swift
Sources/TestSupport/TestWorkspace.swift
Sources/Workspace/CheckoutState.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This improves handling of branch-based inside the resolver which leads
to a deterministic handling of the revision that is picked as part of
the resolution process. This also fixes the bug that branch-based
dependencies were being always resolved from HEAD (if there was no build
cache) when a resolved file was present.
<rdar://problem/45289738> Dependency resolution doesn't respect the resolved file for branch-based dependencies when starting resolution process from scratch

[PackageGraph] Improve handling of branch-based dependencies

---

Sources/Build/BuildPlan.swift
Sources/Build/Toolchain.swift
Sources/Build/Triple.swift
Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleMapTests.swift
Utilities/build_ubuntu_cross_compilation_toolchain

The dynamic library extension is entirely derivable from the target
triple and does not need to be parameterized nor be made part of the
Toolchain.

Move dynamicLibraryExtension to an extension method on Triple

---

Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift

This is also something that doesn't belong here and is not useful
to override at this level.

Move sysrootFlag into UserToolchain

---

Sources/Basic/FileSystem.swift
Sources/Build/BuildPlan.swift

- FileSystem: `if #available(macOS 10.12, *)` is also true on Linux, so
the #if is a no-op
- The exclusion of -static-stdlib has nothing to do with the host OS,
this correctly excludes the flag when the *target* is Linux so that
this works correctly when building on Linux or x-compiling from macOS

Clean up some compile time checks which should be runtime

---

Package.swift
Sources/SPMPackageEditor/ManifestRewriter.swift
Sources/SPMPackageEditor/PackageEditor.swift
Sources/swiftpm-manifest-tool/main.swift
Tests/SPMPackageEditorTests/AddPackageDependencyTests.swift
Tests/SPMPackageEditorTests/AddTargetDependencyTests.swift
Tests/SPMPackageEditorTests/AddTargetTests.swift
Tests/SPMPackageEditorTests/PackageEditorTests.swift

This adds functionality to mechanically edit the Package.swift file
using the SwiftSyntax library. The functionality is encapsulated in
a PackageEditor target and is driven using a new "swiftpm-manifest-tool"
tool. This tool is an implementation detail and the actual functionality
will be available using the `swift package` tool.

Add functionality to mechanically edit Package.swift file

---

.gitignore

We shouldn't be tracking these for SwiftPM unless really need to.

Add .swiftpm and Package.resolved to gitignore

---

Sources/PackageGraph/Pubgrub.swift

Otherwise, we end up doing a lot of unnecessary work upfront.

[Pubgrub] Lazily check for available versions

---

Sources/PackageGraph/Pubgrub.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/XCTestManifests.swift

This is no longer required because the postive dictionary already
contains the intersections.

[Pubgrub] Kill Solution.versionIntersection(for:)

---

Sources/Basic/ByteString.swift

- Also, provide a direct initializer from ArraySlice -- this is not efficient,
but at least is more obvious than a reliance on inlining to even get
acceptable performance.

[ByteString] Make inlinable.

---

Tests/BuildTests/BuildPlanTests.swift

Current `Siwftpm` test supports only Linux of `x86_64`  and `macOS`, 
add support to Linux of  `s390x` as well as other archs.

Support s390x as well as other platforms

---

Fixtures/DependencyResolution/External/Complex/app/Package.swift
Sources/PackageModel/Manifest.swift
Tests/CommandsTests/PackageToolTests.swift

It’s possible that the reason `platforms` was missing from the JSON output was because the `Codable` `encode` method for `Manifest` is custom. If so I offer to supplement the tests to check for this condition. Would that be ok?
Also I feel at the least I should supplement one of the fixtures to specify platforms and check for that. Can I and if so, which?

Add `platforms` to dump-package output

---

Sources/PackageGraph/Pubgrub.swift
Tests/PackageGraphTests/PubgrubTests.swift

We shouldn't need to normalize (not foo empty) because the intersection
computation was just broken for this case.

[Pubgrub] Fix inverse intersection computation for empty terms

---

Sources/PackageGraph/Pubgrub.swift
Tests/PackageGraphTests/PubgrubTests.swift

Fix non-determinism in tests (thanks to dict iteration in DependencyGraphBuilder) and bubble up errors instead of asserting on non-pubgrub errors. Also assert that incompatibilities have at least a single term after normalization so that the check for that in `isCompleteFailure` can be removed.

[Pubgrub] Minor changes

---

Sources/PackageGraph/Pubgrub.swift

A temporary change, outputting the root cause directly in case of conflict.
The output looks like this:
`
Root cause: {cache[https://github.com/tettoffensive/Cache.git] 4.1.3..<4.2.0} noAvailableVersion because of {¬cache[https://github.com/tettoffensive/Cache.git] 4.1.3..<4.2.0, myserver[/Users/kilian/Desktop/Ian] 1.0.0} root
`

[Pubgrub] Print root cause directly if conflict occurs

---

Sources/Xcodeproj/XcodeProjectModelSerialization.swift

Handle unexpected build setting value type in Xcodeproj's `PropertyListDictionaryConvertible.asPropertyList()` with a precondition violation.
One less fix me. 👍

[Xcodeproj] Handle unexpected build setting value type

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageGraph/PackageGraphRoot.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift
Tests/XcodeprojTests/GenerateXcodeprojTests.swift

Using root package's name as the identity doesn't really work properly
because there is no way to override the basename in the urls for
package dependencies. This does require that root package's basename
is same as the dependency url's basename but that is better than having
no solution for this.
<rdar://problem/48520076>

[PackageGraph] Use basename as identity of root packages

---

Sources/Build/BuildDelegate.swift
Sources/Build/BuildPlan.swift
Sources/Build/SwiftCompilerOutputParser.swift
Sources/Commands/SwiftTool.swift
Sources/SPMUtility/ProgressAnimation.swift
Tests/BuildTests/SwiftCompilerOutputParserTests.swift
Tests/CommandsTests/RunToolTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift

Reverts apple/swift-package-manager#1934
Following tests started failing: 
```
11:56:13 Failing Tests (4):
11:56:13     swift-package-tests :: swift-package-init-exec.md
11:56:13     swift-package-tests :: swift-package-init-lib.md
11:56:13     swift-package-tests :: swift-package-with-spaces.txt
11:56:13     swift-package-tests :: swift-run.md
```

Revert "Update the build animation for each Swift compiler task"

---

Tests/PackageGraphTests/PubgrubTests.swift

Actually use the new assertions funcs in a bunch of tests that weren't yet and move some stuff around so that the actual tests aren't buried deep in the file.

[PubgrubTests] General cleanup

---

Package.swift

If SWIFTCI_USE_LOCAL_DEPS is set, and we are not bootstrapping, get the
llbuild sources from ../llbuild. This allows packages that import
swiftpm in swift-ci, such as sourcekit-lsp, to get all the sources from
the local checkouts created by update-checkout.

Use local llbuild sources if requested in swift ci

---

Sources/SPMUtility/ArgumentParser.swift

Hi.
I added a default value for the kind parameter in some methods of the ArgumentParser class.
For the user, it will look like this:
```
let package: PositionalArgument<String> = parser.add(positional: "package name of the year", usage: "The name of the package")
```
Was:
```
let package = parser.add(positional: "package name of the year", kind: String.self, usage: "The name of the package")
```
Sometimes it is useful.

Add default value for kind parameter

---

Sources/Build/BuildPlan.swift
Sources/Build/Toolchain.swift
Tests/BuildTests/BuildPlanTests.swift

<rdar://problem/48696675> Add toolchain's usr/lib directory in the linker search path

[Build] Add linker search path to lib dir in the toolchain

---

Sources/Build/llbuild.swift
Sources/Commands/SwiftTool.swift
Tests/BuildTests/BuildPlanTests.swift

llbuild doesn't need `resolvedFile` path at all.

Remove unused dependency

---

Sources/Build/BuildPlan.swift

It seems not used anywhere in the project.

BuildPlan.regenerateManifestToken is not used

---

Sources/SPMUtility/ArgumentParser.swift
Tests/UtilityTests/ArgumentParserTests.swift

In larger command line tools there can be a few levels of subparsers and a top level USAGE description may not be able to capture all varieties of sub-commands. It would help users of these tools if they can get USAGE strings for lower level sub parsers.

Allow subparsers to have Usage strings

---

Sources/PackageDescription4/Package.swift

Support Windows as an OS and use `ucrt` for the C library.

PackageDescription: use the correct C provider on Win32

---

Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/SPMUtility/URL.swift
Tests/UtilityTests/StringTests.swift

This is just a simple fix until we get rid of this method completely..
<rdar://problem/48926287>

[SPMUtility] Avoid detecting paths containing @ as URLs with schemes

---

Sources/PackageGraph/DependencyResolver.swift
Sources/TestSupport/DiagnosticsEngine.swift
Tests/PackageGraphTests/DependencyResolverTests.swift

Fixes [SR-7829](https://bugs.swift.org/browse/SR-7829).
Hi, this is my first contribution here, so let me know if there's anything I should do differently!
Given a `Package.swift` which depends on a tag which does not exist, like so:
```swift
.package(url: "https://github.com/apple/swift-package-manager.git", .exact("123.0.0"))
```
SwiftPM would generate a diagnostic like this:
```
error: dependency graph is unresolvable; found these conflicting requirements:
Dependencies: 
https://github.com/apple/swift-package-manager.git @ 123.0.0
```
After this patch it generates this error:
```
error: couldn't find tags for the following specified versions:
swift-package-manager[https://github.com/apple/swift-package-manager.git] @ 123.0.0
```
Some questions:
1. Is the place I do the diagnosis here a …

Fix SR-7829: Bad error message when a tag doesn't exist

---

Sources/SPMUtility/ArgumentParser.swift

closes SR-9696
https://bugs.swift.org/browse/SR-9696
`ArgumentParserError` and `ArgumentConversionError` make confirming to `LocalizeError`.
This PR may help to read error when using these errors as directly.

[SR-9696] Confirm some errors to LocalizedError

---

Sources/SPMLLBuild/llbuild.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

We were not handling fatal errors from the build engine that can happen
in rare situations (such as the db being deleted while a build is in
progress). In those cases, llbuild returns an empty value for the
overall result and reports errors via the delegate. This implements the
delegate and throws the errors when this happens.

[SPMLLBuild] Handle fatal errors from the build engine

---

Sources/Build/BuildDelegate.swift
Sources/Build/SwiftCompilerOutputParser.swift
Tests/BuildTests/SwiftCompilerOutputParserTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift

Improved the build animation by:
* Printing `[finished_count/scanned_count]` instead of `[finished_count/started_count]` to get a higher estimate quicker of the total number of tasks
* Printing only when `finished_count` changes, and not when the second value changes, to avoid initial `[0/1]` updates.
* Stripping references to paths inside the build directory to only mention the file name instead

Improve build animation

---

Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/Pubgrub.swift
Tests/PackageGraphTests/PubgrubTests.swift

Moved most of the current implementation with some minor changes into DiagnosticReportBuilder. 
There's also still a bug where it's reporting the wrong root cause thanks to the change in 
a4639be 😕 
Due to the `skipDiagnosticAssert` param in the relevant tests this currently passes all of them. The graphs are correctly being diagnosed as unresolvable, the diagnostic is wrong though.

Error Reporting

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/Pubgrub.swift
Sources/Workspace/Workspace.swift

This adds a hidden flag `--trace-resolver` which will generate resolver
trace in the build directory. Useful for debugging.
<rdar://problem/48141259> [PubGrub] Implement an option to redirect the pubgrub log to a trace file

[Pubgrub] Add an option to generate resolver trace

---

Utilities/bootstrap

Moving CoreFoundation into the root is needed to actually get the proper
dependency tracking for Foundation builds. This adjusts the use of it
in swift-package-manager.

build: adjust for new build layout

---

Sources/Xcodeproj/XcodeProjectModelSerialization.swift

"English" as a development region (as well as other spelled out languages) has been deprecated for many years. While Xcode 10.2 is the first Xcode release to make this a formal warning, all versions of Xcode that support Swift will be happy with ISO codes.
Localizations from project generated from `master`:
Localizations from project generated from this branch:

[Xcodeproj] Use "en" for developmentRegion

---

Sources/Xcodeproj/XcodeProjectModel.swift
Sources/Xcodeproj/pbxproj().swift

The new code closely mirrors how OTHER_CFLAGS works. This fixes an issue where if you had a target with C++ code and used `cxxSettings: [.unsafeFlags(...)]`, then `swift package generate-xcodeproj` would crash.

[Xcodeproj] Added code for handling OTHER_CPLUSPLUSFLAGS

---

Sources/Basic/TerminalController.swift

This file will definitely need another look to make sure it actually does what it's supposed to do, but for now, just not using ioctl is enough to get this compiling on Windows.

Make TerminalController compile on Windows

---

Sources/Basic/FileSystem.swift
Sources/clibc/include/clibc.h
Tests/BasicTests/FileSystemTests.swift

Replace the use of fts with Foundation's Directory Enumerator, which (on
Darwin/Linux) calls fts instead, but is cross platform for Windows.

Remove use of fts

---

Sources/Basic/ProcessSet.swift

Windows doesn't have SIGKILL, we'll use SIGTERM instead

Fix Up ProcessSet for Windows

---

Sources/Basic/Lock.swift

The intention of this PR is to rename two simple variables on the file Lock.swift to give more context to them.

Rename variables at Lock.swift

---

Sources/Basic/Lock.swift

Some variables were not changed when being renamed on Windows.

Fix Compilation of Lock.swift on Windows

---

Sources/Build/BuildPlan.swift

This fixes Swift doing a full rebuild when you switch between a tty, and
non-tty
https://bugs.swift.org/browse/SR-7982
Depends on https://github.com/apple/swift/pull/24144

Optionally use non-frontend color-diagnostics flag

---

Sources/Basic/FileSystem.swift

On Windows Symlinks aren't marked as regular files, but they can still
be executed, so isExecutable should indicate as such.

Symlinks can be executable

---

Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This will just generate a manifest in the current directory. The contents will be the same as for initializing a library package.
That means the contents will likely not match the filesystem layout, but I think that is OK, this will still make it easier to add a manifest to an existing project. We can improve it in the future and make the generated content based on what is actually there on the filesystem.
rdar://problem/50347943

Add new `manifest` option to `swift package init`

---

Sources/Workspace/InitPackage.swift
Tests/WorkspaceTests/InitTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

Add new `manifest` option to `swift package init` (#2106)

---

Sources/Basic/Process.swift

Once this change (and the remaining Windows PRs right now) go in, SwiftPM technically compiles on Windows. However, the bootstrap script produces `.a` static libraries. Swift on Windows currently only supports dynamic linking, so I'm working on support for that in llbuild/the boostrap script.

Port Process.swift to Windows

---

Sources/PackageGraph/PackageGraph.swift
Sources/Xcodeproj/SchemesGenerator.swift

Other clients might also want to know which test targets are relevant for a particular executable target.
rdar://problem/47648572

Move code for finding test targets into `PackageGraph`

---

Sources/PackageGraph/PackageGraph.swift
Sources/Xcodeproj/SchemesGenerator.swift

Move code for finding test targets into `PackageGraph` (#2109)

---

Utilities/bootstrap

#2118 did not update the custom invocation of `swiftc` in `process_runtime_libraries()`, which is still causing build failures in CI. This PR corrects that.
Hopefully completes work on rdar://problem/50385698.
(@aciidb0mb3r, does this need to be separately cherry-picked to swift-5.1-branch?)

Bootstrap PackageDescription with -module-cache-path

---

Utilities/bootstrap

The new XCTest build has been CMake based for ages.  This places the
Swift contents in a directory named swift in the build tree.  Update
the search path.

build: clean up the legacy paths

---

Sources/PackageDescription4/SupportedPlatforms.swift

`SupportedPlatforms.swift` contains an extra heading that is unnecessary. This PR deletes it.

Remove unnecessary heading in source docs of SupportedPlatforms.swift

---

Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift

<rdar://problem/51147551>
(cherry picked from commit 991d64a39702c53b68ed94a50848b21d844d6f2d)

[PerfTests] Fix two perf tests

---

Sources/Build/BuildPlan.swift
Sources/PackageModel/ResolvedModels.swift
Tests/BuildTests/BuildPlanTests.swift

apple/swift#25030 introduces a compatibility library that can be statically linked into binaries
in order to back-deploy runtime fixes and new features to OSes that shipped with older Swift
runtimes. This library depends on the Swift runtime being linked into the executable, so it will
cause link errors for pure Clang products (and even if it didn't, it would be a waste of code
size). When building a product without any Swift in it, ask Swift to drive the linker without
introducing any runtime compatibility libraries (and shake out a few other unnecessary linker
flags while we're here).
rdar://problem/50057445

Don't link runtime compatibility library in pure Clang targets.

---

Sources/Build/BuildDelegate.swift

If new cases are added to CommandResult we need to handle them.
Since we only care about succeeded or skipped commands, we don't
do anything here.
rdar://51069563
This is needed for the following llbuild change: https://github.com/apple/swift-llbuild/pull/487 but makes the code actually more robust to changes on that enum.

Add default case to switch on CommandResult

---

Documentation/Development.md

Hi there! I was following the development documentation, and I ran into issues because I didn't have Ninja installed. Figured I would make a note that Ninja is required to run the bootstrap.

[Documentation] Note Ninja/CMake build requirement in development docs

---

Sources/Basic/EditDistance.swift
Sources/SPMUtility/ArgumentParser.swift
Tests/UtilityTests/ArgumentParserTests.swift

We implemented a closest match comparison on the available options, and chose the option that had the least number of differences.  We limited the solution space to those options that had fewer differences than half the length of the option string.  This solution uses the new Swift 5.1 sequence difference for companions.  If no option meets the match criteria, no option is returned and the default error message is displayed.  We added some tests to verify the comparison.

[SR-10794] Close option suggestions

---

Sources/Build/BuildDelegate.swift
Sources/Build/SwiftCompilerOutputParser.swift
Tests/BuildTests/SwiftCompilerOutputParserTests.swift

<rdar://problem/49235252>
Looks like swift compiler can emit a non-parsable message in some cases.

[Build] Handle unparsable messages during message size parsing

---

Sources/Build/BuildPlan.swift
Sources/Commands/SwiftTool.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/TestSupport/SwiftPMProduct.swift

To workaround the ModuleCache issues that we've been seeing on Swift CI
<rdar://problem/51596389>

Isolate ModuleCache for SwiftPM tests

---

Tests/FunctionalTests/CFamilyTargetTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift

Using Swift to link pure C targets relies on a new Swift driver flag
introduced in https://github.com/apple/swift/pull/25330. Stage this in
by disabling tests until that change propagates.
rdar://problem/50057445

Disable pure C package tests for staging.

---

Sources/Commands/SwiftTestTool.swift
Sources/TestSupport/Resources.swift
Sources/Workspace/Destination.swift

Support new XCTest overlays

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

[Build] Disable Swift static linking on macOS

---

Sources/Workspace/UserToolchain.swift
Utilities/bootstrap

Now that we have clang shipping in the Swift toolchains, we can just
locate it in the bin dir. This also removes the hack we did for enabling
index store only on Darwin. There is a new env variable
SWIFTPM_DISABLE_CLANG_INDEX_STORE if someone wants to explictly disable
the index store.
<rdar://problem/51077480>
https://bugs.swift.org/browse/SR-10633

[Toolchain] Lookup clang in the toolchain

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Sources/Workspace/UserToolchain.swift

We got library-based llbuild execution last year and swift-build-tool invocation is just dead code at this point. We should remove it.

Remove use of swift-build-tool from SwiftPM

---

Sources/PackageLoading/ManifestLoader.swift

<rdar://problem/51725297>
(cherry picked from commit fba7a31676d5be5e851fd17ce2e6e532f1ab64eb)

Add SWIFTPM_MODULECACHE_OVERRIDE for Swift CI

---

Sources/SPMUtility/FSWatch.swift
Sources/Workspace/PinsStore.swift
Sources/Workspace/Workspace.swift

This adds a delegate method that will notify clients when the
Package.resolved file is changed outside of libSwiftPM operations. For
example, when a git operation is performed.
<rdar://problem/51762359>

[Workspace] Add ability to notify when Package.resolved file is changed

---

Sources/Build/BuildPlan.swift
Sources/PackageModel/ResolvedModels.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/FunctionalTests/CFamilyTargetTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift

apple/swift#25330 introduces a compatibility library that can be statically linked into binaries
in order to back-deploy runtime fixes and new features to OSes that shipped with older Swift
runtimes. This library depends on the Swift runtime being linked into the executable, so it will
cause link errors for pure Clang products (and even if it didn't, it would be a waste of code
size). When building a product without any Swift in it, ask Swift to drive the linker without
introducing any runtime compatibility libraries (and shake out a few other unnecessary linker
flags while we're here).
rdar://problem/50057445

[5.1] Don't link runtime compatibility library in pure Clang targets.

---

Sources/Commands/SwiftTestTool.swift
Sources/TestSupport/Resources.swift
Sources/Workspace/Destination.swift

Reverts apple/swift-package-manager#2160

Revert "Support new XCTest overlays"

---

Documentation/Development.md
Sources/Commands/SwiftTestTool.swift

[SwiftTestTool] Allow skipping SwiftPM tests using an env variable

---

Sources/Workspace/InitPackage.swift

Now that SwiftPM is more likely to checked in alongside with Xcode
artifacts, ignore the commonly ignored Xcode artifacts.

Ignore xcuserdata/

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift

Add a --jobs/-j to limit parallel compilation.

Backport PR 2127.

---

Sources/PackageDescription4/BuildSettings.swift
Sources/PackageDescription4/LanguageStandardSettings.swift
Sources/PackageDescription4/Package.swift
Sources/PackageDescription4/PackageDependency.swift
Sources/PackageDescription4/PackageRequirement.swift
Sources/PackageDescription4/Product.swift
Sources/PackageDescription4/SupportedPlatforms.swift
Sources/PackageDescription4/Target.swift
Sources/PackageDescription4/Version+StringLiteralConvertible.swift
Sources/PackageDescription4/Version.swift

This PR improves the in-source docs of the` PackageDescription` API for better readability and clarity.

Improve the in-source docs of the PackageDescription API for better readability.

---

Utilities/bootstrap

[bootstrap] Pass sdk when creating libPackageDescription

---

Sources/Basic/Path.swift
Sources/Build/BuildDelegate.swift
Sources/Build/BuildPlan.swift
Sources/Build/ToolProtocol.swift
Sources/Build/llbuild.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Sources/PackageModel/Target.swift
Sources/SPMUtility/IndexStore.swift
Sources/SPMUtility/dlopen.swift
Sources/clibc/include/indexstore_functions.h
Sources/clibc/include/module.modulemap

This is a WIP PR for implementing test discovery on linux using indexing
data. The basic idea is to leverage the IndexStore library to get the
test methods and then generate a LinuxMain.swift file during the build
process.
This PR "works" but there are a number of serious hacks that require
resolving before we can merge it.

[WIP] Implement test discovery on linux

---

Sources/Workspace/UserToolchain.swift

The non-Darwin targets do not properly support `-sdk`.  Passing this in
during a build prevents the use of `-sdk` for Swift code with the Swift
toolchain and a standalone Swift SDK for a host.  This will allow us to
begin wiring up `-sdk` for such a usage.

UserToolchain: disable use of `-sdk` on !Darwin

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

Previously we would not take the type into account and therefore reference "Sources" instead of "Tests".

This fixes the no source files message for test targets

---

Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

Before we were running into a precondition in `RelativePath`.
rdar://problem/52811361

Error out if `publicHeadersPath` is absolute

---

Sources/Commands/SwiftTool.swift

<rdar://problem/52359638> Ctrl+C on `swift build` does not interrupt build subprocess
Looks like SwiftPM became responsible for cancelling the build when it switched to
using library-based llbuild.

[Commands] Cancel build when we receive a signal

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

As [SR-11088](https://bugs.swift.org/browse/SR-11088) states, the diagnostic message can be a bit confusing in case a dependency specifies an incompatible platform version. With this pull request, I try to solve this problem using a more clear diagnostic message suggested by the reporter.

[SR-11088] Ambiguous Error when Dependency Specifies Incompatible Platform Version

---

Sources/Workspace/PinsStore.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This improves our resolution logic when we already have state and there
are updates to Package.resolved file. Previously, we were restoring the
Package.resolved file with our current state if we saw that there is
a missing entry in there. This is not correct since dependencies can
disappear as part of an update performed on some other machine (or just
switching between commits/branches without removing state).
<rdar://problem/51080676> [SR-10718]
(cherry picked from commit ab7f4741ca3a655e095b6bf67c9777b01d1b0e2b)

[Workspace] Improve how we handle changes to Package.resolved

---

Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

... using local packages
<rdar://problem/52263385> [SR-11032]: Package resolution fails when replacing remote dependency with local dependency

[Workspace] Diagnose basename mismatch when overriding

---

Sources/Build/llbuild.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/BuildTests/XCTestManifests.swift

This fixes the  build time dependency to depend on the executable
product's binary whenever it is available.
<rdar://problem/52979509>

[Build] Establish dependency on executable product when available

---

Sources/Commands/SwiftPackageTool.swift

Avoid blindly accessing the first manifest since we don't know if it was
actually loaded or not.
<rdar://problem/53157810> [SR-11146]: Swift dump-package results in a SIGILL (Illegal Instruction)

[Commands] Don't access manifest array directly

---

Sources/Workspace/Workspace.swift

This will force the resolution even if the current checkout has
everything that is required. This can be used to "refresh" the managed
dependencies contents.
<rdar://problem/51463965>

[Workspace] Add an option to force resolution

---

Sources/Commands/SwiftPackageTool.swift

This adds a `swift package _format` command to format all the sources in
a package. The swift-format binary will be looked up in PATH and
SWIFT_FORMAT. Arguments after -- will passed to swift-format as options.
For now, this is just for experimentation and not an officially
supported feature.
<rdar://problem/53549175>

[Commands] Add exprimental support for swift-format

---

Sources/Build/BuildPlan.swift
Sources/Commands/MultiRootSupport.swift
Sources/Commands/SwiftTestTool.swift

Extends the testing command for multiroot packages (see previous
commit). The test discovery doesn't work with this yet but that can be
fixed in a later commit.
<rdar://problem/53723874> Add a way to test multi root packages with swift-test

[Commands] Add test support for multiroot packages

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

SwiftPM wasn't allowing using unsafe flags in a root package that is
overriding another package.
<rdar://problem/53781795>

[PackageGraph] Fix a bug related to overridden packages and unsafe flags

---

Sources/Basic/Process.swift
Sources/Basic/ProcessEnv.swift
Sources/Basic/TemporaryFile.swift
Sources/Basic/TerminalController.swift
Sources/Build/BuildPlan.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/SPMUtility/PkgConfig.swift
Sources/TestSupport/misc.swift
Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift

Cache ProcessEnv.vars because ProcessInfo.processInfo.environment is
costly and we don't really mutate the env.
<rdar://problem/53828756>

[Perf] Cache process env

---

Sources/Build/BuildDelegate.swift
Sources/Build/BuildPlan.swift
Sources/Build/ToolProtocol.swift
Sources/Build/llbuild.swift
Sources/Commands/Options.swift
Sources/Commands/SwiftBuildTool.swift
Sources/Commands/SwiftTool.swift
Sources/TestSupport/misc.swift
Sources/Workspace/ManagedDependency.swift
Tests/BuildTests/IncrementalBuildTests.swift
Tests/BuildTests/XCTestManifests.swift

This implements caching for llbuild manifest behind
--enable-build-manifest-caching flag. This currently only works for
`swift build` invocations but there is enough facility to extend this to
other tools (we need to store more information in BuildDescription).
This works by creating a new command "PackageStructure" which depends on
the directory structure of the package, the package manifest,
Package.resolved file, build parameters and the process env.
<rdar://problem/53901583>
Here are some null build timings with and without build manifest caching (on 6 core/i9):
| Package   | without | with  |
|-----------|---------|-------|
| trivial   |  0.076  | 0.060 |
| swift-nio |  0.198  | 0.102 |
| vapor     |  0.668  | 0.192 |
| unnamed   |  1.177  | 0.216 |

Implement build manifest caching

---

Tests/BuildTests/IncrementalBuildTests.swift

`SPMLibc.sleep` should be replaced with `Thread.Sleep(for:)`.  However,
there is no use of this in the test.  Simply remove the unnecessary
import.

Tests: remove unnecessary import

---

Sources/Basic/Lock.swift
Sources/Basic/ProcessEnv.swift
Sources/SPMUtility/InterruptHandler.swift
Sources/SPMUtility/dlopen.swift

`BOOL` is now properly bridged into a boolean as `WindowsBool`.
Unfortunately, as there is no current CI for s-p-m on Windows, this was
not caught.  Update s-p-m so that we can enable CI.

Windows: `BOOL` is now WindowsBool

---

Sources/SPMUtility/IndexStore.swift

Out-of-line the flags for `dlopen` since the flags are not uniformly
available.  This is needed for Windows which does not have the Unix
style `dlopen`.

SPMUtility: out-of-line flags for `dlopen`

---

Sources/SPMUtility/Platform.swift

This private method is only used on macOS targets, but was globally
defined.  This depends on `confstr` which is part of the C library on
Unix systems.  However, it is not available on Windows.  Limit the
function to the platform where it is used.

SPMUtility: limit private method to `macOS`

---

Sources/Basic/TemporaryFile.swift

There is no equivalent to the POSIX `EDQUOT` error on Windows.  Since it
cannot arise, simply ignore it.

Basic: Windows does not support `EDQOT`

---

Sources/Basic/PathShims.swift

Use `createSymbolicLink` from Foundation rather than using `symlink`
from the C library which is not portable (Windows does not provide
`symlink`).

Basic: replace `symlink` with Foundation

---

Sources/Build/BuildPlan.swift

Currently the extra-cpp-flags specified in a destination.json file are not
passed through to clang. This is because the extra cpp flags are not being
encoded. This patch fixes that.

Add extraCPPFlags to BuildParameters

---

CMakeLists.txt
Sources/Basic/CMakeLists.txt
Sources/Build/CMakeLists.txt
Sources/CMakeLists.txt
Sources/Commands/CMakeLists.txt
Sources/PackageDescription4/CMakeLists.txt
Sources/PackageGraph/CMakeLists.txt
Sources/PackageLoading/CMakeLists.txt
Sources/PackageModel/CMakeLists.txt
Sources/SPMLLBuild/CMakeLists.txt
Sources/SPMLibc/CMakeLists.txt
Sources/SPMUtility/CMakeLists.txt
Sources/SourceControl/CMakeLists.txt
Sources/Workspace/CMakeLists.txt
Sources/Xcodeproj/CMakeLists.txt
Sources/clibc/CMakeLists.txt
Sources/swift-build/CMakeLists.txt
Sources/swift-run/CMakeLists.txt
Sources/swift-test/CMakeLists.txt
Sources/swiftpm-xctest-helper/CMakeLists.txt

This enables proper use of modern CMake for building s-p-m.  This makes
it extremely easy to bootstrap swift-package-manager for other
platforms.

build: add a CMake based build for bootstrapping

---

Sources/Basic/TemporaryFile.swift

`FileManger.removeItem(atPath:)` will remove the file or directory.
`rmdir` will only remove the directory if it is empty, which is the
default behaviour unless an explicit delegate is provided to the
FileManager.  Collapse the two cases into one which enables this path to
work on Windows which does not provide `rmdir`.

TemporaryFile: simplify clean up

---

Sources/Basic/TemporaryFile.swift

Use `NSTemporaryDirectory` to compute the temporary directory in a
portable way.

Basic: use `NSTemporaryDirectory` to compute the temporary directory

---

Sources/PackageGraph/CMakeLists.txt

Update the source list for PackageGraph.  This allows us to bootstrap on
Windows again.

build: update PackageGraph CMakeLists

---

Sources/PackageGraph/CMakeLists.txt
Sources/PackageGraph/CheckoutState.swift
Sources/PackageGraph/PinsStore.swift
Sources/Workspace/CMakeLists.txt
Sources/Workspace/misc.swift
Tests/WorkspaceTests/PinsStoreTests.swift

This will allow us to access PinsStore inside the dependency resolver.

[NFC] Move PinsStore to PackageGraph

---

Sources/Basic/CMakeLists.txt
Sources/Basic/OSLog.swift

This will allow us to us os_log without availability and platform
checks.

[Basic] Add a thin wrapper around OSLog

---

Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/Pubgrub.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/TestSupport/MockDependencyResolver.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/XCTestManifests.swift

This adds support for handling tools version in the resolver as an
incompatibility instead of it being implicit when computing which
version are available. This is a big improvement over the current legacy
resolver where we emit no diagnostics if the resolution fails because of
the tools version.
<rdar://problem/53947020>

[PubGrub] Add support for handling tools version in the resolver

---

Sources/PackageGraph/Pubgrub.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/XCTestManifests.swift

This will avoid going into infinite loops when there are cycles in
branch or local packages. Cycles are ok in the resolver (as long they
are satisfied) and are diagnosed at a later stage.
<rdar://problem/54586155>

[PubGrub] Avoid infinite looping when processing inputs

---

Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/XCTestManifests.swift

These are working correctly now so re-enable them.
Note that cycles are ok in the dependency resolver as long as it's
resolvable. However, they are diagnosed later during package loading.

[PubGrub] Re-enable some cycle related tests

---

Sources/PackageGraph/VersionSetSpecifier.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageGraphTests/VersionSetSpecifierTests.swift

Handle two cases where the set difference with .ranges and .exact was
being wrongly computed. See the new test cases in
VersionSetSpecifierTests for the examples.
<rdar://problem/54645274>

[PubGrub] Fix an issue in set difference computation

---

Sources/Basic/FileSystem.swift
Sources/Basic/TemporaryFile.swift
Sources/Commands/SwiftTestTool.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/SourceControl/GitRepository.swift
Sources/TestSupport/misc.swift
Tests/BasicTests/FileSystemTests.swift
Tests/BasicTests/LockTests.swift
Tests/BasicTests/OutputByteStreamTests.swift
Tests/BasicTests/POSIXTests.swift
Tests/BasicTests/PathShimTests.swift
Tests/BasicTests/ProcessSetTests.swift
Tests/BasicTests/ProcessTests.swift
Tests/BasicTests/TemporaryFileTests.swift
Tests/ExtraTests/Tests/ExtraTests/FSWatchTests.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
Tests/WorkspaceTests/InitTests.swift

Replacing the TemporaryFile/TemporaryDirectory classes with withTemporaryFile/withTemporaryDirectory functions.
Using classes+deinit for resource management is problematic because the lifetime of classes is not guaranteed to be the lexical scope. Compiler optimizations may shrink the lifetime to the last use. One way to fix this is would be to make sure that the TemporaryFile class instances are referenced as long as the managed resource (= the file or directory) is in use. That could be done e.g. with stdlib's withExtendedLifetime function. But that would be cumbersome.
The better way to fix this is to change the ABI to a closure based approach (there are several examples for this in the swift stdlib, e.g. withExtendedLifetime). It does not only fix the lifetime problem, but also makes …

[Basic] Fix the lifetime problems of utilities for creating temporary files and directories.

---

Sources/PackageGraph/Pubgrub.swift
Tests/PackageGraphTests/PubgrubTests.swift

PubGrub normalizes some ranges by omitting the lower or upper bounds in
some cases. This leads to easier to read diagnostics (see updated
diagnostics in the unit tests).
<rdar://problem/54797988>

[PubGrub] Normalize ranges so they're easier to read in the diagnostics

---

Utilities/bootstrap

In order to support libdispatch tests on Windows, the build tree layout needs to
be adjusted.  Account for this path adjustment here in a compatible manner.

build: stage movement for dispatch build output

---

Sources/Basic/TemporaryFile.swift
Tests/BasicTests/TemporaryFileTests.swift
Tests/BasicTests/XCTestManifests.swift

Fixed a TemporaryFile crash caused by higher ASCII characters in the directory path.

Fixed a TemporaryFile crash

---

Sources/Build/BuildDelegate.swift
Sources/Commands/SwiftTestTool.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/Pubgrub.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/SPMTestSupport/MockDependencyResolver.swift
Sources/SourceControl/GitRepository.swift
Sources/SourceControl/RepositoryManager.swift
Sources/TSCBasic/Await.swift
Sources/TSCBasic/CodableResult.swift
Sources/TSCBasic/Process.swift
Sources/TSCBasic/Result.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/TSCBasicTests/AwaitTests.swift
Tests/TSCBasicTests/ResultTests.swift
Tests/TSCBasicTests/XCTestManifests.swift

This Pull Request removes implementation of `Result` from the Basic module - in favor of using the same enum from the Standard Library.
`Basic.Result` was a public type so this change can possibly be breaking, but in this case projects using it should probably be using the Standard Library version anyway. Code using `AnyError` and `StringError` will continue to work as public extensions on `Swift.Result`
I've broken down the refactoring into small commits for reviewers convenience and I am planning to squash if the PR will be accepted.

Use Result from the Standard Library

---

Sources/TSCTestSupport/Product.swift

Since this effects the tests that use swift-test.

[TestSupport] Unset the env variable that allows skipping tests

---

Sources/Workspace/Workspace.swift

There are reports of crashes in this area but it's not clear how would
this ever happen since we shouldn't get here unless we know there is an
available tag for the version. I've added some user visible logging so
someone who runs into this can file a bug.
<rdar://problem/55040410>

[Workspace] Turn an IUO into a throwing error

---

Utilities/bootstrap

Use the stable swiftinterface format for PackageDescription so we can
actually mix and match compiler for the runtime libraries on macOS.
While PackageDescription is not really ABI stable, we don't need to
worry about that since it's always linked into the clients and it only
depends on system libraries.
<rdar://problem/54357929>

[bootstrap] Install swiftinterface instead of swiftmodule for PD

---

Tests/BuildTests/BuildPlanTests.swift

Replace the hardcoded target triple with the generic target triple variable `defaultTargetTriple`, so that tests on platforms rather than x86_64 got passed.

Use generic TargetTriple in BuildTests

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

SwiftPM will now generate dSYM only in release mode. We should also
strip the debug symbols from the release binary, which I am tracking
separately.
<rdar://problem/43394671>

[Build] Generate dSYM in release mode

---

Sources/Build/BuildPlan.swift
Sources/Build/llbuild.swift
Tests/BuildTests/BuildPlanTests.swift

This implements proper debugging support on both Darwin and Linux. On
Darwin, this means SwiftPM will pass the swiftmodule file to the linker
and on Linux, it'll link the wrapped module obtained using Swift
compiler's modulewrap subtool.
<rdar://problem/29228963>
<rdar://problem/52118932>
https://bugs.swift.org/browse/SR-3280

[Build] Fix debugging for products built by SwiftPM

---

Sources/CMakeLists.txt
Sources/TSCBasic/CMakeLists.txt
Sources/TSCUtility/CMakeLists.txt
Sources/Workspace/CMakeLists.txt

The CMake build got out of date. This allows compilation again.

Fix CMake Build

---

Sources/Workspace/Destination.swift

This is particularly useful for Windows which doesn't currently have a
standardized place to install the toolchain to.
~~I'm not at all attached to using `SWIFT_TOOLCHAIN_PATH` so if there's a better name, I can change it.~~

Enable SWIFTPM_CUSTOM_BINDIR in Non Debug 

---

Sources/TSCBasic/TerminalController.swift

By default, Windows doesn't interpret VT100 sequences.
Previously:
```
☐[31m☐[1merror: ☐[0munknown option --bin-path; use --help to list available options
```
Now (pretending error is in red):
```
error: unknown option --bin-path; use --help to list available options
```

Enable VT100 Sequences on Windows

---

CMakeLists.txt

CMAKE_Swift_LANGUAGE_VERSION isn't supported until CMake 3.16 which
isn't generally released yet. For anything less, pass in -swift-version
4.2 with add_compile_options.

[CMake] Manually Set swift-version

---

Utilities/bootstrap

Stage the changes needed in the include path for libdispatch with the
new CMake support.

build: add support for new build layout for libdispatch

---

Sources/PackageGraph/Pubgrub.swift
Sources/PackageLoading/ModuleMapGenerator.swift
Sources/TSCUtility/PkgConfig.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift

Fix warnings

---

Sources/Build/Triple.swift
Utilities/bootstrap

Absense of environment in the triple seems to cause issues during
debugging. Adding this to unblock my integration test but we should just
switch to asking clang for the host target triple using `clang
-print-target-triple`.

[Build] Add -gnu in x86_64 Linux's triple

---

Sources/PackageGraph/Pubgrub.swift

This improves cloning performance when a Package.resolved file is present.
<rdar://problem/55182904>

Implement prefetching in the new resolver

---

Sources/TSCBasic/Path.swift

Foundation will do the same thing: removing . and .. and will also have
the benefit of normalizing the windows paths to use '/' instead of '\'

Defer to Foundation for Path Normalization in Windows

---

Sources/TSCBasic/Path.swift

~~On Windows, Foundation has already implemented cross platform path
handling logic and it would be convenient to use it for enabling Windows
support. This allows Foundation to optionally be used rather than
SwiftPM's existing path handling which doesn't handle Windows paths.
Since Foundation is cross platform for any language Swift supports, this
adds an option to enable it for any platform that might in the future
want it.~~
~~I've also included a sample of how the flag would be used. `USE_FOUNDATION` doesn't seem like the most descriptive thing for what it does, but I don't currently have a better name.~~
On Windows, Foundation has already implemented cross platform path
handling logic and it would be convenient to use it for enabling Windows
support.

Use Foundation for Paths Splitting on Windows 

---

Sources/PackageLoading/PackageBuilder.swift
Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

I found some bugs in the new target sources builder thanks to benchmark
package. I'll fix them properly in a separate commit but these fixes
should unblock CI. We also need to build swift benchmarks in SwiftPM PR
testing.
<rdar://problem/56780087>

[PackageLoading] Disable modulemap mixed with sources check

---

Sources/Commands/SwiftPackageTool.swift
Sources/SPMTestSupport/TestWorkspace.swift
Sources/TSCTestSupport/XCTAssertHelpers.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

- Added `swift package --dry-run`
- Added prettyPrinted to `Requirement`
- Added test

[SR-7836] Added swift package update --dry-run

---

Sources/PackageDescription4/SupportedPlatforms.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift

Gated behind version 5.2. This will allow for example, Windows specific
c/cxx flags to be passed to build indexstoredb and llbuild.
See also: https://forums.swift.org/t/adding-support-for-windows-as-a-platform/30158

Add Windows as a Supported Platform

---

Sources/Commands/SwiftTestTool.swift

Avoid building all the other test products if one test product is requested through the `--test-product` option.

Only build requested test product if one is specified using --test-product

---

Sources/PackageLoading/ManifestLoader.swift
Utilities/bootstrap

Thanks to https://github.com/apple/swift/pull/28035, we can start
simplifying the bootstrap script and remove lots of horrible hacks that
we currently have.
<rdar://problem/56849141>

[bootstrap] Remove fake toolchain dead code from the bootstrap script

---

Tests/FunctionalTests/MiscellaneousTests.swift

This test fails sometimes on linux bots. I suspect that's because of the
module cache issue but we don't know for sure because the full log is
not dumped.
<rdar://problem/56792965>

[FunctionalTests] Include stderr in testCompileFailureExitsGracefully

---

Sources/Build/BuildPlan.swift

Test discovery requires an index store for the test targets to discover the tests.

Build an index store for test targets if test discovery is enabled

---

Sources/Build/BuildPlan.swift

The generated test lists import the test target with `@testable` so we need to build the test module with testability enabled.

Enable testing when building when test discovery is enabled

---

Sources/Build/BuildPlan.swift
Tests/BuildTests/BuildPlanTests.swift

This will allow test bundles to find any linked dylibs in the build
directory.
<rdar://problem/56793593>

[Build] Provide correct rpath for macOS test bundles

---

Fixtures/Miscellaneous/EchoExecutable/Sources/secho/main.swift
Sources/Build/BuildPlan.swift
Sources/Build/Triple.swift
Sources/Commands/SwiftTool.swift
Sources/PackageDescription4/Package.swift
Sources/PackageDescription4/SupportedPlatforms.swift
Sources/PackageModel/Platform.swift
Sources/TSCBasic/Process.swift
Sources/TSCLibc/libc.swift
Sources/TSCUtility/FSWatch.swift
Sources/TSCUtility/IndexStore.swift
Sources/TSCUtility/InterruptHandler.swift
Sources/TSCUtility/Platform.swift
Sources/TSCUtility/dlopen.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleMapTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/TSCBasicTests/FileSystemTests.swift

This pull was used to build SPM natively on Android in [the Termux app](https://termux.com/), similar to apple/swift#27167. The first commit consists of compile-time changes that were needed to build SPM itself natively on an Android host, whereas the second commit adds some support for using SPM to build for Android. None of the second commit was needed to run the SPM tests on Android, so any of it can be removed if it interferes with any other plans for Android compilation, though there's currently only two mentions of Android in the SPM source.
This pull was tested against the 10/24 source snapshot and out of 623 test cases run, it reports 72 failing. Most are related to looking for PackageDescription4 and other dependencies of SPM itself, [which fails here because it can't find them …

Android: add native platform support

---

Sources/TSCBasic/Process.swift

On systems like Fedora and Arch, glibc 2.30 is the default version, this PR fixes some errors compiling SwiftPM.
This have been tested and compiles on the latest Arch Linux using glibc 2.30, i haven't tested on Ubuntu, since i figure there are CI in place to test that :)

Adding support for glibc 2.30

---

Sources/PackageGraph/PinsStore.swift
Sources/PackageLoading/PackageBuilder.swift
Sources/PackageLoading/ToolsVersionLoader.swift
Sources/SPMTestSupport/MockDependencyGraph.swift
Sources/SPMTestSupport/MockDependencyResolver.swift
Sources/SourceControl/RepositoryManager.swift
Sources/TSCBasic/DictionaryExtensions.swift
Sources/TSCBasic/JSON.swift
Sources/TSCBasic/JSONMapper.swift
Sources/TSCUtility/ArgumentParser.swift
Sources/Workspace/ManagedDependency.swift
Sources/Workspace/Workspace.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift
Tests/SourceControlTests/GitRepositoryTests.swift
Tests/TSCBasicTests/DictionaryExtensionsTests.swift
Tests/TSCBasicTests/JSONMapperTests.swift
Tests/XcodeprojTests/PackageGraphTests.swift

Remove TSCBasic.Dictionary.init(items:) to favour using the new Standard Library Dictionary initialisers and replace all uses of it.

Remove TSCBasic.Dictionary.init(items:)

---

Sources/TSCUtility/ArgumentParserShellCompletion.swift

The code that generates the bash-completion script didn't produce a
working script. The generated function was missing the variables for
the currently typed word (`$cur`) and the previously typed word (`$prev`).
The change also includes a call to the `complete` command to register
the function.
The tests were also updated to match the change.

Fix bash completion script code

---

Utilities/bootstrap

The recent CMake changes require explicitly passing the SDK when
building llbuild. This is essentially a small bug in Swift CMake
support.
<rdar://problem/57430915>

[bootstrap] Fix desktop bootstrapping

---

Utilities/bootstrap

New cmake is looking for sqlite in the wrong place for some reason. We
can fix it by explicitly passing -DSQLite3_INCLUDE_DIR=$(xcrun -sdk
macosx -show-sdk-path)/usr/include in the cmake invocation.
<rdar://problem/57437541>

[bootstrap] Force SQLite to be picked from the SDK for llbuild

---

Sources/PackageDescription4/CMakeLists.txt

This automatically computes the library name and permissions at the time
of installation.  It also adds proper dependencies for the install rules
unlike the installation of files.

build: use `install(TARGETS)` rather than `install(FILES)`

---

Sources/Build/Triple.swift

This adds a mirroring property `sharedLibraryExtension` to Triple for
computed values for the extensions.  This is important to ensure that we
will be able to cross-compile properly rather than hardcoding the
extension, which makes execution difficult.

Build: add new `executableExtension` property (NFC)

---

Sources/TSCBasic/PathShims.swift

`realpath` will heap allocate the path, and `String(cString:)` will copy
the heap allocation.  This results in a memory leak due to the allocated
memory never being freed.  Ensure that we deallocate the memory.

TSCBasic: plug a memory leak

---

CMakeLists.txt
Sources/PackageDescription4/CMakeLists.txt

PackageDescription4 requires that Foundation be re-exported for users.

build: add re-export for Foundation

---

Sources/PackageLoading/Target+PkgConfig.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/TSCBasicTests/FileSystemTests.swift
Tests/TSCBasicTests/PathShimTests.swift
Utilities/bootstrap

With this pull, I got SPM built natively on Android and all the tests passing with the Nov. 8 source snapshot from the master branch.

Android: add bootstrap build support and fix tests

---

Sources/Workspace/CMakeLists.txt

Interpreter support on Windows is currently unavailable.  Support
compiled manifests for Windows.  On other platforms, this can be tested
by setting `_SWIFTPM_USE_COMPILED_MANIFEST` in the environment.  There
are dependencies on swift-tools-support-core for this to actually
function on Windows.

build: update CMake build for new file

---

CMakeLists.txt
Sources/SPMLLBuild/CMakeLists.txt
Utilities/new-bootstrap
cmake/modules/FindLLBuild.cmake

This removes the `LLBUILD_FRAMEWORK` option.  Use a proper
FindLLBuild.cmake module that searches for the framework if desired,
allows the user to specify the llbuild to use, or can use the export
targets from an llbuild instance.

build: remove `LLBUILD_FRAMEWORK`, simplify

---

Utilities/bootstrap

This would fail to add rpath if one already exists and we can ignore
that message.

[bootstrap] Suppress stderr from install_name_tool

---

Sources/Build/BuildDelegate.swift
Sources/Commands/Error.swift
Sources/Commands/SwiftTool.swift
Sources/PackageGraph/DependencyResolver.swift
Sources/PackageGraph/Pubgrub.swift
Sources/PackageGraph/RepositoryPackageContainerProvider.swift
Sources/SPMTestSupport/MockDependencyResolver.swift
Sources/SourceControl/RepositoryManager.swift
Sources/TSCBasic/Process.swift
Sources/TSCBasic/Result.swift
Sources/Workspace/ResolverPrecomputationProvider.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphTests/DependencyResolverTests.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/SourceControlTests/RepositoryManagerTests.swift
Tests/TSCBasicTests/AwaitTests.swift
Tests/TSCBasicTests/ResultTests.swift
Tests/TSCBasicTests/XCTestManifests.swift

This is a nice cleanup as `AnyError` is not required since `Result` allows the `Error` protocol to conform to itself. This is required for #2452.

Remove the AnyError type as Error doesn’t need to be erased

---

Sources/Build/BuildPlan.swift
Sources/Build/Triple.swift
Sources/TSCBasic/CMakeLists.txt
Utilities/bootstrap

This pull redoes [the previous tweaks for the old non-CMake bootstrap script](https://github.com/apple/swift-package-manager/pull/2417/files#diff-296aa080a049a48a75c47e0a2926fde0). Since the new bootstrap script rebuilds llbuild by using its Package.swift, rather than the prior approach of linking against the llbuild already built by the Swift build-script, I had problems when building llbuild with SPM because of the C++ modules support.
Removing those flags, as for Windows, gets llbuild and SPM built, with some of those BuildPlanTests now failing, as they explicitly look for that flag.
In the process, I discovered that the `isAndroid()` function I added earlier wasn't working right, as it would only detect `androideabi` and not `android`. As the two appear to be equivalent, with [LLVM …

Android: fix ABI triple detection, disable C++ modules flags, and bring back bootstrap script tweaks

---

Sources/SourceControl/GitRepository.swift
Sources/SourceControl/InMemoryGitRepository.swift
Sources/TSCBasic/FileSystem.swift
Sources/TSCTestSupport/XCTAssertHelpers.swift
Tests/TSCBasicTests/FileSystemTests.swift
Tests/TSCBasicTests/XCTestManifests.swift

This will be necessary for binary targets to move files around after downloading them.

Add copy and move methods to the FileSystem protocol

---

Utilities/bootstrap

We don't require this anymore since we're no longer using testability.

[bootstrap] Don't force enable testability

---

Sources/Build/BuildOperation.swift
Sources/Build/BuildParameters.swift
Sources/Build/BuildPlan.swift
Sources/Commands/SwiftTool.swift
Tests/BuildTests/BuildPlanTests.swift

Rather than passing the number of CPUs everywhere, use the jobs option to limit both the number of llbuild jobs and Swift compiler jobs. @TaborKelly tried to fix this in #2127, but [it was lost when implementing build manifest caching in master](https://github.com/apple/swift-package-manager/commit/87366c916154d80e161e1364d291225798fb51ba#diff-b1d92ba41a0ed8ddabdf8c2604a41504L628), which probably wasn't noticed because it isn't tested.
As this pull applies the same limit to both the number of llbuild jobs and the number of jobs that an instance of the swiftc compiler creates, it's possible that `-j5` will actually spawn 25 compilation processes, ie 5 llbuild swiftc jobs that spawn 5 `swift -frontend` processes each.
Since SPM seems to call the swiftc compiler once for each target and all …

Actually limit build jobs, fixing SR-10325 again

---

Sources/Commands/SwiftPackageTool.swift
Sources/PackageGraph/PinsStore.swift
Sources/PackageGraph/Pubgrub.swift
Sources/PackageModel/Package.swift
Sources/SPMTestSupport/TestWorkspace.swift
Sources/Workspace/Workspace.swift
Tests/PackageGraphTests/PubgrubTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

This adds support for partially updating the package graph. The package update
command will not optionally take a list of package names and only those
packages would be updated. This is done by respecting the entry in
Package.resolved for other packages in the graph. Example invocation:
swift package update Foo Bar Baz

Add support for performing partial package graph updates

---

Package.swift
Utilities/bootstrap

Some of the logic for conditionalization was wrong in our
manifest/bootstrap script. For example, tools support core is cloned
when SWIFTCI_USE_LOCAL_DEPS is set but it's not set when linking llbuild
as a framework. Similarly, we should turn SWIFTPM_BOOTSTRAP to something
better that describes its purpose.
<rdar://problem/58303769>

Properly conditionalize dependencies in Package.swift

---

Utilities/bootstrap

Rather than listing a ton of target triples and platform runtime library paths manually, Ankit suggested getting this info from the new swiftc option instead, apple/swift@61c83d241. Seems to work fine and shouldn't change any behavior ~other than relative rpaths will now be added to SPM shared libraries and executables on some Darwin platforms, [primarily macOS 10.14 or older](https://github.com/apple/swift/blob/23b1a6b87afee535296a786dcdd2a6d0e65d67ef/lib/Basic/Platform.cpp#L57)~.
~However, I have no idea if the Darwin rpath's done right, as I don't use macOS~. @aciidb0mb3r, let me know what you think, can exempt ~Darwin~/Windows from that as before, if wanted.

bootstrap: use the new `swiftc -print-target-info` to get the target triple and runtime library path

---

Utilities/bootstrap

Just in case we end up with a compiler that has this flag but not the
unversionedTriple in the returned JSON.
<rdar://problem/58306196>

[bootstrap] Handle potentially missing 'unversionedTriple' key

---

TSC/CMakeLists.txt
TSC/Sources/TSCBasic/CMakeLists.txt

On platforms where Foundation is not provided by the system and you wish
to build against a custom build of Foundation, you need a number of
flags.  This allows you to instead opt for passing `-DFoundation_DIR=`
and `-Ddispatch_DIR=` to CMake when configuring to pick up those paths.

build: explicitly link against dispatch and Foundation

---

Sources/Build/BuildDelegate.swift

This is being added as part of https://github.com/apple/swift-llbuild/pull/619

Updates usages of ExternalCommand to conform to new signature

---

Sources/Build/Triple.swift

`swift-package-manager` builds for `master-branch` and `swift-5.2-branch` are currently failing on Linux Aarch64 with following error:-
```
File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
"can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/worksonarm_test/jenkins_slave/workspace/swift-master-aarch64/build/buildbot_linux/swiftpm-linux-aarch64/aarch64-unknown-linux-gnu/release/swift-build': doesn't exist or not a regular file
```
Due to the new swiftpm build methods Linux Aarch64 now requires the `-gnu` tag on the triple.
This was adding to x86_64 in https://github.com/apple/swift-package-manager/pull/2353
This is currently causing the build failures on …

Add -gnu in aarch64 Linux's triple

---

TSC/Sources/TSCBasic/ByteString.swift
TSC/Tests/TSCBasicTests/ByteStringTests.swift
TSC/Tests/TSCBasicTests/XCTestManifests.swift

Adds a zero-copy `withData` function to get access to a `Data` instance that wraps the `ByteString`, and a `hexadecimalRepresentation` function.
Both functions are used by the new binary targets implementation.

Add new useful ByteString APIs

---

Sources/PackageLoading/ManifestLoader.swift
Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift

Failing to do so will cause the build to fail when running `swift build`
under certain environments such as tests which don't have PATH set.
Further, it is not valid to invoke xcrun from any other location but
/usr/bin, so we should not spend time looking up a constant.

SPM should always invoke xcrun using an absolute path

---

Sources/PackageDescription/CMakeLists.txt
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/ToolsVersion.swift

Notice that this change requires modifications to `bootstrap` and `ManifestLoader` to make sure the compiled manifest can find the dynamic `PackageDescription` runtime library.

Compile manifests instead of interpreting them

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageModel/Manifest.swift
Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
TSC/Sources/TSCBasic/CollectionAlgorithms.swift
TSC/Sources/TSCBasic/DiagnosticsEngine.swift
TSC/Sources/TSCTestSupport/DiagnosticsEngine.swift
TSC/Sources/TSCUtility/Diagnostics.swift
TSC/Tests/TSCBasicTests/CollectionAlgorithmsTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/PackageLoadingTests/PD5_2LoadingTests.swift
Tests/PackageLoadingTests/PDLoadingTests.swift
Tests/PackageLoadingTests/PDNextLoadingTests.swift

Refactor manifest validation diagnostics to emit all of them when parsing manifests from Workspace, instead of failing on the first one. Also took the opportunity to improve the wording of some of those diagnostics.
For example, the following Package:
```swift
name: "Foo",
products: [
.library(name: "Product", targets: []),
.library(name: "Product", targets: ["A", "C"]),
],
.package(path: "../foo1"),
.package(url: "/foo1.git", from: "1.0.1"),
.package(url: "path/to/foo1", from: "3.0.0"),
.package(url: "/foo2.git", from: "1.0.1"),
.package(url: "/foo2.git", from: "1.1.1"),
.package(url: "/foo3.git", from: "1.0.1"),
],
targets: [
.target(name: "A"),
.target(name: "B"),
.target(name: "A"),
.target(name: "B"),
]
)
```
will now emit the following …

Emit all diagnostics when parsing manifest in Workspace

---

TSC/Sources/TSCTestSupport/DiagnosticsEngine.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/PackageLoadingTests/PD5_2LoadingTests.swift

In some few tests, we could be receiving diagnostics in slightly different order. To improve tests, I've added a function to `DiagnosticsEngineTester` to allow checking for any diagnostic, not only the next in line.

Allow checking diagnostics unordered

---

TSC/Sources/TSCTestSupport/AssertMatch.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

Improved `PackageBuilderTests` by reusing the `DiagnosticsEngineTester`, which allows us to:
* pattern match diagnostic messages with `StringPattern`
* test the diagnostic's behavior and location

Improve PackageBuilder tests by reusing DiagnosticsEngineTester

---

Sources/PackageLoading/ManifestLoader.swift
Sources/SPMLLBuild/llbuild.swift

This will throw instead of crashing if we can't form a build value.
That can happen if we add new properties to the objects that get encoded in
the database but not bump the schema. This change will cause the build
value to be out-of-date and instead force recomputation of the cached
value.
<rdar://problem/51146826>

[SPMLLBuild] Gracefully handle missing data

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

For some reason I thought that we ignored symlinked directories and
baked that logic in the new sources builder. This fixes that regression.
<rdar://problem/58963219>
https://bugs.swift.org/browse/SR-12094

[PackageLoading] Fix a regression in target sources builder

---

Sources/Workspace/WorkspaceState.swift

The `public func restore(from json: JSON, supportedSchemaVersion: Int) throws` function has a default implementation that does nothing: and this is why I missed implementing it. This is a bit dangerous, we might want to do something about it.

[SR-12101] Support migration of old dependencies-state.json

---

Utilities/bootstrap

Previously, we would only care if "CMakeCache.txt" exists, this adds a
check for whether we are using the correct `swiftc`. This resolves an
issue when switching between different versions of Xcode.
<rdar://problem/58680012>

[bootstrap] Reconfigure cmake when swiftc path changes

---

Sources/Build/BuildParameters.swift
Sources/Build/Triple.swift
Sources/Commands/SwiftTool.swift
Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/CommandsTests/BuildToolTests.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/FunctionalPerformanceTests/BuildPerfTests.swift
Tests/FunctionalTests/CFamilyTargetTests.swift
Tests/FunctionalTests/DependencyResolutionTests.swift
Tests/FunctionalTests/MiscellaneousTests.swift
Tests/FunctionalTests/ModuleMapTests.swift
Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift
Tests/FunctionalTests/ToolsVersionTests.swift
Tests/WorkspaceTests/InitTests.swift

I'm not extremely happy of this PR. This feature introduces a cyclic dependency in the SwiftPM types: to generate the host `Triple`, we now need the path to the Swift compiler, which is calculated and stored in a `Toolchain`. The `UserToolchain` used in SwiftPM itself requires the host `Destination`, which requires the host `Triple` :)
I resolved this cyclic dependency by introducing a `getHostTriple(usingSwiftCompiler:)` static function on `Triple` and defining a cached `Triple.hostTriple` extension property in `Workspace` that uses the bare minimum information in the `UserToolchain` static functions to get the path to a Swift compiler.
Please let me know if you think there is a better way.

Use the swift compiler to get the host triple

---

Utilities/bootstrap

This adds the executable relative path to the runtime path selection to
ensure that we use local copies of the libraries to run executables.
Without this, the system libraries would be used which may not have
changes that the tool was built against.

bootstrap: add an `LC_RPATH` relative to the executable

---

Tests/PackageLoadingTests/PD4LoadingTests.swift

This test failed in https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04-long-test/5425
I am not sure what happened but this might help in debugging if this
happens in the future. It might be just the module cache issue >_<
<rdar://problem/58990196>

[PackageLoadingTests] Improve assertion reporting

---

Sources/PackageLoading/PackageBuilder.swift
Sources/PackageLoading/TargetSourcesBuilder.swift
TSC/Sources/TSCBasic/CollectionExtensions.swift
TSC/Tests/TSCBasicTests/CollectionExtensionsTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/XCTestManifests.swift

Since header files are allowed to be mixed with sources, it makes sense
to handle them inside the target sources builder. This allow us to not
special case the public headers directory which can lead to weird edge
cases with previously supported layouts. This patch also adds two more
things 1) diagnostics for duplicate declaration in sources parameter 2)
move the explicit resources check to the vNext tools version as
resources isn't a Swift 5.2 feature.
<rdar://problem/56783465>
(cherry picked from commit a8e5d49ab2d628ca0394bfb84958f6ab4109b3d5)

[PackageLoading] Handle header files in TargetSourcesBuilder

---

Sources/PackageGraph/PackageGraphLoader.swift
Sources/PackageLoading/ManifestLoader.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/PackageModel/Manifest.swift
Sources/SPMTestSupport/TestWorkspace.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageLoadingTests/PD4LoadingTests.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift
Tests/PackageLoadingTests/PD5_2LoadingTests.swift
Tests/PackageLoadingTests/PDLoadingTests.swift
Tests/PackageModelTests/ManifestTests.swift
Tests/WorkspaceTests/WorkspaceTests.swift

Added a missing diagnostic to check that explicit dependency names match the package name and improve the diagnostic for invalid product target dependency references.

Fix an issue and improve diagnostics for target-based dependencies

---

Sources/PackageLoading/ManifestLoader.swift
TSC/Sources/TSCUtility/Diagnostics.swift
Tests/PackageLoadingTests/PD4_2LoadingTests.swift

Fixes two issues:
* Crash when a product references an unknown target in the root package
* Missing diagnostic when failing to load a manifest of a dependency package

Fix issues with diagnostics emitted during manifest loading

---

Utilities/bootstrap

Add `@executable_path/../lib/swift/<platform>` RPATH on Darwin platforms.
This is necessary for experimental toolchains that include libraries not part of the OS (e.g. `PythonKit` or `TensorFlow`).
Verified to fix SwiftPM command linker issues for Swift for TensorFlow toolchains: https://github.com/tensorflow/swift/issues/347.
Effectively reverts https://github.com/apple/swift-package-manager/pull/2548: an unverified fix for the same issue that did not work.
---
Note: previously, `@executable_path/../lib/swift/macosx` was [actually added as an RPATH in `Utilities/bootstrap`](https://github.com/apple/swift-package-manager/pull/2462/files#diff-296aa080a049a48a75c47e0a2926fde0L1302), but the `Utilities/bootstrap ` revamp in https://github.com/apple/swift-package-manager/pull/2462 removed …

[bootstrap] Add RPATH on Darwin.

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift
Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift

Package builder started considering directories inside a target as
a file that can have a rule. However, this wasn't gated behind the tools
version check and we were not handling directories that are explicitly
declared as sources in the package manifest.
<rdar://problem/59243977>
https://bugs.swift.org/browse/SR-12158
(cherry picked from commit 1e15bbb4d399d28ed7d03b4e11cc4c1a720ca2fa)

[PackageLoading] Better handling for directories with extension

---

Sources/PackageGraph/Pubgrub.swift
Sources/SPMTestSupport/TestWorkspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift
Tests/WorkspaceTests/XCTestManifests.swift

Avoid prefetching overriden packages as that will cause us to create and
cache the wrong container kind if an overriden package is present in the
Package.resolved file.
<rdar://problem/59310622>

[Resolver] Don't prefetch overridden packages

---

Sources/PackageLoading/ManifestLoader.swift

Avoid using temporary file in compiled manifest as that opens a file and
causes issues on Linux. We can use a temporary directory and let
compiler do all of the file handling.
<rdar://problem/59472703>
(cherry picked from commit 2500ac0b19026127b750bdcd6b4930441116b075)

[PackageLoading] Use temporary directory when compiling manifest

---

Sources/Build/ManifestBuilder.swift
Sources/LLBuildManifest/BuildManifest.swift

If a package contains only test targets (like Integration Tests), SwiftPM currently fails building it because it generates a manifest with a `defaultTarget` of `main`, but no target called `main` exists as they are lazily created. This change makes it so that SwiftPM always creates `main` and `test` targets, even if they end up empty.

Make sure main and test targets are always created

---

Sources/Commands/SwiftTestTool.swift

When running a local development version of SwiftPM with `—package-path`, the search for `swiftpm-xctest-helper` be relative to the current working directory, which has been changed by `—package-path`. This PR fixes this by looking relative to the original working directory.

Fix search for swiftpm-xctest-helper when debugging

---

Sources/Workspace/Workspace.swift

Now that `ManagedDependencies` is a true collection, this has caused random crashed in `Workspace` where we were mutating managed dependencies while iterating over them. To resolve those crashes, we make a copy of dependencies before iterating over them.

Resolve Dictionary crashes in Workspace

---

Sources/Build/SwiftCompilerOutputParser.swift
Sources/Commands/BuildSystem.swift
Sources/Commands/SwiftTool.swift
Sources/XCBuildSupport/CMakeLists.txt
Sources/XCBuildSupport/XCBuildDelegate.swift
Sources/XCBuildSupport/XCBuildOutputParser.swift
TSC/Sources/TSCUtility/CMakeLists.txt
TSC/Sources/TSCUtility/JSONMessageStreamingParser.swift
TSC/Tests/TSCUtilityTests/JSONMessageStreamingParserTests.swift
Tests/BuildTests/SwiftCompilerOutputParserTests.swift

Added an initial simple implementation for parsing XCBuild output and used it to prettify the `swift build --enable-xcbuild` output.
This builds on top of https://github.com/apple/swift-package-manager/pull/2585, so check the second commit to see the real changes.

XCBuild output parsing

---

TSC/Sources/TSCUtility/ArgumentParser.swift

This PR:
- removes `Bool`'s manual parsing with Swift's `Bool(_:)` initializer
- improves `ShellCompletion` documentation.
Twin of https://github.com/apple/swift-tools-support-core/pull/44

ArgumentKind improvements

---

Sources/Commands/show-dependencies.swift
Tests/CommandsTests/PackageToolTests.swift

`show-dependencies` emits duplicate lines in dot format in some cases. This behavior, for example,  causes wasteful arrows when converted image is drawn.
This PR will fix the issue.
Resolves [SR-12016](https://bugs.swift.org/browse/SR-12016).

[SR-12016] show-dependencies: Don't emit duplicate lines in dot format.

---

Sources/Commands/Options.swift
Sources/Commands/SwiftTool.swift
Sources/Workspace/Destination.swift

This adds command line options to override individual aspects of the destination.
It enables cross‐compilation to be done without the need to write out a separate JSON file, and it simplifies one‐off experiments during testing. It also paves the way for SwiftPM to start looking for things in standard locations based on the supplied triple (but that is not implemented here).
The new options are just as hidden as the original `--destination` option that served as their inspiration.
The aspects of the JSON file not touched on here were already available through other means anyway. (e.g.`-Xswiftc`, `-Xcc`)
[Here](https://github.com/SDGGiesbrecht/swift-package-manager/compare/sdg%E2%80%90ci...sdg%E2%80%90destination%E2%80%90ci) is a diff that also shows the simplification it allows to an …

Cross‐Compilation Overrides

---

Tests/FunctionalTests/ResourcesTests.swift

This flag allows us to control the language instead of it getting picked
up from the system.

[FunctionalTests] Make localization test more robust

---

Utilities/build_ubuntu_cross_compilation_toolchain

This PR enables building code for Linux that uses `zlib` (for instance, [swift-nio-zlib-support](https://github.com/apple/swift-nio-zlib-support)). There’s probably a deeper to-do in here, as `libz-dev` is an alias to `zlib1g-dev` for Ubuntu, but for now this gets things building.

Add zlib to package names

---

Sources/Commands/CMakeLists.txt

On Swift-Foundation targets, FoundationXML is required.  When building
against a custom Foundation and a SDK which does not have Foundation,
FoundationXML will not be tracked properly without the explicit linkage.

Commands: be more explicit about dependencies

---

Sources/Commands/SwiftTestTool.swift

This probably got regressed during the swift-test rework but was caught
by the code coverage integration tests in the swift-integration-tests
repo.
<rdar://problem/59716913>

[Commands] Fix code coverage export

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

<rdar://problem/59725095>
Most of these can be now used when passing --build-system xcode

[PackageLoading] Recognize some Xcode filetypes

---

Sources/PackageGraph/PackageGraphLoader.swift
Tests/PackageGraphTests/PackageGraphTests.swift
Tests/PackageGraphTests/XCTestManifests.swift

The package name validation was wrong for product target dependencies
(`.product(name: "<product>", package: "<package>")`) as we were looking
up the package using its identity instead of the name. This completely
breaks package loading in 5.2 if a package wants to use a product from
a dependency that doesn't match the package name of that dependency.
<rdar://problem/59821906>
(cherry picked from commit e3a880b310e5ded7e19a0f8cb3ca91f5e1e777a9)

[PackageGraph] Fix package name validation for product target dependencies

---

IntegrationTests/Tests/IntegrationTests/BasicTests.swift
Sources/Commands/SwiftTestTool.swift

This improves performance by decreasing the number of spawned XCTest processes & makes the testing results output more convenient – `Executed 100 tests, with 0 failures` will be printed instead of `Executed 1 tests, with 0 failures` 100 times.
This is the next step after https://github.com/apple/swift-corelibs-xctest/pull/268

Execute filtered tests with single XCTest invocation

---

Sources/PackageDescription/SupportedPlatforms.swift
Sources/PackageLoading/PackageDescription4Loader.swift
Sources/PackageModel/Manifest.swift
Tests/CommandsTests/PackageToolTests.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift

This adds a way to express generic "sdk options" in string version of
the platforms API. The idea is that a package might be able to express
some platform-specific options for the underlying build system in
a generic way. Currently, this is just for experimentation purposes and
we might want some other (better, more typesafe) way of allowing
extending the package description language.
<rdar://problem/59788403>

[PackageModel] Add sdk options to platform description

---

TSC/Sources/TSCBasic/Path.swift

This is a NFC commit that paves the way for implementing a `WindowsPath` type that implements windows path management. This required moving some of the logic in `AbsolutePath` into `PathImpl`. Once that was done, it was easy to describe the protocol that each platform type must conform to.

Move all platform path logic into PathImpl and describe it with a protocol

---

Sources/Workspace/Destination.swift
Sources/Workspace/UserToolchain.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This is a further narrowing of #2620. It now only changes anything when building for Android. It merely adds `|| triple.isAndroid()`.
The local variable of `triple` was necessary because `||` involves an implicit closure and would result in an error if the instance property were used directly:
> 'self' captured by a closure before all members were initialized

-sdk for Android (Take 3)

---

TSC/Sources/TSCBasic/OutputByteStream.swift

I've just been reading SPM code and tripped over a possible documentation error.  In TSCBasic.OutputByteStream.swift, lines 296-275, are there two uses of type-safe where thread-safe is intended?

SR-12299: typo in SPM file [TSCBasic.OutputByteStream]

---

Sources/Build/ManifestBuilder.swift
Sources/PackageDescription/SupportedPlatforms.swift
Sources/PackageModel/Platform.swift
Sources/SPMBuildCore/BuildParameters.swift
Sources/SPMBuildCore/Triple.swift
Tests/BuildTests/BuildPlanTests.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

- 2548c5e The main change of this PR adds WebAssembly/WASI variant as platform.
- 6d16075 This change is necessary to make swift-autolink-extract work.
For wasm target, swift-autolink-extract try to extract info from swiftmodule. But without target argument, compiler emits module as Mach-O format on macOS which is not supported by swift-autolink-extract. So SwiftPM need to pass target option when emitting swiftmodule.
This is a part of SR-9307 and [#24684](https://github.com/apple/swift/pull/24684).

WebAssembly Support

---

Sources/PackageLoading/Diagnostics.swift
Sources/PackageLoading/PackageBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

Improve the diagnostics emitted when an executable product doesn’t have exactly one executable target by being more precise depending on if the number of executable targets is 0, and the user probably needs help on how to make a target executable, or if its more than 1, in that case we don’t need to provide that help.

Improve executable product diagnostics

---

Tests/PackageLoadingTests/PD5LoadingTests.swift

The test parses the code below and checks for a `expected ')' in expression list` diagnostic:
```
import PackageDescription
name: "Trivial",
targets: [
.target(
name: "foo",
dependencies: []),
)
```
Prior to the parser fix the invalid targets array literal failed to parse but the error status wasn't propagated up to the containing argument list parsing code, so it produced an additional (and undesirable) missing right token diagnostic that this test was checking for.
```
/tmp/t.swift:9:1: error: expected expression in container literal
)
^
/tmp/t.swift:9:2: error: expected ')' in expression list
)
^
/tmp/t.swift:2:22: note: to match this opening '('
^
```
After the parser fix in https://github.com/apple/swift/pull/30187 lands, we will only …

[test] Update PD5LoadingTests.swift for an upcoming parser fix that suppressed a diagnostic it was checking for.

---

Utilities/bootstrap

The install name didn't used to matter when we were evaluating the
manifests through the Swift interpreter.
<rdar://problem/60635550>

[bootstrap] Use the right install name for PackageDescription

---

Sources/SPMBuildCore/BuildParameters.swift
Sources/SPMBuildCore/Triple.swift
Tests/BuildTests/BuildPlanTests.swift

- Unify the binary path extension logic to `Triple` and reuse the existing `Triple.executableExtension` method.
- Add tests.

Unify binary path extension logic to `Triple`

---

Sources/SPMBuildCore/Triple.swift

Gets rid of allKnown static property of OS enum in favour for allCases from CaseIterable

Gets rid of allKnown static property of OS enum

---

swift-tools-support-core/Sources/TSCBasic/TemporaryFile.swift
swift-tools-support-core/Tests/TSCBasicTests/TemporaryFileTests.swift

Only delete tmpdir when explicitly asked by clients.
https://github.com/apple/swift-tools-support-core/pull/63

[TSCBasic] Don't delete empty tmpdir

---

Sources/SPMTestSupport/TestWorkspace.swift
Sources/SourceControl/InMemoryGitRepository.swift
Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift

`InMemoryGitRepository` is initialized with a path and an in-memory file system where it belongs. It then creates seperate in-memory file systems for each of its commits.
Previously, the contents of the repository in the commit file systems was at the same location as in the working directory file system, which caused issues when cloning the repository to a different location on the file system (in `installHead`).
Now, the contents of the repository in the commit file systems is located at root.

Fix InMemoryGitRepository by expecting its contents to present at root

---

Sources/Commands/SwiftTool.swift

Enable build manifest caching when SWIFTPM_ENABLE_BUILD_MANIFEST_CACHING
is set. We might want to have a general mechanism for enabling
experiemental features in SwiftPM.

[Commands] Allow enabling build manifest caching using env variable

---

Sources/Commands/SwiftPackageTool.swift
Sources/SPMTestSupport/PIFTester.swift
Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/XCBuildSupportTests/PIFBuilderTests.swift
Tests/XCBuildSupportTests/PIFTests.swift

This adds support for Decoding PIF types. The encoder uses
a CodingUserInfoKey named `preservePIFModelStructure` to preseve the
structure that makes it easier to decode the model vs encoding it for
xcbuild consumption.

[XCBuildSupport] Implement Decodable for PIF types

---

Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/XCBuildSupportTests/PIFTests.swift

This just flips the encoding from encoding for XCBuild consumption by
default to encoding the internal structure by default. This is a little
better as clients don't need to worry about providing the right user
info in the normal case of preserving the internal model.

[XCBuildSupport] Preserve PIF structure in default encoding

---

Sources/PackageDescription/PackageDescription.swift
Sources/PackageLoading/ManifestLoader.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift

Manifests can emit output to stdout (useful for debugging purposes).  When switching from an interpreted to a compiled manifest, this output was no longer captured; and more seriously, if enough stdout output was emitted to fill the stdout buffer (or if buffering was disabled), the stdout output would interfere with the emitted JSON.
This change causes the JSON to again be emitted on a separate channel from the stdout, as it was when the manifest was interpreted.

[SR-12553] [ManifestLoader] Capture JSON output from a manifest on a separate pipe than stdout

---

Sources/Build/BuildPlan.swift

When the generated code to load a resource bundle can't find the bundle, it should emit a fatal error rather than crashing the process with a force-unwrap.
I don't see any tests that check that we properly have a fatal error when the bundle can't be loaded at runtime.  Perhaps we should add one?

Don't use force unwrap in the generated bundle accessor for resource bundles

---

Sources/XCBuildSupport/PIF.swift
Sources/XCBuildSupport/PIFBuilder.swift
Tests/XCBuildSupportTests/PIFTests.swift

Sign PIF model in a separate step so it can still by modified after it
is constructed by the PIFBuilder.

[XCBuildSupport] Sign PIF objects out-of-band

---

README.md

I don't think this link is present anywhere else in the repository, but it can be tremendously useful to users when working with Package.swift files.

Add link to PackageDescription API to README.md

---

Sources/Build/BuildPlan.swift

When the generated code to load a resource bundle can't find the bundle, it should emit a fatal error rather than crashing the process with a force-unwrap
(cherry picked from commit 33d4375442f67d254c49b0529e2d0f28a430af73)

[5.3] Don't use force unwrap in the code generated for looking up the module resource bundle

---

Sources/PackageDescription/PackageDescription.swift
Sources/PackageLoading/ManifestLoader.swift
Tests/PackageLoadingTests/PD5LoadingTests.swift

Manifests can emit output to stdout (useful for debugging purposes).  The earlier switch from an interpreted to a compiled manifest caused this output to no longer be captured; and more seriously, if enough stdout output was emitted to fill the stdout buffer (or if buffering was disabled), then the stdout output would interfere with the emitted JSON description of the package manifest.
This change causes the JSON to again be emitted to a separate file so that there is no interference with stdout output, restoring the behavior of when the manifest was interpreted.
There are possible various error conditions that the existing code doesn't handle, and this change doesn't improve on that (it also doesn't make it worse).  A future change should consider making those cases more robust, although …

[5.3] [SR-12553] [ManifestLoader] Capture JSON output from a manifest separately from the stdout

---

Sources/Workspace/Diagnostics.swift
Sources/Workspace/Workspace.swift
Tests/WorkspaceTests/WorkspaceTests.swift

This should be clearer than the original diagnostic and also provides the checksums as part of the message for easy copy-paste if it is simply out of date.

Improve diagnostic for binary checksum mismatch

---

Fixtures/Resources/Localized/Package.swift
Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift

So far we have only been processing resources if they are in a folder that has explicitly been declared as a resource, but we should do it by default.
rdar://problem/61957063

Process any files in .lproj by default

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

SwiftPM 5.2 introduced a regression that caused a semantic change in how package manifests declaring a tools version earlier than 5.3 were parsed.  Specifically, files with an unknown source type are not ignored, as they were in SwiftPM 5.1.x and earlier.  This leads to issues such as the one reported here: https://swiftpm.slack.com/archives/C14QU6CUU/p1587442104122300

Fix a SwiftPM 5.2 regression that cause it to try to compile unknown files in pre-5.3 manifests

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

SwiftPM 5.2 introduced a regression that caused a semantic change in how package manifests declaring a tools version earlier than 5.3 were parsed. Specifically, files with an unknown source type are not ignored, as they were in SwiftPM 5.1.x and earlier. This leads to issues such as the one reported here: https://swiftpm.slack.com/archives/C14QU6CUU/p1587442104122300
This is the 5.3 nomination PR.  The original change is already on master
(cherry picked from commit 3f63a2ddef92c7feaa083b9418b59988fb20426b)

[5.3] Fix a SwiftPM 5.2 regression that cause it to try to compile unknown files in pre-5.3 manifests

---

Sources/PackageLoading/TargetSourcesBuilder.swift
Tests/PackageLoadingTests/PackageBuilderTests.swift

When the source scanning logic was reworked in preparation for support of resources, there was an unintentional change to the semantics of how files with unrecognized filename suffixes under declared source directories were treated.  This caused some existing packages to fail to build, if they use the `sources:` parameter when declaring a target and include at least one file that isn't a recognized source file.
This fix restores the previous semantics of only treating files with recognized source file suffixes as sources.
This fix is already in master as well as in the 5.3 branch, and this is a nomination for fixing it in the 5.2 branch as well, for inclusion in any future 5.2.x release.  This PR should be reviewed and tested, but held pending further discussion and approval.

[5.2] [SR-12667] Fix a SwiftPM 5.2 regression that causes non-source files under declared source directories to be treated as source files
